[translation]
10008-StatusMessageJp = "あぁん！？"
10008-FullNameJp = "美甘ネル"
10008-FamilyNameJp = "美甘"
10008-PersonalNameJp = "ネル"
10008-SchoolYearJp = "3年生"
10008-CharacterAgeJp = "17歳"
10008-BirthdayJp = "8月17日"
10008-HobbyJp = "勝利"
10008-WeaponNameJp = "ツイン・ドラゴン"
10008-WeaponDescJp = "ネルが使用する2丁のサブマシンガン。\n\nどちらにも黄金の龍の美しい文様が刻まれている。"
10008-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、エージェント組織「C&C」のリーダー。\n\n一見してメイド服の上にスカジャンを着たチンピラの子供にしか見えないが、実はミレニアム最強の戦闘能力を持ったエージェントである。そのため彼女のコールサイン「ダブルオー」は、界隈では約束された勝利の象徴とされている。"
10008-CharacterSSRNewJp = "気合い入れろよ。本気でいくぜ！"
