[translation]
100050001-StatusMessageJp = "Tirando uma soneca, não me acorde"
100050001-FullNameJp = "Takanashi Hoshino"
100050001-FamilyNameJp = "Takanashi"
100050001-PersonalNameJp = "Hoshino"
100050001-SchoolYearJp = "3º ano"
100050001-CharacterAgeJp = "17 anos"
100050001-BirthdayJp = "2 de janeiro"
100050001-HobbyJp = "Tirar sonecas, ficar de bobeira"
100050001-WeaponNameJp = "Eye of Horus"
100050001-WeaponDescJp = "Uma escopeta de design simples que Hoshino usa com frequência.\n\nEmbora ela seja preguiçosa por natureza, ela nunca negligencia a manutenção de sua arma."
100050001-ProfileIntroductionJp = "Uma garota preguiçosa que pertence ao Colégio Abydos, onde atua como presidente do conselho estudantil e presidente do comitê de contramedidas.\n\nEla é conhecida por falar como uma pessoa mais velha e prefere brincar a trabalhar. Por causa disso, ela vive levando bronca dos outros membros do comitê, mas quando uma missão começa, ela luta na linha de frente para proteger seus companheiros.\nDesde que aceitou o título de presidente do conselho estudantil, ela tem se tornado mais alegre aos poucos. Talvez essa seja a verdadeira Hoshino."
100050001-CharacterSSRNewJp = "Eu não consegui tirar minha soneca nem um pouco,\nmas bem, fazer o quê?"
