[translation]
10019-StatusMessageJp = "et omnia vanitas"
10019-FullNameJp = "白洲アズサ"
10019-FamilyNameJp = "白洲"
10019-PersonalNameJp = "アズサ"
10019-SchoolYearJp = "2年生"
10019-CharacterAgeJp = "16歳"
10019-BirthdayJp = "12月26日"
10019-HobbyJp = "なし"
10019-WeaponNameJp = "Et Omnia Vanitas"
10019-WeaponDescJp = "アズサが常にしっかりと持っている銃。\n\n銃身には「全ては虚しい。どこまで行こうとも、全てはただ虚しいものだ」という文言が刻まれている。"
10019-ProfileIntroductionJp = "トリニティ総合学園所属、補習授業部の氷の魔女。\n\n本来はある学校を中退した身だったが、諸事情でトリニティへと通うことになり、再び学業に勤しんでいる。性根は寂しがり屋だが、他の人に迷惑をかけることを恐れて自発的に距離を置いており、補習授業部の他の生徒たちから心配されている。"
10019-CharacterSSRNewJp = "全てのものは空しく、生に意味はない\nだけど、信じたくなる……あなたの言葉を"
