[translation]
10015-StatusMessageJp = "ミレニアムのゲーム開発部、アリスです"
10015-FullNameJp = "天童アリス"
10015-FamilyNameJp = "天童"
10015-PersonalNameJp = "アリス"
10015-SchoolYearJp = "1年生"
10015-CharacterAgeJp = "??歳"
10015-BirthdayJp = "3月25日"
10015-HobbyJp = "ゲーム（特にRPG）"
10015-WeaponNameJp = "光の剣：スーパーノヴァ"
10015-WeaponDescJp = "アリスがエンジニア部から譲り受けた巨大なレールガン。\n\nその重さと出力は、普通の生徒たちでは持ち歩くことすら難しいほど。"
10015-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、ゲーム開発部の部員。\n\n廃墟で発見された正体不明の少女で、年齢を含め全ての情報が不詳。現在はモモイやミドリ、ユズと共にゲームを楽しんで、重度のゲームマニアになっている。やや会話がたどたどしかったり不自然な点があるが、それは彼女の発言のほとんどがレトロゲームのセリフで構成されているためである。"
10015-CharacterSSRNewJp = "……その声に喚ばれる時を、ずっと待っていました"
