[translation]
10032-StatusMessageJp = "今年はもっと楽しい一年にしようね♪"
10032-FullNameJp = "浅黄ムツキ"
10032-FamilyNameJp = "浅黄"
10032-PersonalNameJp = "ムツキ"
10032-SchoolYearJp = "2年生"
10032-CharacterAgeJp = "16歳"
10032-BirthdayJp = "7月29日"
10032-HobbyJp = "爆弾収集"
10032-WeaponNameJp = "トリックオアトリック"
10032-WeaponDescJp = "ムツキがいつも持ち歩いているマシンガン。\n\nお正月を迎えて着飾った彼女だが、きちんとその鞄の中には銃が仕舞われている。ムツキ曰くいざとなれば即座に取り出せるようになっており、悪戯には何の支障も無いとのこと。"
10032-ProfileIntroductionJp = "ゲヘナ学園所属、便利屋68の行動隊長兼突撃隊長。\n\n新年を迎えてアルたちと一緒にお参り（遊び）に行くため、装いも新たに。せっかくの新年ということで気合の入った格好になっているものの中身はいつも通りで、悪戯やトラブルを引き起こしてはその様子を笑いながら楽しんでいる。新年になっても相変わらずトラブルに遭いがちなアルのことを、こちらも変わらずにすぐそばの特等席で見ている。それはそれとして彼女なりに正月も楽しんでいるマイペースな小悪魔系少女。"
10032-CharacterSSRNewJp = "くふふっ♪今年も一緒にたくさん遊ぼうね、先生！"
