[translation]
10049-StatusMessageJp = "Sou membro do Clube de Doces depois da aula."
10049-FullNameJp = "Azusa Kazusa"
10049-FamilyNameJp = "Azusa"
10049-PersonalNameJp = "Kazusa"
10049-SchoolYearJp = "1º ano"
10049-CharacterAgeJp = "15 anos"
10049-BirthdayJp = "5 de agosto"
10049-HobbyJp = "Comer doces de um jeito \"normal\""
10049-WeaponNameJp = "Mabinogion"
10049-WeaponDescJp = "Uma metralhadora que acompanha Kazusa há muito tempo.\n\nEla faz uma cara feia sempre que perguntam a origem do nome."
10049-ProfileIntroductionJp = "Membro do \"Clube de Doces depois da aula\" da Academia Trinity, com uma personalidade calma e descontraída.\n\nComo não gosta de se destacar, geralmente apenas segue as outras integrantes em silêncio. Ela sempre acaba se envolvendo nas excentricidades ao seu redor e passando por apuros, mas, por outro lado, valoriza muito esses momentos."
10049-CharacterSSRNewJp = "Ah, Sensei.\nQue coincidência encontrar você por aqui."
