[translation]
10059-StatusMessageJp = "Procurando alguém para conversar comigo!"
10059-FullNameJp = "Misono Mika"
10059-FamilyNameJp = "Misono"
10059-PersonalNameJp = "Mika"
10059-SchoolYearJp = "3º ano"
10059-CharacterAgeJp = "17 anos"
10059-BirthdayJp = "8 de maio"
10059-HobbyJp = "Conversar, colecionar acessórios"
10059-WeaponNameJp = "Quis ut Deus"
10059-WeaponDescJp = "A submetralhadora favorita da Mika.\n\nUma submetralhadora comum fabricada em Trinity, que a Mika decorou com todo o seu carinho. Agora, ela possui uma aparência especial que brilha como uma estrela, mesmo na escuridão. Ela está sempre pronta para entrar em ação pela Mika, a qualquer hora e em qualquer lugar."
10059-ProfileIntroductionJp = "Uma garota da Academia Trinity, ex-líder do \"Pater\", um dos grupos de estudantes que compõem Trinity.\n\nEla é uma das ex-membros do Tea Party e amiga de infância da líder, Nagisa. No entanto, como estão em posições politicamente opostas, ela sabe separar bem o lado público do privado. Embora esteja sempre sorrindo alegremente e pareça inocente, dizem que ela guarda preocupações profundas que não pode contar a ninguém."
10059-CharacterSSRNewJp = "Sim, desculpe a espera!\nDe agora em diante, pode deixar tudo comigo☆"
