[translation]
10101-StatusMessageJp = "Pedidos de ajuda são aceitos a qualquer momento."
10101-FullNameJp = "Joumae Saori"
10101-FamilyNameJp = "Joumae"
10101-PersonalNameJp = "Saori"
10101-SchoolYearJp = "2º ano"
10101-CharacterAgeJp = "17 anos"
10101-BirthdayJp = "3 de setembro"
10101-HobbyJp = "Nenhum"
10101-WeaponNameJp = "Rifle de Assalto de Arius"
10101-WeaponDescJp = "O rifle de assalto usado por Saori.\n\nMesmo em meio a vários trabalhos de meio período, ela o mantém cuidadosamente para que possa atingir seu desempenho original."
10101-ProfileIntroductionJp = "A líder do Esquadrão Arius que continua em busca de si mesma.\n\nPor não conhecer muito sobre o mundo, às vezes ela faz coisas inesperadas, mas encara o trabalho que aceita com sinceridade."
10101-CharacterSSRNewJp = "Qual é a próxima missão?"
