[translation]
10102-StatusMessageJp = "Verão... mar... será que isso é um sonho!?"
10102-FullNameJp = "Tsuchinaga Hiyori"
10102-FamilyNameJp = "Tsuchinaga"
10102-PersonalNameJp = "Hiyori"
10102-SchoolYearJp = "2º ano"
10102-CharacterAgeJp = "16 anos"
10102-BirthdayJp = "8 de janeiro"
10102-HobbyJp = "Colecionar revistas"
10102-WeaponNameJp = "Identidade"
10102-WeaponDescJp = "O rifle de precisão usado por Hiyori.\n\nEmbora ela tenha acabado mirando em prêmios em vez de inimigos, sua precisão continua a mesma."
10102-ProfileIntroductionJp = "Membro do Esquadrão Arius que veio se divertir na praia.\n\nCom o conhecimento que obteve em revistas, ela está ansiosa para aproveitar a praia, mas parece difícil aproveitar 100% devido à sua personalidade negativa."
10102-CharacterSSRNewJp = "O-o local do festival... é aqui?"
