[translation]
10127-StatusMessageJp = "校則は守りましょう……。"
10127-FullNameJp = "桜井ミヨ"
10127-FamilyNameJp = "桜井"
10127-PersonalNameJp = "ミヨ"
10127-SchoolYearJp = "2年生"
10127-CharacterAgeJp = "16歳"
10127-BirthdayJp = "8月24日"
10127-HobbyJp = "タイプライター集め"
10127-WeaponNameJp = "キヴォトス・タイプライター"
10127-WeaponDescJp = "ミヨがいつも持ち歩いているライフル。\n\n彼女の性格もあり、この銃が使われることはほとんどない。弾痕というテキストを記す手段……程度の扱いである。"
10127-ProfileIntroductionJp = "ワイルドハント芸術学院所属、非公認サークル特殊交易部の部長。\n\n目標は部の廃部。気が弱く、他メンバーをうまく止めることができないため、ずるずると活動を続けている。目標達成は当分難しそうだ。"
10127-CharacterSSRNewJp = "私も……ちゃんと恋愛小説家になれるんでしょうか？"
