[translation]
10123-StatusMessageJp = "Chegou a hora de despertar do conto de fadas"
10123-FullNameJp = "Yurizono Seia"
10123-FamilyNameJp = "Yurizono"
10123-PersonalNameJp = "Seia"
10123-SchoolYearJp = "3º ano"
10123-CharacterAgeJp = "17 anos"
10123-BirthdayJp = "29 de setembro"
10123-HobbyJp = "Resolver mistérios, leitura"
10123-WeaponNameJp = "Brilho Aguçado"
10123-WeaponDescJp = "A pistola favorita de Seia.\n\nEmbora suas roupas tenham se tornado mais leves, aquele seu jeito peculiar de falar e seu poder de fogo não diminuíram nem um pouco. Assim como seu novo traje, ela maneja a arma com ousadia."
10123-ProfileIntroductionJp = "Líder do \"Sanctus\", a união de estudantes que compõe a Trinity, atualmente aproveitando suas férias de verão com total tranquilidade na Trinity General School.\n\nEla mudou para o modo de férias e está pronta para aproveitar o verão ao máximo. Embora sempre tenha tido um temperamento tranquilo, parece que um lado ainda mais livre e espontâneo está começando a aparecer."
10123-CharacterSSRNewJp = "Todas as coisas estão em constante mudança... e isso não se limita apenas à aparência."
