[translation]
10137-StatusMessageJp = "機種変したんで、連絡先飛んでまーす"
10137-FullNameJp = "志真 コノカ"
10137-FamilyNameJp = "志真"
10137-PersonalNameJp = "コノカ"
10137-SchoolYearJp = "2年生"
10137-CharacterAgeJp = "16歳"
10137-BirthdayJp = "8月19日"
10137-HobbyJp = "マッサージチェアを使うこと、新聞のクロスワードパズルを解くこと"
10137-WeaponNameJp = "道具"
10137-WeaponDescJp = "コノカ愛用の銃。\n\n業務だけでなく、昼寝の枕として使うなど、使い道は様々だ。"
10137-ProfileIntroductionJp = "ヴァルキューレ警察学校所属、公安局の副局長。\n\n風貌から容疑者と勘違いされることもあるが、有能な警官。犯罪者の心理や行動を公安局の誰よりも上手くトレースできるが、意識してやっているようには見えない。\n\n公安局で最も昇進したことが多く、最も降格されたことの多い生徒でもあるのだとか。"
10137-CharacterSSRNewJp = "ちわーっす、おなしゃーす！"
