[translation]
10145-StatusMessageJp = "緑陰幽草勝花時"
10145-FullNameJp = "竜華キサキ"
10145-FamilyNameJp = "竜華"
10145-PersonalNameJp = "キサキ"
10145-SchoolYearJp = "3年生"
10145-CharacterAgeJp = "17歳"
10145-BirthdayJp = "2月19日"
10145-HobbyJp = "茶道、密行"
10145-WeaponNameJp = "知彼知己"
10145-WeaponDescJp = "キサキが愛用するサブマシンガン。\n\n夏の休暇を満喫していても手放すことはない。"
10145-ProfileIntroductionJp = "夏を迎え水着に着替えた山海経高級中学校所属、生徒会「玄龍門」の門主。\n\n周囲に助けられ、夏のバカンスへ行くことに。体調も普段より良く、より一層解放感を得ている様子。このような自由時間は珍しいため、色々と「楽しむつもり」。"
10145-CharacterSSRNewJp = "この暑さは、どうにも苦手じゃ。"
