[translation]
13003-StatusMessageJp = "ダイエット中……"
13003-FullNameJp = "羽川ハスミ"
13003-FamilyNameJp = "羽川"
13003-PersonalNameJp = "ハスミ"
13003-SchoolYearJp = "3年生"
13003-CharacterAgeJp = "17歳"
13003-BirthdayJp = "12月12日"
13003-HobbyJp = "読書、人間観察"
13003-WeaponNameJp = "インペイルメント"
13003-WeaponDescJp = "ハスミのお気に入りのスナイパーライフル。\n\nどこか古風な良さがあるすらりとした外観と、それに反してかなり激しい威力は、どちらとも持ち主にそっくりである。"
13003-ProfileIntroductionJp = "トリニティ総合学園所属、正義実現委員会のNo.2。\n\n狂乱の象徴である委員長、ツルギの代わりに、正義実現委員会の戦術指揮官の役割も担当している。そのため一見、落ち着いていて知的という「これぞトリニティの生徒」という模範的な生徒にも見えるが、れっきとした正義実現委員会の一員である。誰よりも冷静に、時には無茶な行動をしたりもする。"
