[translation]
16006-StatusMessageJp = "Em uma jornada em busca das iguarias de verão!"
16006-FullNameJp = "Shishidou Izumi"
16006-FamilyNameJp = "Shishidou"
16006-PersonalNameJp = "Izumi"
16006-SchoolYearJp = "2º ano"
16006-CharacterAgeJp = "16 anos"
16006-BirthdayJp = "11 de maio"
16006-HobbyJp = "Comer e preparar pratos exóticos"
16006-WeaponNameJp = "Daily Cutlery"
16006-WeaponDescJp = "Uma metralhadora pesada usada pela Izumi.\n\nSe for pela gastronomia de verão, ela atravessa fogo e água! Com proteção à prova d'água impecável."
16006-ProfileIntroductionJp = "Pertencente à Academia Gehenna, é a garota gulosa do Clube de Pesquisa Gastronômica, que mantém um apetite voraz mesmo no verão escaldante.\n\nCom uma melancia na mão direita e uma caixa térmica na esquerda, ela veio à praia em busca de ainda mais iguarias de verão. Enguia grelhada com sabor de chocolate, raspadinha super apimentada, melancia com cobertura de menta e chocolate... quando o verão chega, não faltam menus peculiares típicos da estação. Sua paixão por buscar todo e qualquer tipo de comida, incluindo essas bizarrices, queima tão intensamente quanto o calor do verão."
