[translation]
16008-StatusMessageJp = "Café combina com rosquinhas!"
16008-FullNameJp = "Nemugaki Fubuki"
16008-FamilyNameJp = "Nemugaki"
16008-PersonalNameJp = "Fubuki"
16008-SchoolYearJp = "1º ano"
16008-CharacterAgeJp = "15 anos"
16008-BirthdayJp = "21 de outubro"
16008-HobbyJp = "Palavras-cruzadas, rádio"
16008-WeaponNameJp = "Rifle Padrão Valkyrie Nº 14"
16008-WeaponDescJp = "O rifle padrão fornecido a Fubuki pela Academia de Polícia Valkyrie.\n\nEmbora possua um alto poder de fogo único, como Fubuki tende a negligenciar sua manutenção, ele acaba não conseguindo demonstrar seu desempenho original."
16008-ProfileIntroductionJp = "Uma aluna preguiçosa do Departamento de Segurança Pública da Academia de Polícia Valkyrie.\n\nIngressou na Academia de Polícia Valkyrie aspirando a uma vida tranquila como funcionária pública. Mesmo quando surgem reclamações no Departamento de Segurança Pública, ela basicamente as trata com uma atitude consistente de falta de sinceridade, aproveitando sua vida como uma funcionária encostada que não se deixa levar por dinheiro ou fama. O que ela mais gosta de fazer é comer rosquinhas enquanto ouve rádio."
