[translation]
16019-StatusMessageJp = "Operação em andamento, pronta para o combate."
16019-FullNameJp = "Asuma Toki"
16019-FamilyNameJp = "Asuma"
16019-PersonalNameJp = "Toki"
16019-SchoolYearJp = "1º ano"
16019-CharacterAgeJp = "16 anos"
16019-BirthdayJp = "16 de agosto"
16019-HobbyJp = "Assistir a transmissões (provisório), jogos (provisório), mangás (provisório)"
16019-WeaponNameJp = "Search & Recon"
16019-WeaponDescJp = "Uma pistola de energia exclusiva da Toki.\n\nSegundo ela, o conceito e a atmosfera foram completamente renovados. Provavelmente, este também é um item essencial para a nova Asuma Toki."
16019-ProfileIntroductionJp = "Membro do Millennium Science School, agente da C&C e responsável de campo do Departamento de Investigação de Fenômenos Singulares.\n\nSua aparência após trocar de roupa para uma missão de reconhecimento. Segundo ela, esta é a \"nova Asuma Toki com mobilidade superior\". Além disso, parece que ela conseguiu encontrar alguns hobbies, ainda que provisórios."
