[translation]
16014-StatusMessageJp = "ゲヘナ学園のイブキです！"
16014-FullNameJp = "丹花イブキ"
16014-FamilyNameJp = "丹花"
16014-PersonalNameJp = "イブキ"
16014-SchoolYearJp = "1年生"
16014-CharacterAgeJp = "11歳"
16014-BirthdayJp = "4月14日"
16014-HobbyJp = "予習・復習、ぬいぐるみ集め"
16014-WeaponNameJp = "バンバーン！ちゃん"
16014-WeaponDescJp = "イブキが大切にしている銃。\n\n「万魔殿」の先輩から受け継いだ制式小銃に、イブキがお気に入りのステッカーを貼ったり、アクセサリーをつけたもの。イブキにとってかけがえのない大切な宝物なのだとか。"
16014-ProfileIntroductionJp = "ゲヘナ学園所属、「万魔殿」の議員であり、マスコット的な少女。\n\n元々ゲヘナ学園初等部所属だったが、能力を認められゲヘナでも優秀な生徒のみが入れるという「万魔殿」に加入した。「万魔殿」の中では最年少だが、ひたむきな可愛さで皆から愛されている。その分、先輩たちの迷惑にならないよう、今日も頑張っている品行方正な女の子。"
