[translation]
16020-StatusMessageJp = "Solidão em meio à multidão"
16020-FullNameJp = "Tenjinyama Otogi"
16020-FamilyNameJp = "Tenjinyama"
16020-PersonalNameJp = "Otogi"
16020-SchoolYearJp = "3º ano"
16020-CharacterAgeJp = "17 anos"
16020-BirthdayJp = "20 de maio"
16020-HobbyJp = "Quebra-cabeças, devaneios"
16020-WeaponNameJp = "Rifle de Precisão Modelo FOX-82"
16020-WeaponDescJp = "Um rifle de precisão padrão fornecido pela Academia SRT.\n\nSua alta capacidade de penetração permite atingir alvos escondidos atrás de coberturas. Além disso, sua alta velocidade de disparo possibilita tiros de ultra longa distância. No entanto, tem a desvantagem de ser extremamente pesado, o que dizem causar dores constantes nos ombros de Otogi."
16020-ProfileIntroductionJp = "Sniper do Esquadrão FOX, pertencente à Academia SRT. Seu codinome é \"FOX4\".\n\nEntre os snipers, que geralmente são lobos solitários, ela é uma presença rara que consegue se enturmar rapidamente mesmo com quem acabou de conhecer. No esquadrão, ela ocupa a posição de animadora.\nNo campo de batalha, ela também desempenha o papel de reduzir o moral do inimigo.\n\nDizem que ela é habilidosa com dispositivos eletrônicos e capaz de consertar equipamentos comuns."
