[translation]
20001-StatusMessageJp = "ターゲットは逃がさない"
20001-FullNameJp = "角楯カリン"
20001-FamilyNameJp = "角楯"
20001-PersonalNameJp = "カリン"
20001-SchoolYearJp = "2年生"
20001-CharacterAgeJp = "16歳"
20001-BirthdayJp = "2月2日"
20001-HobbyJp = "お掃除"
20001-WeaponNameJp = "ホークアイ"
20001-WeaponDescJp = "カリン専用の対物スナイパーライフル。\n\nたとえそれが空を舞う目標でも、正確無比に撃ち落とす。"
20001-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、秘密組織「C&C」のエージェント。\n\nコールサインは「ゼロツー」で、後方からの火力支援を担っている。外見はやや荒っぽそうなものの、実のところC&Cのエージェントの中でも最も慎重な性格の持ち主で、作戦中に暴走しがちなアスナやアカネを止めることに日々苦心している。"
20001-CharacterSSRNewJp = "ご主人様の仰せの通りに"
