[translation]
20005-StatusMessageJp = "新しいペロロ様の浮き輪、見てください！"
20005-FullNameJp = "阿慈谷ヒフミ"
20005-FamilyNameJp = "阿慈谷"
20005-PersonalNameJp = "ヒフミ"
20005-SchoolYearJp = "2年生"
20005-CharacterAgeJp = "16歳"
20005-BirthdayJp = "11月27日"
20005-HobbyJp = "ペロログッズ集め、可愛いもの集め、ショッピング、相談に乗ること"
20005-WeaponNameJp = "マイ・ネセシティ"
20005-WeaponDescJp = "ヒフミがいつも持ち歩いているピンク色のアサルトライフル。\n\n可愛い刻印が刻まれた銃器は、海辺のバカンスにおいても必需品。"
20005-ProfileIntroductionJp = "トリニティ総合学園所属、友人と一緒に海を訪れた、補習授業部の多情多感な少女。\n\n海に行ったことがないというアズサのため、彼女はトリニティのクルセイダー戦車をこっそり盗む（本人曰く「借りる」）というとんでもない行動に出た。しかし案の定、正義実現委員会にバレてしまい、彼女はそれをきっかけに、大きな出来事へと巻き込まれていく。戦車に乗っていてもドジっ子気質は相変わらずで、戦車の力がある分、かえって騒ぎを大きくすることに一役買ってしまっている。"
20005-CharacterSSRNewJp = "えっと……普通の水着、ですよ？"
