[translation]
20019-StatusMessageJp = "少しだけ新しい日常と共に"
20019-FullNameJp = "室笠アカネ"
20019-FamilyNameJp = "室笠"
20019-PersonalNameJp = "アカネ"
20019-SchoolYearJp = "2年生"
20019-CharacterAgeJp = "16歳"
20019-BirthdayJp = "4月1日"
20019-HobbyJp = "お掃除"
20019-WeaponNameJp = "サイレントソリューション"
20019-WeaponDescJp = "アカネが常に所持しているピストル。\n\n潜入任務にはこれ以上なく相応しいモノである。"
20019-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、潜入ミッションのためバニーガール姿へと着替えた「C&C」のエージェント。\n\n不慣れな環境下でも、バニー服を率先して用意したり、C4を爆発させて障害物を片付けるなど、いつもと変わらず落ち着いて作戦を遂行する姿が見られる。普段とは違う服装に少し浮かれているのか、随所にウキウキした表情が垣間見えることも。"
20019-CharacterSSRNewJp = "ご主人様のメイド……\nいえ、今は\nご主人様のウサギ、と申しましょうか"
