[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
20018-StatusMessageJp = "Comprando ativamente mísseis e projéteis que você não usa mais!" 
20018-FullNameJp = "Kazekura Moe" 
20018-FamilyNameJp = "Kazekura" 
20018-PersonalNameJp = "Moe" 
20018-SchoolYearJp = "1º Ano" 
20018-CharacterAgeJp = "15 Anos" 
20018-BirthdayJp = "13 de Setembro" 
20018-HobbyJp = "Fogos de artifício" 
20018-WeaponNameJp = " Pistola RABBIT Tipo-224" 
20018-WeaponDescJp = "Pistola padrão distribuída pela Academia Especial SRT para Moe.\n\nApesar de ser uma pistola de mão, ostenta de uma absurda taxa de tiro, esvaziando o seu carregador inteiro num piscar de olhos." 
20018-ProfileIntroductionJp = "Operadora e apoio tático do Esquadrão RABBIT da Academia Especial SRT. Seu indicativo de chamada (Call Sign) é 'RABBIT 3'.\n\nIngressou na SRT inspirada no colossal e destruidor arsenal bélico e de poder de fogo da academia. No entanto, ela foi subitamente fechada, deixando Moe em uma situação inusitada: morando na rua e dividindo bancos de praça com as garotas do seu esquadrão. Ela tem um fetiche e tara muito esquisitos por explodir e reduzir coisas a poeira, mas as suas habilidades genuínas como operadora beiram à genialidade. Em contrapartida, é incrivelmente viciada em açúcar, sempre tendo que andar por aí com um pirulito grudado na boca." 
20018-CharacterSSRNewJp = "Aqui é RABBIT 3. Qual o alvo pro próximo bombardeio?" 