[translation]
20025-StatusMessageJp = "Que você tenha um ano novo muito feliz e duradouro."
20025-FullNameJp = "Igusa Haruka"
20025-FamilyNameJp = "Igusa"
20025-PersonalNameJp = "Haruka"
20025-SchoolYearJp = "1º ano"
20025-CharacterAgeJp = "15 anos"
20025-BirthdayJp = "13 de maio"
20025-HobbyJp = "Cultivar ervas daninhas"
20025-WeaponNameJp = "Blow Away"
20025-WeaponDescJp = "Uma espingarda que Haruka usa para exterminar \"pragas\" e coisas do tipo.\n\nClaro, ela também é usada quando se trata de exterminar pragas de verdade."
20025-ProfileIntroductionJp = "Uma funcionária comum da Problem Solver 68, da Academia Gehenna, que dá as boas-vindas ao ano novo.\n\nComo não está acostumada a passar o ano novo com pessoas importantes, ela se vestiu com roupas que não costuma usar para tentar se enturmar com todos."
20025-CharacterSSRNewJp = "Este ano também...\nEu vou me esforçar até a morte!!"
