[translation]
23000-StatusMessageJp = "Chocomenta é o melhor!"
23000-FullNameJp = "Kurimura Airi"
23000-FamilyNameJp = "Kurimura"
23000-PersonalNameJp = "Airi"
23000-SchoolYearJp = "1º ano"
23000-CharacterAgeJp = "15 anos"
23000-BirthdayJp = "30 de janeiro"
23000-HobbyJp = "Procurar doces deliciosos, festas de chá"
23000-WeaponNameJp = "Chocomenta Refrescante"
23000-WeaponDescJp = "A submetralhadora da Airi.\n\nDizem que o nome veio do seu doce favorito, encontrado na loja que a Airi costuma frequentar."
23000-ProfileIntroductionJp = "Membro alegre do Clube de Doces Depois da Aula, da Academia Trinity.\n\nPossui uma personalidade descontraída e valoriza acima de tudo o tempo que passa conversando com suas amigas enquanto comem doces. Ela adora sorvete e, ultimamente, tem viciado no sabor de chocomenta."
