[translation]
23003-StatusMessageJp = "急な用件はDMで"
23003-FullNameJp = "小鈎ハレ"
23003-FamilyNameJp = "小鈎"
23003-PersonalNameJp = "ハレ"
23003-SchoolYearJp = "2年生"
23003-CharacterAgeJp = "16歳"
23003-BirthdayJp = "4月19日"
23003-HobbyJp = "ゲーム, 映画鑑賞"
23003-WeaponNameJp = "オートエイマー"
23003-WeaponDescJp = "ハレが使用するアサルトライフル。\n\n自動照準機能を始めとした様々な最先端の機能が搭載されているが、ほとんど使ってない様子。"
23003-ProfileIntroductionJp = "ミレニアムサイエンススクール所属、ハッカー集団「ヴェリタス」のエンジニア。\n\n頭の良い人が多いことで有名なミレニアムにおいても頭一つ抜けている屈指の天才少女。ミレニアムで生み出される最先端の機器のほとんどは、彼女の手によって開発されている。しかしその実力や成果にも関わらず、自慢したり威張ったりすることなく、他の生徒たちとも交流し、良く話しを聞いてくれる優しい女の子である。"
