[translation]
26008-StatusMessageJp = "Franquia Hyakkiyako em pleno funcionamento!"
26008-FullNameJp = "Kawa Shizuko"
26008-FamilyNameJp = "Kawa"
26008-PersonalNameJp = "Shizuko"
26008-SchoolYearJp = "2º ano"
26008-CharacterAgeJp = "16 anos"
26008-BirthdayJp = "7 de julho"
26008-HobbyJp = "Atender clientes de forma fofa, soco de garota-propaganda"
26008-WeaponNameJp = "Sakura Bonbon"
26008-WeaponDescJp = "Uma espingarda de ação por bombeamento que Shizuko usa até mesmo na praia durante o verão.\n\nComo sempre, um leve aroma doce de anmitsu paira sobre ela."
26008-ProfileIntroductionJp = "Membro da Academia Hyakkiyako e presidente do Comitê de Operações de Festivais, que continua cheia de ambição mesmo no verão.\n\nEla dedica sua paixão hoje, como sempre, para transformar a Hyakkiyado na maior franquia de Kivotos. Nenhum obstáculo é um problema se ela estiver com seu soco de ídolo. A garota do verão é invencível e agarrará tudo o que estiver ao seu alcance."
