[translation]
10025-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ！"
10025-CVGroup_CharacterGet_Idle1-1 = "こっ、子供扱いしないでください……！\nこれでも心は変わらず、みんなのお姉さんですから！"
10025-CVGroup_Cafe_Idle1-1 = "（この視線で見るカフェは、何だか不思議ですね……）"
10025-CVGroup_Cafe_Idle2-1 = "うーん……\nこの身長だと、みんなにとっても少し不便かもしれません。"
10025-CVGroup_Cafe_Idle3-1 = "（も、もう少し……背伸びをすれば、何とか……！）"
10025-CVGroup_Cafe_Idle4-1 = "んん……眠くなってきました……。"
10025-CVGroup_Cafe_Idle5-1 = "今はせっかくこういう身体ですし……\nお昼寝、しても良いですよね？"
10025-CVGroup_WeaponGet_Idle1-1 = "今の私には少し大きい気もしますが……\nでもやっぱりこの武器が一番です！"
10025-CVGroup_UIEventLobby_Enter1-1 = "お散歩にぴったりのお天気ですねっ。"
10025-CVGroup_UIEventLobby_Enter2-1 = "今日は私が、山海経を案内しますねっ！"
10025-CVGroup_UIEventLobby_Idle1-1 = "しゅ、シュンお姉さんはどこに行ったんでしょうね……？"
10025-CVGroup_UIEventLobby_Idle2-1 = "（ま、まだバレてませんよね……？）"
10025-CVGroup_UIEventLobby_Idle3-1 = "先生、あそこに美味しそうなお菓子がいっぱいあります！"
10025-CVGroup_UIEventLobby_Idle4-1 = "（ふふっ。この身体も、それほど悪くないですね）"
10025-CVGroup_UIEventMission_Enter1-1 = "おかえりなさい、です！\n先生！今日の授業もよろしくお願いします！"
10025-CVGroup_UIEventMission_Idle1-1 = "ふふっ、このサイズも時には便利ですね！"
10025-CVGroup_UIEventMission_Idle2-1 = "んん……眠くなってきました……。"
10025-CVGroup_UIEventMission_Buy1-1 = "ありがとうございます！"
10025-CVGroup_UIEventMission_Buy2-1 = "ふふ。ありがとうございます、先生。"
10025-CVGroup_UIEventMission_Interaction1-1 = "ふふっ、また一緒に遊びましょうね、先生！"
