[translation]
10038-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ。"
10038-CVGroup_CharacterGet_Idle1-1 = "SRT特殊学園、RABBIT小隊の月雪ミヤコです。\n先生、ご指示を。"
10038-CVGroup_Cafe_Idle1-1 = "……可愛い飾りを発見しました。"
10038-CVGroup_Cafe_Idle2-1 = "これぐらいの空間なら、\n私一人でも制圧できそうな……。"
10038-CVGroup_Cafe_Idle3-1 = "こんなところに狙撃ポイントが……。"
10038-CVGroup_Cafe_Idle4-1 = "……受信中、感度良好。"
10038-CVGroup_Cafe_Idle5-1 = "何か問題でもありましたか？"
10038-CVGroup_WeaponGet_Idle1-1 = "RABBIT31式短機関銃、確かに受け取りました。\n……可愛い。"
