[translation]
10041-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10041-CVGroup_CharacterGet_Idle1-1 = "……Misaki, do Esquadrão Arius.\nAgora sou como um cão de caça sem dono, então……\nAqui está a coleira. Pode me dar as ordens que quiser."
10041-CVGroup_Cafe_Idle1-1 = "Está um pouco barulhento aqui."
10041-CVGroup_Cafe_Idle2-1 = "……Tudo aqui é novidade para mim."
10041-CVGroup_Cafe_Idle3-1 = "……Isso é divertido?"
10041-CVGroup_Cafe_Idle4-1 = "Não tenho interesse."
10041-CVGroup_Cafe_Idle5-1 = "……O que você está fazendo?"
10041-CVGroup_WeaponGet_Idle1-1 = "Não vou perguntar o motivo, mas me entregar algo assim...\nNo mundo que eu conhecia, não existiam pessoas como você. Que estranho.\n……Vou confiar este poder a você, Sensei, por enquanto."
