[translation]
10048-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10048-CVGroup_CharacterGet_Idle1-1 = "Sou a Saori, do Esquadrão Arius.\n……Sensei, você cuidou de mim de várias formas.\nPelo menos farei o meu trabalho para compensar isso. Conto com você."
10048-CVGroup_Cafe_Idle1-1 = "Hmm……."
10048-CVGroup_Cafe_Idle2-1 = "Não estou acostumada com lugares assim……."
10048-CVGroup_Cafe_Idle3-1 = "O que é isso……?"
10048-CVGroup_Cafe_Idle4-1 = "Não consigo entender……."
10048-CVGroup_Cafe_Idle5-1 = "Entendo, então é para isso que serve……."
10048-CVGroup_WeaponGet_Idle1-1 = "Por que você…… confia em mim?\nMesmo depois de tudo o que aconteceu…… você não se importa se eu te trair?\nAinda há muitas coisas que não entendo, mas mesmo assim…… farei o meu melhor."
