[translation]
10058-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10058-CVGroup_CharacterGet_Idle1-1 = "Sou Aomori Mine, capitã do Esquadrão de Primeiros Socorros.\nQuem aqui precisa de atendimento médico?"
10058-CVGroup_Cafe_Idle1-1 = "Há alguém... que precise de ajuda médica?"
10058-CVGroup_Cafe_Idle2-1 = "Este lugar... é muito relaxante."
10058-CVGroup_Cafe_Idle3-1 = "Que tal organizarmos uma festa do chá aqui?"
10058-CVGroup_Cafe_Idle4-1 = "Todos precisam de descanso.\nClaro, inclusive o Esquadrão de Primeiros Socorros."
10058-CVGroup_Cafe_Idle5-1 = "Para a saúde e a beleza, uma xícara de chá após as refeições."
10058-CVGroup_WeaponGet_Idle1-1 = "Agradeço pela sua consideração.\n...Dedicarei tudo o que tenho para ser útil ao Sensei."
