[translation]
10052-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10052-CVGroup_CharacterGet_Idle1-1 = "Sou a secretária do Seminar, Ushio Noa.\nConto com você, Sensei... em vários aspectos, sim."
10052-CVGroup_Cafe_Idle1-1 = "(Este café parece um sonho que sonhadores teriam...)"
10052-CVGroup_Cafe_Idle2-1 = "(Vamos esquecer um pouco a realidade entediante e nos entregar a um devaneio.)"
10052-CVGroup_Cafe_Idle3-1 = "Eu gostaria de instalar este móvel na sala de descanso do Seminar. Fufu."
10052-CVGroup_Cafe_Idle4-1 = "A estrutura deste espaço... é impressionante."
10052-CVGroup_Cafe_Idle5-1 = "Fufu, eu adoraria mostrar esta cena\npara a Yuuka-chan também."
10052-CVGroup_WeaponGet_Idle1-1 = "Este kit de conversão tem uma estrutura curiosa.\nFiquei com vontade de... testar várias coisas. Fufu."
10052-CVGroup_UIEventLobby_Enter1-1 = "Então, vamos começar os preparativos para o 'Festival Esportivo de Halo'."
10052-CVGroup_UIEventLobby_Enter2-1 = "Vamos nos esforçar para não nos atrasarmos para a cerimônia de abertura!"
10052-CVGroup_UIEventLobby_Enter3-1 = "(Bem... o que preciso preparar a seguir é...)"
10052-CVGroup_UIEventLobby_Enter4-1 = "Falta pouco para o início do 'Festival Esportivo de Halo'."
10052-CVGroup_UIEventLobby_Enter4-2 = "Por favor, dê o seu melhor até o fim."
10052-CVGroup_UIEventLobby_Enter5-1 = "Bom trabalho, Sensei.\nComo todos nos unimos para preparar tudo,"
10052-CVGroup_UIEventLobby_Enter5-2 = "este 'Festival Esportivo de Halo' certamente será divertido."
10052-CVGroup_UIEventLobby_Idle1-1 = "É um festival que atrai a atenção de todo o Kivotos,"
10052-CVGroup_UIEventLobby_Idle1-2 = "então farei o meu melhor para mostrar o verdadeiro valor do Millennium!"
10052-CVGroup_UIEventLobby_Idle2-1 = "Não sou muito boa com exercícios, mas..."
10052-CVGroup_UIEventLobby_Idle2-2 = "isso também é, de certa forma, um trabalho do Seminar."
10052-CVGroup_UIEventLobby_Idle3-1 = "(...Então nem todos estão ansiosos pelo festival, não é...)"
10052-CVGroup_UIEventLobby_Idle4-1 = "Quando a Yuuka-chan acordar, com certeza será uma tempestade de reclamações."
10052-CVGroup_UIEventLobby_Idle4-2 = "Fufu... já estou ansiosa para ver a Yuuka-chan em pânico."
10052-CVGroup_UIEventMission_Enter1-1 = "Aqui está a lista de tarefas necessárias para os preparativos do 'Festival Esportivo de Halo'."
10052-CVGroup_UIEventMission_Enter2-1 = "Ah, que bom que você apareceu!\nTem um trabalho que eu gostaria que o Sensei fizesse..."
10052-CVGroup_UIEventMission_Idle1-1 = "Hm? O que houve?"
10052-CVGroup_UIEventMission_Idle2-1 = "Fufu, não pode.\nEstou ocupada agora... depois eu te dou atenção."
10052-CVGroup_UIEventMission_Buy1-1 = "Como esperado do Sensei.\nAprendi muito."
10052-CVGroup_UIEventMission_Buy2-1 = "Que bom trabalho.\nFiquei impressionada."
10052-CVGroup_UIEventMission_Interaction1-1 = "O trabalho aqui terminou por enquanto.\nAgradeço pela sua colaboração."
