[translation]
10076-CVGroup_UITitle_Idle1-1 = "Blue! Archive!"
10076-CVGroup_CharacterGet_Idle1-1 = "Se precisar de explicações ou apoio, pode deixar comigo!"
10076-CVGroup_Cafe_Idle1-1 = "Oh! Quanta gente aqui!?"
10076-CVGroup_Cafe_Idle2-1 = "Talvez eu até consiga dar uma palestra aqui!?"
10076-CVGroup_Cafe_Idle3-1 = "A decoração do Sensei... é muito interessante!"
10076-CVGroup_Cafe_Idle4-1 = "Ora, aquilo é...!"
10076-CVGroup_Cafe_Idle5-1 = "Já que estamos aqui, que tal procurarmos um palco para torcer?"
10076-CVGroup_WeaponGet_Idle1-1 = "Permita-me explicar sobre esta arma...!\n...Hehe, brincadeira. O Sensei já sabe, não é?\n...Se as coisas continuarem aumentando assim, algum dia..."
10076-CVGroup_UIEventLobby_Enter1-1 = "Para apoio e explicações, pode deixar comigo!"
10076-CVGroup_UIEventLobby_Enter2-1 = "Rah, rah! Sen-sei!\nForça, força! Sensei!"
10076-CVGroup_UIEventLobby_Enter2-2 = "O que achou? Se sentiu mais animado?"
10076-CVGroup_UIEventLobby_Enter3-1 = "Está bem animado, não é?\nDê o seu melhor!"
10076-CVGroup_UIEventLobby_Enter4-1 = "Falta pouco!\nEstarei torcendo até o fim!"
10076-CVGroup_UIEventLobby_Enter5-1 = "Ufa... foi difícil, não foi?"
10076-CVGroup_UIEventLobby_Enter5-2 = "Mas sinto que cumprimos o nosso dever!"
10076-CVGroup_UIEventLobby_Idle1-1 = "Ah, aconteceu alguma coisa?"
10076-CVGroup_UIEventLobby_Idle2-1 = "Tem algo que está te preocupando?"
10076-CVGroup_UIEventLobby_Idle2-2 = "Se for isso, eu mesma..."
10076-CVGroup_UIEventLobby_Idle3-1 = "A-assim, cutucando tantas vezes..."
10076-CVGroup_UIEventLobby_Idle3-2 = "É um pouco vergonhoso..."
10076-CVGroup_UIEventLobby_Idle4-1 = "Iiiih!?\nAh, é-é você, Sensei...!"
