[translation]
10088-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10088-CVGroup_CharacterGet_Idle1-1 = "Olá.\nEu não estou muito... acostumada a usar isso, então me desculpe se estiver um pouco estranho...\nConto com você, Sensei."
10088-CVGroup_Cafe_Idle1-1 = "Você tem um bom gosto."
10088-CVGroup_Cafe_Idle2-1 = "Sinto como se estivessem me observando..."
10088-CVGroup_Cafe_Idle3-1 = "...Hmm. Então o Sensei gosta desse tipo de coisa?"
10088-CVGroup_Cafe_Idle4-1 = "...De alguma forma, isso é relaxante."
10088-CVGroup_Cafe_Idle5-1 = "Será que tem algum lugar onde eu possa sentar?"
10088-CVGroup_WeaponGet_Idle1-1 = "Às vezes eu penso. Eu recebi tantas coisas até agora, mas...\nSerá que eu consigo retribuir tudo isso?\nMas... como esse dia provavelmente nunca chegará, vou dizer logo de uma vez.\n...Obrigada, Sensei. De agora em diante... eu vou me esforçar."
10088-CVGroup_UIEventLobby_Enter1-1 = "Eu estava te esperando, Sensei.\nO que devemos fazer?"
10088-CVGroup_UIEventLobby_Enter2-1 = "...Ah, eu estava justamente te procurando, Sensei."
10088-CVGroup_UIEventLobby_Enter3-1 = "Estamos surpreendentemente ocupados, né?\nVamos começar logo."
10088-CVGroup_UIEventLobby_Enter4-1 = "Estamos em cima da hora.\nMas não se preocupe, eu vou ajudar."
10088-CVGroup_UIEventLobby_Enter5-1 = "Vou começar a arrumar tudo."
10088-CVGroup_UIEventLobby_Idle1-1 = "...Sim? Me chamou?"
10088-CVGroup_UIEventLobby_Idle2-1 = "Sensei... não é hora de brincadeiras."
10088-CVGroup_UIEventLobby_Idle3-1 = "Haa... deixe para brincar depois que o trabalho terminar."
10088-CVGroup_UIEventLobby_Idle4-1 = "Não que eu me importe com as brincadeiras em si, mas..."
10088-CVGroup_UIEventLobby_Idle4-2 = "Eu preferiria que parasse agora."
10088-CVGroup_UIEventShop_Enter1-1 = "Você precisa de suprimentos, né?\nEstão aqui."
10088-CVGroup_UIEventShop_Enter2-1 = "Se precisar de algo, é só falar.\nEu vou buscar."
10088-CVGroup_UIEventShop_Enter3-1 = "O trabalho terminou, mas...\nEsqueceu de alguma coisa?"
10088-CVGroup_UIEventShop_Idle1-1 = "Se você me disser exatamente o que é, eu procuro para você."
10088-CVGroup_UIEventShop_Idle2-1 = "Sensei...\nIsso faz cócegas."
10088-CVGroup_UIEventShop_Buy1-1 = "Então era isso que você precisava."
10088-CVGroup_UIEventShop_Buy2-1 = "Estava aqui.\nTenho certeza de que será útil."
10088-CVGroup_UIEventShop_Buy3-1 = "Que bom que encontramos algo perfeito."
10088-CVGroup_UIEventShop_Buy4-1 = "Boa escolha."
10088-CVGroup_UIEventMission_Enter1-1 = "Organizei as tarefas em andamento.\nVamos dar uma olhada juntos, Sensei."
10088-CVGroup_UIEventMission_Enter2-1 = "Veio verificar o progresso?"
10088-CVGroup_UIEventMission_Idle1-1 = "Sensei... espere um pouco..."
10088-CVGroup_UIEventMission_Idle2-1 = "...É bom trabalhar com você, Sensei."
10088-CVGroup_UIEventMission_Buy1-1 = "Certo, resolvido."
10088-CVGroup_UIEventMission_Buy2-1 = "Nada mal."
10088-CVGroup_UIEventMission_Interaction1-1 = "O trabalho de hoje terminou."
