[translation]
10080-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ。"
10080-CVGroup_CharacterGet_Idle1-1 = "あら、自己紹介はしたはずだけど……\nもしかして覚えてないのかしら？うふふっ。"
10080-CVGroup_Cafe_Idle1-1 = "あら、なかなか可愛いインテリアじゃない？"
10080-CVGroup_Cafe_Idle2-1 = "センスあるじゃない。"
10080-CVGroup_Cafe_Idle3-1 = "面白そうな子が多いわねぇ。"
10080-CVGroup_Cafe_Idle4-1 = "なんだか……落ち着くかも。"
10080-CVGroup_Cafe_Idle5-1 = "気を使わなくていい場所だからかしら……\n悪くないわね。"
10080-CVGroup_WeaponGet_Idle1-1 = "あなたも変わってるわねぇ。ああ、悪い意味では無いのよぉ。\n……普通は頭の中を読んでない相手のことなんて、信じないんだけど……\n疑ってない程度、って事にしておこうかしら？"
10080-CVGroup_UIEventLobby_Enter1-1 = "待ってたわよぉ、先生。\nそれじゃ始めましょうか？"
10080-CVGroup_UIEventLobby_Enter2-1 = "なにか手伝いましょうかぁ？"
10080-CVGroup_UIEventLobby_Enter2-2 = "これはコッチの話だから、協力するゾ☆"
10080-CVGroup_UIEventLobby_Enter3-1 = "うまくいってる～？"
10080-CVGroup_UIEventLobby_Enter4-1 = "そろそろ終わりが見えてきたかしら？"
10080-CVGroup_UIEventLobby_Enter5-1 = "やり残したことはないか、\nもう一回確認してみるといいゾ☆"
10080-CVGroup_UIEventLobby_Idle1-1 = "へぇ？そういう事しちゃうんだぁ。"
10080-CVGroup_UIEventLobby_Idle2-1 = "他にやることがあるんじゃなぁい？"
10080-CVGroup_UIEventLobby_Idle3-1 = "……私の我慢にも限界があるんだゾ☆"
10080-CVGroup_UIEventLobby_Idle4-1 = "……あらあら。\nこれ、大丈夫かしらぁ？"
10080-CVGroup_UIEventMission_Enter1-1 = "進捗を確認してみましょうかぁ。"
10080-CVGroup_UIEventMission_Enter2-1 = "確認にきたのねぇ。\n何か手伝いましょうかぁ？"
10080-CVGroup_UIEventMission_Idle1-1 = "諦め、って言葉を知らない感じかしらぁ？"
10080-CVGroup_UIEventMission_Idle2-1 = "へぇ……？"
10080-CVGroup_UIEventMission_Buy1-1 = "なかなか頑張ったんじゃなぁい？\n褒めてつかわすゾ☆"
10080-CVGroup_UIEventMission_Buy2-1 = "少しは役に立んじゃなぁい？"
