[translation]
10098-CVGroup_UITitle_Idle1-1 = "……ブルーアーカイブ。"
10098-CVGroup_CharacterGet_Idle1-1 = "いやー、大事になっちゃったね～\nこれは……おじさんが出なきゃいけないね。"
10098-CVGroup_Cafe_Idle1-1 = "（遮蔽物……確認。出口……確認）"
10098-CVGroup_Cafe_Idle2-1 = "とりあえず、弾薬を確認しよう。"
10098-CVGroup_Cafe_Idle3-1 = "うへ……気が休まらないなぁ……\nこんな時は、先生に会いたいかも……。"
10098-CVGroup_Cafe_Idle4-1 = "この髪型、たしかに楽だけど……\n変じゃないかなぁ。"
10098-CVGroup_Cafe_Idle5-1 = "今日は昼寝する気にならないなぁ……。"
10098-CVGroup_WeaponGet_Idle1-1 = "……おじさんの力が必要になったら、いつでも言うんだよ？\n先生のことは、いつだって最優先だからさ。"
