[translation]
10101-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10101-CVGroup_CharacterGet_Idle1-1 = "Então este é o local de trabalho desta vez... É minha primeira vez no mar, mas pode deixar comigo."
10101-CVGroup_Cafe_Idle1-1 = "Tudo bem se eu praticar aqui?"
10101-CVGroup_Cafe_Idle2-1 = "Aquele enfeite... acho que combinaria com a Atsuko."
10101-CVGroup_Cafe_Idle3-1 = "Este lugar é barulhento. Talvez não seja adequado para a Misaki."
10101-CVGroup_Cafe_Idle4-1 = "Um café, hein... Espero encontrar a revista favorita da Hiyori por aqui."
10101-CVGroup_Cafe_Idle5-1 = "Tenho certeza de que o livro de contas estava aqui..."
10101-CVGroup_WeaponGet_Idle1-1 = "O futuro é incerto, mas posso afirmar uma coisa: este símbolo de confiança que recebi do Sensei... vou cuidar dele até o fim."
10101-CVGroup_UIEventLobby_Enter1-1 = "O próximo trabalho é..."
10101-CVGroup_UIEventLobby_Enter1-2 = "Ah, Sensei, precisa de ajuda com alguma coisa?"
10101-CVGroup_UIEventLobby_Enter2-1 = "B-bem-vindo! Quantas pessoas..."
10101-CVGroup_UIEventLobby_Enter2-2 = "...Ah, era você, Sensei. Desculpe, foi reflexo."
10101-CVGroup_UIEventLobby_Enter3-1 = "O trabalho de meio período ainda não acabou."
10101-CVGroup_UIEventLobby_Enter3-2 = "Vamos manter o foco até o fim."
10101-CVGroup_UIEventLobby_Enter4-1 = "O festival está chegando ao fim. Você se divertiu, Sensei?"
10101-CVGroup_UIEventLobby_Enter5-1 = "O trabalho desta vez também terminou em segurança."
10101-CVGroup_UIEventLobby_Enter5-2 = "Graças ao Sensei. Sou muito grata."
10101-CVGroup_UIEventLobby_Idle1-1 = "O mar é... vasto e infinito, e tem uma quantidade surpreendente de água."
10101-CVGroup_UIEventLobby_Idle1-2 = "Fiquei impressionada."
10101-CVGroup_UIEventLobby_Idle2-1 = "Se eu tivesse um pouco mais de tempo, poderia ter melhorado a perfeição do palco..."
10101-CVGroup_UIEventLobby_Idle3-1 = "A brisa do mar é refrescante."
10101-CVGroup_UIEventLobby_Idle3-2 = "É perfeita para aliviar o calor."
10101-CVGroup_UIEventLobby_Idle4-1 = "Farei o meu melhor para que este festival seja divertido."
10101-CVGroup_UIEventLobby_Idle4-2 = "Sensei, por favor, aproveite o festival também."
10101-CVGroup_UIEventMiniGameMission_Enter1-1 = "Desculpe, Sensei, mas me empreste um pouco da sua força."
10101-CVGroup_UIEventMiniGameMission_Enter1-2 = "Não consigo dar conta de tudo sozinha."
10101-CVGroup_UIEventMiniGameMission_Enter2-1 = "Esta é a lista de tarefas de hoje. Sensei, pode me ajudar?"
10101-CVGroup_UIEventMiniGameMission_Idle1-1 = "Sou alguém que se sustenta com trabalhos de meio período."
10101-CVGroup_UIEventMiniGameMission_Idle1-2 = "Preciso gerenciar bem as demandas de trabalho."
10101-CVGroup_UIEventMiniGameMission_Idle2-1 = "S-Sensei, precisa de mim?"
10101-CVGroup_UIEventMiniGameMission_Buy1-1 = "Obrigada pela ajuda. Você é muito eficiente, Sensei."
10101-CVGroup_UIEventMiniGameMission_Buy2-1 = "Você já terminou...?"
10101-CVGroup_UIEventMiniGameMission_Buy2-2 = "Como agradecimento, aceite isto..."
10101-CVGroup_UIEventMiniGameMission_Interaction1-1 = "Por hoje é só. Agradeço pela colaboração."
10101-CVGroup_UIEventMiniGameMission_Interaction1-2 = "Sensei, gostaria de tomar alguma coisa comigo?"
