[translation]
10106-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ。"
10106-CVGroup_CharacterGet_Idle1-1 = "ふふっ、驚きましたか？\nいかがでしょう……\nこれまでの私とは、違うのですよ？"
10106-CVGroup_Cafe_Idle1-1 = "も、もしかして私だと\n気づかれているのでしょうか……？"
10106-CVGroup_Cafe_Idle2-1 = "歌ってしまったほうが良いのでしょうか……？"
10106-CVGroup_Cafe_Idle3-1 = "なんだか、浮足立って落ち着かない心地です。"
10106-CVGroup_Cafe_Idle4-1 = "ふふ……少しスッキリしますね。"
10106-CVGroup_Cafe_Idle5-1 = "もしかして……\n見られているのでしょうか？"
10106-CVGroup_WeaponGet_Idle1-1 = "私に、それを……？\nいえ、どのような格好でも私は私。\n仰るとおりですね。謹んで頂戴いたします。\nありがとうございます、先生。"
10106-CVGroup_UIEventLobby_Enter1-1 = "あーあーあーあー"
10106-CVGroup_UIEventLobby_Enter1-2 = "あっ……せ、先生！？"
10106-CVGroup_UIEventLobby_Enter2-1 = "お越し下さりありがとうございます、先生。"
10106-CVGroup_UIEventLobby_Enter2-2 = "さ、サクラコ、嬉しいです！"
10106-CVGroup_UIEventLobby_Enter3-1 = "もう半分が過ぎてしまったのですね……。"
10106-CVGroup_UIEventLobby_Enter4-1 = "素晴らしい時間はあっという間とは申しますが……"
10106-CVGroup_UIEventLobby_Enter4-2 = "あまりにも一瞬で過ぎ去ってしまったような心地です。"
10106-CVGroup_UIEventLobby_Enter5-1 = "ふふっ、名残惜しいのですか？"
10106-CVGroup_UIEventLobby_Enter5-2 = "……偶然ですね、私もです。"
10106-CVGroup_UIEventLobby_Idle1-1 = "先生、何か御用でしょうか？"
10106-CVGroup_UIEventLobby_Idle1-2 = "……あ、握手……でしょうか？"
10106-CVGroup_UIEventLobby_Idle2-1 = "シスター服の時よりも、\n皆さんと親密になれた気がします。"
10106-CVGroup_UIEventLobby_Idle2-2 = "ふふっ、この服装も良いものですね。"
10106-CVGroup_UIEventLobby_Idle3-1 = "その……何か御用があるのでしょうか？"
10106-CVGroup_UIEventLobby_Idle3-2 = "何度も呼ばれると……\nその、何をすれば良いのか分かりません。"
10106-CVGroup_UIEventLobby_Idle4-1 = "練習中のとっておきの振り付けがあるのですが……"
10106-CVGroup_UIEventLobby_Idle4-2 = "よ、よろしければご覧になりますか？"
10106-CVGroup_UIEventMission_Enter1-1 = "先生の業務を\nまとめておきました。"
10106-CVGroup_UIEventMission_Enter2-1 = "いらっしゃったのですね、\n先生。"
10106-CVGroup_UIEventMission_Idle1-1 = "そういえば、先生……いま、二人きりですね。"
10106-CVGroup_UIEventMission_Idle1-2 = "え？い、いえ……言葉通りで、"
10106-CVGroup_UIEventMission_Idle1-3 = "特に深い意味はないのです……が……。"
10106-CVGroup_UIEventMission_Idle2-1 = "その服、よく似合ってる……？\nふふ、ありがとうございます。"
10106-CVGroup_UIEventMission_Buy1-1 = "はい、こちら確認いたしました。"
10106-CVGroup_UIEventMission_Buy2-1 = "はい、よくできました。"
10106-CVGroup_UIEventMission_Interaction1-1 = "お疲れ様でした、先生。"
10106-CVGroup_UIEventMission_Interaction1-2 = "頑張った先生に\nご、ご褒美を…な、\nなんちゃって。"
