[translation]
10100-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ。"
10100-CVGroup_CharacterGet_Idle1-1 = "アビドスの砂狼シロコ……。\nん、またよろしくね、先生。"
10100-CVGroup_Cafe_Idle1-1 = "ここは……悪くない……。"
10100-CVGroup_Cafe_Idle2-1 = "平和だね、ここは。"
10100-CVGroup_Cafe_Idle3-1 = "ん、休憩しようかな。"
10100-CVGroup_Cafe_Idle4-1 = "これは……なに？\n開けてみていいの……？"
10100-CVGroup_Cafe_Idle5-1 = "（この家具……先生の好みなのかな……）"
10100-CVGroup_WeaponGet_Idle1-1 = "私に、ここまでしてくれるんだ。\nう、ううん。不満とかじゃなくて。\nただ、ちょっと驚いただけ……。"
