[translation]
10127-CVGroup_UITitle_Idle1-1 = "ブルー、アーカイ……ブ？"
10127-CVGroup_CharacterGet_Idle1-1 = "わ、ワイルドハント芸術学院、桜井ミヨと申します。\nど、どうして私が呼ばれたのか分かりませんが……よろしくお願いします。"
10127-CVGroup_Cafe_Idle1-1 = "（ゆっくり原稿ができそうな場所……ないかな）"
10127-CVGroup_Cafe_Idle2-1 = "タイプライターを使ったら迷惑になってしまうでしょうか……。"
10127-CVGroup_Cafe_Idle3-1 = "皆さん、のびのびと……\nワイルドハントとは大違いです。"
10127-CVGroup_Cafe_Idle4-1 = "（先生……どんなコーヒーがお好きなのでしょう？）"
10127-CVGroup_Cafe_Idle5-1 = "ええと、あそこから進入して、脱出は……\nって、ここではそんなの探さなくてもいいのに……。"
10127-CVGroup_WeaponGet_Idle1-1 = "もし叶うなら、この瞬間を本にしたいです。\n私たちの思い出を……いつでも読み返せるように。"
10127-CVGroup_UIEventLobby_Enter1-1 = "いらっしゃいませ、先生。\nちょうどプロットを書き終えたところです。"
10127-CVGroup_UIEventLobby_Enter2-1 = "先生にお会いできて、すごく安心しました。"
10127-CVGroup_UIEventLobby_Enter3-1 = "ワイルドハントに入学した時は、\nまさかこんな事をする羽目になるなんて想像もしていませんでした。"
10127-CVGroup_UIEventLobby_Enter4-1 = "事態が複雑になってきましたね……。\n……諦めるわけには。物語は完結させてこそ、です。"
10127-CVGroup_UIEventLobby_Enter5-1 = "無事に終わって良かったです。\n……はぁ。こんな依頼、もうたくさんです。"
10127-CVGroup_UIEventLobby_Idle1-1 = "あっ……タイピング音、うるさかったですか？"
10127-CVGroup_UIEventLobby_Idle2-1 = "どうしてこんなことに巻き込まれてしまったんでしょう……。"
10127-CVGroup_UIEventLobby_Idle3-1 = "そ、そんなにじっと見つめて……ふふっ。嬉しいです。"
10127-CVGroup_UIEventLobby_Idle4-1 = "お仕事のあとは、\nぜひ私たちの寮へ遊びに来てくださいね。"
10127-CVGroup_UIEventCardShop_Enter1-1 = "ようこそ、先生。\nこちらですよ。"
10127-CVGroup_UIEventCardShop_Enter2-1 = "お手をどうぞ。\n……一緒にカードを引きませんか？"
10127-CVGroup_UIEventCardShop_Enter3-1 = "物語の結末まで……\n悔いのないよう、見届けていってください。"
10127-CVGroup_UIEventCardShop_Idle1-1 = "何か問題でもありましたか？"
10127-CVGroup_UIEventCardShop_Idle2-1 = "お目当てのカードはありますか？"
10127-CVGroup_UIEventCardShop_Prize3-1 = "すごいです！私もこの目で見るのは初めてのカードですよ！"
10127-CVGroup_UIEventCardShop_Prize2-1 = "運がいいですね、先生！\nこの流れに乗って、次も……！"
10127-CVGroup_UIEventCardShop_Prize1-1 = "普通には、普通の美学というものがあります。"
10127-CVGroup_UIEventCardShop_Prize0-1 = "気を落とさないでください、先生。\n不運は、次の幸運の前兆ですよ。"
