[translation]
10122-CVGroup_UITitle_Idle1-1 = "Blue Archive~ Ahaha☆"
10122-CVGroup_CharacterGet_Idle1-1 = "Mika Misono, reaparecendo de traje de banho~☆\nÉ mais ou menos isso, né?\nContinue contando comigo, Sensei!"
10122-CVGroup_Cafe_Idle1-1 = "Ahaha, que estranho~"
10122-CVGroup_Cafe_Idle2-1 = "Hmm, então é assim que todo mundo vem ao Schale."
10122-CVGroup_Cafe_Idle3-1 = "(Tenho certeza de que todos também têm suas preocupações. Assim como eu...)"
10122-CVGroup_Cafe_Idle4-1 = "Quando será que o Sensei vem, hein?"
10122-CVGroup_Cafe_Idle5-1 = "Será que tudo bem tocar nisso...?"
10122-CVGroup_WeaponGet_Idle1-1 = "Isso é... para mim? Mentira!\n...Ei, é sério?\nNossa... Sensei, você é muito injusto. Sempre fazendo essas coisas com essa cara de quem não quer nada.\nIsso é trapaça...\nEu queria poder retribuir também..."
10122-CVGroup_UIEventLobby_Enter1-1 = "Ei, Sensei.\nEstá se divertindo?"
10122-CVGroup_UIEventLobby_Enter2-1 = "Hmm... nessas horas,\no que o Sensei faria...?"
10122-CVGroup_UIEventLobby_Enter3-1 = "É um desenrolar um pouco inesperado..."
10122-CVGroup_UIEventLobby_Enter3-2 = "Bem, vai dar tudo certo. Provavelmente!"
10122-CVGroup_UIEventLobby_Enter4-1 = "Preciso manter o foco."
10122-CVGroup_UIEventLobby_Enter4-2 = "Afinal, nunca se sabe o que pode acontecer!"
10122-CVGroup_UIEventLobby_Enter5-1 = "Ufa~ que bom que terminou."
10122-CVGroup_UIEventLobby_Enter5-2 = "O que teria acontecido se o Sensei não estivesse aqui..."
10122-CVGroup_UIEventLobby_Enter5-3 = "Nem quero pensar nisso..."
10122-CVGroup_UIEventLobby_Idle1-1 = "Que bom que estou com o Sensei~"
10122-CVGroup_UIEventLobby_Idle1-2 = "Você deve saber,"
10122-CVGroup_UIEventLobby_Idle1-3 = "mas eu sou um pouco descuidada às vezes..."
10122-CVGroup_UIEventLobby_Idle2-1 = "O que foi, o que foi?"
10122-CVGroup_UIEventLobby_Idle2-2 = "Por acaso, você precisa de mim?"
10122-CVGroup_UIEventLobby_Idle3-1 = "Ahaha, c-côcegas, Sensei!"
10122-CVGroup_UIEventLobby_Idle3-2 = "Tudo bem, né? Eu também vou fazer em você~"
10122-CVGroup_UIEventLobby_Idle4-1 = "Sensei...? Acho que já chega..."
10122-CVGroup_UIEventLobby_Idle4-2 = "Ah! Não é que eu não goste! De jeito nenhum!"
10122-CVGroup_UIEventLobby_Idle4-3 = "Mas é que... eu posso acabar entendendo errado."
10122-CVGroup_UIEventMission_Enter1-1 = "Uau, tem muita coisa para fazer..."
10122-CVGroup_UIEventMission_Enter2-1 = "A gente veio até a praia... e ainda tem que trabalhar...?"
10122-CVGroup_UIEventMission_Idle1-1 = "Que preguiça..."
10122-CVGroup_UIEventMission_Idle1-2 = "Se tivesse uma recompensa, talvez eu me animasse~"
10122-CVGroup_UIEventMission_Idle2-1 = "Ei, Sensei."
10122-CVGroup_UIEventMission_Idle2-2 = "...Vamos matar o trabalho juntos♪"
10122-CVGroup_UIEventMission_Buy1-1 = "Uau! Como esperado do Sensei☆"
10122-CVGroup_UIEventMission_Buy2-1 = "Oh, você está surfando em uma boa onda, hein!"
10122-CVGroup_UIEventMission_Interaction1-1 = "Trabalho terminado!"
10122-CVGroup_UIEventMission_Interaction1-2 = "Sensei, o que vamos fazer... agora?"
10122-CVGroup_UIEventMission_Interaction1-3 = "Eu... não tenho planos, na verdade."
