[translation]
10136-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10136-CVGroup_CharacterGet_Idle1-1 = "Nesta situação... eu também preciso trocar de roupa.\nO que acha, Sensei? Estou bem assim?"
10136-CVGroup_Cafe_Idle1-1 = "Ugh... estou precisando\nde cafeína."
10136-CVGroup_Cafe_Idle2-1 = "Da próxima vez, quero vir\naqui só com você, Sensei."
10136-CVGroup_Cafe_Idle3-1 = "Vou descansar um pouco ali..."
10136-CVGroup_Cafe_Idle4-1 = "Esta mochila está\nmeio quente..."
10136-CVGroup_Cafe_Idle5-1 = "Que paz..."
10136-CVGroup_WeaponGet_Idle1-1 = "É a primeira vez que vejo uma arma com esse formato,\nmas... para a missão,\nvou aprender a usá-la logo.\n...Pelo bem do Sensei também."
10136-CVGroup_UICarrierLobby_Enter1-1 = "É um lugar confortável e eficiente, mas..."
10136-CVGroup_UICarrierLobby_Enter2-1 = "Rações de combate são eficientes, mas..."
10136-CVGroup_UICarrierLobby_Enter3-1 = "Não sei por que, mas estou com uma vontade enorme de ir à cozinha."
10136-CVGroup_UICarrierLobby_Enter4-1 = "Sensei, quer beber algo gelado também?"
10136-CVGroup_UICarrierLobby_Idle1-1 = "Posso ligar o ar-condicionado? Será que a chefe vai se incomodar?"
10136-CVGroup_UICarrierLobby_Idle2-1 = "Será que é mais eficiente comer acompanhada?"
10136-CVGroup_UICarrierLobby_Idle3-1 = "Existem coisas no mundo que não são lógicas, mas são eficientes, né?"
10136-CVGroup_UICarrierLobby_Idle4-1 = "Meus pensamentos não se organizam..."
10136-CVGroup_UICarrierLobby_Idle4-2 = "Quando não é o corpo, mas a mente que está quente,"
10136-CVGroup_UICarrierLobby_Idle4-3 = "o que será que devo fazer..."
10136-CVGroup_UIEventMission_Enter1-1 = "Ei, Sensei, está me ouvindo?"
10136-CVGroup_UIEventMission_Enter2-1 = "É uma situação de emergência,\nentão estou te contatando por rádio."
10136-CVGroup_UIEventMission_Enter2-2 = "Mesmo através da linha,\nfico feliz em ver seu rosto."
10136-CVGroup_UIEventMission_Idle1-1 = "Garanti a ventilação, mas..."
10136-CVGroup_UIEventMission_Idle1-2 = "Ainda está quente.\nSe eu tirar mais uma camada—"
10136-CVGroup_UIEventMission_Idle1-3 = "Hã? Não posso? Entendi..."
10136-CVGroup_UIEventMission_Idle1-4 = "Bem, se o Sensei\ndiz isso..."
10136-CVGroup_UIEventMission_Idle2-1 = "Agora, mais do que uma sniper,\nsou uma atiradora de elite."
10136-CVGroup_UIEventMission_Idle2-2 = "Quando me movo,\nfico com a equipe."
10136-CVGroup_UIEventMission_Idle2-3 = "...Obrigada por me levar\npara um lugar mais fresco."
10136-CVGroup_UIEventMission_Buy1-1 = "Conversar com o Sensei\né realmente divertido."
10136-CVGroup_UIEventMission_Buy2-1 = "Aqui, bom trabalho."
10136-CVGroup_UIEventMission_Interaction1-1 = "Missão cumprida.\nConte comigo para a próxima."
