[translation]
10137-CVGroup_UITitle_Idle1-1 = "ぶる～あ～かいぶ～"
10137-CVGroup_CharacterGet_Idle1-1 = "あー、どもども。ヴァルキューレ警察学校、\n公安局の志真コノカっす。\n今日の占い、一緒に見てみません？"
10137-CVGroup_Cafe_Idle1-1 = "人が～おおいなぁ～"
10137-CVGroup_Cafe_Idle2-1 = "（さぁて犯罪者は……まぁ、ここにはいないか）"
10137-CVGroup_Cafe_Idle3-1 = "あれっ？あたしのバッジ……どこやったっけ……。"
10137-CVGroup_Cafe_Idle4-1 = "平和だなー。はぁ……暇だ。"
10137-CVGroup_Cafe_Idle5-1 = "これって合法なんすか？"
10137-CVGroup_WeaponGet_Idle1-1 = "あ、これ欲しかったんすよ！\nこれがあれば話が簡単に済むっすからね！"
10137-CVGroup_UIEventLobby_Enter1-1 = "ツチノコやーい！どこだー！？"
10137-CVGroup_UIEventLobby_Enter1-2 = "捕まえたらただじゃおかな……"
10137-CVGroup_UIEventLobby_Enter1-3 = "い、いや！でてこーい！"
10137-CVGroup_UIEventLobby_Enter2-1 = "ううっ……怖っ……。"
10137-CVGroup_UIEventLobby_Enter3-1 = "なんでこんな嫌がらせみたいな――ひっ！？\nだっ、誰……？"
10137-CVGroup_UIEventLobby_Enter4-1 = "お化けだろうが手錠をかけられるなら……！"
10137-CVGroup_UIEventLobby_Enter5-1 = "無事終わったっすね！\n運命なんてちょろいもんっす！はっはっはっ――"
10137-CVGroup_UIEventLobby_Enter5-2 = "い、いや！今のなし！\nちょろくないっす！ごめんなさい！！"
10137-CVGroup_UIEventLobby_Idle1-1 = "ひ、ひゃっ！？……って、ビックリした！"
10137-CVGroup_UIEventLobby_Idle2-1 = "ふぅ……ここ、空気だけは美味しいんすよね。"
10137-CVGroup_UIEventLobby_Idle3-1 = "ツチノコー！\n捕まえたら絶対に逃がさないっす！"
10137-CVGroup_UIEventLobby_Idle4-1 = "平常心……平常心……。"
10137-CVGroup_UIEventBoxGachaShop_Enter1-1 = "さあ！どんどんいくっすよ！！"
10137-CVGroup_UIEventBoxGachaShop_Enter2-1 = "今日の占いはどうでした？\n先生の運勢を信じてますよ！"
10137-CVGroup_UIEventBoxGachaShop_Enter3-1 = "後片づけタイム！\n最後まで気張ってくっすよ！"
10137-CVGroup_UIEventBoxGachaShop_Idle1-1 = "運勢、分けてくれるんすか？やったぁ！"
10137-CVGroup_UIEventBoxGachaShop_Idle2-1 = "先生と一緒だし、なんとかなるっす！"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-1 = "くぅー！これこれ！"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-1 = "すっごいツイてますね！？\n先生、マジパないっす！"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-1 = "毎日こうならいいんすけどね～"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaFinish1-1 = "一応、最後まで調べてみるっすよ！"
