[translation]
10137-CVGroup_UITitle_Idle1-1 = "Blue Archive~"
10137-CVGroup_CharacterGet_Idle1-1 = "Ah, e aí. Sou Konoka Shima, da Divisão de Segurança Pública da Academia Valkyrie.\nQuer dar uma olhada na previsão do dia comigo?"
10137-CVGroup_Cafe_Idle1-1 = "Tem... muita gente aqui~"
10137-CVGroup_Cafe_Idle2-1 = "(Bom, vamos ver os criminosos... bem, acho que não tem nenhum por aqui)"
10137-CVGroup_Cafe_Idle3-1 = "Ué? Onde foi que eu coloquei meu distintivo...?"
10137-CVGroup_Cafe_Idle4-1 = "Que paz... Ah, que tédio."
10137-CVGroup_Cafe_Idle5-1 = "Isso é legalizado?"
10137-CVGroup_WeaponGet_Idle1-1 = "Ah, eu queria muito isso! Com isso, as coisas vão ficar bem mais fáceis de resolver!"
10137-CVGroup_UIEventLobby_Enter1-1 = "Tsuchinoko, cadê você?! Apareça!"
10137-CVGroup_UIEventLobby_Enter1-2 = "Se eu te pegar, você vai ver só..."
10137-CVGroup_UIEventLobby_Enter1-3 = "N-não, espera! Aparece logo!"
10137-CVGroup_UIEventLobby_Enter2-1 = "Ugh... que medo..."
10137-CVGroup_UIEventLobby_Enter3-1 = "Por que fazer algo tão irritante assim— Hii!?\nQ-quem está aí...?"
10137-CVGroup_UIEventLobby_Enter4-1 = "Se for um fantasma, eu vou algemar mesmo assim...!"
10137-CVGroup_UIEventLobby_Enter5-1 = "Terminamos sem problemas! O destino é moleza! Hahaha—"
10137-CVGroup_UIEventLobby_Enter5-2 = "N-não, esquece o que eu disse! Não é moleza não! Desculpa!!"
10137-CVGroup_UIEventLobby_Idle1-1 = "H-hyah!? ...Nossa, que susto!"
10137-CVGroup_UIEventLobby_Idle2-1 = "Ufa... pelo menos o ar aqui é bom."
10137-CVGroup_UIEventLobby_Idle3-1 = "Tsuchinoko! Se eu te pegar, não vou te deixar escapar de jeito nenhum!"
10137-CVGroup_UIEventLobby_Idle4-1 = "Mantenha a calma... mantenha a calma..."
10137-CVGroup_UIEventBoxGachaShop_Enter1-1 = "Vamos lá! Vamos continuar com tudo!"
10137-CVGroup_UIEventBoxGachaShop_Enter2-1 = "Como foi a previsão de hoje? Estou confiando na sua sorte, Sensei!"
10137-CVGroup_UIEventBoxGachaShop_Enter3-1 = "Hora da limpeza! Vamos dar o nosso melhor até o fim!"
10137-CVGroup_UIEventBoxGachaShop_Idle1-1 = "Vai compartilhar sua sorte comigo? Oba!"
10137-CVGroup_UIEventBoxGachaShop_Idle2-1 = "Como estou com o Sensei, vai dar tudo certo!"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-1 = "Uau! É isso mesmo!"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-1 = "Que sorte incrível, hein!? Sensei, você é demais!"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-1 = "Seria bom se fosse assim todo dia, né?"
10137-CVGroup_UIEventBoxGachaShop_BoxGachaFinish1-1 = "Vou dar uma última conferida, só por precaução!"
