[translation]
10143-CVGroup_UITitle_Idle1_Shun-1 = "ブルー、アーカイブ。"
10143-CVGroup_CharacterGet_Idle1-1 = "準備体操はしましたか？\nちゃんとしないとメッですよ？"
10143-CVGroup_Cafe_Idle1-1 = "あら……素敵な場所ですね。"
10143-CVGroup_Cafe_Idle2-1 = "このお茶……お肌に良さそうです。"
10143-CVGroup_Cafe_Idle3-1 = "（ここって水着姿で来ても、大丈夫だったのでしょうか……）"
10143-CVGroup_Cafe_Idle4-1 = "うう……肩が凝ってしまいそう……。"
10143-CVGroup_Cafe_Idle5-1 = "とても快適すぎて……ずっとここにいたいです……。"
10143-CVGroup_WeaponGet_Idle1_Shun-1 = "こんな風にバカンスに出かけていると、ついつい気が緩んでしまうもの。\nですが、そういう時こそ気を引き締めないといけませんよ？\n規則を守らないと、メッですからね。"
10143-CVGroup_UITitle_Idle1_ShunSmall-1 = "ブルーアーカイブ！　えへへ。"
10143-CVGroup_UIEventLobby_Enter1_Shun-1 = "秘境に到着……\nふふっ、いかがですか、先生？"
10143-CVGroup_UIEventLobby_Enter1_Shun-2 = "私ですか？なんだか新鮮で、楽しいですよ。"
10143-CVGroup_UIEventLobby_Enter2_Shun-1 = "後でお時間よろしいでしょうか……？"
10143-CVGroup_UIEventLobby_Enter2_Shun-2 = "いえ、大したことではありません。"
10143-CVGroup_UIEventLobby_Enter2_Shun-3 = "ただ……先生と二人で、"
10143-CVGroup_UIEventLobby_Enter2_Shun-4 = "ここを見て回りたくて。"
10143-CVGroup_UIEventLobby_Enter3_Shun-1 = "先生と皆さんと一緒に旅行に来られて……。\nとてもうれしいです。"
10143-CVGroup_UIEventLobby_Enter3_Shun-2 = "きっと、私はこの日を忘れません、ずっと……。"
10143-CVGroup_UIEventLobby_Enter4_Shun-1 = "子供というのは、とても純粋です。"
10143-CVGroup_UIEventLobby_Enter4_Shun-2 = "私たちが思っている以上に色んなことを受け取っていて。"
10143-CVGroup_UIEventLobby_Enter4_Shun-3 = "だから、導いてあげないといけないんです。"
10143-CVGroup_UIEventLobby_Enter4_Shun-4 = "先生が私たちに対して、"
10143-CVGroup_UIEventLobby_Enter4_Shun-5 = "そう思ってくださるように。"
10143-CVGroup_UIEventLobby_Enter5_Shun-1 = "お疲れさまでした、先生。\nええ……本当に。"
10143-CVGroup_UIEventLobby_Enter6_Shun-1 = "その……よかったら、今から一緒に……。"
10143-CVGroup_UIEventLobby_Enter6_Shun-2 = "本当の旅行を楽しみませんか？"
10143-CVGroup_UIEventLobby_Idle1_Shun-1 = "準備運動はしっかりしましたか？"
10143-CVGroup_UIEventLobby_Idle1_Shun-2 = "水に入る時は、"
10143-CVGroup_UIEventLobby_Idle1_Shun-3 = "足からゆっくり水をかけて温度に慣らしてから入るんですよ。"
10143-CVGroup_UIEventLobby_Idle2_Shun-1 = "はい、私はここにいますよ。"
10143-CVGroup_UIEventLobby_Idle2_Shun-2 = "もしも寒いようでしたら……\n温めてあげますからね。"
10143-CVGroup_UIEventLobby_Idle3_Shun-1 = "わっ、そこはダメです、先生……っ！"
10143-CVGroup_UIEventLobby_Idle3_Shun-2 = "っ……。"
10143-CVGroup_UIEventLobby_Idle3_Shun-3 = "少しだけ、ですよ……。"
10143-CVGroup_UIEventLobby_Idle4_Shun-1 = "もう！先生ったら……めっ、です！"
10143-CVGroup_UIEventLobby_Idle4_Shun-2 = "二人きりになってからにしましょうね。"
10143-CVGroup_UIEventCardShop_Enter1_ShunSmall-1 = "こんにちは！お待ちしてました！"
10143-CVGroup_UIEventCardShop_Enter1_ShunSmall-2 = "先生のシュエリンですよ！"
10143-CVGroup_UIEventCardShop_Enter2_ShunSmall-1 = "先生、おかえりなさい！"
10143-CVGroup_UIEventCardShop_Enter2_ShunSmall-2 = "え？シュエリンで大丈夫なのか……？"
10143-CVGroup_UIEventCardShop_Enter2_ShunSmall-3 = "ふふっ、私はいつでも大丈夫ですよ！"
10143-CVGroup_UIEventCardShop_Idle1_ShunSmall-1 = "えへへっ、どうでしょう？新鮮ですか？"
10143-CVGroup_UIEventCardShop_Idle1_ShunSmall-2 = "あれ、どうかされたんですか？"
10143-CVGroup_UIEventCardShop_Idle1_ShunSmall-3 = "もしかして「シュエリン」とは……。"
10143-CVGroup_UIEventCardShop_Idle1_ShunSmall-4 = "遊びたくないのですか？"
10143-CVGroup_UIEventCardShop_Idle2_ShunSmall-1 = "先生と一緒にいる時が、"
10143-CVGroup_UIEventCardShop_Idle2_ShunSmall-2 = "一番幸せです。"
10143-CVGroup_UIEventCardShop_Idle2_ShunSmall-3 = "だって……。"
10143-CVGroup_UIEventCardShop_Idle2_ShunSmall-4 = "自分の気持ちに素直になれますから。"
10143-CVGroup_UIEventCardShop_Idle2_ShunSmall-5 = "子供の身体になるのって、最高～です！"
10143-CVGroup_UIEventCardShop_Prize3_ShunSmall-1 = "当たりです！すごいです！"
10143-CVGroup_UIEventCardShop_Prize3_ShunSmall-2 = "あっちで商品と交換できるみたいですよ！"
10143-CVGroup_UIEventCardShop_Prize2_ShunSmall-1 = "わあ！すごい！\n先生、もっと近くで見せてください！"
10143-CVGroup_UIEventCardShop_Prize1_ShunSmall-1 = "これは一体何でしょう……？\nきっとすごいものですよ！"
10143-CVGroup_UIEventCardShop_Prize0_ShunSmall-1 = "コンプリート、でしょうか？\nお疲れ様でした、先生！"
10143-CVGroup_UIEventCardShop_Enter3_ShunSmall-1 = "あっ、先生！えへへ。お待ちしてました！"
10143-CVGroup_UIEventCardShop_Enter4_ShunSmall-1 = "やることぜーんぶ終わってるなら……\n遊びに行きませんか？"
10143-CVGroup_UIEventCardShop_Enter4_ShunSmall-2 = "もちろん……二人きり、で。"
10143-CVGroup_UIEventMission_Enter1_Shun-1 = "一応、これも査察の一環なんです。"
10143-CVGroup_UIEventMission_Enter1_Shun-2 = "今日のスケジュールを見ていきましょうか。"
10143-CVGroup_UIEventMission_Enter2_Shun-1 = "査察対象がこんな綺麗な渓谷だなんて……。"
10143-CVGroup_UIEventMission_Enter2_Shun-2 = "なんだか、楽しみですね。"
10143-CVGroup_UIEventMission_Buy3_Shun-1 = "先生、よかったらフルーツを頂きませんか？"
10143-CVGroup_UIEventMission_Buy3_Shun-2 = "休憩がてら……はい、どうぞ。"
10143-CVGroup_UIEventMission_Buy4_Shun-1 = "お疲れさまでした。"
10143-CVGroup_UIEventMission_Buy4_Shun-2 = "あちらの方で色々と準備してくださっているみたいですよ。"
10143-CVGroup_UIEventMission_Idle1_Shun-1 = "その……先生のお時間は、もちろん先生のものですが……。"
10143-CVGroup_UIEventMission_Idle1_Shun-2 = "一部だけでも……ほんの少し、でもいいので。"
10143-CVGroup_UIEventMission_Idle1_Shun-3 = "一緒に過ごせたら、と思う時があるんです。"
10143-CVGroup_UIEventMission_Idle2_Shun-1 = "たまにそそっかしすぎると言われることがあるのですが……。"
10143-CVGroup_UIEventMission_Idle2_Shun-2 = "それが功を奏す時もあるんです。"
10143-CVGroup_UIEventMission_Idle2_Shun-3 = "ふふっ。ええ。"
10143-CVGroup_UIEventMission_Idle2_Shun-4 = "こうやって一緒にいる時間が、作れましたから。"
10143-CVGroup_UIEventMission_Interaction5-1 = "今日の査察はこれでおしまいですね。"
10143-CVGroup_UIEventMission_Interaction5-2 = "後は……自由時間です。"
