[translation]
10142-CVGroup_UITitle_Idle1-1 = "Blue... Archive."
10142-CVGroup_CharacterGet_Idle1-1 = "Já que viemos à praia... quero fazer memórias inesquecíveis com todos.\nSensei, você... me faria companhia?"
10142-CVGroup_Cafe_Idle1-1 = "Onde será o lugar mais fresco..."
10142-CVGroup_Cafe_Idle2-1 = "A festa de confraternização... estou ansiosa."
10142-CVGroup_Cafe_Idle3-1 = "Quero mostrar... um lado que seja digno de uma presidente."
10142-CVGroup_Cafe_Idle4-1 = "Eu não quero... chamar muita atenção..."
10142-CVGroup_Cafe_Idle5-1 = "Quero guardar com carinho as memórias de hoje."
10142-CVGroup_WeaponGet_Idle1-1 = "Ainda me falta muita coisa.\nMas, mesmo assim, quero continuar portando a Hyakuren.\nIsso não é... para fingir ser a presidente da Hyakkaryouran.\n--É para poder enfrentar o meu próprio coração."
10142-CVGroup_UIEventLobby_Enter1-1 = "Sensei, você vai observar nossas conquistas?"
10142-CVGroup_UIEventLobby_Enter2-1 = "Fufu, vou te mostrar o poder que estive selando."
10142-CVGroup_UIEventLobby_Enter3-1 = "Ainda temos alguma margem, mas não vamos baixar a guarda."
10142-CVGroup_UIEventLobby_Enter4-1 = "É a reta final, não é?"
10142-CVGroup_UIEventLobby_Enter4-2 = "Pessoal, vamos dar o nosso melhor."
10142-CVGroup_UIEventLobby_Enter5-1 = "Sensei, obrigada por ficar até o fim."
10142-CVGroup_UIEventLobby_Enter5-2 = "Vamos nos divertir juntos da próxima vez também."
10142-CVGroup_UIEventLobby_Idle1-1 = "O festival está bem animado, né."
10142-CVGroup_UIEventLobby_Idle1-2 = "Até eu estou ficando empolgada."
10142-CVGroup_UIEventLobby_Idle2-1 = "O sol está forte... precisamos nos proteger direito dos raios UV."
10142-CVGroup_UIEventLobby_Idle2-2 = "Dizem que queimadura de sol é um tipo de queimadura de verdade."
10142-CVGroup_UIEventLobby_Idle3-1 = "Você está... interessado em mim?"
10142-CVGroup_UIEventLobby_Idle3-2 = "Me desculpe. Por chamar tanta atenção."
10142-CVGroup_UIEventLobby_Idle4-1 = "Comer yakitori no festival, traz um sentimento especial."
10142-CVGroup_UIEventLobby_Idle4-2 = "Sensei não acha o mesmo?"