[translation]
10151-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ！"
10151-CVGroup_CharacterGet_Idle1-1 = "183号特別クラスの学級委員長、仁木（にき）アンナです。\nごめんなさいね、サインはまた今度。"
10151-CVGroup_Cafe_Idle1-1 = "（サインペンの準備、よし）"
10151-CVGroup_Cafe_Idle2-1 = "この椅子、素晴らしいですね。\n座れるし、軽いから振り回しやすい……。"
10151-CVGroup_Cafe_Idle3-1 = "素敵なデザイン……感銘を受けました。"
10151-CVGroup_Cafe_Idle4-1 = "ああ……気づいてしまったのですね。\nええ、そうです。私が仁木アンナです。"
10151-CVGroup_Cafe_Idle5-1 = "（この部屋からレスリングの才能の波動を感じます……）"
10151-CVGroup_WeaponGet_Idle1-1 = "ありがとうございます、先生。\nいただいたこちら、電動工具と同じくらい多用な使い道があって……本当に助かります。"
10151-CVGroup_UIEventLobby_Enter1-1 = "レッドウィンターが誇る科学者の学級――"
10151-CVGroup_UIEventLobby_Enter1-2 = "183号特別クラスへ、ようこそ！"
10151-CVGroup_UIEventLobby_Enter1-3 = "そして、私が183号特別クラスの学級委員長、仁木アンナです。"
10151-CVGroup_UIEventLobby_Enter2-1 = "戦車づくり？\nそんなのお茶の子さいさいです。"
10151-CVGroup_UIEventLobby_Enter3-1 = "進捗？\nえ、ええ！もちろん、\n順調ですよ！"
10151-CVGroup_UIEventLobby_Enter3-2 = "ええ……。"
10151-CVGroup_UIEventLobby_Enter4-1 = "自信？\nも、もちろん\nありますとも……"
10151-CVGroup_UIEventLobby_Enter4-2 = "ええ……あはは……。"
10151-CVGroup_UIEventLobby_Enter5-1 = "うっ……うっ……"
10151-CVGroup_UIEventLobby_Enter5-2 = "ありがとう……ございました……っ！"
10151-CVGroup_UIEventLobby_Idle1-1 = "ええ、私がその天才ですよ。"
10151-CVGroup_UIEventLobby_Idle1-2 = "正真正銘のホンモノ、です。"
10151-CVGroup_UIEventLobby_Idle1-3 = "ほ、ほんおに……ほんおの、れすから……！"
10151-CVGroup_UIEventLobby_Idle2-1 = "ナデナデ……？\nふ、ふつう、握手をするものでは？"
10151-CVGroup_UIEventLobby_Idle3-1 = "レッドウィンターにおける発明のほとんどは私たちが行ったものです。"
10151-CVGroup_UIEventLobby_Idle3-2 = "まぁ……本意ではありませんが。"
10151-CVGroup_UIEventLobby_Idle4-1 = "特別クラス脱しゅ……修了の日は近いですね。"
10151-CVGroup_UIEventShop_Enter1-1 = "ショッピング、ですね。\nいつも買ってきてもらっているので、自分で来たのは久しぶりです。"
10151-CVGroup_UIEventShop_Enter2-1 = "お買い物……ど、どうやるのでしたっけ？"
10151-CVGroup_UIEventShop_Enter3-1 = "「閉店セール」はないのですか……？\n新聞にはあるって……。"
10151-CVGroup_UIEventShop_Enter3-2 = "ええっ……。"
10151-CVGroup_UIEventShop_Idle1-1 = "その……私も買いたいものがあるのですが……"
10151-CVGroup_UIEventShop_Idle1-2 = "一緒に探してくださると、嬉しいです。"
10151-CVGroup_UIEventShop_Idle1-3 = "えっと……GOST5632を100kgほど……"
10151-CVGroup_UIEventShop_Idle1-4 = "見つけたら、教えて下さいね。"
10151-CVGroup_UIEventShop_Idle2-1 = "ど、どうしました？\n私は買ってあげることはできませんよ？"
10151-CVGroup_UIEventShop_Buy1-1 = "調達契約も必要ないのですね、助かりました。"
10151-CVGroup_UIEventShop_Buy2-1 = "ここで頑張ったら……恩赦がもらえたり、しませんかね？しませんよね。"
10151-CVGroup_UIEventShop_Buy3-1 = "素晴らしい判断です。ええ、私の業績と同じくらい。"
10151-CVGroup_UIEventShop_Buy4-1 = "計算も完璧ですね。"
10151-CVGroup_UIEventMission_Enter1-1 = "リストがこんなに……\n管理職としての腕がなりますね。"
10151-CVGroup_UIEventMission_Enter2-1 = "「リストを確認すること」"
10151-CVGroup_UIEventMission_Enter2-2 = "ええ、Ｔｏｄｏリストにも書いてありました。"
10151-CVGroup_UIEventMission_Idle1-1 = "ノルマを先に終わらせましょう。サインはまた後ほど。"
10151-CVGroup_UIEventMission_Idle2-1 = "すぐに終わらせて休憩に入りましょう、先生。"
10151-CVGroup_UIEventMission_Buy1-1 = "称賛と褒賞は、いくらあっても構いません。"
10151-CVGroup_UIEventMission_Buy2-1 = "先生にも報酬が必要です。ええ、当然。"
10151-CVGroup_UIEventMission_Interaction1-1 = "今日はここまで。ノルマ達成ですね。"
