[translation]
13006-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
13006-CVGroup_CharacterGet_Idle1-1 = "Tcharam! Finalmente cheguei!\nVamos nos divertir muito a partir de agora, Sensei!"
13006-CVGroup_Cafe_Idle1-1 = "É divertido, então está tudo bem."
13006-CVGroup_Cafe_Idle2-1 = "Hmm?\nAquilo ali também não parece bom?"
13006-CVGroup_Cafe_Idle3-1 = "Kufufu~♥"
13006-CVGroup_Cafe_Idle4-1 = "Faz um carinho em mim~"
13006-CVGroup_Cafe_Idle5-1 = "Vamos brincar juntos~"
13006-CVGroup_WeaponGet_Idle1-1 = "Sensei! Olha só~\nEssa arma parece muito forte e, além disso, é fofa!"
