[translation]
13012-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
13012-CVGroup_CharacterGet_Idle1-1 = "Aqui é a Kirino, da Academia de Polícia Valkyrie!\nTodos, mãos para o alto e sigam as minhas instruções!"
13012-CVGroup_Cafe_Idle1-1 = "Vejamos, não há nenhum criminoso escondido por aqui, certo?"
13012-CVGroup_Cafe_Idle2-1 = "Isso aqui... está dentro das regras?"
13012-CVGroup_Cafe_Idle3-1 = "Aquela pessoa, sinto que já a vi em algum lugar...\nSerá que é uma procurada?"
13012-CVGroup_Cafe_Idle4-1 = "Nenhuma anormalidade por hoje!"
13012-CVGroup_Cafe_Idle5-1 = "Kivotos está pacífica hoje também!"
13012-CVGroup_WeaponGet_Idle1-1 = "Vou me esforçar para aprender a manusear esta arma tão bem quanto ela merece...!"
