[translation]
16005-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16005-CVGroup_CharacterGet_Idle1-1 = "Kihihi... Ah, Se-Sensei...!?"
16005-CVGroup_Cafe_Idle1-1 = "E-Eu posso mesmo ficar aqui...?"
16005-CVGroup_Cafe_Idle2-1 = "Ugh, hah!?\nSe-Sensei...!?"
16005-CVGroup_Cafe_Idle3-1 = "E-Err...\nBem... ugh...\nUwaaaaaa!"
16005-CVGroup_Cafe_Idle4-1 = "É mais inquietante do que o campo de batalha..."
16005-CVGroup_Cafe_Idle5-1 = "E-Eu, bem, lugares assim não são muito para mim...!"
16005-CVGroup_WeaponGet_Idle1-1 = "Ufufufu...\nCom isso, com certeza...\nUhihihihihi!!!"
16005-CVGroup_UIEventLobby_Enter1-1 = "Ah, Se-Sensei...!?\nErr... bem... isso...\nMu-Muito prazer...!"
16005-CVGroup_UIEventLobby_Enter2-1 = "(O que será que o Sensei acha deste traje de banho...)"
16005-CVGroup_UIEventLobby_Enter2-2 = "Ah, auuu...!!!"
16005-CVGroup_UIEventLobby_Idle1-1 = "A... aquele...\nUgh... err..."
16005-CVGroup_UIEventLobby_Idle2-1 = "Ah, Sensei...\nE-Eu já estou pronta..."
16005-CVGroup_UIEventLobby_Idle3-1 = "(O que eu faço, o que eu faço, o que eu faço, o que eu faço...!?)"
16005-CVGroup_UIEventLobby_Idle4-1 = "T-Tsurugi!"
16005-CVGroup_UIEventLobby_Idle4-2 = "Indo para a batalha...!"
