[translation]
16009-CVGroup_UITitle_Idle1-1 = "Blue! Archive!"
16009-CVGroup_CharacterGet_Idle1-1 = "Fufufu... Desculpe a espera!\nA presidente do Clube de Pesquisa de Ninjutsu, Chidori Michiru... chegou para somar!\nConto com você daqui em diante, Mestre!"
16009-CVGroup_Cafe_Idle1-1 = "Muito bem, que tipo de vídeo devo postar no canal agora?"
16009-CVGroup_Cafe_Idle2-1 = "“Crônicas Ninja da Michiru-chi”...\nMeta: 100 inscritos no canal!"
16009-CVGroup_Cafe_Idle3-1 = "Ah, tive uma ideia para um novo ninjutsu!"
16009-CVGroup_Cafe_Idle4-1 = "Ué...\nQual era mesmo a data de lançamento do novo volume de “Kamaboko: A Lenda da Rajada de Vento”?"
16009-CVGroup_Cafe_Idle5-1 = "Ugh, tem estudantes de outras escolas por toda parte...\nNão quero ter que interagir muito..."
16009-CVGroup_WeaponGet_Idle1-1 = "Uau, até isso você me deu...!?\nE-eu me sinto um pouco responsável por isso, mas...\n...Não, tudo bem, pode deixar comigo, Mestre! Vou te mostrar o verdadeiro significado... do ninjutsu estilo Michiru!"
16009-CVGroup_UIEventLobby_Enter1-1 = "Ah, Mestre!\nAgora é a hora do Clube de Pesquisa de Ninjutsu brilhar!"
16009-CVGroup_UIEventLobby_Enter1-2 = "Vamos lá, vamos resolver isso de forma rápida e elegante!"
16009-CVGroup_UIEventLobby_Enter2-1 = "Uau, acabou virando uma confusão enorme..."
16009-CVGroup_UIEventLobby_Enter2-2 = "M-Mestre, vai ficar tudo bem, né?\nEu confio em você, viu!?"
16009-CVGroup_UIEventLobby_Enter3-1 = "Eita, já está nessa hora...\nSerá que vou conseguir chegar a tempo...?"
16009-CVGroup_UIEventLobby_Enter3-2 = "Ah, chega! O Grupo Chimi é muito insistente...!"
16009-CVGroup_UIEventLobby_Enter4-1 = "Eu não vou desistir até o fim...!\nNem da aprovação do Clube de Pesquisa de Ninjutsu!"
16009-CVGroup_UIEventLobby_Enter4-2 = "Nem dos 100 inscritos no canal “Crônicas Ninja da Michiru-chi”!"
16009-CVGroup_UIEventLobby_Enter5-1 = "Ueeeh... A-acabou finalmente...? Já posso ir para casa?"
16009-CVGroup_UIEventLobby_Enter5-2 = "Fuaah... Quero ir logo para casa assistir a filmes de ninja..."
16009-CVGroup_UIEventLobby_Enter5-3 = "Daqueles filmes B que não exigem que você pense em nada..."
16009-CVGroup_UIEventLobby_Idle1-1 = "O Grupo Chimi causando confusão, o Departamento Onmyou pressionando a gente,"
16009-CVGroup_UIEventLobby_Idle1-2 = "e o Pandemônio de Gehenna sendo um incômodo...\nO que é que está acontecendo, afinal...?"
16009-CVGroup_UIEventLobby_Idle2-1 = "...Hya!?\nM-Mestre!? O que você fez agora!?"
16009-CVGroup_UIEventLobby_Idle2-2 = "E-eu me assusto quando você me toca de repente...!"
16009-CVGroup_UIEventLobby_Idle3-1 = "Um ninja nunca desiste."
16009-CVGroup_UIEventLobby_Idle3-2 = "Corremos até o fim e cumprimos nossa missão, não importa o que aconteça..."
16009-CVGroup_UIEventLobby_Idle3-3 = "Vou te mostrar que é assim que nós, do Clube de Pesquisa de Ninjutsu, agimos!"
16009-CVGroup_UIEventLobby_Idle4-1 = "Vou resolver os pedidos do Departamento Onmyou com elegância,"
16009-CVGroup_UIEventLobby_Idle4-2 = "e desta vez eles vão ter que nos reconhecer como um clube oficial!"
