[translation]
16011-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ。"
16011-CVGroup_CharacterGet_Idle1-1 = "あら、先生。こちらでもお会いしましたね。\nトリニティ総合学園、正義実現委員会の羽川ハスミ。\nこの度はトリニティを代表して実行委員を務めることになりました。何卒よろしくお願いいたします。"
16011-CVGroup_Cafe_Idle1-1 = "……よく片付いた場所ですね。"
16011-CVGroup_Cafe_Idle2-1 = "競技場でもないのにこんな格好でいるのは変でしょうか……？"
16011-CVGroup_Cafe_Idle3-1 = "あ……あれは……?"
16011-CVGroup_Cafe_Idle4-1 = "いつもと違って、ちょっと走りたくなりますね。"
16011-CVGroup_Cafe_Idle5-1 = "（ううっ……ダイエットの大敵が……）"
16011-CVGroup_WeaponGet_Idle1-1 = "ありがとうございます、先生。まるで優勝旗をいただいたような気分です。\n先生が一緒にいてくださる以上、今後も負けることはありません。\nですので、これからもよろしくお願いいたしますね。"
16011-CVGroup_UIEventLobby_Enter1-1 = "お待ちしておりました、先生。\n準備はよろしいですか？"
16011-CVGroup_UIEventLobby_Enter2-1 = "ちょうど試合が始まるところです。\n一緒に参りましょうか。"
16011-CVGroup_UIEventLobby_Enter3-1 = "結構盛り上がっていますね。"
16011-CVGroup_UIEventLobby_Enter3-2 = "これなら、「晄輪大祭」は成功……\nと考えてもいいですね。"
16011-CVGroup_UIEventLobby_Enter4-1 = "「晄輪大祭」も大詰めを迎えていますね。"
16011-CVGroup_UIEventLobby_Enter4-2 = "最後まで頑張りましょう。"
16011-CVGroup_UIEventLobby_Enter5-1 = "先生のおかげで、\n「晄輪大祭」は大成功を収めることができました。"
16011-CVGroup_UIEventLobby_Enter5-2 = "本当にお疲れ様でした。"
16011-CVGroup_UIEventLobby_Idle1-1 = "せ、先生……？"
16011-CVGroup_UIEventLobby_Idle2-1 = "そ、そんなに見つめられても……。"
16011-CVGroup_UIEventLobby_Idle3-1 = "そろそろ出発のお時間ですよ……。"
16011-CVGroup_UIEventLobby_Idle4-1 = "何か必要なものでもありますか？"
16011-CVGroup_UIEventMission_Enter1-1 = "試合の記録を確認しますか？"
16011-CVGroup_UIEventMission_Enter2-1 = "進行状況を整理しました。\n確認しますか？"
16011-CVGroup_UIEventMission_Idle1-1 = "えっと……現在お見せできるのはこれで全てです。"
16011-CVGroup_UIEventMission_Idle2-1 = "他に確認したいことでもありますか……?"
16011-CVGroup_UIEventMission_Buy1-1 = "確認しました。\n素晴らしい記録ですね。"
16011-CVGroup_UIEventMission_Buy2-1 = "これは……新記録かもしれません。"
16011-CVGroup_UIEventMission_Interaction1-1 = "本日の記録は以上です。"
