[translation]
16020-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16020-CVGroup_CharacterGet_Idle1-1 = "Эй! Как поживаешь?\nДумаю, мы впервые представляемся друг другу как надо.\nЯ Тэндзиняма Отоги, снайпер взвода FOX.\nС этого момента рассчитываю на тебя, Сенсей."
16020-CVGroup_Cafe_Idle1-1 = "(Так спать хочется... Интересно, есть ли тут кофе...)"
16020-CVGroup_Cafe_Idle2-1 = "Раз-два... Может, мне стоит заодно немного подкачаться?"
16020-CVGroup_Cafe_Idle3-1 = "О... А сейчас я чувствую себя довольно бодро..."
16020-CVGroup_Cafe_Idle4-1 = "(Где-то я это уже видела... в Бюро исправительных учреждений?)"
16020-CVGroup_Cafe_Idle5-1 = "О, это новый мерч «Full Jelly»?\nНадо обязательно сфоткать."
16020-CVGroup_WeaponGet_Idle1-1 = "Снайперская винтовка FOX-82 получена.\nОна идеально подходит для сверхдальней стрельбы и устранения препятствий...\nВот только плечи жутко затекают, если стрелять слишком много."
16020-CVGroup_UIEventLobby_Enter1-1 = "Итак, операция наконец-то начинается..."
16020-CVGroup_UIEventLobby_Enter1-2 = "Давайте поднажмём!"
16020-CVGroup_UIEventLobby_Enter2-1 = "Я ждала тебя. Без тебя ничего бы не началось, Сенсей."
16020-CVGroup_UIEventLobby_Idle1-1 = "«Операция по выслеживанию Роа», хах..."
16020-CVGroup_UIEventLobby_Idle1-2 = "А Роа вообще можно выследить глазами?"
16020-CVGroup_UIEventLobby_Idle2-1 = "Хм? Что-то не так?"
16020-CVGroup_UIEventLobby_Idle3-1 = "Инари-суши Нико просто великолепны. Они вкусные, когда бы я их ни ела."
16020-CVGroup_UIEventLobby_Idle4-1 = "Интересно, как там Юкино..."
16020-CVGroup_UIEventLobby_Idle4-2 = "Кажется, она всё ещё немного зациклена на том, что произошло раньше."
16020-CVGroup_UIEventMission_Enter1-1 = "О, Сенсей. Как раз вовремя."
16020-CVGroup_UIEventMission_Enter1-2 = "Кое-что хотелось спросить у тебя по поводу того инцидента."
16020-CVGroup_UIEventMission_Enter2-1 = "Эй, у тебя найдётся минутка?"
16020-CVGroup_UIEventMission_Enter2-2 = "У меня есть к тебе пара просьб."
16020-CVGroup_UIEventMission_Idle1-1 = "Хм? Ты уставился на мои волосы, что такое?"
16020-CVGroup_UIEventMission_Idle1-2 = "Тебя в них что-то смущает?"
16020-CVGroup_UIEventMission_Idle1-3 = "А... я заплетаю их так, потому что было бы проблемой, если бы они за что-то зацепились в узком проходе."
16020-CVGroup_UIEventMission_Idle1-4 = "Вот почему я ношу такие косы."
16020-CVGroup_UIEventMission_Idle1-5 = "Хотя я думала о том, чтобы просто отрезать их."
16020-CVGroup_UIEventMission_Idle1-6 = "Но я растила их так долго, что теперь как-то жалко стричь."
16020-CVGroup_UIEventMission_Idle2-1 = "Воу! Не надо их теребить!?"
16020-CVGroup_UIEventMission_Idle2-2 = "...Я не особо люблю, когда у меня кто-то стоит за спиной."
16020-CVGroup_UIEventMission_Buy1-1 = "Хех... Вот как, понятно."
16020-CVGroup_UIEventMission_Buy1-2 = "Полагаю, у тех слухов всё-таки есть основание."
16020-CVGroup_UIEventMission_Buy2-1 = "Ты уже закончил?\n...Это было быстро. Потрясающе."
16020-CVGroup_UIEventMission_Buy2-2 = "Может, мне стоит называть тебя «Командиром»?"
16020-CVGroup_UIEventMission_Interaction1-1 = "Думаю, на сегодня этого вполне достаточно.\nОтличная работа!"
