[translation]
20004-CVGroup_UITitle_Idle1-1 = "Blue Archive."
20004-CVGroup_CharacterGet_Idle1-1 = "Sou Mashiro, do primeiro ano do Comitê de Justiça de Trinity.\nEm qualquer lugar e em qualquer situação,\napoiarei o Sensei com todas as minhas forças."
20004-CVGroup_Cafe_Idle1-1 = "Sinto que alguém está me observando..."
20004-CVGroup_Cafe_Idle2-1 = "Não há nenhum encrenqueiro tentando causar problemas por aqui, há?"
20004-CVGroup_Cafe_Idle3-1 = "(Da próxima vez, quero vir com todos os veteranos...)"
20004-CVGroup_Cafe_Idle4-1 = "(Este lugar parece ser um bom ponto de sniper.)"
20004-CVGroup_Cafe_Idle5-1 = "(Mantenha a mente como a superfície da água. Deixe as oscilações diminuírem, silenciosamente...)"
20004-CVGroup_WeaponGet_Idle1-1 = "Será que isto também é...\na verdadeira justiça...?"
20004-CVGroup_UIEventLobby_Enter1-1 = "Está muito abafado hoje, não é?...\nPor favor, tome muito cuidado com a insolação."
20004-CVGroup_UIEventLobby_Enter2-1 = "Muito bem, vamos começar o treinamento especial de verão!"
20004-CVGroup_UIEventLobby_Idle1-1 = "É a primeira vez que venho à praia com o pessoal de Trinity...\nEstou um pouco nervosa."
20004-CVGroup_UIEventLobby_Idle2-1 = "Dizem que o sábio aprecia a água..."
20004-CVGroup_UIEventLobby_Idle3-1 = "(Será que eu deveria ter escolhido um biquíni que não fosse preto...?)"
20004-CVGroup_UIEventLobby_Idle4-1 = "Acabei de ouvir o grito da Tsurugi-senpai vindo de algum lugar..."
20004-CVGroup_UIEventMission_Enter1-1 = "Cumprirei tanto as missões quanto o descanso com dedicação."
20004-CVGroup_UIEventMission_Idle1-1 = "Não há nenhum encrenqueiro tentando causar problemas por aqui, há?"
20004-CVGroup_UIEventMission_Idle2-1 = "Mesmo em um resort, não podemos baixar a guarda."
