[translation]
20025-CVGroup_UITitle_Idle1-1 = "B-Blue... Archive..."
20025-CVGroup_CharacterGet_Idle1-1 = "A-Ah... e-eu acabei vindo de novo...\nLogo no início do ano... me desculpe..."
20025-CVGroup_Cafe_Idle1-1 = "A-Ah, me desculpe.\nAlguém como eu usar roupas tão bonitas assim..."
20025-CVGroup_Cafe_Idle2-1 = "P-Professor...?\nSerá que ele não está aqui..."
20025-CVGroup_Cafe_Idle3-1 = "Então este é o lugar do Professor...\nP-Por que alguém como eu está aqui..."
20025-CVGroup_Cafe_Idle4-1 = "S-Será que estou parecendo deslocada..."
20025-CVGroup_Cafe_Idle5-1 = "Queria me esconder..."
20025-CVGroup_WeaponGet_Idle1-1 = "Este ano, no próximo ano...\nE até na próxima vida...!\nEu vou eliminar tudo o que o Professor detesta!"
20025-CVGroup_UIEventLobby_Enter1-1 = "P-P-P-Professor!?\nB-Bem-vindo de volta!\nE, d-desculpe!"
20025-CVGroup_UIEventLobby_Enter2-1 = "...Hehe...\nPoder encontrar o Professor aqui..."
20025-CVGroup_UIEventLobby_Enter2-2 = "N-Não! Não é como se tivesse algum significado especial...!"
20025-CVGroup_UIEventLobby_Idle1-1 = "S-Sim!?\nO-O-O que houve, Professor!?"
20025-CVGroup_UIEventLobby_Idle2-1 = "Hã...? Só... me chamou?"
20025-CVGroup_UIEventLobby_Idle2-2 = "E-Entendo.\nHehe..."
20025-CVGroup_UIEventLobby_Idle3-1 = "Recebendo o ano novo...\nCom o pessoal da Problem Solver... e com o Professor assim..."
20025-CVGroup_UIEventLobby_Idle3-2 = "Ehehe... é um sentimento um pouco especial."
20025-CVGroup_UIEventLobby_Idle4-1 = "Professor. Como eu disse, estar com alguém como eu...\nNão deve ser tão divertido..."
20025-CVGroup_UIEventLobby_Idle4-2 = "Não é... verdade? É mesmo...?"
20025-CVGroup_UIEventLobby_Idle4-3 = "...M-Muito obrigada, Professor."
20025-CVGroup_UIEventLobby_Enter3-1 = "Eu não entendo muito bem, mas...\nParece que algo terrível aconteceu..."
20025-CVGroup_UIEventLobby_Enter3-2 = "D-Devemos destruir tudo?"
20025-CVGroup_UIEventLobby_Enter4-1 = "A Aru-sama... parece estar se divertindo..."
20025-CVGroup_UIEventLobby_Enter4-2 = "Que bom. H-Hehe..."
20025-CVGroup_UIEventLobby_Enter5-1 = "Parece que a confusão finalmente se acalmou..."
20025-CVGroup_UIEventLobby_Enter5-2 = "Hum, aquele robô era...\nO que será que era aquilo...?"
