[translation]
20031-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ～"
20031-CVGroup_CharacterGet_Idle1-1 = "やっほ～先生、227号温泉郷へようこそ。\n私のことは気にせず、ゆっくりしてってね。"
20031-CVGroup_Cafe_Idle1-1 = "（どこからか冷たい空気が……）"
20031-CVGroup_Cafe_Idle2-1 = "（この賑やかな感じ、久しぶり……嫌いじゃない）"
20031-CVGroup_Cafe_Idle3-1 = "ん～いいにおい。"
20031-CVGroup_Cafe_Idle4-1 = "あれ……？\nこれダメになっちゃった？"
20031-CVGroup_Cafe_Idle5-1 = "この一杯は……あの冬の日に。"
20031-CVGroup_WeaponGet_Idle1-1 = "まあ、武器の出番がないならそれが一番だけど……\n必要なら、仕方ないよね。"
