[translation]
20043-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
20043-CVGroup_CharacterGet_Idle1-1 = "Feliz Ano Novo, Sensei!\nVamos começar outra aventura gastronômica este ano!"
20043-CVGroup_Cafe_Idle1-1 = "Que tipo de sabores vamos encontrar este ano?"
20043-CVGroup_Cafe_Idle2-1 = "Aventura gastronômica\nEstou tão animada!"
20043-CVGroup_Cafe_Idle3-1 = "Sabe... acho que quero comer aquilo ali!"
20043-CVGroup_Cafe_Idle4-1 = "Primeiro, preciso trazer o meu molho secreto especial!"
20043-CVGroup_Cafe_Idle5-1 = "Quer experimentar um takoyaki de menta com sardinha?"
20043-CVGroup_WeaponGet_Idle1-1 = "Aventuras gastronômicas às vezes trazem perigos...\nPor isso, eu vou proteger você, Sensei!"
20043-CVGroup_UIEventLobby_Enter1-1 = "Vamos lá, Sensei! É Ano Novo!"
20043-CVGroup_UIEventLobby_Enter1-2 = "Que tal começarmos nossa aventura em busca de iguarias?"
20043-CVGroup_UIEventLobby_Enter2-1 = "Tem algo que você queira comer?"
20043-CVGroup_UIEventLobby_Enter2-2 = "Eu quero comer tudo, absolutamente tudo!"
20043-CVGroup_UIEventLobby_Idle1-1 = "Só de ver você comendo com gosto, Sensei,"
20043-CVGroup_UIEventLobby_Idle1-2 = "eu me sinto tão feliz!"
20043-CVGroup_UIEventLobby_Idle2-1 = "Estar com você, Sensei, é cheio de descobertas!"
20043-CVGroup_UIEventLobby_Idle2-2 = "Meu coração dispara, como se eu estivesse provando um sabor novo!"
20043-CVGroup_UIEventLobby_Idle3-1 = "Dizem que aventuras devem ser feitas com amigos!"
20043-CVGroup_UIEventLobby_Idle3-2 = "Quando eu sair em uma aventura gastronômica, você vem comigo, Sensei!"
20043-CVGroup_UIEventLobby_Idle4-1 = "Eu também sou um membro do Clube de Pesquisa Gastronômica!"
20043-CVGroup_UIEventLobby_Idle4-2 = "Não vou parar de buscar novos sabores!"
20043-CVGroup_UIEventLobby_Idle4-3 = "Esse é o meu caminho gastronômico!"
