[translation]
23000-CVGroup_UITitle_Idle1-1 = "ブルーアーカイブ～"
23000-CVGroup_CharacterGet_Idle1-1 = "お会いできて嬉しいです、先生～\n先生はどんなアイスが好きですか？"
23000-CVGroup_Cafe_Idle1-1 = "んー、何を食べようかな……。"
23000-CVGroup_Cafe_Idle2-1 = "今日もやっぱりいちご＆ミント～"
23000-CVGroup_Cafe_Idle3-1 = "アイス、アイス～\nアイスクリーム～"
23000-CVGroup_Cafe_Idle4-1 = "放課後にはやっぱりスイーツ！"
23000-CVGroup_Cafe_Idle5-1 = "いちごとミントは最高！"
23000-CVGroup_WeaponGet_Idle1-1 = "……この武器は……。ありがとうございます。先生。\n強くなるのは、少し怖いことですが……。\n先生と一緒なら、大丈夫です！"
23000-CVGroup_UIEventMission_Enter1-1 = "おいしいスイーツのため～\n今日も一緒に、頑張りましょう！"
23000-CVGroup_UIEventMission_Enter2-1 = "今日も頑張ります！"
23000-CVGroup_UIEventMission_Idle1-1 = "えへへっ、もっと私に頼ってもいいんですよ～"
23000-CVGroup_UIEventMission_Idle2-1 = "えへへっ、少し照れちゃいますね、先生。"
23000-CVGroup_UIEventMission_Buy1-1 = "ありがとうございます、先生！"
23000-CVGroup_UIEventMission_Buy2-1 = "みんな、ファイトです！"
23000-CVGroup_UIEventMission_Interaction1-1 = "いつもありがとうございます～\n先生、えへへっ。"
