[translation]
26009-CVGroup_UITitle_Idle1-1 = "Blue... Archive..."
26009-CVGroup_CharacterGet_Idle1-1 = "Eu sou a Hanaoka Yuzu.\nPor vários motivos... estou vestida assim agora.\nPrazer em conhecê-lo..."
26009-CVGroup_Cafe_Idle1-1 = "Já que agora sou uma empregada...\nTalvez eu devesse limpar alguma coisa..."
26009-CVGroup_Cafe_Idle2-1 = "Uma empregada que cria jogos... talvez seja algo novo?"
26009-CVGroup_Cafe_Idle3-1 = "Uu... queria me esconder em algum lugar..."
26009-CVGroup_Cafe_Idle4-1 = "Caixas de papelão são itens essenciais para infiltração, mas..."
26009-CVGroup_Cafe_Idle5-1 = "Bem-vindo de volta, mestre.\nUu, ainda é muito vergonhoso..."
26009-CVGroup_WeaponGet_Idle1-1 = "F-fazer tudo isso por mim... não acredito... estou muito, muito feliz.\n...Eu vou me esforçar ainda mais.\n...Por favor, continue me observando, Sensei!"
26009-CVGroup_UIEventLobby_Enter1-1 = "Sensei! Bem..."
26009-CVGroup_UIEventLobby_Enter1-2 = "Bem-vindo de volta, mestre."
26009-CVGroup_UIEventLobby_Enter2-1 = "Não estou acostumada a lugares com tanta gente..."
26009-CVGroup_UIEventLobby_Enter2-2 = "Acho que isso também é um tipo de evento, de certa forma..."
26009-CVGroup_UIEventLobby_Enter3-1 = "Limpeza e hospitalidade..."
26009-CVGroup_UIEventLobby_Enter3-2 = "Uu, se tivesse um pouco menos de clientes..."
26009-CVGroup_UIEventLobby_Enter4-1 = "I-isso se tornou um grande problema...!"
26009-CVGroup_UIEventLobby_Enter4-2 = "Sensei... por favor, me ajude...!"
26009-CVGroup_UIEventLobby_Enter5-1 = "Ainda não consigo acreditar\nque aquilo aconteceu..."
26009-CVGroup_UIEventLobby_Enter5-2 = "Conseguimos resolver tudo graças ao Sensei."
26009-CVGroup_UIEventLobby_Idle1-1 = "A-a caixa? Onde está a caixa? Sem ela, eu..."
26009-CVGroup_UIEventLobby_Idle1-2 = "Ah, você a encontrou para mim!"
26009-CVGroup_UIEventLobby_Idle1-3 = "Muito obrigada, Sensei."
26009-CVGroup_UIEventLobby_Idle2-1 = "Bem... é muito assustador, mas..."
26009-CVGroup_UIEventLobby_Idle2-2 = "Talvez eu consiga usar essa experiência no meu jogo..."
26009-CVGroup_UIEventLobby_Idle3-1 = "Sensei. Será que eu...\nSerei capaz de fazer isso direito?"
26009-CVGroup_UIEventLobby_Idle4-1 = "Uu... queria ir para casa jogar..."
26009-CVGroup_UIEventLobby_Idle4-2 = "Mas não posso ficar apenas tremendo, né?"
26009-CVGroup_UIEventLobby_Idle4-3 = "Preciso fazer o que está ao meu alcance..."
