[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 22/06.]
10014-CVGroup_Battle_Buffed_1-1 = "Arte Ninja! Jutsu da Gratidão!"
10014-CVGroup_Battle_Covered_1-1 = "Me escondi!"
10014-CVGroup_Battle_Defense_1-1 = "Isso não funciona na Izuna!"
10014-CVGroup_Battle_In_1-1 = "Izuna, entrando em cena!"
10014-CVGroup_Battle_In_2-1 = "Pessoal, confiem na Izuna e sigam-me!"
10014-CVGroup_Battle_Move_1-1 = "Izuna, em movimento!"
10014-CVGroup_Battle_Move_2-1 = "Corrida ninja até a próxima área de operação!"
10014-CVGroup_Battle_Recovery_1-1 = "Muito obrigada!"
10014-CVGroup_Battle_TacticalAction_1-1 = "Sasa-sa-sat!"
10014-CVGroup_Battle_Victory_1-1 = "É a vitória das artes ninjas do Estilo Izuna!"
10014-CVGroup_Battle_Victory_2-1 = "Kon-kon!\nVitória, vitória!"
10014-CVGroup_CommonSkill-1 = "Lá vai, shuriken! Ei!"
10014-CVGroup_ExSkill_1-1 = "Arte Ninja, Estilo Izuna!"
10014-CVGroup_ExSkill_2-1 = "Vou te mostrar o meu ninjutsu!"
10014-CVGroup_ExSkill_3-1 = "Yá! Jutsu Utsusemi!"
10014-CVGroup_ExSkill_Level_1-1 = "Evasão de emergência!"
10014-CVGroup_ExSkill_Level_2-1 = "Isso também é ninjutsu...!\nOu algo parecido com isso!"
10014-CVGroup_ExSkill_Level_3-1 = "Vou desviar de tudo!"
10014-CVGroup_Formation_In_1-1 = "Se essa for a ordem do Meu Mestre!"
10014-CVGroup_Formation_In_2-1 = "Dê qualquer ordem para a Izuna!"
10014-CVGroup_Formation_Select-1 = "Nin-nin!\nMeu Mestre, o que a Izuna deve fazer?"
10014-CVGroup_Growup_1-1 = "Com isso, acho que posso aprender ninjutsus ainda mais difíceis!"
10014-CVGroup_Growup_2-1 = "Essa também é mais uma das grandes graças que recebi do Meu Mestre!"
10014-CVGroup_Growup_3-1 = "Eu com certeza me tornarei uma ninja que atenderá às expectativas do Meu Mestre!"
10014-CVGroup_Growup_4-1 = "Mais alto e mais rápido do que antes!\nA Izuna de agora talvez seja a ninja mais forte, Meu Mestre!!"
10014-CVGroup_Relationship_Up_1-1 = "Esse coração batendo forte quando estou com o Meu Mestre... será que é... senso de dever?"
10014-CVGroup_Relationship_Up_2-1 = "Ficar ao seu lado me deixa muito feliz.\nIsso é... a alegria de um ninja servindo ao seu lorde?"
10014-CVGroup_Relationship_Up_3-1 = "Por favor, me dê qualquer ordem!\nPara cumprir a vontade do Meu Mestre, a Izuna está bem aqui!"
10014-CVGroup_Relationship_Up_4-1 = "A Izuna procurou por um lorde como o Meu Mestre a vida inteira...\nFinalmente... finalmente pude conhecê-lo.\nA Izuna de agora é muuuito feliz."
10014-CVGroup_Tactic_In_1-1 = "Missão iniciada!"
10014-CVGroup_Tactic_In_2-1 = "Vou mostrar a Arte Ninja Estilo Izuna!"
10014-CVGroup_Tactic_Victory_1-1 = "Missão cumprida! Hoje eu também fiz um trabalho perfeito como uma ninja!"
10014-CVGroup_Tactic_Victory_2-1 = "Ofereço esta vitória ao Meu Mestre!"