[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
10038-CVGroup_Battle_Buffed_1-1 = "Ufa…… Sim, nada mal."
10038-CVGroup_Battle_Covered_1-1 = "Me ocultando."
10038-CVGroup_Battle_Defense_1-1 = "A resistência é inútil."
10038-CVGroup_Battle_In_1-1 = "Atenção a todos, não baixem a guarda……\nSensei, ordens, por favor!"
10038-CVGroup_Battle_In_2-1 = "Iniciando a operação!"
10038-CVGroup_Battle_Move_1-1 = "Área limpa, avançando."
10038-CVGroup_Battle_Move_2-1 = "Onde está o próximo inimigo?"
10038-CVGroup_Battle_Recovery_1-1 = "Muito obrigada pelo suporte."
10038-CVGroup_Battle_TacticalAction_1-1 = "Mudando de posição."
10038-CVGroup_Battle_Victory_1-1 = "Nós conseguimos."
10038-CVGroup_Battle_Victory_2-1 = "Área limpa."
10038-CVGroup_CommonSkill-1 = "Atenção, todos se afastem!"
10038-CVGroup_ExSkill_1-1 = "Múltiplos alvos confirmados à frente. Iniciando engajamento."
10038-CVGroup_ExSkill_2-1 = "Recepção limpa e clara. Iniciando invasão."
10038-CVGroup_ExSkill_3-1 = "Chegada confirmada, infiltrando de imediato."
10038-CVGroup_ExSkill_Level_1-1 = "Acionando os drones…… Solicito fogo de cobertura!"
10038-CVGroup_ExSkill_Level_2-1 = "Atenção todos, preparem-se para o impacto!"
10038-CVGroup_ExSkill_Level_3-1 = "Granada de luz, lançando!"
10038-CVGroup_Formation_In_1-1 = "Em posição."
10038-CVGroup_Formation_In_2-1 = "Entendido."
10038-CVGroup_Formation_Select-1 = "Posicionou no lugar errado?"
10038-CVGroup_Growup_1-1 = "Sinto que estou ainda mais forte."
10038-CVGroup_Growup_2-1 = "Então isso é o que chamam de…… crescimento."
10038-CVGroup_Growup_3-1 = "Crescer é uma sensação muito mais agradável do que eu imaginava."
10038-CVGroup_Growup_4-1 = "Vou me esforçar ainda mais para corresponder às suas expectativas."
10038-CVGroup_Relationship_Up_1-1 = "Você vai ficar…… ao meu lado para sempre?"
10038-CVGroup_Relationship_Up_2-1 = "Obedecerei a qualquer ordem que me der, Sensei…… Qualquer uma."
10038-CVGroup_Relationship_Up_3-1 = "Por favor…… fique comigo mais um pouco."
10038-CVGroup_Relationship_Up_4-1 = "Dizem que os coelhos são criaturas que morrem de solidão.\n……O Esquadrão RABBIT não é muito diferente."
10038-CVGroup_Tactic_In_1-1 = "Infiltrando a zona de operação, iniciando o avanço."
10038-CVGroup_Tactic_In_2-1 = "Como devemos proceder a partir daqui?"
10038-CVGroup_Tactic_Victory_1-1 = "Bom trabalho a todos."
10038-CVGroup_Tactic_Victory_2-1 = "A vitó-ria é nossa. Sensei."