[translation]
10048-CVGroup_Battle_Buffed_1-1 = "支援を確認。"
10048-CVGroup_Battle_Covered_1-1 = "遮蔽物、確保。"
10048-CVGroup_Battle_Defense_1-1 = "無意味だ。"
10048-CVGroup_Battle_In_1-1 = "なるほど、ここか。"
10048-CVGroup_Battle_In_2-1 = "戦闘準備完了。"
10048-CVGroup_Battle_Move_1-1 = "急ぐぞ。"
10048-CVGroup_Battle_Move_2-1 = "次の場所へ移動する。"
10048-CVGroup_Battle_Recovery_1-1 = "支援、感謝しよう。"
10048-CVGroup_Battle_TacticalAction_1-1 = "面白い。"
10048-CVGroup_Battle_Victory_1-1 = "簡単だったな……次の任務は？"
10048-CVGroup_Battle_Victory_2-1 = "次はどうする？"
10048-CVGroup_CommonSkill-1 = "無駄だ。"
10048-CVGroup_ExSkill_1-1 = "vanitas vanitatum, et omnia vanitas！"
10048-CVGroup_ExSkill_2-1 = "vanitas vanitatum……！"
10048-CVGroup_ExSkill_3-1 = "虚しい……全てはただ、虚しいだけだ……！"
10048-CVGroup_ExSkill_Level_1-1 = "誰もそこからは、逃れられない！"
10048-CVGroup_ExSkill_Level_2-1 = "はぁっ！！"
10048-CVGroup_ExSkill_Level_3-1 = "そのことを思い知れ！！"
10048-CVGroup_Formation_In_1-1 = "了解。"
10048-CVGroup_Formation_In_2-1 = "ああ。"
10048-CVGroup_Formation_Select-1 = "何をする気だ？"
10048-CVGroup_Growup_1-1 = "……能力が向上した。"
10048-CVGroup_Growup_2-1 = "強くなったのか。"
10048-CVGroup_Growup_3-1 = "もっと強くならないと……\n強さが無ければ、何も守れない。"
10048-CVGroup_Growup_4-1 = "まだ足りない。\nもっと……もっと強くならなければ……。"
10048-CVGroup_Relationship_Up_1-1 = "お前は、私のことを信じているのか？"
10048-CVGroup_Relationship_Up_2-1 = "その、感謝はしている。だが私は……\nいや、何でもない。忘れてくれ。"
10048-CVGroup_Relationship_Up_3-1 = "私がお前に、感謝をするとでも？"
10048-CVGroup_Relationship_Up_4-1 = "……私を見捨てる気はない、ということか？"
10048-CVGroup_Tactic_In_1-1 = "内容は把握した。"
10048-CVGroup_Tactic_In_2-1 = "了解、対処を始める。"
10048-CVGroup_Tactic_Victory_1-1 = "簡単な任務だった。"
10048-CVGroup_Tactic_Victory_2-1 = "任務完了。"
