[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 22/06.]
10046-CVGroup_Battle_Buffed_1-1 = "Arte Ninja, Jutsu da Gratidão! Versão de Verão!"
10046-CVGroup_Battle_Covered_1-1 = "Arte Ninja! Jutsu de Ocultação!"
10046-CVGroup_Battle_Defense_1-1 = "Isso é inútil!"
10046-CVGroup_Battle_In_1-1 = "Izuna, liderando a vanguarda!"
10046-CVGroup_Battle_In_2-1 = "Rápida como um ninja!\nMissão, iniciada!"
10046-CVGroup_Battle_Move_1-1 = "Vamos para o próximo alvo, Meu Mestre!"
10046-CVGroup_Battle_Move_2-1 = "Me movimentando! Touh!"
10046-CVGroup_Battle_Recovery_1-1 = "Ah, muito obrigada!"
10046-CVGroup_Battle_TacticalAction_1-1 = "Sasa-sat......!"
10046-CVGroup_Battle_Victory_1-1 = "Nós conseguimos, Meu Mestre!\nA vitória é nossa!"
10046-CVGroup_Battle_Victory_2-1 = "Ehehe! O que achou, Meu Mestre!\nA Izuna se esforçou bastante!"
10046-CVGroup_CommonSkill-1 = "Arte Ninja! Jutsu Puku-puku das Bolhas!"
10046-CVGroup_ExSkill_1-1 = "Tooh! Izuna, a caminho!"
10046-CVGroup_ExSkill_2-1 = "Essa também é uma Arte Ninja do Estilo Izuna!"
10046-CVGroup_ExSkill_3-1 = "Arte Ninja! Jutsu do Vôlei de Praia!"
10046-CVGroup_ExSkill_Level_1-1 = "Super Chute Ultra Poderoso!"
10046-CVGroup_ExSkill_Level_2-1 = "Esta é a Izuna agindo a sério!"
10046-CVGroup_ExSkill_Level_3-1 = "Vou te mostrar tudo o que a Izuna de verão tem a oferecer!"
10046-CVGroup_Formation_In_1-1 = "Sim! Meu Mestre!\nIzuna, a postos!"
10046-CVGroup_Formation_In_2-1 = "É a vez da Izuna!"
10046-CVGroup_Formation_Select-1 = "Neste verão também, por favor me dê qualquer ordem, Meu Mestre!\nNin-nin!"
10046-CVGroup_Growup_1-1 = "Isso é para a Izuna...?\nMuito obrigada, Meu Mestre!"
10046-CVGroup_Growup_2-1 = "A Izuna cresceu e evoluiu!\nSendo assim, vamos brincar agora mesmo! Meu Mestre!"
10046-CVGroup_Growup_3-1 = "Com isso, eu devo aguentar o calor sem problemas...!?\nSendo assim, Meu Mestre, vamos brincar juntos!"
10046-CVGroup_Growup_4-1 = "Graças ao Meu Mestre, a Izuna pôde ficar tão forte!\nVou continuar dando tudo de mim por você!"
10046-CVGroup_Relationship_Up_1-1 = "Poder passar este verão junto com o Meu Mestre...\nA Izuna está incrivelmente feliz!"
10046-CVGroup_Relationship_Up_2-1 = "Meu Looorde! Meu Mestre! Meuu Meeeestreee!\nEhehe! Não sei por quê, mas só de te chamar assim, eu já me sinto tão feliz!"
10046-CVGroup_Relationship_Up_3-1 = "......? Aconteceu alguma coisa?\nNão, não, eu sei que o dia está quente, mas enquanto eu estiver escoltando o Meu Mestre, não ligo para o calor!"
10046-CVGroup_Relationship_Up_4-1 = "(Olhar para o Meu Mestre faz o meu rosto ficar tão quente... Por que será?)"
10046-CVGroup_Tactic_In_1-1 = "Fique de olho nas minhas habilidades, hein! Meu Mestre!"
10046-CVGroup_Tactic_In_2-1 = "Vou te mostrar a Arte Ninja do Estilo Izuna que evoluiu para o verão!"
10046-CVGroup_Tactic_Victory_1-1 = "Missão cumprida!\nVamos logo brincar no mar! Meu Mestre!"
10046-CVGroup_Tactic_Victory_2-1 = "Com o ninjutsu do Estilo Izuna, não há oponente que não possamos derrotar! Provavelmente!"