[translation]
10048-CVGroup_Battle_Buffed_1-1 = "Suporte confirmado."
10048-CVGroup_Battle_Covered_1-1 = "Cobertura garantida."
10048-CVGroup_Battle_Defense_1-1 = "Inútil."
10048-CVGroup_Battle_In_1-1 = "Entendo, é aqui."
10048-CVGroup_Battle_In_2-1 = "Preparada para o combate."
10048-CVGroup_Battle_Move_1-1 = "Vamos nos apressar."
10048-CVGroup_Battle_Move_2-1 = "Indo para o próximo local."
10048-CVGroup_Battle_Recovery_1-1 = "Agradeço pelo suporte."
10048-CVGroup_Battle_TacticalAction_1-1 = "Interessante."
10048-CVGroup_Battle_Victory_1-1 = "Foi fácil... Qual a próxima missão?"
10048-CVGroup_Battle_Victory_2-1 = "O que faremos agora?"
10048-CVGroup_CommonSkill-1 = "Desperdício."
10048-CVGroup_ExSkill_1-1 = "vanitas vanitatum, et omnia vanitas！"
10048-CVGroup_ExSkill_2-1 = "vanitas vanitatum……！"
10048-CVGroup_ExSkill_3-1 = "Vazio... Tudo é apenas vazio...!"
10048-CVGroup_ExSkill_Level_1-1 = "Ninguém pode escapar disso!"
10048-CVGroup_ExSkill_Level_2-1 = "Haa!!"
10048-CVGroup_ExSkill_Level_3-1 = "Sinta isso na pele!!"
10048-CVGroup_Formation_In_1-1 = "Entendido."
10048-CVGroup_Formation_In_2-1 = "Sim."
10048-CVGroup_Formation_Select-1 = "O que pretende fazer?"
10048-CVGroup_Growup_1-1 = "...Minhas habilidades melhoraram."
10048-CVGroup_Growup_2-1 = "Fiquei mais forte?"
10048-CVGroup_Growup_3-1 = "Preciso ficar mais forte...\nSem força, não posso proteger nada."
10048-CVGroup_Growup_4-1 = "Ainda não é o suficiente.\nPreciso... preciso ficar ainda mais forte..."
10048-CVGroup_Relationship_Up_1-1 = "Você confia em mim?"
10048-CVGroup_Relationship_Up_2-1 = "Bem, eu sou grata. Mas eu...\nNão, esqueça. Esqueça o que eu disse."
10048-CVGroup_Relationship_Up_3-1 = "Você acha que eu te agradeceria?"
10048-CVGroup_Relationship_Up_4-1 = "...Então você não pretende me abandonar?"
10048-CVGroup_Tactic_In_1-1 = "Entendi o conteúdo."
10048-CVGroup_Tactic_In_2-1 = "Entendido, começando a lidar com isso."
10048-CVGroup_Tactic_Victory_1-1 = "Foi uma missão simples."
10048-CVGroup_Tactic_Victory_2-1 = "Missão concluída."
