[translation]
10047-CVGroup_Battle_Buffed_1-1 = "Sinto minhas forças aumentando~"
10047-CVGroup_Battle_Covered_1-1 = "Posso ficar escondida aqui~?"
10047-CVGroup_Battle_Defense_1-1 = "Isso faz cócegas."
10047-CVGroup_Battle_In_1-1 = "Vou destruir o que estiver no caminho~"
10047-CVGroup_Battle_In_2-1 = "Hora de passear, vamos lá~"
10047-CVGroup_Battle_Move_1-1 = "Para onde vamos agora~?"
10047-CVGroup_Battle_Move_2-1 = "Vamos por aqui~"
10047-CVGroup_Battle_Recovery_1-1 = "Ah, obrigada~"
10047-CVGroup_Battle_TacticalAction_1-1 = "Por aqui, por aqui~"
10047-CVGroup_Battle_Victory_1-1 = "Olha só, Sensei, pose de vitória~"
10047-CVGroup_Battle_Victory_2-1 = "Pose de vitória versão de verão~ O que achou?"
10047-CVGroup_CommonSkill-1 = "Disparar~?"
10047-CVGroup_ExSkill_1-1 = "Tem um monte de brilhos por aqui~"
10047-CVGroup_ExSkill_2-1 = "Vamos lá, vamos seguir em frente~"
10047-CVGroup_ExSkill_3-1 = "O mar de verão está em festa, né~"
10047-CVGroup_ExSkill_Level_1-1 = "Acho que era por aqui... Achei, bum."
10047-CVGroup_ExSkill_Level_2-1 = "Eu deveria estar com ele... Ah, achei. Granada, disparar~"
10047-CVGroup_ExSkill_Level_3-1 = "Hum, vejamos... Sim. Por enquanto, vamos tentar atirar."
10047-CVGroup_Formation_In_1-1 = "O sol está tão quentinho~"
10047-CVGroup_Formation_In_2-1 = "Hum... ...Preparado, Sensei?"
10047-CVGroup_Formation_Select-1 = "Vamos nadar?"
10047-CVGroup_Growup_1-1 = "É como se eu estivesse banhada pelo sol de verão..."
10047-CVGroup_Growup_2-1 = "Sim, fiquei mais forte~ Será que o Sensei também está ficando mais forte junto?"
10047-CVGroup_Growup_3-1 = "Me sinto leve, como se estivesse flutuando nas nuvens~"
10047-CVGroup_Growup_4-1 = "Da próxima vez quero virar um tanque... E depois, um foguete."
10047-CVGroup_Relationship_Up_1-1 = "Ficar quentinha junto com o Sensei... Será que é isso que chamam de felicidade?"
10047-CVGroup_Relationship_Up_2-1 = "Sensei, escuta, escuta, meu coração está batendo forte."
10047-CVGroup_Relationship_Up_3-1 = "Ficar com o Sensei me faz pensar em vários haicais, é divertido."
10047-CVGroup_Relationship_Up_4-1 = "O verão é cheio de brilhos, mas... O que mais brilha de verdade é, sem dúvida..."
10047-CVGroup_Tactic_In_1-1 = "Passeando, passeando~... Ah, não é isso?"
10047-CVGroup_Tactic_In_2-1 = "Em busca de brilhos, avançar~"
10047-CVGroup_Tactic_Victory_1-1 = "Já acabou~? Então vamos voltar, Sensei~"
10047-CVGroup_Tactic_Victory_2-1 = "Nós vencemos? Então, já podemos ir nadar?"
