[translation]
10042-CVGroup_Battle_Buffed_1-1 = "Suporte confirmado, obrigada."
10042-CVGroup_Battle_Covered_1-1 = "Estou escondida."
10042-CVGroup_Battle_Defense_1-1 = "Inútil."
10042-CVGroup_Battle_In_1-1 = "Sim."
10042-CVGroup_Battle_In_2-1 = "Vamos."
10042-CVGroup_Battle_Move_1-1 = "Movendo-me."
10042-CVGroup_Battle_Move_2-1 = "Avançar."
10042-CVGroup_Battle_Recovery_1-1 = "Obrigada."
10042-CVGroup_Battle_TacticalAction_1-1 = "Estou indo para aí."
10042-CVGroup_Battle_Victory_1-1 = "Sim...!"
10042-CVGroup_Battle_Victory_2-1 = "Vencemos."
10042-CVGroup_CommonSkill-1 = "...Estou sendo visada?"
10042-CVGroup_ExSkill_1-1 = "Entendi, faz sentido..."
10042-CVGroup_ExSkill_2-1 = "Isso é... para mim..."
10042-CVGroup_ExSkill_3-1 = "Então é assim que funciona..."
10042-CVGroup_ExSkill_Level_1-1 = "Nesse caso... não vou me segurar."
10042-CVGroup_ExSkill_Level_2-1 = "Então, por favor."
10042-CVGroup_ExSkill_Level_3-1 = "Se isso puder ser útil."
10042-CVGroup_Formation_In_1-1 = "Entendido."
10042-CVGroup_Formation_In_2-1 = "Confirmação concluída."
10042-CVGroup_Formation_Select-1 = "Hm?"
10042-CVGroup_Growup_1-1 = "Eu também valorizo esse sentimento de você cuidar de mim."
10042-CVGroup_Growup_2-1 = "Eu achava que não tinha valor suficiente para receber algo assim."
10042-CVGroup_Growup_3-1 = "Vou me lembrar para sempre do que você me ensinou."
10042-CVGroup_Growup_4-1 = "Aprendi mais uma coisa."
10042-CVGroup_Relationship_Up_1-1 = "Você é gentil comigo."
10042-CVGroup_Relationship_Up_2-1 = "Será que um dia conseguirei retribuir tudo o que recebi?"
10042-CVGroup_Relationship_Up_3-1 = "Dessa forma, mais... \nAh, não, nada não."
10042-CVGroup_Relationship_Up_4-1 = "É graças ao Sensei, bem, sabe... por tudo."
10042-CVGroup_Tactic_In_1-1 = "Ataque iniciado."
10042-CVGroup_Tactic_In_2-1 = "Operação iniciada."
10042-CVGroup_Tactic_Victory_1-1 = "Sim, vitória."
10042-CVGroup_Tactic_Victory_2-1 = "Vencemos, né."
