[translation]
10064-CVGroup_Battle_Buffed_1-1 = "Suporte, confirmado."
10064-CVGroup_Battle_Covered_1-1 = "Certo..."
10064-CVGroup_Battle_Defense_1-1 = "Tranquilo."
10064-CVGroup_Battle_In_1-1 = "Este ano também, temos muitos pedidos..."
10064-CVGroup_Battle_In_2-1 = "Vida nova... vamos lá."
10064-CVGroup_Battle_Move_1-1 = "Iniciando exploração."
10064-CVGroup_Battle_Move_2-1 = "Alvo, alterado."
10064-CVGroup_Battle_Recovery_1-1 = "Aceito com gratidão."
10064-CVGroup_Battle_TacticalAction_1-1 = "Mudando de posição."
10064-CVGroup_Battle_Victory_1-1 = "Que falta de sorte a sua."
10064-CVGroup_Battle_Victory_2-1 = "Será que foi um bom começo de ano?"
10064-CVGroup_CommonSkill-1 = "Fufu, que fofo."
10064-CVGroup_ExSkill_1-1 = "Ehem... aqui, um amuleto."
10064-CVGroup_ExSkill_2-1 = "Ehem... você poderia aceitar isto?"
10064-CVGroup_ExSkill_3-1 = "Hmm...\nComo foi?"
10064-CVGroup_ExSkill_Level_1-1 = "Espero que traga sorte."
10064-CVGroup_ExSkill_Level_2-1 = "Para afastar os maus espíritos."
10064-CVGroup_ExSkill_Level_3-1 = "Que você tenha um ótimo ano."
10064-CVGroup_Formation_In_1-1 = "É a minha vez? ...Entendido."
10064-CVGroup_Formation_In_2-1 = "Combina comigo? ...Que bom."
10064-CVGroup_Formation_Select-1 = "...O quê?"
10064-CVGroup_Growup_1-1 = "Sobre isso... obrigada.\nEste ano também estarei com o Sensei, né."
10064-CVGroup_Growup_2-1 = "Não sei se conseguirei atender às expectativas, mas... vou me esforçar."
10064-CVGroup_Growup_3-1 = "Que tipo de expressão devo fazer agora?\nDesculpe, não estou acostumada com esse tipo de situação..."
10064-CVGroup_Growup_4-1 = "Eu sempre recebo tanto do Sensei...\nNão sei se conseguirei retribuir à altura, mas farei o meu melhor."
10064-CVGroup_Relationship_Up_1-1 = "Laços são... misteriosos.\nComo é possível que, quanto mais se fortalecem, mais pensamos um no outro?"
10064-CVGroup_Relationship_Up_2-1 = "Ei, eu não costumo dizer esse tipo de coisa, mas...\n...Estou feliz por ter você aqui, Sensei."
10064-CVGroup_Relationship_Up_3-1 = "Eu sempre me perguntava como seria passar o ano novo com o Sensei...\nE agora, sinto que entendi um pouco."
10064-CVGroup_Relationship_Up_4-1 = "Obrigada por dizer que combina comigo.\nBem, deve ser só um elogio vazio... Não é um elogio vazio?\nE-espere, Sensei. Isso foi injusto..."
10064-CVGroup_Tactic_In_1-1 = "Vamos."
10064-CVGroup_Tactic_In_2-1 = "Pedidos devem ser feitos com rapidez."
10064-CVGroup_Tactic_Victory_1-1 = "Bom trabalho, Sensei.\nSuas roupas nem sujaram... que bom."
10064-CVGroup_Tactic_Victory_2-1 = "Quero começar o ano com o pé direito."
