[translation]
10087-CVGroup_Battle_Buffed_1-1 = "ご支援ありがとうございます！"
10087-CVGroup_Battle_Covered_1-1 = "ふぅ、隠れましたよ。"
10087-CVGroup_Battle_Defense_1-1 = "無駄です！"
10087-CVGroup_Battle_In_1-1 = "ふふ、私の活躍を、どうぞ目に焼き付けてくださいね。"
10087-CVGroup_Battle_In_2-1 = "さあ、作戦遂行しますよ。"
10087-CVGroup_Battle_Move_1-1 = "さあ、行きましょうか？"
10087-CVGroup_Battle_Move_2-1 = "次の会場へ。"
10087-CVGroup_Battle_Recovery_1-1 = "あ、ありがとうございます！"
10087-CVGroup_Battle_TacticalAction_1-1 = "次のポイントへ移動します。"
10087-CVGroup_Battle_Victory_1-1 = "ふふ、行政官に相応しい活躍でしたね！"
10087-CVGroup_Battle_Victory_2-1 = "どうでしょう？\n私、頑張りましたよ。"
10087-CVGroup_CommonSkill-1 = "逃がしません！"
10087-CVGroup_ExSkill_1-1 = "……やはり、そうだったのですね。"
10087-CVGroup_ExSkill_2-1 = "皆さん、ポジションについてください！"
10087-CVGroup_ExSkill_3-1 = "危険因子を排除いたします！"
10087-CVGroup_ExSkill_Level_1-1 = "包囲網に隙などありません！"
10087-CVGroup_ExSkill_Level_2-1 = "皆さん、確実に対処していきますよ！"
10087-CVGroup_ExSkill_Level_3-1 = "風紀委員会から逃れられると思っていたんですか！"
10087-CVGroup_Formation_In_1-1 = "ええ！いきましょうか。"
10087-CVGroup_Formation_In_2-1 = "私にお任せください。"
10087-CVGroup_Formation_Select-1 = "何か必要なものがありましたら\nなんなりとお申し付けください。"
10087-CVGroup_Growup_1-1 = "変わらぬご支援。ありがとうございます……ふふっ。"
10087-CVGroup_Growup_2-1 = "また一歩、成長できました。\n頼りがいのある存在になれているのなら、本望です。"
10087-CVGroup_Growup_3-1 = "……ありがとうございます、先生。\n……一応、いつも感謝しているんですよ？"
10087-CVGroup_Growup_4-1 = "また一歩、前進です。\n成長した分、より完璧な先生の補佐をお約束いたします。"
10087-CVGroup_Relationship_Up_1-1 = "また、ですか。\n……もう、その程度で慌てたりなんかしませんからね。\n見ていてください。"
10087-CVGroup_Relationship_Up_2-1 = "あ……。い、いえ。別に動揺などしていませんよ。全く。\nいつもより距離が近くても全っ然なんともないですから！"
10087-CVGroup_Relationship_Up_3-1 = "いつも気付いたらスッと人の懐に入っているんですよ、\nあなたという人は……\n……ズルいです。本当に、ズルいですよ。"
10087-CVGroup_Relationship_Up_4-1 = "以前、お伝えした通り……\n別に先生のことを嫌っているわけではありません。\n……あの言葉は、嘘偽りのない本心なんですよ？"
10087-CVGroup_Tactic_In_1-1 = "ええ、作戦を始めます。\n先生、指揮をお願いいたしますね。"
10087-CVGroup_Tactic_In_2-1 = "私が現場に直接出ましょう。\n先生はご支援をお願いいたします。"
10087-CVGroup_Tactic_Victory_1-1 = "おや、驚きました。\n先生の指揮が、まさかこれほどだったなんて。"
10087-CVGroup_Tactic_Victory_2-1 = "ええ、完璧な連携でした。\nふふ、私も現場に出た甲斐がありました。"
