[translation]
10094-CVGroup_Battle_Buffed_1-1 = "うん！ありがとう！"
10094-CVGroup_Battle_Covered_1-1 = "隠れるよ！"
10094-CVGroup_Battle_Defense_1-1 = "当たらないもん！"
10094-CVGroup_Battle_In_1-1 = "ゲームは実戦のように、\n実戦はゲームのように！"
10094-CVGroup_Battle_In_2-1 = "メイドの気分になるには、こういう仕事も必要だよね？"
10094-CVGroup_Battle_Move_1-1 = "とりあえず、お仕事終わり～！"
10094-CVGroup_Battle_Move_2-1 = "掃除完了！疲れたぁ～"
10094-CVGroup_Battle_Recovery_1-1 = "ありがとう！"
10094-CVGroup_Battle_TacticalAction_1-1 = "次はどこ！"
10094-CVGroup_Battle_Victory_1-1 = "ふんっふふ～見た？先生。\n今日のメイドモモイ、最高だったでしょ？"
10094-CVGroup_Battle_Victory_2-1 = "わははっ！これが――って、ああっ！？"
10094-CVGroup_CommonSkill-1 = "掃除はイヤだぁ～ええっ！？"
10094-CVGroup_ExSkill_1-1 = "また外れたぁ！って、あれ？"
10094-CVGroup_ExSkill_2-1 = "私、もう怒ったんだから！\nえ？ラッキー！"
10094-CVGroup_ExSkill_3-1 = "もーっ、当たれってば！\nって、何これ？"
10094-CVGroup_ExSkill_Level_1-1 = "見つけたっ、レアアイテム！"
10094-CVGroup_ExSkill_Level_2-1 = "おおお、この力は一体……！"
10094-CVGroup_ExSkill_Level_3-1 = "今の私は！\n何も怖くないっ！"
10094-CVGroup_Formation_In_1-1 = "メイドの気分になってみようかな！"
10094-CVGroup_Formation_In_2-1 = "メイドみたいに、全部解決するよ！"
10094-CVGroup_Formation_Select-1 = "いぇ～い！見てる？先生。\n全部私が片付けてあげるね！"
10094-CVGroup_Growup_1-1 = "レベルアップ！メイドレベルもアップ！\nえ？メイドレベルはまだ、だって？\n先生！それどういう意味？"
10094-CVGroup_Growup_2-1 = "先生！へへっ、私強くなったよ。\nえ？じゃあ、一緒に掃除しようって？\nそれは……ちょっと……。"
10094-CVGroup_Growup_3-1 = "メイドモモイの成長、とくとご覧あれっ！\nどう？先生？"
10094-CVGroup_Growup_4-1 = "あ～あ、仕方ないね。\nこの最強メイドモモイ様が、なんでも解決してあげる！"
10094-CVGroup_Relationship_Up_1-1 = "せ、先生と居ると、やっぱり楽しいかも。\nその……これは本心だからね？"
10094-CVGroup_Relationship_Up_2-1 = "聞いて、先生！\nメイドには報酬が大事なんだって！\nだから、ご褒美として……私と遊ぼ！"
10094-CVGroup_Relationship_Up_3-1 = "メイドも人間だよ！\n休まないと壊れちゃう……\nだから！今から先生は私と一緒に休憩するの！えへへっ。"
10094-CVGroup_Relationship_Up_4-1 = "ゲームでメイドが出てくると……\n高確率で攻略対象になるじゃん？\nだから先生。私のことも……攻略してみない？"
10094-CVGroup_Tactic_In_1-1 = "早く終わらせて、ゲームしに行こ！"
10094-CVGroup_Tactic_In_2-1 = "問題ないよ！\n私が居るんだもん！"
10094-CVGroup_Tactic_Victory_1-1 = "お掃除完了！\nま、こんなもんだね！"
10094-CVGroup_Tactic_Victory_2-1 = "やればできる子！\nなんだからさ！"
