[translation]
10098-CVGroup_Formchange1_Battle_Buffed_1-1 = "Acho que fiquei mais resistente~"
10098-CVGroup_Formchange1_Battle_Defense_1-1 = "Vou parar você, tá?~"
10098-CVGroup_Formchange1_Battle_In_1-1 = "Prepare-se."
10098-CVGroup_Formchange1_Battle_In_2-1 = "Deixo o suporte com vocês."
10098-CVGroup_Formchange1_Battle_Move_1-1 = "Ainda tem mais?~"
10098-CVGroup_Formchange1_Battle_Move_2-1 = "Eu vou na frente, então não se preocupe~"
10098-CVGroup_Formchange1_Battle_Recovery_1-1 = "Valeu~"
10098-CVGroup_Formchange1_Battle_TacticalAction_1-1 = "Vou mudar de posição."
10098-CVGroup_Formchange1_Battle_Victory_1-1 = "Isso não foi nada~"
10098-CVGroup_Formchange1_Battle_Victory_2-1 = "Já pode ficar tranquilo."
10098-CVGroup_Formchange1_CommonSkill-1 = "Vamos nos reagrupar~"
10098-CVGroup_Formchange1_ExSkill_1-1 = "Agora é a vez do tio aqui~"
10098-CVGroup_Formchange1_ExSkill_2-1 = "Isso não vai funcionar."
10098-CVGroup_Formchange1_ExSkill_3-1 = "Chamou?~"
10098-CVGroup_Formchange1_ExSkill_Level_1-1 = "Pessoal, recuem!"
10098-CVGroup_Formchange1_ExSkill_Level_2-1 = "Eu vou!"
10098-CVGroup_Formchange1_ExSkill_Level_3-1 = "Só isso?\nO tio aqui ficou decepcionado~"
10098-CVGroup_Formchange1_Formation_In_1-1 = "Vamos com tudo~"
10098-CVGroup_Formchange1_Formation_In_2-1 = "É um saco, mas...\nBem, eu vou fazer direito."
10098-CVGroup_Formchange1_Formation_Select-1 = "Uhe~ Ficar esperando também cansa, sabia?~"
10098-CVGroup_Formchange1_Formchange-1 = "Deixe a linha de frente comigo."
10098-CVGroup_Growup_1-1 = "Oh? É para o tio aqui?\nValeu~"
10098-CVGroup_Growup_2-1 = "Certo, recebi com certeza.\n...Então, vamos acabar com esses encrenqueiros?"
10098-CVGroup_Growup_3-1 = "Nossa, ganhei de novo.\nE agora, onde vamos lutar?"
10098-CVGroup_Growup_4-1 = "Uhe~ Fico sem jeito com essas coisas, mas... obrigado, Sensei.\nO tio aqui vai lutar por você."
10098-CVGroup_Relationship_Up_1-1 = "De novo isso...\nO tio aqui fica sem jeito~"
10098-CVGroup_Relationship_Up_2-1 = "Se por acaso o Sensei estiver em perigo, nesse momento...\n...Não, eu não vou deixar isso acontecer."
10098-CVGroup_Relationship_Up_3-1 = "Uhe~ Patrulhar com o Sensei...\nQuando será a próxima?\nJá estou ansiosa~"
10098-CVGroup_Relationship_Up_4-1 = "Mesmo eu estando assim, você ainda confia em mim, Sensei.\nUhe~ Que vergonha...\n...Mas, estou feliz."
10098-CVGroup_Formchange1_Tactic_In_1-1 = "Venham comigo."
10098-CVGroup_Formchange1_Tactic_In_2-1 = "Vamos começar?~"
10098-CVGroup_Formchange1_Tactic_Victory_1-1 = "Resultado esperado, eu diria."
10098-CVGroup_Formchange1_Tactic_Victory_2-1 = "Acabou~\nEntão, vamos descansar."
