[translation]
10103-CVGroup_Battle_Buffed_1-1 = "なんだ、この力は……。"
10103-CVGroup_Battle_Covered_1-1 = "隊列を組め！"
10103-CVGroup_Battle_Defense_1-1 = "金剛不壊（こんごうふえ）！"
10103-CVGroup_Battle_In_1-1 = "偉大なるレッドウィンターのために！"
10103-CVGroup_Battle_In_2-1 = "キヴォトスの果てまで、前進！"
10103-CVGroup_Battle_Move_1-1 = "敵を追え！"
10103-CVGroup_Battle_Move_2-1 = "突撃！突撃せよ！"
10103-CVGroup_Battle_Recovery_1-1 = "協力に感謝する。"
10103-CVGroup_Battle_TacticalAction_1-1 = "戸惑うな！"
10103-CVGroup_Battle_Victory_1-1 = "鍛錬に励んだ甲斐があったな。"
10103-CVGroup_Battle_Victory_2-1 = "突撃こそ、究極の戦法！"
10103-CVGroup_CommonSkill-1 = "不意打ち、成功だ！"
10103-CVGroup_ExSkill_1-1 = "ここは……うわっ！？"
10103-CVGroup_ExSkill_2-1 = "こんな森の奥に一体何が……は、ハチ！？"
10103-CVGroup_ExSkill_3-1 = "熊の姿はないな……う、うわあっ！？"
10103-CVGroup_ExSkill_Level_1-1 = "前方、ハチの巣！"
10103-CVGroup_ExSkill_Level_2-1 = "は、離れろ！"
10103-CVGroup_ExSkill_Level_3-1 = "危険因子を、排除する！"
10103-CVGroup_Formation_In_1-1 = "うむ！私が出よう！"
10103-CVGroup_Formation_In_2-1 = "動きやすくなったぞ！"
10103-CVGroup_Formation_Select-1 = "ま、待て！\nこのワンピース、少し開きすぎではないか……！？"
10103-CVGroup_Growup_1-1 = "こういうのも、新鮮で良いな。"
10103-CVGroup_Growup_2-1 = "（この本……読んだことがあるような……？）"
10103-CVGroup_Growup_3-1 = "ふむ、これは興味深い。"
10103-CVGroup_Growup_4-1 = "暑いからといって、訓練をサボっていい理由にはならん。"
10103-CVGroup_Relationship_Up_1-1 = "人より視野が狭い自覚は……ある……\nだからできるだけ……そばにいてくれ、先生。"
10103-CVGroup_Relationship_Up_2-1 = "露出の激しい衣装は、個人的に好きではない。\nだが先生がいいというのなら……まあ良いだろう。"
10103-CVGroup_Relationship_Up_3-1 = "勲章以外で先生にお返しができれば良いのだが……。"
10103-CVGroup_Relationship_Up_4-1 = "私は……いや、我がレッドウィンターは、常に先生を信じている。"
10103-CVGroup_Tactic_In_1-1 = "ずいぶんと複雑な道だな……。"
10103-CVGroup_Tactic_In_2-1 = "（慣れない道はあまり自信がないのだが……）"
10103-CVGroup_Tactic_Victory_1-1 = "ふふ、見たか！\nこれがレッドウィンターの勇姿だ！"
10103-CVGroup_Tactic_Victory_2-1 = "レッドウィンターの覇道に、敗北なし！"
