[translation]
10100-CVGroup_Battle_Buffed_1-1 = "Obrigada."
10100-CVGroup_Battle_Defense_1-1 = "Isso faz cócegas."
10100-CVGroup_Battle_In_1-1 = "Hum, vou ficar na frente."
10100-CVGroup_Battle_In_2-1 = "Hum, venham comigo."
10100-CVGroup_Battle_Move_1-1 = "Para onde vamos agora?"
10100-CVGroup_Battle_Move_2-1 = "Deveria ter trazido minha bicicleta..."
10100-CVGroup_Battle_Recovery_1-1 = "Obrigada."
10100-CVGroup_Battle_TacticalAction_1-1 = "Vou me mover."
10100-CVGroup_Battle_Victory_1-1 = "Hum, podem ficar tranquilos agora."
10100-CVGroup_Battle_Victory_2-1 = "Bom trabalho."
10100-CVGroup_CommonSkill-1 = "Chegou a hora de usar isto."
10100-CVGroup_ExSkill_1-1 = "Isto é... obrigada."
10100-CVGroup_ExSkill_2-1 = "Professor?\n...Hum, entendi."
10100-CVGroup_ExSkill_3-1 = "Para mim...? \nTudo bem, pode deixar comigo."
10100-CVGroup_ExSkill_Level_1-1 = "Hum, encaixa bem na mão."
10100-CVGroup_ExSkill_Level_2-1 = "Alvo à frente."
10100-CVGroup_ExSkill_Level_3-1 = "Iniciando suporte de fogo."
10100-CVGroup_Formation_In_1-1 = "Preparada.\nVou ajudar."
10100-CVGroup_Formation_In_2-1 = "Hum, entrando na batalha."
10100-CVGroup_Formation_Select-1 = "Aconteceu alguma coisa...?"
10100-CVGroup_Growup_1-1 = "É para mim?\nVou cuidar bem disso."
10100-CVGroup_Growup_2-1 = "Hum, talvez eu tenha crescido...\nEstou falando da minha altura."
10100-CVGroup_Growup_3-1 = "Isto é... hum, recebi com certeza.\nVou me esforçar para ser útil."
10100-CVGroup_Growup_4-1 = "Obrigada, Professor.\nDe agora em diante... conto com você."
10100-CVGroup_Relationship_Up_1-1 = "Professor, me empresta... seu ombro."
10100-CVGroup_Relationship_Up_2-1 = "Fico feliz por ter conseguido ajudar o Professor."
10100-CVGroup_Relationship_Up_3-1 = "Bem... não sei como isso vai soar, mas...\nÉ que... me sinto calma quando estou com o Professor."
10100-CVGroup_Relationship_Up_4-1 = "Ainda tem muita coisa que não sei...\nHum, me ensine várias coisas, Professor."
10100-CVGroup_Tactic_In_1-1 = "Inimigo detectado, aguardo instruções."
10100-CVGroup_Tactic_In_2-1 = "Posso atirar?"
10100-CVGroup_Tactic_Victory_1-1 = "Hum, como o esperado."
10100-CVGroup_Tactic_Victory_2-1 = "Já que o Professor está aqui.\nÉ um resultado natural."
