[translation]
10145-CVGroup_Battle_Buffed_1-1 = "次もよろしく頼むぞ。"
10145-CVGroup_Battle_Covered_1-1 = "少々、身を隠そうか。"
10145-CVGroup_Battle_Defense_1-1 = "精進が足りぬな。"
10145-CVGroup_Battle_In_1-1 = "夏の妾を目に焼き付けておくんじゃぞ？"
10145-CVGroup_Battle_In_2-1 = "遊ぶのなら全力で。当然じゃろう？"
10145-CVGroup_Battle_Move_1-1 = "場所を移そうかの。"
10145-CVGroup_Battle_Move_2-1 = "次はどこじゃ？"
10145-CVGroup_Battle_Recovery_1-1 = "感謝する。"
10145-CVGroup_Battle_TacticalAction_1-1 = "移動しようか。"
10145-CVGroup_Battle_Victory_1-1 = "見ていたのじゃろう？先生。\nほれ……頑張った生徒には、褒美が必要じゃろう？"
10145-CVGroup_Battle_Victory_2-1 = "避暑もたまには良いものじゃな。\nさて先生……この後の予定は空いてるかえ？"
10145-CVGroup_CommonSkill-1 = "無礼者。"
10145-CVGroup_ExSkill_1-1 = "おや……？\nっ……！？\nはぁ……。"
10145-CVGroup_ExSkill_2-1 = "ほう……。\nひゃあっ！？\nこれは、事故じゃ……。"
10145-CVGroup_ExSkill_3-1 = "ふふ……。\nなっ！？\n……夏じゃのう。"
10145-CVGroup_ExSkill_Level_1-1 = "たしかに涼しくはなったが……はぁ。"
10145-CVGroup_ExSkill_Level_2-1 = "不届き者がいたようじゃな。"
10145-CVGroup_ExSkill_Level_3-1 = "この程度で気を悪くはせぬよ。"
10145-CVGroup_Formation_In_1-1 = "やれやれ……。\n穏やかに過ごしたいのじゃが。"
10145-CVGroup_Formation_In_2-1 = "ふむ、妾と過ごしたいのかえ？\nふふっ、元よりそのつもりじゃよ？"
10145-CVGroup_Formation_Select-1 = "どうじゃ？似合っておるかの？\nふふっ、ゆっくり見ていくと良い。"
10145-CVGroup_Growup_1-1 = "明日があるというのは喜ばしいものじゃ。\nうむ、休暇と同じくらいにはな。"
10145-CVGroup_Growup_2-1 = "余白があるからこそ、人は成長できる。\n良いことじゃな。"
10145-CVGroup_Growup_3-1 = "其方が見ていてくれたから……\nここまで来ることができた。\n感謝してもしきれぬよ。"
10145-CVGroup_Growup_4-1 = "キキ、せいちょーう！\nふふっ驚いたかの？先生。\nこれは二人だけの秘密、じゃぞ？"
10145-CVGroup_Relationship_Up_1-1 = "新葉、陰、涼多し……春去りて来幾日ぞ\n夏雲忽にして嵯峨たり\nふふ……其方はこの意味、分かるかのう？"
10145-CVGroup_Relationship_Up_2-1 = "外見は内面の一番外側、とも言うじゃろう？\n時と場に相応しい格好をせねばならぬ。\nふふっ……そうさな。\nだから、これを其方の前で着ておるのじゃよ。"
10145-CVGroup_Relationship_Up_3-1 = "生涯の友となら、どこへ行こうとも怖くないというじゃろう？\nじゃから……妾と、どこまでも共にいてくれぬか？先生。"
10145-CVGroup_Relationship_Up_4-1 = "キキね……。\n世界で一番、先生が好き！\nふふっ。そんな顔をするでない。\nそろそろ慣れてきたのではないかえ？"
10145-CVGroup_Tactic_In_1-1 = "ふむ、道を探していこうか。"
10145-CVGroup_Tactic_In_2-1 = "木陰はないかのう。"
10145-CVGroup_Tactic_Victory_1-1 = "はぁ……休暇に来たはずなのじゃが。"
10145-CVGroup_Tactic_Victory_2-1 = "いい余興じゃったな。"
