[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 24/06.]
10143-CVGroup_Formchange_Shun_Battle_Buffed_1-1 = "Muito obrigada."
10143-CVGroup_Formchange_Shun_Battle_Covered_1-1 = "Vou me esconder um pouquinho."
10143-CVGroup_Formchange_Shun_Battle_Defense_1-1 = "Acho que vocês precisam se esforçar mais do que isso."
10143-CVGroup_Formchange_Shun_Battle_In_1-1 = "Prestem muita atenção onde pisam, meninas."
10143-CVGroup_Formchange_Shun_Battle_In_2-1 = "Sigam-me e não se percam."
10143-CVGroup_Formchange_Shun_Battle_Move_1-1 = "O que será que nos aguarda lá na frente?"
10143-CVGroup_Formchange_Shun_Battle_Move_2-1 = "É bem ali."
10143-CVGroup_Formchange_Shun_Battle_Recovery_1-1 = "Ufa. Isso ajudou bastante."
10143-CVGroup_Formchange_Shun_Battle_TacticalAction_1-1 = "Vamos nos mover para aquele lado."
10143-CVGroup_Formchange_Shun_Battle_Victory_1-1 = "Sim, hoje foi um dia excelente."
10143-CVGroup_Formchange_Shun_Battle_Victory_2-1 = "Poder brincar e me divertir com todas vocês... me deixou muito feliz."
10143-CVGroup_Formchange_Shun_CommonSkill-1 = "Ora, ora... fufu."
10143-CVGroup_Formchange_Shun_ExSkill_1-1 = "Fufu.\nAra?\nProblema resolvido."
10143-CVGroup_Formchange_Shun_ExSkill_2-1 = "Isso é divertido.\nAh?\nVamos continuar."
10143-CVGroup_Formchange_Shun_ExSkill_3-1 = "Hyaah!\nO que é aquilo...?\nUfufu."
10143-CVGroup_Formchange_Shun_ExSkill_Level_1-1 = "Oh, nossa."
10143-CVGroup_Formchange_Shun_ExSkill_Level_2-1 = "Tome muito cuidado, está bem?"
10143-CVGroup_Formchange_Shun_ExSkill_Level_3-1 = "Aconteceu alguma coisa?"
10143-CVGroup_Formchange_Shun_Formation_In_1-1 = "Cuidado para não se machucarem enquanto brincam."
10143-CVGroup_Formchange_Shun_Formation_In_2-1 = "Se algo acontecer, me contem imediatamente, tudo bem?"
10143-CVGroup_Formchange_Shun_Formation_Select-1 = "Ora... você vai brincar de jogar para o alto comigo? Fufu."
10143-CVGroup_Formchange_Shun_Formchange-1 = "Oh, aguarde só um momentinho, por favor."
10143-CVGroup_Formchange_Shun_Growup_1-1 = "Acompanhar o crescimento das crianças me aquece o coração profundamente.\nEh? O Sensei se sente da mesma forma me olhando...?\nP-Puxa vida... Muito obrigada."
10143-CVGroup_Formchange_Shun_Growup_2-1 = "O esforço contínuo para crescer e amadurecer é algo muito importante.\nPor isso... Eu também me sinto muito feliz por ter o Sensei me guiando e cuidando de mim."
10143-CVGroup_Formchange_Shun_Growup_3-1 = "Será que eu ainda posso crescer um pouco mais...?\nSabe... eu também acabo querendo ser mimada assim como as outras crianças."
10143-CVGroup_Formchange_Shun_Growup_4-1 = "A instrutora do Jardim da Flor de Ameixeira... está na posição de cuidar e observar as crianças.\nPor isso... Me sinto um pouco envergonhada de estar na posição de aluna sendo cuidada desse jeito."
10143-CVGroup_Formchange_Shun_Relationship_Up_1-1 = "Preparei algumas frutas tropicais fresquinhas.\nTem algo que você queira comer primeiro?\nTudo o que está aqui é para o Sensei, então sinta-se à vontade."
10143-CVGroup_Formchange_Shun_Relationship_Up_2-1 = "Se, por um acaso, conseguíssemos ficar a sós, apenas nós dois...\nO que o Sensei gostaria de fazer?\nEu... eu tenho uma coisa que gostaria de tentar."
10143-CVGroup_Formchange_Shun_Relationship_Up_3-1 = "Mesmo no verão, não podemos abaixar a guarda.\nAfinal, os resfriados de verão são os piores.\nMas, se o Sensei acabar adoecendo... eu cuidarei muito bem de você."
10143-CVGroup_Formchange_Shun_Relationship_Up_4-1 = "Memórias são coisas alegres, belas e...\nÀs vezes, nos trazem uma sensação de melancolia e tristeza.\nEu sempre desejo que elas permaneçam lindas para sempre, no entanto."
10143-CVGroup_Formchange_Shun_Tactic_In_1-1 = "Está tudo bem, eu estou aqui com vocês."
10143-CVGroup_Formchange_Shun_Tactic_In_2-1 = "Por favor, confiem em mim."
10143-CVGroup_Formchange_Shun_Tactic_Victory_1-1 = "Certo, meninas. Sigam-me em fila e sem bagunça."
10143-CVGroup_Formchange_Shun_Tactic_Victory_2-1 = "Por favor, não se apressem tanto~"