[translation]
13003-CVGroup_Battle_Buffed_1-1 = "Agradeço pelo apoio."
13003-CVGroup_Battle_Covered_1-1 = "Ponto de sniper garantido."
13003-CVGroup_Battle_Defense_1-1 = "Fufu, que amador."
13003-CVGroup_Battle_In_1-1 = "Recarga concluída.\nIrei aniquilar o inimigo agora."
13003-CVGroup_Battle_In_2-1 = "Coração quente, mente fria.\nVamos lá!"
13003-CVGroup_Battle_Move_1-1 = "Talvez eu devesse me exercitar um pouco mais..."
13003-CVGroup_Battle_Move_2-1 = "Limpo."
13003-CVGroup_Battle_Recovery_1-1 = "É delicioso, mas a porção é um pouco pequena...\nN-não é nada."
13003-CVGroup_Battle_TacticalAction_1-1 = "Mudando o ponto de sniper."
13003-CVGroup_Battle_Victory_1-1 = "Bom trabalho."
13003-CVGroup_Battle_Victory_2-1 = "Ainda não é o suficiente.\nContinuarei me esforçando."
13003-CVGroup_CommonSkill-1 = "Vamos lá."
13003-CVGroup_ExSkill_1-1 = "Atacando."
13003-CVGroup_ExSkill_2-1 = "Alvo detectado."
13003-CVGroup_ExSkill_3-1 = "Alvo capturado."
13003-CVGroup_ExSkill_Level_1-1 = "Não vou deixar você escapar."
13003-CVGroup_ExSkill_Level_2-1 = "Vou perfurar...!"
13003-CVGroup_ExSkill_Level_3-1 = "Lá vou eu!"
13003-CVGroup_Formation_In_1-1 = "Não precisa se conter.\nDeixe comigo."
13003-CVGroup_Formation_In_2-1 = "Eu estava esperando por você."
13003-CVGroup_Formation_Select-1 = "Hmm..."
13003-CVGroup_Growup_1-1 = "Obrigada pela consideração, Sensei."
13003-CVGroup_Growup_2-1 = "À medida que fico mais forte, sempre me pergunto se estou realmente me tornando alguém necessária...\nSempre me preocupo com isso."
13003-CVGroup_Growup_3-1 = "Fazer tudo isso por mim...\nEstou lisonjeada."
13003-CVGroup_Growup_4-1 = "Muito obrigada."
13003-CVGroup_Relationship_Up_1-1 = "Por que será?\nQuando estou com o Sensei, fico mais nervosa do que o normal."
13003-CVGroup_Relationship_Up_2-1 = "Mesmo que este momento seja apenas um sonho...\nEu o guardarei como um tesouro para toda a vida."
13003-CVGroup_Relationship_Up_3-1 = "Estarei sempre ao seu lado...\nSempre que precisar de mim, é só chamar."
13003-CVGroup_Relationship_Up_4-1 = "Sou sempre grata a você.\nEu também preciso me esforçar."
13003-CVGroup_Tactic_In_1-1 = "Inimigo detectado.\nPreparando para o combate."
13003-CVGroup_Tactic_In_2-1 = "Partindo."
13003-CVGroup_Tactic_Victory_1-1 = "Excelente trabalho."
13003-CVGroup_Tactic_Victory_2-1 = "Missão cumprida."
