[translation]
16015-CVGroup_Battle_Buffed_1-1 = "もっと頑張れそうです！"
16015-CVGroup_Battle_Covered_1-1 = "ここに！"
16015-CVGroup_Battle_Defense_1-1 = "効きません！"
16015-CVGroup_Battle_In_1-1 = "練習の成果、お見せします！"
16015-CVGroup_Battle_In_2-1 = "素敵な公演になるはず！"
16015-CVGroup_Battle_Move_1-1 = "次の小節へ！"
16015-CVGroup_Battle_Move_2-1 = "まだ演奏は終わっていません！"
16015-CVGroup_Battle_Recovery_1-1 = "あ、ありがとうございます！"
16015-CVGroup_Battle_TacticalAction_1-1 = "やっ！"
16015-CVGroup_Battle_Victory_1-1 = "お祝いの曲でも演奏しましょうか？"
16015-CVGroup_Battle_Victory_2-1 = "素敵な公演でした！"
16015-CVGroup_CommonSkill-1 = "ちょっと待ってくださいね～"
16015-CVGroup_ExSkill_1-1 = "……ふふ♪"
16015-CVGroup_ExSkill_2-1 = "うん。みんな楽しそう！"
16015-CVGroup_ExSkill_3-1 = "……やってよかった！"
16015-CVGroup_ExSkill_Level_1-1 = "私も……！"
16015-CVGroup_ExSkill_Level_2-1 = "いい感じ！"
16015-CVGroup_ExSkill_Level_3-1 = "これです！"
16015-CVGroup_Formation_In_1-1 = "れ、練習、たくさんしましたから！"
16015-CVGroup_Formation_In_2-1 = "大丈夫、大丈夫！\nいけるよアイリ！"
16015-CVGroup_Formation_Select-1 = "ん？……えへへ……。"
16015-CVGroup_Growup_1-1 = "上達しました！やったー！"
16015-CVGroup_Growup_2-1 = "初心者卒業できたかな……？"
16015-CVGroup_Growup_3-1 = "何でもできそうな気がします！"
16015-CVGroup_Growup_4-1 = "テンションがどんどん上がっていきます！"
16015-CVGroup_Relationship_Up_1-1 = "先生はいつも見守ってくださるんですね。\n……ありがとうございます。"
16015-CVGroup_Relationship_Up_2-1 = "今のこの感じ……。\nいつか音楽で表現したいです。"
16015-CVGroup_Relationship_Up_3-1 = "そ、その……やってみたい楽器とかありますか？\n……私が教えましょうか？"
16015-CVGroup_Relationship_Up_4-1 = "え、えっと！\n……お、お時間よろしければ……。\n一緒にスイーツカフェでも……！"
16015-CVGroup_Tactic_In_1-1 = "先生が任せてくださったお仕事だから……！必ず！"
16015-CVGroup_Tactic_In_2-1 = "こ、こんなに多いんですか……！？"
16015-CVGroup_Tactic_Victory_1-1 = "やりました、先生！\nできましたよ！"
16015-CVGroup_Tactic_Victory_2-1 = "これからも任せてください！先生！"
