[translation]
16020-CVGroup_Battle_Buffed_1-1 = "Sinto uma força surgindo!"
16020-CVGroup_Battle_Covered_1-1 = "Em cobertura. Deixo o suporte com vocês!"
16020-CVGroup_Battle_Defense_1-1 = "Tudo bem. Eu os afastei."
16020-CVGroup_Battle_In_1-1 = "FOX4, entrando."
16020-CVGroup_Battle_In_2-1 = "Pessoal, vamos dar o nosso melhor."
16020-CVGroup_Battle_Move_1-1 = "Indo para o próximo ponto."
16020-CVGroup_Battle_Move_2-1 = "Iniciando movimento."
16020-CVGroup_Battle_Recovery_1-1 = "Salvou minha vida, obrigada!"
16020-CVGroup_Battle_TacticalAction_1-1 = "Talvez tenham descoberto minha posição."
16020-CVGroup_Battle_Victory_1-1 = "FOX4, missão cumprida!"
16020-CVGroup_Battle_Victory_2-1 = "Vitória do Esquadrão FOX! Iei♪"
16020-CVGroup_CommonSkill-1 = "Acerto."
16020-CVGroup_ExSkill_1-1 = "Distância, 3500 jardas — vento, 15 nós vindo de nordeste..."
16020-CVGroup_ExSkill_2-1 = "Será que você consegue escapar desta bala mágica?"
16020-CVGroup_ExSkill_3-1 = "Vou decidir isso... com este disparo!"
16020-CVGroup_ExSkill_Level_1-1 = "Drone de reconhecimento, implantado."
16020-CVGroup_ExSkill_Level_2-1 = "Te achei♪"
16020-CVGroup_ExSkill_Level_3-1 = "Vou trocar para munição HEIAP."
16020-CVGroup_Formation_In_1-1 = "FOX4, pronta para a ação!"
16020-CVGroup_Formation_In_2-1 = "Uaa... já é essa hora?"
16020-CVGroup_Formation_Select-1 = "Oh, você é mais forte do que parece?\nAhaha, então, posso me apoiar em você?"
16020-CVGroup_Growup_1-1 = "Então, vamos começar o treinamento especial!"
16020-CVGroup_Growup_2-1 = "Obrigada por me ajudar.\nComo esperado, o Sensei é muito confiável."
16020-CVGroup_Growup_3-1 = "Acho que hoje estou em boa forma.\nSente que dá para notar o meu crescimento?"
16020-CVGroup_Growup_4-1 = "Ah... não posso deixar os veteranos me verem passando vergonha."
16020-CVGroup_Relationship_Up_1-1 = "Ahaha. Você é um adulto estranho mesmo."
16020-CVGroup_Relationship_Up_2-1 = "Até o dia em que a Academia Especial SRT for restaurada, conto com você, Sensei."
16020-CVGroup_Relationship_Up_3-1 = "Sempre que me chamar, eu virei correndo!\nPor isso... é que...\nSensei, quando eu te chamar, responda logo também, tá? Prometido!"
16020-CVGroup_Relationship_Up_4-1 = "Um tiro certeiro no seu coração!\n...Brincadeirinha. Ahaha!\nEu queria muito dizer uma frase dessas.\nN-não tem nenhum significado profundo, viu?"
16020-CVGroup_Tactic_In_1-1 = "Verificando a posição inimiga... qual é o alvo?"
16020-CVGroup_Tactic_In_2-1 = "Ei... eu que vou na frente?"
16020-CVGroup_Tactic_Victory_1-1 = "Moleza, moleza♪"
16020-CVGroup_Tactic_Victory_2-1 = "Vou voltar logo.\nEstou morrendo de fome."
