[translation]
20008-CVGroup_CommonSkill-1 = "É um suprimento do Comitê Disciplinar!"
20008-CVGroup_ExSkill_1-1 = "Estou enviando os dados de combate identificados."
20008-CVGroup_ExSkill_2-1 = "Os dados são este, este e..."
20008-CVGroup_ExSkill_3-1 = "Vou mostrar a vocês a capacidade de coleta de informações do Comitê Disciplinar."
20008-CVGroup_ExSkill_Level_1-1 = "Análise concluída, os pontos fracos já foram identificados."
20008-CVGroup_ExSkill_Level_2-1 = "O resto deixo com você, está bem?"
20008-CVGroup_ExSkill_Level_3-1 = "Hehe, estou totalmente preparada."
20008-CVGroup_Formation_In_1-1 = "É trabalho, não é? Sim, pode deixar comigo."
20008-CVGroup_Formation_In_2-1 = "Instruções de serviço como Schale... é isso? \nNesse caso, não tenho escolha."
20008-CVGroup_Formation_Select-1 = "Eu realmente queria resolver isso pacificamente, mas... \nparece que não tenho escolha a não ser fazer."
20008-CVGroup_Growup_1-1 = "Aceito com gratidão o seu apoio, Sensei."
20008-CVGroup_Growup_2-1 = "Estou... crescendo. \nAté eu mesma estou, bem, surpresa."
20008-CVGroup_Growup_3-1 = "Esse tipo de coisa não é algo que se faz casualmente, não é? \n...Qual é o seu objetivo? Quer que eu faça algo?"
20008-CVGroup_Growup_4-1 = "Sobre isso... obrigada, Sensei. \n...O que é essa cara? \nEu também sei agradecer quando alguém faz algo por mim. Francamente..."
20008-CVGroup_Relationship_Up_1-1 = "Ei, a distância não está um pouco curta demais...? \nN-não, não é que eu esteja pensando demais nisso..."
20008-CVGroup_Relationship_Up_2-1 = "...Você deseja um relacionamento fora do trabalho? \nAinda é muito cedo para isso..."
20008-CVGroup_Relationship_Up_3-1 = "Que tipo de sentimento é este... \nPor favor, me dê um pouco mais de tempo para analisar. \nSério, só um pouco já basta."
20008-CVGroup_Relationship_Up_4-1 = "Haa... sim, eu admito. \nNão é como se eu odiasse você, Sensei. \nE então? O que tem isso?"
