[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
20014-CVGroup_CommonSkill-1 = "Isso vai doer!" 
20014-CVGroup_ExSkill_1-1 = "RABBIT 2, pronta para a descida." 
20014-CVGroup_ExSkill_2-1 = "Arnês preparado." 
20014-CVGroup_ExSkill_3-1 = "RABBIT 2, chegando no local." 
20014-CVGroup_ExSkill_Level_1-1 = "Fogo de cobertura, iniciar!" 
20014-CVGroup_ExSkill_Level_2-1 = "Iniciando suporte de poder de fogo!" 
20014-CVGroup_ExSkill_Level_3-1 = "Não subestime a força da SRT!" 
20014-CVGroup_Formation_In_1-1 = "Meus preparativos já estão concluídos." 
20014-CVGroup_Formation_In_2-1 = "Em posição, pronta para ação." 
20014-CVGroup_Formation_Select-1 = "Ei, não toque sem permissão!\nIsso é perigoso, sabia!?" 
20014-CVGroup_Growup_1-1 = "Isto também é o fruto\nde um treinamento incansável." 
20014-CVGroup_Growup_2-1 = "Se quiser ficar mais forte,\ntem que ler o manual com dedicação." 
20014-CVGroup_Growup_3-1 = "É frustrante admitir, mas...\nOs ensinamentos do Sensei realmente são úteis." 
20014-CVGroup_Growup_4-1 = "Para alcançar as nossas veteranas...\nEu preciso me tornar muito, muito mais forte...!" 
20014-CVGroup_Relationship_Up_1-1 = "Se é uma ordem do Sensei, eu obedeço.\nAfinal, eu confio em você." 
20014-CVGroup_Relationship_Up_2-1 = "Uma interação para fortalecer\nos laços com o comandante...\nBem, se é assim, não tem outro jeito." 
20014-CVGroup_Relationship_Up_3-1 = "Sensei, você pode depender de nós\nde vez em quando, sabia?" 
20014-CVGroup_Relationship_Up_4-1 = "Se for para o Sensei, posso confiar a minha\nretaguarda sem medo." 