[translation]
20042-CVGroup_CommonSkill-1 = "あたしの芸術を見てってよね！"
20042-CVGroup_ExSkill_1-1 = "電波どこ？……あった！\n……え、ちょっ……わあっ！？"
20042-CVGroup_ExSkill_2-1 = "繋がれ、繋がれ……\nよし！う、うわあっ！"
20042-CVGroup_ExSkill_3-1 = "お願い、繋がって……わぁ！\nえ、ええ……！？"
20042-CVGroup_ExSkill_Level_1-1 = "うわっ、ミスった……！\nま、いっか……。"
20042-CVGroup_ExSkill_Level_2-1 = "うぐぐ……\nゲッ……今の見た？"
20042-CVGroup_ExSkill_Level_3-1 = "うぎゃぁはっ！？\nちゃ、着地成功……！"
20042-CVGroup_Formation_In_1-1 = "え？出かけないとなの？"
20042-CVGroup_Formation_In_2-1 = "もー！キャンプだけで手一杯なんだけど！？"
20042-CVGroup_Formation_Select-1 = "あ、これいいね！このまま連れてってよ～"
20042-CVGroup_Growup_1-1 = "キャンプにも慣れてきた気はするけど……\n……これっていい事なのかなぁ？"
20042-CVGroup_Growup_2-1 = "まだ道は遠いけど、\nどこに向かえばいいのか分かった気がする！"
20042-CVGroup_Growup_3-1 = "うん、これならもっと頑張れそう！"
20042-CVGroup_Growup_4-1 = "おお、インスピレーションが湧いてきた！"
20042-CVGroup_Relationship_Up_1-1 = "いつもありがとう、先生。\nこれは本心だよ！"
20042-CVGroup_Relationship_Up_2-1 = "山に登るのは大変だけど……\nでも、先生が一緒なら、まぁいいかな。"
20042-CVGroup_Relationship_Up_3-1 = "先生、一緒に散歩でもどう？\nべ、別に他意はないよ！？\n……天気もいいし？"
20042-CVGroup_Relationship_Up_4-1 = "（あれ？おかしいな……\nさっき先生の顔、すごくキラキラして見えたのに……）"
