[translation]
20054-CVGroup_CommonSkill-1 = "Fufu, esperei por você."
20054-CVGroup_ExSkill_1-1 = "Ficou hipnotizado?"
20054-CVGroup_ExSkill_2-1 = "Em termos de velocidade, não perderei para ninguém."
20054-CVGroup_ExSkill_3-1 = "Quer que eu faça um para você também?"
20054-CVGroup_ExSkill_Level_1-1 = "Isto é uma cadeira de rodas."
20054-CVGroup_ExSkill_Level_2-1 = "Bem, vamos começar?"
20054-CVGroup_ExSkill_Level_3-1 = "Você precisa da minha ajuda, não é?"
20054-CVGroup_Formation_In_1-1 = "Precisa da minha ajuda?\nSim, eu imaginei que precisaria."
20054-CVGroup_Formation_In_2-1 = "Bem, por onde devemos começar?"
20054-CVGroup_Formation_Select-1 = "Sim, Sensei. Estou aqui."
20054-CVGroup_Growup_1-1 = "É possível crescer em qualquer situação...\nImagino que seja isso que o Sensei diria."
20054-CVGroup_Growup_2-1 = "Crescer por conta própria é algo muito difícil.\nTalvez eu seja quem sou hoje graças à sua presença, Sensei."
20054-CVGroup_Growup_3-1 = "Eu entendo, Sensei.\nNão podemos baixar a guarda, mas também não é bom ficar tenso demais."
20054-CVGroup_Growup_4-1 = "Crescer é algo gratificante... Sim, eu entendo isso.\nAo mesmo tempo, penso em quantos recursos o Sensei dedicou a mim.\nPor favor, não se sobrecarregue."
20054-CVGroup_Relationship_Up_1-1 = "O que achou do meu novo traje?\n...Combina comigo? Sim, eu imaginei que diria isso."
20054-CVGroup_Relationship_Up_2-1 = "Costumam dizer que ninguém vive sozinho...\nUltimamente, tenho sentido o verdadeiro significado dessas palavras.\n...Sensei, você não vai me deixar sozinha, vai?"
20054-CVGroup_Relationship_Up_3-1 = "Tudo o que aconteceu desde que conheci o Sensei\nfoi algo que nem mesmo eu, com meu diploma de \"Onisciência\", pude prever.\nE... certamente, continuará sendo assim."
20054-CVGroup_Relationship_Up_4-1 = "Posso desabafar um pouco...?\nFique ao meu lado, só por agora.\nObrigada, Sensei.\n...Estou muito feliz."
