[translation]
20058-CVGroup_CommonSkill-1 = "Может, постараешься чуточку лучше?"
20058-CVGroup_ExSkill_1-1 = "Что же мне взять... \n...Хмм. \nПожалуй, выберу вот это."
20058-CVGroup_ExSkill_2-1 = "Хмм... \nО... \nА это миленько!"
20058-CVGroup_ExSkill_3-1 = "Хмм-хмм-хмм~ \nА? \nЭто точно нужно купить."
20058-CVGroup_ExSkill_Level_1-1 = "На, держи."
20058-CVGroup_ExSkill_Level_2-1 = "Возьми, если хочешь."
20058-CVGroup_ExSkill_Level_3-1 = "Это подарок."
20058-CVGroup_Formation_In_1-1 = "Хмм, я сегодня в отличном настроении."
20058-CVGroup_Formation_In_2-1 = "Мы идём вместе? Ладно."
20058-CVGroup_Formation_Select-1 = "Ой!? \nЭй, Сенсей... \n*Вздох*, мог бы и предупредить сначала."
20058-CVGroup_Growup_1-1 = "Хмм... так приятно. Словно подзаряжаюсь энергией~"
20058-CVGroup_Growup_2-1 = "Странно. Чувствую, будто силы прямо через край плещут~"
20058-CVGroup_Growup_3-1 = "Эй, Сенсей... Я бы хотела, чтобы ты сделал это снова."
20058-CVGroup_Growup_4-1 = "Это как-то затягивает... даже немного опасно."
20058-CVGroup_Relationship_Up_1-1 = "Что-то мы в последнее время часто видимся, Сенсей. С чего бы это?"
20058-CVGroup_Relationship_Up_2-1 = "Ты постоянно даришь мне столько всего. \nЯ рада, конечно, но... мне неловко просто так всё принимать. \nМожет, ты сам чего-нибудь хочешь, Сенсей?"
20058-CVGroup_Relationship_Up_3-1 = "Хмм... Кажется, я подсаживаюсь на это. \nНе балуй меня слишком сильно, ладно? А то проблем не оберёшься."
20058-CVGroup_Relationship_Up_4-1 = "Ну серьёзно... ты меня совсем разбалуешь, Сенсей. \n...Боже. Такое чувство, что в этой ситуации сердце бешено колотится только у меня одной."