[translation]
20050-CVGroup_CommonSkill-1 = "Ei!"
20050-CVGroup_ExSkill_1-1 = "Fufu, tenho algo perfeito aqui~♪"
20050-CVGroup_ExSkill_2-1 = "Trouxe algo incrível!"
20050-CVGroup_ExSkill_3-1 = "Tenho certeza que é por aqui...!"
20050-CVGroup_ExSkill_Level_1-1 = "Aqui, coma isso! Vamos dar o nosso melhor!"
20050-CVGroup_ExSkill_Level_2-1 = "Anime-se! Vamos lá!"
20050-CVGroup_ExSkill_Level_3-1 = "Ei, você ainda aguenta, né!"
20050-CVGroup_Formation_In_1-1 = "O que, o que? Vamos fazer alguma coisa?"
20050-CVGroup_Formation_In_2-1 = "Parece divertido! Me deixa participar também!"
20050-CVGroup_Formation_Select-1 = "Hum-hum-hum~♪ ...Ah, é o Sensei!"
20050-CVGroup_Growup_1-1 = "Eh! É para mim!? Sério mesmo~?"
20050-CVGroup_Growup_2-1 = "Com isso, vou conseguir carregar até as maiores rochas!"
20050-CVGroup_Growup_3-1 = "Obrigada, Sensei! Vou me esforçar ainda mais!"
20050-CVGroup_Growup_4-1 = "Olha só! Fiquei tão forte assim~!"
20050-CVGroup_Relationship_Up_1-1 = "Ei, ei, posso fazer uma estátua do seu rosto, Sensei?"
20050-CVGroup_Relationship_Up_2-1 = "...Então essa é a textura da sua pele, Sensei.\nHum! Acho que consigo reproduzir!"
20050-CVGroup_Relationship_Up_3-1 = "Ultimamente, quando sinto vontade de esculpir algo,\nsó consigo pensar no seu rosto, Sensei... Por que será?"
20050-CVGroup_Relationship_Up_4-1 = "Sabe... quando eu olho para você, Sensei...\nmeu peito fica apertado."
