[translation]
23003-CVGroup_CommonSkill-1 = "これは痛いよ。"
23003-CVGroup_ExSkill_1-1 = "電磁パルス、稼働開始。"
23003-CVGroup_ExSkill_2-1 = "EMPドローン稼働。"
23003-CVGroup_ExSkill_3-1 = "第1段階エミッター、作動開始。"
23003-CVGroup_ExSkill_Level_1-1 = "装備を停止する。"
23003-CVGroup_ExSkill_Level_2-1 = "予想通りか。"
23003-CVGroup_ExSkill_Level_3-1 = "みんな、後ろに下がって。"
23003-CVGroup_Formation_In_1-1 = "私の実力を証明して見せる機会だね。"
23003-CVGroup_Formation_In_2-1 = "任せて。"
23003-CVGroup_Growup_1-1 = "ふーん……これは目を見張る結果だね。"
23003-CVGroup_Growup_2-1 = "もっと多くのデータが必要だね。"
23003-CVGroup_Growup_3-1 = "このこみ上げる力も数値化できるのかな？"
23003-CVGroup_Growup_4-1 = "未知の知識を探求するのは、いつだって楽しいことだね。"
23003-CVGroup_Relationship_Up_1-1 = "この研究が終わったら……\n次は先生のことを研究してみたいな。"
23003-CVGroup_Relationship_Up_2-1 = "人の心も顕微鏡でのぞき込んで、見ることができたらいいのに。"
23003-CVGroup_Relationship_Up_3-1 = "先生に惹かれるこの心は、どんな力学で証明できるんだろう？"
23003-CVGroup_Relationship_Up_4-1 = "私の能力で時間を巻き戻せるのかって？さあ。\nでも私は、この瞬間を永遠に楽しみたいけど。"
