[translation]
26001-CVGroup_CommonSkill-1 = "貴方の狙いはすべて把握しました。"
26001-CVGroup_ExSkill_1-1 = "傍受開始。"
26001-CVGroup_ExSkill_2-1 = "しっ、傍受を始めます。"
26001-CVGroup_ExSkill_3-1 = "私の耳は誤魔化せません。"
26001-CVGroup_ExSkill_Level_1-1 = "……キャッチ。"
26001-CVGroup_ExSkill_Level_2-1 = "……見つけました。"
26001-CVGroup_ExSkill_Level_3-1 = "……エンカウント。\nリンクします。"
26001-CVGroup_Formation_In_1-1 = "素晴らしい判断です。"
26001-CVGroup_Formation_In_2-1 = "適切な選択だと考えます。"
26001-CVGroup_Growup_1-1 = "この調和された力は……\nまるで洗練されたオーケストラのようですね。"
26001-CVGroup_Growup_2-1 = "これで私はもっと強くなりました。\n試してもらっても構いません。"
26001-CVGroup_Growup_3-1 = "この滑らかな旋律……\nもっと聞きたいです。"
26001-CVGroup_Growup_4-1 = "これでもっとよく聞こえます。\n……先生の心拍の音まで。"
26001-CVGroup_Relationship_Up_1-1 = "心拍数上昇、血流加速、体温上昇。\n原因は……不明。"
26001-CVGroup_Relationship_Up_2-1 = "今まで先生と交わした、すべての会話は録音してあります。\nもしかして……聞きたいですか?"
26001-CVGroup_Relationship_Up_3-1 = "先生の声は私にとって音楽と同じです。\n私の心を高揚させますから。"
26001-CVGroup_Relationship_Up_4-1 = "……確信しました。\n先生は私にとって特別です。"
