[translation]
26009-CVGroup_CommonSkill-1 = "う、受け取ってください！"
26009-CVGroup_ExSkill_1-1 = "隠れるのは……\nまだ……自信があるから！"
26009-CVGroup_ExSkill_2-1 = "見つからないように……！"
26009-CVGroup_ExSkill_3-1 = "そこ……！"
26009-CVGroup_ExSkill_Level_1-1 = "ターゲット、確認しました！"
26009-CVGroup_ExSkill_Level_2-1 = "当たって……！"
26009-CVGroup_ExSkill_Level_3-1 = "う、動かないでください！"
26009-CVGroup_Formation_In_1-1 = "わ……わたしですか？\n 本当に……？"
26009-CVGroup_Formation_In_2-1 = "先生が一緒にいてくださるなら……\nわたしも……！"
26009-CVGroup_Formation_Select-1 = "うう……帰りたい……。"
26009-CVGroup_Growup_1-1 = "せ、先生！？\nえっと、その……あうう……。"
26009-CVGroup_Growup_2-1 = "いつも……ありがとうございます。\n先生がいてくださって……本当に、よかったです。"
26009-CVGroup_Growup_3-1 = "こうやって、一歩……踏み出せましたし……\nわたし自身も、変わりたいです。"
26009-CVGroup_Growup_4-1 = "今のわたしは、メイド……なので……\n先生の、お役に立ちたいです。"
26009-CVGroup_Relationship_Up_1-1 = "あの、先生……\nい、いえ！やっぱり、なんでもありません……。"
26009-CVGroup_Relationship_Up_2-1 = "先生がいてくださったから、頑張ることができました。\n言葉だけでは、伝えきれませんが……\nその……ありがとうございます。"
26009-CVGroup_Relationship_Up_3-1 = "先生は……その、メイドって、どう思います？\n……じゃあ、この格好は？"
26009-CVGroup_Relationship_Up_4-1 = "その……もう少し前向きなわたしになれたら、先生に言いたいことがあります。\nえっ、今ですか！？そ、それは……！"
