[translation]
40015-CVGroup_Battle_Buffed_1-1 = "Poder aumentado!"
40015-CVGroup_Battle_Defense_1-1 = "Esquiva elegante!"
40015-CVGroup_Battle_Recovery_1-1 = "Obrigada pela magia de cura!"
40015-CVGroup_Summon_Retreat_02-1 = "N-não pense que isso é o fim!!"
40015-CVGroup_CommonSkill_2-1 = "Lá vai minha magia suprema! Vai doer, hein!"
40015-CVGroup_Summon_Retreat_01-1 = "Adeus! Fui! Fiuuu! Vapt-vupt!"
