[translation]
10000-327 = "Сенсей. То дело, в котором вы помогли раньше, наконец-то завершилось."
10000-328 = "Клиент, кажется, остался весьма доволен."
10000-329 = "Хе-хе, вы хорошо поработали."
10000-330 = "О чём это ты?"
10000-331 = "Всё это благодаря президенту Ару!"
10000-332 = "Э? Неужели не помнишь?"
10000-333 = "Ну, тогда и правда было довольно суматошно..."
10000-334 = "К-короче...!"
10000-335 = "К-какое естественное умение жить, вот это по-взрослому...!"
10000-336 = "...нет, не то."
10000-337 = "Когда сотрудник добивается выдающихся результатов, нужно дать ему соответствующую награду."
10000-338 = "Я думаю, это тоже входит в обязанности президента."
10000-339 = "Ну же, что для Сенсея будет лучшей наградой?"
10000-340 = "Я подумала, вернувшись домой,"
10000-341 = "если скажу «давай съедим парфе из раздела сложных блюд в качестве награды»,"
10000-342 = "все, наверное, рассердятся."
10000-343 = "...И не думала, что за эффективностью скрывается такой пробел."
10000-344 = "Так что, э-это..."
10000-345 = "Сенсей, вы согласитесь составить мне компанию и в следующий раз?"
10000-346 = "Сенсей, для того чтобы стать президентом, нужны не только лидерские качества."
10000-347 = "Конечно, мои лидерские качества прекрасны,"
10000-348 = "но в работе требуются и другие способности."
10000-349 = "Другие способности?"
10000-350 = "Например?"
10000-351 = "Хе-хе-хе. Хотите узнать? Конечно хотите?"
10000-352 = "Тогда приходите сегодня в библиотеку. Я буду ждать вас, Сенсей."
10000-353 = "Сенсей, я пересмотрела своё мнение о вас."
10000-354 = "Но запомните:"
10000-355 = "в следующий раз я не дам себя так легко провести!"
10000-356 = "...Это отдельно. А вообще, давай как-нибудь позанимаемся вместе ♪"
10000-357 = "Сенсей, вы слышали тот разговор?"
10000-358 = "Говорят, тот легендарный фильм снова будут показывать."
10000-359 = "Если у вас будет время, не хотите сходить вместе?"
10000-360 = "Ура! Это свидание от Ару!"
10000-361 = "Ч-что, что вы такое говорите, Сенсей!?"
10000-362 = "Х-хватит говорить глупости, просто встречаемся у кинотеатра!"
10000-363 = "Сенсей, вы сегодня свободны?"
10000-364 = "Ага, свободен."
10000-365 = "Если Ару зовёт меня, то я просто обязан пойти."
10000-366 = "Х-хе-х...!? Н-ну, тогда ладно."
10000-367 = "Сегодня у меня есть важный разговор с вами."
10000-368 = "Позже зайдёте в офис нашей Бенрия?"
10000-369 = "Буду ждать."
10000-370 = "Разве вы можете видеть меня такой крутой, как сегодня, — это редкость, знаете ли?"
10000-371 = "Буду рассчитывать на вас и впредь, Сенсей!"
10000-372 = "...И кстати, тот звонок был действительно по работе! Честно!"
10000-100000010 = "Сенсей "
10000-100000020 = "И ещё раз... мы, вся Бенрия, искренне благодарны вам, Сенсей."
10000-100000030 = "Когда вы так говорите, мне становится неловко."
10000-100000040 = "Фу-фу-фу, это на вас не похоже."
10000-100000050 = "Если вы будете стесняться по таким мелочам, то дальше будет трудно."
10000-100000060 = "Тогда поменяемся ролями, пусть и Ару тоже станет неловко."
10000-100000070 = "Что это значит!?!?"
10000-100000080 = "Прости, просто хотел это сказать."
10000-100000090 = "Т-так вот..."
10000-100000100 = "Короче, по существу: в благодарность за вашу постоянную помощь"
10000-100000110 = "не хотите ли вместе поужинать?"
10000-100000120 = "С удовольствием!"
10000-100000130 = "Вот и хорошо."
10000-100000140 = "Тогда буду ждать вас, Сенсей."
