[translation]
10054-100540010 = "Olá, Sensei. É a Mari."
10054-100540020 = "Desculpe a mensagem repentina, mas eu gostaria de conversar sobre uma coisa..."
10054-100540030 = "É um pouco difícil para mim resolver sozinha..."
10054-100540040 = "Claro, o que aconteceu?"
10054-100540050 = "Aconteceu alguma coisa?"
10054-100540060 = "Ah... bem..."
10054-100540070 = "Não é nada tão sério assim..."
10054-100540080 = "Não é como se eu estivesse envolvida em algo perigoso ou coisa do tipo..."
10054-100540090 = "Mas fico muito feliz com a sua preocupação. Obrigada."
10054-100540100 = "Então, indo direto ao ponto... Você teria um tempo para mim amanhã de manhã?"
10054-100540110 = "Estarei esperando na Catedral."
10054-100540120 = "Sei que você deve estar muito ocupado, Sensei, mas..."
10054-100540130 = "Espero que possamos nos ver no dia do Grande Festival Kouhlin também."
10054-100540140 = "Espero que você tenha um dia maravilhoso hoje também, Sensei."
10054-100540150 = "Sensei..."
10054-100540160 = "Está tudo bem com você hoje?"
10054-100540170 = "Entrei em contato porque queria pelo menos te dar um oi..."
10054-100540180 = "Estou rezando para que você tenha um dia feliz, Sensei."
10054-100540190 = "???"
10054-100540200 = "Mari, o que foi?"
10054-100540210 = "...Mari?"
10054-100540220 = "..."
10054-100540230 = "Sensei...?"
10054-100540240 = "Hum, não aconteceu nada?\nQuando eu estava saindo, tive a impressão de ter ouvido um barulho surdo..."
10054-100540250 = "Deve ter sido só impressão sua."
10054-100540260 = "Eu tive a mesma impressão, mas está tudo bem. Não se preocupe."
10054-100540270 = "???"
10054-100540280 = "...E-Entendo."
10054-100540290 = "Entro em contato de novo mais tarde."
10054-100540300 = "Sensei... Hum, há algo que eu possa fazer por você?"
10054-100540310 = "Graças a você, Sensei, eu consegui crescer durante o Grande Festival Kouhlin."
10054-100540320 = "Então, eu queria te agradecer... mas não sei bem como..."
10054-100540330 = "Não precisa agradecer. Fico feliz só de ver que você está bem, Mari."
10054-100540340 = "Fiquei feliz em ver você se divertindo, Mari."
10054-100540350 = "Ahaha..."
10054-100540360 = "Realmente, não consigo competir com você, Sensei."
10054-100540370 = "...Entendido."
10054-100540380 = "Vou esperar pela oportunidade de poder te ajudar um dia."
10054-100540390 = "Não é bem uma substituição, mas por hoje..."
10054-100540400 = "Vou rezar para que você tenha um dia tranquilo, Sensei."
10054-100540410 = "Hum, Sensei."
10054-100540420 = "Se não for incômodo para você..."
10054-100540430 = "Eu estava pensando que seria legal se você viesse com roupas de ginástica da próxima vez."
10054-100540440 = "O parque é fresco e agradável, perfeito para se exercitar..."
10054-100540450 = "Então, depende da sua disponibilidade, Sensei, mas..."
10054-100540460 = "Hum..."
10054-100540470 = "Eu ficaria... feliz se pudéssemos nos exercitar juntos da próxima vez."
10054-100540480 = "Então... até mais."
