[translation]
10062-100620010 = "Sensei, ouvi dizer que você também está trabalhando hoje."
10062-100620020 = "A Schale parece sempre tão ocupada, não é?"
10062-100620030 = "Quem...?"
10062-100620040 = "Nessas horas, você precisa de uma assistente, certo?"
10062-100620050 = "Estou indo aí agora mesmo, Sensei."
10062-100620060 = "Sério, quem é!?"
10062-100620070 = "Sensei, você tem um momento?"
10062-100620080 = "Recebi uma carta estranha e não sei bem o que fazer."
10062-100620090 = "Se você estiver ocupado, estou pensando em resolver isso sozinha, mas..."
10062-100620100 = "Pensei em te consultar primeiro."
10062-100620110 = "A Toki está com problemas!? Você está bem? Estou indo aí agora!"
10062-100620120 = "Muito obrigada."
10062-100620130 = "Então, você poderia vir até a escola?"
10062-100620140 = "Ouvi dizer que hoje é o meu dia de plantão No Schale."
10062-100620150 = "Não há nenhum engano na agenda?"
10062-100620160 = "Estou ansiosa pelo seu primeiro plantão, Toki."
10062-100620170 = "...?"
10062-100620180 = "Não entendi muito bem, mas..."
10062-100620190 = "Farei o meu melhor para auxiliar e corresponder às suas expectativas, Sensei."
10062-100620200 = "Então, nos vemos mais tarde."
10062-100620210 = "Sensei."
10062-100620220 = "Hoje tive um compromisso que demorou um pouco mais, então parece que vou me atrasar."
10062-100620230 = "Peço desculpas por não poder te auxiliar no horário combinado."
10062-100620240 = "Tudo bem, mas é raro você se atrasar, Toki."
10062-100620250 = "Posso perguntar o que aconteceu?"
10062-100620260 = "Não."
10062-100620270 = "Não foi nada importante."
10062-100620280 = "Por favor, não se preocupe muito."
10062-100620290 = "Então, nos vemos mais tarde."
10062-100620300 = "Sensei. Creio que já está na hora de, entre nós,"
10062-100620310 = "haver uma "prova"."
10062-100620320 = "Gostaria de conversar com você sobre isso."
10062-100620330 = "O-o que você quer dizer!? O que é uma "prova"!?"
10062-100620340 = "Está tudo bem."
10062-100620350 = "Basta que eu entenda."
10062-100620360 = "Toki...?"
