[translation]
10115-101150010 = "Bom dia, Sensei!"
10115-101150020 = "Sou Rei Nomasa, do Clube de Beisebol da Millennium Science School!"
10115-101150030 = "Bom dia, Rei."
10115-101150040 = "Como você tem estado ultimamente?"
10115-101150050 = "Estou me esforçando para conseguir um home run."
10115-101150060 = "Hoje também pretendo praticar beisebol."
10115-101150070 = "Ah, é verdade."
10115-101150080 = "Se não for incômodo, Sensei, por que não vem assistir?"
10115-101150090 = "O campo de treino é aberto para visitantes."
10115-101150100 = "Bom dia, Sensei!"
10115-101150110 = "Muito obrigada por toda a ajuda no outro dia!"
10115-101150120 = "Fico feliz se pude ajudar, mas..."
10115-101150130 = "Na verdade, Sensei..."
10115-101150140 = "Para melhorar a rebatida,"
10115-101150150 = "Acho que não basta apenas praticar rebatidas."
10115-101150160 = "Percebi que outros treinamentos especiais também são necessários."
10115-101150170 = "Outros treinamentos especiais?"
10115-101150180 = "Isso mesmo."
10115-101150190 = "Acho que é mais rápido mostrar do que explicar."
10115-101150200 = "Como eu disse antes, o campo de treino é aberto para visitantes."
10115-101150210 = "Por favor, venha quando for conveniente para o Sensei."
10115-101150220 = "Sensei! Você se lembra do nosso compromisso de hoje, certo?"
10115-101150230 = "Vamos assistir a um jogo de beisebol, não é?"
10115-101150270 = "Como você conseguiu dois ingressos?"
10115-101150240 = "Estou feliz por poder ir com o Sensei!"
10115-101150250 = "O jogo de hoje é uma partida realmente incrível!"
10115-101150260 = "Por favor, esteja animado!"
10115-101150280 = "Primeiro a chegar, primeiro a ser servido... uma competição feroz onde um segundo pode decidir o destino..."
10115-101150290 = "Mas, de alguma forma, consegui pegá-los."
10115-101150300 = "Talvez isso também seja resultado do meu treinamento diário."
10115-101150310 = "Então, Sensei,"
10115-101150320 = "Estarei esperando por você no Browns Sox Stadium."
10115-101150330 = "Se você se atrasar, haverá uma penalidade!"
10115-101150340 = "Sensei! Hoje é o dia da inspeção de equipamentos do clube de beisebol!"
10115-101150350 = "Inspeção de equipamentos?"
10115-101150360 = "Vocês fazem a manutenção manual das luvas e outras coisas?"
10115-101150370 = "Não, isso é em outro dia."
10115-101150380 = "Como vamos enviar os equipamentos quebrados para a oficina de reparos,"
10115-101150390 = "Hoje, vamos verificá-los antes disso."
10115-101150400 = "Posso ir assistir?"
10115-101150410 = "Hã?"
10115-101150420 = "Eu, claro, ficaria feliz em ter você, mas..."
10115-101150430 = "Para ser sincera, não acho que seja algo tão divertido de assistir, sabe?"
10115-101150440 = "Não me importo com essas coisas."
10115-101150450 = "É mesmo?"
10115-101150460 = "Então, por favor, venha!"
10115-101150470 = "Hehe."
10115-101150480 = "Estarei esperando por você!"
