[translation]
10137-101370010 = "Давно не виделись, Сенсей."
10137-101370020 = "С вами говорит Шима Конока."
10137-101370030 = "Конока!?"
10137-101370040 = "Что-то ты непривычно вежливая..."
10137-101370050 = "О чём это вы?"
10137-101370060 = "По-моему, я всегда так разговариваю."
10137-101370070 = "А, точно. Просто в сегодняшнем гороскопе сказано: \"Представьтесь как следует\", так что..."
10137-101370080 = "...я решила сделать всё по правилам."
10137-101370090 = "Вот оно что! А я и не знал!"
10137-101370100 = "Сенсей... что с вами такое?"
10137-101370110 = "Ну да ладно. Загляните в Валькирию, как будет свободное время."
10137-101370120 = "Мне нужно обсудить с вами кое-какие административные вопросы."
10137-101370130 = "Вообще-то, ситуация довольно паршивая."
10137-101370140 = "Ты в порядке?"
10137-101370150 = "А, ну, пустяки, бывало и хуже."
10137-101370160 = "Я просто рада, что в холодильнике нашлось молоко."
10137-101370170 = "А ту сегодняшнюю дeвочку... её привлекут к дисциплинарной ответственности?"
10137-101370180 = "Конечно нет."
10137-101370190 = "Человек, способный настолько сильно подозревать окружающих, на самом деле отлично подходит для Валькирии."
10137-101370200 = "Будь я новичком, наверняка поступила бы точно так же, понимаете?"
10137-101370210 = "Как круто! Нашего Замдиректора ничем не проймёшь!"
10137-101370220 = "Ну, в этот раз я тоже виновата..."
10137-101370230 = "Хоть в гороскопе и было сказано представиться нормально, я этого не сделала..."
10137-101370240 = "Так что сама виновата."
10137-101370250 = "Как поживаете, Сенсей?"
10137-101370260 = "Совет дня на сегодня, кажется, \"будьте пунктуальны\"."
10137-101370270 = "Ну, приходить вовремя — это же просто базовое приличие, верно?"
10137-101370280 = "Хотя порой это на удивление трудно."
10137-101370290 = "Вообще, в гороскопах обычно советуют то, что и так нужно делать постоянно.."
10137-101370300 = "Но когда видишь это чёрным по белому, невольно начинаешь следить за собой усерднее."
10137-101370310 = "В общем, просто захотелось поделиться сегодняшним предсказанием!"
10137-101370320 = "Хорошего дня! Увидимся!"
10137-101370330 = "Похоже, я вас удивила, да?"
10137-101370340 = "Эх~ как же круто следовать советам гороскопа прямо с самого утра!"
10137-101370350 = "А разве строгая пунктуальность... была не вчерашним советом?"
10137-101370360 = "А?"
10137-101370370 = "Ой..."
10137-101370380 = "Эм-м, сегодняшний, значит..."
10137-101370390 = "\"Не зацикливайтесь на времени.\""
10137-101370400 = "..."
10137-101370410 = "А-ха-ха..."
10137-101370420 = "У меня тут есть засекреченная информация..."
10137-101370430 = "Ну, вам-то, Сенсей, я могу её рассказать."
10137-101370440 = "Сейчас скину адрес, встретимся там."
10137-101370450 = "Йо, Сенсей."
10137-101370460 = "Сегодняшний совет дня: \"действуйте сообща с напарником\"!"
10137-101370470 = "Так что... побудете моим напарником на сегодня?"
10137-101370480 = "Я на вас рассчитываю!"
10137-101370490 = "Ой-"
10137-101370500 = "Я сегодня взяла больничный, так что..."
10137-101370510 = "...просто делайте то, что посчитаете нужным."
10137-101370520 = "Оставляю всё на вас~"
10137-101370530 = "??"
10137-101370540 = "Это что ещё за реакция? Вы так с начальством разговариваете? Хех..."
10137-101370550 = "Я простудилась во время того расследования на днях."
10137-101370560 = "В общем, присмотрите там за всем вместо меня."
10137-101370570 = "Полностью! Здорова!"
10137-101370580 = "Сенсей, спасибо за помощь на днях."
10137-101370590 = "Вы ведь не заразились от меня?"
10137-101370600 = "Я в порядке!"
10137-101370610 = "Всего лишь небольшая температура, горло болит и всё тело ломит!"
10137-101370620 = "Да это стопроцентная простуда!"
10137-101370630 = "Что ж, тогда..."
10137-101370640 = "В знак благодарности я приду тебя проведать."
10137-101370650 = "Угощу тебя тонкацу рамэном!"