[translation]
13012-130120010 = "Сенсей, время патруля!"
13012-130120020 = "Вчера был северный район, так что сегодня давайте обойдём центральный!"
13012-130120030 = "Сегодня, кажется, выходной..."
13012-130120040 = "Нельзя ли сегодня отдохнуть...?"
13012-130120050 = "Так не пойдёт! Происшествия случаются не в переговорной, а на местах!"
13012-130120060 = "Пока мы наслаждаемся приятным послеобеденным сном..."
13012-130120070 = "где-то может происходить крупное преступление, которое горожане не могут решить!"
13012-130120080 = "Тем более не хочется идти..."
13012-130120090 = "Сенсей, происшествие!"
13012-130120100 = "Похоже, в ювелирном магазине в городе Шиба проблемные студенты взяли заложников и забаррикадировались!"
13012-130120110 = "И, похоже, из-за пробок переговорщик задерживается..."
13012-130120120 = "..."
13012-130120130 = "Если я воспользуюсь этим шансом, прибуду на место первой и проведу успешные переговоры..."
13012-130120140 = "признают ли тогда мои способности начальники Валькирии?"
13012-130120150 = "Не лучше ли подождать профессионального переговорщика...?"
13012-130120160 = "...Нет, я решила. Даже сейчас заложники дрожат от страха."
13012-130120170 = "Хотя я ещё не официальный полицейский, я не могу стоять на месте."
13012-130120180 = "Кирино, выезжаю!"
13012-130120190 = "Уу, Сенсей...(T_T)"
13012-130120200 = "Из-за того недавнего дела с заложниками я получила предупреждение от начальства..."
13012-130120210 = "Если бы только моё мастерство стрельбы было лучше..."
13012-130120220 = "Сенсей, как улучшить навыки стрельбы?"
13012-130120230 = "Это немного сложный вопрос для меня..."
13012-130120240 = "Ну, тогда... хотя бы в следующий раз не могли бы вы понаблюдать за мной со стороны, когда я буду стрелять?"
13012-130120250 = "Я слышала, что для повышения точности важно исправить плохие привычки и позу во время стрельбы!"
13012-130120260 = "Да, тогда с удовольствием."
13012-130120270 = "Спасибо, Сенсей!"
13012-130120280 = "Тогда я буду ждать вас в школьном тире!"
13012-130120290 = "Сенсей, я ужасно нервничаю..."
13012-130120300 = "Что случилось? У тебя экзамен после этого?"
13012-130120310 = "Сегодня днём дети из соседнего детского сада придут на экскурсию в полицейскую академию Валькирии..."
13012-130120320 = "и мне поручили проводить эту экскурсию."
13012-130120330 = "Я очень переживаю, вдруг я сделаю что-то не так..."
13012-130120340 = "Если я тоже пойду, я могу поддержать тебя рядом?"
13012-130120350 = "Э, правда можно?"
13012-130120360 = "Тогда я спокойна, спасибо, Сенсей!"
13012-130120370 = "Ты выглядишь очень воодушевлённой, так что если я могу помочь, с радостью."
13012-130120380 = "Мне очень поможет. Да, раз уж это возможность, я хочу показать детям, какие крутые бывают полицейские."
13012-130120390 = "Ведь когда я была маленькой, я тоже ходила на такую экскурсию и тогда решила стать полицейским..."
13012-130120400 = "Я должна показать им себя такой же крутой, как те полицейские тогда...!"
13012-130120410 = "Кирино, одно предостережение."
13012-130120420 = "Да, что именно?"
13012-130120430 = "Только не доставай оружие. Малыши могут пострадать, это опасно."
13012-130120440 = "Э-это...! Х-хотя мне это и не по душе, но... да, конечно..."