[translation]
20003-2136 = "Bom trabalho hoje também."
20003-2137 = "Você também, Mashiro, bom trabalho."
20003-2138 = "Graças ao Sensei, hoje também conseguimos repelir o mal sem ferimentos e em segurança."
20003-2139 = "O comando do Sensei foi maravilhoso hoje também. Aprendi muitas coisas com você."
20003-2140 = "Ah, falando nisso..."
20003-2141 = "Falando nisso?"
20003-2142 = "Houve algum outro problema?"
20003-2143 = "Não, é que... a costura da minha saia descosturou durante a operação..."
20003-2144 = "Se não parecer que dá para consertar, talvez eu precise pegar um uniforme reserva."
20003-2145 = "Recentemente, li um livro interessante sobre justiça."
20003-2146 = "Sobre como alguém que busca a justiça deve agir em diversas situações..."
20003-2147 = "Era um livro que ensinava sobre esse tipo de coisa."
20003-2148 = "Tipo um... Manual do Herói da Justiça?"
20003-2149 = "Existe algum livro para quem busca o mal também?"
20003-2150 = "Certamente, pode ser algo próximo disso. Foi muito interessante."
20003-2151 = "Isso, sinto muito, eu não saberia dizer..."
20003-2152 = "Mas, lendo, houve algumas partes que não consegui entender."
20003-2153 = "Acho que é porque meu entendimento sobre justiça ainda é insuficiente..."
20003-2154 = "Se não se importar, Sensei. Você poderia me ensinar sobre a justiça?"
20003-2155 = "Sobre a justiça...?"
20003-2156 = "Terminei o treinamento de hoje no Schale. Voltarei para a academia agora."
20003-2157 = "Que tipo de treinamento um atirador faz normalmente?"
20003-2158 = "Está curioso sobre o treinamento de atiradores?"
20003-2159 = "Bem, basicamente não é tão diferente dos outros."
20003-2160 = "Se for para citar uma diferença, seria o aprendizado das técnicas de camuflagem."
20003-2161 = "Posso assistir um dia?"
20003-2162 = "Não me importo que assista, mas... não acho que seja algo particularmente interessante."
20003-2163 = "Como mencionei antes, gostaria de reforçar."
20003-2164 = "Devido ao treinamento de hoje, alterei o turno que estava planejado para outro dia."
20003-2165 = "Conto com sua compreensão."
20003-2166 = "Sim, entendido. Aliás, posso ir junto no treinamento de hoje?"
20003-2167 = "Você vai me ajudar no treinamento?"
20003-2168 = "Sim, tudo bem?"
20003-2169 = "Não há problema, mas... o de hoje é um pouco puxado, então é melhor estar preparado."
20003-2170 = "( ºㅁº )"
20003-2171 = "Ei, Sensei... você está bem?"
20003-2172 = "No caminho de volta, você estava com uma expressão como se sua alma tivesse saído do corpo..."
20003-2173 = "( ºㅁº )"
20003-2174 = "Será que aquele treinamento foi um pouco rigoroso demais de repente?"
20003-2175 = "( ºㅁº )"
20003-2176 = "Sensei!?"
20003-2177 = "Agora é o momento de realizar a justiça!"
20003-2178 = "O que houve?"
20003-2179 = "Finalmente chegou a hora de minha vida chegar ao fim..."
20003-2180 = "Hã? Sensei, você fez algo contra a justiça?"
20003-2181 = "Bem, de acordo com as informações das veteranas,"
20003-2182 = "um vilão cruel e perverso do mercado negro passará perto da"
20003-2183 = "Academia Trinity ao meio-dia de hoje."
20003-2184 = "Vamos esperar no telhado do prédio e atirar nesse vilão!"
20003-2185 = "Atirar, que medo..."
20003-2186 = "O treinamento terminou mais cedo do que o esperado hoje, não é?"
20003-2187 = "Graças ao nosso esforço, parece que teremos um tempo livre."
20003-2188 = "Mashiro, o que você costuma fazer nessas horas?"
20003-2189 = "Bem, eu costumo ler ou dar uma caminhada, mas..."
20003-2190 = "Eu também gosto de subir em lugares altos."
20003-2191 = "Lugares altos...?"
20003-2192 = "Essa reação... será que esse é um hobby incomum?"
20003-2193 = "Eu achava que era um hobby normal..."
20003-200030010 = "Eu gostaria de perguntar uma coisa..."
20003-200030020 = "Você gosta de ler?"
20003-200030030 = "Mais ou menos..."
20003-200030040 = "Entendo."
20003-200030050 = "Você está lendo livros sobre justiça?"
20003-200030060 = "Não, não é isso."
20003-200030070 = "Eu só estava curiosa."
