[translation]
20018-200180370 = "Сенсей, ты вчера случайно не был в парке Ширатори?"
20018-200180380 = "Мне показалось, что я видела, как ты бегаешь..."
20018-200180390 = "Моэ тоже там была."
20018-200180400 = "Надо было подойти и поздороваться."
20018-200180410 = "Я подумала, что ты работаешь, поэтому не хотела беспокоить..."
20018-200180420 = "Значит, я могла бы спокойно поговорить с тобой?"
20018-200180430 = "Ты всегда можешь подойти. Я в последнее время увлекся бегом."
20018-200180440 = "В конце концов, постоянно сидеть на одном месте вредно для здоровья."
20018-200180450 = "А-а, тут я тебя понимаю."
20018-200180460 = "Если сидеть слишком долго, то начинаешь горбиться, а плечи так и затекают, да?"
20018-200180470 = "Я знаю, что следить за осанкой важно, но..."
20018-200180480 = "Не хочешь как-нибудь потренироваться вместе со мной, Моэ?"
20018-200180490 = "Сенсей, ты часом не забыл, что я оперативник?"
20018-200180500 = "Вообще-то я боец SRT. И тренируюсь абсолютно каждый день."
20018-200180510 = "Ну, положим, не так много, как Саки или Мияко."
20018-200180520 = "Но пробежка с тобой... это может закончиться катастрофой, тебе не кажется?"