[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
20018-200180010 = "E aí, quanto tempo, Sensei" 
20018-200180020 = "Ouvi uns boatos de que cê tava me caçando……" 
20018-200180030 = "Qual foi?" 
20018-200180040 = "Olá, Moe" 
20018-200180050 = "Desculpe pelo incômodo, mas eu gostaria da sua ajuda com uma coisinha, você está livre agora?" 
20018-200180060 = "Ajuda pro Sensei? De boa pra mim, mas……" 
20018-200180070 = "Cê pedindo a minha ajuda é uma raridade" 
20018-200180080 = "Ah, relaxa que não tem nenhum motivo mórbido pra isso não. É só que eu sinto que isso tem cheirinho de caos, sabe…… Kuhihi" 
20018-200180090 = "Enfim, tô indo me arrumar" 
20018-200180100 = "Sensei, eu tava rodando por aí e chegou um bagulho bem interessante nos meus ouvidos……" 
20018-200180110 = "É verdade que todos os dados do PC da Schale sumiram de vez?" 
20018-200180120 = "Kuhihi…… Pois é……" 
20018-200180130 = "Isso, no fim das contas, foi tudo por água abaixo…… Kuhihi……" 
20018-200180140 = "Wow…… O Sensei tá soltando a mesma risadinha maléfica que eu dou" 
20018-200180150 = "A porra aí deve estar bem séria, hein" 
20018-200180160 = " É... você vai entender quando chegar aqui……" 
20018-200180170 = "Saquei, chego na Schale no finzinho da tarde" 
20018-200180180 = "Sensei, você sabia?" 
20018-200180190 = "Aquelas capinhas de segurança de plástico por cima de botões de emergência.\nAquilo chama 'Molly Guard'." 
20018-200180200 = "E pra você não se perguntar de onde esse nome veio" 
20018-200180210 = "Dizem que foi por causa de uma criança chamada Molly, que não parava quieta e sempre tentava apertar o botão de emergência" 
20018-200180220 = "Entendi" 
20018-200180230 = "Isso com certeza é muito interessante" 
20018-200180240 = "Mas toda vez que eu escuto essa história, me bate uma tristeza, sabia" 
20018-200180250 = "Se eu tivesse nascido muito antes da Molly" 
20018-200180260 = "Agora a capa de segurança seria conhecida mundialmente como 'Moe Guard', quem sabe……" 
20018-200180270 = "Eu não acho que isso seria um título lá muito lisonjeiro de se ter……" 
20018-200180280 = "Hm, Sensei, foi mal te pedir de supetão mas……" 
20018-200180290 = "Pode dar um pulinho no Parque dos Coelhinhos rapidão?" 
20018-200180300 = "Sem problemas, mas……" 
20018-200180310 = "O que houve tão de repente?" 
20018-200180320 = "Os suprimentos extras que encomendamos chegaram e tão empilhados no parque" 
20018-200180330 = "Mas as meninas tão numa missão, então eu tive que carregar tudo sozinha e……" 
20018-200180340 = "Ter que carregar essa caralhada de bagulho pesado já é osso duro de roer…… Mas ignorando essa parte" 
20018-200180350 = "Tem um monte de materiais altamente inflamáveis e perigosos aí no meio……" 
20018-200180360 = "Estou indo!" 
20018-200180370 = "Sensei, você tava no Parque Shiratori ontem?" 
20018-200180380 = "Achei ter visto você correndo que nem doido por lá……" 
20018-200180390 = "A Moe estava lá também, é" 
20018-200180400 = "Poderia ter me dado um alô, sabe" 
20018-200180410 = "Jurei que cê tava fazendo algum exercício prático a trabalho, então resolvi não te cortar a brisa……" 
20018-200180420 = "Então era de boas te interromper?" 
20018-200180430 = "Claro, seria ótimo. Resolvi fazer corrida matinal por esses dias" 
20018-200180440 = "Afinal de contas, ficar só sentado o dia todo é muito ruim pra saúde" 
20018-200180450 = "Ah, te entendo perfeitamente nessa" 
20018-200180460 = "Ficar plantada numa cadeira acaba zoando com a coluna e dá mó dor no pescoço" 
20018-200180470 = "Sei que a postura é chave pra evitar isso, mas né……" 
20018-200180480 = "Nesse caso, gostaria de tentar se exercitar comigo?" 
20018-200180490 = "Sensei, você não esqueceu de que eu sou das Forças Especiais da SRT, né?" 
20018-200180500 = "Apesar das aparências, eu faço parte da SRT. Minha cota de treinamento diária tá em dia, saca?" 
20018-200180510 = "Bem, quer dizer, não chego nem perto do nível de psicopatia da Saki ou da Miyako, mas" 
20018-200180520 = "Por outro lado, dar uma corridinha de leve com você, Sensei…… não soa como a pior catástrofe que poderia me acontecer" 