[translation]
20024-200240010 = "Faz tempo que não nos vemos."
20024-200240020 = "Como vai você, Sensei?"
20024-200240030 = "Nagisa, quanto tempo."
20024-200240040 = "Sim, faz bastante tempo, de fato."
20024-200240050 = "Na verdade, eu gostaria de conversar com você sobre as alunas de Trinity."
20024-200240060 = "Não é nada muito sério, então pensei se poderíamos conversar enquanto tomamos um chá da tarde. O que acha?"
20024-200240070 = "Ah, claro. Com certeza."
20024-200240080 = "Fufu."
20024-200240090 = "Então, prepararei um bom chá e estarei esperando por você."
20024-200240100 = "Peço desculpas por ter me retirado mais cedo, Sensei."
20024-200240110 = "De repente, comecei a me sentir mal... Sinto muito por não ter cuidado bem da minha saúde."
20024-200240120 = "Está tudo bem, não se preocupe."
20024-200240130 = "O chá de garrafa, será que não agradou o seu paladar?"
20024-200240140 = "Desculpe por ter insistido para você tomar..."
20024-200240150 = "Não, foi uma experiência muito interessante. Obrigada..."
20024-200240160 = "Mas, da próxima vez, talvez seja melhor eu controlar a quantidade que consumo..."
20024-200240170 = "...Peço desculpas pelo ocorrido outro dia."
20024-200240180 = "Como você tem passado ultimamente?"
20024-200240190 = "Você melhorou daquele mal-estar?"
20024-200240200 = "Ah, sobre o outro dia..."
20024-200240210 = "Estou bem. Não foi nada grave, então não se preocupe."
20024-200240220 = "Aliás, houve algo que não consegui te falar outro dia. Se não for incômodo, poderia me conceder um pouco do seu tempo?"
20024-200240230 = "Quando estiver livre, por favor, venha até o terraço."
20024-200240240 = "Vou preparar um chá para nós."
20024-200240250 = "Certo, entendido. Quer que eu leve aquele chá de antes?"
20024-200240260 = "Bem, isso não será necessário. Já provei o suficiente outro dia..."
20024-200240270 = "...Como você tem passado?"
20024-200240280 = "Outro dia, acabei mostrando uma imagem um tanto deplorável..."
20024-200240290 = "Gostaria de esclarecer que não costumo agir daquela maneira habitualmente..."
20024-200240300 = "Não se preocupe com isso."
20024-200240310 = "Mesmo dizendo isso... Como parte do Tea Party, não posso simplesmente ignorar tal falha."
20024-200240320 = "...Se não se importar, poderia me conceder um tempo para que eu possa me desculpar?"
20024-200240330 = "As novas folhas de chá que encomendei chegarão em breve."
20024-200240340 = "Deixe-me oferecer um chá. Se for conveniente para você, Sensei."
20024-200240350 = "Nesse caso, aceito o convite."
20024-200240360 = "Obrigada. Então, estarei esperando no terraço."
20024-200240370 = "Bom dia, Sensei."
20024-200240380 = "Dizem que o dia começa com o café da manhã... Você já comeu?"
20024-200240390 = "Sim, acabei de comer. E você, Nagisa?"
20024-200240400 = "Eu tomei uma sopa de missô agora pouco."
20024-200240410 = "...Isso é um pouco surpreendente."
20024-200240420 = "Eu tinha a impressão de que o Tea Party só comia doces..."
20024-200240430 = "O que você está dizendo..."
20024-200240440 = "Por mais que gostemos, comer apenas doces não é nada equilibrado nutricionalmente."
20024-200240450 = "Nós não vivemos apenas de bolos e doces o tempo todo."
