[translation]
23005-2194 = "Olá, Sensei. É a Ayane."
23005-2195 = "Você teria um momento?"
23005-2196 = "Tudo bem, o que houve?"
23005-2197 = "Estou um pouco ocupado, mas se for pela Ayane, não tem problema nenhum!"
23005-2198 = "Obrigada. Na verdade..."
23005-2199 = "E-eh, bem, ahaha... O-obrigada."
23005-2200 = "Na verdade..."
23005-2201 = "É um pedido de conselho, ou melhor, algo que eu gostaria que você ouvisse..."
23005-2202 = "Tem algo sobre o que eu gostaria de conversar."
23005-2203 = "Desculpe pelo repentino!"
23005-2204 = "Sim, entendi."
23005-2205 = "Não, está tudo bem."
23005-2206 = "O-obrigada! Então, no próximo feriado, vamos nos encontrar na escola!"
23005-2207 = "Sensei, sobre aquele livro..."
23005-2208 = "Eu pedi para avaliarem em uma loja de antiguidades no centro comercial,"
23005-2209 = "e disseram que é apenas um romance popular antigo sem muito valor..."
23005-2210 = "Ah, entendo..."
23005-2211 = "Entendi..."
23005-2212 = "Ahaha... mas, mesmo assim, recebi 1200 ienes por ele."
23005-2213 = "Disseram que não tinha valor, mas parece que valeu isso."
23005-2214 = "Então não foi perda de tempo."
23005-2215 = "Que bom, né?"
23005-2216 = "Sim, é verdade."
23005-2217 = "Talvez eu peça outros conselhos estranhos no futuro, conto com você, Sensei."
23005-2218 = "Sensei, tenho boas notícias."
23005-2219 = "Encontrei algo na escola,"
23005-2220 = "e parece que vai render um bom dinheiro."
23005-2221 = "Fufu, talvez seja um golpe de sorte."
23005-2222 = "Que tipo de coisa?"
23005-2223 = "Parece ser ferro comum, mas,"
23005-2224 = "como tem bastante, acho que vai render um bom valor."
23005-2225 = "Posso ir ver também?"
23005-2226 = "Eh?"
23005-2227 = "Ah, sim, claro que pode, mas..."
23005-2228 = "Bom trabalho, Sensei."
23005-2229 = "Você está bem...?"
23005-2230 = "Sim, estou bem."
23005-2231 = "Meus óculos estão tortos e, bem, meu uniforme rasgou um pouco, mas..."
23005-2232 = "Dobramos o valor! É nossa vitória!"
23005-2233 = "Bom trabalho..."
23005-2234 = "Ultimamente, as instalações da escola têm quebrado com frequência, e estou um pouco preocupada."
23005-2235 = "Ontem, a energia ficou cortada por duas horas..."
23005-2236 = "E anteontem, a água também parou de funcionar."
23005-2237 = "Será que aconteceu algum problema nas instalações subterrâneas...?"
23005-2238 = "Por que não chama um profissional?"
23005-2239 = "Não seria melhor chamar alguém que entenda para dar uma olhada?"
23005-2240 = "Se eu chamar profissionais para ver todos os lugares suspeitos, vai custar uma fortuna..."
23005-2241 = "Vou ter que arranjar tempo para consertar aos poucos, talvez nos dias de folga..."
23005-2242 = "Quer que eu ajude?"
23005-2243 = "Vamos consertar juntos."
23005-2244 = "Ah…… é sério?"
23005-2245 = "Sendo assim, aceitarei sua gentileza. Obrigada, Sensei."
23005-2246 = "Bom trabalho hoje, Sensei."
23005-2247 = "Graças a você, conseguimos terminar o conserto sem problemas."
23005-2248 = "Sim, bom trabalho."
23005-2249 = "Ayane, bom trabalho para você também."
23005-2250 = "Bem... hum..."
23005-2251 = "Sobre isso..."
23005-2252 = "Hm?"
23005-2253 = "O que houve?"
23005-2254 = "Eu poderia... te chamar de novo? Sobre isso..."
23005-2255 = "Hoje eu acabei te causando problemas, mas... eu, com o Sensei..."
23005-2256 = "Claro que sim."
23005-2257 = "Claro, pode me chamar quando quiser."
23005-2258 = "……Muito obrigada, Sensei."
23005-2259 = "Então, entrarei em contato novamente."
