[translation]
26016-260160010 = "★Weekly Pandemonium★ Special Event for our beloved readers!"
26016-260160020 = "Why not try writing an article yourself? Apply now!"
26016-260160030 = "Eh...?"
26016-260160040 = "The readers write the articles...?"
26016-260160050 = "Ah, you're suspicious, aren't you..."
26016-260160060 = "Ah, geez! I admit it!"
26016-260160070 = "It's just an excuse to hang out with you, Sensei!"
26016-260160080 = "It's lonely gathering materials all by myself..."
26016-260160090 = "You're very honest..."
26016-260160100 = "Of course! Taking the truth out of Weekly Pandemonium would be like taking the noodles out of ramen!"
26016-260160110 = "People tell me, \"Isn't that just soup?\"... but anyway!"
26016-260160120 = "Well then, I'll be waiting for you!"
26016-260160130 = "This is bad! The article was scrapped!"
26016-260160140 = "That restaurant from the other day, I wrote a feature article titled \"A Famous Restaurant Close to Home\", but..."
26016-260160150 = "During editing, I heard it went out of business!"
26016-260160160 = "Even though they had so many customers, I wonder why?"
26016-260160170 = "Profitable bankruptcy...?"
26016-260160180 = "I guess things like that happen too!"
26016-260160190 = "I've learned a lot!"
26016-260160200 = "This might be sudden, but do you know what the sea is, Sensei?"
26016-260160210 = "From what I hear, it's a place with a lot of water!"
26016-260160220 = "Well- of course, it's the sea!?"
26016-260160230 = "Yes!"
26016-260160240 = "By presenting an obvious fact like this,"
26016-260160250 = "I can draw people's interest! It's a type of journalistic technique!"
26016-260160260 = "So, let's actually go and see just how much water there is!"
26016-260160270 = "I don't know how we're going to check that, but understood!"
26016-260160280 = "Thank you for the valuable stories the other day!"
26016-260160290 = "If it hadn't been for that, I might not recovered..."
26016-260160300 = "Thanks to you, that really helped me out"
26016-260160310 = "As I thought, relying completely on memory is..."
26016-260160320 = "Very dangerous!"
26016-260160330 = "This week's manuscript is safely submitted!"
26016-260160340 = "But the content of the article is..."
26016-260160350 = "I feel like it's quite different from what we talked about..."
26016-260160360 = "While keeping it strictly based on facts... I dramatized it a little bit."
26016-260160370 = "Thanks to that, it's a hot topic!"
26016-260160380 = "Sensei, I owe you a big time!"
26016-260160390 = "Subscribe to \"Weekly Pandemonium\""
26016-260160400 = "Apply now..."
26016-260160410 = "I'm already subscribed though..."
26016-260160420 = "You seem kind of down?"
26016-260160430 = "Ugh..."
26016-260160440 = "I just can't think of any ideas for an article."
26016-260160450 = "Nothing interesting is happening..."
26016-260160460 = "If things keep going like this, I'll have no choice but to cause a huge incident myself..."
26016-260160470 = "I don't really get it, but stop right there!"
26016-260160480 = "How about going for a walk somewhere you might find a scoop?"
26016-260160490 = "Oh?"
26016-260160500 = "Ooh!"
26016-260160510 = "I can do that!"
26016-260160520 = "The spirit of visiting the scene a hundred times, right!"
26016-260160530 = "Well then, see you later!"
26016-260160540 = "I have to go too!?"
26016-260160550 = "Sensei, look at this!"
26016-260160560 = "Ta-da!"
26016-260160580 = "This week's Weekly Pandemonium has recorded its highest circulation ever!"
26016-260160590 = "Makoto-senpai even said she'd nominate me for this year's Reporter Award!"
26016-260160600 = "I'm the only reporter, but... anyway!"
26016-260160610 = "Thanks to you, Sensei, I was able to get a scoop!"
26016-260160620 = "I'm glad I could help!"
26016-260160630 = "Yes! I look forward to working with you again next time!"
26016-260160640 = "So, what happened to that kelp?"
26016-260160650 = "I took it to the kitchen and made pickled kelp!"
26016-260160660 = "Because storing it is a hassle!"
26016-260160670 = "You're not going to keep it safe!?"
26016-260160680 = "The summer feature article is finally reaching its climax!"
26016-260160690 = "This time, I'm thinking of doing the final adjustments at the sea!"
26016-260160700 = "I want to capture the atmosphere of the scene exactly as it is!"
26016-260160710 = "So with that said, could you come to the beach house?"
26016-260160720 = "I'll be waiting!"
26016-260160730 = "Um... Sensei..."
26016-260160740 = "Well..."
26016-260160750 = "No! It's nothing!"
26016-260160760 = "I forgot what I was going to say!"
26016-260160770 = "Well then! That's that!"