[translation]
10006-20 = "Você é o Sensei? De hoje em diante, eu ficarei com você. Se for uma missão, pode deixar comigo."
10006-30 = "Hmph, nada mal."
10006-40 = "Vamos descansar um pouco antes de ir."
10006-50 = "O pessoal do Comitê de Justiça... eles são um saco."
10006-60 = "Francamente, não tem jeito. Eu ajudo."
10006-70 = "Ah, como as coisas chegaram a esse ponto? Bem... não é como se fosse algo ruim."
10006-80 = "Ah, bem-vindo de volta. Sensei, qual é a missão de hoje?"
10006-90 = "Não tente matar aula. Eu estou sempre de olho em você."
10006-100 = "...Não, não foi nesse sentido!"
10006-110 = "Eu tenho um tempo livre agora... então vou te ajudar um pouco."
10006-120 = "Por que tem tanta gente causando problemas por aí?"
10006-130 = "Bem, eu não vou dizer que você deve seguir as regras cegamente."
10006-140 = "Se não as seguir, só terá que arcar com as consequências."
10006-150 = "Não existe regra que agrade a todos."
10006-160 = "É justamente por isso que é necessário impô-las."
10006-170 = "Sensei, eu confio na sua capacidade de comando."
10006-180 = "Hm?! O-o quê?! Hoje é seu aniversário?"
10006-190 = "N-não tem jeito. Hoje, bem... eu vou cooperar com qualquer missão que você tiver!"
10006-200 = "Obrigada por comemorar comigo."
10006-210 = "Eu cresci um pouco, afinal... talvez eu deva começar a levar as coisas mais a sério daqui para frente...?"
10006-220 = "Sensei. Vamos nos esforçar juntos neste novo ano também."
10006-230 = "Natal, é? Hoje em dia, perdeu o seu significado original."
10006-240 = "Bem, o significado atual não é ruim."
10006-250 = "Gostosuras ou travessuras, é? Bem, é um dia interessante."
10006-260 = "O que acha, Sensei? Não quer sair um pouco comigo?"
10006-280 = "Que cara é essa? Você não está pensando em nada estranho, está?"
10006-290 = "Vai ficar olhando até quando? Anda logo."
10006-300 = "Nnn... mmm... ah..."
10006-310 = "Se doeu? Hmph, uma integrante do Comitê Disciplinar de Gehenna não sentiria dor por algo assim!"
10006-320 = "É só que... foi um pouco de cócegas."
10006-330 = "O que está fazendo? A bandagem vai soltar."
10006-340 = "Se for você, Sensei... eu não me importo se nossas mãos se tocarem."
10006-350 = "Faça direito, até o fim."
10006-2600 = "Vou retribuir com resultados. É a única forma de provar o que estou sentindo agora."
