[translation]
10013-20 = "Kihihihihihihiii~~\nKyahahahaha!"
10013-30 = "Ah... Uwaaaa... \nO que eu faço, o que eu faço."
10013-40 = "Por favor, não fale\ncomigo..."
10013-50 = "Eu vou ficar\nno cantinho..."
10013-60 = "O-olá..."
10013-70 = "U-uwaaaa..."
10013-80 = "O... Olá, Sensei. \nEu estava vigiando aqui."
10013-90 = "Tsurugi, em espera! \nE-eu conto com você!!"
10013-100 = "H-hoje também é um\nótimo dia, nééé!!"
10013-110 = "...N-não! Não é isso! \nO que eu deveria dizer?!"
10013-120 = "Kihihi. Ihihihihi~"
10013-130 = "...A-ah? \nV-você estava olhando? \nHauwwawawa!?!?"
10013-140 = "Ah... \nO... \nPor favor, fale sobre qualquer coisa."
10013-150 = "E-eu não entendo muito\nsobre o trabalho dos adultos...!"
10013-160 = "M-mas! \nPor favor, deixe-me fazer isso!"
10013-170 = "(Quero ir para casa... \nEstou feliz por estar com você, mas \nsobre o que eu deveria conversar...)"
10013-180 = "A-aniversário?! \nO que eu deveria fazer?"
10013-190 = "O que eu preciso fazer?"
10013-200 = "A-aniversário? \nÉ o meu aniversário?"
10013-210 = "Sim? \nU-u-u-um encontro?"
10013-220 = "Encontro?"
10013-230 = "E-este ano também, \nconto com você~!"
10013-240 = "Natal... \nUm encontro de adultos..."
10013-250 = "Uwaaaaa! \nN-não é nada!!"
10013-260 = "Halloween... \nFestival... \nFesta..."
10013-270 = "Sim? \nN-não é nada!"
10013-290 = "(Fugir? \nDevo pular pela janela \nagora mesmo?)"
10013-300 = "(Será que vou morrer? Vou morrer, né? \nQuero morrer... Devo matar? \nNão, não, não!)"
10013-310 = "O-o-o-o que, \nv-você quer... conversar sobre..."
10013-320 = "U-um lugar como este... \nNão combina comigo..."
10013-330 = "Ah, uuu... \nEu ainda não estou pronta..."
10013-340 = "(Gyaaaaaaa~~! \nPor que eu vim parar \nem um lugar desses!!)"
10013-2600 = "Fufufufufu~\nUfufufufufufufufu~\nKuhahahahahahahahaha~!!"
