[translation]
10011-20 = "Sou Shun, instrutora do Departamento de Apoio Educacional Baikaen. Por favor, cuide bem das minhas crianças, s-e-n-s-e-i?"
10011-30 = "Fufu, que tal trazermos todos aqui para a próxima aula?"
10011-40 = "Ainda não é hora da soneca, mas... sinto que estou ficando com sono..."
10011-50 = "Será que Rinka está cuidando das crianças direitinho..."
10011-60 = "Ora, que adorável..."
10011-70 = "Fufu, que coisa mais fofa~"
10011-80 = "Bem-vindo, Sensei. Gostaria de jantar, ou talvez tomar um banho?"
10011-90 = "Ou será que... prefere uma aula?"
10011-100 = "Vamos retomar a aula que paramos na última vez, fufu."
10011-110 = "Ora, Sensei, você não pode ficar mimado comigo."
10011-120 = "Mas, se for só de vez em quando... eu posso abrir uma exceção, sabe?"
10011-130 = "Fufu, conto com você hoje também, está bem?"
10011-140 = "Sim~, é a Shun~"
10011-150 = "Bom garoto, bom garoto~"
10011-160 = "Se tocar de novo..."
10011-170 = "Vou ter que te dar uma bronca, viu?"
10011-180 = "Feliz aniversário para você♪ Feliz aniversário para você♬"
10011-190 = "Feliz aniversário, querido Sensei~♪ Feliz aniversário para você♬"
10011-200 = "Puxa... envelheci mais um ano..."
10011-210 = "Minha idade? Fufu, é segredo."
10011-220 = "Fufu, conto com você para mais este ano também~"
10011-230 = "Psiu, Sensei. Tome cuidado para não revelar o disfarce de Papai Noel."
10011-240 = "O coração puro das crianças é a coisa mais preciosa que existe."
10011-250 = "Ora, parece que as crianças ganharam muitos doces em algum lugar."
10011-260 = "Trick..."
10011-270 = "Como é mesmo que se diz?"
10011-290 = "Ora, você acordou."
10011-300 = "Hoje... foi realmente muito divertido. Fufu."
10011-310 = "Ora, já está na hora das crianças voltarem."
10011-320 = "Não seria melhor você voltar para o seu trabalho agora...?"
10011-330 = "Não, na verdade... fufu, fique um pouco mais, Sensei."
10011-340 = "Eu cuidarei da aula de hoje no seu lugar."
10011-350 = "Ah... que fofo... fufu."
10011-2600 = "Eu não queria ter que usar isto, mas... às vezes, um pouco de disciplina rigorosa por amor é necessária."
