[translation]
10010-20 = "Segunda anista do Comitê de Contramedidas de Abydos.\nSunaookami Shiroko. Prazer."
10010-30 = "Hmm...\nÉ um lugar bem espaçoso.\nSuficiente para fazer\num exercício moderado."
10010-40 = "Hum..."
10010-50 = "Para onde devemos ir\nna próxima pedalada?"
10010-60 = "O que o Sensei faz\ndepois da escola...?"
10010-70 = "Falando nisso, está na hora\nde inspecionar as armas."
10010-80 = "Se tiver algo que queira que eu faça,\né só pedir."
10010-90 = "Bem-vindo, Sensei.\nConto com você hoje também."
10010-100 = "Estou aqui para\najudar o Sensei."
10010-110 = "(Por que está me encarando\ntanto assim?)"
10010-120 = "...Ei, tem algo\nno meu rosto?"
10010-130 = "Ah, só queria olhar para o meu rosto?\n...E-entendo."
10010-140 = "Não é nada ruim\nficar assim com você."
10010-150 = "Feliz aniversário, Sensei. Que tal\ncomemorarmos fazendo uma corrida juntos?"
10010-160 = "...Não quer?"
10010-170 = "Meu aniversário...\nNão achei que você\nlembraria."
10010-180 = "Não, claro que estou feliz.\nSim. É verdade."
10010-190 = "Feliz Ano Novo, Sensei.\nConto com você este ano também."
10010-200 = "Feliz Natal.\nDizem que hoje é um dia especial."
10010-210 = "Não sei exatamente\no que o torna especial, mas..."
10010-220 = "Sensei, pode me explicar?"
10010-230 = "...Halloween.\nNão tenho memórias especiais.\nA cidade sempre foi silenciosa."
10010-240 = "Sim.\nSeria bom ver uma cidade\nmais movimentada."
10010-260 = "Tem algo que queira que eu faça?"
10010-270 = "(Fico curiosa sobre\no que você está pensando)"
10010-280 = "(O que será que você\npretende fazer agora...?)"
10010-290 = "Estou aqui para\najudar o Sensei."
10010-300 = "E-eu não me importo...\nque você me faça carinho assim..."
10010-2600 = "Será que eu fiquei um pouco mais forte? \nSim, assim poderei ser útil para todos."
