[translation]
10020-10 = "Blue Archive."
10020-20 = "Shimoe Koharu... E-eu já vou avisando, não pretendo ficar aqui por muito tempo...!"
10020-30 = "Uuu... Malditos populares..."
10020-40 = "Auuuu..."
10020-50 = "E-eu não tenho intenção de me enturmar."
10020-60 = "Se eu encontrar qualquer coisa indecente, vou confiscar tudo, entendeu?"
10020-70 = "Todos parecem estar se divertindo..."
10020-80 = "Ah, Sensei, bem-vindo de volta."
10020-90 = "Eu estava te esperando, Sensei."
10020-100 = "N-não vou tolerar mau comportamento na minha frente!"
10020-110 = "Não fale sobre as minhas notas! E-eu estou me esforçando, tá..."
10020-120 = "Vou me esforçar para me formar logo no Clube de Estudos Suplementares."
10020-130 = "C-coisas indecentes...?"
10020-140 = "I-isso não pode! Se eu encontrar, vou confiscar tudo! E queimar!"
10020-150 = "Como estudantes, vocês não deveriam estar namorando! Isso é insalubre!"
10020-160 = "Isso é proibido em Kivotos!"
10020-170 = "É o seu aniversário, Sensei. Acho que você poderia descansar um pouco hoje..."
10020-180 = "N-não, esquece o que eu disse, volte a trabalhar sério!"
10020-190 = "V-você lembrou do meu aniversário?"
10020-200 = "O-obrigada... Eu não achei que você fosse lembrar..."
10020-210 = "Talvez... eu esteja um pouco feliz...?"
10020-220 = "É Ano Novo, você tem certeza que quer ficar comigo?"
10020-230 = "E-eu não me importo, mas..."
10020-240 = "Q-qualquer comportamento impuro que suje a noite sagrada está proibido! Sensei, você está ouvindo!?"
10020-250 = "Doce? Eu já passei dessa fase faz tempo! E-eu sou mais madura..."
10020-260 = "N-não é nada."
10020-280 = "O-o que...!?"
10020-290 = "(Hã... espera... isso seria, por acaso...!?)"
10020-300 = "E-eu não disse nada de errado, disse!?"
10020-310 = "(Espera, será que se continuar assim, eu e o Sensei...!?)"
10020-320 = "(E-esse tipo de situação, eu já vi várias vezes nos livros...! Será que vai acontecer mesmo daquele jeito!?)"
10020-330 = "(A-aquilo, e aquilo outro também...)"
10020-340 = "(!? S-será que até isso...!?)"
10020-350 = "V-você finalmente mostrou sua verdadeira face, Sensei...!?"
10020-360 = "(Ferrou, ferrou, ferrou...! E-eu ainda não estou preparada para isso, de jeito nenhum!?)"
10020-2600 = "Eu também consegui chegar até aqui... Sensei, está vendo? Este é apenas o começo. Continue cuidando de mim, está bem?"
