[translation]
10035-10 = "Blue... Archive..."
10035-20 = "Uwaah...!?\nAh, Sensei, era você...\nEu não sabia quem era, levei um susto..."
10035-30 = "O, onde é que eu estou...\nExatamente...?"
10035-40 = "E, estou sentindo um olhar sobre mim...\nUuu..."
10035-50 = "É, talvez seja melhor do que\nficar lá fora..."
10035-60 = "Bem...\nAh, o que é aquilo...?"
10035-70 = "P, poderia evitar falar comigo\no máximo possível...\nAh, S, Sensei é uma exceção..."
10035-80 = "O, olá, Sensei...\nNa verdade, tem algumas alunas\nque eu gostaria de lhe recomendar..."
10035-90 = "……Eeh!? S, Sensei...!?\nDesde quando você estava\naí...?"
10035-100 = "E, eu não estava fazendo\nnada de estranho...!"
10035-110 = "E, eu só estava lendo\num livro de verdade...!"
10035-120 = "Normalmente, eu não me sinto à vontade\nfora da biblioteca antiga..."
10035-130 = "Mas aqui, de alguma forma, é bem...\nSerá que é porque\nvocê está aqui, Sensei...?"
10035-140 = "Ah, b, bem...\nN, não... não é\nnada..."
10035-150 = "Sensei, você parece\nestar sempre ocupado..."
10035-160 = "H, há algo em que eu possa\nte ajudar?"
10035-170 = "S, se houver, por favor...\nme avise!"
10035-180 = "Aqui também tem muitos livros..."
10035-190 = "……Eh, tem coisas que é melhor\nnão ver? \nS, sinto muito...!"
10035-200 = "F, feliz aniversário,\nSensei...!"
10035-210 = "Que tal tirar o dia de folga hoje...\nSe não se importar, gostaria de ler\num livro comigo...?"
10035-220 = "H, hoje é, tecnicamente,\no meu aniversário..."
10035-230 = "S, se você não se importar,\nna verdade..."
10035-240 = "P, posso me sentar...\nao seu lado...?"
10035-250 = "Um novo ano...\nSerá que eu consigo\nmudar...?"
10035-260 = "Se o Sensei estiver comigo,\ntalvez..."
10035-270 = "Uuu... q, que dia\nbarulhento..."
10035-280 = "Eu não gosto\nde barulho..."
10035-290 = "Ah, mas... em dias assim, eu gosto bastante\nde ler um livro em frente a uma\nlareira quentinha..."
10035-300 = "P, preciso reforçar\no sistema de segurança...!"
10035-310 = "Hoje é o dia em que muitos\nintrometidos sem noção aparecem...!"
10035-320 = "Eles insistem em vir aqui\npor causa de doces...!"
10035-330 = "Ah, céus...!"
10035-350 = "Ah, muito obrigada,\nSensei... isso, \nme ajudou muito..."
10035-360 = "……Isso? \nBem, eu estava fazendo\num trabalho de decodificação."
10035-370 = "Nesta biblioteca antiga...\nExistem muitos livros escritos\nem línguas antigas."
10035-380 = "Esses livros também devem estar\nesperando, guardando coisas que\nqueriam transmitir a alguém..."
10035-390 = "Não tem mais ninguém para fazer isso...\nEntão, eu..."
10035-400 = "……Sinto muito,\nfoi um assunto chato,\nnão foi?"
10035-410 = "……! Ah, bem, isso...\nReceber um elogio desses,\nisso..."
10035-420 = "Eu não sei o que responder...\nAs palavras simplesmente\ndesaparecem... Fufu..."
10035-2600 = "P, para ser sincera, eu ainda não entendo muito bem... Por que alguém como você faria tanto por mim... M, mas... Já que você foi tão gentil comigo, sim...! E, eu vou me esforçar...!"
