[translation]
10037-10 = "ブルーアーカイブ！"
10037-20 = "私を呼んだのは先生か。\nチェリノ会長からの指示書は持っているな？"
10037-30 = "冷たいカンポットでも、\n一杯飲めたら\nいいのだが……。"
10037-40 = "暖かくて\nふかふかしていて、\n眠くなるな………。"
10037-50 = "おっと、いけない。\n早く過酷な訓練を\nしなくては……！"
10037-60 = "この空間は広くて、\n突撃訓練にちょうど\n良さそうだ。"
10037-70 = "この中で\n迷子になったら\nどうしよう……？"
10037-80 = "時は金なりだ、先生！\nこれからはもっと\n早く戻ってくるように！"
10037-90 = "帰ってきたか、先生。\n今日も思いっきり突撃するぞ！"
10037-100 = "私たちレッドウィンターは\n熊の如く、何も恐れることなく\n狩りを行う！"
10037-110 = "怠けていたら、\nサボタージュの疑いで\n事務局に告発するぞ！"
10037-120 = "ど、どこを触ってる！\n特別クラス送りにするぞ！"
10037-130 = "ん、メドヴェーチとは\n誰か……だと？"
10037-140 = "メドヴェーチ、それは私と\n寝床を共にしてくれる、\n忠実な熊のぬいぐるみだ。"
10037-150 = "やつがいなければ、\n私は熟睡できなくてな。"
10037-160 = "チェリノ会長は可愛い……？"
10037-170 = "うむ、うむ！私もそう思うぞ！"
10037-180 = "今日は先生の\n誕生日なのか？\nめでたい日だな。"
10037-190 = "事務局に連絡して、\n特別な補給品が\nもらえるように取り計らおう。"
10037-200 = "私の誕生日だからといって、\n特別な措置をとる必要はない。"
10037-210 = "ただ、先生が一緒に\nいてくれるなら……"
10037-220 = "それは少し\n嬉しいかもしれない。"
10037-230 = "今年一年、\nどこへでも突撃できるよう、\n準備を万全にしておこう！"
10037-240 = "サンタクロース……\n一晩ですべてのキヴォトスの\n学園を巡るなんて、"
10037-250 = "なんて恐ろしい速さなんだ！"
10037-260 = "いたずらをしなければ\n飴を分けてやるだと……?"
10037-270 = "何を言っている、\n飴は基本全ての生徒たちに、\n平等に配るべきだ！"
10037-290 = "くっ……この隙間の汚れ、\n中々やるじゃないか。"
10037-300 = "しかし、\nこの保安委員長の猛撃に\nいつまで耐えられるかな？"
10037-310 = "ふふっ……\nこの新兵器の力を\n甘く見るなよ。"
10037-320 = "新たに購入したこの\n洗剤さえあれば、"
10037-330 = "なかなか届かぬ\n隙間までバッチリだ！"
10037-340 = "はっ、待て先生！\n鏡やガラスは洗剤で洗った後、"
10037-350 = "乾拭きで水気をしっかり\n取るように言っただろう！"
10037-360 = "こういうのは特に\n新聞紙を使うことで、"
10037-370 = "その真の輝きを\n取り戻せるのだ！"
10037-380 = "それから、こういった\n洗浄液は密室で使うと\nかなり危険性がある。"
10037-390 = "使用時には\n必ず換気を忘れるな！"
10037-400 = "きちんと安全に留意した上で、\nこのレッドウィンターにおける\n衛生環境を脅かす汚染物質共を、"
10037-410 = "徹底的に駆除するのだ！"
10037-2600 = "立派な装備だな、\nこれなら敵を一掃できそうだ。"
