[translation]
10048-10 = "Blue Archive"
10048-20 = "Sou aqui, do Esquadrão Arius. \n...Sensei, você cuidou de mim de várias formas. \nPelo menos farei o meu trabalho para compensar. Conto com você."
10048-30 = "Hmm..."
10048-40 = "Não estou acostumada \ncom lugares assim..."
10048-50 = "O que é isso...?"
10048-60 = "Não consigo entender..."
10048-70 = "Entendo, então é \npara isso que serve..."
10048-80 = "Estou pronta. \nSe precisar de algo, \né só dizer, Sensei."
10048-90 = "Eu estava te esperando, Sensei."
10048-100 = "...Por que essa reação?"
10048-110 = "Estou sendo útil?"
10048-120 = "...Então está bem. Só por isso, \neu posso continuar aqui."
10048-130 = "Embora tudo seja vazio, \npor que será que \nnós vivemos..."
10048-140 = "Eu ainda não \nsei a resposta."
10048-150 = "Eu... continuarei \ntentando sobreviver."
10048-160 = "Dê-me uma ordem, Sensei. \nÉ para isso que \nestou aqui."
10048-170 = "Será que eu ainda \nposso continuar vivendo...?"
10048-180 = "...Ouvi dizer que \né o seu aniversário, Sensei."
10048-190 = "Sinto muito, mas \nnão sei o que se deve fazer \nem momentos como este."
10048-200 = "Mas... se você não estivesse aqui, \neu também não estaria."
10048-210 = "Por isso, Sensei. \nDeixe-me agradecer novamente."
10048-220 = "...Eu nunca, até hoje, \ncomemorei aniversários."
10048-230 = "Por isso, ainda não sei \ncomo receber \nessas palavras."
10048-240 = "Ou se tenho o direito disso."
10048-250 = "Será que um dia, \npoderei comemorar este dia \nde coração...?"
10048-260 = "O fim do ano, é... entendo. \nOs dias neste mundo \ncontinuam frios e dolorosos, mas..."
10048-270 = "Mesmo assim, \no tempo continua passando."
10048-280 = "Véspera de Natal... Não tenho \nnenhuma opinião sobre isso."
10048-290 = "Não acho que a dor deste mundo \nvá diminuir \npor causa disso."
10048-300 = "...Tudo é apenas vazio."
10048-310 = "Parece ser um festival, mas... \nnão tenho interesse algum."
10048-320 = "É apenas vazio."
10048-330 = "Estou pronta. \nSe precisar de algo, \né só dizer, Sensei."
10048-340 = "Eu estava te esperando, Sensei."
10048-350 = "...Por que essa reação?"
10048-360 = "Estou sendo útil?"
10048-370 = "...Então está bem. Só por isso, \neu posso continuar aqui."
10048-380 = "Embora tudo seja vazio, \npor que será que \nnós vivemos..."
10048-390 = "Eu ainda não \nsei a resposta."
10048-400 = "Eu... continuarei \ntentando sobreviver."
10048-410 = "Dê-me uma ordem, Sensei. \nÉ para isso que \nestou aqui."
10048-420 = "Será que eu ainda \nposso continuar vivendo...?"
10048-430 = "...Ouvi dizer que \né o seu aniversário, Sensei."
10048-440 = "Sinto muito, mas \nnão sei o que se deve fazer \nem momentos como este."
10048-450 = "Mas... se você não estivesse aqui, \neu também não estaria."
10048-460 = "Por isso, Sensei. \nDeixe-me agradecer novamente."
10048-470 = "...Eu nunca, até hoje, \ncomemorei aniversários."
10048-480 = "Por isso, ainda não sei \ncomo receber \nessas palavras."
10048-490 = "Ou se tenho o direito disso."
10048-500 = "Será que um dia, \npoderei comemorar este dia \nde coração...?"
10048-510 = "O fim do ano, é... Pois é.\nOs dias neste mundo\ncontinuam frios e dolorosos, mas..."
10048-520 = "Mesmo assim,\no tempo continua a passar."
10048-530 = "Véspera de Natal, é... Não tenho\nnenhuma opinião sobre isso."
10048-540 = "Não creio que a dor deste mundo\nvá diminuir por causa disso."
10048-550 = "…Tudo não passa de um vazio."
10048-560 = "Parece que é um festival, mas...\nNão tenho interesse algum."
10048-570 = "É apenas vazio."
10048-590 = "Sensei, por que você está aqui...?"
10048-600 = "Ugh... haa..."
10048-610 = "…Não se preocupe,\né algo que acontece sempre."
10048-620 = "Foi apenas um descuido\nda minha parte..."
10048-630 = "Mesmo que nada tenha mudado...\neu acabei me enganando."
10048-640 = "Cof, cof...!"
10048-650 = "Não faça essa cara,\nestou acostumada com a dor."
10048-660 = "Nada mudou em relação ao que era antes.\nNão é nada de novo."
10048-670 = "Por enquanto, está tudo bem assim..."
10048-680 = "Só mais um pouco, deixe-me ficar assim..."
10048-2600 = "Por que você... consegue confiar em mim?\nMesmo depois de tudo o que aconteceu...\nVocê não se importa se eu te trair?\nAinda há muitas coisas que não entendo,\nmas mesmo assim... farei o meu melhor."
