[translation]
10042-10 = "Blue Archive."
10042-20 = "……Meu nome é Atsuko Hakarime.\nO que você deseja de mim, Sensei?\nSe for algo que eu possa fazer, tudo bem."
10042-30 = "(Sussurro, sussurro……)"
10042-40 = "Hmm?"
10042-50 = "É um pouco estranho, mas\n……sim, eu não desgosto."
10042-60 = "Isso é\numa conversa normal……?"
10042-70 = "Aqui…… seria bom\ncolocar flores."
10042-80 = "Bom trabalho, Sensei."
10042-90 = "Bem-vindo de volta, Sensei."
10042-100 = "Se tiver algo\nque queira me pedir,\né só dizer."
10042-110 = "Posso decorar aqui\ncom flores também?"
10042-120 = "Se tiver algum desejo,\npode me pedir qualquer coisa."
10042-130 = "Então isso é ser responsável……\nEu queria tentar fazer isso um pouco."
10042-140 = "Feliz aniversário\npara você……"
10042-150 = "Eu fiz exatamente como aprendi, mas\nessa sua expressão……\nSerá que eu fiz errado?"
10042-160 = "Aniversário……?\n……Sim. Eu sei o que significa.\nAprendi recentemente."
10042-170 = "E também sei que, quando alguém te parabeniza,\nvocê deve agradecer.\nBem, obrigado."
10042-180 = "Ano Novo…… mais um ano\npassando assim, não é?"
10042-190 = "Dias tão diferentes do habitual……\nComo será que vai ser\no próximo ano?"
10042-200 = "Noite Santa……\nEu aprendi. Sim."
10042-210 = "Teria sido bom se houvesse flores adequadas\npara um dia como este……\nVou pesquisar sobre isso depois."
10042-220 = "Doce? É para mim?\nObrigada……\nMas, por que?"
10042-230 = "Bom trabalho, Sensei."
10042-240 = "Bem-vindo de volta, Sensei."
10042-250 = "Se tiver algo\nque queira me pedir,\né só dizer."
10042-260 = "Posso decorar aqui\ncom flores também?"
10042-270 = "Se tiver algum desejo,\npode me pedir qualquer coisa."
10042-280 = "……?\nTem algo no meu rosto?"
10042-290 = "Então isso é ser responsável……\nEu queria tentar fazer isso um pouco."
10042-300 = "Feliz aniversário\npara você……"
10042-310 = "Eu fiz exatamente como aprendi, mas\nessa sua expressão……\nSerá que eu fiz errado?"
10042-320 = "Aniversário……?\n……Sim. Eu sei o que significa.\nAprendi recentemente."
10042-330 = "E também sei que, quando alguém te parabeniza,\nvocê deve agradecer.\nBem, obrigado."
10042-340 = "Ano Novo…… mais um ano\npassando assim, não é?"
10042-350 = "Dias tão diferentes do habitual……\nComo será que vai ser\no próximo ano?"
10042-360 = "Noite Santa……\nEu aprendi. Sim."
10042-370 = "Teria sido bom se houvesse flores adequadas\npara um dia como este……\nVou pesquisar sobre isso depois."
10042-380 = "Doce? É para mim?\nObrigada……\nMas, por que?"
10042-400 = "Esta flor,\nserá que……"
10042-410 = "……Você trouxe\npara mim."
10042-420 = "Para mim……?"
10042-430 = "……Entendo."
10042-440 = "……Vou cuidar bem dela,\npara sempre."
10042-450 = "……Estou muito feliz.\nObrigada."
10042-2600 = "Desisti de pensar, desisti de decidir……\nEu apenas vivi seguindo um destino traçado.\nMas, de agora em diante……\nSim. Obrigada, Sensei."
