[translation]
10049-10 = "Blue Archive."
10049-20 = "Sou da Academia Trinity, do Clube de Doces depois da aula, Kazusa Kyoyama. Hum, prazer... em conhecê-lo."
10049-30 = "……É fofo. Não é ruim."
10049-40 = "Será que eu posso... sentar aqui?"
10049-50 = "Tem algo que parece... delicioso aqui."
10049-60 = "Um tempo relaxante... não é nada mal."
10049-70 = "Isso é... o gosto do Sensei...?"
10049-80 = "Ah. Bem-vindo de volta, Sensei. O que vamos fazer hoje?"
10049-90 = "Eu estava te esperando, Sensei. Se tiver algo em que eu possa ajudar, é só falar."
10049-100 = "Se precisar de algo, pode falar a qualquer momento."
10049-110 = "Ah, mas eu não sou muito boa em ler textos complicados... então, prefiro passar essa parte."
10049-120 = "Ficar aqui me deixa... calma. Acho que estou ficando com um pouco de sono."
10049-130 = "Sensei, não está na hora de comer alguma coisa? ...Quer que eu compre algo lá fora?"
10049-140 = "……Hm? Ah, não se preocupe, eu só estava te observando trabalhar, Sensei."
10049-150 = "Eh, sobre a época do ensino fundamental...? ...Acho melhor você não saber."
10049-160 = "Feliz aniversário, Sensei. Eu não tenho nenhum presente em especial, mas..."
10049-170 = "Hum, que tal darmos uma volta juntos?"
10049-180 = "Ah, é verdade, é meu aniversário... Sim. Obrigado, Sensei. Fico feliz."
10049-190 = "Feliz ano novo, Sensei. Conto com você este ano também."
10049-200 = "Mesmo com a virada do ano, não sinto que algo tenha mudado muito,"
10049-210 = "……mas isso também não é ruim."
10049-220 = "Natal... né."
10049-230 = "Você tem planos para depois? Na verdade, eu... preparei algo, só por precaução..."
10049-240 = "Halloween... é bem agitado. Eu não gosto muito de barulho, mas..."
10049-260 = "V-você, por acaso, já tinha percebido desde o começo...?"
10049-270 = "Entendi... Bem, não tinha como você não perceber, né..."
10049-280 = "Não é que eu estivesse te evitando, na verdade..."
10049-290 = "É só que... bom... agora... eu estou sem maquiagem, então..."
10049-300 = "Não chegue tão perto...!"
10049-310 = "Quer dizer, Sensei, eu já disse para não chegar perto."
10049-320 = "……S-sério? ...Você acha?"
10049-330 = "Bem... se é assim, então tudo bem..."
10049-340 = "……O que foi essa reação?"
10049-350 = "Q-que foi!? Por que você está rindo tanto!?"
10049-360 = "Ei!!!"
10049-2600 = "……Ah, desculpe. Não, é que eu fiquei pensando por que você me deu algo assim... Será que isso significa que ainda terei oportunidades de ajudar o Sensei? Se eu puder ser útil, fico feliz."
