[translation]
10055-10 = "ブルーアーカイブ"
10055-20 = "あ、先生。仕事前に\n一杯どうかな？ふふっ……\nお酒じゃないから安心して。"
10055-30 = "かわいいものが\nいっぱいだね。"
10055-40 = "あれは……？"
10055-50 = "発酵に最適な\n温度だね。"
10055-60 = "ここは温かいね。\n……もう少しだけ\nここにいたいな。"
10055-70 = "これにアレを\n少し混ぜて……。"
10055-80 = "いらっしゃい、先生。\nちょうど暇だったし"
10055-90 = "おしゃべりでもしない？"
10055-100 = "おかえり、先生。\n疲れてるみたいだね……"
10055-110 = "これでも飲む？"
10055-120 = "シャーレは\n日当たりがよくて、\n温かいね。"
10055-130 = "ボーっとしてたら\n寝ちゃいそう……。"
10055-140 = "ん？何か手伝おうか？"
10055-150 = "今度は私が\n先生を招待しようかな。"
10055-160 = "ふんふふ～ん♪"
10055-170 = "なんで前に配給用カンポットに\nお酒を混ぜたのか、って？"
10055-180 = "そうだなぁ……。"
10055-190 = "昔のことだから思い\n出せないや……ふふ。"
10055-200 = "お誕生日おめでとう、先生。"
10055-210 = "お祝いのカンポットでもどう？"
10055-220 = "そういえば今日私の\n誕生日だったね。"
10055-230 = "無茶なお願いは\nしないから安心して\n……ふふっ。"
10055-240 = "あけましておめでとう、先生。"
10055-250 = "新年だし甘酒くらい、\nいいよね？"
10055-260 = "……ん？ダメなの？"
10055-270 = "メリークリスマス、先生。\n何か欲しいものはある？"
10055-280 = "私？"
10055-290 = "……私は\n今のままで十分かな。"
10055-300 = "かぼちゃジュースが\n飲みたい気分。"
10055-310 = "もちろん\n発酵していないヤツね。"
10055-330 = "綺麗な夜景だね……。"
10055-340 = "こんな素敵な景色を\n見せてくれてありがとう、\n先生。"
10055-350 = "……そう言ってくれるのは\n嬉しいけど。"
10055-360 = "私、やっぱり今の場所が\n好きなんだ。"
10055-370 = "……こういう都会だと、\nあまり星が見えないでしょ。"
10055-380 = "明るすぎる光の中だと、\n星ってうまく見つけられ\nなくなっちゃうから……"
10055-390 = "だから、私は暗闇から\n眺めるだけで十分。"
10055-400 = "大切な人と、美味しい\n飲み物さえあれば……"
10055-410 = "場所はどこだって\n構わないからね。"
10055-2600 = "このグレネードランチャー、\n火を起こす時はいいんだけど\n狩りでは微妙なんだよね。\n……でもまぁ、\n熊を追い返すには十分なのかな。"
