[translation]
10072-10 = "Blue Archive!"
10072-20 = "RABBIT2, prontos para a operação.\nMesmo sendo no mar, não vou descuidar da vigilância!"
10072-30 = "(Realmente, esse traje é difícil de se mover em ambientes fechados...)"
10072-40 = "(Aquilo é... será que dá para comer...?)"
10072-50 = "Na próxima operação... talvez não seja uma má ideia usar um traje assim."
10072-60 = "Será que aquilo é... aquela arma que eu só vi nos manuais de instrução...?"
10072-70 = "Em patrulha, sem anormalidades."
10072-80 = "Você veio, Sensei. Eu estava justamente prestes a fazer a manutenção da arma."
10072-90 = "U-uau!? Desde quando você estava aí?"
10072-100 = "E-eu não estou vadiando, viu!?"
10072-110 = "Está muito quente hoje."
10072-120 = "Você está se prevenindo contra a insolação?"
10072-130 = "Cuidado com a desidratação, não esqueça de repor a água."
10072-140 = "Além disso, é bom ingerir um pouco de sal também."
10072-150 = "Na verdade, eu não gosto tanto assim do mar."
10072-160 = "É porque as armas de fogo estragam facilmente..."
10072-170 = "Mas, ser capaz de se adaptar perfeitamente a qualquer ambiente é o que define uma aluna da SRT."
10072-180 = "Na praia, eu uso um mapa tático com tratamento à prova d'água."
10072-190 = "A Moe me recomendou um equipamento de GPS com função à prova d'água, mas..."
10072-200 = "Eu não quero. O papel tem um valor que só o papel pode oferecer!"
10072-210 = "(Teria sido bom se pudéssemos ter vindo ao mar com as outras integrantes, fora de uma missão...)"
10072-220 = "Quer saber onde está o meu capacete de sempre?"
10072-230 = "Este chapéu boonie é o substituto do capacete."
10072-240 = "Pode não parecer, mas ele é feito de material à prova de balas, sabia?"
10072-250 = "Feliz aniversário, Sensei."
10072-260 = "Eu cuidarei do trabalho que leva tempo. Pode ir para casa descansar hoje."
10072-270 = "Passar o aniversário no turno da noite... seria triste, afinal."
10072-280 = "...Presente de aniversário? Não... não preciso de nada..."
10072-290 = "Mas, se você quiser, Sensei... vamos jantar juntos."
10072-300 = "O cardápio pode ser qualquer coisa, até uma marmita de loja de conveniência."
10072-310 = "Feliz ano novo, Sensei. Minha meta para este ano...?"
10072-320 = "Bem... se possível, comer peixe fresco uma vez por semana..."
10072-330 = "Ah, não... é a restauração da Academia Especial SRT!"
10072-340 = "Ah, Sensei. Se tiver tempo à noite, poderia vir ao Parque dos Coelhinhos?"
10072-350 = "Como é Natal, a Moe trouxe um peru enorme,"
10072-360 = "mas não acho que o RABBIT Squad consiga comer tudo sozinho."
10072-370 = "Fazer um churrasco no Schale é difícil... vamos fazer uma festa no parque."
10072-380 = "Ultimamente, tenho visto muitas marmitas de loja de conveniência com abóbora."
10072-390 = "Será que... esta é a famosa temporada de Halloween?"
10072-410 = "(Vamos lá, Sensei. Fique calmo e olhe para mim.)"
10072-420 = "(Isso, devagar. Expire o ar lentamente.)"
10072-430 = "(Fufu, como esperado do Sensei. Aprende rápido.)"
10072-440 = "(...É uma sensação estranha.)"
10072-450 = "(Estar a sós com o Sensei debaixo d'água, sem palavras, conversando apenas com olhares e gestos...)"
10072-460 = "(É como se...)"
10072-470 = "(...Hã? Eu pareço estar com dificuldade para respirar?)"
10072-480 = "(Não, não há problema nenhum. Está tudo bem!)"
10072-490 = "(De alguma forma, diferente do habitual... minha respiração está instável.)"
10072-500 = "(...Talvez o mergulho com o Sensei tenha sido cedo demais para mim.)"
10072-2600 = "Metralhadora RABBIT modelo 26, recebida com sucesso. O tratamento à prova d'água está perfeito para não estragar debaixo d'água. Claro, terei que fazer a manutenção adequada assim que a batalha terminar..."
