[translation]
10078-10 = "ブルーアーカイブ～！！ハーハッハッハッハ！"
10078-20 = "ハーッハッハッハッ！そこに温泉があるから我々がいる！\nいや、たとえ温泉がなくとも我々がいる！\nさあ、発破の準備はできているぞ！"
10078-30 = "おっ？\nここなら……？"
10078-40 = "ここに\n温泉を掘ったら……。"
10078-50 = "……おっと、危ない。\n困ったやつらが\nいるな。"
10078-60 = "ここでもまた\n隠れなければ\nならないのか？"
10078-70 = "うむ……\n暇だ……勉強でも\nしようじゃあないか。"
10078-80 = "やぁやぁ先生！\nここはハイカラな\n所じゃあないか！"
10078-90 = "ようやくおでましだな！\n待っていたぞ、先生！"
10078-100 = "別に私だって所構わず掘って\nいるわけではないのだぞ？"
10078-110 = "ある程度のあたりを\nつけてやっている。"
10078-120 = "むっ？掘るばかりが\n温泉開発じゃあないぞ？"
10078-130 = "建てるのも無論好きだ！"
10078-140 = "普段は建てるところまで\n進められていないだけでな！"
10078-150 = "ハーッハッハッ！\nうむ、それもまた一興！"
10078-160 = "先生といると温泉開発をしている\n時みたいに楽しいぞ。"
10078-170 = "ハーッハッハッ！\nそう警戒するな！"
10078-180 = "もし私が捕まってしまったら\n是非、面会に来てくれ！"
10078-190 = "待っているぞ！\nハーッハッハッハッ！"
10078-200 = "おお！先生、\n時に今日はあなたの\n誕生日じゃあないか？"
10078-210 = "特別な日だからな！\nプレゼントを作ってこよう！"
10078-220 = "はぁ……シャーレに来る途中で\n風紀委員に追われてしまった。"
10078-230 = "まったく！今日は私の\n誕生日なのだからもう少し手心を\n加えても良いんじゃあないか？"
10078-240 = "あけましておめでとう、先生！\n無事に年を越すことができたな。"
10078-250 = "さあ、今年もたくさん\n掘っていこうじゃあないか！"
10078-260 = "クリスマスは素晴らしい！\n警備が手薄になるから\n開発に持ってこいの日だ！"
10078-270 = "ずいぶんと賑やかだな！\nこれなら掘削機の音も紛れて……"
10078-280 = "そんな目で見ないでくれ。"
10078-300 = "ハーハッハッハッハ！\nちょうど良いところに来たな！"
10078-310 = "ようこそ、先生。\nここが私の第86秘密アジトだ。"
10078-320 = "ここで何をしているのかって？\n愚問だな、先生。\n私がすることといえばただ一つ。"
10078-330 = "すなわち……\n新たな温泉ポイントを\n探しているのだ！"
10078-340 = "ハハッ、先生。\n話が早くて助かるな。"
10078-350 = "ああ、その通り。\n実際に爆破する場所に\nあたりをつけていたのだよ。"
10078-360 = "ふむ……\nここが良いだろうか？"
10078-370 = "いや……\nこっちもなかなか……"
10078-380 = "なんだ、先生？\n何故そんな目で私を見る？"
10078-390 = "何か問題でも起きたのか？"
10078-2600 = "先生……本当に良いのか？\n私に付き合い続けるのは、\nかなり骨が折れるぞ？忠告はしたぞ！\nどうなっても私は知らないからな！\nハーハッハッハッハ！"
