[translation]
10108-10 = "Blue Archive."
10108-20 = "Me chamar a uma hora dessas... B-bom, claro que não tem problema! Mas você vai ter que me compensar por isso depois, então esteja preparado, entendeu?"
10108-30 = "Estou um pouco com sono\n... talvez."
10108-40 = "Algum lugar para\ndescansar..."
10108-50 = "Um lugar que não seja\nnem muito quente nem muito frio..."
10108-60 = "(Como, por exemplo, deitar\nao lado do Sensei...)"
10108-70 = "Que tipo de chá\nseria bom para\nrelaxar...?"
10108-80 = "Ah, você chegou, Sensei."
10108-90 = "E-eu não estava esperando\nhá tanto tempo assim...!"
10108-100 = "Olá, Sensei."
10108-110 = "Você perguntou por que\nestou vestida de forma casual...?"
10108-120 = "É porque você me chamou\nde repente...!"
10108-130 = "Eu também queria ter colocado\numa roupa mais bonitinha..."
10108-140 = "Falando nisso, o que você\nusa para dormir, Sensei?"
10108-150 = "N-não estou pensando em\nnada de malicioso!"
10108-160 = "Foi só por curiosidade,\nmais nada..."
10108-170 = "Vida regrada,\nnutrição, sono.\nTudo isso é muito importante."
10108-180 = "S-se quiser, eu posso\norganizar isso para você?"
10108-190 = "S-se você não se importar,\né claro..."
10108-200 = "A falta de sono confunde o raciocínio\ne causa erros."
10108-210 = "Os seres humanos não são\nperfeitos como máquinas."
10108-220 = "Você tem descansado bem?"
10108-230 = "Sinceramente, olhando para o seu rosto, parece que sim... ou talvez não..."
10108-240 = "Às vezes, eu penso em como seria\nacordar de manhã ao lado\nde alguém que admiro."
10108-250 = "N-não tem nenhum significado\nprofundo nisso, viu!?"
10108-260 = "Feliz aniversário,\nSensei."
10108-270 = "Como presente... vou te emprestar\no meu travesseiro por um dia!"
10108-280 = "..."
10108-290 = "É-é brincadeira! Não leve\na sério, por favor!?"
10108-300 = "Você se lembrou do\nmeu aniversário.\nObrigada, Sensei."
10108-310 = "Sobre o presente... qualquer coisa\nque venha de você\nme deixará feliz."
10108-320 = "Hã? \"Pode escolher qualquer coisa\nque eu tenha agora, Yuuka\"\n...?"
10108-330 = "B-bem, então..."
10108-340 = "...Você está preparado, não está,\nSensei?"
10108-350 = "Feliz Ano Novo, Sensei.\nPassar o primeiro dia do ano\ncom você..."
10108-360 = "Pensando em tudo o que passamos...\nEu nunca teria imaginado."
10108-370 = "Até hoje, eu só pensava no Natal\ncomo um dia corrido e\ncheio de trabalho."
10108-380 = "...Quer saber como é desta vez?"
10108-390 = "Hehe... Pode tentar adivinhar,\nSensei."
10108-400 = "É Halloween... Me disseram que\neu poderia sair assim\nsem problemas, mas..."
10108-410 = "Eu deveria ficar feliz\ncom isso...?"
10108-430 = "S-Sensei?\nPor que a essa hora...?"
10108-440 = "E-eu... isso é, bom..."
10108-450 = "Eu não conseguia dormir, então\nsaí para caminhar..."
10108-460 = "E acabei vendo o cartaz do\n\"Angel Chicken\"\nque estava ali..."
10108-470 = "M-mas, não tem como evitar, né?"
10108-480 = "O Angel Chicken a essa hora\né frito na hora!"
10108-490 = "Está super quente e\ncheio de suco de carne!\nNão tinha como não comprar!"
10108-500 = "E-então, é que... não é como se\neu estivesse comendo"
10108-510 = "lanche da madrugada\ntodos os dias..."
10108-520 = "Bem... se quiser,"
10108-530 = "você também gostaria de uma mordida, Sensei?"
10108-2600 = "Muito obrigada, Sensei.\nCom isso, poderei eliminar racionalmente\nos elementos que atrapalham meu sono."
