[translation]
10105-10 = "ブルーアーカイブ！"
10105-20 = "アイドルはあまりやったことがありませんが……\n精いっぱい努めて参りますね。\nよろしくお願いいたします、先生！"
10105-30 = "とても心地よい\n空間ですね。"
10105-40 = "何か視線を\n感じるような……？"
10105-50 = "次はなにを\nしましょう……？"
10105-60 = "何かお手伝い\nできることは\nありませんか？"
10105-70 = "握手会……？\nチェキ……？"
10105-80 = "お待ちしておりました、先生。\n準備は万全ですよ。"
10105-90 = "それでは聞いて下さい。\n一曲目は、この曲です。"
10105-100 = "先生がお望みでしたら……\nステージでも、\nそれ以外でも……\n歌を届けます。"
10105-110 = "私の歌で先生が幸せに\nなってくださるのなら……\nそれ以上望むことは\nありません。"
10105-120 = "あ、握手ですか？\nはい、どうぞ。"
10105-130 = "あ、あはっ、あはは……！\nせ、先生、\nく、くすぐったいです……！"
10105-140 = "もう……そんなことを\nするのでしたら私も……！\nえい！"
10105-150 = "お誕生日\nおめでとうございます、先生。\nこの歌を先生に捧げますね。"
10105-160 = "私の誕生日……"
10105-170 = "自分が主役の日というのは、\nいつまで経っても\n慣れませんね。"
10105-180 = "でも、そんな風に\n言っていただけて、\nとても嬉しいです。\nありがとうございます、先生。"
10105-190 = "明けまして\nおめでとうございます、先生。"
10105-200 = "今年もより多くの方に\n歌を届けられる……"
10105-210 = "そんな幸せに満ちた\n一年であることを、\n祈っております。"
10105-220 = "聖なる夜……\n賛美歌を皆さんに\n届ける日です。"
10105-230 = "ええ、歌うのに\nぴったりの格好ですから。"
10105-240 = "こ、これは仮装では\nないのですが……"
10105-250 = "でも……先生が\n気に入っているのでしたら……\nこのままでいますね。"
10105-270 = "先生、待っていて\nくださったのですね！"
10105-280 = "まさかずっとここで\n待っていて\nくださったなんて……"
10105-290 = "その……ステージ、\nどうでしたか？"
10105-300 = "舞台袖からだと\nあんまり良く見えなかったとは\n思うのですが……"
10105-310 = "でも、先生はずっと\n見守ってくださって\nいたから……"
10105-320 = "舞台袖からでも\n大丈夫かな……"
10105-330 = "その……\nパフォーマンス、どうでした？"
10105-340 = "ちゃんと……\n「アイドル」に\nなれていました？"
10105-350 = "……！！"
10105-360 = "……ありがとうございます、\n先生……！"
10105-370 = "……えへへ。"
10105-2600 = "今なら、なんでも先生に\n言えるような気がするんです。\nその…なので、聞いても忘れてくださいね。\n…これからも、ずっと私の\nそばにいてください。約束ですよ。"
