[translation]
10126-10 = "Blue…… Archive…… Ihi."
10126-20 = "Kanoe Itagaki da Academia de Artes Wildhunt…….\nEu sabia que nos encontraríamos hoje…….\nNós estamos conectados pelo fio vermelho do destino…… Ihi."
10126-30 = "Na minha vida passada……\neu nunca vim\na um lugar como este……."
10126-40 = "Eu também preciso colocar\nartigos de ocultismo aqui……."
10126-50 = "Ali……\ntem \"alguma coisa\", né."
10126-60 = "Não tem um lugar\nescuro e apertado……?"
10126-70 = "O ritual de invocação……\nposso fazer aqui?"
10126-80 = "Sensei, eu estava te esperando."
10126-90 = "Desde a minha vida passada."
10126-100 = "Bem-vindo de volta, Sensei……."
10126-110 = "Eu…… tenho a temperatura corporal baixa."
10126-120 = "Por isso, se você não me aquecer\nficando ao meu lado……\nnão vai dar certo…… Ihi."
10126-130 = "Graças a este elástico de cabelo……"
10126-140 = "Eu consigo\n\"ver\" as coisas, sabe."
10126-150 = "Ihi……"
10126-160 = "É brincadeira……."
10126-170 = "Minha poção especial……"
10126-180 = "Você quer?"
10126-190 = "Eu coloquei \"várias coisas\"\npara você, Sensei……."
10126-200 = "O destino…… \"existe\"……."
10126-210 = "O nosso encontro……\né a prova disso."
10126-220 = "Eu consigo fazer\nqualquer tipo de voz……."
10126-230 = "Se tiver algum timbre que queira ouvir,\né só me pedir……."
10126-240 = "Feliz aniversário…… Sensei."
10126-250 = "Na vida passada também……\nnós comemoramos, né.\nIhihi……."
10126-260 = "Hoje é o dia dos mortos……"
10126-270 = "E o meu aniversário."
10126-280 = "Pensando nas almas que descansam……"
10126-290 = "Vamos rezar juntos."
10126-300 = "Feliz ano novo, Sensei."
10126-310 = "Espero que este ano\nseja maravilhoso."
10126-320 = "Fui madura agora, não fui?\nIhi……."
10126-330 = "Poder passar o Natal\ncom o Sensei……\nA Kanoe está tão feliz♡"
10126-340 = "Hoje, eu não vou\nte deixar ir embora♡"
10126-350 = "Halloween……"
10126-360 = "O dia em que o Clube de Ocultismo brilha na escuridão."
10126-370 = "Vamos lá, vamos fazer\numa lanterna de abóbora……\nIhi."
10126-390 = "Se, Sensei……\nBem, antes da gravação……\ntenho algo que quero te contar."
10126-400 = "Na, na verdade……\neu tenho algo que escondi\npor muito tempo……."
10126-410 = "Eu, eu……\nsou muito tímida\ne não consigo falar direito."
10126-420 = "Para esconder isso, eu fingia\nser uma personagem sombria……."
10126-430 = "Eu entrei para o ocultismo\nporque queria mudar a mim mesma."
10126-440 = "A única pessoa que sabe disso……\né você, Sensei."
10126-450 = "Por isso……\nmantenha segredo, tá?"
10126-460 = "Se, Sensei……\neu confio em você……."
10126-470 = "……Ihi, ihihi.\nEi, você acreditou?"
10126-480 = "O Sensei gosta de\ncoisas fofas, né?"
10126-490 = "Então, você também……\ngosta de mim, né?"
10126-500 = "Ihi……!"
10126-2600 = "Como esperado do Sensei……\nvocê entende, né. Ihihi."
