[translation]
13000-10 = "ブルーアーカイブ。"
13000-20 = "最高のご奉仕をお約束し、\nご主人様へのご挨拶と\n致します。"
13000-30 = "この場所はきれいに\n掃除されてますね。\n有能なメイドが待機\nしているに違いないです。"
13000-40 = "ダイエットですか…。\n一時、そういうことで\n悩んでいた時期も\nありましたね。ふふっ。"
13000-50 = "ようこそいらっしゃいました。\n温かい紅茶を一杯、\nご用意いたしましょうか？"
13000-60 = "ご主人様、先生、もしくは…ダーリン？\nふふっ。\nどのようにお呼びするのが\nお好きでしょうか。"
13000-70 = "あら。これは…私がやる\nべきことでしたのに…。\nさらにやる気になってしまいましたよ。\nご・主・人・様。"
13000-80 = "おかえりなさいませ、ご主人様。\n今日もお疲れ様でした。"
13000-90 = "お茶でもいかがでしょうか？\nちょうど最高級の茶葉が\n入りましたよ。"
13000-100 = "はい。書類は私が\n片づけておきました。\nお任せください。"
13000-110 = "何かお望みでしょうか。\n最高のご奉仕で、\nお応えします。"
13000-120 = "手紙が届きました。"
13000-130 = "あら、可愛い字ですね。"
13000-140 = "お・読・み・い・た・し・\nま・しょ・う・か？"
13000-150 = "優雅な願いでは\nないかもしれません。\nでも、ご主人様。"
13000-160 = "これからもアカネを\nお呼びください。"
13000-170 = "お誕生日おめでとう\nございます。ご主人様。"
13000-180 = "ご主人様がここに\n来てくださって…"
13000-190 = "…嬉しいです。"
13000-200 = "生誕は、祝福です。"
13000-210 = "ご主人様に出会った\nその瞬間から、\n私はその事にいつも\n感謝していました。"
13000-220 = "明けましておめでとう\nございま～～っす。"
13000-230 = "今年一年も、よろしく\nお願いします。ご主人様！"
13000-240 = "メリークリスマス～。"
13000-250 = "私からの\nプレゼントは、\n最高のご奉仕と\n笑顔です。"
13000-260 = "先生からの\nプレゼントは何ですか？"
13000-270 = "さあ。飴をくれないと、\nいたずらしますよ～？"
13000-280 = "私は、いたずらの方が\n好きですけどね。"
13000-300 = "あら。おかえりなさいませ。"
13000-310 = "今日一日、いかがでしたか？"
13000-320 = "あ、ご主人様。ちょうど\n最高級の茶葉が入りましたよ。"
13000-330 = "私の方で一杯、\nご用意いたしましょうか？"
13000-340 = "はい？ここは、私たちの\nお家ではないですって？"
13000-350 = "ふふっ。\n気にしません。"
13000-360 = "私たちのお家ではなくても、\n私たちは今一緒に\nいるのですから。"
13000-2600 = "期待されるとは、\nこんなにもときめくことだったのですね。\nアカネは、ご主人様に\n最高のご奉仕で応えます。"
