[translation]
13006-20 = "じゃーん！ついに登場！\nさぁ、これから楽しく遊ぼう、先生！"
13006-30 = "楽しいから\n大丈夫。"
13006-40 = "ふーん？\nあれも\n良さそうじゃん？"
13006-50 = "くふふ～♥"
13006-60 = "ナデナデして～"
13006-70 = "一緒にあ～そ～ぼ～"
13006-80 = "おはよ～先生～\nお仕置きに来たよ～"
13006-90 = "今日はどんな\n任務をするの？\n楽しいことからやろう！"
13006-100 = "先生、\n今日は何して遊ぶ？"
13006-110 = "なにぃ！？忙しい？\n仕事なんか後回しにしちゃお、\nダメ？"
13006-120 = "この前やってた\n遊びの続きしない？"
13006-130 = "あれ…楽しかったでしょ？"
13006-140 = "くふふ～♥\n照れる表情、面白い。"
13006-150 = "あれ、\nからかい過ぎたかな。\nこれは怒られるかも…。"
13006-160 = "先生の誕生日？！\nめちゃくちゃ\n大事な日じゃん！\nお祝いしよう！"
13006-170 = "便利屋の事務所で\nパーティーを開こうよ！"
13006-180 = "今日は私の\n誕生日だよ！"
13006-190 = "先生～、遊んで…\nくれるよね～？！"
13006-200 = "今年は去年より\nもっと楽しく遊ぼう～"
13006-210 = "くふふ、楽しみ～♥"
13006-220 = "じゃじゃーん！\nクリスマスの\nプレゼントは\nこの私！"
13006-230 = "リボンを解くといいよ？\nくふふふ♥"
13006-240 = "お菓子をくれないと～\nいたずらしちゃうよ～"
13006-250 = "うん？本当にくれるの？\nお菓子よりいたずらの\n方が好きなのにぃ。"
13006-270 = "あ～あ、ざーんねんっ。\nくふふっ、\nバレちゃったかぁ～♪"
13006-280 = "何を隠そう、今日の可愛い\n依頼人の正体は他でもない、\nこのムツキちゃん\nなのでした～。"
13006-290 = "考えてもみてよ先生～。\nそもそも便利屋の依頼を、\n私一人で解決しに\n行くわけないじゃん？"
13006-300 = "あはっ、どうだった？先生？\n私のいたずら、\nほぼ完璧だったでしょ？"
13006-310 = "きゃはっ、なぁに先生、\nその間抜けな顔。\nうける！あはは～っ♪"
13006-320 = "今日は先生と、\nいろんなことしたねー。"
13006-330 = "クレープ食べて、\n遊園地にも行って、\nあ、図書館では\n共犯にもなっちゃったし…！"
13006-340 = "あ～あ、最後まで完璧に\n騙せると思ったのに、\n残念だな～。"
13006-350 = "でも今度は、絶対に最後まで\n騙し通してみせるから、\n楽しみにしといてね～！"
13006-360 = "あーっ、今日はほんっと、\n楽しかった！"
13006-2600 = "先生！\n見て見て～この武器、\nすごく強そうで、しかも可愛いの！"
