[translation]
16002-20 = "Se precisar de uma explicação ou comentário, pode deixar comigo!"
16002-30 = "A resposta correta está sempre perto do problema. Assim como a resposta errada, aliás."
16002-40 = "Hm? Sinto que alguém, em algum lugar, está precisando de uma explicação!"
16002-50 = "Ah, eu quero explicar! Agora mesmo!"
16002-60 = "O mistério foi solucionado!"
16002-70 = "Minhas explicações são sempre perfeitas. Exceto pelo fato de serem longas demais!"
16002-80 = "Bem-vindo, Sensei! Vou explicar a agenda de hoje!"
16002-90 = "Que dia bom, Sensei! Por favor, venha logo para a sala de briefing!"
16002-100 = "Se tiver algo que queira saber, é só me chamar!"
16002-110 = "Socorro, Kotori! ...é o que eu diria!"
16002-120 = "Boa pergunta, Sensei! Deixe-me respondê-la!"
16002-130 = "Estes óculos? São estilosos, não são? O Sensei quer experimentar?"
16002-140 = "A explicação é a luz que supera a escuridão da ignorância."
16002-150 = "...embora não deva ser brilhante demais."
16002-160 = "Ah, alguém quer saber algo agora."
16002-170 = "Sensei! Vamos sair agora mesmo!"
16002-180 = "Feliz aniversário, Sensei! O aniversário é um dia especial que comemora o dia em que alguém nasceu, e..."
16002-190 = "Ah! Aonde você vai??"
16002-200 = "Já que é meu aniversário, vou falar um pouco sobre mim..."
16002-210 = "Ah! Espere! Minha história ainda não acabou!"
16002-220 = "Ainda estou na parte da 'introdução'!"
16002-230 = "Feliz Ano Novo!"
16002-240 = "Este ano, sinto que quero assistir a muito mais aulas do Sensei."
16002-250 = "Feliz Natal! Dizem que este é o dia em que o bebê chamado Salvador nasceu! Por que se tornou o dia dos namorados..."
16002-260 = "Hm? Namorados...?"
16002-270 = "Gostosuras ou travessuras! Se não me der um doce, eu vou explicar..."
16002-280 = "Ei, uau! Não precisa de tanto assim!"
16002-300 = "E... eeee!? Po-por que de repente, é, i-isso é...!"
16002-310 = "Desculpe, só por precaução, poderia repetir...?"
16002-320 = "Ah, entendo... é, foi isso..."
16002-330 = "E-então, como posso dizer..."
16002-340 = "A-a propósito, por que de repente perguntou isso...? Existe algum, sabe, motivo...?"
16002-350 = "N-não, tudo bem se não tiver um motivo específico!"
16002-360 = "C-claro que eu sei sobre mim mesma, afinal...!"
16002-370 = "E-então, v-você está falando de mim!? Eu normalmente, sabe,"
16002-380 = "Por exemplo, absorvendo vários conhecimentos, pensando no Sensei, e então, bem...!"
16002-390 = "...? Ué, o que eu acabei de dizer...?"
16002-400 = "Absorvendo vários conhecimentos e, o Sensei..."
16002-410 = "Ah, ahaha..."
16002-420 = "Não, o que eu disse agora foi...! Ah, ahhh...!"
16002-2600 = "O nome desta arma é... Sensei K!"
