[translation]
16004-10 = "Blue Archive!"
16004-20 = "ごきげんよう。\nアッ、こっちの言葉の方がより自然かもデス。\nハジメマシテ！"
16004-30 = "良いところデスね。\nなんだか懐かしい感じがしマス！"
16004-40 = "センセイにも、\nピザやホットケーキより\nお好み焼きを好きに\nなってもらいたいデス…。"
16004-50 = "Wow〜、\n良い雰囲気デスネ！"
16004-60 = "Cool～な烏龍茶がいいデス！\nコーヒーやコーラは好きじゃないデス。"
16004-70 = "ごきげんよう。"
16004-80 = "アッ、思わず前の\n学園での口癖が…。"
16004-90 = "ようこそセンセイ〜\n今日も思い切って、\n任務を始めマショウ！"
16004-100 = "百鬼夜行の夏は\nドキドキしマス。\nお祭りが始まりマスから！"
16004-110 = "本当にKimonoは最高デスよ！\n最高 of the 最高！"
16004-120 = "安心してクダサイ。\n峰打ちデス…。"
16004-130 = "アッ…。\nよく見たら\n刀ではなく\n銃デシタ！"
16004-140 = "不義を許さない！\n正義の金髪美女！\nここに参上、デス！"
16004-150 = "挨拶するときは、\n逆立ちをするんデスか？\n百鬼夜行の文化は、\nやはり不思議デス！"
16004-160 = "Today～is～、\n一年にただ一度だけの、\n特別な日デス！"
16004-170 = "Happy Birthday To You！\nセンセイ！お誕生日\nおめでとうございマス！"
16004-180 = "今日はワタシの\n誕生日デス！"
16004-190 = "センセイ!\nおこわを食べなけれ\nばなりまセン！"
16004-200 = "センセイ！\n新年には神社に\n行くべきデス！"
16004-210 = "おみくじを引きに、\n今すぐ行くのデス！"
16004-220 = "Merry Christmas！\nサンタは素晴らしいデス！"
16004-230 = "センセイもサンタは\n好きデスか？！"
16004-240 = "鬼は外～、福は内～"
16004-250 = "エッ？\n節分ではなかったのデスか？\nHalloweenデスか？！"
16004-270 = "ふぅ……なんだか少し、\nから回ってしまった\nようデスネ。"
16004-280 = "こうして落ち着いてみると、\n何だか少々お恥ずかしいと\n言いマスか……。"
16004-290 = "……フフッ。実は……前から\nずっと、今日のこの日を\n楽しみにしていたんデス。"
16004-300 = "ワタシ……今日のこの日を\n迎えられたこと、\n本当に嬉しく思いマス。"
16004-310 = "……センセイはいつも、\nワタシが困った時に\n導いてくれマシタ。"
16004-320 = "……今日だけでなく、\nいつも。"
16004-330 = "大切なものは何か、\n自分のやり方とは\nどうあるべきなのか……"
16004-340 = "センセイに会えず、教えてもらえ\nなかったら……そう思うと、\n胸が苦しくなりマス。"
16004-350 = "……ですから、\n心から感謝してるんデス。"
16004-360 = "センセイ、\nこれからもフィーナを……"
16004-2600 = "強くなるのは\n武器ではなく、魂デス！"
