[translation]
20007-10 = "みんなのために歌うバーチャル・シンガー、初音ミクです！\nよろしくお願いします！"
20007-20 = "素敵なステージ……！"
20007-30 = "キヴォトスの\n技術力って、\nすごい……！"
20007-40 = "～～～♪～～～♪"
20007-50 = "このカフェの音楽、\n何だか落ち着くなぁ。"
20007-60 = "（これ……ネギ？\nどうして……？）"
20007-70 = "こんにちは、先生！\n今日は何の歌が良いですか？"
20007-80 = "あっ、待ってましたよ、先生！"
20007-90 = "さあ、新しいステージの\n準備を始めましょう！"
20007-100 = "私は元々\nバーチャル・シンガーですが、\nこのキヴォトスでこうして、\n自由に歌える身体を貰えました。"
20007-110 = "お礼と言っては何ですが、\n私にできることであれば\n何でも言ってください！"
20007-120 = "先生のためなら、\nたくさん歌っちゃいますよ！"
20007-130 = "今、ミクのこと呼びましたか！？"
20007-140 = "首にネギを巻いたら、\nもっと素敵な声で\n歌えるんですか……？"
20007-150 = "私はバーチャル・シンガー、\n歌を歌い、そこに\n込められた想いを\n届ける存在です！"
20007-160 = "お誕生日おめでとう\nございます、先生！"
20007-170 = "私のお誕生日の歌、\n聞いてください！\n先生がお望みでしたら、\n今日は一日中歌っちゃいますよ！"
20007-180 = "今日は私にとって、\nすっごく特別な日……"
20007-190 = "こんな大切な日に\n先生と一緒にいられて……\n私、幸せです！"
20007-200 = "明けましておめでとう\nございます、先生！\n今年もまた、\n良い一年にしましょう！"
20007-210 = "メリークリスマス！\nさあ、クリスマス・キャロルを\n一緒に歌いましょう！"
20007-220 = "えっと……どなたですか？"
20007-230 = "インタビューでしたら、\nマネージャーさんを\n通してもらえると……。"
20007-240 = "……なんて。ふふっ、\nちょっとした悪戯です。\nだって、今日は\nハロウィンですから！"
20007-260 = "（みんなが私の歌に、\n言葉に……\n耳を傾けてくれてる）"
20007-270 = "（自分の気持ちを\n込めて歌うのって、\nこんなに気持ち良い\nことだったんだ……！）"
20007-280 = "（こんな風に、みんなの\nために歌えるなんて……\n嬉しい、楽しい……！）"
20007-290 = "（このままずっと、\nずっと歌っていたい……！）"
20007-2600 = "これで、もっともっとたくさんの方に、\n歌を届けてみせます……！"
