[translation]
20021-10 = "Blue Archive!"
20021-20 = "Feliz Natal! No lugar do Papai Noel, a Hanae chegou!"
20021-30 = "Olá! Mesmo vestida de Papai Noel, ainda sou a Hanae!"
20021-40 = "Alguém aqui precisa de uma cirurgia ou de um presente?"
20021-50 = "Mesmo no Natal, o Esquadrão de Socorro está totalmente preparado!"
20021-60 = "A chaminé... onde será que ela fica?"
20021-70 = "Vai ter um evento de caridade no Natal. Eu também vou cantar lá com todo mundo!"
20021-80 = "Sensei, Sensei! Tem algo que você queira?"
20021-90 = "Eu, como Papai Noel, vou te dar um presente!"
20021-100 = "Sensei, você parece ocupado ultimamente... chegou tarde hoje também."
20021-110 = "Quer que eu faça uma cirurgia simples para aliviar sua fadiga?"
20021-120 = "Eu estou ótima hoje também! E você, Sensei, como está?"
20021-130 = "Se não estiver se sentindo bem, chame a Hanae!"
20021-140 = "Vou te dar injeções e cirurgias de presente!"
20021-150 = "Cuidado com o congelamento no inverno!"
20021-160 = "Se você errar um passo sequer, pode acabar tendo que amputar a parte afetada!"
20021-170 = "Mal posso esperar pelo Natal! Meu coração está super animado!"
20021-180 = "Ficaria feliz se você também estivesse animado, Sensei!"
20021-190 = "Sensei, Sensei! Que tal um coelho de pelúcia gigante de presente de Natal?"
20021-200 = "Uau, feliz aniversário!"
20021-210 = "Aqui está! Tentei colocar um presente dentro de outro presente! O que achou?"
20021-220 = "Eh... parece uma boneca russa... é isso?"
20021-230 = "Hoje é meu aniversário! O presente é..."
20021-240 = "Eu quero você, Sensei! Ehehe."
20021-250 = "Sensei, já é Ano Novo! Feliz Ano Novo!"
20021-260 = "O Natal já passou, mas será que ainda tem problema eu usar a roupa de Papai Noel?"
20021-270 = "Sensei, é Natal!"
20021-280 = "Será que o Papai Noel vai vir este ano também?"
20021-290 = "O Halloween também é uma das minhas festas favoritas!"
20021-300 = "Mas... parece que tem muita gente precisando de tratamento ou cirurgia, não é?"
20021-320 = "Isso é... a minha forma de me preparar para receber o Papai Noel."
20021-330 = "Para o Papai Noel não sentir frio, acendi a lareira..."
20021-340 = "E decorei a árvore de Natal bem bonitinha."
20021-350 = "Dizendo: 'Papai Noel, estou te esperando~'."
20021-360 = "Se eu fizer isso, ele sempre coloca um presente na minha meia!"
20021-370 = "E este ano..."
20021-380 = "Estou pensando em retribuir o Papai Noel!"
20021-390 = "Ehehe, o que acha? Biscoitos caseiros e leite fresco!"
20021-2600 = "Muito bem, tudo pronto!"
