[translation]
20044-10 = "ブルー、アーカイブ。"
20044-20 = "いらしていたのですね、トレーナー。\n喉が渇いた時は、遠慮なく声をかけてください。"
20044-30 = "運動に集中で\nきそうな場所は……。"
20044-40 = "カフェはドリンクを\n提供する場所……\nそれなら、私も……。"
20044-50 = "スペシャルメニューに、\nプロテインドリンクを\n追加して……"
20044-60 = "よろしければ\nいかがですか？"
20044-70 = "ここなら、\n筋トレも\n捗りそうです。"
20044-80 = "おかえりなさい、\nトレーナー。"
20044-90 = "先ほど、ドリンクの\n種類が変わったのですが、\nよかったら飲んでみませんか？"
20044-100 = "本日の私の役割は\n「先生」のコンディションを\n整えることです。"
20044-110 = "水分とタンパク質――\n同時に提供いたします。\n必要とあらば、いつでも。"
20044-120 = "私は……諦めない人が\n好きです。"
20044-130 = "歩みを止めない人、\nいつまでも挑戦し続ける人。"
20044-140 = "……そうですね。\n一致する箇所が多いのは\n気の所為ではありませんよ。"
20044-150 = "大切なのは、目標を立て、\nコツコツと積み重ねること。"
20044-160 = "続かなかったとしても、\n大丈夫です。"
20044-170 = "最初の一歩を\n踏み出せているのなら、\n後はどうとでもなりますから。"
20044-180 = "何故か、アルバイトの\n制服を着ていると、\n応援を頼まれるんですよね。"
20044-190 = "理由は分かりませんが……\n皆さんに元気になって\nもらえたのなら、何よりです。"
20044-200 = "お疲れのご様子ですね。"
20044-210 = "マッサージには自信が\nありますので、\nいつでも声をかけてください。"
20044-220 = "……今ならスポーツドリンクも\nついてきますよ。"
20044-230 = "お誕生日おめでとうございます、\nトレーナー。"
20044-240 = "こちら、プレゼントの\nプロテイン一箱です。\nどうぞお受け取りください。"
20044-250 = "「先生」からのお祝い……\nなんだかむず痒いですね。"
20044-260 = "そうですね……\n私とスペシャル強化\nトレーニングを\nしてくださりませんか？"
20044-270 = "……ふむ、プレゼントなら\nプロテインドリンクの\n全フレーバーを……。"
20044-280 = "ふふ、明けまして\nおめでとうございます。"
20044-290 = "今年も健やかな一年と\nなりますように。"
20044-300 = "クリスマスですね。\n脂肪がつきやすい日です。"
20044-310 = "ですが、心配は無用です。"
20044-320 = "脂肪とは貯めこんだ燃料……"
20044-330 = "すなわち、エネルギッシュな\nトレーニングをする準備が\nできているということ……！"
20044-340 = "……トレーナー？\nどちらへ？"
20044-350 = "この日のために\nプロテインキャンディを\n特注しました。"
20044-360 = "かぼちゃフレーバーです。"
20044-370 = "栄養バランスを\n極めた力作です。"
20044-380 = "お一つどうぞ。\n味は……分かりません。"
20044-400 = "お疲れ様でした！\nトレーナー！"
20044-410 = "本当に、\n見事な走りでした。"
20044-420 = "どうぞ、お飲み物を\nご用意しています。"
20044-430 = "ええ、この努力は\n報われるべきです。"
20044-440 = "ちゃんとしたご褒美が\nあってこそ、ですから。"
20044-450 = "もちろん、\n世の中のすべてが――"
20044-460 = "努力に比例した評価が\n与えられるわけでは\nありません。"
20044-470 = "それでも私は……"
20044-480 = "頑張った人がきちんと\n報われて欲しいと、\n思うのです。"
20044-490 = "さあ、お飲みください。"
20044-500 = "私も一杯、いただきます。"
20044-2600 = "細やかなご指導、感謝します。\nこれに満足せず、\nこれからも精進していきます。\nさあトレーナー、\nもうワンセットいきましょう！"
