[translation]
20051-10 = "Blue Archive!!"
20051-20 = "Chamada atendida e aqui estou! De volta à ação!\nA garota mágica, Magical Uzawa Reisa, chegou!"
20051-30 = "H-hoje também...\nTem muita gente aqui..."
20051-40 = "T-tentar agir...\nO mais naturalmente possível..."
20051-50 = "(Ah! Essa parte...\nEu conheço essa história!)"
20051-60 = "Vocês todos parecem\nse divertir muito!"
20051-70 = "(Ah não...\nPegaram o meu lugar...)"
20051-80 = "Fufufu...\nVocê se atrasou, Sensei.\nNão, não,\nnão fique desanimado!"
20051-90 = "Porque uma aliada da justiça\nsempre chega antes de qualquer um!"
20051-100 = "Esqueça a Reisa Uzawa\ndo Comitê de Vigilância..."
20051-110 = "A partir de hoje, eu sou...\nA Suprema Garota Mágica do Comitê de Vigilância,\nUzawa Reisa!"
20051-120 = "Respondendo ao chamado do Sensei...!"
20051-130 = "Thermite Pink,\nchegou para o serviço!"
20051-140 = "O que acha de criarmos\nuniformes para o Comitê de Vigilância?"
20051-150 = "Já que vamos fazer, que seja\num bem estiloso assim!"
20051-160 = "Volt Forward!\nThermite Pink...!"
20051-170 = "Ah! Olá, Sensei!\nEu estava só praticando\nminhas falas..."
20051-180 = "Sensei, você conhece a frase icônica\ndo episódio 4 da 3ª temporada\nde \"MahoReva\"?"
20051-190 = "\"Quanto mais quentes forem a amizade e o poder de fogo, melhor\", é isso!\nÉ uma frase incrível, não é?"
20051-200 = "Senti uma fominha...\nJá sei!"
20051-210 = "Estou pensando em ir comprar um pão,\nvocê quer um também, Sensei?"
20051-220 = "Sensei, feliz aniversário!"
20051-230 = "Se eu pudesse usar magia,\neu lançaria um feitiço de bênção em você!\nHehehe."
20051-240 = "Aniversário?\nDe quem?\n...Ah! É o meu!"
20051-250 = "Obrigada por me desejar\nfelicidades!\nHehehe..."
20051-260 = "Sensei, feliz ano novo!\nQue este ano seja repleto\nde justiça!"
20051-270 = "Magical~ Christma~s!"
20051-280 = "Ah! Não era Magical,\nera Merry!"
20051-290 = "Gostosuras ou travessuras!\nFeliz Halloween!"
20051-300 = "Fantasia de bruxa? Não, não!\nIsso é de garota mágica!"
20051-310 = "Bruxas e garotas mágicas\nsão coisas totalmente diferentes, sabia?"
20051-330 = "Salva!"
20051-340 = "Fufu... A paz da pipa\nfoi preservada!"
20051-350 = "Bem antes de cair na água!\nEu consegui\npegá-la assim!"
20051-360 = "Se for pelo bem de todos,\no Comitê de Vigilância não hesita!"
20051-370 = "Seja no fogo,\nou na água!\nEu pulo em qualquer lugar\npara salvar o dia!"
20051-380 = "Nihehe...!"
20051-390 = "O traje de um herói é algo que..."
20051-400 = "Brilha de verdade quando\nvocê está cumprindo\nseu dever como herói!"
20051-410 = "Além disso, pode colocar\nna máquina de lavar,\nentão está tudo bem!"
20051-420 = "E também... foi o Sensei\nquem me ensinou."
20051-430 = "Que quem não hesita — é capaz de proteger a todos!\nHehehe!"
20051-440 = "Hehe, e, heee... \nAtchim!!"
20051-450 = "Uuuu..."
20051-2600 = "O Sensei é sempre tão gentil comigo...\nEstar aqui com você assim... faz com que eu sinta que posso me tornar a mais forte de todas...!"
