[translation]
20052-10 = "Blue Archive, mufufu."
20052-20 = "Impressão, encadernação, gestão, distribuição... Se precisar de conselhos sobre livros, sinta-se à vontade para procurar a chefe do Departamento Editorial de Red Winter, Yakumo Aramaki. Mufufu."
20052-30 = "Bem... Quais serão os novos canais de venda...?"
20052-40 = "Aqui é tão quentinho e relaxante..."
20052-50 = "Se eu montasse uma banca de vendas ali... Mufufu."
20052-60 = "A literatura atual é quase como um negócio de plataforma, sabe?"
20052-70 = "Bem, qual será o faturamento de hoje...?"
20052-80 = "Ah, eu estava me perguntando quando você viria..."
20052-90 = "Estive esperando ansiosamente por você, Sensei."
20052-100 = "Então, vamos começar a discutir o novo projeto conjunto entre o Departamento Editorial e o Schale..."
20052-110 = "Vamos conversar com calma, sim? Mufufu."
20052-120 = "Eu estava esperando por você, Sensei."
20052-130 = "Enquanto esperava aqui, selecionei cuidadosamente os melhores livros para a estante do Schale..."
20052-140 = "Como chefe do Departamento Editorial, preparei uma lista para você."
20052-150 = "...Se você me pedir, posso trazer qualquer um deles agora mesmo. Mufufu."
20052-160 = "Criar planos de negócios é quase um hobby para mim, sim."
20052-170 = "Estranho? Bem, suponho que sim."
20052-180 = "Eu gosto de pensar nas possibilidades."
20052-190 = "Escrever conforme as ideias surgem é surpreendentemente divertido, sabe?"
20052-200 = "...Isso não é um plano de negócios, é um caderno de ideias?"
20052-210 = "O que está dizendo! Não é um caderno de ideias, não!"
20052-220 = "Onde que... bem, é que..."
20052-230 = "Nossa, negociar orçamento com a secretaria... é realmente exaustivo."
20052-240 = "Mas... no fim das contas, o que importa é conseguir o orçamento."
20052-250 = "Se eu puder propor um projeto tão atraente que a secretaria fique desesperada para aprovar..."
20052-260 = "Poderei obter um orçamento muito maior do que o que conseguiria apenas como verba do departamento...! Mufufu."
20052-270 = "Usei vários meios de transporte para chegar ao Schale, mas..."
20052-280 = "As instalações ferroviárias por aqui são muito bem feitas... é até invejável..."
20052-290 = "...Embora não seja só isso que eu invejo."
20052-300 = "Ultimamente, o mercado editorial está um pouco difícil, sabe?"
20052-310 = "Existe uma tendência de que o texto perca espaço para os vídeos..."
20052-320 = "Foi então que percebemos."
20052-330 = "Se o Departamento Editorial começar a produzir vídeos, mataremos dois coelhos com uma cajadada só!"
20052-340 = "Ah... deixando as formalidades de lado, o Schale é um lugar muito bom."
20052-350 = "Dá até vontade de me transferir para cá."
20052-360 = "É quente, as instalações são completas, há muitas oportunidades de negócios... e o Sensei também está aqui."
20052-370 = "...O Schale não é uma escola, então não posso me transferir?"
20052-380 = "...E assim, mais uma vez, sou esmagada pela dureza da realidade."
20052-390 = "Ora, ora, se não é o protagonista do dia."
20052-400 = "Feliz aniversário, Sensei. Aceite este pequeno presente da minha parte."
20052-410 = "Aqui, um vale-livro. ...Estarei esperando você usá-lo. Mufufu."
20052-420 = "Hoje é dia 18 de maio, sabia?"
20052-430 = "Não esqueceu, esqueceu? Não tem nada para me dizer?"
20052-440 = "Como esperado do Sensei! Você sabe bem quando é meu aniversário!"
20052-450 = "O ano começou, hein... hum..."
20052-460 = "Muitos negócios planejam algum tipo de evento para as vendas de início de ano, mas..."
20052-470 = "Isso acaba sendo um dilema, na verdade..."
20052-480 = "Como todo mundo faz, não se pode esperar um grande impacto econômico,"
20052-490 = "mas se você não fizer, acaba ficando para trás."
20052-500 = "Dizem que a época do Natal é a melhor para as vendas, não é?"
20052-510 = "Mas essa temporada\nqualquer coisa que lançarmos\nprovavelmente vai vender..."
20052-520 = "Esse tipo de planejamento\nfácil, imprudente e simplório\né o que arruína os negócios."
20052-530 = "Hoje é Halloween, não é?"
20052-540 = "Essa é uma dúvida que surgiu\ndesde que conheci o Sensei,\nmas..."
20052-550 = "Ganhar um doce do Sensei\nou ganhar o direito de\npregar uma peça no Sensei."
20052-560 = "Qual dos dois\né mais vantajoso, hein?"
20052-580 = "Oh... é bem fofinho."
20052-590 = "Surpreendentemente bom...\nquem sabe."
20052-600 = "...foi o que pensei, mas\nainda está frio, afinal."
20052-610 = "Atchim!"
20052-620 = "Conseguiu tirar a foto?\nEntão agora é a vez do Sensei."
20052-630 = "Ué?\n...Você não vai me dizer que\npretende deixar só eu fazer isso, vai?"
20052-640 = "Ora, ora, acho que isso\né simplório demais,\nnão acha, Sensei?"
20052-650 = "O General Inverno de\nRed Winter é igual\npara todos, sabe? Mufufu."
20052-2600 = "Tolos e tesouras só servem se bem usados...\nA partir de agora, acho que finalmente\nconseguirei fazer com que cumpram o contrato \"direitinho\"... Mufufu."
