[translation]
20060-10 = "Blue Archive, here we go!"
20060-20 = "Ibuki is going to the beach with everyone too! Let's set sail, Sensei!"
20060-30 = "Once we're out of the water, we have to brush off the sand and dry ourselves off..."
20060-40 = "If I drink some coffee, do you think I'll be able to play for longer?"
20060-50 = "Sensei... are you still not ready yet? Ehehe..."
20060-60 = "I wonder if they sell pudding here?"
20060-70 = "Coffee smells so good, but it's super bitter. Why is that?"
20060-80 = "Sensei! Hurry, hurry! Finish your work so we can go to the beach together!"
20060-90 = "Sensei! I'm all done getting ready for work!"
20060-100 = "I did it all by myself! Ehehe, am I a good girl?"
20060-110 = "Sensei, you should wear a swimsuit too! It's so cool and comfy! Ehehe!"
20060-120 = "Whoa! This chair is cold! That's strange... is it because I'm sitting on it in my swimsuit?"
20060-130 = "I'll do my best with my duty work!"
20060-140 = "Everything feels so fun when I'm wearing a swimsuit!"
20060-150 = "So cool... Ehehe!"
20060-160 = "If I work hard, do you think I can be as cool as the upperclassmen?"
20060-170 = "I have a present for you today, Sensei!"
20060-180 = "Ta-da! It's a special seashell! Isn't it pretty?"
20060-190 = "Ehehe, happy birthday, Sensei!"
20060-200 = "Today is my birthday!"
20060-210 = "So... I really want to play with you all day long!"
20060-220 = "The big sun coming up from the ocean was so beautiful, wasn't it?"
20060-230 = "Happy New Year, Sensei! Ehehe!"
20060-240 = "I hung up so many stockings!"
20060-250 = "Now Santa will bring presents for you and the upperclassmen too, right?"
20060-260 = "It's Halloween today, so if I play outside like this—"
20060-270 = "Huh? I should wear something over this? Why?"
20060-290 = "Sensei! Over here, over here!"
20060-300 = "It's super cool here!"
20060-310 = "No matter how strong the sunlight is—"
20060-320 = "If we're here... see? It's not hot at all!"
20060-330 = "So, you see!"
20060-340 = "We don't have to keep moving the parasol anymore, Sensei."
20060-350 = "...Yeah. Actually, I was watching."
20060-360 = "I saw you struggling to carry the parasol over here..."
20060-370 = "But it'll be fine here!"
20060-380 = "Let's take a nice, long rest together!"
20060-2600 = "I'll treasure this forever and ever! I promise! Thank you, Sensei!"