[translation]
23004-20 = "少女を美しくするのは\n化粧ではなく熱情さ。"
23004-30 = "…先生のロボットを作ったら…\nお金持ちになれるかも。"
23004-40 = "そういえば、\nそろそろヘリの整備もしなきゃ。"
23004-50 = "うーん…\n戦闘機能を持った\n洗浄便座なんてどうかな。"
23004-60 = "どうして誰も光学迷彩下着を必要と\nしないのだろう…。\n自信作だったのに…。"
23004-70 = "うーん…。\n何か修理が必要なものは、\nないのかな。"
23004-80 = "ようこそ、先生。\n今日一日、よろしくね。"
23004-90 = "私を呼んだのは、\n合理的な選択だね。"
23004-100 = "その期待に応えられる\nように、頑張るよ。"
23004-110 = "(うーん…先生は…\n本当に、分析が難しいな)"
23004-120 = "…計算通りだ。\nこうやって\n一緒にいられる。"
23004-130 = "ミレニアムの戦闘は、\nどれだけ優秀な技術者と\n一緒なのかで決まるんだ。"
23004-140 = "私たちは、先生と\n一緒にいることで\nさらに多くのことが\n可能になった。"
23004-150 = "機械の真善美は\n合理的で、精密で、\nそして簡易で\nあることだね。"
23004-160 = "お誕生日おめでとう\n先生。"
23004-170 = "そしたら今年で\n年式はいくつになる？"
23004-180 = "今日が私の誕生日？"
23004-190 = "そうか。忘れていた。\nあまり重要じゃなかったから…"
23004-200 = "でも…先生が\n祝ってくれるのは、\nなんだか嬉しいね。"
23004-210 = "明けまして\nおめでとう先生。"
23004-220 = "今年の私は、\nもっと優しい\n私になる。"
23004-230 = "…先生がいるから。"
23004-240 = "サンタが最新機器を\nプレゼントして\nくれたらいいのに。"
23004-250 = "うん？\n直接作った方がいいって？"
23004-260 = "えっと。\nそれは…"
23004-270 = "サンタクロースを？"
23004-280 = "動くカボチャの人形を\n作ってくれって\n頼まれたんだ。"
23004-290 = "しかし、自爆機能を\n搭載したことを理由に\n納品を断られた。"
23004-300 = "……理解できない。\n自爆機能のないロボットは\nただの鉄くずなのに。"
23004-320 = "どれどれ……\nふむ、軸周りが緩く\nなっているな。"
23004-330 = "ということは、\nベアリングが……。"
23004-340 = "うん、もしかしたら\n部品の交換が\n必要かもしれないね。"
23004-350 = "……先生、これは、\n見ていて面白いかい？"
23004-360 = "先生が良いのであれば、\n別に構わないのだけど……。"
23004-370 = "多少なりとも危険が伴うから、\nあっちの方で座りながら\n見るのをお勧めするが……。"
23004-380 = "この辺りは鋭利な鉄くずが\nあちこちに散らばるし、"
23004-390 = "油の匂いもひどいし、\nそれに……。"
23004-400 = "顔が、汗と煤だらけになる、\nから……。"
23004-410 = "いや、何でもない……\n今のは忘れてくれ。"
23004-420 = "……なるほど、思った通り。"
23004-430 = "潤滑油が足りなくて、\nベアリング部分が\n摩耗しているみたいだ。"
23004-440 = "そっちにあるスパナ、\n取ってくれるかい？"
23004-450 = "あ……すまない、\n今のはその、\nいつもの癖でつい……。"
23004-460 = "……とはいえやはり、\n隣で誰かが手伝ってくれた\n方が効率的だし、"
23004-470 = "気分も高揚することは\n否定できなさそうだ。"
23004-480 = "先生も、顔が煤だらけに\nなってしまうだろうけど……"
23004-490 = "手伝ってくれるかい？"
23004-2600 = "私の指先で成り立つ奇跡。\n設計と製作。\n先生。これからの私に期待していて。"
