[translation]
26006-20 = "Você é o Sensei que eu estive observando através do telescópio esse tempo todo, não é...? Eu estou tão emocionada...!"
26006-30 = "Fufu, encontrei um móvel maravilhoso!"
26006-40 = "O que será que tem ali do outro lado...?"
26006-50 = "Preciso sair logo desta classe especial..."
26006-60 = "Este lugar é tão bonito, não é?"
26006-70 = "Onde será que o Sensei está...?"
26006-80 = "Eu sabia que você voltaria logo!"
26006-90 = "Eu estive... eu estive te observando esse tempo todo!"
26006-100 = "Ué? O Sensei estava ali até agora há pouco..."
26006-110 = "Ah, v-você me assustou! D-desde quando você está aí? N-não, eu não estava te vigiando!"
26006-120 = "Haah, haah... No fim das contas, observar o Sensei é o que eu mais gosto de fazer."
26006-130 = "Fufu... Eu nunca me canso de olhar para o rosto do Sensei!"
26006-140 = "Ugh... Eu não faço esse tipo de coisa com qualquer um, sabia?"
26006-150 = "Quando olho para este vasto universo..."
26006-160 = "Sinto novamente como a vida humana é realmente efêmera."
26006-170 = "Fufu, um dia eu adoraria ir observar o céu noturno com você, Sensei."
26006-180 = "Feliz aniversário, Sensei!"
26006-190 = "Eu vou ficar de olho em você o dia todo para garantir que nada de ruim aconteça!"
26006-200 = "Sensei, sabia? Na noite do meu aniversário, se você olhar para o céu noturno..."
26006-210 = "Dá para ver um par de estrelas gêmeas passando pelo céu do sul. E esse dia é justamente..."
26006-220 = "Hoje!"
26006-230 = "Espero que este ano eu consiga sair daqui e voltar para o prédio principal..."
26006-240 = "A vista noturna do Natal, quando vista de longe,"
26006-250 = "parece o céu noturno, brilhante e linda."
26006-260 = "Será que neste Halloween, nós também receberemos doces...?"
26006-280 = "Ah, uma estrela cadente! Ah... ali também! E ali!"
26006-290 = "O céu está cheio de estrelas cadentes! Elas estão caindo como se fosse chuva!"
26006-300 = "Poder ver um espetáculo tão lindo assim... parece um sonho."
26006-310 = "Se eu tenho algum desejo?"
26006-320 = "Não... hoje, estou satisfeita."
26006-330 = "Já que estou podendo ver um céu estrelado tão lindo ao lado da pessoa que eu gosto,"
26006-340 = "se eu pedir mais alguma coisa, sinto que as estrelas vão acabar me dando uma bronca..."
26006-350 = "Por hoje, isso já basta."
26006-2600 = "Muito obrigada, Sensei! Vou cuidar disso com tanto carinho quanto cuido do meu telescópio!"
