[translation]
10055-450 = "Ei, Sensei. Se não se importar, poderia me ajudar com o trabalho na estância termal?"
10055-460 = "Tem um minuto? Queria fazer um pouco de exercício antes de entrar na fonte termal."
10055-470 = "A Nodoka é uma garota muito esforçada."
10055-480 = "Hehe, o Mols desta vez ficou muito bom."
10055-490 = "Hm? Você quer ir ao banho comigo?"
10055-500 = "Brincadeira. Não precisa ficar com essa cara séria."
10055-510 = "Bom trabalho. Se quiser, quer provar um pouco de Mols?"
10055-520 = "Como esperado do Sensei. Agora entendo por que você é tão popular com todos."
