[translation]
10068-70 = "Ah, Sensei!\nPor aqui!"
10068-80 = "A super-heroína\nda força de autodefesa!"
10068-90 = "Uzawa Reisa,\nà sua disposição!"
10068-100 = "Sim!\nUzawa Reisa,\naguardando ordens!"
10068-110 = "Aconteceu alguma coisa?\nPode me chamar\na qualquer momento!"
10068-120 = "Um incidente!?\nOnde!?\nQuem está envolvido!?"
10068-130 = "Hmm...\nFicar parada é a coisa\nmais difícil de todas..."
10068-340 = "Ah, Sensei!\nPor aqui!"
10068-350 = "A super-heroína\nda força de autodefesa!"
10068-360 = "Uzawa Reisa,\nà sua disposição!"
10068-370 = "Oooooh!\nAs coisas estão\nficando animadas!"
10068-380 = "É o sprint final!"
10068-390 = "Vamos correr\naté o fim!"
10068-400 = "Sim!\nUzawa Reisa,\naguardando ordens!"
10068-410 = "Aconteceu alguma coisa?\nPode me chamar\na qualquer momento!"
10068-420 = "Um incidente!?\nOnde!?\nQuem está envolvido!?"
10068-430 = "Hmm...\nFicar parada é a coisa\nmais difícil de todas..."
10068-440 = "São coisas que encontrei durante a patrulha! Quer dar uma olhada, Sensei?"
10068-450 = "Fazendo este trabalho,\nacabo encontrando muitos\nobjetos perdidos..."
10068-460 = "Espero que os donos\nsejam encontrados logo."
10068-470 = "Precisa de mais alguma coisa?\nVou verificar agora mesmo!"
10068-480 = "Hm? Está procurando por algo?"
10068-490 = "Será que isso não\nestá por aqui?"
10068-500 = "Se precisar de algo,\né só pedir!"
10068-510 = "Trarei para você imediatamente!"
10068-520 = "Oh, entendo, entendo."
10068-530 = "Hmm! Isso também é uma boa ideia."
10068-540 = "Então era isso que\nvocê estava procurando!"
10068-550 = "Sim, aqui está,\npode pegar!"
10068-560 = "Ah!\nOlá, Sensei!"
10068-570 = "Temos uma pilha de incidentes\nque precisam ser resolvidos!"
10068-580 = "Preparei uma lista!\nVamos conferir juntos!"
10068-590 = "Hm...? Sensei?\nO que houve?"
10068-600 = "Foco!\nPor favor, foque no trabalho!"
10068-610 = "Ooooh!\nComo esperado do Sensei!"
10068-620 = "Muito bom! Estamos indo bem!!"
