[translation]
10097-10 = "Esta é apenas uma operação de infiltração para investigar o incidente... Espero que termine bem."
10097-20 = "RABBIT 1. Preparativos da operação concluídos. Sensei, dê as ordens."
10097-30 = "Quando foi a última vez que comi um sanduíche cheio de camarão?"
10097-40 = "(Espero não parecer animada demais...)"
10097-50 = "Durante a minha ausência, os cuidados com Pyonko..."
10097-60 = "Estão sendo feitos pelo pessoal do Departamento de Segurança Pública da Valkyrie."
10097-70 = "Às vezes, parece que a Pyonko está mais apegada ao pessoal do Departamento de Segurança Pública do que ao RABBIT Squad,"
10097-80 = "o que me deixa um pouco triste..."
10097-90 = "A primeira expedição do RABBIT Squad... Meu coração está um pouco acelerado."
10097-100 = "Agora é a nossa vez, da SRT!"
10097-110 = "RABBIT 2, pronta! Podemos ir a qualquer momento!"
10097-120 = "Tentei me vestir como uma turista comum, mas..."
10097-130 = "Será que estou parecendo suspeita?"
10097-140 = "Hum... Sensei, tem algo no meu estômago?"
10097-150 = "Na verdade, não gosto muito de frutos do mar. É difícil de conservar."
10097-160 = "Ah, mas se for algo seco, como lula desidratada... eu gosto!"
10097-170 = "Iii... Parece uma vila de pescadores de um romance de terror..."
10097-180 = "Quero voltar logo para a escola..."
10097-190 = "Ah, nossa escola, ela já..."
10097-200 = "V-v-você está me chamando...?"
10097-210 = "(Por que será que vim parar em uma vila tão remota como esta...)"
10097-220 = "Este penteado, a Miyako-chan fez em mim logo antes de partirmos para a operação."
10097-230 = "Hehe... Talvez isso seja fofo..."
10097-240 = "Pardais, doninhas, gaivotas..."
10097-250 = "Por que será que os animais selvagens se aproximam tanto de mim...?"
10097-260 = "Então esta é a Vila Yodoura, famosa pelos camarões..."
10097-270 = "Talvez seja a primeira vez que venho aqui de verdade."
10097-280 = "O que será que está acontecendo nesta vila?"
10097-290 = "Será por causa da névoa...?"
10097-300 = "Está um pouco frio, mesmo sendo verão..."
10097-310 = "Hmm. De fato, parece que há um cheiro de destruição em algum lugar..."
10097-320 = "Embora seja uma operação da SRT,"
10097-330 = "o mar no verão é diferente do habitual, então serve como uma mudança de ares."
10097-340 = "Esta boia é suspeita?"
10097-350 = "Bem, com certeza não é para uso comum. Kuhihi..."
10097-620 = "Então esta é a Vila Yodoura, famosa pelos camarões..."
10097-630 = "Talvez seja a primeira vez que venho aqui de verdade."
10097-640 = "O que será que está acontecendo nesta vila?"
10097-650 = "Os 'Profundos'..."
10097-660 = "Se aquele boato for verdade, será que aguentaria até uma bomba enorme?"
10097-670 = "O 'Kusaya' fica com aquele cheiro só por causa da fermentação?"
10097-680 = "Talvez eu queira tentar fazer um dia... Kuhihi."
10097-690 = "Hehe. Com isso, finalmente,"
10097-700 = "poderemos comer aquele delicioso sanduíche de camarão com manjericão, né?"
10097-710 = "Será por causa da névoa...?"
10097-720 = "Está um pouco frio, mesmo sendo verão..."
10097-730 = "Hmm. De fato, parece que há um cheiro de destruição em algum lugar..."
10097-740 = "Embora seja uma operação da SRT,"
10097-750 = "o mar no verão é diferente do habitual, então serve como uma mudança de ares."
10097-760 = "Esta boia é suspeita?"
10097-770 = "Bem,\nnão há dúvidas de que\nnão é para uso diário. Hehehe..."
