[translation]
10101-10 = "次の仕事は…"
10101-20 = "あ、先生、\n何か手伝ってほしいのか？"
10101-30 = "い、いらっしゃいませ！\n何名様…"
10101-40 = "…あ、先生だったか。\nすまない。反射でつい。"
10101-50 = "海は…\n果てしなく広くて、\n驚くほど水が多いのだな。"
10101-60 = "感心した。"
10101-70 = "もう少し\n時間があったら、\nステージの完成度を\nあげられたのに…。"
10101-80 = "海風は涼しいな。"
10101-90 = "熱を冷ますのに\nちょうどいい。"
10101-100 = "楽しいお祭りになるよう、\n最善を尽くそう。"
10101-110 = "先生も、どうかお祭りを\n楽しんでくれ。"
10101-120 = "もう少し\n時間があったら、\nステージの完成度を\nあげられたのに…。"
10101-130 = "海風は涼しいな。"
10101-140 = "熱を冷ますのに\nちょうどいい。"
10101-150 = "楽しいお祭りになるよう、\n最善を尽くそう。"
10101-160 = "先生も、どうかお祭りを\n楽しんでくれ。"
10101-750 = "悪いが先生、\n少し力を貸してくれ。"
10101-760 = "私一人では手が回らなくてな。"
10101-770 = "今日の業務リストだ。\n先生、手伝ってもらえるか？"
10101-780 = "アルバイトで生計を\n立てている身だ。"
10101-790 = "仕事の案件は、しっかり\n管理しなければならない。"
10101-800 = "せ、先生、私に用か？"
10101-810 = "おかげで助かった。\n先生は敏腕だな。"
10101-820 = "もう片付けたのか…？"
10101-830 = "お礼にこれを…\n受け取ってくれ。"
