[translation]
10145-10 = "青い空、\n眩しい日差し――夏じゃ。\nとなれば、避暑じゃろう？"
10145-20 = "ふふっ……\n其方がどう思っているかは\n知らぬが。"
10145-30 = "妾は、\nとても浮かれておるぞ？"
10145-40 = "良い場所じゃのう。"
10145-50 = "とくにあそこ――"
10145-60 = "自然の前では、"
10145-70 = "妾たちは無力であると\n痛感させられるのう。"
10145-80 = "先生と一緒なら、\nキキはどこでも\n嬉しいです！"
10145-90 = "……なんじゃ、\n見ているだけかえ？"
10145-100 = "誰しも未熟な時は\nあるというもの。"
10145-110 = "じゃが、世の理は"
10145-120 = "学び続けねばならぬ。\n妾たちとて、な。"
10145-130 = "無事に終わったのう。"
10145-140 = "ふふっ……じゃが、\n妾たちの避暑は、"
10145-150 = "まだまだこれから\nじゃろう？"
10145-160 = "ん？どうしたのじゃ、\n先生。"
10145-170 = "ふふっ、ほれ。\n存分に堪能すると良い。"
10145-180 = "門主の柔肌――じゃよ？"
10145-190 = "ここへ先生と\n来られるなんて……\nまこと、夢のようじゃ。"
10145-200 = "ふふっ……\n深い意味はないさの。"
10145-210 = "身体の調子が\n悪いわけでもない。"
10145-220 = "言葉とおりに\n受け止めると良い。"
10145-230 = "青い蝶は、\n山海経において「不滅」を\n意味する。"
10145-240 = "「諦めを知らぬ」"
10145-250 = "とも言い換えられるな。"
10145-260 = "ふふ。なあに、\nただの戯言だと\n思ってくれて構わんよ。"
10145-270 = "妾のワガママに\n付き合ってもらって\n悪いのう、先生。"
10145-280 = "恩に着る。"
10145-290 = "ああ、そうさな……\n先に謝っておこうか。"
10145-300 = "……今からもっと、\n我が儘を言うつもり\nじゃからの。"
10145-790 = "先生こんにちは！\nキキです！"
10145-800 = "今日はお店番を\nすることになりました！"
10145-810 = "えっ、キサキ？\nキキにはちょっと\n分からないです……。"
10145-820 = "いらっしゃいませ、先生！"
10145-830 = "キキ、お店番\n頑張ってるんですよ？\nなでなでしてください！"
10145-840 = "来てくださり\nありがとうございます！"
10145-850 = "お買い逃しのないよう、\nゆっくり見ていって\nくださいね！"
10145-860 = "先生はどれが好きですか？\nキキは～……。"
10145-870 = "先生が選んだ\nものなら、\n何でも好きです！"
10145-880 = "水着、\n着てみたんですが……。"
10145-890 = "どうでしょう？\n似合っていますか？\n可愛いですか？"
10145-900 = "実はキキ……泳ぐの\n得意じゃないんです。"
10145-910 = "あっ、それキキも\n気になってました！"
10145-920 = "あっ！\nこういう時には\nこう言うんですよね！"
10145-930 = "「お買い上げ\nありがとうございます！」"
10145-940 = "わあ！\nキキにも見せて\nください！"
10145-950 = "はい、どうぞ！\nキキ、よくできてますか？"
