[translation]
10152-500 = "ようこそ。夢と\n希望のワンダーランドへ。"
10152-510 = "ふふっ、先生を導く\nことができて光栄です。"
10152-520 = "みなさんの努力が、\n実を結びますように。"
10152-530 = "そろそろ……\nエンディングの\nお時間ですね。"
10152-540 = "饗宴の準備は\nできています。"
10152-550 = "先生の魂に残る\n調べであったのなら、\n幸いです。"
10152-560 = "先生もコープス・\nペイントを\nしてみませんか？"
10152-570 = "私にお任せください。\n素敵に仕上げて\n見せますよ？"
10152-580 = "…やはり、バニーガールの\n格好でお迎えすべきで\nしたでしょうか？"
10152-590 = "私のギターは、\n平和を歌っています。"
10152-600 = "……ええ、\n嘘はついてませんとも。"
10152-610 = "ふふっ。\nセッションで触れる\n魂の共鳴も素敵ですが……"
10152-620 = "指先のふれあいも、\n大切にしていきたい\nですね。"
