[translation]
16008-10 = "Parece que você está ocupado\nhoje também, Sensei."
16008-20 = "Eu comprei agorinha\npouco, mas...\nQuer um donut de chocolate?"
16008-30 = "Patrulhar\ndá tanta preguiça..."
16008-40 = "Ufa, que paz."
16008-50 = "Esse clima animado de\nDia dos Namorados\nnão é nada mau."
16008-60 = "Mas acima de tudo...\nassim que essa\népoca acabar,"
16008-70 = "Um monte de donuts\nde chocolate encalhados\nvão entrar em liquidação!"
16008-80 = "A menos que algo\nmuito grave aconteça,"
16008-90 = "Eu acho que não vai ter nenhum motivo\npra nós da Segurança Pública\nentrarmos em ação."
16008-100 = "Por exemplo..."
16008-110 = "A Raposa da Calamidade\nroubar um carro-forte ou algo do tipo."
16008-120 = "Haha, brincadeira, brincadeira.\nUma coisa dessas\nnunca vai acontecer."
16008-130 = "Eu acho que não vai ter nenhum motivo\npra nós da Segurança Pública\nentrarmos em ação."
16008-140 = "Por exemplo..."
16008-150 = "A Raposa da Calamidade\nroubar um carro-forte ou algo do tipo."
16008-160 = "Haha, brincadeira, brincadeira.\nUma coisa dessas\nnunca vai acontecer."