[translation]
16015-10 = "Bem-vindo de volta, Sensei!\nEstava esperando por você!"
16015-20 = "Sensei! Se não se importar, por favor,\nveja os resultados do meu treino!"
16015-30 = "Está indo tudo bem!\nEu também vou me esforçar!"
16015-40 = "Vou me esforçar até o fim!\nPor favor, continue olhando, Sensei!"
16015-50 = "Ah... que alívio!\nComo foi para você, Sensei?"
16015-60 = "Sensei? ...Você me chamou?"
16015-70 = "É, bem..."
16015-80 = "Se você ficar me cutucando\nassim..."
16015-90 = "I-isso faz cócegas,\nSensei..."
16015-100 = "Ahaha..."
16015-110 = "Ah, não~! Eu também vou\nretribuir, viu?"
16015-690 = "Olá, Sensei!\nEstava esperando por você!"
16015-700 = "Você veio, Sensei!\nEu organizei o progresso para você!"
16015-710 = "Se, Sensei...?"
16015-720 = "N-não olhe para mim,\nolhe para lá..."
16015-730 = "Sim! É por aqui!"
16015-740 = "Verificação concluída!"
