[translation]
20005-140 = "Sente-se o cheiro\nrefrescante do mar, não é?"
20005-150 = "Espero que tenhamos\numas férias divertidas!"
20005-160 = "Estou pronta! Também trouxe\na boia do Peroro-sama\ncomigo!"
20005-170 = "Ué? A chave do vestiário,\ntenho certeza de que a deixei aqui...?"
20005-180 = "Hum, bem... E-eu fico\ncom vergonha se você\nficar me encarando\nassim..."
20005-190 = "Finalmente chegamos!\nO mar, é o mar!"
