[translation]
20010-230 = "いらっしゃいませ。\n227号温泉郷へようこそ！"
20010-240 = "あわわっ！せ、先生！？\nあれ、今日ご予約\nされてましたっけ……！？"
20010-250 = "お金も稼げて、\nきれいな景色も\nたくさん見られて……"
20010-260 = "温泉郷、最高ですね！"
20010-270 = "どうかしましたか、先生？\n何か足りない\n備品とかありました？"
20010-280 = "ふふっ……今の私は、\nこれまでとは一味も二味も\n違いますよ！"
20010-290 = "ふふっ、今の私は\n余裕があるので何と……"
20010-300 = "食後にプリンを、\n二つも食べちゃいます！"
20010-310 = "温泉郷、最高ですね！"
20010-320 = "どうかしましたか、先生？\n何か足りない\n備品とかありました？"
20010-330 = "ふふっ……今の私は、\nこれまでとは一味も二味も\n違いますよ！"
20010-340 = "ふふっ、今の私は\n余裕があるので何と……"
20010-350 = "食後にプリンを、\n二つも食べちゃいます！"
20010-360 = "温泉グッズなどもたくさん\n準備していますよ！"
20010-370 = "もし使っていないものなどが\nありましたら、こちらで別の商品と\n交換させていただきます！"
20010-380 = "無念ではありますが、\n227号温泉郷の営業は\n終了いたしました……。"
20010-390 = "先生？\nどうされましたか？"
20010-400 = "い、いくら先生でも、\nタダでお渡しするわけには……！"
20010-410 = "お買い上げありがとう\nございます！"
20010-420 = "いつもありがとうございます、\n先生。"
20010-430 = "本日もご利用いただき、\nありがとうございます！"
20010-440 = "こ、こんなに良い物を\n頂いてしまって、\n良いのでしょうか……！？"
