[translation]
20037-150 = "やぁ、先生。お疲れー"
20037-160 = "ウォーターパーク……\n仕事じゃなきゃ、\n好きな場所なのに……"
20037-170 = "みんな元気いいね～。\n遊びに来てるからか。"
20037-180 = "さあ、もうすぐ\n退勤時間だよ！"
20037-190 = "色々あったけど、\nなんとか終わったね。\n先生もお疲れさん。"
20037-200 = "ウォータースライダー？"
20037-210 = "いや、\n怖いというより……め、\nめんどくさいかなぁ……"
20037-220 = "あっつい……\nこんな日に仕事だなんて、\n最悪だよ～"
20037-230 = "こういう熱い日に\nこそ糖分補給は\n大事だからね。"
20037-240 = "そう、ドーナッツは\n生活必需品ってわけ。"
20037-250 = "はっ！げ、現場異常無し！\n……って、先生？\nびっくりしたぁ。"
20037-480 = "交換しに来たの？\n色々あるから見てって～"
20037-490 = "は～ぁ、すずし～～\n先生もゆっくりして\nいってよ。"
20037-500 = "営業終了～っとさぁ、\n先生。打ち上げにでも\n行こっか？"
20037-510 = "いくら先生でも、\nタダでは渡せないなぁ？"
20037-520 = "私じゃなくて、\n商品を見なよ～"
20037-530 = "うわぁ！？\nそんなのあったんだ！"
20037-540 = "せ、先生。\n思ったより運がいいんだね？"
20037-550 = "おめでと～これ、1等だよ。"
20037-560 = "これで全部終わりかな。\nいやぁ、2人とも頑張ったね。"
