[translation]
20048-200 = "Sensei, seja bem-vindo.\nFico feliz que tenha vindo.\nPor favor, sente-se aqui."
20048-210 = "Para não ser descoberta\nenquanto faço corpo mole,\né preciso ter técnica."
20048-220 = "Fufu... quer que eu lhe\nensine os truques?"
20048-230 = "Estou preocupada com o\ntrabalho que deixei para trás..."
20048-240 = "Espero que as coisas\nestejam correndo bem..."
20048-250 = "Incidentes continuam\nacontecendo, não é..."
20048-260 = "Teria sido melhor se fosse\napenas um pesadelo..."
20048-270 = "Já é hora de ir embora?"
20048-280 = "O que aconteceu aqui também,\num dia se tornará uma\nboa lembrança, não é?"
20048-290 = "Precisa de algo?"
20048-300 = "Está quente, não é..."
20048-310 = "Vou pedir para prepararem\nalguma bebida gelada."
20048-320 = "Sim,\nmas que não seja\nchá gelado."
20048-330 = "Ora, Sensei,\ninteressado neste livro?"
20048-340 = "Sensei, sua pele vai\nqueimar se ficar aí."
20048-350 = "Venha por aqui, por favor.\nDebaixo do guarda-sol\nestá fresco."
20048-1070 = "Fique à vontade para olhar."
20048-1080 = "Temos estoque\nsuficiente."
20048-1090 = "Afinal de contas,\né a minha primeira vez\ncomo atendente."
20048-1100 = "Por favor... seja gentil\ncomigo."
20048-1110 = "Ficou satisfeito com\nsuas compras?"
20048-1120 = "Então, vamos voltar\npara casa, Sensei."
20048-1130 = "Atender clientes também é,\nde certa forma, um tipo\nde negociação...?"
20048-1140 = "Entendo, ouvir isso\nme deixa um pouco\nmais relaxada."
20048-1150 = "Atendimento, caixa, reposição..."
20048-1160 = "O escopo do trabalho é\nmais amplo do que eu pensava."
20048-1170 = "Você tem bom gosto, Sensei."
20048-1180 = "Espere um momento, por favor.\nVou embrulhar para você."
20048-1190 = "Hã!? O que eu quero...?"
20048-1200 = "Fufu, vou aceitar apenas\na sua intenção."
20048-1210 = "Fufu, sinto que peguei o jeito\nde cuidar da loja."
