[translation]
20041-280 = "Momento oportuno, hein."
20041-290 = "Eu já imaginava que\nvocê viria logo."
20041-300 = "Está tudo correndo bem.\nMas ainda não é hora\nde baixar a guarda."
20041-310 = "Em breve, poderei\nte dar um relatório completo."
20041-320 = "Espere só mais\num pouco."
20041-330 = "Fico feliz que tenha sido resolvido."
20041-340 = "……Isso é sincero."
20041-350 = "……Me tocar de repente,\no que houve?"
20041-360 = "Poderia me dizer\ncom palavras?"
20041-370 = "Por isso…… é que……"
20041-380 = "O que você……\nestá querendo de mim?"
20041-800 = "A lista já\nestá pronta."
20041-810 = "Estas são as tarefas de hoje."
20041-820 = "……Não consigo entender\nas intenções do Sensei."
20041-830 = "Só me tocar em silêncio\nnão transmite nada."
20041-840 = "……Será que,"
20041-850 = "você quer que eu faça o mesmo?"
20041-860 = "Vou verificar."
20041-870 = "Atualizei a lista."
20041-11460 = "Será que isso conta como\nparticipar no meio do caminho?"
20041-11470 = "……Conto com você\ndaqui para frente, Sensei."
20041-11480 = "Você é alguém que\nrespeita o horário, não é?"
20041-11490 = "Uma atitude realmente racional."
20041-11500 = "Este é o lugar da Himari……"
20041-11510 = "Não, é a nossa\nbase, não é?"
20041-11520 = "……Ainda não\nme caiu a ficha."
20041-11530 = "De que estou na mesma operação\nque o Sensei."
20041-11540 = "……Todos têm me tratado\nsem qualquer cerimônia."
20041-11550 = "Não é que eu não goste,\nmas……"
20041-11560 = "é um fato que estou\num pouco confusa."
20041-11570 = "Fora da área da engenharia……"
20041-11580 = "Desculpe, não entendo\ntanto assim."
20041-11590 = "……O que foi?\n……Só queria\npuxar conversa?"
20041-11600 = "Evite esse tipo de comportamento\nirracional, Sensei."
20041-11610 = "……Não cheguei a dizer\nque é desagradável."
20041-11620 = "Antes, eu pensava que precisava\nter controle absoluto\nsobre tudo."
20041-11630 = "Mas agora…… percebi o limite do que\num ser humano consegue\ncontrolar sozinho."
20041-11640 = "……Será que foi\ngraças ao Sensei?"
20041-11650 = "Recebi o repasse\nda Himari."
20041-11660 = "Atualmente, em vários locais,\nforam encontrados"
20041-11670 = "materiais misteriosos\ndo \"Deus Sem Nome\"."
20041-11680 = "Se tivermos amostras,\npoderemos fazer o reabastecimento."
20041-11690 = "Mostre-me as amostras\nque você coletou."
20041-11700 = "Agradeço pela cooperação."
20041-11710 = "Estou analisando a \"matéria\". Estou produzindo subprodutos a partir dela."
20041-11720 = "Este dispositivo está\nemetendo muito calor……"
20041-11730 = "Acho que pode ser um pouco\ndifícil para a Eimi."
20041-11740 = "Não tenho reclamações sobre a estrutura do dispositivo."
20041-11750 = "Surpreso? Fufu, até eu reconheço\nquando algo é excelente."
20041-11760 = "Ah, mas, no design e nos detalhes,\npoderia ter um pouco mais de racionalidade……"
20041-11770 = "……Acho que não há nada a ganhar\nfazendo algo assim."
20041-11780 = "……Você quer ver\nminhas expressões mudarem?"
20041-11790 = "……Entendi por que dizem\nque você é estranho."
20041-11800 = "Aqui está o resultado da análise."
20041-11810 = "Bem-vindo, o que deseja?"
20041-11820 = "……Eu só estava imitando.\nEsqueça o que acabou de ouvir."
20041-11830 = "Será que o \"escambo\"\nque existia no passado,"
20041-11840 = "era assim?"
20041-11850 = "Uma escolha racional."
20041-11860 = "Deixarei a escolha final com você."
20041-11870 = "Aqui, adotamos um método\nde análise um pouco\ndiferente."
20041-11880 = "Em resumo――\nÉ uma \"extração baseada\nem coincidências\"."
20041-11890 = "A possibilidade de perder\nem um \"sorteio\" já foi\ncomprovada pela teoria das probabilidades."
20041-11900 = "……Mas,\nnão há como evitar agora."
20041-11910 = "……Os gostos da Himari\nnão mudam, não é?"
20041-11920 = "……Uma análise multifacetada\né necessária. Sim."
20041-11930 = "Não conseguir prever\nos resultados da análise é..."
20041-11940 = "Como alguém do Seminar,\nconsidero isso um pouco lamentável."
20041-11950 = "Mesmo que você não obtenha\no resultado esperado..."
20041-11960 = "Não há nada que eu possa fazer.\nJá vou me desculpando de antemão."
20041-11970 = "\"Deus não joga dados\"……"
20041-11980 = "Embora essa proposição\nseja considerada incorreta,"
20041-11990 = "eu――em certos aspectos,\nconcordo com ela."
20041-12000 = "A mecânica quântica não é algo\nque se entende."
20041-12010 = "……É algo que se decora."
20041-12020 = "O mundo é algo que existe\nfora da cognição humana."
20041-12030 = "……Pois é,\nassim como esta análise baseada na sorte."
20041-12040 = "……Isso é……!\nÉ verdade……?"
20041-12050 = "A lei dos grandes números, entendo."
20041-12060 = "Continuar puxando até conseguir…?"
20041-12070 = "Teoricamente, não está errado,\nmas…"
20041-12080 = "A maior parte do mundo\nexiste dentro de uma distribuição normal……"
20041-12090 = "Você conseguiu, Sensei.\nParabéns."
