[translation]
10004010-1 = "第1話;シュン教官の憂鬱"
10004010-2 = "山海経・訓育支援部「梅花園」"
10004010-6 = "はあ、流石に今回は疲れましたね……。"
10004010-7 = "普段はあんなに天使みたいなのに、一度はしゃぎ始めると何を言っても聞かなくて時々困ってしまいます……。"
10004010-8 = "たまには私もあんな風に、何のしがらみもなく、駄々をこねたくなってしまいますね……。"
10004010-9 = "……いえ、私が逃げるわけにはいきません。"
10004010-10 = "あの子たちを導くことは、[ruby=せんがいきょう]山海経[/ruby]の教官としての責務！愚痴を言っている場合ではありません！"
10004010-11 = "それに、ずっと顔をしかめているのは、美容にも良くないらしいですからね。"
10004010-12 = "さて……では気分転換に、ちょっと自分へのご褒美でも頂くことにしましょうか？"
10004010-13 = "ふふっ、「バーゲンダッツ」のラムレーズン味……！"
10004010-14 = "山海経では中々手に入らない味なのでずっと大事にしてましたが……今日くらいはこれを食べて、ゆっくりしても良いですよね。"
10004010-15 = "では……"
10004010-18 = "あ、あれ？冷凍庫に入れておいたはずなのですが……？"
10004010-20 = "あれ、シュン姉さん何を探してるの？"
10004010-21 = "あら、ココナちゃん。"
10004010-22 = "ここに入れておいたアイスクリームが無くって……見たことありませんか？"
10004010-23 = "あぁ、あれ？美味しかったよ？"
10004010-24 = "えぇぇぇっ！？た、食べてしまったんですか！？"
10004010-25 = "うぅ、いつか食べようと大事にとっておいたのに……。"
10004010-26 = "で、でも先週姉さんが、「ダイエットをするのでこれからアイスやお菓子は食べません！」って言ってなかった……？"
10004010-27 = "だから逆に食べちゃった方が、シュン姉さんを苦しめずに済むかなって……。"
10004010-28 = "うぅぅぅ……。"
10004010-29 = "ご、ごめんなさい……えっと、この間買ってきた「ゴリゴリ君」のコーンポタージュ味、食べる？"
10004010-30 = "いえ、大丈夫です、ありがとうございます……ちゃんと「取っておいて」と言わなかった私も悪いですし……。"
10004010-31 = "あ、ところでシュン姉さん。ひまわり組の午後のおやつ、私の代わりにお願いしても良い？"
10004010-32 = "それは構いませんが、何か予定でも入ったのですか？"
10004010-33 = "ううん、ただ今日のおやつが「キャロットケーキ」って聞いて……私、人参はちょっと……。"
10004010-34 = "ココナちゃん……前にも言いましたけど、好き嫌いをしていると立派な教官には……"
10004010-35 = "うう、そうやってまたすぐお小言……言われなくても分かってるっ！"
10004010-36 = "とにかく、埋め合わせはどこかでするから！お願いね！"
10004010-40 = "ま、待ってください、ココナちゃん！"
10004010-42 = "……ふう。"
10004010-43 = "みなさん、どうしてそんな自分勝手に……。"
10004010-44 = "子どもたちも、ココナも……。"
10004010-46 = "私だってたまには、子どもっぽく好き勝手に振舞いたいですっ！"
10004010-47 = "……おっと、いけませんね。平常心、平常心……。"
10004010-48 = "ストレスは美容の敵！こんなことばかり考えていると、アンチエイジングも意味が無くなってしまいます。"
10004010-49 = "ただでさえ最近は疲れのせいか、お肌が荒れてきて……何か新しい美容法を探してみないとですね。"
10004010-50 = "あ、そういえばこの間……錬丹術研究会のサヤさんが、「不老不死の霊薬」がどうこうと仰っていたような……？"
10004010-51 = "「不老不死」とまではいかなくても、もしかしたらアンチエイジングに効く薬をご存じかもしれません。"
10004010-52 = "午後のおやつまで時間もありますし……ちょっと錬丹術研究会のところに行ってみましょうか。"
10004010-54 = "錬丹術研究会・サヤの研究室"
10004010-55 = "ふーっふっふっふっふ……さあて、今日はどこでどんな実験をしようか、今から楽しみなのだ！"
10004010-57 = "えっと、失礼します。"
10004010-58 = "ん、梅花園のシュンじゃないか？ぼく様の研究室へようこそなのだ！"
10004010-59 = "あっ、サヤさん。今日は可愛らしいお洋服を着られてるんですね。"
10004010-60 = "この後どこかへお出かけですか？"
10004010-61 = "うむ。今日の午後に、[USERNAME]先生と市内で会う約束をしてるのだ。"
10004010-62 = "何やらシャーレに置いておく常備薬について、相談したいと言われてな。"
10004010-63 = "えっ、先生と……！？"
10004010-64 = "そうだけど、何か問題でもあるのだ？"
10004010-65 = "いえ、そういうわけでは無いのですが……。"
10004010-66 = "（この間ご予定を聞いた時は、ちょっとしばらくは忙しいと仰ってましたが……そこにサヤさんとの予定は入っていたんですね……）"
10004010-67 = "（もちろん、シャーレの仕事の一環のようですが……なんだかモヤモヤした気持ちが……）"
10004010-68 = "ふーん？ところで今日は、どうしてぼく様の研究室に？梅花園のこと？"
10004010-69 = "それともまさか……玄龍門と玄武商会の仲裁を頼みに！？いくらぼく様が天才とはいえ、その件はお断りなのだ！"
10004010-70 = "い、いえ、まさか……。"
10004010-71 = "あの殺伐とした抗争に割り込もうなんて、そんなことはしませんよ。"
10004010-72 = "えっと、今日ここに来た理由はその……薬のことをお伺いしたくって。"
10004010-73 = "薬？体調でも悪いのか？"
10004010-74 = "いえ、身体は元気なのですが……。"
10004010-75 = "最近疲れが溜まっているのか、それともストレスなのか、お肌が荒れてしまって……。"
10004010-76 = "何か、美容に良い薬のことなどを教えていただけたらなと。"
10004010-77 = "ふーっっふっふっふ！なるほど、そういうことか……こんなこともあろうかと、ちょうど新しい秘薬を作っていたところなのだ！"
10004010-78 = "その名も……"
10004010-80 = "ずばり、「若返りの秘薬」！"
10004010-82 = "若返りの……？"
10004010-87 = "そう！この薬は誰でも一口飲むだけで、まるで生まれたての赤ちゃんのような柔らかいお肌が手に入る、ぼく様が新しく生み出したばかりの秘薬なのだ！"
10004010-88 = "まだテスト段階だから、ちょっとした副作用はあるかもだけど……効能についてはバッチリなのだ！多分。"
10004010-89 = "どう、飲んでみる？"
10004010-90 = "は、はい！ぜひ！"
10004010-91 = "よし。"
10004010-94 = "じゃあこれを飲んでもらって、どんな感じがするかぼく様に教えてほしいのだ。"
10004010-100 = "（本当にこの薬を飲めば、小さい子のように……）"
10004010-101 = "（思えば子どもの頃は、お肌のことで悩んだり、疲れを感じることもありませんでしたね……）"
10004010-102 = "（……やっぱり、子どものままの方が良かったのかもしれません。時間が経つにつれて、嫌なことがたくさん増えて……）"
10004010-103 = "（どうせなら、もう一度小さい子どもに……）"
10004010-114 = "……どうだ？何か変化とか感じるか？"
10004010-115 = "よく分かりませんが、何だか身体が熱くて、ズキズキと痛むような……。"
10004010-116 = "ん、それは変だな？材料の中に、身体を温めるような成分は無かったはず――"
10004010-117 = "って、うわっ！？"
10004010-118 = "ど、どうしたんですかサヤさん？"
10004010-119 = "いや、どうしたも何も……。"
10004010-120 = "あれ、サヤさんいつの間にそんなに大きく……？何だか、視線の高さが……？"
10004010-121 = "ぼく様が大きくなったんじゃなくて、シュンの方が縮んでるのだ！鏡を見ろ！"
10004010-122 = "鏡……？"
10004010-132 = "えぇぇっ！？ど、どうして私の身体、縮んでるんですか……！？"
10004010-133 = "ぼ、ぼく様にも分からない！完全に予想外なのだ！"
10004010-134 = "肌が柔らかくなるから、身体がゴムみたいに伸びるとかそういう副作用は予想してたけど、まさか身体が小さくなるとは……。"
10004010-135 = "サヤさん、少なくともそこまでは予想した上で、そんな薬を私に……。"
10004010-136 = "し、心配無いのだ！ぼく様は天才だから、解毒剤もすぐに作れる！"
10004010-137 = "ちょっと待ってて！研究会の倉庫に行って、すぐに材料を取ってくるのだ！"
10004010-142 = "ふぅ、まさかの事態ですね……ここしばらく「小さい頃に戻りたい」と思ってはいましたが、まさか本当にそうなってしまうなんて……。"
10004010-143 = "ですが、確かにお肌はツルツルになりましたね。それに、小さい子特有の柔らかい匂いが……。"
10004010-150 = "あっ、激しく動いても肩も痛みませんし、何だか身体が軽いです！"
10004010-151 = "この身体、意外と悪くないかも……？"
10004010-154 = "[ns] \"こんにちは。\""
10004010-155 = "せ、先生！？ど、どうしてここに……！？"
10004010-156 = "そ、その、この姿はですね……！"
10004010-157 = "[s] \"えっと……梅花園の子、かな？初めまして。\""
10004010-158 = "え？"
10004010-159 = "あ、はい、初めまして……？"
10004010-162 = "（もしかして先生、私が誰だか気づいてないのでしょうか……？）"
10004010-163 = "（確かにそれはそうですよね、ココナよりも幼い感じになってますし……）"
10004010-164 = "（説明しようとしてもややこしくなりそうですし、すぐに元に戻るみたいですし……とりあえず今は……）"
10004010-167 = "え、えと、私、最近梅花園に来た9歳のしゅ……しゅ、シュエリンです！"
10004010-168 = "シュンお姉ちゃんと一緒に山海経をお散歩してたら、迷子になっちゃって……。"
10004010-169 = "[s1] \"そうなんだ。よろしくね。\"\n[s2] \"ところで、サヤって子を見なかった？約束してたんだけど……。\""
10004010-170 = "あ、サヤお姉ちゃんは……えっと、確か、どこかにお出かけしちゃったと聞きましたよ？"
10004010-171 = "あ、サヤお姉ちゃんは……えっと、確か、どこかにお出かけしちゃったと聞きましたよ？"
10004010-172 = "[s3] \"そっか。じゃあ戻ってくるまでの間に、一緒にシュンを探そうか？\"\n[s4] \"サヤが帰ってくるまで、時間かかりそうだし。\""
10004010-173 = "え、えと、そこまでしていただかなくても……。"
10004010-174 = "え、えと、そこまでしていただかなくても……。"
10004010-177 = "（な、何だかサヤさんと先生との予定に割り込んでしまった感じが……）"
10004010-178 = "（それにとっさにとはいえ、先生に嘘をついてしまいました……）"
10004010-179 = "（で、でも、この状況はよく考えるとサヤさんが原因ですし……？）"
10004010-180 = "（そもそもこんなことが起きなかったら、先生に嘘をつくこともなかったわけで……これは、正当防衛なのではないでしょうか！？）"
10004010-183 = "じゃ、じゃあその……お願いします、先生！"
10004010-184 = "[s] \"うん、任せて。はぐれたのはどの辺り？\""
10004010-185 = "それは……あ、たぶん、玄武商会のあたりかな？"
10004010-186 = "美味しい「タンフールー」のお店で新作が出るって聞いて、行ってみたい……じゃなくて、シュンお姉ちゃんも好きなので、そこに行ったのかもしれません。"
10004010-187 = "も、もちろんシュンお姉ちゃんはその、子どもたちを放り出して美味しいものを食べに行くような、無責任な教官ではないのですが……！"
10004010-188 = "[s] \"えっと、どうしてシュエリンが代わりに言い訳を……？\""
10004010-189 = "それはその、シュンお姉ちゃんならそう言うかなと思いまして……あはは……。"
10004010-190 = "さ、さあ、細かいことは良いですから、行きましょう先生！"
