[translation]
1000602-1 = "彼女の誤解"
1000602-2 = "キヴォトス・商店街"
1000602-4 = "自販機の前で100円を落とした。"
1000602-5 = "……そのまま小銭が転がって、隙間から下水の中へと消えてしまった。"
1000602-6 = "[s] 蓋を開けて下に降りて、小銭を探す。"
1000602-8 = "（ガチャン）"
1000602-11 = "……おい、そこで何をしてるんだ？"
1000602-16 = "……先生？"
1000602-17 = "[s] \"………。\""
1000602-18 = "………。"
1000602-19 = "[s] \"………。\""
1000602-20 = "噂のヘンタイを捕まえたって風紀委員会に連絡しないとな……。"
1000602-21 = "[s] \"誤解だよ。\""
1000602-22 = "誤解？何を言ってるんだ。"
1000602-23 = "わざわざ下水口の蓋を開けて中に入るような理由があるのか？"
1000602-24 = "あるとしたら、目につきにくい下水路に潜って、女子生徒たちのスカートの中を覗こうとしていたに違いない。"
1000602-25 = "[s] 事情を説明する。"
1000602-26 = "小銭を拾おうとして下水に入った？"
1000602-27 = "……シャーレの先生は、小銭一枚のために下水に入るくらい苦しい生活をしてるのか……。"
1000602-28 = "先生、何か飲みたい物があれば私が奢ってあげる。"
1000602-29 = "生徒に迷惑はかけられないって？#nいや、100円ぐらいならいいから。"
1000602-30 = "これからは小銭を落としたからといって下水に入るなよ。"
1000602-31 = "お金が足りなくてそうしてるわけじゃない？#nじゃあ何で……。"
1000602-32 = "[s1] \"ここ、意外と涼しくて気持ちがいいんだよね。\"\n[s2] \"この位置からだとイオリの脚がよく見える。\""
1000602-33 = "な、何言ってるんだ！？"
1000602-34 = "な、何言ってるんだ！？"
1000602-35 = "ヘンタイ、死ね！！"
1000602-37 = "その後、小銭は見つけたがイオリに誤解されてしまった。"
