[translation]
10001005-1 = "プロローグ;偉大なる生徒会長"
10001005-2 = "レッドウィンター連邦学園・正門"
10001005-6 = "……ようこそお越しくださいました、先生。レッドウィンター連邦学園を代表し、先生のご来訪を心より歓迎いたします。"
10001005-7 = "さあ、チェリノ会長が中でお待ちです。"
10001005-8 = "こちらへどうぞ……。"
10001005-11 = "レッドウィンター連邦学園・会長執務室"
10001005-15 = "[ns] あれは……。"
10001005-19 = "あの肖像画が気になりますか？"
10001005-20 = "あの御方こそ、我がレッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、運動部代表兼、清掃部部長兼、風紀委員長兼、給食部部長のチェリノ会長で御座います。"
10001005-21 = "[s1] \"忙しそうだね。\"\n[s2] \"髭がナイス。\""
10001005-22 = "書記長、先生をお連れいたしました。"
10001005-26 = "はい、あのヒゲこそ、レッドウィンターの権威の象徴なのです。"
10001005-27 = "お気に召されたのでしたら幸いです。"
10001005-28 = "書記長、先生をお連れいたしました。"
10001005-35 = "……ご苦労だった、トモエ秘書室長。忠実な我が右腕よ。褒美として後日、勲章を授けよう。"
10001005-36 = "光栄です、書記長。"
10001005-38 = "そして……我がレッドウィンター連邦学園へようこそ、カムラッド。"
10001005-40 = "私こそがチェリノである！"
10001005-41 = "このレッドウィンター連邦学園の生徒会長であり、環境美化部部長兼、書記長兼、清掃部部長……"
10001005-42 = "ええと……"
10001005-43 = "あとは……あと何だっけ……。"
10001005-44 = "（ひそひそ）運動部代表兼、風紀委員長兼、給食部部長……！"
10001005-45 = "……それだ！とにかく、凄いことは何でも任されている偉い人なのだ！こうして出会えたことを光栄に思うがいい、カムラッド！"
10001005-46 = "[s] \"肖像画とはちょっと違う……？\""
10001005-47 = "はっ！そのような些細なことは気にするな！あれは、私の将来の姿を描いたものだから問題ない！"
10001005-48 = "それともカムラッド、私の肖像画に何か不満でも？"
10001005-49 = "大人ならそのぐらいは空気を読ん……"
10001005-50 = "うひゃっ！？"
10001005-54 = "しょっ、書記長！？"
10001005-55 = "いたた……。"
10001005-56 = "トモエ！！ここは転びやすいから、カーペットをちゃんと整えておくようにと言っただろう！粛清するぞ！？"
10001005-57 = "チェ、チェリノちゃん！ヒゲ！おヒゲが！"
10001005-58 = "……ん？"
10001005-59 = "えっ、う、うひゃあ！おいらのヒゲがっ！"
10001005-68 = "……ふう。今日も良い天気だな、トモエ、そう思わないか？"
10001005-69 = "仰る通りかと、書記長。"
10001005-70 = "[s] \"ところで今日は急に、何の用事で？\""
10001005-71 = "ふふふ、聞いて驚け……それは、"
10001005-72 = "「イワン・クパーラ」の準備のためだ！"
10001005-73 = "[s] \"イワン・クパーラ？\""
10001005-74 = "カムラッドも知ってると思うが、そろそろ「夏至」の季節。つまり、一年でもっともお昼の時間が長い日が近づいている……。"
10001005-75 = "雪も少し解け始め、新緑が芽吹くこの時期に、レッドウィンター連邦学園では毎年、夏至祭「イワン・クパーラ」を開いているのだ！"
10001005-76 = "「イワン・クパーラ」はレッドウィンター連邦学園における古き良き伝統！そのため事務局としても、これを盛大に開催できるよう、生徒たちを総動員し、最高の「イワン・クパーラ」とするための準備をしているのである！"
10001005-77 = "そうだな？トモエ秘書室長。"
10001005-78 = "はい。会長の指示に従って2交代制を実施し、模範労働者には褒賞を与えた結果、先週は対前週比250%の生産量を達成できました。"
10001005-79 = "えっと……それはつまり、上手く行っているという意味で良いのか？"
10001005-80 = "……そうか！よし、よし！それなら今回の「イワン・クパーラ」も完璧だな！"
10001005-81 = "[s3] \"夏至ってまだ1か月後だよね？\"\n[s4] \"私に何か手伝えることとかある？\""
10001005-82 = "おいらをバカにしてるのか！それぐらい分かっている！"
10001005-83 = "はは！この私の完璧な指導の元で進められているのだ、我がレッドウィンター連邦学園に不足や不備など何もない！"
10001005-84 = "このタイミングでカムラッドを呼んだ理由は……お前がシャーレの先生だからだ。"
10001005-85 = "シャーレの先生として、他の学校の生徒たちと頻繁に交流をしているのだろう？"
10001005-86 = "その繋がりを生かし、我がレッドウィンター連邦学園の雄姿を広めるために、シャーレの先生を買収……"
10001005-87 = "いや、売り渡……？"
10001005-88 = "（ひそひそ）チェリノちゃん、引き入れ、です。引き入れ！"
10001005-89 = "そ、そう！シャーレの先生を引き入れるのが、我がレッドウィンターの名声を高めるのに最善の手段だと考えたのだ！"
10001005-94 = "さあ、カムラッド！夏至祭に向けて準備しているレッドウィンター連邦学園の、この素晴らしい姿をきちんとその目に焼き付け、各学校の生徒たちを通じてキヴォトス全域へと広めるのだ！"
10001005-97 = "#video;10001"
