[translation]
10006010-1 = "~Edição de Ensaio~; Show Especial da Hatsune Miku em Kivotos"
10006010-5 = "Olá a todos! Eu sou a cantora virtual, Hatsune Miku!"
10006010-6 = "Imagino que para muitos de vocês, esta seja a primeira vez que nos encontramos assim."
10006010-7 = "Estou muito feliz por poder encontrar todos vocês aqui em Kivotos!"
10006010-8 = "Desta vez, para realizar este show em Kivotos..."
10006010-9 = "Inacreditavelmente, prepararam este corpo real para mim!"
10006010-10 = "Hehe, o que acharam? Não é maravilhoso?"
10006010-11 = "Porém, como acabei de assumir este corpo, ainda não estou conseguindo pegar o ritmo direito..."
10006010-12 = "Segundo os engenheiros que criaram este corpo, para fazer os ajustes finos, são necessários dados de movimentos mais próximos da apresentação real."
10006010-13 = "Por isso, farei este \"ensaio especial\" na frente de vocês!"
10006010-14 = "Então, pessoal, conto com o apoio de vocês!"
10006010-15 = "Ah, mas depois deste ensaio, não deixem de vir ao show principal, está bem?"
