[translation]
1001702-1 = "勲章授与式"
1001702-2 = "レッドウィンター連邦学園・会長の執務室"
1001702-3 = "うーん……なかなか良い名前が浮かばないな。"
1001702-4 = "もっと誉れ高く、高貴で、それでいておいらにふさわしい名前が……。"
1001702-6 = "おお、来たかカムラッド！待っていたぞ！"
1001702-7 = "実は、カムラッドの知恵を借りたい重要な案件があって呼んだのだ。"
1001702-8 = "カムラッドも知っていると思うが、ここ数か月間おいらはレッドウィンター連邦学園の発展のために、昼夜を問わず頑張ってきた。"
1001702-9 = "給食施設の品質管理のために、一日中プリンの味見をしたり、学校を視察……する前に、体力を温存するべく昼寝をしたり、また……えっと、他には……。"
1001702-10 = "とにかく！あれこれすごいことをたくさんして、おいらはとても疲れたのだ。それに応じた報酬を受け取るのは当然のこと！"
1001702-11 = "そこでおいらは自分自身にどんなご褒美を与えるか、悩んで悩んで……最終的に、レッドウィンター連邦学園で最高に名誉ある勲章を授与することに決めたのだ。"
1001702-12 = "勲章は、プリンとは違って食べると無くなるものでもないし、授与されると同時に記録され……"
1001702-13 = "永遠にレッドウィンター連邦学園の歴史に残る――長い間頑張って苦労したおいらへのご褒美としては、もってこいだ！"
1001702-14 = "ただこれには一つ問題がある、それは……。"
1001702-15 = "おいらはすでに、レッドウィンター連邦学園にある全ての勲章を授与されてるから、もうこれ以上もらえる勲章が無いということ！"
1001702-16 = "まあおいらが生徒会長なんだから、勲章なんか新しく作ればいいのだが。"
1001702-17 = "ただ問題は、新しい勲章に付けられる良い名前が思い浮かばないことでな……。"
1001702-18 = "そこでだカムラッド。誉れ高く、高貴で、優雅でありながら、おいらの業績が後世まで伝わりそうな良い名前はないか？"
1001702-19 = "勲章の前に付けるとカッコいい、何かそれっぽい言葉を考えてくれ！"
1001702-20 = "[s1] \"ハイパー。\"\n[s2] \"ウルトラ。\"\n[s3] \"メガ。\""
1001702-22 = "おおぉっ、カッコいいぞ！！そういう言葉を繋げれば、さぞかし良い名前の勲章が誕生するに違いない！"
1001702-24 = "おおぉっ、カッコいいぞ！！そういう言葉を繋げれば、さぞかし良い名前の勲章が誕生するに違いない！"
1001702-26 = "おおぉっ、カッコいいぞ！！そういう言葉を繋げれば、さぞかし良い名前の勲章が誕生するに違いない！"
1001702-27 = "他にも、何か他にもないか！？"
1001702-28 = "ん？言葉の前に「超」という言葉を付けると、必殺技っぽくて強そうな印象になる？"
1001702-29 = "よし、それも採用だ！"
1001702-30 = "うむ、うむ。なるほど、それも……"
1001702-33 = "よし、決めた！"
1001702-34 = "レッドウィンターにおいて最高に栄誉ある、新しい勲章の名は「超ハイパーウルトラメガスーパー勇猛努力栄誉章」だ！"
1001702-35 = "これなら、勲章の名前を聞いただけで、ありとあらゆる生徒たちが感心せざるを得ないな？ふふふ……。"
1001702-36 = "ん？名前を決めるに当たって一緒に考えてくれたカムラッドに、何かご褒美はないのかって？"
1001702-37 = "確かに……でも「超ハイパーウルトラメガスーパー勇猛努力栄誉章」は、レッドウィンター連邦学園で一番栄誉のある勲章にしちゃったから、むやみに授与はできないし……。"
1001702-38 = "仕方ない。"
1001702-39 = "カムラッドには、最高の栄誉に比べたら劣るものの、それに次ぐ「ハイパーウルトラメガスーパー勇猛努力栄誉章」を授与する。"
1001702-40 = "光栄に思え、カムラッド！"
1001702-42 = "その後、チェリノと一緒に勲章のデザインを考えながら、楽しい時間を過ごした。"
