[translation]
10014075-2 = "Haa, haa..."
10014075-3 = "Já, já chega... não está bom por aqui?..."
10014075-9 = "Será que por aqui está seguro...?#nJá chegamos ao Distrito Escolar de Trinity..."
10014075-10 = "Digo, precisávamos mesmo fugir?#nEstávamos praticamente ganhando, não estávamos...?"
10014075-11 = "Não, enrolar mais do que isso seria realmente perigoso.#nJá estava na hora da polícia da Valkyrie aparecer..."
10014075-12 = "Se tivéssemos ficado lá, a essa altura, todas nós teríamos sido presas."
10014075-13 = "A-ah, é mesmo..."
10014075-17 = "...A propósito, o que é 'polícia'?"
10014075-21 = "...Ah."
10014075-22 = "[s1] \"Terminologia técnica...\"\n[s2] \"Provavelmente, ela está falando da Academia de Polícia Valkyrie.\""
10014075-23 = "Ah... então é sobre as alunas da academia de polícia...#nE, Sensei, como você sabe disso?"
10014075-24 = "Ah... então é sobre as alunas da academia de polícia...#nE, Sensei, como você sabe disso?"
10014075-29 = "E assim, elas que tentaram impedir o renascimento de Cath Palug...#nforam, pelo contrário, varridas do mapa."
10014075-30 = "Ah... o mundo não conseguiu impedir o renascimento da fera demoníaca e mergulhou novamente na era das trevas—"
10014075-37 = "Para com isso!!!"
10014075-39 = "Chega!!"
10014075-41 = "Eu disse"
10014075-43 = "para"
10014075-45 = "parar"
10014075-47 = "com isso!"
10014075-49 = "Que horror!!"
10014075-51 = "A, ahh~!! Aaaa~~~!! Isso, é..."
10014075-53 = "Ahaha..."
10014075-54 = "...Hehe."
10014075-55 = "[s3] \"Parece que você está se divertindo, Yoshimi.\"\n[s4] \"É o seu melhor sorriso ultimamente.\""
10014075-56 = "...Sim, com certeza."
10014075-57 = "...Sim, com certeza."
10014075-58 = "Estou me divertindo muito agora... deixe as coisas como estão."
10014075-60 = "...A propósito, o que vamos fazer com ela?"
10014075-61 = "Ela...?#nAh..."
10014075-67 = "Falando nisso... ela já estava desmaiada desde que quebrou a parede..."
10014075-68 = "Hmm. Nem lutar, nem ver nossos rostos ela conseguiu."
10014075-69 = "Mas, felizmente, ela não parece estar ferida..."
10014075-74 = "...Entendi. Então não precisa se preocupar.#nBem, é só deixar ela dormindo em um banco por aqui."
10014075-81 = "E-eh!?!?#nKa-Kazusa-chan!?"
10014075-82 = "Não, espera... não importa o que aconteça, deixar alguém desmaiado em um banco assim..."
10014075-84 = "...Não, espere, confie em mim.#nEla realmente vai ficar bem."
10014075-85 = "Eu sei do que estou falando... já vi isso acontecer várias vezes.#nE, na verdade, ela adora dormir em bancos."
10014075-86 = "Entendo... uma relação de confiança nascida de uma má convivência."
10014075-88 = "...Isso é romântico."
10014075-89 = "[s5] \"...Sim, com certeza.\"\n[s6] \"Desta vez, a Natsu pode estar certa.\""
10014075-90 = "Ai, calem a boca!!#nQue romântico o quê..."
10014075-91 = "Ai, calem a boca!!#nQue romântico o quê..."
10014075-95 = "...Hmm."
10014075-99 = "...O que você está fazendo?"
10014075-100 = "Kazusa-chan, isso é... um desafio?#nVocê vai devolver para a Reisa-chan?"
10014075-101 = "Bem... não serve de nada comigo, então vou devolver para a dona.#nSó isso."
10014075-103 = "Entendi. Então é uma tsundere."
10014075-104 = "Eu disse para parar com isso."
10014075-105 = "Haa, estou exausta... por que as coisas terminaram assim..."
10014075-110 = "Você tem um relógio biológico bem preciso, não tem?"
10014075-111 = "Todo mundo se esforçou a noite toda, afinal..."
10014075-112 = "Sim. Precisamos repor as energias com um pouco de açúcar."
10014075-113 = "[s7] \"Então, vamos comer alguma coisa.\"\n[s8] \"Hoje é por minha conta, Sensei.\""
10014075-120 = "……Ebaaa!!"
