[translation]
10019070-9 = "Ah, Azusa-chan... aquilo é..."
10019070-10 = "Sim. Sem dúvida, aquilo é..."
10019070-11 = "Perorodzilla...!!"
10019070-13 = "Hifumi. Quando você disse que o Perorodzilla vive no coração de todos, era disso que estava falando?"
10019070-14 = "N-não...!#nNão era essa a minha intenção..."
10019070-19 = "Nós também confirmamos. #nUm monstro gigante desembarcou no Distrito Shiratori de D.U."
10019070-26 = "Uau, o que é aquilo!?"
10019070-27 = "Incrível!! Ele está disparando raios pelos olhos!!"
10019070-28 = "Vou me aproximar dali. Todos, segurem-se firme★"
10019070-29 = "Fufu. Sim, vamos impedi-lo."
10019070-31 = "N-nós também vamos nos juntar a vocês!#nAzusa-chan, segure-se firme!"
10019070-32 = "Sim!"
