[translation]
10011005-1 = "Prólogo; Invasão Ninja!"
10011005-5 = "Schale - Sala de Descanso"
10011005-8 = "（O expediente no Schale terminou e eu estava descansando, quando...）"
10011005-13 = "[ns] \"Ué, a luz...?\""
10011005-25 = "Hehehe! Infiltração concluída com sucesso!"
10011005-27 = "Uau... sério que conseguimos nos infiltrar... naquele lendário Schale...!"
10011005-29 = "Regra de ouro dos ninjas, número um! 'Um ninja deve sempre aceitar desafios sem hesitar'! É por isso!"
10011005-30 = "Com isso, o Schale estará em minhas mãos...!"
10011005-32 = "As coisas estão ficando impressionantes...!"
10011005-34 = "Se você é um ninja, não deve pensar nas consequências, apenas agir... é importante..."
10011005-36 = "Vou anotar essa filosofia da chefe para não esquecer...!"
10011005-38 = "...Isso é um elogio, né? Não está interpretando errado?"
10011005-40 = "Bem, de qualquer forma, vamos logo! Com o passo ninja, tipo chutatata!"
10011005-42 = "Sim, chutatata...!"
10011005-46 = "[ns] \"Bem...\""
10011005-51 = ".........Hã?"
10011005-53 = "Ah, é...?"
10011005-54 = "[s] \"Quem são vocês...?\""
10011005-58 = "A-a-não entre em pânico, Tsukuyo! É nessas horas que devemos lembrar!"
10011005-59 = "Regra de ouro dos ninjas! Número dois!"
10011005-60 = "Ah, sim!"
10011005-61 = "'Um ninja nunca desiste, não importa a situação de perigo'...!"
10011005-62 = "Isso! Sendo assim, vamos usar a 'Técnica de Emboscada' as duas ao mesmo tempo!"
10011005-64 = "Hã, será que isso é uma boa ideia...?"
10011005-65 = "Tudo bem, tudo bem, VAI!"
10011005-66 = "[s] \"Não, espere, espere--\""
10011005-73 = "Ah, chefe. A luz..."
10011005-74 = "Por queee!?"
10011005-78 = "Izuna, apresentando-se!"
10011005-79 = "Ah, Izuna-chan...!"
10011005-80 = "Ouvi a voz do mestre, então vim correndo!"
10011005-81 = "Aquela voz, será que o mestre estava em perigo...!?"
10011005-82 = "Sendo assim, não posso ficar parada!"
10011005-83 = "Izuna, entrando em ação!"
10011005-84 = "Espere, Izuna! Isso não estava no plano--"
10011005-85 = "Ninnin!"
10011005-86 = "[s] \"Uwaaaah!?\""
10011005-92 = "（Depois disso, consegui convencê-las e acalmar as três que atacaram de repente）"
10011005-96 = "Schale - Escritório"
10011005-97 = "Poxa, Izuna! Isso não era o que tínhamos planejado!"
10011005-98 = "Uuu... mas chefe!"
10011005-99 = "No momento em que ouvi a voz do mestre, não consegui ficar parada..."
10011005-100 = "Como uma ninja, eu não podia simplesmente ficar sem fazer nada!"
10011005-101 = "Não, não, não, isso é bom, mas!"
10011005-102 = "Mas, sabe... a Izuna-chan que veio correndo tão rápido..."
10011005-103 = "Acho que foi muito legal da sua parte."
10011005-104 = "Ehehe! Obrigada, Tsukuyo-dono!"
10011005-105 = "Ehehe..."
10011005-106 = "[s] \"Bem, são conhecidas da Izuna...? Por que estão aqui...?\""
10011005-107 = "Hm?"
10011005-108 = "Ah, bem, é que... nós..."
10011005-112 = "Ah, Mestre...!? Não pode ser...!"
10011005-113 = "[s] \"...Não pode ser?\""
10011005-114 = "Você esqueceu os dias que passou junto com a Izuna!?"
10011005-115 = "Será que, por acaso, esse é aquele clichê onde você perdeu todas as suas memórias por causa do impacto de agora pouco!?"
10011005-116 = "[s] \"Não, não é isso, eu obviamente sei quem é a Izuna, mas--\""
10011005-117 = "Falando nisso, Izuna, eu já vi isso em um drama ninja! Um ninja que arriscou a própria vida para proteger seu mestre é atacado de surpresa...!"
10011005-118 = "E acaba sofrendo de amnésia, aquela cena de chorar! Será que isso aconteceu com você, Mestre...!?"
10011005-119 = "[s] \"Izuna, espere--\""
10011005-120 = "Aquele momento em que Izuna e Mestre se conheceram...! Aquela vez em que você disse que apoiaria os sonhos da Izuna...! Você esqueceu de tudo isso!?"
10011005-121 = "Nós passamos por tantas situações de vida ou morte, aquele grande vilão do mundo..."
10011005-122 = "Aquele grande rei demônio que tentava dominar o mundo, o \"Nyan-tenmaru\", nós derrotamos ele juntas, não foi! Até essas memórias foram perdidas...!?"
10011005-123 = "[s] \"B-bem, eu não tenho memórias de um evento tão grandioso assim...\""
10011005-124 = "Izuna está triste... mas, por favor, não se preocupe!"
10011005-125 = "Mesmo que o Mestre tenha esquecido de tudo... basta criarmos novas memórias!"
10011005-126 = "Não importa o que aconteça, Izuna é sua ninja leal! E você, Mestre, será sempre o meu Mestre! Nin-nin!"
10011005-127 = "[s1] \"Fico feliz em ouvir isso, mas não é bem assim...\"\n[s2] \"É a primeira vez que vejo as outras, prazer em conhecê-las.\""
10011005-136 = "Entendo, então você quer saber quem nós somos..."
10011005-137 = "Então, vamos nos apresentar novamente..."
10011005-138 = "Domo, prazer em conhecê-lo, Mestre... Eu me chamo Michiru."
10011005-139 = "Prazer... em conhecê-lo...! Meu nome é Tsukuyo..."
10011005-140 = "E a Izuna é a Izuna! Mestre!"
10011005-141 = "[s] \"Olá... mas, Mestre \"Mestre\"?\""
10011005-142 = "Fu-fu-fu... não há nada a esconder, nós três somos, isso mesmo!"
10011005-143 = "Vamos, Izuna, Tsukuyo!"
10011005-144 = "Sim, Chefe!"
10011005-145 = "Sim...!"
10011005-146 = "Agora, a pose de vitória hiper estilo ninja!"
10011005-147 = "[s] \"Estilo ninja, hiper...?\""
10011005-153 = "O que é um ninja! E o que é o ninjutsu!"
10011005-156 = "A essência... do ninja!"
10011005-160 = "Pesquisar, explorar e investigar sua verdadeira natureza..."
10011005-161 = "Um trio de ninjas fofas que agem nas sombras para espalhar o charme dos ninjas!"
10011005-162 = "É isso!"
10011005-166 = "Fazendo até as crianças que choram rirem,"
10011005-167 = "O grupo ninja mais forte da Academia Hyakkiyako!"
10011005-168 = "[s] \"...?\""
10011005-172 = "O nome é, \"Clube de Pesquisa de Ninjutsu\"!"
10011005-173 = "É isso!"
10011005-174 = "É isso..."
10011005-178 = "E eu sou a chefe do Clube de Pesquisa de Ninjutsu! Chidori Michiru!"
10011005-179 = "[s] \"Entendo... E por que o Clube de Pesquisa de Ninjutsu está aqui?\""
10011005-180 = "Fu-fu-fu... Fu-fu-fu-fu!"
10011005-181 = "O Mestre está pensando nisso agora, não está?"
10011005-182 = "\"Que ninjas garotas tão legais e adoráveis!\"... é isso."
10011005-183 = "[s] \"B-bem, sim...\""
10011005-184 = "E você também deve ter pensado:"
10011005-185 = "\"Quero apoiar essas garotas! Quero usar o poder de um adulto para ajudá-las a abrir suas asas em crescimento e voar para o vasto mundo!\"... é isso."
10011005-186 = "Não precisa dizer mais nada, eu entendo. Sabendo que seria assim, eu preparei isto!"
10011005-191 = "[ns] \"\"Carta de recomendação para a aprovação do clube\"...?\""
10011005-192 = "Vamos, assine aqui!"
10011005-193 = "[s3] \"Veio até aqui só para conseguir isso?\"\n[s4] \"Isso significa que o Clube de Pesquisa de Ninjutsu ainda não é um clube oficial?\""
10011005-196 = "Presidente, era isso? Izuna, acabei de descobrir agora!"
10011005-197 = "Eu também, achei que... fosse para cumprimentar o Sensei..."
10011005-198 = "I-Isso também, mas!"
10011005-199 = "...Ahem. Já ouvi rumores sobre o Sensei. Dizem que você tem um poder incrível!"
10011005-200 = "Com esse poder, a aprovação do clube pode se tornar realidade... não pode!? Por favor!"
10011005-201 = "[s] \"Isso é um pouco difícil...\""
10011005-202 = "O quê...!?"
10011005-203 = "Ah..."
10011005-204 = "???"
10011005-205 = "P-Por que...!? Não me diga que o Sensei também..."
10011005-206 = "\"Um clube para pesquisar ninjas, não posso aprovar uma atividade tão estranha assim\"... é isso!?"
10011005-207 = "[s] \"Não é isso, só estou dizendo que é necessário seguir os procedimentos normais, não é?\""
10011005-208 = "I-Isso é verdade, mas... mas..."
10011005-209 = "M-Mas! A Kaho nunca vai aprovar esse tipo de atividade!"
10011005-210 = "Quer dizer, bem... isso! Leva muito tempo para ser aprovado e é muito rigoroso..."
10011005-211 = "...?"
10011005-212 = "A-A Kaho-san é uma pessoa tão rigorosa assim...?"
10011005-213 = "B-Bem, às vezes não é... m-mas de qualquer forma, por favor, Sensei!"
10011005-214 = "[s] \"Hmm, eu adoraria ajudar, mas...\""
10011005-219 = "[ns] \"Mais um visitante...?\""
10011005-227 = "...Muito prazer, Sensei. Eu sou a vice-presidente do Departamento Yin-Yang, Kuwakami Kaho."
10011005-228 = "O Departamento Yin-Yang tem um pedido para o Schale, por isso vim até aqui."
10011005-229 = "Poderia me conceder um pouco do seu tempo?"
10011005-230 = "Nya! Falando no diabo...!?"
10011005-231 = "...Ora."
10011005-232 = "[s] \"Departamento Yin-Yang, isso significa que você é de Hyakkiyako...?\""
10011005-236 = "#video;10011"
