[translation]
10014050-1 = "Episódio 5; Um passado que quero esquecer"
10014050-2 = "（………）"
10014050-3 = "……Ah, Sensei!#nVocê já chegou!"
10014050-4 = "[s1] \"Fui eu quem te chamei, afinal.\"\n[s2] \"Por favor, sente-se aqui.\""
10014050-5 = "Olá!! Uzawa Reisa, apresentando-me formalmente mais uma vez!!"
10014050-6 = "Olá!! Uzawa Reisa, apresentando-me formalmente mais uma vez!!"
10014050-7 = "Quem diria que você me chamaria logo depois de eu te dar meu contato!"
10014050-8 = "A propósito…… qual seria o assunto……?"
10014050-9 = "……Eh?"
10014050-10 = "Ah…… sobre o dia de hoje?"
10014050-11 = "I-isso, não precisa se preocupar! Sim!#nEu ouvi com meus próprios ouvidos!!"
10014050-12 = "Kyoyama Kazusa se arrependeu de seus erros e#nestá vivendo uma vida comum com seus amigos!"
10014050-13 = "Mesmo eu não seria tão indelicada a ponto de atrapalhar essa nova vida!#nPor isso, não precisa mais se preocupar!"
10014050-14 = "Não causarei mais nenhum problema para a Kyoyama Kazusa!"
10014050-15 = "[s3] \"Não é sobre isso, levante a cabeça.\"\n[s4] \"……Reisa, você está bem com isso?\""
10014050-16 = "……Eh? O que você quer dizer com……#nDesculpe, não entendi bem……."
10014050-17 = "……Eh? O que você quer dizer com……#nDesculpe, não entendi bem……."
10014050-18 = "Afinal, Kyoyama Kazusa não é mais uma delinquente.#nNão há mais necessidade de derrotá-la ou desafiá-la……."
10014050-19 = "……O-o que mais poderia haver além disso?"
10014050-20 = "……Eh?"
10014050-21 = "Sobre ter entrado em contato com outros grupos de vigilantes ou com o Comitê de Justiça sobre a Kyoyama Kazusa……?"
10014050-22 = "Não, especificamente……"
10014050-23 = "……Ué?"
10014050-24 = "B-bem, é verdade, né? Hmm…… de fato, nunca denunciei nem entrei em contato com ninguém.#nPor que será?"
10014050-25 = "Também nunca falei sobre isso com a Suzumi-san…… que estranho."
10014050-26 = "Minha arqui-inimiga que eu deveria derrotar!!"
10014050-27 = "……Não seria porque eu achava que ela era isso?#nAhaha……."
10014050-31 = "……Bem, para começar, nem tenho com quem entrar em contato.#nAhaha……."
10014050-32 = "Deixando isso de lado.#n……Sensei, por que você está me perguntando essas coisas?"
10014050-33 = "Será que……"
10014050-34 = "Achei ela!! A baixinha do grupo de vigilantes!!"
10014050-35 = "……Eh?"
10014050-36 = "[ns] \"……！？\""
10014050-42 = "Ah, é ela mesma, sem dúvida!!"
10014050-43 = "Ei! Chamem todos os reforços! Não a deixem escapar!#nEssa é a chance perfeita!"
10014050-44 = "[s5] \"Não a deixem escapar……?\"\n[s6] \"Chance perfeita?\""
10014050-45 = "Hã? O que foi?#nTem um adulto junto também……."
10014050-46 = "Hã? O que foi?#nTem um adulto junto também……."
10014050-47 = "Tanto faz. Ei, se não quiser se machucar, saia da frente agora.#nNós só temos assuntos com ela!"
10014050-48 = "……Comigo?"
10014050-49 = "Não se faça de boba. A gente sabe de tudo."
10014050-50 = "Você…… sabe a identidade real de \"Cath Palug\", não sabe?"
10014050-51 = "……？？Cath Palug?#nB-bem, eu sei quem é…… mas o que tem isso?"
10014050-52 = "Como assim \"o que tem\"! Ouvimos dizer que ela fundou uma nova organização!"
10014050-53 = "Acho que o nome era \"Clube de Doces Depois da Escola\".#nEi? Acertei, não foi?"
10014050-54 = "[s7] \"……Ah, não pode ser.\"\n[s8] \"A situação parece estar se complicando.\""
10014050-55 = "E-espere um pouco!#nIsso é um mal-entendido!! Não existe tal organização!!"
10014050-56 = "E-espere um pouco!#nIsso é um mal-entendido!! Não existe tal organização!!"
10014050-57 = "Kyoyama…… não, Cath Palug não é…… a pessoa que vocês pensam!"
10014050-58 = "Na verdade, ela nem está mais aqui!"
10014050-59 = "Do que você está falando? Acha que vamos acreditar numa história dessas? Não nos faça de idiotas!"
10014050-60 = "Ah, ahaha... É, né? Eu mesma não acreditei no começo..."
10014050-61 = "Não, não é isso! Mas é a verdade! O Cath Palug não existe mais!"
10014050-62 = "Eu não esperava que você fosse abrir o bico tão fácil assim, mas fazer o quê..."
10014050-63 = "Ei!! Vamos nessa!!"
10014050-68 = "Guarde os detalhes para conversar com a ponta do meu cano!!"
10014050-73 = "Po-por que isso está acontecendo..."
10014050-74 = "Se-Sensei...!?"
10014050-75 = "[s9] \"Isso... não pode ser evitado.\"\n[s10] \"Por enquanto, deixe-me assumir o comando, Reisa.\""
10014050-76 = "Ah..."
10014050-77 = "Ah..."
10014050-78 = "...Sim!!"
