[translation]
10016040-1 = "第4話;遅めのランチ"
10016040-2 = "（ユウカと別れた後、昼食を摂るべく競技場の外へ再び足を運んだ）"
10016040-6 = "（なぜか休憩広場の真ん中に人がたくさん集まっている……）"
10016040-7 = "選手の皆さん！午前の試合、お疲れ様でした。"
10016040-8 = "こちらでは飲み物をお配りしております。#n喉が渇いた方はどうぞご利用ください！"
10016040-9 = "ありがたくいただきます、シスター！"
10016040-10 = "わ、私……選手ではありませんが、飲み物をいただいても大丈夫でしょうか？"
10016040-11 = "もちろんです。#nはい、どうぞ。"
10016040-12 = "シスター、こちらのボックスでもう終わりです。あと数本しか……"
10016040-13 = "あ、あれ？もう無くなってしまいましたか？"
10016040-14 = "少々お待ちください……今すぐ実行委員会本部に連絡して補充を――"
10016040-15 = "うわーん、お姉ちゃーん……どこー"
10016040-16 = "あら、迷子……？"
10016040-17 = "大丈夫ですよ。#n私がすぐお姉さんを探してきますから、少しここで待っててくださいね。"
10016040-18 = "シスター、ここから一番近い自販機ってどこですか？"
10016040-19 = "ここから一番近い自販機は東館1階にありますが、今は修理中なので……#n少し曲がっていただいて、西館側にある自販機をご利用ください。"
10016040-20 = "よろしければ後でご案内しますよ――"
10016040-21 = "シスター、午後のリレーで良い記録を出す方法ってありますか？"
10016040-22 = "い、良い記録を出す方法……ですか？"
10016040-23 = "運動には詳しくないので、良いアドバイスができるか分かりませんが……#n十分な休憩を取ってコンディションを整えるのはいかがでしょう？"
10016040-24 = "はい、スポーツドリンクをどうぞ。#nそしてすみません、今は迷子を――"
10016040-25 = "シスター……正義とは何でしょうか？"
10016040-26 = "……少し難しい質問ですね。"
10016040-27 = "[s] \"な、なんだかすごく忙しそうだね。\""
10016040-28 = "あっ、[USERNAME]先生！こんにちは。"
10016040-29 = "ご挨拶が遅くなり申し訳ありません。#n実行委員会の仕事に追われてしまっていまして……"
10016040-30 = "もしかして、先生も何かご質問が？"
10016040-31 = "[s] \"ううん、気にしなくて大丈夫だよ。\""
10016040-33 = "[ns] \"ところで……お昼は食べた？\""
10016040-34 = "お昼、ですか……？"
10016040-38 = "あら、もうこんな時間なんですね。"
10016040-39 = "実行委員会の仕事をしていたら、時間が経つのも忘れてしまっていました……"
10016040-40 = "まだ色々と残ってしまっていますので……ご飯は後でいただく予定です。"
10016040-41 = "[s] \"お仕事、一緒にやるよ。\""
10016040-42 = "いえ、大丈夫ですよ。"
10016040-43 = "私のせいで先生までご飯を食べ逃してしまうのは、申し訳ないですから……"
10016040-44 = "えっ？この辺で一番評判のいい屋台……ですか？"
10016040-45 = "そうですね……玄武商会の屋台で売っている中華丼が美味しいと聞きますが……。"
10016040-46 = "玄武商会の屋台はそこを曲がったらありますので、すぐ見つかると思います。"
10016040-47 = "[s1] \"方向音痴だから、道に迷っちゃうかも……。\"\n[s2] \"マリーに道案内をしてもらえたら助かるなぁ……。\""
10016040-52 = "ふふ……それなら、仕方ないですね。"
10016040-53 = "それでは急いで仕事を終わらせますね。#n先生を屋台までご案内いたします。"
10016040-55 = "（……その後、マリーの仕事のお手伝いをした）"
10016040-57 = "先生、お疲れ様でした。"
10016040-58 = "おかげで皆さんの様々なお悩みを解決できました。"
10016040-59 = "[s3] \"マリーもお疲れ様。\"\n[s4] \"みんな、マリーにお悩み相談したくなっちゃうのかな。\""
10016040-60 = "悩みを聞くのはシスターの役目ですから。"
10016040-61 = "悩みを聞くのはシスターの役目ですから。"
10016040-62 = "内に秘めていた悩みや苦しみを打ち明けてくださるのは良い事です。"
10016040-63 = "まぁ……お昼の時間は少し遅くなってしまいましたが。ふふっ。"
10016040-64 = "[s5] \"頑張った分、お昼は私がご馳走するね。\"\n[s6] \"マスター、中華丼2人前お願い。\""
10016040-65 = "あっ、その必要は……"
10016040-66 = "あっ、その必要は……"
10016040-67 = "中華丼2人前ね。あいよ！毎度あり！"
10016040-72 = "はい、中華丼2人前！お待ちどうさん！"
10016040-73 = "は、早い……！"
10016040-74 = "わぁ……この紙どんぶりは何か独特な形ですね！"
10016040-75 = "試合を見に来たお客さんを、お店の前で待たせるわけにはいかないからね。#n飲食業だものスピード命でやらせてもらってんだ！"
10016040-76 = "大運動会は食べながら試合を観戦したいというお客さんが多いからね。#nこの紙どんぶりは持ち歩きに特化してるんだよ。"
10016040-77 = "さて、説明はこの辺で……冷めないうちに食べな。"
10016040-78 = "テーブルもない道端でこうして中華丼をいただくなんて……"
10016040-79 = "ふふ、なんだか悪いことをしているみたいで……ちょっと緊張しますね。"
10016040-80 = "それでは……いただきます。"
10016040-84 = "わぁ！この中華丼、本当に美味しいです。"
10016040-85 = "これは山海経独自の香辛料でしょうか……？#nほのかなスパイスが広がって……"
10016040-86 = "この刺激的でいて、飽きのこない味はクセになりそうです。"
10016040-87 = "そうだろうそうだろう？#nこの中華丼は、私たち玄武商会が開発した秘伝のソースを使った新作なのさ！"
10016040-88 = "……こんなに美味しいのに、ルミ会長は料理対決が終わるやいなや、改善点が浮かんだと言って急に帰ってしまって……"
10016040-89 = "あのゲヘナ生の言葉を気にしすぎなんじゃないだろうか？"
10016040-90 = "[s] \"すみません、おかわりお願いします！\""
10016040-91 = "まいどあり！ちょっと待ってくれよな。"
10016040-95 = "……あ、あっつ！"
10016040-97 = "だ、大丈夫ですか！？"
10016040-98 = "ただの油ハネだから大丈夫。いてて……。"
10016040-99 = "大丈夫じゃないです！火傷はとても怖いんですよ？#n早く合同医療本部に……"
10016040-100 = "でも、ルミ会長もいないのに席を外すわけには……"
10016040-101 = "お店には私が残ってお客様に了承を得ておきます。#n店員さんは先生と一緒に合同医療本部に行ってきてください。早く！"
10016040-102 = "[s7] \"ひょっとしたら傷跡になってしまうかもしれないから。\"\n[s8] \"合同医療本部へは私が案内するね。\""
10016040-103 = "まぁ……お客さんもほとんど帰ったし、ちょっとならいいか。"
10016040-104 = "まぁ……お客さんもほとんど帰ったし、ちょっとならいいか。"
10016040-105 = "じゃあ悪いけど、お願いするね。"
10016040-106 = "はい、いってらっしゃいませ！"
10016040-109 = "先ほどの試合でまた大量の怪我人が……"
10016040-110 = "セナさん、まず軽い擦り傷の方の消毒をお願いします！#n追加措置が必要な方は、私が簡易ベッドに移しておきます。"
10016040-111 = "確認しました。医薬品箱消毒されたガーゼを追加で取ってきます。"
10016040-112 = "[s] \"ここも結構忙しそうだね。\""
10016040-113 = "あれ、先生？合同医療本部に何かご用でしょうか？"
10016040-114 = "もしかしてお怪我を……？"
10016040-115 = "[s] \"怪我したのは私じゃなくて……。\""
10016040-116 = "天ぷらを揚げていたら油で火傷してしまって……面倒をかけて悪いね。"
10016040-117 = "いえ！火傷は早く治さないと傷跡になってしまうかもしれませんからね！"
10016040-118 = "特に温度の高い油は肌の表面にくっつきやすいんです。#n表皮のみならず深部まで到達していたらとても危険です。"
10016040-119 = "セナさん、追加で火傷用のガーゼもご用意いただけますか？"
10016040-120 = "少々お待ちください。骨折した患者に使う添え木を切っていたところなので……"
10016040-121 = "こちらの対応が終わり次第、すぐ対処します。"
10016040-122 = "[s9] \"……手伝おうか？\"\n[s10] \"医薬品を取ってくるくらいならできるから……。\""
10016040-126 = "ダメです！"
10016040-127 = "え、ええっと、救護室の中には……入っちゃダメですよ！"
10016040-128 = "[s] \"救護室に何かあるの……？\""
10016040-129 = "その、ええと……"
10016040-130 = "いま、救護室では砲弾を受けて深刻な負傷状態の重患者を治療しているんです。"
10016040-131 = "かなり酷い状態なので、一般人の先生が見ることはおすすめしません。"
10016040-132 = "はい……見るだけで夢に出てきてしまうような状態なんです！"
10016040-133 = "[s11] \"それは大変だね……。\"\n[s12] \"そんなに忙しいなら、やっぱり手伝ったほうが……\""
10016040-134 = "ひ、ひどい怪我とはいえ……私たちの力だけでも治療できますから！"
10016040-135 = "ひ、ひどい怪我とはいえ……私たちの力だけでも治療できますから！"
10016040-136 = "両学園の医療スタッフが全力で治療していますので、1時間ほどで全快になるでしょう。"
10016040-137 = "[s] \"そんなに簡単に治療できるの……？\""
10016040-138 = "はい！ですから、患者さんの治療は私たちに任せて、#n先生は大運動会を楽しんでください！"
10016040-139 = "そちらの死体……"
10016040-140 = "いいえ、火傷の患者さんはこちらへどうぞ。"
10016040-144 = "し、死体？えっと……とりあえず頼むよ。"
10016040-146 = "（そうして、セナとセリナに押し出されるように合同医療本部を後にした……）"
