[translation]
10019040-10 = "Chegamos diante do guardião do 4º Sanctum.#nVamos começar imediatamente."
10019040-11 = "Com orgulho e convicção gravados em nossos corações... 'Socorro onde o socorro for necessário'!"
10019040-15 = "Sim. Pessoal do 'Esquadrão', por favor, juntem-se a mim!"
10019040-23 = "Entendido.#n— Mas pensar que seríamos usados não apenas para defesa, mas também em operações de ataque..."
10019040-24 = "Bem, tanto faz... Vamos nessa."
10019040-40 = "...Estou indo."
