[translation]
10016010-1 = "第1話;燃え上がる実行委員会"
10016010-2 = "晄輪大祭実行委員会・事務室"
10016010-10 = "……忙しい中こうして集まってくれてありがとう。"
10016010-11 = "開会式も無事終わった事だし、今後のスケジュールと注意事項をいくつか説明するわ。"
10016010-12 = "まぁ、開会式では「ちょっとした」問題が発生したけど……"
10016010-13 = "あら……ミレニアム側はアレを些事だと？"
10016010-14 = "え、ええと、それは……"
10016010-15 = "トリニティの選手代表が公の場で晄輪大祭の権威を貶める発言をしたというのに、ただ見過ごすわけにはいきません。"
10016010-16 = "本件は、トリニティ総合学園に責任を問うべき事態だと思いますが。"
10016010-17 = "……"
10016010-18 = "も、もも、申し訳ありません……。"
10016010-19 = "私たちシスターフッドも、まさかあのような事になるとは思わず……"
10016010-20 = "い、いえっ！全く思っていなかったわけではありませんが……#nまさか、あそこまでの事態に発展するとは……"
10016010-21 = "はぁ……可能性はあったのね。"
10016010-22 = "ふふ……責任をとって、トリニティは今回の実行委員から手を引いてはいかがです？"
10016010-23 = "足りない人員の補充は、私たち風紀委員会にお任せください。"
10016010-24 = "――ゲヘナの生徒を増やす、と？"
10016010-25 = "行政官は晄輪大祭を台無しにするおつもりで？"
10016010-26 = "既にどこかの学園のおかげで台無しになっていると思いますよ？"
10016010-27 = "え、えっと……み、皆さん少し落ち着いてください！"
10016010-28 = "晄輪大祭は、学園を問わず皆が手を取り合って競技を行う祭典ですよね。"
10016010-29 = "なのに、競技が始まる前からこうして実行委員会が争っているだなんて皆さんが知ってしまったら……"
10016010-30 = "きっと悲しむと思うのです……。"
10016010-31 = "……失礼しました。"
10016010-32 = "実行委員会が内部で争っていると知られても、悲しむどころか喜ぶ生徒のほうが多いと思いますけど……。"
10016010-36 = "あいだに入ってくれてありがとう。#n――[ruby=いおち]伊落[/ruby]さんだったかしら？"
10016010-37 = "い、いえ……むしろご迷惑をおかけして申し訳ありません……。"
10016010-38 = "それと、私のことは気軽にマリーと呼んでください。"
10016010-39 = "（……なんでこの2人がトリニティの実行委員に選ばれたのか、少し分かった気がするわ）"
10016010-45 = "……その事から、以下の種目は競技内容が部分的に修正されたわ。#n準備に必要な時間を考慮して、調整後の順番やインターバルはプリントに記載してあるから目を通しておいてちょうだい。"
10016010-46 = "直前で変更された部分だけど、参加校のいずれからも反対意見はないわ。"
10016010-47 = "何か質問はある？"
10016010-48 = "[s] \"一つ聞いてもいい？\""
10016010-49 = "シャーレの[USERNAME]先生、どうぞ。"
10016010-50 = "何か気になるところでも？"
10016010-51 = "[s1] \"今回の晄輪大祭はミレニアムが主催を引き受けてると聞いたけど……。\"\n[s2] \"実行委員会って他校の生徒もなれるものなの……？\""
10016010-52 = "はい。晄輪大祭の競技は特定の学園や集団が有利にならないよう、公正に運営する必要がありますから。"
10016010-53 = "はい。晄輪大祭の競技は特定の学園や集団が有利にならないよう、公正に運営する必要がありますから。"
10016010-54 = "全ての運営や管理を主催校の役員が引き受けては、不正が発生しやすいですし、不満も出ます。#nなので、実行委員会は主催校だけでなく、複数の学園で分担して担当しているんです。"
10016010-55 = "それに、晄輪大祭は様々な学園の生徒が集まりますから、当然ですが生徒同士が問題を起こす可能性も上がります。#nそのような事態に発展しても、該当する学園の実行委員が対応することで素早く解決できますからね。"
10016010-56 = "本来、晄輪大祭の実行委員は、各学園の自治区を代表する生徒会役員が務めるという慣例があるのですが……"
10016010-58 = "……どうして今年の晄輪大祭[ruby=パンデモニウム・ソサエティー]に「万魔殿」と[/ruby]「ティーパーティー」が来なかったの？"
10016010-59 = "まったくです……私たち風紀委員会としても、抗議をしたかったのですが。"
10016010-60 = "「万魔殿」のタヌキ……いいえ、マコト議長はこのように仰っていました。"
10016010-62 = "ゲヘナのトップである万魔殿が、実行委員会に入ってわざわざ平凡な生徒たちの面倒を見る、だと？"
10016010-63 = "……このマコト様がそんな面倒くさそうなことをやってたまるか！断る！"
10016010-64 = "代わりにお前たち風紀委員会が全責任を負うんだな！キキキッ！"
10016010-66 = "……ティーパーティーは？"
10016010-67 = "ティーパーティーの現ホストを務めるナギサ様より、祝電を預かっております。"
10016010-69 = "公私ともに忙しく、「晄輪大祭」に参加できなかったこと、とても残念に思っております。"
10016010-70 = "心からのお詫びとして、ハスミさんに良い茶葉をお預けしました。"
10016010-71 = "……それでは、「晄輪大祭」の成功を心よりお祈り申し上げます。"
10016010-73 = "……結局、面倒だから来ないというわけですね。"
10016010-74 = "――失礼な物言いですね。#nティーパーティーは、学園内外の様々な案件が集まってくる重責です。"
10016010-75 = "ナギサ様のことですから……きっと参加したい気持ちを抑え、断腸の思いで私に託してくださったのです。"
10016010-76 = "ああ、それでしたら万魔殿も常に――"
10016010-77 = "はぁ……あのタヌキたちのことは擁護のしようがありませんね。"
10016010-78 = "面倒な仕事はヒナ委員長に回して、裏で無駄な策を弄しているのでしょうから。"
10016010-79 = "ところで、この紅茶ってもしかして……#n先程、話題に挙がっていたティーパーティーの？"
10016010-80 = "……後日とんでもない金額の請求書を送りつけたりしないでしょうね？"
10016010-81 = "――ご心配なく。#nゲヘナに出した紅茶は、コンビニで買ってきた一番安いものですので。"
10016010-82 = "あら、それは……水ではないことに感謝しないといけませんね。"
10016010-83 = "あ、あの……皆さん、もう少し穏やかに……"
10016010-87 = "……両校の生徒会が参加しなかった理由はひとまず理解したわ。"
10016010-88 = "それにしたって……"
10016010-89 = "せめて委員長が来るべきだったんじゃないの？"
10016010-90 = "不良生徒をひと睨みで制圧できるのは、彼女たちぐらいでしょうに……。"
10016010-91 = "その……ヒナ委員長には他にお願いしたい事がありましたので……。"
10016010-92 = "他に……？"
10016010-93 = "過ぎたるは猶及ばざるが如しと申しますか……#n適材適所と捉えてもらえますと。"
10016010-94 = "ツルギは正義実現委員会の委員長ですが、このような対外業務は元から私が担当しておりますので。"
10016010-95 = "それに、ツルギが実行委員を務めることになってしまえば、出場できる競技の数も……。"
10016010-96 = "あっ……"
10016010-97 = "それって、つまり……。"
10016010-98 = "各学園の戦力になるような生徒は選手に回して、#n「運動音痴」の生徒が派遣されたってこと……？"
10016010-100 = "う、運動音痴だなんて、ひどい言い草ですね！"
10016010-101 = "運動神経が良い方ではありませんが……#n少なくとも、正義実現委員会の副委員長として、最低限の体力はありますよ。"
10016010-102 = "ゲヘナには優秀な選手がたくさんおりますので、私が競技に参加する予定はありません。それだけの話です。"
10016010-103 = "それには私も同意見です。#n少しでも優秀な選手を参加させたほうが、総合優勝に近づきますから。"
10016010-107 = "……いい加減にしてくれない！？"
10016010-108 = "たしかに総合優勝が大切なのは分かるけど、だからって実行委員会の仕事を後回しにしていいわけないでしょ！？#n自分の学園のことばっかり考えて！"
10016010-109 = "[ruby=ミレニアム]うちが[/ruby]真面目にやっていたら好き放題やって……#n私たちだって、優勝を諦めてるわけじゃないのよ！？"
10016010-111 = "……ミレニアムは昔からスポーツに興味がなかったのでは？"
10016010-112 = "私もそう聞いています。#n野球の学園別選抜ではいつもランキング外ですし、試合内容よりも奇行が話題になるくらいですから……。"
10016010-114 = "そ、それはそうだけど……"
10016010-115 = "今回の晄輪大祭はミレニアムで開催するわけだし……"
10016010-116 = "ミレニアムサイエンススクールが誇る技術と分析力を駆使したトレーニングで、#n今年こそ総合優勝してみせるわ！"
10016010-124 = "どうしましょう……思った以上に空気が緊迫しています……。"
10016010-125 = "キヴォトスの安寧を願う祭典のお手伝いができると聞いて、#n喜んで参加したのですが……まさかこんな事になってしまうなんて……。"
10016010-126 = "[s3] \"本気で取り組んでる証拠だから、前向きに捉えて大丈夫だよ。\"\n[s4] \"みんな意欲的だから議論がヒートアップしてるだけだよ。\""
10016010-127 = "先生がそうおっしゃるのであれば、大丈夫だと思いますが……。"
10016010-128 = "先生がそうおっしゃるのであれば、大丈夫だと思いますが……。"
10016010-132 = "その胸を強調したジャージ姿は何ですか？#nトリニティは体操着すらまともに着られないんですか？"
10016010-133 = "こ、これは……チャックが噛んでしまって……"
10016010-134 = "そういうあなたこそ、他人の服装を指摘できる立場ですか！？"
10016010-135 = "どうか皆さんが、お怪我せずに晄輪大祭を終えられますように……。"
