[translation]
10024100-1 = "Epílogo; Banquete Completo"
10024100-2 = "（Assim, o tumulto do contrabando do \"Ginseng de Dez Mil Anos\" chegou ao fim）"
10024100-10 = "Q-que prato é este...!?"
10024100-11 = "Primeiro, experimente! É um prato especial feito com sopa ao estilo Red Winter, adicionando carne cozida no vapor ao estilo Wild Hunt e uvas!#n"
10024100-12 = "A sopa está rosa, mas será que isso é realmente comestível...?"
10024100-13 = "A cor é intensa, mas o sabor aromático, agridoce, é uma iguaria!#nA carne cozida no vapor está tão macia que desmancha na boca!"
10024100-18 = "Será que isso é realmente aceitável...#nAs tradições de Shanhaijing... nossa cultura..."
10024100-19 = "Não adianta se preocupar com detalhes!#nDepois que terminar de comer, vou servir doces ao estilo Trinity também!"
10024100-20 = "A combinação de biscoitos amanteigados com açúcar e chá com leite é surpreendentemente boa!"
10024100-22 = "M-misturar leite no chá, não tem como algo assim ser bebível!"
10024100-24 = "Esqueça isso, apenas tome um gole primeiro!#nÉ um sabor que vicia."
10024100-33 = "Sim, pessoal.#nEste banquete foi oferecido pelo pessoal da Genryumon e da Associação Comercial Genbu~"
10024100-34 = "Aproveitem bastante.#nMas, por favor, tomem cuidado para não incomodar ninguém ao redor, está bem?"
10024100-35 = "Sim!"
10024100-36 = "Quando terminarem de comer, não se esqueçam de agradecer pela refeição!"
10024100-37 = "E também, não se esqueçam de escovar os dentes quando chegarem em casa!"
10024100-38 = "A Kokona-chan também precisa escovar os dentes!"
10024100-39 = "Não é Kokona-chan, é Instrutora Kokona!"
10024100-40 = "Então, Kokona-chan. Pode cuidar das crianças por um tempo?"
10024100-41 = "Eh? Shun-nee, onde você vai!?"
10024100-42 = "Ufufu.#nA irmã mais velha... tem um \"compromisso\" com o Sensei agora."
10024100-46 = "Eh? Só a irmã é injusto!#nEu também...! Ugh, mas as crianças..."
10024100-47 = "Ah, Shun-nee!#nVocê vai acabar com o sorvete do freezer de novo!"
10024100-52 = "......Não consigo relaxar com tanta gente aqui~#nEu queria voltar logo para o laboratório..."
10024100-53 = "Mas todos os pratos parecem deliciosos... o que eu faço."
10024100-54 = "Já sei, tive uma ideia! Como esperado de mim!"
10024100-55 = "Seria ótimo se eu tivesse um remédio para criar um clone!"
10024100-56 = "Assim, um poderia saborear a comida e o outro poderia se concentrar na pesquisa!"
10024100-57 = "Mas, para isso, eu teria que voltar e pesquisar primeiro, então..."
10024100-58 = "Eu não conseguiria comer essa comida!"
10024100-59 = "......Nhm, nham nham...#nTodos os pratos estão realmente deliciosos."
10024100-69 = "Todos parecem felizes, Kisaki."
10024100-70 = "Era essa a cena que você queria ver?"
10024100-71 = "Bem, quem sabe.#nPara mim, contanto que Shanhaijing esteja em paz, já basta."
10024100-72 = "Fufu. Faz tempo que não vejo uma expressão tão feliz no seu rosto, Kisaki."
10024100-73 = "[s] \"É verdade.\""
10024100-77 = "Você também vê dessa forma?"
10024100-78 = "......Acho que posso relaxar um pouco em momentos como este."
10024100-79 = "Ainda assim, é uma combinação curiosa de pratos.#nGelo com leite, leite condensado, uvas e balas..."
10024100-81 = "Gostaria que eu trouxesse mais, Mestra?"
10024100-82 = "Fufu, já que estamos aqui, acho que vou experimentar os outros pratos também."
10024100-83 = "Fufu. Fico feliz que a Kisaki, que come tão pouco, esteja comendo tanto da minha comida.#nPara mim, você é como uma irmã mais nova."
10024100-84 = "......Quantas vezes tenho que dizer que não pretendo ser sua irmã mais nova."
10024100-85 = "Não tem problema! Há quantos anos você acha que estamos juntas!#nAqui, coma isto também. Morangos com chantilly envoltos em mochi!"
10024100-87 = "Ou você preferia as bolinhas de queijo fritas?#nComo só teve coisas doces, você deve querer algo salgado para limpar o paladar."
10024100-88 = "Hum, acho que vou aceitar ambos."
10024100-90 = "（Os problemas entre as organizações podem não ser resolvidos tão cedo）"
10024100-91 = "（Mesmo assim, se essas duas estiverem aqui, com certeza...）"
10024100-92 = "Dragões no Mesmo Barco ~Imaginando um Futuro~"
