[translation]
10028020-1 = "Episódio 2; Coisas do dia a dia"
10028020-7 = "Haa... haa, haa..."
10028020-8 = "Só um pouco... de fôlego... ufa..."
10028020-13 = "Mas... de alguma forma, conseguimos embarcar, né... haha..."
10028020-20 = "...Professor? V-você está bem? #nPor acaso você não está se sentindo mal, está...!"
10028020-21 = "[s1] \"N-não se preocupe, estou bem...\"\n[s2] \"É que... eu preciso... melhorar meu condicionamento físico... talvez...\""
10028020-24 = "A-ainda bem..."
10028020-25 = "Haa... eu queria que o professor tivesse descansado no trem de volta, mas..."
10028020-29 = "Sinto muito... por tudo ter acabado assim..."
10028020-30 = "Dizer que está tudo bem... #nEu agradeço por dizer isso, mas..."
10028020-31 = "Mas, ainda assim, o começo não foi nada bom..."
10028020-32 = "Uuu... onde será que eu errei..."
10028020-36 = "M-mas...! A mala deve estar neste trem!"
10028020-37 = "O pior cenário foi evitado!"
10028020-38 = "[s3] \"Tudo bem, não se preocupe.\"\n[s4] \"Isso é algo que acontece todo dia.\""
10028020-41 = "V-verdade!! Isso é algo que acontece todo dia mesmo! Haha!"
10028020-42 = "Assim que encontrarmos a mala, podemos descer no caminho e pegar o trem para Trinity..."
10028020-43 = "Temos tempo de sobra! Se conseguirmos voltar hoje, não tem problema!"
10028020-47 = "Bem, o fato de ser um \"trem para Gehenna\" é um pouco preocupante, mas..."
10028020-52 = "............?"
10028020-53 = "O que é aquilo? Aquela ali não é de Trinity? #nPor que tem alguém de Trinity aqui...?"
10028020-54 = "E aquela braçadeira... aquilo é do Comitê de Justiça, não é?"
10028020-55 = "Por que alguém de Trinity está em um trem para Gehenna?"
10028020-70 = "...Hum."
10028020-71 = "Sabe, esse clima..."
10028020-72 = "Não somos bem-vindas, né..."
10028020-73 = "[s5] \"A incompatibilidade entre as escolas é inevitável...\"\n[s6] \"Mesmo que não tenha jeito...\""
10028020-76 = "Ei, vocês aí! Que barulheira é essa!!"
10028020-80 = "Francamente, o pessoal de Gehenna sempre causa problemas, não é!?"
10028020-84 = "...Hm? O que é isso?"
10028020-85 = "Não é uma aluna de Trinity!? #nPor que você está neste trem? Este é o trem para Gehenna, sabia?"
10028020-89 = "...Não, tanto faz. Mostre sua passagem."
10028020-90 = "E-e-então... a passagem...? #nÉ que..."
10028020-91 = "...Hm? Você não tem passagem?"
10028020-92 = "E quanto a esse adulto aqui?"
10028020-93 = "...Os dois não têm? Vocês estão brincando comigo?"
10028020-94 = "Ah... não, espere um pouco, por favor. Existe um motivo para isso..."
10028020-95 = "Motivo? O que seria, por acaso é aquilo?"
10028020-96 = "Achou que, por ser um trem para Gehenna, não seria algo sério?"
10028020-97 = "...Eh."
10028020-98 = "Não, é que..."
10028020-99 = "Achou que, como os passageiros são barulhentos, conseguiria enganar os funcionários...!"
10028020-100 = "Isso, espere..."
10028020-101 = "Achou que poderia viajar de graça, não foi...?"
10028020-102 = "Não é isso, deixe-nos explicar..."
10028020-103 = "Eu já sei quais são suas desculpas!"
10028020-104 = "Não, nós..."
10028020-105 = "Pensando que aqui é terra de ninguém..."
10028020-106 = "Tentando viajar de graça em plena luz do dia, não é!!"
10028020-107 = "É por isso que nós queríamos comprar a passagem..."
10028020-108 = "Já chega!! Até a Trinity vir tirar sarro da gente!!!"
10028020-109 = "PIII! PIIIIIIIIIIII!! Todos, reunir-se!!!!!"
10028020-110 = "Encontramos uma dupla de clandestinos! Lidem com eles usando o Manual C!!"
10028020-113 = "O quê, clandestinos!? Então são eles...!!"
10028020-114 = "Não aguento mais... Sem perguntas, vamos capturá-los!!"
10028020-115 = "Todos, reúnam-se rápido!!!!"
10028020-120 = "...Hum."
10028020-121 = "Hmmmm."
10028020-122 = "Que estranho..."
10028020-123 = "..."
10028020-128 = "Não era para ter sido assim..."
