[translation]
10023110-1 = "Epílogo; Um final feliz para sempre!"
10023110-5 = "……"
10023110-6 = "……"
10023110-7 = "Iii..."
10023110-9 = "Waaaaa! A Neru-senpai está brava! Alice está com medo!"
10023110-11 = "Escutem aqui, vocês..."
10023110-12 = "Perdoe-nos, Neru-senpai!"
10023110-13 = "……Ah? Do que você está falando?"
10023110-14 = "Você precisa que a gente diga com todas as letras?#nQue cruel, senpai!"
10023110-15 = "Não, eu estou perguntando do que você está falando..."
10023110-16 = "Pessoal, me desculpem!#nSe eu... se eu tivesse recusado desde o início... nada disso teria acontecido...!"
10023110-17 = "Já era... A Neru-senpai está furiosa e o Clube de Desenvolvimento de Jogos vai ser fechado...#nO crime de se passar pela C&C é grave..."
10023110-18 = "Uuu... É um clube que nos esforçamos tanto para proteger...#nMesmo agora que a Alice e a Yuzu conseguiram ficar juntas assim...!"
10023110-20 = "Momoi..."
10023110-21 = "N-não chore, por favor. Momoi, a Alice..."
10023110-22 = "Nós ficaremos bem.#nA Alice aprendeu que, mesmo estando longe, nossos corações estão juntos...!"
10023110-24 = "Haa... Vocês parecem ter entendido tudo errado..."
10023110-25 = "Eu ainda não fiz nada..."
10023110-26 = "Espera, vocês sempre pensaram isso de mim!?"
10023110-27 = "Fufu, quem sabe?"
10023110-28 = "Ei, você está querendo dizer que eu mereci isso!?"
10023110-30 = "Senpais, peço perdão."
10023110-31 = "Consegui recuperar as evidências, mas não fui capaz de capturar os suspeitos..."
10023110-33 = "Ah, isso não importa, nós já os capturamos."
10023110-34 = "Não. Foi por minha incompetência que acabei dando trabalho para as senpais..."
10023110-35 = "Não se preocupe com isso.#nQuem ri por último, ri melhor, não é?"
10023110-36 = "E então..."
10023110-41 = "Vocês."
10023110-46 = "Iii!?"
10023110-47 = "P-pelo menos poupe nossas vidas...!"
10023110-49 = "Espere, Neru-senpai."
10023110-50 = "Ahã?"
10023110-51 = "Sobre este caso... por favor, não culpe tanto o Clube de Desenvolvimento de Jogos."
10023110-52 = "Oh?"
10023110-53 = "O Clube de Desenvolvimento de Jogos não fez nada de errado."
10023110-54 = "O correto seria ter entrado em contato com as senpais e esperado por reforços, mas eu não fiz isso."
10023110-55 = "E, como membro do Clube de Desenvolvimento de Jogos — como amiga.#nEu escolhi lutar ao lado delas."
10023110-56 = "Portanto... se diz que elas têm culpa, então eu também tenho."
10023110-58 = "I-isso mesmo, Neru-senpai!#nA Toki e a Alice são companheiras. Somos amigas!"
10023110-59 = "Aprendi nos jogos que, quando um amigo está em apuros, devemos ajudar uns aos outros.#nPor isso, por isso..."
10023110-61 = "Não, é que... o que eu quero dizer é..."
10023110-62 = "O que é, esse..."
10023110-63 = "Vocês fizeram um bom trabalho."
10023110-68 = "Hã...?"
10023110-69 = "Hã!? Você não é uma impostora idêntica à Neru-senpai, é?"
10023110-71 = "Do que você está falando!"
10023110-72 = "Caramba, eu estou tentando elogiar vocês..."
10023110-74 = "Bem... você realmente nos perdoa...?"
10023110-75 = "Ahã?"
10023110-79 = "Perdoar ou não, no fim das contas vocês resolveram tudo, não foi?"
10023110-80 = "Então está tudo bem. O suspeito foi capturado e as evidências foram reunidas."
10023110-81 = "Agora é só entregar tudo para a Valkyrie, certo?"
10023110-86 = "(A senpai Neru... ela pode ser pequena, mas tem um coração enorme...)"
10023110-87 = "(Irmã! Cuidado com o que diz! E se ela ouvir?!)"
10023110-93 = "E então, Toki, você também..."
10023110-94 = "Sim, estou preparada para aceitar qualquer punição."
10023110-95 = "Por isso eu disse que não é isso... Ah, droga!"
10023110-96 = "Primeiro, por que uma roupa de coelhinha?"
10023110-97 = "Claro, porque era uma missão de infiltração."
10023110-101 = "……Haa."
10023110-102 = "É por isso que, naquela hora, eu disse que não queria vestir aquilo..."
10023110-104 = "Hm? Líder, mas você ficou tão bem nela, não ficou?"
10023110-105 = "Ahaha! A Toki-chan também está uma gracinha!"
10023110-110 = "Muito, obrigada..."
10023110-111 = "Enfim!"
10023110-112 = "O que eu quero dizer é..."
10023110-114 = "Sim. Suspensão, detenção, confinamento, aceitarei qualquer tipo de punição."
10023110-115 = "Eu disse que não!"
10023110-116 = "Ah, meu Deus..."
10023110-117 = "[s1] \"A Neru está elogiando a Toki.\"\n[s2] \"Ela quer se desculpar por ter deixado você para trás.\""
10023110-121 = "Se, Sensei!?!"
10023110-122 = "Droga... esqueci que o Sensei estava aqui...!"
10023110-124 = "Isso, o que exatamente significa...?"
10023110-125 = "Ah, chega! Eu já disse!"
10023110-129 = "……Você fez um bom trabalho. E também... me desculpe."
10023110-130 = "É isso, entende? Eu... não queria ter deixado você para trás."
10023110-131 = "Desta vez foi uma missão de emergência e não tive escolha a não ser deixar você sozinha. #nMas você conseguiu terminar até o fim..."
10023110-132 = "Então... bom trabalho."
10023110-134 = "Fufu, é isso mesmo, Toki-chan. #nA líder não é muito honesta nessas horas."
10023110-135 = "Não diga coisas desnecessárias!"
10023110-136 = "Mas é verdade, Toki-chan! Que bom, né!"
10023110-142 = "……Muito obrigada."
10023110-144 = "Haa... que cansaço~ #nDepois de tanto esforço, não só não ganhamos recompensa, como o pedido em si desapareceu... foi tudo em vão."
10023110-145 = "Mas não serviu de inspiração para o próximo jogo?"
10023110-146 = "Próximo jogo...?"
10023110-147 = "Ah, é verdade... só de material, temos de sobra..."
10023110-148 = "[s] \"Ah, falando nisso. Vocês devem receber uma recompensa da Valkyrie.\""
10023110-149 = "Eh...? Recompensa, como assim? #nÉ a primeira vez que ouço falar disso."
10023110-150 = "[s3] \"Eu também soube agora há pouco, mas esses itens roubados...\"\n[s4] \"Parece que a Valkyrie também estava procurando por eles.\""
10023110-153 = "Recompensa pela conclusão da missão! #nTan-tan-tan! Alice e as outras conseguiram a recompensa!"
10023110-156 = "Ah! Então, com esse dinheiro, o Play-Station――"
10023110-157 = "Tem um jeito melhor de usar, não tem, irmã!?"
10023110-158 = "Por que!? Nós somos o Departamento de Desenvolvimento de Jogos! #nSe o Departamento de Desenvolvimento de Jogos não investir em jogos, vai investir em quê!"
10023110-160 = "Alice, tenho uma ideia!"
10023110-161 = "A chefe do Departamento de Desenvolvimento de Jogos é a Yuzu! Vamos deixar a Yuzu decidir!"
10023110-167 = "……Eu tenho, uma ideia……"
10023110-168 = "Eh? O que é, o que é?"
10023110-169 = "Que tal usarmos esse dinheiro... para o custo de desenvolvimento do próximo jogo?"
10023110-170 = "Custo de desenvolvimento do próximo jogo...?"
10023110-172 = "……Falando nisso, a verba de pesquisa e desenvolvimento que recebemos do Seminar está quase acabando..."
10023110-173 = "Como esperado da Yuzu!"
10023110-175 = "Se usarmos a experiência que ganhamos aqui..."
10023110-176 = "Talvez possamos criar algo ainda mais interessante..."
10023110-178 = "Isso mesmo! Eu tenho uma ótima ideia!"
10023110-179 = "Escuta, escuta! É assim..."
10023110-180 = "Não fala, faz um documento de planejamento de verdade... irmã mais velha."
10023110-181 = "N-não é isso... Eu não sou boa com documentos de planejamento, irmãzinha."
10023110-182 = "Você é roteirista e planejadora, como pode não ser boa com documentos de planejamento?!"
10023110-184 = "Quando voltarmos... preciso preparar a codificação imediatamente..."
10023110-186 = "Espera! Para transformar essas ideias transbordantes em algo concreto..."
10023110-187 = "Que tal jogarmos um pouco primeiro?"
10023110-188 = "Nem pensar! Você vai acabar dizendo que as ideias desapareceram enquanto a gente brincava, não vai?!"
10023110-190 = "Alice, estou pronta a qualquer momento!"
10023110-192 = "Elas estão cheias de energia... fufu..."
10023110-197 = "(E assim, elas retornaram do extraordinário que surgiu de repente para o cotidiano de sempre—)"
10023110-198 = "(Elas brincaram alegremente até altas horas da noite)"
10023110-200 = "(E assim, quando todos já estavam dormindo...)"
10023110-204 = "[ns] \"Momoi.\""
10023110-205 = "Hm? O que foi, Sensei?"
10023110-206 = "[s] \"Foi realmente muito difícil, não é...\""
10023110-207 = "Sim..."
10023110-208 = "Teve um momento em que achei que tudo ia dar errado..."
10023110-209 = "Mas sabe!"
10023110-210 = "[s] \"Hm...?\""
10023110-211 = "A Midori, a Yuzu e a Alice também!#n—E a Toki também. Porque vocês estavam comigo!"
10023110-212 = "Foi difícil, mas foi realmente muito, muito divertido!"
10023110-213 = "Como foi para você, Sensei?"
10023110-214 = "[s] \"Sim, eu também me diverti muito.\""
10023110-215 = "Hehe, que bom!"
10023110-220 = "(Os sorrisos da Momoi e do Clube de Desenvolvimento de Jogos pareciam brilhar mais do que nunca)"
10023110-225 = "\"...Sim, é claro. Todas vocês são alunas preciosas.\""
10023110-233 = "..."
10023110-237 = "\"...Sim, é claro. Todas vocês são alunas preciosas.\""
10023110-238 = "...Sensei."
10023110-242 = "\"...Sim, é claro. Todas vocês são alunas preciosas.\""
10023110-243 = "Ufa..."
10023110-244 = "Meu peito está tão apertado... O que é essa batida..."
10023110-245 = "Mas não é doloroso... Pelo contrário, é um sentimento de felicidade."
10023110-246 = "Por que será? Será que o Sensei sabe a resposta?"
10023110-247 = "..."
10023110-248 = "Não há nada que eu não possa roubar. Sempre... as coisas preciosas são para todos."
10023110-249 = "As pessoas não nascem com um nome. O mesmo vale para o coração.#n...Dizem que a vida é uma sucessão constante de escolhas."
10023110-250 = "Sensei, um dia—"
10023110-256 = "—eu virei buscar o nome desse sentimento."
10023110-259 = "O Aviso de Prévia de Giz Branco ~A Mansão da Vaidade e o Lugar da Estética~"
