[translation]
10021005-3 = "先生！現在「アトラ・ハシースの箱舟」は、自爆態勢に入りました！！"
10021005-4 = "生徒のみなさんは、先生を助けるために向かっていますが、それまでに私たちはこの「ナラム・シンの玉座」で、別の時間軸の「シロコ」さんと「プレナパテス」に立ち向かわなくてはなりません！"
10021005-5 = "最後の戦いになるかもしれません！私たちの全力で応戦しましょう！"
10021005-6 = "では、よろしくお願いします、先生！"
