[translation]
1002702-1 = "Um ângulo inesperado"
1002702-4 = "（Trouxe o que me pediram e vim ao lugar onde disseram que a Asuna estaria, mas não há ninguém por perto...）"
1002702-8 = "[ns] \"……？\""
1002702-10 = "Aqui é a Karin."
1002702-11 = "Hum, Sensei?"
1002702-12 = "Bem, desculpe... Acabei de ouvir que parece que houve um mal-entendido..."
1002702-13 = "A Asuna-senpai foi para algum lugar que não faço ideia de onde seja..."
1002702-14 = "Sinto muito mesmo, pedi sua ajuda mesmo você estando ocupado..."
1002702-15 = "O que eu deveria fazer..."
1002702-16 = "...Por enquanto, você poderia deixar aí? Não posso te causar mais problemas do que já causei..."
1002702-17 = "Quando as coisas se acalmarem mais tarde, eu irei buscar."
1002702-18 = "[s1] \"Tudo bem, mas...\"\n[s2] \"Onde você está agora, Karin?\""
1002702-19 = "...Hum?"
1002702-20 = "...Hum?"
1002702-21 = "Eu?"
1002702-22 = "Bem... Acho que você consegue ver um prédio abandonado se entrar na rua ao lado de onde você está agora."
1002702-23 = "Estou no último andar dele. Mas não posso desviar a atenção do meu alvo de vigilância agora..."
1002702-24 = "[s] \"Então, vou levar até aí.\""
1002702-25 = "Eh?"
1002702-26 = "Fazer você ir até aí... sinto que estou abusando da sua boa vontade..."
1002702-27 = "Parece que estou te tratando como um faz-tudo..."
1002702-28 = "[s] \"Está tudo bem, espere um pouco.\""
1002702-29 = "Se é assim... hum."
1002702-30 = "Então, vou aceitar sua ajuda."
1002702-31 = "Obrigada, Sensei."
1002702-38 = "（Aquele prédio abandonado estava bem deteriorado, parecia um lugar que foi deixado de lado há muito tempo）"
1002702-39 = "（Apenas o som dos meus próprios passos ecoava de forma estranhamente alta）"
1002702-40 = "Sensei, você não se perdeu, né?"
1002702-41 = "...Ah, ouvi os passos do Sensei."
1002702-42 = "Parece que não há mais risco de se perder, então."
1002702-43 = "[s] Seguir em frente sem parar."
1002702-49 = "...Ah, Sensei?"
1002702-50 = "[s]\"...!?\""

1002702-51 = "……？"
1002702-52 = "Sensei, aconteceu alguma coisa?"
1002702-53 = "A postura...?"
1002702-54 = "……Ué!?"
1002702-57 = "[wa:50]― ……Ué!?"
1002702-61 = "[wa:700]― Se, [wa:1200]Sensei!?[wa:1700] Não, [wa:870] isso é, tipo...!"
1002702-64 = "[wa:50]― Espere![wa:1250] Agora, [wa:480] não posso mudar minha postura...!"
1002702-67 = "[wa:1050]― Bem, [wa:1450] estou em uma missão de sniper agora...!"
1002702-70 = "[wa:100]― Não posso [wa:400] tirar a mira do alvo,"
1002702-72 = "― Então...!"
1002702-75 = "[wa:550]― ...Eh, [wa:1700] aqui está tudo bem...?"
1002702-77 = "― ...Na verdade, [wa:880] você quer que eu continue assim?[wa:2150] Ei...!"
1002702-80 = "[wa:1000]― V, [wa:1020] você parece [wa:480] estar gostando, mas [wa:2530] isso é demais...!"
1002702-82 = "― Realmente [wa:500] não dá, [wa:1300] é vergonhoso...!"
1002702-85 = "[wa:650]― Eh, [wa:1100] para continuar sem se importar...?"
1002702-87 = "― C, [wa:1000] como vou conseguir não me importar!? [wa:1770] Idiota!"
1002702-90 = "（Fiquei esperando quietamente atrás dela até que a Karin terminasse a missão）"
1002702-95 = "……Bem, missão cumprida."
1002702-96 = "Hm? Esse visual…?"
1002702-97 = "Ah, bem, como a missão de hoje não envolvia encontrar ninguém, pensei que seria uma boa oportunidade para usar isso…"
1002702-98 = "Mas deixando isso de lado… hah, desculpe. Eu não esperava que as coisas fossem ficar assim."
1002702-99 = "Eu sabia que o Sensei viria, mas não consegui pensar direito sobre isso…"
1002702-100 = "Bem, eu planejava ficar aqui por mais um tempo, mas de qualquer forma, obrigada. O Sensei já vai voltar para o Schale?"
1002702-101 = "……Quer ficar comigo por mais um pouco?"
1002702-102 = "Fufu. Será que o Sensei está dizendo algo tão gentil assim porque acha que eu estou me sentindo solitária aqui sozinha?"
1002702-103 = "Está tudo bem, atiradores de elite passam por isso de ficar esperando sozinhos o tempo todo, então…"
1002702-104 = "……Não é nada disso? Então, isso significa que, talvez…"
1002702-105 = "……É um colírio para os olhos?"
1002702-109 = "……Hah."
1002702-110 = "O Sensei é realmente, ah, não tem jeito mesmo…"
