[translation]
10027110-1 = "第11話;特別な取引"
10027110-4 = "レッドウィンター連邦学園・雪山"
10027110-6 = "うわぁあ！遅れる！遅れちゃう！"
10027110-7 = "でも、なんとかなりましたね……お疲れ様でした、先生……。"
10027110-11 = "[ns] \"直感が言っている……これは不吉だと……！\""
10027110-12 = "急にどうしたんですか先生？"
10027110-13 = "え？二度あることは三度ある？#nまたまた、そんな。"
10027110-14 = "そうですよ！偶然が重なっただけなんじゃないですか？"
10027110-22 = "「知識解放戦線」で「同人誌」を作っていると聞きました！"
10027110-23 = "私はいい考えがあるってノドカに言われたから付いてきたよ。"
10027110-25 = "まさか……？"
10027110-27 = "同人誌の内容はよく分かりませんが、とにかくそれが貴重で価値のあるものだとお聞きしましたので！"
10027110-28 = "それを手に入れてチェリノ会長と取り引きしたら、ストーブがもらえるかもしれないじゃん？"
10027110-29 = "シグレちゃん！227号特別クラスの生活に慣れないで！？#n停学から抜け出すことを考えないと！"
10027110-30 = "とにかく……チェリノ会長は欲張りですからね！#n他人が貴重だと言うのなら、何が何でも自分のものにしようとするでしょう。"
10027110-31 = "私たちはチェリノ会長のそういう部分を利用して停学から抜け出し……きちんとした暖房器具があって、虫がいなくて、布団があって……飢えた熊も出てこない……「普通」の生活に戻りたいんです！"
10027110-38 = "人の同人誌をそんなことに使うな！"
