[translation]
10020015-5 = "O "Motor Dimensional" da Área 1 foi destruído com sucesso!!"
10020015-13 = "[ns] \"E-espera!!\""
10020015-14 = "A, a Shiroko-san recuou... ela desapareceu."
10020015-15 = "[ns] \"............\""
10020015-17 = "A Shiroko-chan fugiu de novo, hein..."
10020015-18 = "Sim... ela não deu nem chance para o Sensei agir..."
10020015-20 = "Bem, acho que não tem problema."
10020015-21 = "Se a Shiroko-chan vai ficar nos atrapalhando por aí, #nnós só precisamos destruir a Arca."
10020015-22 = "Assim, ela certamente aparecerá diante de nós no final."
10020015-23 = "Nesse momento, poderemos conversar direito com ela."
10020015-24 = "Se destruirmos tudo, ela não terá para onde fugir, não é?"
10020015-25 = "I-isso é verdade, mas... você não está empolgada demais com essa "captura"?"
10020015-33 = "Até agora, a situação da batalha de ocupação não está ruim."
10020015-34 = "Ocupamos a Área 1 sem problemas e a destruição do "Motor Dimensional" foi um sucesso. #nNão é um começo muito bom?"
10020015-35 = "Conseguimos tomar para nós cerca de um quarto da capacidade de processamento da Arca."
10020015-36 = "Sim — com isso, agora podemos fazer muito mais coisas do que antes."
10020015-37 = "É verdade. Primeiro, acho que a defesa desta área ficará mais fácil. #nDe agora em diante, o sistema de defesa que construímos nos protegerá até certo ponto."
10020015-39 = "Ah... que alívio~ #nFinalmente vou poder descansar..."
10020015-40 = "Além disso, também podemos avançar para a próxima área."
10020015-41 = "Área 2, né? #nOra, ora, estamos indo muito bem, não estamos?"
10020015-43 = "...No entanto, não podemos baixar a guarda até o fim."
10020015-44 = "Então, vamos entrar na Área 2 da "Arca de Atra-Hasis"."
10020015-45 = "Sensei, continue no comando, por favor!"
