[translation]
10029005-1 = "Prólogo; Outra Cidade Acadêmica"
10029005-2 = "（Uma tarde qualquer, enquanto eu descansava no sofá da sala de descanso após terminar o trabalho）"
10029005-8 = "……Ah, Sensei. Você tem um momento?"
10029005-9 = "[s1] \"O que houve, Eimi?\"\n[s2] \"Claro, estou livre.\""
10029005-12 = "Hmm……#nEu poderia falar por comunicação, mas talvez seja mais rápido se você vier até aqui."
10029005-13 = "Você poderia vir ao Millennium depois?"
10029005-14 = "……?"
10029005-15 = "Ah, desculpe. #nPelo menos eu deveria explicar o básico."
10029005-16 = "Se você tiver uma noção do que está acontecendo, poderá ir pensando no caminho……"
10029005-17 = "Seria mais eficiente. #nÉ um assunto um pouco sério."
10029005-18 = "……Estávamos investigando umas ruínas durante as atividades do Departamento de Investigação de Fenômenos Estranhos e encontramos sobreviventes. #nEntão, por enquanto, os trouxemos para o Millennium, mas……"
10029005-19 = "Segundo a chefe do departamento, essas pessoas……"
10029005-20 = "――Parece que vieram de outro mundo."
10029005-22 = "#video;10029"
