[translation]
10023030-1 = "Episódio 3: O Coração sem Relógio"
10023030-2 = "“Ladrão da Benevolência”... quem é esse?"
10023030-3 = "O “Ladrão da Benevolência” é um dos infames “Sete Prisioneiros”.#nNão sei o nome verdadeiro, mas..."
10023030-4 = "[s1] “Os ‘Sete Prisioneiros’...!?”\n[s2] “O mesmo que a Wakamo...?”"
10023030-5 = "Exatamente.#nA Wakamo, conhecida como a “Raposa da Calamidade”, transforma tudo ao seu redor em terra arrasada sempre que aparece, mas..."
10023030-6 = "Exatamente.#nA Wakamo, conhecida como a “Raposa da Calamidade”, transforma tudo ao seu redor em terra arrasada sempre que aparece, mas..."
10023030-7 = "O “Ladrão da Benevolência”... é famoso por sempre roubar o que escolhe como alvo."
10023030-9 = "“Ladrão”... isso é só um criminoso! E que nome estranho!"
10023030-10 = "Irmã..."
10023030-11 = "Ho... reagir assim ao “Ladrão da Benevolência”...#nComo esperado da C&C."
10023030-12 = "No entanto... os feitos do “Ladrão da Benevolência” não podem ser ignorados. Uma vez que o aviso chega, não há segurança que baste; o tesouro sempre é levado..."
10023030-13 = "Embora, como o aviso é extremamente enigmático, o fato de ninguém saber o que está sendo visado até que seja roubado também seja um fator importante."
10023030-17 = "Tan-tan-tan! Atualização de missão. O próximo confronto é contra o “Ladrão da Benevolência”!"
10023030-18 = "Esse aviso... nós também podemos... ver?"
10023030-19 = "Sim, claro."
10023030-20 = "Aqui está."
10023030-22 = "Dois viajantes que se encontram 22 vezes ao dia."
10023030-24 = "Dois precisos. 20 imensuráveis. E meio passo."
10023030-26 = "O lugar onde a lua não alcança, a dança parada e o lado oculto de Antikythera."
10023030-28 = "Visitarei a espada luxuosa, porém infeliz, que nunca foi premiada.#n――Ladrão da Benevolência"
10023030-31 = "Isso é...?"
10023030-35 = "É o aviso do “Ladrão da Benevolência”. Para começar, é muito difícil de decifrar..."
10023030-36 = "Apesar disso, o “Ladrão da Benevolência” espalha seus próprios crimes, dizendo: “Enviei o aviso abertamente e o roubo foi um sucesso”."
10023030-37 = "Ah, não importa quantas vezes eu leia, não entendo.#nO que seriam esses “dois viajantes que se encontram 22 vezes ao dia”?"
10023030-41 = "Não significa que tem alguém nesta mansão que se encontra 22 vezes por dia?"
10023030-42 = "O que você está dizendo, irmã?#nComo você contaria quantas vezes as pessoas se encontram?"
10023030-44 = "Alice, entendi! Esses viajantes são NPCs.#nSe forem NPCs de balcão de missão, você pode encontrá-los não só 20 vezes, mas muito mais por dia!"
10023030-45 = "Alice... na realidade, não existem NPCs de balcão de missão..."
10023030-47 = "Não é verdade!#nYuzu pode encontrá-los se for a lugares específicos, e se você conversar, eles dão missões!"
10023030-49 = "Uuu... não posso negar completamente, mas..."
10023030-53 = "[ns] “Se são 22 vezes por dia, é um ritmo de quase uma vez por hora...”"
10023030-54 = "O dia tem 24 horas, então eles não se encontram por 2 horas..."
10023030-55 = "24 horas... será que...?"
10023030-56 = "Desculpe... Sr. Meitaro.#nExiste algum relógio analógico nesta mansão...?"
10023030-57 = "Ah, sim... há um grande relógio de parede no centro do saguão..."
10023030-58 = "Poderia... dar uma olhada nesse relógio...?"
10023030-59 = "Sim, claro. Por acaso, encontrou alguma pista...?"
10023030-60 = "Yuzu, você descobriu algo?"
10023030-62 = "Se o meu raciocínio estiver correto... este aviso é..."
10023030-64 = "Eu sabia...!"
10023030-65 = "O-o que foi, Yuzu?#nSe for sobre as horas, dá para ver no celular, não dá?"
10023030-66 = "Não, não é isso. O celular... ou melhor, relógios digitais não ajudam muito."
10023030-67 = "...Acho que consegui decifrar a primeira linha e parte da segunda...!"
10023030-69 = "!!!"
10023030-70 = "Hã!? Como assim? Como você fez isso!?"
10023030-72 = "Os “dois viajantes que se encontram 22 vezes ao dia”...#nProvavelmente, está falando do ponteiro das horas e do ponteiro dos minutos de um relógio analógico."
10023030-73 = "Mas Yuzu, o dia tem 24 horas. São duas vezes a mais!"
10023030-74 = "Sim... eu também pensei isso no começo. Mas, Alice.#nOs ponteiros do relógio se sobrepõem 11 vezes de manhã e 11 vezes à tarde... totalizando apenas 22 vezes."
10023030-75 = "O ponteiro das horas se move 0,5 grau por minuto e o dos minutos se move 6 graus por minuto, então...#nEles se sobrepõem duas vezes apenas às 12 horas, e as outras 20 vezes ocorrem em horários diferentes..."
10023030-76 = "Entre as 11 e as 12 horas, os ponteiros não se sobrepõem, então..."
10023030-78 = "Oh... Como esperado da C&C, que capacidade de dedução surpreendente! Então, você já sabe o resto?"
10023030-82 = "Bem... #n\"E meio passo. O lugar onde a lua não alcança, a dança parada e o lado oculto de Antikythera\"."
10023030-83 = "\"Irei até a espada que nunca foi concedida, luxuosa, porém infeliz\", não é?"
10023030-84 = "Meio passo, meio passo... Acho que isso também se refere ao tempo."
10023030-85 = "Meio passo... metade..."
10023030-86 = "Ah! Será que não são 30 minutos?"
10023030-87 = "Yuzu-chan, você sabe que horas os ponteiros do relógio se sobrepõem, ficando em torno de 30 minutos?"
10023030-89 = "Nesse caso, seria entre 5:27 e 7:38... talvez?"
10023030-90 = "Isso significa que o ladrão vai invadir nesse horário?"
10023030-91 = "Mas ainda não entendemos \"o lugar onde a lua não alcança, a dança parada e o lado oculto de Antikythera\"... O que isso poderia significar?"
10023030-96 = "Antikythera... Antikythera..."
10023030-97 = "Hmm!?"
10023030-98 = "Você tem alguma ideia sobre isso?"
10023030-99 = "N-não, nada! Falar sobre o lado oculto de Antikythera é algo realmente absurdo. No entanto... se for sobre \"uma espada que nunca foi concedida, luxuosa, porém infeliz\", eu tenho uma ideia."
10023030-100 = "Provavelmente... trata-se da obra de arte que será exibida a partir de depois de amanhã."
10023030-101 = "É esta aqui."
10023030-106 = "……！"
10023030-107 = "É uma pintura de uma cerimônia de investidura. #nRetrata a cena em que um cavaleiro recebe uma espada de seu senhor."
10023030-108 = "Se for uma espada retratada em uma pintura, não se encaixaria em \"nunca foi concedida\"?"
10023030-109 = "Nesse sentido, também poderíamos dizer que ela é \"infeliz\"."
10023030-111 = "Agora que você mencionou...?"
10023030-112 = "……"
10023030-114 = "Esta pintura é uma peça valiosa que será leiloada, então deve haver muitos interessados."
10023030-115 = "Ah, pensar que alguém visaria esta pintura tão preciosa... #nSe não fosse pela ajuda de vocês, eu só estaria assistindo enquanto ela era roubada sem poder fazer nada."
10023030-116 = "Já que descobrimos o alvo, gostaria que vocês protegessem esta pintura com todas as suas forças..."
10023030-117 = "Eh? #nNão existem outros itens valiosos...?"
10023030-118 = "Não, não! O mistério da carta de aviso foi resolvido, então basta proteger isto! #nAh, ah, ah, aquele \"Ladrão da Benevolência\" idiota..."
10023030-119 = "Ele nem deve sonhar que vocês, tão competentes, estariam aqui!"
10023030-120 = "Ahaha. S-será?"
10023030-121 = "Mas..."
10023030-125 = "É-é um prazer poder ajudar..."
10023030-126 = "Missão concluída! #nAgora é a missão contínua de proteger a pintura!"
10023030-130 = "E, peço desculpas pelo incômodo, mas gostaria de pedir algo adicional a vocês..."
10023030-131 = "……O que seria?"
10023030-132 = "Poderiam cuidar da segurança desta mansão pelos próximos três dias?"
10023030-133 = "Tudo bem, mas... e se a solução da carta de aviso estiver errada?"
10023030-134 = "Claro, não posso negar a possibilidade de o ladrão ter outro alvo. #n...Mas, bastaria que vocês o capturassem."
10023030-135 = "O \"Ladrão da Benevolência\" é famoso por ser esquivo, mas diante da habilidade da C&C, ele não passa de uma criança. #nAh, ah, ah, não é verdade?"
10023030-136 = "Por favor, eu insisto. Pagaremos uma recompensa generosa... vejamos,"
10023030-137 = "Que tal este valor?"
10023030-141 = "!!!??"
10023030-143 = "(S-sério mesmo, esse valor todo...?)"
10023030-144 = "(Dá para comprar um Pricestation Pro7 para cada uma... e ainda a série ZBOX Z! Não, não, dá para comprar dois de cada e ainda sobra troco!)"
10023030-145 = "(O que a gente faz? Midori!?)"
10023030-146 = "(Não me pergunta!)"
10023030-148 = "[ns] (...Primeiro, vamos nos acalmar.)"
10023030-150 = "[ns] \"Poderia nos dar um momento para discutirmos entre nós?\""
10023030-151 = "Ah, peço perdão pela falta de consideração. Vou me retirar, então."
10023030-155 = "Ahhh... Obrigada, Sensei. #nMinha cabeça estava prestes a explodir..."
10023030-156 = "O-o que faremos, Sensei? #n\"Sete Prisioneiros\"... isso já está fora do nosso alcance..."
10023030-157 = "Quero ir para casa... para o meu armário... meu lar espiritual..."
10023030-158 = "Pessoal, por que estão reagindo assim...?#nAlice, o que devemos fazer agora...?"
10023030-159 = "[s3] \"Primeiro, vamos decidir o que fazer com o pedido?\"\n[s4] \"Devemos contar a verdade e recusar?\""
10023030-160 = "……Se recusarmos o pedido, o que vai acontecer exatamente……?"
10023030-161 = "……Se recusarmos o pedido, o que vai acontecer exatamente……?"
10023030-162 = "Provavelmente... o cliente vai reclamar.#nSe dissermos agora que era mentira, pode virar um problema para toda a Millennium..."
10023030-163 = "S-se isso acontecer, a senpai Neru também vai ficar furiosa... né?"
10023030-164 = "Não quero nem imaginar..."
10023030-166 = "Mas Momoi! Esta é uma missão dada à Alice e às outras!#nVocê mesma disse que uma missão aceita deve ser concluída até o fim."
10023030-167 = "Mesmo assim, podemos simplesmente desistir...?"
10023030-168 = "A-Alice...! B-bem, é claro que você tem razão, mas...!"
10023030-169 = "Mas... isso é pesado demais para nós..."
10023030-170 = "[s] \"Às vezes, pode ser necessário ir contra a missão.\""
10023030-171 = "Sensei?"
10023030-172 = "O que... você quer dizer com isso?"
10023030-173 = "[s] \"Não precisamos necessariamente lutar contra o ladrão, não é?\""
10023030-174 = "Não precisamos... lutar?"
10023030-175 = "Acho que entendi o que o Sensei quer dizer!"
10023030-176 = "Basicamente, se o ladrão não roubar nada, nós vencemos, certo?"
10023030-179 = "!!!"
10023030-181 = "Já chegamos até aqui e o Sensei está com a gente.#nAlém disso, os equipamentos de segurança da mansão são incríveis, né?"
10023030-182 = "Não precisamos lutar de frente com o ladrão nem capturá-lo.#nSó precisamos garantir que o tesouro não seja roubado!"
10023030-183 = "Pensando bem, talvez ainda haja uma chance..."
10023030-184 = "Nós... já temos experiência lutando contra a C&C...#ne já passamos por batalhas ainda mais difíceis..."
10023030-185 = "Se usarmos isso a nosso favor..."
10023030-186 = "[s] \"Se tiverem sucesso, podem receber uma recompensa. Mas há riscos.\""
10023030-187 = "(É verdade, com essa recompensa... o nosso Departamento de Desenvolvimento de Jogos...)"
10023030-188 = "Então, está decidido?"
10023030-189 = "Ai... será que vai dar certo mesmo?"
10023030-190 = "Nós conseguimos!#nAlém disso, essa não é uma chance de deixar a C&C em dívida conosco?"
10023030-191 = "Originalmente, era para a C&C ter aceitado isso!"
10023030-193 = "Alice vai dar o seu melhor!#nSe estivermos com o Sensei, somos invencíveis!"
10023030-197 = "……Vejo que tomaram uma decisão.#nObrigada por aceitarem."
10023030-198 = "Então, como mencionei anteriormente, gostaria que protegessem esta mansão e as obras de arte por 3 dias."
10023030-199 = "Três dias são suficientes?"
10023030-200 = "Sim. Apenas durante o período do evento que começa amanhã."
10023030-201 = "No primeiro dia teremos uma festa para convidados, no segundo a exposição das obras.#nE no último dia... pretendemos realizar o leilão das peças."
10023030-202 = "……O-o ladrão virá em algum momento desses três dias…… é isso……"
10023030-203 = "Sim, provavelmente.#nNo primeiro dia, gostaria que protegessem o local enquanto servem como garçons."
10023030-205 = "Hã, garçons...?"
10023030-206 = "Sim. Como diz o ditado, a melhor forma de esconder uma árvore é na floresta, não é?#nAcho ideal para se misturarem ao local sem revelar suas identidades.#nAliás, vocês já estão vestidas de forma perfeita para isso."
10023030-207 = "Por precaução, gostaria de avisar... existe a possibilidade de o ladrão estar infiltrado entre os convidados.#nNão baixem a guarda, por favor, tenham muito cuidado."
10023030-209 = "(Tem algo que não está me cheirando bem...)"
10023030-210 = "(Será que a resposta da carta de aviso está realmente correta...?#n　Ainda parece haver outras possibilidades...)"
