[translation]
10020040-5 = "……今回は、「あの」シロコさんは見えませんね。"
10020040-6 = "んだね。もしかして、諦めたとか？"
10020040-7 = "そこまでは分かりません……で、ですが油断は禁物です！"
10020040-9 = "そういえば、皆に良い知らせがあるよ。#n船の修理作業が……まもなく完了しそうでね。"
10020040-10 = "そ、そうですか……！ありがとうございます！みなさん、本当にお疲れ様でした！！"
10020040-11 = "いやぁ～、正直かなり心配してたけど……よかったよかった。 "
10020040-15 = "うん。ハッキングした箱舟の演算装置のおかげで、思ったよりすぐ終わった。"
10020040-16 = "はい！この演算装置、素晴らしい性能でした！"
10020040-17 = "あとは……第4エリアの「次元エンジン」を破壊できれば、箱舟の「自爆シーケンス」を作動できるはず。"
10020040-18 = "自爆まで余裕があると思うから、その間にウトナピシュティムを再起動させて脱出すれば大丈夫。"
10020040-19 = "ここからはタイミングが肝心だよ。気を引き締めていこう。"
10020040-20 = "では、そちらの健闘を祈る。"
10020040-25 = "不幸中の幸いと言いますか……リオ、あなたの提案してくれた「脱出装置」の出番はなさそうですね。"
10020040-26 = "……そうね。"
10020040-41 = "私たちは「特別エリア」の制御室前で交戦中です！"
10020040-42 = "ほんっとにもう、しつこいわね！"
10020040-43 = "まだ抵抗されていますが、破壊完了まで時間の問題です！"
10020040-44 = "ほらほら、その程度じゃ足止めにもなんないよ～？"
10020040-45 = "制御室の破壊が完了次第、またご連絡します！"
