[translation]
10034080-1 = "Epílogo; Não é o suficiente"
10034080-4 = "[log=???]\"Tem certeza de que quer deixar assim?\"[/log]"
10034080-9 = "……."
10034080-10 = "Ah, desculpe. Mesmo tendo perguntado, acabei me distraindo..."
10034080-16 = "Por isso, fiquei pensando se só o \"Café de Casa Assombrada\" seria o bastante."
10034080-17 = "Ah, não é que a ideia da Airi seja ruim!"
10034080-18 = "Mas, se vamos abrir um café para o festival escolar, não acha que falta um toque a mais?"
10034080-19 = "Algo mais único e interessante... Ah, o que é isso que a Airi está carregando?"
10034080-21 = "……Isso? Um teclado?"
10034080-23 = "É isso, Airi!"
10034080-24 = "Que tal um café de casa assombrada com banda? Não seria algo inédito?"
10034080-26 = "Um café de casa assombrada com banda……."
10034080-27 = "Hmm……."
10034080-31 = "……."
10034080-32 = "……Hehe."
10034080-33 = "……Airi?"
10034080-34 = "Aconteceu alguma coisa……?"
10034080-35 = "Ahaha…… não, nada."
10034080-36 = "No fim das contas, acho que vou deixar como está mesmo!"
10034080-41 = "Entendi, bem, se a Airi diz isso!"
10034080-42 = "De repente, você parece bem mais aliviada."
10034080-43 = "Então boa sorte! Vou dar uma passada aí onde vocês estão!"
10034080-44 = "Ah, e vou avisar meus amigos também. Estou ansioso por isso."
10034080-46 = "……Sim, pode esperar!"
10034080-50 = "Ah, preciso descer na próxima."
10034080-51 = "Então, até mais!"
10034080-53 = "Tchau, tchau."
10034080-54 = "Até amanhã!"
10034080-56 = "Sim!!"
10034080-60 = "……Ufa."
10034080-61 = "Ué, essa situação... parece que já aconteceu antes."
10034080-63 = "Airi! Por aqui, por aqui!!"
10034080-64 = "……?"
10034080-68 = "Por que está aí parada? Vamos, vamos ensaiar uma última vez antes da apresentação!"
10034080-69 = "Não precisa ter tanta pressa assim."
10034080-70 = "Hã?"
10034080-71 = "E se não der tempo!? Você não vai conseguir comer o Semla!?"
10034080-72 = "Já faz uma semana de treinos intensos. Todos, preparem-se. Vamos tocar um rock de fazer sangrar..."
10034080-73 = "Não, não, se a gente sangrar não vai dar para tocar..."
10034080-74 = "Mas, de qualquer forma, é hora de mostrar o resultado do nosso treino."
10034080-75 = "……Vamos, Airi."
10034080-77 = "……."
10034080-78 = "Airi?"
10034080-79 = "Vamos, não temos mais tempo!"
10034080-80 = "Para nós, pode ser um pequeno passo, mas será um dia que vai abalar o mundo das bandas de Kivotos!"
10034080-81 = "…………."
10034080-85 = "\"Tem certeza de que quer deixar assim?\""
10034080-94 = "\"……Agora está tudo bem.\""
10034080-97 = "-ive aLIVE!"
