[translation]
10031010-1 = "第1話;協力要請"
10031010-12 = "（その後、話を仕切り直し……）"
10031010-14 = "キキキッ。この場で私の提案が受け入れられなかったのは残念だが、いずれ時が経てば引き受けてくれるはず。"
10031010-15 = "実は、すでに後悔しているのではないか？"
10031010-16 = "だが、安心してくれ。#n返事は今マコト様が計画している超巨大イベントの後で構わない。"
10031010-17 = "[s] \"超巨大イベント……？\""
10031010-18 = "あ、ここであの話を出すんですね！#nさすがマコト先輩！"
10031010-19 = "……はっ！もしかして、さっきまでの漫才みたいなやり取りは……#nすべてここに繋げるつもりだったんですか！？"
10031010-20 = "ん……？"
10031010-21 = "……ん？あ、ああ、そうだ。まさにそうだとも！"
10031010-22 = "どう見ても、思ってすらなかった顔じゃないですか。"
10031010-23 = "それより……本当にやるんですか、アレ。"
10031010-24 = "当たり前だ、イロハ！#nもうここまで準備を進めたのだ！"
10031010-25 = "あの計画で、万魔殿の名声をゲヘナ中……いや、キヴォトス中に広めるぞ！"
10031010-26 = "うん～イブキもすごく楽しみ～"
10031010-27 = "[ns] \"えっと……何を準備しているの？\""
10031010-28 = "クククッ……実は5日後、我々万魔殿は近日中に完成する新議事堂で「ゲヘナ特別パーティー」を開催する予定だ。"
10031010-29 = "このパーティーで、ゲヘナ中の生徒が知ることになるだろう！"
10031010-33 = "我々万魔殿が、いかに素晴らしい組織なのか！そして、あの愚かな風紀委員会の奴らと比べて、どれほど器が大きいのかを！キキキッ！！"
10031010-36 = "……はぁ、私から補足しておきます。"
10031010-37 = "万魔殿は毎年、バレンタインの季節に様々な有力者を招待してパーティーを開いてきました。"
10031010-38 = "そこで今年は、去年や一昨年よりも規模の大きい、特別なものにしたいとマコト先輩が言い出しまして……"
10031010-39 = "これまで開催してきたパーティーとは、根本的に違うのだ！"
10031010-40 = "何せ今年は、シャーレの先生が居るのだからな！"
10031010-44 = "[ns] \"……私？\""
10031010-45 = "ああ、そうだとも。先生の協力さえ得られれば、今回のパーティーは過去に類を見ないほど最強になるだろう！"
10031010-46 = "このマコト様の政治力がいかに優れているのか！#nそれを万人に知らせる絶好の機会！"
10031010-48 = "ひゅ～っ！#n先生を利用して私利私欲を満たそうとするなんて、マコト先輩らしいですね！"
10031010-49 = "ふ～ん。マコトちゃんはパーティーを最強にして、どうするの？"
10031010-51 = "いや、気にするところそこですか……"
10031010-52 = "キキッ。先生よ、安心してほしい。"
10031010-53 = "先生が手伝ってくれる以上、もはやパーティーの成功は約束されたも同然！"
10031010-54 = "そしてゲヘナの全生徒は私を敬うようになり、先生は私を見直し……#nこのマコト様とシャーレの同盟が成立すること間違いなしだ！"
10031010-55 = "まさに前途洋々！キキキッ！"
10031010-56 = "[s] \"説得したい相手の私にお願いしちゃうんだ……？\""
10031010-57 = "……ですよね。指摘されるとは思わなかったんですか、マコト先輩。#nいくら何でも、流石に先生も呆れて……"
10031010-58 = "[s] \"まあ、手伝うよ。\""
10031010-59 = "うむ、そう言ってくれると思っていた！"
10031010-60 = "……！？ほ、本当にいいんですか？"
10031010-61 = "[s9] \"生徒のお願いは、できるだけ聞いてあげたいからね。\"\n[s10] \"ゲヘナのパーティーと聞いて、ちょっと気になったんだ。\""
10031010-64 = "そう、ですか……"
10031010-66 = "良かったね～イロハちゃん！"
10031010-67 = "ふ～ん……"
10031010-69 = "わあ、先生が手伝ってくれるの～？やった～！"
10031010-70 = "イブキも先生と一緒にパーティーの準備頑張る！"
10031010-71 = "クククッ、うまくいったな。"
10031010-72 = "よし！[USERNAME]先生よ！#n残り5日間……よろしく頼むぞ！キキキッ！！"
10031010-74 = "（こうしてゲヘナのバレンタインパーティーを手伝うことになった）"
