[translation]
10036140-1 = "Como o esquadrão se diverte com jogos (2)"
10036140-3 = "Oh!#nParabéns por completar o nível iniciante!"
10036140-4 = "Hmph."
10036140-5 = "Aquilo nem chega a ser um treinamento."
10036140-9 = "Pessoal, podemos ir para a próxima?"
10036140-15 = "Sem problemas."
10036140-16 = "É divertido jogar com todo mundo."
10036140-17 = "E-hehe... Estamos um passo mais perto da última edição da \"BiBi\"...!"
10036140-18 = "Talvez, só talvez, a gente realmente consiga o prêmio...!"
10036140-19 = "Pode ter sido só sorte."
10036140-20 = "A-ah... Como eu pensei, nós não..."
10036140-21 = "Não, é que... foi uma brincadeira."
10036140-27 = "A Misaki..."
10036140-28 = "Fez uma brincadeira...?"
10036140-29 = "O-o senso de humor da Misaki é..."
10036140-30 = "C-cala a boca!#nAinda tem o próximo jogo, não tem? Vamos logo."
10036140-31 = "Já que estão prontas, vamos começar o nível intermediário!"
