[translation]
10031010-1 = "Episódio 1; Pedido de Cooperação"
10031010-12 = "（Depois disso, o assunto foi retomado...）"
10031010-14 = "Kikiki. É uma pena que minha proposta não tenha sido aceita aqui, mas tenho certeza de que você aceitará com o passar do tempo."
10031010-15 = "Na verdade, você já não está se arrependendo?"
10031010-16 = "Mas não se preocupe. #nA resposta pode ficar para depois do super evento que a Makoto-sama está planejando agora."
10031010-17 = "[s] \"Super evento...?\""
10031010-18 = "Ah, então é por isso que você mencionou aquilo! #nComo esperado da veterana Makoto!"
10031010-19 = "......Hã! Será que aquela troca de farpas de agora há pouco... #ntudo isso era para levar a este momento!?"
10031010-20 = "Hm...?"
10031010-21 = "......Hm? Ah, sim, é isso mesmo! Exatamente!"
10031010-22 = "Não importa como se olhe, essa é a cara de quem nem tinha pensado nisso."
10031010-23 = "Mais importante... você vai mesmo fazer aquilo?"
10031010-24 = "Claro que sim, Iroha! #nJá avançamos com os preparativos até aqui!"
10031010-25 = "Com esse plano, vamos espalhar a fama do Pandemonium por toda Gehenna... não, por todo Kivotos!"
10031010-26 = "Uhum~ A Ibuki também está muito animada~"
10031010-27 = "[ns] \"Bem... o que vocês estão preparando?\""
10031010-28 = "Kukuku... Na verdade, daqui a 5 dias, nós do Pandemonium realizaremos uma \"Festa Especial de Gehenna\" no novo edifício do conselho que será concluído em breve."
10031010-29 = "Com esta festa, todos os alunos de Gehenna saberão!"
10031010-33 = "O quão incrível é a nossa organização, o Pandemonium! E o quão grande é a nossa capacidade, comparada àqueles tolos do Comitê Disciplinar! Kikiki!!"
10031010-36 = "......Haa, eu vou complementar."
10031010-37 = "Todos os anos, na época do Dia dos Namorados, o Pandemonium convida várias figuras influentes para realizar uma festa."
10031010-38 = "Então, este ano, a veterana Makoto decidiu que queria fazer algo especial, em uma escala maior do que no ano passado ou no anterior..."
10031010-39 = "É fundamentalmente diferente das festas que realizamos até agora!"
10031010-40 = "Afinal, este ano, o Sensei do Schale está aqui!"
10031010-44 = "[ns] \"...Eu?\""
10031010-45 = "Ah, sim, exatamente. Se conseguirmos a cooperação do Sensei, esta festa será a mais forte e sem precedentes!"
10031010-46 = "O quão excelente é o poder político desta Makoto-sama! #nEsta é a oportunidade perfeita para mostrar a todos!"
10031010-48 = "Uau! #nUsar o Sensei para satisfazer seus próprios interesses, é bem a sua cara, veterana Makoto!"
10031010-49 = "Hum. Makoto-chan, o que você vai fazer tornando a festa a mais forte?"
10031010-51 = "Não, é isso que você vai perguntar..."
10031010-52 = "Kiki. Sensei, fique tranquilo."
10031010-53 = "Já que o Sensei vai ajudar, o sucesso da festa já está garantido!"
10031010-54 = "E todos os alunos de Gehenna passarão a me respeitar, o Sensei vai me ver com outros olhos... #nNão há dúvidas de que a aliança entre esta Makoto-sama e o Schale será estabelecida!"
10031010-55 = "O futuro é brilhante! Kikiki!"
10031010-56 = "[s] \"Você está pedindo ajuda justamente para a pessoa que quer convencer...?\""
10031010-57 = "......Pois é. Você não achou que ele notaria, veterana Makoto? #nPor mais que seja, o Sensei deve estar pasmo..."
10031010-58 = "[s] \"Bem, eu ajudo.\""
10031010-59 = "Hum, eu sabia que você diria isso!"
10031010-60 = "......!? S-sério mesmo?"
10031010-61 = "[s9] \"Porque quero atender aos pedidos dos meus alunos sempre que possível.\"\n[s10] \"Fiquei um pouco curioso ao ouvir sobre a festa de Gehenna.\""
10031010-64 = "É, é mesmo..."
10031010-66 = "Que bom, Iroha-chan!"
10031010-67 = "Hum..."
10031010-69 = "Uau, o Sensei vai ajudar? Oba~!"
10031010-70 = "A Ibuki também vai se esforçar nos preparativos da festa com o Sensei!"
10031010-71 = "Kukuku, deu certo."
10031010-72 = "Muito bem! [USERNAME] Sensei! #nNos próximos 5 dias... conto com você! Kikiki!!"
10031010-74 = "（Assim, acabei ajudando na festa de Dia dos Namorados de Gehenna）"
