[translation]
1003420-1 = "A determinação de uma Yamato Nadeshiko"
1003420-3 = "Seja muito bem-vindo, Sensei!"
1003420-4 = "Hoje, eu gostaria de mostrar os resultados do meu treinamento culinário... por isso pedi um pouco do seu tempo."
1003420-5 = "Então, vamos logo para a sala de economia doméstica!"
1003420-6 = "Sala do Clube de Treinamento"
1003420-7 = "Chegamos—"
1003420-8 = "Espere, por que a sala de economia doméstica está tão bagunçada!?"
1003420-23 = "Além do treinamento culinário, nós a usamos para preparar refeições, mas... por que será que está assim..."
1003420-24 = "Mimori-chan... ah, o Sensei do Schale também está aqui, olá. #nÉ que... parece que o Grupo Chimi fez um festival aqui ontem à noite..."
1003420-25 = "Vai levar muito tempo para limpar agora, então talvez não dê para usar hoje..."
1003420-26 = "..."
1003420-27 = "Não, está tudo bem."
1003420-44 = "Mimori-chan!?"
1003420-45 = "Vou limpar agora mesmo. #nSe for só isso, terminarei rapidamente."
1003420-46 = "[s] \"Concordo. Se fizermos juntos, terminaremos rápido.\""
1003420-47 = "Hã!? Não... eu não poderia incomodar o Sensei com isso..."
1003420-48 = "Eu farei isso... por favor, deixe comigo! Esta é a sala de economia doméstica do nosso Clube de Treinamento. Estou acostumada com os lugares e os procedimentos de limpeza."
1003420-49 = "Além disso... como uma Yamato Nadeshiko, eu deveria ter percebido que o Grupo Chimi faria um festival aqui com antecedência..."
1003420-50 = "Eu deveria ter controlado a situação antes e deixado tudo limpo!"
1003420-51 = "[s] \"Isso é coisa de Yamato Nadeshiko!?\""
1003420-52 = "Ma-mas..."
1003420-53 = "Como eu não me preparei com antecedência, as coisas ficaram assim..."
1003420-54 = "E mesmo assim, causar esse transtorno ao Sensei é..."
1003420-55 = "[s1] \"Não se preocupe, Mimori.\"\n[s2] \"Eu quero ajudar a Mimori.\""
1003420-58 = "..."
1003420-59 = "Se o Sensei insiste tanto..."
1003420-60 = "...Conto com a sua ajuda, Sensei."
1003420-61 = "Bem, como já tomamos bastante tempo..."
1003420-62 = "Eu, Mizuha Mimori, como vice-presidente do Clube de Treinamento..."
1003420-63 = "Hoje vou me esforçar ainda mais! Vou fazer isso com toda a minha determinação!"
1003420-64 = "[s] \"Você já se esforça tanto e ainda vai fazer mais!?\""
1003420-65 = "Sim! #nPara me tornar uma Yamato Nadeshiko maravilhosa, preciso sempre buscar a melhoria!"
1003420-66 = "Por isso, hoje... vou usar \"aquilo\"!"
1003420-73 = "[ns] \"Um, um avental!?\""
1003420-74 = "Então, vamos lá!"
1003420-77 = "(Fiquei tão impressionado com o modo determinado (?) da Mimori que nem tive chance de ajudar...)"
1003420-84 = "Ufa... bom trabalho, Sensei."
1003420-85 = "Hã? Eu limpei quase tudo sozinha?"
1003420-86 = "Fufu, foi graças à sua presença, Sensei."
1003420-87 = "Mas... é verdade. #nTalvez tenha sido graças a isto também."
1003420-92 = "...Que combinou comigo? Não diga essas coisas."
1003420-93 = "Ai, meu Deus... Sensei, por favor, não brinque comigo."
1003420-94 = "Você não está brincando...?"
1003420-95 = "..."
1003420-96 = "Vo-você deve estar cansado. #nPrimeiro, vamos mudar de lugar! Sim, por aqui, por favor!"
1003420-99 = "Espere um momento, por favor. Vou preparar um chá."
1003420-112 = "...Aqui está. #nJá que estamos aqui, trouxe também alguns doces japoneses."
1003420-113 = "Na verdade... eu queria que você me visse preparando estes doces..."
1003420-120 = "...E então? Estão do seu agrado?"
1003420-121 = "[s] \"Estão muito gostosos. O chá também tem um aroma maravilhoso.\""
1003420-122 = "Fufu, que bom."
1003420-123 = "Eh? Este avental?"
1003420-124 = "……。"
1003420-125 = "Este é... o avental que comprei quando li mangá pela primeira vez e sonhei com o meu eu ideal."
1003420-126 = "Eu cuidei dele por muito, muito tempo... é o meu tesouro."
1003420-127 = "[s] \"Pensei que fosse novo...\""
1003420-128 = "Fufu, é mesmo?#nSe olhar bem, verá que tem bolinhas e marcas de remendos em partes pequenas."
1003420-129 = "Mas, para mim... este é um avental insubstituível."
1003420-130 = "É confortável de usar e, acima de tudo, sinto uma sensação de segurança quando o visto..."
1003420-131 = "Limpar, lavar, cozinhar, costurar, ler mentes... sinto que posso fazer qualquer coisa."
1003420-132 = "[s] \"...Ler mentes?\""
1003420-133 = "Ah, i-isso!"
1003420-134 = "Não! Le... leitura!"
1003420-136 = "(Tentei perguntar sobre a leitura de mentes algumas vezes, mas ela mudou de assunto imediatamente...)"
1003420-138 = "Como comprei há muito tempo, na época ele era tão grande que eu precisava dobrar a barra para não arrastar no chão."
1003420-139 = "Mas... eu dizia a mim mesma que, quando este avental servisse perfeitamente, eu certamente estaria mais perto do meu sonho.#nFoi assim que continuei meu treinamento."
1003420-140 = "Fufu... que nostálgico. Pensando agora, sinto um pouco de vergonha."
1003420-141 = "[s] \"Não precisa ter vergonha.\""
1003420-142 = "Sério... você acha?"
1003420-143 = "Naquela época, eu achava que poderia realizar qualquer coisa."
1003420-144 = "Agora, o avental está no tamanho perfeito, mas..."
1003420-145 = "Não sei dizer se me tornei a pessoa com quem a minha versão mais jovem sonhava."
1003420-147 = "(No momento em que eu ia dizer que a Mimori já se esforça o suficiente――)"
1003420-148 = "Ah, Sensei. Você não ia dizer agora que eu \"já me esforço o suficiente\"?"
1003420-149 = "[s] \"Como você sabia!?\""
1003420-150 = "Fufu. Talvez seja a confiança de que o Sensei diria algo assim...?"
1003420-151 = "[s3] \"Então esse avental tem algum segredo!?\"\n[s4] \"É por causa do avental que sua leitura de mentes está mais forte que o normal!?\""
1003420-154 = "S-sim!? Eu não disse nada disso...!"
1003420-158 = "Não me olhe com essa cara de quem \"entendeu tudo\"...!"
1003420-159 = "Sensei? Sensei??"
1003420-161 = "(Depois disso, passei o resto do tempo tomando chá com a Mimori)"
