[translation]
1003602-1 = "聖堂の管理者"
1003602-2 = "トリニティ聖堂内部"
1003602-3 = "（とある用事でトリニティを訪れ、ヒナタのメッセージを思い出して聖堂へと向かった）"
1003602-4 = "（聖堂の中は広々としており、生徒の姿は見当たらない）"
1003602-5 = "ガタンッ"
1003602-6 = "[ns] \"……？\""
1003602-7 = "ガタッ、ガタガタッ……"
1003602-8 = "ドンッ！"
1003602-9 = "（聖堂の片隅、かすかに開いている扉から音が聞こえてくる）"
1003602-10 = "[ns1] \"……誰かいるのかな？\"\n[ns2] 音がする方へ行ってみる。"
1003602-14 = "（その扉の向こう側には廊下が続いており、さらにその先は倉庫になっていた）"
1003602-18 = "……？あれ、先生……？"
1003602-19 = "[s] \"あ、ヒナタ。\""
1003602-20 = "えっと、き、奇遇ですね？こちらにどんなご用事で……？"
1003602-21 = "いえ、それよりどうやってこの場所に……！？"
1003602-22 = "ここはその、一応部外者の方は入れないところなのですが……？"
1003602-23 = "え、音が聞こえて……？"
1003602-24 = "……扉が開いてた、ですか？"
1003602-25 = "……。"
1003602-26 = "あぁっ！私、通路の扉を開けっ放しのまま……！"
1003602-27 = "うぅ……また私、こんな初歩的なミスを……。"
1003602-28 = "……？"
1003602-29 = "誰にも言わない、ですか……？"
1003602-30 = "え、えっと、そういう問題では無く……！いえ、それ自体はありがたいのですが、その……！"
1003602-31 = "……あ、私ですか？"
1003602-32 = "えっと、見ての通りになってしまうかもですが……。"
1003602-33 = "備品の整理をしていたところ、でして。"
1003602-34 = "聖堂はパッと見た感じですと、さっぱりしていてシンプルな場所に見えるかもしれませんが……"
1003602-35 = "シスターのみなさんの所持品、聖堂に必要な備品、訪れた方々の忘れ物など……結構色んなものがあるんです。"
1003602-36 = "こうして集めてみると、一日に動かさないといけない分だけで数十箱あったりします。"
1003602-37 = "[s3] \"確かにすごい量だね……これ、全部ひとりで？\"\n[s4] \"なるほど、ヒナタがその担当なんだね。すごい。\""
1003602-38 = "あ、えっと、それほどすごいというわけでは……。"
1003602-39 = "あ、えっと、それほどすごいというわけでは……。"
1003602-40 = "ですが、はい。施設の整備、補修。それから物品管理などが私の役割です。"
1003602-41 = "もちろん、他のシスターのみなさんも手伝ってくださるのですが。"
1003602-42 = "とはいえ基本的に、力仕事とかは私がやった方が良いので。"
1003602-43 = "えっ……手伝ってくださるんですか？"
1003602-44 = "え、えっと、そのお申し出はすごくありがたいのですが……。"
1003602-45 = "せ、先生！？"
1003602-49 = "[ns5] \"び、ビクともしない！？\"\n[ns6] \"こ、腰が……っ！\""
1003602-50 = "だ、大丈夫ですか先生！？"
1003602-51 = "だ、大丈夫ですか先生！？"
1003602-55 = "お、お分かりになったかもしれませんが、この箱は見た目以上に重くって……普段、他のシスターの方なら3、4人がかりで持ち上げることが多いんです。"
1003602-56 = "毎回そんな人数にお願いするのもあれなので、基本的には私がやっている……ということでして。"
1003602-57 = "[s7] \"なるほど……本当にすごいね、ヒナタは……。\"\n[s8] \"そ、そっか……ヒナタの長所のひとつだね。\""
1003602-58 = "あ、ありがとうございます。"
1003602-59 = "あ、ありがとうございます。"
1003602-60 = "……そう言ってくださると、何だか嬉しいです。"
1003602-61 = "私はその、他のシスターのみなさんのように、「誰かの話を聞いて心を楽にする」みたいなことは得意でなくって……。"
1003602-62 = "こういったことくらいしか、できないので。"
1003602-63 = "消去法、みたいな感じでしょうか……えへへ……。"
1003602-64 = "[s] \"そんなことは無いよ。\""
1003602-65 = "そう、でしょうか……？"
1003602-66 = "あっ。わ、私ったら、また無駄話を……。"
1003602-67 = "すみません、何だか変な話をしてしまって。"
1003602-68 = "そ、そろそろ外に出ましょうか？案内しますね。"
1003602-69 = "……え？あ、いえいえそんな。"
1003602-70 = "あまり忙しかったわけでもありませんし、気にしないでください。"
1003602-71 = "ちょうど私も、礼拝堂の方へ持っていきたいものがありましたし。"
1003602-72 = "えっと……あ、これですね。"
1003602-73 = "……よっと。"
1003602-74 = "ふぅ。"
1003602-75 = "……では、行きましょうか？"
1003602-78 = "[ns] あの重量を軽々と持ちあげたことに驚きつつ、ヒナタについていく。"
1003602-82 = "ふぅ……これでOKですね。"
1003602-83 = "あぁ、何だか汗をかいてしまいましたね……それほど激しい運動ではなかったのに、結構私汗っかきでして……。"
1003602-84 = "それに先生も汗が……ふふ、先ほど頑張ってくれましたもんね。"
1003602-85 = "あっ、す、すみません先生。こんなに汗をかいた状態で傍になんて、失礼しました……。"
1003602-86 = "でも、さっきまでずっと一緒にいましたし、今更でしょうか……？"
1003602-90 = "……あれ？何だか人だかりが……。"
1003602-91 = "気のせいでなければみなさん、私たちの方を見てます……？"
1003602-92 = "な、何ででしょうね、先生？……先生？顔色が悪いですが、大丈夫ですか？"
1003602-93 = "……誤解？それは、どういう……。"
1003602-94 = "汗をかきながら、一緒に奥の部屋から出てきたから……？"
1003602-95 = "[s9] \"と、とりあえず今日はありがとう！\"\n[s10] \"今は離れた方が良さそうだから、お疲れ様！\""
1003602-100 = "え、ええっ……！？"
1003602-101 = "せ、先生……！？"
1003602-103 = "（余計な誤解が大きくなるのを防ぐため、素早くその場を離れた）"
1003602-104 = "（そしてヒナタは結局、最後まで誤解の内容について見当がついていないようだった）"
