[translation]
10031070-1 = "第7話;パーティー当日"
10031070-2 = "（様々な問題を乗り越え、いよいよパーティー当日を迎えた）"
10031070-4 = "ゲヘナ学園・パーティー会場"
10031070-7 = "[ns] \"パーティー開始まで、後3時間か……\""
10031070-22 = "そういえば、あの話って聞いた？"
10031070-23 = "あ、もしかしてすっごく大きい広告出てたやつ？"
10031070-24 = "私も聞いたよ！#n今回のパーティーで一番の目玉だよね！"
10031070-25 = "「風紀委員長のオープニングピアノ演奏！」"
10031070-26 = "ヒナ委員長の演奏が聴けるなんて、楽しみだよね～"
10031070-27 = "でも、万魔殿と風紀委員会って仲が悪かったよね？#nよく万魔殿主催のパーティーで、風紀委員長が演奏することになったね。"
10031070-28 = "私も聞いただけなんだけど、万魔殿の議長が海のような広い心で、関係を進展させるために招待したんだって。"
10031070-30 = "[ns] \"マコト、さりげなくそんな噂を……\""
10031070-31 = "……はぁ、本当に気が滅入ります。"
10031070-36 = "訓練や万魔殿の横暴に振り回されている間に、偏向報道をしていたとは……"
10031070-37 = "あのタヌキは一度こうと思ったら、私たちの聞く耳を持ちませんからね……"
10031070-38 = "……はぁ。#n今さらですけど、委員長がきっぱり断っていれば……"
10031070-39 = "[s] \"アコ、大丈夫？\""
10031070-40 = "あ、先生……お疲れ様です。先にいらしてたんですね。"
10031070-41 = "正直、先生が万魔殿に協力していることに対しては、文句の一つや二つ言いたいところですが……"
10031070-42 = "[s1] \"まあ、生徒の頼みだからね。\"\n[s2] \"パーティーで何か企んでいるわけじゃなさそうだったし。\""
10031070-45 = "同じ生徒である以上、協力するのは当然……ということでしょうか？"
10031070-46 = "……まあ、先生の立場を考えたら理解はできます。"
10031070-47 = "そのせいで、風紀委員会が割りを食っていますが……"
10031070-48 = "[s] \"風紀委員会の力を信じてるからね。\""
10031070-49 = "……はあ。#n信頼は嬉しいですが、厄介事を押し付けられるのは困りものですね。"
10031070-50 = "それで、いかがでしたか？万魔殿を直接相手にした感想は？"
10031070-51 = "あの無茶苦茶な集団を相手にして……#n少しは私たちの気持ちが理解できましたか？"
10031070-52 = "[s] \"ま、まあ……みんな個性的な子たちだね。\""
10031070-53 = "個性的、ですか……物は言いようですね。"
10031070-54 = "[s] \"そ、それよりアコ、その格好は……\""
10031070-55 = "あ、これですか。"
10031070-56 = "決して乗り気だったわけではありませんが……"
10031070-57 = "委員長を補佐するためにも、場に応じた格好をしなくてはいけませんから。"
10031070-58 = "そうですね……さながらパーティーに忍び込むスパイ……ですかね。"
10031070-59 = "ええ、そういうコンセプトですので。"
10031070-60 = "[s] \"うん、よく似合ってるよ。\""
10031070-61 = "……なっ。"
10031070-62 = "ご、誤解しないでください。#nこれは本当に、業務の一環で……"
10031070-63 = "……って、何を慌てているんでしょう。"
10031070-64 = "せ、先生が変なことを言うからです。"
10031070-65 = "[s] \"え！？私のせい！？\""
10031070-66 = "……ふふっ。ですが、せっかく褒めていただいたので、素直に受け取っておきます。"
10031070-67 = "とにかく……このパーティー、油断はできませんね。"
10031070-68 = "とりあえず、どんな事態が発生しても迅速に対応できるよう、風紀委員会の部隊を配置しておきました。"
10031070-83 = "これだけ警戒しても、不安が残るのはなぜでしょう？"
10031070-84 = "……万魔殿が主催し、風紀委員会までもが参加するパーティー。相当な怖いもの知らずでなければ、問題を起こさないはず……だとは思いますが。"
10031070-85 = "万魔殿主催というのが、引っかかっているんですかね。"
10031070-86 = "まったく、最後まで油断はできません。"
10031070-87 = "[s3] \"でも、大丈夫じゃないかな？ここまで来た以上……\"\n[s4] \"何があっても、風紀委員会が何とかしてくれるでしょ？\""
10031070-90 = "うーん、しかし……"
10031070-91 = "[s] \"そういえばアコ、ヒナはどこに居るの？\""
10031070-92 = "あ、それが……委員長は用事があるようで……"
10031070-93 = "少し、遅れるそうです。"
10031070-94 = "クククッ。よく来てくれた、[USERNAME]先生。#nそれと、行政官も。"
10031070-105 = "こんにちは～！先生！アコ先輩～！"
10031070-107 = "ふん……あなた達ですか。"
10031070-111 = "[ns] \"こんにちは、二人もよく似合ってるね。\""
10031070-113 = "キキッ！ああ、よくぞ気づいてくれた！#n今日のために、この私の威厳に相応しいドレスをオーダーしたのだ！"
10031070-114 = "イブキのドレスはね～マコト先輩が選んでくれたんだ～#nねえ、先生、可愛い～？"
10031070-115 = "[s] \"イブキもドレスも全部可愛いよ！\""
10031070-116 = "ほんと？ありがとう、先生！"
10031070-117 = "クククッ……そうだ。#nイブキの魅力はドレスと合わさって、いつもの150倍増しになっている。"
10031070-118 = "気をつけるんだな、[ruby=あまう]天雨[/ruby]アコ。#nあまりの可愛さに卒倒しても知らないぞ。"
10031070-120 = "……あ、はい。#nあなたはともかく、イブキちゃんが可愛いのは事実ですからね。"
10031070-121 = "わぁ！アコ先輩、ありがとう！"
10031070-122 = "ただ本心を言っただけですからね……ふふっ。"
10031070-123 = "キキキキッ！まあ、イブキの可愛さは当然として……"
10031070-124 = "[ruby=そらさき]空崎[/ruby]ヒナ……風紀委員長の姿が見えないな。"
10031070-125 = "そ、それは……"
10031070-126 = "後2時間ほどで、オープニング演奏が始まるというのに。"
10031070-127 = "こんな時間になっても姿を現さないとは……"
10031070-128 = "キキッ。#n風紀委員長め、やはり怖くて逃げたんじゃないのか？"
10031070-129 = "……なんて言いました？"
10031070-130 = "そうでもなければ、こんな時間まで現れないのはおかしいだろう？"
10031070-131 = "本来なら、とっくにリハーサルを終えて控え室に居る時間だぞ？"
10031070-132 = "そ、それはそうかもしれませんが……。"
10031070-133 = "委員長が逃げるわけないじゃないですか！#n他の誰でもない、風紀委員長ですよ！"
10031070-134 = "キキッ。相変わらず威勢だけはいいな、アコ行政官。"
10031070-135 = "いくら責任感が強くとも、逃げ出したくなる日くらいあるだろう。"
10031070-136 = "努力したところで自分にはできないことがあると知れば……#nあの風紀委員長でも逃げるかもしれないぞ？"
10031070-140 = "[ns] \"自分にはできないことって……？\""
10031070-141 = "キキキッ！よくぞ聞いてくれた！"
10031070-142 = "我々万魔殿のスパイは非常に優秀なのだ！#n風紀委員会など相手にならないくらいにな！"
10031070-143 = "そのスパイを通じて、風紀委員会に関する極秘情報を手に入れたのだ。"
10031070-144 = "……いつの間に、そんなスパイを送り込んでいたのですか！？"
10031070-145 = "ふん、今さら驚いてどうする。#nゲヘナではよく聞く話だろう？"
10031070-146 = "情報によると、一見完璧そうにも見える風紀委員長だが……"
10031070-147 = "実は、あいつにも苦手なことがあると分かったのだ。"
10031070-148 = "そのひとつが……水泳！"
10031070-149 = "！？"
10031070-150 = "それだけではない！ピアノをはじめ、楽器全般が苦手らしいじゃないか！"
10031070-151 = "ま、まさかそれを知ったうえで、あなたは……"
10031070-152 = "そうだとも！#nむしろ、その弱点を知っていたからこそ、あいつに演奏を押し付けたのだ！"
10031070-153 = "……なぜですか？"
10031070-154 = "演奏が失敗したら、せっかく準備してパーティーが台無しになる可能性もあるのに……と言いたいのか？"
10031070-155 = "ククククッ。何を言っている、行政官よ……"
10031070-156 = "パーティーの成功よりも、あいつが恥をかく姿を見る方が愉快に決まっているからだ！"
10031070-157 = "[s] \"……うわぁ。\""
10031070-158 = "……あの人、バカなんですか？"
10031070-159 = "ええい！もちろん、狙いはそれだけじゃない！"
10031070-160 = "あいつが姿を表さなければ、それはそれで万魔殿と風紀委員会の格の違いを知らしめられる！"
10031070-161 = "逃げた以上、言い訳のしようは無いからな！"
10031070-162 = "よくも、そんなズルい手口を……"
10031070-163 = "しかし、委員長は逃げたわけでは……"
10031070-164 = "ふん、今さら何を言おうと意味は無い。"
10031070-165 = "イロハ！チアキ！どこだ！#nパーティーが始まるというのに、風紀委員長が一向に姿を現さない！"
10031070-166 = "この事実をゲヘナ全域に放送し、我々万魔殿の勝利を宣言しろ！"
10031070-167 = "ちょ、ちょっと待ってください。正気ですか！？#nそんな宣言をしたら……！"
10031070-168 = "キキキッ！負け犬の言葉など聞くものか！#nそれより、イロハとチアキは……"
10031070-169 = "その二人なら、パーティーの準備で席を外してるわよ。"
10031070-170 = "こんなにも愉快な瞬間に居合わせられないなんて、まったく残念だな。"
10031070-171 = "クククッ……まあ良い、このマコト様が直々に動こう。"
10031070-172 = "クククッ……いよいよ今日を境に……！"
10031070-173 = "我々万魔殿の時代が始まる……！"
10031070-174 = "[ns] \"……とても嫌な予感がする。\""
10031070-178 = "さあ！ゲヘナ生よ、よく聞け！"
10031070-179 = "本来であれば、今日開催されるゲヘナ特別パーティーのオープニング演奏を担当するはずだった[ruby=そらさき]空崎[/ruby]ヒナが姿を表さなかった！"
10031070-180 = "あいつは重要な役目に怯え、逃げ出したに違いない！"
10031070-181 = "これは我々万魔殿に対する侮辱であると同時に、自ら敗北を宣言したも同然！"
10031070-182 = "よって、これよりゲヘナのトップは紛れもなくこのマコト様のもの！"
10031070-188 = "クククッ……これで勝負はついた。"
10031070-189 = "…………。"
10031070-190 = "[s] \"アコ……大丈夫だよ、安心して。\""
10031070-191 = "私たちは大丈夫です。"
10031070-192 = "ただ、問題は……"
10031070-193 = "[s] \"問題って……？\""
10031070-197 = "ぎ、議長！大変です！"
10031070-198 = "ん？何事だ。"
10031070-199 = "さ、先ほどの放送後、ゲヘナ各地で……！"
10031070-200 = "………？"
10031070-203 = "部長！今の放送は聞いた！？風紀委員長が行方不明だって！#n万魔殿が勝ったらしいよ！"
10031070-204 = "風紀委員長が……行方、不明？"
10031070-205 = "………。"
10031070-206 = "……ずずっ。"
10031070-210 = "それはつまり………温泉開発部の時代が訪れたということだな？"
10031070-211 = "うん！そうかも！"
10031070-212 = "ハーハッハッハッハ！！"
10031070-213 = "全員、突撃！温泉開発の時間だ！#n今度こそ万魔殿の温泉を完成させるぞ！"
10031070-214 = "いえ～い！全員！脱獄よ～い！"
10031070-215 = "地面を掘るよ！"
10031070-225 = "なるほど、いつも私たちの邪魔する風紀委員長が不在ですか……"
10031070-226 = "フフッ★どうしましょうか、ハルナ？"
10031070-227 = "そんなの言うまでもないでしょ？"
10031070-228 = "そうだよ！まだ全然、美味しいもの食べられてないし！！"
10031070-229 = "ええ。先ほどは風紀委員長に捕まってしまいましたが、再び動くとしましょう。"
10031070-249 = "パンちゃんが……パンちゃんが、また暴れ始めました～！"
10031070-252 = "風紀委員長が姿を消したとなれば……ジッとしていられるものか！"
10031070-253 = "そう！私たちは一度依頼されたら全うする義理堅い問題児。"
10031070-254 = "万魔殿のリーダーに頼まれた銅像の設置……今度こそ成功させる！！"
10031070-256 = "……以上のような問題がゲヘナ全域で発生しています！"
10031070-257 = "議長！どうか早く指示を……！"
10031070-262 = "な、な、なにぃ……！？#nど、どうして一斉に混乱が起きているのだ……！？"
10031070-263 = "当然でしょう？#nゲヘナ最大の抑止力が不在だと公表したんですから……"
10031070-264 = "問題児が騒ぎ出すとは思わなかったんですか？"
10031070-265 = "[s] \"あの放送だけで、こんなにも事態が悪化するんだね……\""
10031070-266 = "ゲヘナを舐めないでください、先生。"
10031070-267 = "[s] \"いや、舐めたことはないよ！？\""
10031070-268 = "おそらく……この混乱を鎮圧できなければ、パーティーの中止はもちろんゲヘナ全体で……"
10031070-269 = "こ、こ、これは一体……な、なぜだ……！#nせ、せっかく準備してきたパーティーが……！"
10031070-270 = "私は万魔殿と風紀委員会の格の差を見せつけようとしただけだというのに……！"
10031070-276 = "今の放送は一体……！"
10031070-277 = "……って、完全にめちゃくちゃじゃないですか！？"
10031070-278 = "はあ……マコト先輩、今度は何を……"
10031070-279 = "あははっ！マコト先輩らしいじゃん！相変わらずめちゃくちゃだね！"
10031070-285 = "じゃあ、イブキ……パーティー参加できないの……？"
10031070-286 = "イブキ！ち、違う……！#n大丈夫だ、この私が何とかして……！"
10031070-287 = "う～ん、ここは私のNKウルトラ計画で……！"
10031070-289 = "またおかしなマコト先輩になっちゃうと思いますよ、サツキ先輩～"
10031070-325 = "[ns] （アコが言ってた。ヒナは用事で遅れているだけだと……）"
10031070-327 = "[ns] \"私が何とかしてみるよ。\""
10031070-329 = "先生？"
10031070-330 = "[s] \"ヒナは用事で少し外してるだけなんだよね？\""
10031070-331 = "…………はい。"
10031070-332 = "[s] \"なら、ヒナが帰ってくるまで私に任せて。\""
10031070-333 = "しかし……"
10031070-334 = "アホな議長が起こした騒動の責任を、何も先生が負う必要は……"
10031070-335 = "[ns] \"責任……というか、ヒナの演奏が楽しみなだけだよ。\""
10031070-337 = "[ns] \"だって、ヒナの頑張りは知ってるからね。\""
