[translation]
10030080-1 = "エピローグ;三日坊主"
10030080-4 = "（年明け1週間後）"
10030080-6 = "ヴェリタス・休憩室"
10030080-9 = "う……ぐううっ……"
10030080-14 = "ハレ先輩、頑張って！あとちょっと！"
10030080-15 = "もう少し……もう少しで新記録です……！"
10030080-25 = "ううっ…………きた！"
10030080-26 = "先輩すごい！前回の記録から10kgも追加したのに、もう成功！？"
10030080-27 = "私も成長したはずですが、まだまだハレさんには追いつけませんね。"
10030080-28 = "そこまで言われると、ちょっと恥ずかしい……"
10030080-29 = "でも……ここ数日トレーニングを頑張ったから。"
10030080-30 = "「筋力」を使う運動なら、ある程度できそうかも。"
10030080-32 = "それじゃ今度は「持久力」をメインにしてみよっか……？"
10030080-38 = "……ただいま。"
10030080-42 = "あ、先輩！おかえりー！"
10030080-44 = "久しぶりです、副部長。"
10030080-45 = "部室で会うのは元旦ぶりだよね？何してたの？"
10030080-47 = "うん。セキュリティ顧問を引き受けてる企業から新年会に誘われて、あちこち行ってたんだ。"
10030080-48 = "挨拶回りが忙しくて、声が枯れた気がする……"
10030080-49 = "先輩、ちょっと無理しすぎじゃない……？"
10030080-50 = "仕事なら別の依頼も見つかりますが、一度失った健康はそう簡単に取り戻せません。"
10030080-51 = "……来週は少し休んだら？"
10030080-52 = "そうだね……休息は大事だし。"
10030080-53 = "でも、大事な時期に外部の活動を休むわけにはいかないから。心配してくれてありがとう。"
10030080-54 = "そういえば、あんた達はここ最近何してたの？"
10030080-55 = "さっき部室の外まで聞こえてきたんだけど、何か運動の話をしてなかった？"
10030080-56 = "前までは部室から出ようとすらしなかったのに、自分たちから運動の話をするなんて……キャンプに連れて行った成果かと思ったら嬉しくなったよ。"
10030080-61 = "あ、それは……"
10030080-62 = "たしかに運動の計画、とも言えますが……"
10030080-69 = "「フィットネス・シミュレーター」の育成モードをやってたの！"
10030080-75 = "……ん？"
10030080-76 = "あ、先輩は「フィットネス・シミュレーター」知らない？#n出たばかりのゲームだよ。"
10030080-77 = "ゲームの中で選手になって、いろんな身体能力を鍛えるゲーム！#n現実のトレーニングをリアルに体験できるから話題になったの！"
10030080-78 = "ただ、1周目で育てられる選手のステータスに上限があって……"
10030080-79 = "高ステータスの選手を手に入れるためには、周回しないといけないんだよね。"
10030080-80 = "つまり、さっき言ってた「筋力」とか「持久力」は現実の話じゃなくて……"
10030080-81 = "……ゲームのキャラクターの話？"
10030080-82 = "うん！"
10030080-83 = "念のため聞くけど……"
10030080-84 = "あんた達、最後に部室を出たのはいつ？"
10030080-86 = "昨日……いや、一昨日かな？"
10030080-87 = "もっと前です。元旦に戻ってきてから外には出ていません。"
10030080-88 = "「フィットネス・シミュレーター」の育成モードはクリアに3日以上かかるって言うし、仕方ないよね。"
10030080-90 = "……来週の予定は？"
10030080-92 = "あ、来週はレトロゲーム「BOOM」シリーズのリブート作、「BOOMエターナル」が発売されるよ。"
10030080-94 = "キヴォトスで最も熱い新作！#n真理を追求するヴェリタスのメンバーとして、レビューせずにはいられない！"
10030080-95 = "そういえば、「BOOMエターナル」のプレイ動画をSNSにアップすれば、「妖怪MAX」の限定商品が当たるって見たような……"
10030080-96 = "発売最速クリアRTAをするチャンスです。"
10030080-97 = "チヒロ先輩もどう？#nリリース当日にオールで――"
10030080-106 = "あんた達…………"
10030080-111 = "もう一度お説教が必要みたいだね！？"
10030080-117 = "うわ～ん！ごめんなさい～！！"
10030080-125 = "（電脳）新春行進曲"
