[translation]
10034090-1 = "Epílogo parte 1; Tsumugi Shiina"
10034090-5 = "[ns1] \"Chegamos.\"\n[ns2] \"Será que é aqui mesmo?\""
10034090-8 = "Sim, o endereço que ela passou parece estar correto."
10034090-10 = "Então não é na escola..."
10034090-11 = "E, claro, também não é no terraço como o nosso."
10034090-12 = "É uma atmosfera bem mais séria do que eu imaginava..."
10034090-18 = "Digo, podemos entrar assim mesmo? E os ingressos? Pelo menos dar um oi..."
10034090-19 = "Bem, com certeza seria bom dar um oi."
10034090-20 = "Mas ela mesma disse que fica ocupada antes da apresentação."
10034090-21 = "Então, acho que basta mandarmos uma mensagem quando a apresentação terminar."
10034090-27 = "Vamos pedir para a Airi entrar em contato, representando o clube."
10034090-28 = "M-mas eu já disse que não vou fazer isso como presidente..."
10034090-29 = "Non non, presidente e representante são coisas diferentes. ...Ah, será que você está escondendo o jogo como um falcão que esconde as garras?"
10034090-30 = "Isso também é rock..."
10034090-31 = "Uuuh, não é nada disso..."
10034090-33 = "Pessoal, vai começar logo. Sensei, você também conhece essa tal de Tsumugi, né?"
10034090-34 = "[s] \"Sim, talvez ela tenha uma aura parecida com a da Natsu.\""
10034090-35 = "Hmm...?"
10034090-36 = "É, agora eu estou começando a ficar preocupada..."
10034090-37 = "O que exatamente você quis dizer com isso..."
10034090-38 = "B-bem, vamos entrar logo...!"
10034090-52 = "KIEEEEE! A morte dos humanos é o bem-estar da sociedade!!!"
10034090-53 = "WOEEEEEEEEEEEEEEEEE!!!!"
10034090-57 = "Morram! Morram! Que todos morram!!!"
10034090-58 = "WAAAAAAAAAAAAAA!!!"
10034090-63 = "............"
10034090-64 = "............"
10034090-65 = "............"
10034090-66 = "............"
10034090-70 = "\"Uma impressão parecida com a da Natsu\"... foi isso que você disse?"
10034090-71 = "[s3] \"Ah, não... bem, é que...\"\n[s4] \"Ela parece outra pessoa comparada a quando eu a vi...\""
10034090-77 = "Acho que vou refletir um pouco sobre as minhas ações..."
