[translation]
10035010-1 = "Episódio 1; Salva-vidas, missão iniciada!"
10035010-2 = "Chegamos!"
10035010-3 = "Então este é o 'Aegir', o maior parque aquático da D.U.!"
10035010-4 = "É tão grande que acho que vou acabar me perdendo!"
10035010-5 = "Ah, logo agora, ao ar livre..."
10035010-6 = "Isso é igualzinho a fazer patrulha debaixo de um sol escaldante."
10035010-7 = "O que você está dizendo, Fubuki!"
10035010-8 = "Nosso dever é proteger a segurança dos cidadãos, não é?"
10035010-9 = "Não podemos desanimar só porque está um pouco quente!"
10035010-10 = "É graças aos nossos esforços que todos podem aproveitar a piscina com conforto!"
10035010-12 = "Antes de proteger os cidadãos, eu é que vou acabar secando aqui."
10035010-13 = "E eu nem passei protetor solar..."
10035010-14 = "Eu queria ter sido designada para a piscina coberta."
10035010-15 = "Ei, Diretor(a), você também acha, né?"
10035010-19 = "Ah..."
10035010-20 = "Diretor(a)? O que houve?"
10035010-21 = "Você está com uma cor ruim. E parece menos animado(a) que o normal..."
10035010-22 = "S-será que são os sintomas iniciais de uma insolação!?"
10035010-23 = "Isso é grave! Fubuki! Vamos levar o(a) Diretor(a) para um lugar fresco! #nTambém precisamos chamar um salva-vidas...!"
10035010-24 = "Ah, o-o salva-vidas era eu!"
10035010-26 = "Calma, Kirino. Eu não estou com insolação."
10035010-27 = "É só que... minha cabeça ainda não processou essa situação."
10035010-28 = "Ainda? É melhor desistir logo, sabe~"
10035010-29 = "Não é uma questão tão simples assim."
10035010-30 = "Para começar, é a minha primeira vez."
10035010-31 = "Vir a um parque aquático e usar roupas com tão pouco tecido."
10035010-32 = "Além disso... vir à piscina durante o expediente."
10035010-34 = "E-entendo..."
10035010-35 = "Mas, por que o(a) Diretor(a) acabou sendo destacado(a) para cá?"
10035010-36 = "Pois é. Eu e a Kirino somos da Divisão de Segurança Pública, então faz sentido."
10035010-37 = "Mas o(a) Diretor(a) da Segurança Pública vir junto? Com certeza tem algo por trás disso~"
10035010-39 = "Ah, sobre isso..."
10035010-47 = "Vice-Diretora! O que significa isso?!"
10035010-48 = "Ah, você chegou, chefe."
10035010-49 = "Estou no meio de uma barra fixa... me deixa terminar só isso...!"
10035010-50 = "Hup!"
10035010-53 = "Ufa, que alívio. #nEntão, o que você quer, chefe?"
10035010-54 = "Eu disse para não fazer exercícios pesados dentro da delegacia..."
10035010-55 = "Bem, deixa pra lá."
10035010-56 = "Por que eu fui destacada para esse serviço?"
10035010-57 = "Se continuar assim, vou acabar indo para a piscina como oficial temporária da Divisão de Segurança Pública!"
10035010-59 = "Ah, é isso que está acontecendo?"
10035010-60 = "Não se faça de desentendida! #nFoi você quem planejou isso, Vice-Diretora!"
10035010-61 = "Sua assinatura estava na lista."
10035010-62 = "Não adianta tentar negar."
10035010-66 = "Pff, haha! Exatamente como eu pensei."
10035010-67 = "Não é como se eu tivesse planejado algo tão grandioso assim..."
10035010-68 = "Bem, fui eu quem colocou seu nome na lista, chefe."
10035010-69 = "O pedido chegou justamente quando você não estava."
10035010-70 = "Sua...!"
10035010-71 = "Isso é por sua causa, chefe."
10035010-72 = "Hã?"
10035010-73 = "Ora, todo santo dia você fica interrogando criminosos e fazendo trabalho de escritório, #nsem nem ter um descanso decente."
10035010-74 = "Desse jeito, você vai acabar destruindo sua saúde, sério mesmo."
10035010-75 = "Então... você quer me mandar para um parque aquático?"
10035010-76 = "Exatamente!"
10035010-77 = "Ser salva-vidas também não é lá muito fácil, mas #nacho que não vão deixar pessoas de fora fazerem nenhum trabalho importante de qualquer jeito."
10035010-78 = "O parque aquático só quer vender a sensação de segurança #nde que a 'Academia de Polícia Valkyrie está colaborando'."
10035010-79 = "Por isso, quero que aproveite essa chance para recarregar as energias!"
10035010-80 = "Ah! A consideração de uma subordinada que se preocupa com sua superior que trabalha demais. #nPode chorar de emoção, eu deixo!"
10035010-82 = "……Cancele isso imediatamente."
10035010-83 = "Eu não tenho tempo para descansar em uma piscina."
10035010-84 = "Solicite um reforço para o Departamento de Segurança Pública."
10035010-88 = "Ei, espere um pouco, chefe."
10035010-89 = "Você tem certeza de que não vai se arrepender?"
10035010-90 = "……Do que está falando?"
10035010-91 = "Sendo sincera... acho que essa é uma boa oportunidade para você também, chefe."
10035010-92 = "……?"
10035010-94 = "Chefe... quando você entrou na academia, você se candidatou ao Departamento de Segurança Pública, não foi?"
10035010-95 = "Você, como é que sabe disso!?"
10035010-96 = "Não tanto quanto você, mas como vice-diretora, eu também tenho autorização para acessar os arquivos."
10035010-97 = "Fiquei curiosa e dei uma pesquisadinha."
10035010-98 = "A chefe é uma pessoa necessária para o Departamento de Segurança Pública, mas..."
10035010-99 = "Se você ainda tem algum arrependimento, pensei que talvez fosse uma boa hora para tentar."
10035010-100 = "Você sempre quis trabalhar com atendimento ao público, não queria?"
10035010-104 = "Humpf."
10035010-105 = "?"
10035010-106 = "Não se empolgue, vice-diretora."
10035010-107 = "Hã?"
10035010-108 = "É verdade que houve uma época em que eu desejava o Departamento de Segurança Pública. #nMas eu já superei isso há muito tempo."
10035010-109 = "Alguém com uma cara intimidadora como a minha não conseguiria lidar com o público de forma adequada."
10035010-110 = "Não tenho mais nenhum arrependimento quanto a isso."
10035010-111 = "Vou solicitar aos superiores que reconsiderem o envio de pessoal."
10035010-112 = "Não precisa mais se envolver nisso."
10035010-114 = "Mas..."
10035010-115 = "É que, bem, já está tudo resolvido."
10035010-116 = "O que está resolvido?"
10035010-117 = "O pedido foi aprovado e o orçamento já foi liberado."
10035010-118 = "E olha só, até o aviso de transferência com a data de hoje!"
10035010-119 = "O quê……!"
10035010-122 = "Isso é... um assunto confidencial."
10035010-123 = "O quê, o quê? Fica difícil não ficar curiosa quando você começa a falar e para no meio."
10035010-125 = "[ns1] \"Concordo. Eu também queria ouvir.\"\n[ns2] \"Fico curioso quando param de falar no meio.\""
10035010-129 = "Ué? Não é o Sensei?"
10035010-130 = "Que coincidência encontrar você em um lugar desses!"
10035010-131 = "Nossa, e você está até de roupa de banho."
10035010-132 = "Será que o Sensei também está pronto para se divertir?"
10035010-133 = "[s] \"Olá, Kirino e Fubuki. E Kanna também.\""
10035010-134 = "P-por que o Sensei [USERNAME] está aqui...?"
10035010-135 = "Esta missão de apoio não deveria ter nada a ver com o Schale."
10035010-136 = "[s] \"Recebi um contato pedindo para eu dar uma olhada em como todos estão.\""
10035010-137 = "（Subchefe……！）"
10035010-138 = "[s] \"Bem, não se preocupe comigo.\""
10035010-140 = "[ns] \"Apenas finja que sou uma cliente comum.\""
10035010-141 = "Sim! Entendido!"
10035010-142 = "Se você acabar se afogando, me avise!#nEu irei te salvar imediatamente!"
10035010-143 = "[s] （Será que vou ter tempo de entrar em contato enquanto estiver me afogando……？）"
10035010-144 = "Já que nos encontramos, vamos brincar um pouco na piscina.#nClaro, sem deixar de fazer a patrulha."
10035010-145 = "Primeiro, vamos à loja de donuts na praça de alimentação. Estou começando a sentir um pouco de fome."
10035010-146 = "Você vai tentar matar o trabalho de novo, Fubuki!"
10035010-150 = "Haa……."
10035010-151 = "[s] \"Kanna, está preocupada com algo?\""
10035010-152 = "Ah, não."
10035010-153 = "É que eu não esperava encontrar o professor [USERNAME] aqui."
10035010-154 = "Fiquei apenas um pouco surpresa."
10035010-155 = "[s] \"Esse traje de salva-vidas combina com você.\""
10035010-156 = "……Obrigada por notar."
10035010-157 = "Mas, honestamente, acho que isso é inapropriado para mim."
10035010-158 = "Inapropriado……? Ah, você está falando do tamanho?"
10035010-159 = "Realmente, parece um pouco apertado~"
10035010-160 = "N-não é disso que estou falando!"
10035010-164 = "Aviso operacional. Todos os salva-vidas de plantão――"
10035010-165 = "Iniciaremos o briefing. Por favor, reúnam-se no centro das instalações."
10035010-170 = "Finalmente a missão vai começar!#nVamos dar o nosso melhor!"
