[translation]
10034140-1 = "5 dias atrás: Troca de posição"
10034140-3 = "……Vamos parar por aqui?"
10034140-4 = "Ufa…… Não sei se estou melhorando ou não……."
10034140-5 = "Dizem que é difícil sentir o próprio crescimento enquanto ele está acontecendo……."
10034140-6 = "Mas não precisa se preocupar, o plano de treino está perfeito."
10034140-8 = "Se continuarmos assim, com certeza vamos chegar lá…… além daquele céu."
10034140-9 = "Era para ser um elogio, mas isso me irrita um pouco."
10034140-10 = "E aliás, de que posição você está falando isso?"
10034140-11 = "O que você disse?"
10034140-12 = "Eu também estou melhorando a cada dia!"
10034140-13 = "Sim, sim, é verdade, você tem razão."
10034140-15 = "……Como sempre, né."
10034140-16 = "Falando nisso, Airi, quer trocar de lugar agora?"
10034140-17 = "Já faz um tempo que estou na minha vez."
10034140-18 = "Sim, pode deixar."
10034140-19 = "Obrigada, Kazusa-chan."
10034140-20 = "Então, observe minha performance. Se notar algo, me avise!"
10034140-21 = "Certo, entendido."
