[translation]
10045050-1 = "Episódio 5: Em busca da redenção após a eliminação"
10045050-4 = "[ns] \"……Kyo……!\""
10045050-6 = "[ns] \"Kikyou……!\""
10045050-9 = "Tosse, tosse!#n……Tosse, tosse!"
10045050-13 = "Kikyou!"
10045050-18 = "Sensei……?"
10045050-19 = "[s1] \"Fico feliz que tenha acordado…….\"\n[s2] \"Foi uma sorte você ter sido resgatada em um lugar raso.\""
10045050-22 = "Tosse……!"
10045050-23 = "O, o que aconteceu……? E a partida?"
10045050-24 = "A partida já acabou. Quem avançou para a final foram a Chise e a Izuna."
10045050-25 = "Todas nós fomos eliminadas."
10045050-26 = "……！！"
10045050-27 = "Não pode ser, foi por minha causa……?"
10045050-28 = "Não pense nisso! Ajudar uma aliada é o natural, não é?"
10045050-29 = "A culpa é minha……."
10045050-30 = "Eu não sei nadar…… se eu tivesse dito desde o início que tinha medo de água…… nada disso teria acontecido."
10045050-32 = "Então você não odeia a água…… você estava com medo?"
10045050-33 = "……Eu não sou boa com atividades ao ar livre, então nunca tive a chance de ir a lugares com água."
10045050-34 = "Naturalmente, não sei nadar, e entrar em águas profundas é algo que eu evitaria a todo custo."
10045050-35 = "Mas…… como estrategista do Hyakkaryouran, eu não conseguia admitir que não era capaz de fazer algo assim……."
10045050-36 = "Sinto muito mesmo. Por causa da minha teimosia desnecessária……."
10045050-37 = "Eu já disse para não se preocupar com isso! Além disso, a responsabilidade também é minha."
10045050-38 = "Somos amigas de infância e eu nem percebi isso."
10045050-39 = "Eu que peço desculpas."
10045050-40 = "Não, a culpada sou eu."
10045050-41 = "Não, eu que sou a culpada!"
10045050-42 = "Não importa como olhe, fui eu!"
10045050-43 = "Não, fui eu……!"
10045050-45 = "Fufu, vocês duas são realmente muito próximas."
10045050-46 = "Kikyou-senpai, por favor, não se preocupe tanto."
10045050-47 = "Para mim, o fato de você estar bem já é o suficiente."
10045050-48 = "……Pessoal, vocês não me odeiam?"
10045050-50 = "Por que odiaríamos? O objetivo de participar do torneio era fortalecer nossos laços, não era?#nGanhar ou perder não importa."
10045050-51 = "Exatamente. Por favor, não se culpe tanto."
10045050-52 = "Mas……."
10045050-54 = "[ns] \"Não se preocupe! Ainda temos uma chance!\""
10045050-55 = "Como assim?"
10045050-56 = "[s3] \"Isso será uma surpresa para depois.\"\n[s4] \"Pessoal, nos vemos na quadra de vôlei de praia!\""
10045050-59 = "……?"
10045050-62 = "O tempo voa, e o Festival Aquático de Hyakkiyako já está chegando ao fim, não é?"
10045050-63 = "Mas é triste ver tudo chegando ao fim…… não é?"
10045050-67 = "Atendendo aos pedidos calorosos de todos vocês, preparamos uma partida extra!#nE é esta……!"
10045050-68 = "Repescagem!"
10045050-69 = "As 8 pessoas que foram eliminadas na corrida de obstáculos aquáticos formarão duplas e competirão em um torneio de vôlei de praia!"
10045050-70 = "A equipe que vencer esta repescagem poderá avançar para a final!"
10045050-71 = "O festival ainda continua!#nBoa sorte a todos, nyan-nyan!"
10045050-72 = "[ns] \"Vou anunciar as duplas sorteadas e as chaves das partidas!\""
10045050-74 = "[log]1ª partida de vôlei de praia![/log]"
10045050-77 = "VS"
10045050-81 = "Ah, estou com a Kikyou.#nE o adversário da primeira rodada também não é ruim."
10045050-82 = "……。"
10045050-84 = "Por que, entre todas as pessoas, tinham que ser eles……!"
10045050-85 = "Ainda não! Nós também temos chances de vencer!"
10045050-87 = "[ns] \"A próxima é agora!\" "
10045050-89 = "[log]Jogo de vôlei de praia 2![/log]"

10045050-92 = "VS"
10045050-96 = "A senpai Nagusa e o time dela! Isso é o destino!"
10045050-97 = "Com a senpai ao meu lado, a vitória é garantida!"
10045050-98 = "Sim, vamos dar o nosso melhor."
10045050-100 = "O-o que faremos? Os oponentes são fortes demais……!"
10045050-101 = "Tenha mais confiança. #nNós também chegamos até aqui, afinal."
10045050-102 = "Fufu…… como parceiras de treino, não poderiam ser melhores."
10045050-104 = "Que confronto interessante nós temos aqui!"
10045050-105 = "A primeira partida será após um breve intervalo!"
10045050-106 = "[ns] \"Pessoal, não mudem de canal……!\""
10045050-108 = "(No fim das contas, ou nós ou a senpai seremos eliminadas)"
10045050-109 = "(Mas, se por minha causa a Renge for eliminada de novo……)"
10045050-110 = "(……)"
10045050-111 = "(Eu preciso fazer isso……)"
10045050-112 = "(Desta vez não é na água, então eu devo conseguir……!)"
10045050-113 = "(Os oponentes da primeira rodada nem são tão fortes. Com a Renge, vai dar tudo certo)"
10045050-114 = "(Então, por que……)"
10045050-115 = "(……Por que eu estou com um pressentimento ruim?)"
