[translation]
10049030-1 = "Episódio 3; O que é a Garota Mágica Heavy Caliber!"
10049030-2 = "[log]3 dias atrás, Sala de Descanso do Comitê de Biblioteca[/log]"
10049030-4 = "É isto!!"
10049030-5 = "Isto...?"
10049030-6 = "Sim?"
10049030-10 = "Por favor, torne-se uma garota mágica!"
10049030-11 = "Hehehe... Eu nunca pensei que chegaria o dia em que eu poderia dizer essa frase...!"
10049030-12 = "O que é... essa \"Garota Mágica Heavy Caliber: Especial Borderland\"...?"
10049030-13 = "A Garota Mágica Heavy Caliber fará um show especial no parque de diversões Borderland!"
10049030-14 = "Bem, especificamente falando...?"
10049030-16 = "É um show realizado em vários locais do parque por membros do elenco fantasiados como os personagens."
10049030-17 = "Como o local é grande, parece que eles estão divididos em várias equipes..."
10049030-18 = "Reisa-san, e o que isso tem a ver com a missão...?"
10049030-19 = "Que tal nos disfarçarmos de garotas mágicas ao nos infiltrarmos!"
10049030-20 = "Se existem várias equipes, ninguém vai notar se adicionarmos mais um grupo!"
10049030-21 = "Além disso, acho que não pareceria estranho em lugar nenhum do parque!"
10049030-23 = "Muitas vezes o elenco é convidado de fora...#nMesmo que sejamos novas, talvez não haja motivo para os funcionários do parque suspeitarem."
10049030-24 = "Entendo..."
10049030-25 = "Lembro-me de ter visto um desenho parecido quando eu era pequena.#nSe não me engano, passava de manhã... É a mesma coisa?"
10049030-26 = "Não!!#nAh, não, quero dizer, é um desenho animado matinal, mas!"
10049030-27 = "Garota Mágica Heavy Caliber é a história de garotas escolhidas que protegem Kivotos da invasão de \"Ela\", uma executiva do mal!"
10049030-28 = "E-entendo..."
10049030-29 = "Mas acho que esse traje não é adequado para combate."
10049030-30 = "Seria difícil preparar o equipamento também..."
10049030-31 = "E acima de tudo, eu não entendo quase nada desse gênero."
10049030-32 = "Eu também não tive contato nenhum com isso..."
10049030-33 = "Além disso... é um pouco vergonhoso, por assim dizer..."
10049030-34 = "Ah...#nÉ, você tem razão."
10049030-35 = "Desculpe... é que, eu pensei que poderia ajudar do meu jeito, e acabei falando sem pensar."
10049030-36 = "Hehehe, b-bem, então vou pensar em outro método!"
10049030-40 = "N-não! É que, o que eu quero dizer é..."
10049030-41 = "Pelo contrário, esse tipo de traje pode fazer o inimigo baixar a guarda e..."
10049030-42 = "N-não seria adequado para uma infiltração?"
10049030-43 = "Suzumi-san...?"
10049030-45 = "Mas garotas mágicas são meio infantis, né..."
10049030-46 = "Não é bem assim.#nAcho que a Garota Mágica Happy... Caliber? é muito boa."
10049030-48 = "Não seria \"Heavy Caliber\"?"
10049030-49 = "D-de qualquer forma. Acho que combina com o ambiente de um parque de diversões."
10049030-50 = "Só que... se formos nos disfarçar, precisaremos de conhecimento adequado."
10049030-51 = "Reisa-san, você entende bem dessa obra?"
10049030-52 = "Sim! Eu adoro!"
10049030-53 = "A forma como elas protegem a paz mundial parece um grupo de vigilantes e..."
10049030-54 = "Dá para dizer que é a minha obra favorita de todas!!"
10049030-55 = "Eu até assisti ao filme que lançou recentemente!"
10049030-56 = "Embora eu não consiga conversar com ninguém sobre Heavy Caliber..."
10049030-57 = "..."
10049030-62 = "Bem, posso pedir para você providenciar os trajes agora mesmo?"
10049030-63 = "Deixo a escolha de quais usar por sua conta, Reisa-san."
10049030-65 = "Suzumi-san!?"
10049030-69 = "Sério mesmo!? Vou preparar agora mesmo!!"
10049030-74 = "（Por que será que eu disse uma coisa dessas...）"
10049030-75 = "（A Reisa-san está motivada e acho que é adequado para uma infiltração, mas...）"
10049030-76 = "（Ainda assim, é muito vergonhoso...）"
10049030-77 = "Combina com você! Não precisa ficar com vergonha!"
10049030-78 = "Foi a decisão certa ceder o papel principal! Você tem a presença de uma protagonista, Suzumi-san—"
10049030-79 = "—Não, é \"Thermite White\"!"
10049030-80 = "Te, Thermite White...?"
10049030-81 = "É o nome da personagem que a Suzumi-san vai interpretar!#nSe falarmos o nome real, nossa identidade será revelada!"
10049030-82 = "E eu sou a \"Thermite Pink\"!#nA parceira que dá suporte à \"Thermite White\"!"
10049030-83 = "En, entendo. Rei—"
10049030-89 = "Não, Thermite Pink..."
10049030-93 = "A propósito... por que Thermite Pink?"
10049030-94 = "O traje da Reisa-san é roxo, então não deveria ser \"Purple\"?"
10049030-95 = "Ah! Sobre isso!"
10049030-101 = "[log=레이사 매지컬]魔法少女ヘヴィキャリバーの本編のお話になるのですがもともと#nテルミットピンクは名前の通りハートのジュエルやピンクのドレスが[/log]"
10049030-102 = "[log=레이사 매지컬]メインのデザインだったんです。でもエラの忠実な僕「シルバープレート」#nとの決戦があった「ボルトキャッチ！ヘヴィキャリバー！」の回で危機に[/log]"
10049030-103 = "[log=레이사 매지컬]陥ってしまって！そこでホワイトと共に力を合わせた際に新たな能力に#n目覚めたんですが、それでもシルバープレートを倒すことは叶わずそ#nのまま二人は倒れてしまうんです宿敵を倒したシルバープレートは――[/log]"
10049030-107 = "A, ah..."
10049030-109 = "[log=레이사 매지컬]――友情エネルギーを憎悪の星へ送ろうとしたその瞬間！#nこの姿のピンクが現れて敵を制圧するんです！それで――[/log]"
10049030-117 = "—foi o que aconteceu! A forma que a Pink assume quando se transforma especialmente naquele momento é esta, e como eu amo muito esse episódio, escolhi este traje! Portanto, esta não é a forma normal da Pink, mas sim a forma com seu verdadeiro poder liberado!"
10049030-118 = "En, entendo... isso foi esclarecedor..."
10049030-119 = "A propósito, Rei— Thermite Pink. Você conseguiu entrar em contato com a Shimiko-san?"
10049030-120 = "É a executiva do mal, \"Era\"!"
10049030-121 = "...Ah, E, onde está a Era agora?"
10049030-122 = "Isso é... nem eu sei..."
10049030-123 = "Será que ela perdeu a hora...?"
10049030-124 = "Acho que conseguimos dar conta do local apenas nós duas, mas..."
10049030-125 = "É um pouco preocupante."
10049030-130 = "Pessoal, estão me ouvindo? Aqui é a Mashiro, do Comitê de Implementação da Justiça. Já estou na minha posição."
10049030-132 = "Sim, estamos ouvindo."
10049030-133 = "Thermite Pink, sem problemas!"
10049030-135 = "Aqui a recepção também está boa.#nSe precisar de apoio, entre em contato por este canal."
10049030-136 = "Aliás, minha posição atual é na torre de observação do lado da Trinity."
10049030-138 = "Entendido. Vou ficar atenta à segurança do campo de visão também."
10049030-140 = "...Sensei, você também está ouvindo bem?"
10049030-141 = "[s] \"Sim, perfeitamente.\""
10049030-142 = "Se precisar de mim, Sensei, não hesite em me chamar."
10049030-144 = "Por enquanto, não há problemas com o estado da comunicação."
10049030-145 = "Obrigada pelo apoio, Mashiro-san."
10049030-150 = "Se, Sensei!?"
10049030-151 = "Sensei!"
10049030-152 = "[s1] \"Bom dia. Suzumi, Reisa.\"\n[s2] \"Olá, Thermite White, Pink.\""
10049030-156 = "Se, Sensei!?? De... desde quando você está aí!?"
10049030-160 = "Ah, e, este traje, bem, é que..."
10049030-161 = "[s3] \"Preparando o coração... acho que é isso.\"\n[s4] \"Não se preocupe. Combina muito com você.\""
10049030-165 = "Já ouvi sobre a situação da Hasumi-senpai."
10049030-166 = "O pessoal de apoio de hoje somos eu e o Sensei."
10049030-167 = "Eu não sabia que o Sensei viria..."
10049030-168 = "Ué? A Suzumi-san também não sabia?"
10049030-169 = "Se eu soubesse, teria me preparado melhor...!"
10049030-171 = "A Hasumi-senpai disse que pediu a cooperação do Sensei como um \"apoio na medida do possível\"."
10049030-172 = "Embora eu não saiba os detalhes."
10049030-173 = "Entendo... quem diria que receberíamos o apoio do Schale..."
10049030-174 = "[s5] \"Porque parecia que precisavam de ajuda!\"\n[s6] \"Porque parecia divertido!\""
10049030-177 = "(Estou feliz por poder estar com o Sensei depois de tanto tempo, mas...)"
10049030-178 = "(Mas, este traje é um pouco demais...)"
10049030-179 = "Antes de entrarmos em espera, gostaria de perguntar uma coisa."
10049030-180 = "Os trajes de vocês são bem peculiares, mas..."
10049030-181 = "Seria esse o uniforme da Patrulha?"
10049030-182 = "Diferente do uniforme do Comitê de Justiça, acho que é chamativo e adorável."
10049030-183 = "Não, não é. #nComo a Patrulha não é uma organização, naturalmente, não temos um uniforme designado."
10049030-184 = "Isto é, bem... um traje de infiltração para patrulhar o local..."
10049030-186 = "Somos as protagonistas amigas de \"Garota Mágica Heavy Caliber\"! Estes são os trajes da Termite White e da Pink!"
10049030-187 = "Somos garotas mágicas que protegem a paz mundial e defendem a justiça!"
10049030-188 = "..."
10049030-189 = "..."
10049030-193 = "...Entendo, compreendido."
10049030-194 = "Um traje para defender a justiça... é muito bom."
10049030-195 = "..."
10049030-196 = "Ué? No código de chamada, a Suzumi-san está como \"Termite White\", mas... #nNão seria \"Pink\"? Daqui parece cor-de-rosa..."
10049030-197 = "Ah! O motivo é o seguinte! Primeiro, você precisa assistir ao episódio 7 da terceira temporada! Explicando de forma simples—"
10049030-199 = "O-o código de chamada não tem problema nenhum! Obrigada por verificar!"
10049030-200 = "Reisa-san. Já que estamos aqui, que tal assistirmos ao vídeo juntas depois? #nAté lá, nada de spoilers."
10049030-201 = "Oh! Boa ideia! Da próxima vez, trarei todos os discos!"
10049030-202 = "Bem, a partir de agora, entraremos em espera."
10049030-203 = "Deixem a vigilância e o tiro de precisão comigo."
10049030-204 = "No entanto, lembrem-se de que, para o tiro de precisão, é necessária a permissão de disparo do Comitê de Justiça."
10049030-208 = "Ah..."
10049030-209 = "Será que ainda dá tempo de trocar para uma roupa normal..."
10049030-210 = "Ué!? Mas combina tanto com você!"
10049030-211 = "Mas, ainda assim, é vergonhoso..."
10049030-212 = "Vocês duas, o que estão fazendo?!"
10049030-213 = "O show vai começar em breve, vocês precisam esperar no camarim!"
10049030-214 = "N-nós?"
10049030-215 = "Sim?"
10049030-216 = "Francamente, que dor de cabeça. Depois de mandarem mensagem dizendo que os tripulantes do trem não chegariam a tempo."
10049030-217 = "Bem, já que chegaram a tempo, tudo bem. Vamos, comecem logo!"
10049030-218 = "Começar... o quê?"
10049030-223 = "O show de \"Garota Mágica Heavy Caliber\", é claro!"
10049030-224 = "Vocês são o elenco, não são? Preparem-se logo!"
10049030-225 = "E-elenco!?"
