[translation]
1004720-1 = "Baú de tesouros de memórias"
1004720-2 = "（Preocupado com Chise, saí apressado em direção ao mar para procurá-la）"
1004720-9 = "[ns] \"Talvez, se for a Chise, ela deva estar por aqui...\""
1004720-11 = "（Enquanto procurava por Chise e observava a beira-mar...）"
1004720-23 = "[ns] \"Será que esse som é...?\""
1004720-30 = "Ei!"
1004720-40 = "（Ao olhar na direção do som, vi Chise enchendo vigorosamente sua bolsa com a areia da praia）"
1004720-41 = "[ns] \"Ch-Chise?\""
1004720-47 = "Hmm~? Sensei! Olá~"
1004720-48 = "[s1] \"Ah, Chise.\"\n[s2] \"Olá... mas, o que você está fazendo?\""
1004720-51 = "Eu~?"
1004720-52 = "Isso é..."
1004720-53 = "Estou tentando levar o mar comigo~"
1004720-54 = "[s] \"Levar o mar com você? O que exatamente isso significa...?\""
1004720-56 = "É assim, eu coloco a areia que está aqui dentro."
1004720-57 = "Se eu decorar a sala do Clube Yin-Yang com isso~"
1004720-62 = "As pessoas que não puderam vir à praia também poderão aproveitar, não é~?"
1004720-63 = "[s5] \"Entendo... então você está levando algo que se tornará uma memória.\"\n[s6] \"Era isso que você queria dizer, Chise...\""
1004720-66 = "Hmm~? Existe algum outro significado também~?"
1004720-67 = "[s7] \"Não, eu sei que pode parecer repentino...\"\n[s8] \"Mas, sendo você, Chise, eu pensei que talvez...\""
1004720-73 = "……？"
1004720-75 = "[s] \"Ah, bem, é isso mesmo. Chise, você está levando o mar para todos...\""
1004720-76 = "Sim, mas não é só o mar~"
1004720-77 = "Tem tantas coisas que quero mostrar para todo mundo."
1004720-78 = "……Coloquei tudo o que encontrei de maravilhoso no mar aqui dentro."
1004720-85 = "Sensei, quer ver também~?"
1004720-86 = "（Dizendo isso, Chise começou a tirar algo de sua bolsa）"
1004720-94 = "Essa concha~ eu peguei ali no canto."
1004720-95 = "Essa pedrinha aqui, caiu na lama da maré~"
1004720-96 = "Esse abridor de garrafas foi um presente da casa de praia~"
1004720-97 = "E então~..."
1004720-104 = "Sensei, isso aqui é~..."
1004720-111 = "Sensei~..."
1004720-125 = "（A bolsa de Chise não estava cheia apenas de coisas encontradas na praia, mas de muitas memórias）"
1004720-126 = "（Conchas, carapaças de caranguejo-eremita, pedrinhas e abridores de garrafa que pareciam não ter nada de especial）"
1004720-127 = "（Além de lixos como redes e sacolas plásticas que estavam jogados na areia）"
1004720-128 = "（...Eu reconhecia aquelas «memórias»）"
1004720-130 = "[ns] \"Chise, isso aqui, por acaso...\""
1004720-132 = "Sim, são coisas que pegamos quando estávamos procurando por brilhos com você, Sensei~"
1004720-133 = "Porque nelas estão guardadas as memórias do tempo que passei com você."
1004720-134 = "Por isso, eu quis mostrar para todo mundo também."
1004720-135 = "E então, vou contar a eles a noite toda sobre o que aconteceu..."
1004720-136 = "E recitar um haiku para eles~"
1004720-140 = "……Se eu fizer isso, será que eles vão ficar felizes?"
1004720-141 = "[ns] \"Sim, eles vão ficar felizes.\""
1004720-143 = "[ns] \"Com certeza... não, absolutamente.\""
1004720-144 = "Sério~?"
1004720-145 = "Que bom então~"
1004720-146 = "Então, vou levar muito mais para casa~"
1004720-157 = "（E assim, o que Chise ia enchendo em sua bolsa parecia um tesouro insubstituível...）"
1004720-158 = "(……estava brilhando, brilhando intensamente)"
1004720-160 = "[ns] \"Essa bolsinha é um baú de tesouros para a Chise, não é?\""
1004720-161 = "Um baú de tesouros……?"
1004720-162 = "[s9] \"Sim. Porque está cheia de memórias que você quer mostrar...\"\n[s10] \"...ou contar para alguém.\""
1004720-165 = "Mostrar para alguém... memórias que quero contar..."
1004720-166 = "Um baú de tesouros, cheio de coisas assim..."
1004720-167 = "……Ah."
1004720-168 = "Um tesouro."
1004720-172 = "Preciso levar para casa."
1004720-179 = "[ns] \"……O que houve, Chise?\""
1004720-182 = "[ns] \"Ch-Chise!? O que aconteceu de repente!?\""
1004720-183 = "O Sensei também é um tesouro, então vou levar para o Departamento Yin-Yang~"
1004720-184 = "[s] \"I-Isso é... ugh! Areia na boca...!?\""
1004720-190 = "[ns] \"O-oh, eu vou junto para o Departamento Yin-Yang, então~~~!\""
1004720-192 = "(Dessa forma, sendo puxado pela mão pela Chise...)"
1004720-193 = "(Senti o tempo passar lentamente à beira-mar)"
