[translation]
1004606-1 = "De mãos dadas com Izuna"
1004606-2 = "（Pensando se eu realmente não deveria ter tocado no assunto, fui até o local onde combinei de encontrar a Izuna）"
1004606-3 = "Ah, Mestre! Por aqui! Por aqui!"
1004606-6 = "[ns] \"Izuna, desculpe a demora.\""
1004606-7 = "De jeito nenhum!"
1004606-8 = "Bem, o que devemos fazer? Coisas que podemos fazer na praia..."
1004606-9 = "Hmm, deveria haver muitas coisas, mas é difícil... Treinamento é bom, mas, pensando bem...!"
1004606-13 = "Desta vez, em vez de começar com treinamento ninja,"
1004606-14 = "talvez procurar por lugares deliciosos de verão, ou algo do tipo...!"
1004606-15 = "[s] \"Para o futuro, eu queria te perguntar uma coisa...\""
1004606-16 = "Mestre, aconteceu alguma coisa?"
1004606-17 = "[s] \"Izuna, você não gosta de nadar no mar?\""
1004606-21 = "！？"
1004606-22 = "[s1] \"Não precisa responder se não quiser, mas sinto que você está evitando...\"\n[s2] \"Já que estamos aqui, pensei se havia algum motivo para isso.\""
1004606-25 = "Is-isso é..."
1004606-26 = "[s] \"Desculpe, se não quiser falar, não se preocupe. Sinto muito por perguntar algo que te incomoda.\""
1004606-27 = "N-não é isso, Mestre! Não é que eu não goste...!"
1004606-28 = "A Izuna, bem, é que..."
1004606-31 = "……"
1004606-32 = "U-uwaaaaaa!!"
1004606-33 = "[s] \"I-Izuna!?\""
1004606-34 = "Des-desculpe! Não foi minha intenção esconder, mas...!"
1004606-36 = "（Depois disso, ouvi a história da Izuna）"
1004606-38 = "[ns] \"Então, você não sabe nadar...?\""
1004606-39 = "Si-sim..."
1004606-40 = "A Izuna simplesmente não consegue se acostumar..."
1004606-41 = "Eu tentei algumas vezes até agora, mas..."
1004606-42 = "É que eu acabo ficando com medo, sabe..."
1004606-43 = "Quando a água do mar entra nos meus olhos ou na boca, eu fico toda assustada..."
1004606-44 = "Des-desculpe, Mestre...!"
1004606-45 = "Eu deveria ter dito antes, mas como eu tentei disfarçar..."
1004606-46 = "Sinto muito mesmo...!"
1004606-47 = "[s] \"Não, não é algo pelo qual você precise se desculpar...\""
1004606-49 = "[ns] \"Ah, mas fiquei curioso com uma coisa.\""
1004606-50 = "……？"
1004606-51 = "[s] \"Por que você estava tentando disfarçar?\""
1004606-52 = "Is-isso é..."
1004606-56 = "A Izuna, bem, disse ao Mestre várias vezes..."
1004606-57 = "Que eu me tornaria a ninja mais forte de Kivotos..."
1004606-58 = "[s] \"Sim.\""
1004606-59 = "Se eu almejo ser a mais forte de Kivotos e, bem, acabo descobrindo que não sei nadar..."
1004606-60 = "Bem, ou seja..."
1004606-61 = "Ah, pensei que o Mestre ficaria decepcionado comigo... e isso me deu medo..."
1004606-62 = "[s3] \"...Está tudo bem, Izuna.\"\n[s4] \"Eu não vou te julgar por causa disso.\""
1004606-65 = "É-é mesmo...?"
1004606-66 = "Que bom... ehehe..."
1004606-67 = "Fico aliviada em ouvir isso diretamente do Mestre...!"
1004606-68 = "Mas, ao mesmo tempo, a Izuna tomou uma decisão!"
1004606-69 = "[s] \"Uma decisão...?\""
1004606-70 = "Sim! Mesmo que seja assustador, fugir não vai mudar nada!"
1004606-71 = "Como alguém que almeja ser a maior ninja de Kivotos..."
1004606-75 = "Afinal, é algo que terei que superar algum dia!"
1004606-76 = "[s] \"O que você quer dizer com isso...?\""
1004606-77 = "É por isso, Mestre, por favor, espere um pouco!"
1004606-78 = "[s] \"Ah, entendi...?\""
1004606-85 = "Obrigada por esperar!!"
1004606-89 = "[ns] \"O que é isso...?\""
1004606-90 = "Eu sabia que um dia"
1004606-91 = "esse dia chegaria..."
1004606-92 = "Para superar isso, eu precisaria lutar de forma justa e honrada algum dia!"
1004606-93 = "[s] \"Entendo, esse é um bom espírito.\""
1004606-94 = "E estes são os equipamentos ninja para isso!"
1004606-95 = "Veja, Mestre!"
1004606-96 = "Eles têm um formato estranho, mas são ferramentas que os ninjas usavam para andar sobre a água!"
1004606-100 = "E este tubo!"
1004606-101 = "Este é um tubo de bambu feito para que os ninjas pudessem respirar mesmo debaixo d'água!"
1004606-102 = "E este aqui é para o ninja se mover rapidamente sobre a água—"
1004606-103 = "Um motor de parafuso supercondutor simplificado!"
1004606-104 = "[s] \"Não entendi muito bem, mas é incrível!\""
1004606-106 = "Mesmo que a força não seja suficiente, os ninjas têm seus próprios métodos!"
1004606-107 = "Sendo assim, Izuna vai usar isso para tentar superar a natação!"
1004606-109 = "(E assim, o treinamento especial de Izuna começou)"
1004606-111 = "Primeiro, com estas aranhas d'água!"
1004606-113 = "Então, Mestre, lá vou eu!"
1004606-120 = "[ns] \"Izunaaaa!?\""
1004606-122 = "Eu..."
1004606-123 = "Não consegui ficar de pé de jeito nenhum...!"
1004606-124 = "Será que o treinamento da Izuna ainda não é suficiente!?"
1004606-125 = "[s] \"A menos que seja feito pela Millennium, acho impossível ficar de pé com algo assim...\""
1004606-126 = "Droga... mas a Izuna não vai desistir!"
1004606-127 = "A seguir, com este tubo de bambu...!"
1004606-131 = "Izuna! Lá vou eu!"
1004606-137 = "(Glub, glub, glub...)"
1004606-138 = "[s] \"Izunaaaaaa!?!?\""
1004606-140 = "Puf!"
1004606-145 = "Ah, Mestre..."
1004606-146 = "É muito difícil abrir os olhos debaixo d'água, não é!?"
1004606-147 = "Meus olhos arderam e eu acabei soltando o tubo de bambu..."
1004606-148 = "[s] \"E-entendi... por enquanto, vá lavar os olhos...\""
1004606-149 = "E-eu não vou desistir! Na próxima vez eu consigo...!"
1004606-151 = "(E assim, Izuna tentou várias vezes, mas...)"
1004606-152 = "Waaaaah, Mestre!?"
1004606-157 = "(Infelizmente, todas as tentativas terminaram em fracasso)"
1004606-159 = "Snif... parece que é difícil superar o mar com equipamentos ninja..."
1004606-160 = "Será que a Izuna vai ficar assim para sempre..."
1004606-161 = "Desse jeito, a Izuna nunca será a maior ninja de Kivotos..."
1004606-162 = "[s] \"Izuna, por que não tenta praticar natação?\""
1004606-163 = "......Eh?"
1004606-164 = "[s5] \"Mesmo que não consiga superar com equipamentos ou ninjutsu...\"\n[s6] \"Que tal aprender a nadar?\""
1004606-167 = "Você quer dizer que... o Mestre vai me ensinar?"
1004606-168 = "[s7] \"Sim, eu sei nadar o suficiente. Pode deixar comigo.\"\n[s8] \"Vou dar o meu melhor pela Izuna!\""
1004606-171 = "S-sim...!"
1004606-172 = "E-então, por favor, me ajude! Mestre...!"
1004606-174 = "（Assim, começou uma aula de natação pura, sem qualquer relação com ninjutsu）"
1004606-176 = "Hum, posso segurar a mão do Mestre?"
1004606-177 = "[s] \"Sim. Primeiro, vamos colocar o rosto na água para se acostumar.\""
1004606-178 = "S-sim! Então, Izuna, lá vou eu...!"
1004606-180 = "Com licença, vou colocar o rosto...!"
1004606-181 = "O rosto..."
1004606-182 = "Aquele... Mestre, vamos continuar de mãos dadas...!?"
1004606-183 = "[s] \"Sim, está difícil de fazer assim?\""
1004606-184 = "N-não! Então, Izuna, lá vou eu!"
1004606-190 = "[ns] \"Como foi?\""
1004606-191 = "Puh... S-sim, consegui..."
1004606-192 = "Mas, além disso, aquele..."
1004606-193 = "[s] \"Então, agora vamos tentar bater as pernas.\""
1004606-194 = "S-sim!"
1004606-196 = "（Assim, a aula continuou aos poucos）"
1004606-204 = "（Começando por segurar as mãos e colocar o rosto na água, seguido por bater as pernas）"
1004606-209 = "（Depois disso, praticamos a respiração e outras coisas...）"
1004606-221 = "（Ensinei cada um dos elementos necessários, um por um）"
1004606-224 = "[ns] \"Então, vou te dar apoio, tente colocar o corpo na horizontal dentro da água.\""
1004606-228 = "Hyaaa!?"
1004606-235 = "[ns] \"I-Izuna!? Você está bem!?\""
1004606-236 = "E-estou bem... é que, você tocou na minha cintura de repente..."
1004606-243 = "[ns] \"Nem vi que horas ficaram... quer parar por aqui?\""
1004606-244 = "S-sim... muito obrigada, Mestre..."
1004606-245 = "[s] \"Sim, bom trabalho. Vamos voltar então?\""
1004606-246 = "S-sim...!"
1004606-250 = "（Assim, no caminho de volta para o resort...）"
1004606-257 = "Com o Mestre..."
1004606-258 = "De alguma forma, ainda..."
1004606-262 = "..."
1004606-263 = "[s] \"Desculpe por isso.\""
1004606-264 = "S-sim...!?"
1004606-265 = "[s9] \"Fiquei pensando se não te forcei a vir comigo.\"\n[s10] \"É raro ver a Izuna tão cansada assim...\""
1004606-268 = "N-não é isso...!"
1004606-269 = "Hã, o jeito de andar...?"
1004606-270 = "S-será mesmo...? Izuna está estranha, será...?"
1004606-271 = "[s11] \"Bem, como ensinei o básico do básico, acho que agora você consegue.\"\n[s12] \"Depois, você pode praticar sozinha quando tiver vontade.\""
1004606-274 = "Isso significa que..."
1004606-275 = "As aulas com o Mestre acabam hoje...?"
1004606-276 = "[s] \"Ah, o sol já está se pondo. É melhor irmos logo...\""
1004606-277 = "N-não é nada disso!"
1004606-278 = "Não é isso, Mestre!"
1004606-279 = "[s] \"Izuna...?\""
1004606-280 = "Não foi forçado de jeito nenhum!"
1004606-281 = "Não é porque estou cansada...!"
1004606-282 = "A Izuna, a Izuna...!"
1004606-287 = "[wa:800]― （Por que será..."
1004606-289 = "― Desde que o Mestre disse que me ensinaria a nadar...)"
1004606-292 = "― (O coração da Izuna, [wa:1900] está muito... "
1004606-294 = "― Batendo forte...)"
1004606-297 = "[wa:900]― (A mão da Izuna, [wa:1250] que o Mestre segurou agora pouco,"
1004606-299 = "[wa:100]― e os outros lugares [wa:650] onde o Mestre me tocou..."
1004606-302 = "[wa:100]― Estão, [wa:1150] de alguma forma,"
1004606-304 = "[wa:150]― um pouco quentes...)"
1004606-307 = "[wa:850]― Ei, [wa:1200] Mestre. [wa:1500] Agora pouco, [wa:750] bem,"
1004606-309 = "― eu acabei ficando um pouco [wa:450] agitada, mas..."
1004606-312 = "― O dia de hoje..."
1004606-314 = "― Foi muito divertido e [wa:2000] eu fui muito feliz, Izuna!"
1004606-317 = "― Por isso, [wa:750] bem..."
1004606-319 = "[wa:150]― Como posso dizer, hum...!"
1004606-322 = "[wa:1000]― Se eu puder ser um pouco [wa:1650] egoísta..."
1004606-325 = "― Da próxima vez..."
1004606-327 = "[wa:100]― Você poderia me ensinar [wa:1200] a nadar [wa:750] mais uma vez?"
1004606-330 = "[ns] \"...Com todo o prazer.\""
1004606-331 = "― Ehehe..."
1004606-333 = "― Sim, [wa:950] muito obrigada!"
1004606-336 = "― Por favor,"
1004606-338 = "― continue cuidando [wa:350] de mim daqui para frente! [wa:1800] Mestre!"
1004606-341 = "(Assim, junto com a Izuna, que exibia um sorriso tão brilhante que não perdia nem para a cidade cintilando sob o pôr do sol)"
1004606-342 = "(Voltamos para casa lentamente, conversando sobre várias coisas)"
