[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 22/06.]
1004605-1 = "Treinamento de Fuga com a Izuna!"
1004605-4 = "Desculpe fazer você esperar, Meu Mestre!"
1004605-5 = "[s] \"Não se preocupe, eu não esperei quase nada. Mas hoje está bem quente, não é...\""
1004605-6 = "De fato, tem razão...!"
1004605-7 = "Na previsão do tempo, disseram que seria o dia mais quente dos últimos tempos..."
1004605-8 = "Sendo assim, o que vamos fazer no nosso treinamento ninja de hoje...?"
1004605-9 = "Temos que pensar num treinamento que seja perfeito para esse clima..."
1004605-10 = "[s] \"Com esse calor, a primeira coisa que vem à mente é...\""
1004605-11 = "!!"
1004605-12 = "S-Seria... nadar no mar...!?"
1004605-13 = "E-Er, b-bem... ahn...!"
1004605-14 = "Ah, lembrei de algo!"
1004605-15 = "Já que estamos aqui na praia...!"
1004605-16 = "Lembra daquele dia em que brincamos construindo os castelinhos de areia?"
1004605-17 = "Aquilo foi muito divertido, então o que acha da gente brincar com a areia de uma forma diferente!?"
1004605-18 = "[s] \"Ah, entendi. Uma brincadeira na areia parece legal.\""
1004605-19 = "Ehehe, eu achei que você ia gostar da ideia!"
1004605-20 = "...Ah!?"
1004605-21 = "M-Me desculpe, retiro o que eu disse! Não é uma 'brincadeira na areia'...!"
1004605-22 = "É um treinamento ninja utilizando a areia!"
1004605-23 = "O que você acha dessa ideia, Meu Mestre!?"
1004605-24 = "[s1] \"Ah, sim, se for isso eu adoraria ajudar.\"\n[s2] \"E que tipo de treinamento na areia seria esse?\""
1004605-27 = "Sim! É um treinamento que a Izuna acabou de inventar...!"
1004605-28 = "A ideia é você tentar escapar debaixo dessa areia quente..."
1004605-29 = "O 'Treinamento de Fuga do Banho de Areia'!"
1004605-30 = "[s] \"Fuga... do Banho de areia...?\""
1004605-32 = "Eu vi num drama de época esses dias!"
1004605-33 = "Enquanto os inimigos atacavam o castelo, a ninja fugia com o seu Mestre por uma passagem secreta..."
1004605-37 = "E no momento em que eles conseguiram sair a salvo, a ninja fez a passagem secreta inteira explodir: CABUUM!"
1004605-43 = "A terra e a areia voaram pra todo lado, causando pânico nos inimigos!"
1004605-44 = "Mas na pressa de proteger o Mestre, a ninja também acabou soterrada nos escombros!"
1004605-45 = "Será que ela se sacrificou...!? Enquanto a Izuna assistia com o coração na mão!"
1004605-47 = "Do meio da terra e dos escombros... A ninja saltou para fora lindamente e ilesa!"
1004605-48 = "[s] \"Ah, acho que entendi...\""
1004605-49 = "Isso mesmo! A Izuna quer fazer exatamente igual!"
1004605-50 = "Os ninjas precisam treinar para estar preparados para qualquer situação extrema..."
1004605-51 = "E com esse sol quente de hoje, o clima já está perfeitamente extremo!"
1004605-52 = "...Sendo assim, Meu Mestre!"
1004605-53 = "Meu Mestre, por favor, cubra a Izuna de areia!"
1004605-54 = "Eu vou provar que consigo escapar perfeitamente desse banho de areia!"
1004605-55 = "[s] (Será que... isso realmente conta como um treinamento?)"
1004605-59 = "[ns] \"Bem, pelo menos vamos fazer isso debaixo da sombra.\""
1004605-60 = "Sim!"
1004605-65 = "(Assim, a Izuna e eu fomos para a sombra fugir do sol forte e começamos o 'Treinamento de Fuga do Banho de Areia')"
1004605-66 = "[ns] \"Então, me avise se começar a ficar difícil de respirar ou apertado demais, ok?\""
1004605-67 = "Pode deixar, estou pronta!"
1004605-75 = "[ns] \"O que você acha dessa quantidade?\""
1004605-76 = "Erh, vamos testar pra ver... hyah!"
1004605-77 = "Ah, a Izuna ainda consegue escapar sem o menor problema!"
1004605-78 = "Meu Mestre, pode colocar mais areia!"
1004605-79 = "[s] \"E-Então tá bom...\""
1004605-84 = "[ns] \"Assim está bom?\""
1004605-85 = "Uhn... A Izuna ainda conseguiria escapar disso com facilidade."
1004605-86 = "Meu Mestre! Pode colocar muito mais!"
1004605-87 = "[s] \"O-Ok, então vou colocar mais...!\""
1004605-92 = "[ns] \"A-Acho que assim já está bom...\""
1004605-93 = "Ainda não chegamos a uma situação de perigo extremo!"
1004605-94 = "Por favor, coloque mais!"
1004605-98 = "[ns] \"Será que eu não passei dos limites da segurança!?\""
1004605-99 = "Ainda não, eu ainda consigo! Pode continuar colocando!"
1004605-100 = "[ns] \"N-Não consigo ver um limite nisso...!\""
1004605-105 = "(Depois daquilo, passei um bom tempo colocando mais areia em cima dela...)"
1004605-109 = "(E de dentro do monte, a Izuna não parava de pedir 'Mais!' e 'Mais!'...)"
1004605-110 = "[ns] \"Nossa, o monte ficou gigante...\""
1004605-114 = "(O monte de areia cresceu tanto que a Izuna praticamente desapareceu e virou uma verdadeira duna)"
1004605-118 = "[ns] \"Izuna, acho que já deu, né?\""
1004605-120 = "[ns] \"...Izuna?\""
1004605-122 = "[ns] \"IZUNA!?\""
1004605-134 = "[ns] \"Izuna, você está bem!?\""
1004605-135 = "Meu... Meeestre... mnyaa, mnyaaa..."
1004605-136 = "[s] \"...Hã?\""
1004605-137 = "Ehehe... vamos brincar mais... Meu Mestre..."
1004605-138 = "Já que estamos no verão... A Izuna quer brincar muito mais com o Meu Mestre..."
1004605-139 = "Muuuunyaah..."
1004605-140 = "[s] \"...Acho que ela acabou dormindo de tanto brincar.\""
1004605-144 = "[ns] \"...Vamos brincar bastante depois.\""
1004605-147 = "(Imediatamente, tirei com cuidado o excesso da areia para não deixar a Izuna soterrada)"
1004605-152 = "(Depois disso... fiquei lendo os meus livros e relaxando do ladinho da Izuna enquanto ela tirava uma soneca tranquila)"