[translation]
10047010-1 = "第1話;運命的な再会"
10047010-4 = "（休憩がてら、とある広場を訪れたところ……）"
10047010-8 = "[ns1] \"カッコイイ……。\"\n[ns2] \"どこかで聴いたことがあるような……。\""
10047010-12 = "う、ウソだろ？#nこんなすごい演奏を、女子高生が……！？"
10047010-13 = "このデスメタル……魂がたぎるぜ！！"
10047010-17 = "[ns] \"女子高生……デスメタル……。\""
10047010-22 = "[ns] \"ああ！この演奏は……！！\""
10047010-26 = "ふふ。みなさん、ありがとうございます。"
10047010-27 = "私の名は[ruby=しいな]椎名[/ruby]ツムギ。#n不思議の国から参りました。"
10047010-28 = "もっとも、童話の国など存在しませんが――"
10047010-33 = "――「フィーリング」。"
10047010-34 = "……は大事ですから。"
10047010-35 = "[ns] \"やっぱり、ツムギだったんだ！\""
10047010-39 = "おや？あなたは……。"
10047010-40 = "これは……思わぬ再会ですね。"
10047010-41 = "ああ……「あの子」の言っていた#n「巡り合い」とはこのことですか。"
10047010-42 = "なるほど……。#n運命の赤い糸は、フィクションではなかったのですね。"
10047010-47 = "せっかく再会したのです。#n少し、語り合いませんか？"
10047010-48 = "今日のライブは、もう幕を降ろしましたので。"
10047010-49 = "[s] \"喜んで！\""
10047010-50 = "では、参りましょうか。"
10047010-51 = "――不思議の国へ。"
10047010-52 = "[s] \"不思議の国って……。\""
10047010-56 = "[ns3] \"公園の森のこと？\"\n[ns4] \"会場のこと？\""
10047010-59 = "ふふっ……それは後のお楽しみということで。"
10047010-60 = "さあ、こちらへ。きっと忘れられない体験となるでしょう。"
10047010-65 = "不思議の国へようこそ。#n……さて、ご感想は？"
10047010-66 = "[s] \"ここ……普通のカフェだよね？\""
10047010-67 = "……先生。#n「不思議」とは、「普通と異なるもの」を意味するのですよ。"
10047010-68 = "先生と二人でカフェに来るのは、今日が初めてですよね？#nつまり、[ruby=・]普[/ruby][ruby=・]通[/ruby][ruby=・]と[/ruby][ruby=・]は[/ruby][ruby=・]違[/ruby][ruby=・]う[/ruby]状況。#nこれを「不思議」と言わずして、何と言いましょう？"
10047010-69 = "[s] \"たしかに、そう言われると……。\""
10047010-70 = "とはいえ……先生と生徒を結ぶ関係が#n「不思議」のままというのも……#n[ruby=いささ]些[/ruby]か寂しいではありませんか。"
10047010-71 = "ですから……いかがでしょう？#n物語をひとつ、進めてみるというのは。"
10047010-72 = "[s] \"お互いのことをもっと知りたいってことかな？\""
10047010-73 = "ふふ、それではまるで私がデートに誘っているようではないですか。"
10047010-74 = "いえ、否定はしませんよ。こういった展開では――"
10047010-79 = "――「エモーション」。"
10047010-80 = "……が大事ですから。"
10047010-81 = "ひとつ、聞かせてください。"
10047010-82 = "先日の私の公演……楽しんでいただけましたか？"
10047010-85 = "キェェェェェ！人間の死が社会の福祉だぁぁぁぁぁぁ！！！"
10047010-86 = "ウォェェェェェェェェェェェェッ！！！！"
10047010-89 = "先生？"
10047010-90 = "[s5] \"あ、えっと……。\"\n[s6] \"た、楽しかったよ……。\""
10047010-93 = "ふふ、それは良かったです。"
10047010-94 = "あのときは打ち上げにご招待できず、申し訳ありませんでした。#nメンバーが人見知りでして……。"
10047010-95 = "いつか先生にご紹介できるといいのですが。"
10047010-96 = "[s] \"みんな、ワイルドハントのバンド部なんだっけ？\""
10047010-97 = "いえ、さまざまな学園の生徒が集まっています。"
10047010-98 = "そもそも、ワイルドハントにバンド部はありませんので。"
10047010-99 = "ふふっ、「芸術学院」なのに、不思議ですよね？"
10047010-100 = "より正確に言うならば、公式の部活そのものが存在しないのです。"
10047010-101 = "学科の学びがそのまま芸術活動に繋がっているため、#n部活動をする必要はない――という方針なので。"
10047010-102 = "それでも、私のように別途許可を取れば、#n学外の子と活動することもできますし……。"
10047010-103 = "学内の同好の士で集まり、ひっそりと活動する子もいます。"
10047010-104 = "……ふむ。#nまだまだワイルドハントのことをご紹介したいのですが――#nこの場で語るには、どうにも余白が足りないようです。"
10047010-105 = "なのでここは端的に……#nワイルドハントとは、芸術家たちのための――#n「夢と希望のワンダーランド」のような場所なのです。"
10047010-106 = "[s] \"夢と希望のワンダーランド……？\""
10047010-107 = "夢や志を持って入学し、思うままに追求できる学院ですから。"
10047010-111 = "ああ、せっかくですし、いっそ……。"
10047010-115 = "この椎名ツムギが、先生のウサギを務めましょうか。"
10047010-116 = "[s] \"それは……どういう意味……？\""
10047010-117 = "さながら、少女をワンダーランドへと導いたウサギのように。#n私が先生をワイルドハントへご招待します。"
10047010-118 = "もちろん、本当のウサギではありませんが――"
10047010-123 = "――「雰囲気づくり」。"
10047010-124 = "……は大事ですから。"
10047010-125 = "私と共に学院を巡り、語り合いませんか？"
10047010-126 = "あわせて、寮の友人たちもご紹介できればと。"
10047010-127 = "みんなに先生の話をしたところ、目を輝かせておりまして。"
10047010-128 = "[s] \"いいね。私も楽しみだよ！\""
10047010-129 = "ふふ、では決まりですね。"
10047010-130 = "ただ、今は難しいので……。#nそれでは後日、じっくり見学といきましょうか。"
10047010-131 = "もちろん私は役目通りに、バニーガールの姿で――"
10047010-132 = "[s] \"そこまでしなくて大丈夫だよ！\""
10047010-133 = "ふむ……それは残念ですね……。"
10047010-134 = "バニーガールとギターは、#n「こちら側」でそれなりに歴史のある組み合わせなのですよ。"
10047010-135 = "先生にもぜひ、お見せしたかったのですが……。"
10047010-136 = "[s7] \"今回は……。\"\n[s8] \"普通の格好でお願いしたいかな。\""
10047010-139 = "ふっ……では次回以降のお楽しみということで。"
10047010-140 = "そろそろ注文しましょうか。メニューは……。"
10047010-145 = "……これは！#n先生、こちらをご覧ください。"
10047010-146 = "「一口でメロメロ。悪魔のスイーツフェア！」だそうです。"
10047010-147 = "こちらの「ベリーベリーケーキ」など、#n写真を見ているだけでメロメロになってしまいそうです……！"
10047010-148 = "[s] \"びっくりするくらいベリーが盛られてるね……。\""
10047010-149 = "ベリーが目玉のように見えるのも、とってもチャーミングですね。"
10047010-153 = "そういえば……#n寮にはこれと似たアクセサリーを好む先輩がいるんですよ。"
10047010-154 = "他にもいつもとんがり帽子をかぶっている子や、#n個性的なファッションの子……。"
10047010-155 = "……ふふ、ご紹介するのが楽しみです。"
10047010-156 = "[s9] \"個性的な子たちなんだね。\"\n[s10] \"面白そうな子たちなんだね。\""
10047010-163 = "（この時、私はまだ気づいていなかった）"
10047010-166 = "（物語は、すでに始まっていたことに……）"
