[translation]
10046100-1 = "夏、問題児、浜辺にて"
10046100-7 = "……はい？"
10046100-12 = "ですから、ビーチを一般開放することにしました。"
10046100-13 = "また、宣伝も兼ねてクロノススクールの報道部もお呼びしています。"
10046100-14 = "やっぱり、別荘の件が原因で……？"
10046100-15 = "いえ、それは関係ありませんので、ご心配なく。"
10046100-19 = "イチカさん……このビーチを、どう思いますか？"
10046100-20 = "えーっと……綺麗、ですね？"
10046100-21 = "同感です。私も、とても美しいと思っています。"
10046100-22 = "それを、ただ寝かせておくのは勿体ないと思いまして。#nせっかくなら、皆さんに使っていただこうかと。"
10046100-23 = "は、はぁ……いいお考えだと思います。"
10046100-24 = "それで……私が呼ばれた理由は……？"
10046100-25 = "一つ、お願いしたいことがありまして。"
10046100-26 = "このバカンスの期間中、ビーチのパトロールをしていただきたいのです。"
10046100-27 = "パトロール、ですか？"
10046100-28 = "ええ。夏休み真っ只中ですし、オープン直後は大勢の方で賑わうでしょう。#nその分、事件や事故が起きやすくなります。"
10046100-29 = "事と次第によっては、ティーパーティーが責任を問われることにもなりかねません。"
10046100-30 = "なるほど……。#n承知しました。"
10046100-31 = "急なお願いとなり、申し訳ありません。"
10046100-32 = "いえいえ。任せてください！"
10046100-33 = "ふふ、頼もしいですね。"
10046100-34 = "ですが、そこまでハードな任務にはならないとも思っています。#nどうにも私は心配しすぎるきらいがありますから。"
10046100-35 = "イチカさんも一人の観光客として、#n無理のない範囲で対応していただければ大丈夫ですので。"
10046100-41 = "早々、大きな問題など起こりませんから。"
10046100-46 = "ハーハッハッハッハ！！"
10046100-50 = "許可は得た！もはや邪魔するものはなにもないっ！！#nさあ、温泉開発に取りかかるぞ！！"
10046100-55 = "みんな！部長に続けーっ！！"
10046100-64 = "ふっふっふ、準備は整った。"
10046100-65 = "オープンしたてのビーチにまともな店があるわけねぇからな。#nがっぽり稼がせてもらおうぜ！"
10046100-66 = "この発想とフットワークの軽さ……うちら、商売の天才じゃない？"
10046100-68 = "あら？#nこちらのお店……焼きそばが7000円、アイスは3000円……なるほど。"
10046100-69 = "値段に見合うだけの自信がある……そう解釈してよろしいのでしょうか？"
10046100-70 = "美食研究会として、味見しないわけにはいきませんよね★"
10046100-89 = "はは、大きな問題なんて起こらない……。"
10046100-90 = "起こらない……。"
10046100-102 = "――起こさせないっす。"
