[translation]
1004103-1 = "Um corpo que não me obedece"
1004103-2 = "……。"
1004103-3 = "[s] \"……。\""
1004103-4 = "……Eu não pretendia encontrar o Sensei."
1004103-5 = "[s] \"De-desculpe……。\""
1004103-6 = "Então, o que você quer hoje?"
1004103-7 = "[s] \"Não é como se eu tivesse algum assunto em específico……。\""
1004103-8 = "Então, eu vou embora."
1004103-9 = "[s] \"E-espere!\""
1004103-10 = "……O que é agora?"
1004103-11 = "[s] \"Que tal tentarmos nos aproximar mais?\""
1004103-12 = "Para quê?"
1004103-13 = "[s] \"Bem…… o fato de termos nos conhecido assim, deve ser obra do destino……。\""
1004103-14 = "Não existe destino."
1004103-15 = "No fim das contas, os humanos não passam de náufragos presos em uma ilha deserta chamada corpo."
1004103-16 = "Nascemos sozinhos, vivemos sozinhos e morremos sozinhos. É assim que a vida funciona, não é?"
1004103-17 = "Por isso, essa ideia de fios que conectam as pessoas não passa de uma ilusão."
1004103-18 = "[s] \"Entendo……。\""
1004103-19 = "……。"
1004103-20 = "……Haa."
1004103-21 = "……Já chega, faça o que quiser."
1004103-22 = "Então, o que você quer que eu faça?"
1004103-23 = "[s] \"Bem…… que tal uma caminhada?\""
1004103-24 = "……。"
1004103-25 = "……Se isso for uma ordem."
1004103-27 = "……。"
1004103-28 = "[s] \"As flores estão bonitas, não estão?\""
1004103-29 = "Sim."
1004103-30 = "[s] \"Tem um rio ali.\""
1004103-31 = "……É mesmo."
1004103-32 = "[s] \"Ah…… bem……。\""
1004103-33 = "……。"
1004103-34 = "Qual o sentido de coisas que apenas existem por existir?"
1004103-35 = "[s] \"É, você tem razão……。\""
1004103-36 = "Não pretendo ficar aqui por muito tempo…… só vim porque foi uma ordem."
1004103-37 = "[s] \"A propósito, por que você está usando máscara agora?\""
1004103-38 = "……Não é nada. Bem, é só um pouco."
1004103-39 = "[s1] \"Por que não tira a máscara?\"\n[s2] \"É melhor respirar um ar puro.\""
1004103-40 = "N-não…… espere, mais do que isso… não se aproxime――"
1004103-41 = "N-não…… espere, mais do que isso… não se aproxime――"
1004103-42 = "Ha……! T――"
1004103-43 = "Atchim――！！"
1004103-44 = "[s] \"……！？\""
1004103-45 = "Atchim!"
1004103-46 = "Atchim!"
1004103-47 = "Atchi, atchim！！"
1004103-48 = "[s] \"……。\""
1004103-49 = "Tem…… tem pólen demais aqui……!"
1004103-50 = "[s] \"Misaki, agora há pouco……。\""
1004103-51 = "É por causa da rinite alérgica, sério…………… hein?"
1004103-52 = "[s] \"Misaki... o seu... nariz.\""
1004103-53 = "……eh?"
1004103-54 = "A-AAAAAAHHHHHHH!?!"
1004103-55 = "E-espera... onde estão os lenços...?!"
1004103-56 = "[s3] \"Espera um pouco!\"\n[s4] \"Se for um lenço...\""
1004103-63 = "(Algum tempo depois...)"
1004103-65 = "Haa..."
1004103-66 = "[s] \"V-você está bem, Misaki?\""
1004103-67 = "……vamos sair daqui logo."
1004103-70 = "[ns] \"Aqui, uma bebida.\""
1004103-71 = "……obrigada, Sensei."
1004103-72 = "Haa..."
1004103-73 = "……ter um corpo é o pior."
1004103-74 = "[s] \"Então você tem rinite alérgica...\""
1004103-75 = "Sim... mas, graças ao Sensei, consegui evitar o pior."
1004103-76 = "[s] \"Fico feliz com isso.\""
1004103-77 = "……."
1004103-78 = "[s] \"É um presente do destino entre mim e você, Misaki.\""
1004103-79 = "Para começar, a culpa foi sua, Sensei."
1004103-80 = "Tente ter um pouco de noção."
1004103-81 = "[s] \"Sinto muito...\""
1004103-82 = "……."
1004103-83 = "Mas, obrigada..."
1004103-84 = "……vou lavar o lenço e te devolver."
1004103-85 = "[s] \"Pode ficar com ele. Eu tenho lenços reservas.\""
1004103-86 = "……não pretendo ficar te devendo favores."
1004103-87 = "[s] \"……entendi.\""
1004103-88 = "Haa."
