[translation]
10041010-1 = "Episódio 1; A Prova de Si Mesma"
10041010-3 = "[log]1 semana atrás[/log]"
10041010-9 = "Por que motivo? Aliás, talvez você tenha esquecido, mas..."
10041010-10 = "Esquecido ou não, originalmente isso estava sob minha jurisdição. Estou apenas retomando."
10041010-11 = "Você, por acaso..."
10041010-12 = "—Acha que a \"Seia Yurizono\" não é capaz de fazer isso? #nÉ isso que você está pensando?"
10041010-16 = "Não é isso..."
10041010-20 = "[ns] \"...Hm?\""
10041010-21 = "Seia-chan, você está de mau humor hoje?"
10041010-22 = "Só percebeu agora? Bem, é típico de você..."
10041010-23 = "Não precisa ser tão grossa!"
10041010-24 = "Seia-san, por favor, acalme-se. #nMika-san, primeiro vamos ouvir o que a Seia-san tem a dizer."
10041010-25 = "Haa... Existe mesmo a necessidade de tecer mais palavras?"
10041010-26 = "A gente não tinha acabado de decidir que íamos conversar direito?"
10041010-27 = "Vocês duas... se continuarem assim, vão acabar achando que as integrantes do Chá das Cinco estão brigando."
10041010-28 = "Isso pode ser chamado de \"briga\"? #nO poder de decisão não está apenas com a Nagisa?"
10041010-29 = "Seia-chan!"
10041010-30 = "[ns1] \"Q-que aconteceu...?\"\n[ns2] Vou em direção ao som."
10041010-38 = "...?"
10041010-39 = "Sensei...?"
10041010-44 = "Por que você está aqui...?"
10041010-48 = "Você ouviu o que estávamos falando...? Bem..."
10041010-49 = "Não estávamos brigando, não! É só que..."
10041010-55 = "Haa..."
10041010-56 = "—Fui eu quem o chamei."
10041010-61 = "A Nagisa...?"
10041010-62 = "A Nagi-chan?"
10041010-64 = "Eu esperava que fosse apenas uma preocupação infundada, mas... por precaução."
10041010-65 = "Embora, idealmente, devêssemos resolver isso entre nós mesmas."
10041010-67 = "...Ah!"
10041010-68 = "Quando estivermos preocupadas ou com dúvidas, devemos conversar com alguém."
10041010-69 = "...Nós prometemos isso, não foi?"
10041010-70 = "Entendo... você tem razão."
10041010-71 = "Mas... chegar ao ponto de chamar o Sensei para tentar me convencer..."
10041010-72 = "Poxa, Seia-chan, acho que esse seu jeito de falar não é legal!"
10041010-74 = "Eu estou falando sério."
10041010-75 = "Isso é apenas porque me preocupo com o bem-estar da Seia-san."
10041010-76 = "Por favor, tente entender esse ponto..."
10041010-77 = "É isso mesmo! A Nagi-chan está dizendo isso porque se preocupa com a Seia-chan."
10041010-78 = "Embora ela sempre faça coisas que geram mal-entendidos...!"
10041010-79 = "Mika-san..."
10041010-85 = "[ns3] \"Pode me contar os detalhes?\"\n[ns4] \"Vocês duas devem ter seus motivos, então vamos conversar.\""
10041010-89 = "Acho que a Seia-san é mais qualificada para isso do que eu."
10041010-90 = "Se não se importar, poderia explicar?"
10041010-95 = "...Surpreendente."
10041010-96 = "Lembro-me de que a Nagisa que eu conheço não costumava agir dessa forma."
10041010-98 = "Acho que todo mundo tem dias assim, não acha...?"
10041010-99 = "A Nagi-chan está falando isso por causa da Seia-chan..."
10041010-103 = "Nagi-chan..."
10041010-109 = "...Foi um deslize da minha parte. Peço desculpas."
10041010-110 = "Eu entendo. Que vocês precisam de uma base sólida para se convencerem..."
10041010-111 = "Não, que vocês precisam de uma base que os deixe 'tranquilos'."
10041010-112 = "Claro, não há motivos para duvidar das palavras da Nagisa."
10041010-113 = "Mas, se vocês estão preocupados comigo..."
10041010-114 = "Não seria justo que eu também tivesse esse direito?"
10041010-115 = "Seia-san..."
10041010-116 = "…Sinto muito, Sensei. Tomei seu tempo com assuntos internos. Deixe-me explicar a situação."
10041010-117 = "[s5] \"Obrigado, pode deixar comigo.\"\n[s6] \"O que aconteceu?\""
10041010-120 = "…Estamos em um impasse sobre quem participará da próxima \"EXPO Millennium\" como representante da Trinity."
10041010-123 = "A EXPO Millennium é um grande evento de exibição tecnológica organizado pela Millennium Science School. Desta vez, a Trinity também participará com o objetivo de promover o intercâmbio entre os alunos."
10041010-124 = "E lá... Nagisa e eu, ambas insistimos que deveríamos ser as representantes."
10041010-125 = "…Ultimamente, a carga de trabalho da Nagisa dobrou. #nEla deve estar acumulando muita fadiga."
10041010-128 = "Ela já está vivendo no limite. #nNão acredito que ela ainda tenha energia sobrando para lidar com a diplomacia."
10041010-129 = "Além disso, esse tipo de tarefa costumava ser minha responsabilidade."
10041010-130 = "Claro, ainda hoje, preencho todos os requisitos para ser parte do Tea Party."
10041010-131 = "…Mas a Nagisa não cede, dizendo que minha recuperação e segurança devem vir primeiro."
10041010-132 = "É verdade que o estado da Seia-san melhorou. Mas isso é apenas relativo."
10041010-133 = "Houve uma remissão, mas não posso dizer que está totalmente curada. #nIsso não é apenas minha opinião pessoal, é também o parecer do Esquadrão de Socorro."
10041010-134 = "E mais, a Seia-san perdeu sua maior arma: a capacidade de prever o futuro. #nEla não teria como se preparar para imprevistos."
10041010-138 = "Do meu ponto de vista, a Seia-san é nada menos que alguém que precisa de proteção."
10041010-143 = "De novo com esse assunto?"
10041010-144 = "Nesse aspecto, a Mika-san seria uma escolha mais segura."
10041010-145 = "O que a Nagi-chan pensa de mim, afinal?"
10041010-146 = "A área ao redor da Millennium Science School é relativamente segura. #nA probabilidade de se envolver em crimes não é tão alta."
10041010-147 = "No entanto, experimentos bizarros são realizados diariamente, #ne é um fato que o número de acidentes causados por isso é muito maior do que em outras escolas."
10041010-148 = "Se, por um acaso, a Seia-san sofresse um acidente inesperado..."
10041010-149 = "Nagisa, você tem alguma garantia de que você não se envolveria em um acidente?"
10041010-150 = "…Estou falando da Seia-san. Isso não tem nada a ver comigo."
10041010-152 = "Isso não soa meio errado...?"
10041010-156 = "E aliás, por que eu não estou entre as candidatas?"
10041010-157 = "Mika-san, sua posição atual como \"representante da Trinity\" é um pouco complicada..."
10041010-161 = "Ah... ehehe. É verdade, desculpe."
10041010-162 = "Se a Mika fosse, eu ficaria preocupada pensando em que tipo de problema ela causaria desta vez."
10041010-163 = "…."
10041010-164 = "[s7] \"…Bem, fico feliz que tenham conseguido conversar.\"\n[s8] \"Eu gostaria de apoiar o desejo da Seia.\""
10041010-170 = "Sensei, agradeço as palavras, mas agora..."
10041010-171 = "…Eh?"
10041010-172 = "Você concorda com a Seia-san?"
10041010-178 = "…Com a Seia-san?"
10041010-180 = "Sensei?"
10041010-181 = "…Comigo?"
10041010-182 = "[s9] \"Se eu for junto, não deve ter problema, certo?\"\n[s10] \"Se acontecer qualquer coisa, eu entro em contato imediatamente.\""
10041010-187 = "Nossa..."
10041010-188 = "Que inesperado... Será que não foi um erro chamar o Sensei para isso?"
10041010-189 = "…Depende de ela aceitar ou não."
10041010-194 = "Bem..."
10041010-195 = "Entendo... Então esse é o pensamento do Sensei."
10041010-208 = "Ufa..."
10041010-209 = "Entendido. Então faremos como o Sensei sugeriu."
10041010-214 = "…Nagisa?"
10041010-215 = "Você admite tão facilmente assim!?"
10041010-216 = "Tem certeza mesmo...? Nagi-chan."
10041010-221 = "Qual é exatamente a imagem que vocês têm de mim...?"
10041010-222 = "Não é que eu queira proibir a Seia-san de sair. #nÉ apenas que coloco a segurança dela em primeiro lugar."
10041010-223 = "Honestamente, mesmo que o Sensei acompanhe a Seia-san, é difícil acreditar que a segurança dela esteja garantida."
10041010-224 = "Sim, eu sei muito bem que sou uma pessoa preocupada."
10041010-225 = "Além disso, tratando-se do Sensei, que já nos ajudou inúmeras vezes até agora..."
10041010-226 = "Desta vez também, se for o Sensei, ele dará um jeito, eu..."
10041010-227 = "Sim... eu acredito nisso."
10041010-228 = "[s11] \"Obrigada, Nagisa.\"\n[s12] \"Com certeza vai dar tudo certo. Não se preocupe.\""
10041010-231 = "Sim... por favor, que tudo termine bem."
10041010-237 = "...Nagisa."
10041010-239 = "Você confia no Sensei, não é... e não em mim."
10041010-243 = "[log]Atualmente[/log]"
10041010-247 = "Eu mesma entendo isso melhor do que ninguém. No fim das contas, isso é... um problema meu."
10041010-248 = "「A Seia Sonozaki que perdeu o poder da profecia não tem valor」"
10041010-249 = "...Eu sei muito bem que aquelas duas não pensam assim."
10041010-250 = "No entanto, eu também não passo de uma criança. #nNão consigo controlar minhas emoções completamente."
10041010-251 = "No fim das contas, sou um ser incompleto, frágil... e em pleno desenvolvimento."
10041010-252 = "É justamente por isso que eu não podia abrir mão de participar da Millennium EXPO."
10041010-253 = "Se eu conseguisse concluir isso, eu mesma poderia me reconhecer... foi o que pensei."
10041010-254 = "...Acabei arrastando o Sensei para o meu capricho, não é."
10041010-255 = "[s13] \"Não é nada disso.\"\n[s14] \"É um processo necessário. Não é algo ruim de forma alguma.\""
10041010-258 = "Você de novo..."
10041010-259 = "Entendo. Sinto-me um pouco mais aliviada."
10041010-260 = "...Sendo assim."
10041010-261 = "Poderia me fazer um favor?"
10041010-262 = "Para que eu possa \"provar\" através desta provação."
10041010-263 = "...Para que eu possa sentir que consigo caminhar com minhas próprias pernas."
10041010-264 = "As atividades desta Millennium EXPO..."
10041010-265 = "Sensei, você poderia, separadamente..."
10041010-272 = "...Chegamos?"
10041010-273 = "Por enquanto... explicarei mais tarde."
