[translation]
10043020-1 = "Episódio 2: Me acorde quando virar o jogo"
10043020-3 = "……A energia no estádio está aumentando."
10043020-4 = "Os gritos estão ficando muito altos. Com tanta intensidade assim……"
10043020-5 = "[s] \"Assistir esportes é empolgante, né?\""
10043020-6 = "……É verdade."
10043020-7 = "Sinto algo estranho."
10043020-11 = "[ns] \"Por quê?\""
10043020-12 = "……Estava lembrando um pouco das atividades do Clube de Treinamento."
10043020-15 = "O treinamento é a competição individual definitiva."
10043020-16 = "Exercícios, controle rigoroso da dieta, esforço diário para buscar o melhor resultado."
10043020-17 = "Em certo sentido, poderíamos chamar de um caminho de busca espiritual."
10043020-20 = "Tudo é feito pela própria vontade――"
10043020-21 = "Se um terceiro se envolve, é apenas para receber conselhos."
10043020-22 = "O objetivo final é alcançar o físico ideal."
10043020-23 = "Por isso, continuo em uma partida contra mim mesma."
10043020-24 = "[s] \"É profundo……!\""
10043020-25 = "Mas……"
10043020-29 = "No beisebol, não é assim."
10043020-30 = "Dizer que é apenas rebater a bola, marcar pontos e competir pelo resultado é simples."
10043020-31 = "Mas, na verdade, exige jogadores talentosos, um técnico, a união da equipe……"
10043020-32 = "……Senti que este esporte só funciona quando todos os elementos se encaixam."
10043020-33 = "Entendo por que todos ficam tão entusiasmados."
10043020-34 = "Apenas……"
10043020-35 = "Será que essas pessoas nas arquibancadas estão realmente \"entusiasmadas\"?"
10043020-36 = "Nossa missão é encontrar pessoas suspeitas――"
10043020-37 = "E investigar se são os culpados…… mas……"
10043020-38 = "Pelo que vejo……"
10043020-39 = "――Todos são suspeitos."
10043020-44 = "Meus queridos fãs dos Braves!"
10043020-45 = "Hoje…… as vozes reais de todos no estádio――"
10043020-52 = "Saiam da frente! Saiam logo!"
10043020-53 = "Aquele streamer veio de novo!"
10043020-60 = "Aquele cara deve ser um espião dos Raiders!"
10043020-61 = "Deve estar fazendo um vídeo de \"compilado da derrota dos Braves\"!"
10043020-67 = "Como só perdemos, não tem como evitar……"
10043020-72 = "Por que são tão ruins!? #nEu não faria melhor!?"
10043020-73 = "Hã!? Impossível você fazer melhor."
10043020-79 = "……"
10043020-80 = "B-bem…… o estádio é sempre assim……"
10043020-81 = "[s] \"O que é isso……\""
10043020-82 = "Diga, Treinadora……"
10043020-83 = "O que eu conheço por \"torcida\" parece um pouco diferente disso……"
10043020-84 = "[s1] \"Talvez eles fiquem bravos justamente porque se importam……\"\n[s2] \"Senão, não ficariam tão emocionais……\""
10043020-87 = "Mas, desse jeito……"
10043020-91 = "Pessoal, rezando pela vitória dos Braves――"
10043020-93 = "Hã? Não tem como ganhar, seu idiota!"
10043020-94 = "Ah…… só de olhar já fico irritado!"
10043020-100 = "Arremessador! Já chega! Joga de qualquer jeito!"
10043020-101 = "Isso mesmo! Perde logo de uma vez!"
10043020-102 = "Torcer para um jogo desses é perda de tempo!"
10043020-108 = "Com licença, passando..."
10043020-113 = "Ué? É a vendedora de bebidas?#n Me dá alguma coisa aí!"
10043020-114 = "Isso, tem alguma bem gelada?"
10043020-119 = "Aqui está."
10043020-126 = "Valeu... Pff!#n M-mas que gororoba é essa...!"
10043020-127 = "O normal não seria um refrigerante ou algo assim!?"
10043020-129 = "Este é um shake de proteína."
10043020-130 = "Removi a lactose e a gordura para evitar má digestão e..."
10043020-131 = "utilizei whey protein de rápida absorção."
10043020-132 = "É rico em aminoácidos e proteínas, faz muito bem para o corpo."
10043020-133 = "Mas, por favor, não beba tudo de uma vez. Pode sobrecarregar o seu trato digestivo."
10043020-138 = "Quem é que bebe proteína num estádio de beisebol?!"
10043020-139 = "Ei, você, vem aqui fora agora!"
10043020-144 = "..."
10043020-145 = "Lançando insultos extremamente agressivos..."
10043020-146 = "com um comportamento que parece desejar a derrota do próprio time..."
10043020-147 = "E, além disso, recusar uma proteína saudável..."
10043020-152 = "...Q-que resmungos são esses?!"
10043020-157 = "— Treinador."
10043020-158 = "Esses dois são os culpados, não são?"
10043020-162 = "[ns] \"Por que você chegou a essa conclusão!?\""
10043020-163 = "Todos aqui estão em um estado de euforia, mas..."
10043020-164 = "entre eles, esses dois se destacam por comentários particularmente agressivos."
10043020-165 = "O culpado do telefonema também apresentava um comportamento anormal. Ou seja..."
10043020-166 = "— Esses dois são os culpados!"
10043020-171 = "Ficou aí falando um monte de besteira..."
10043020-172 = "Se veio comprar briga com a gente, espero que esteja preparado!"
10043020-177 = "Então, Treinador."
10043020-178 = "Vamos proceder com a detenção."
10043020-179 = "[s] \"S-será que isso é mesmo uma boa ideia...?\""
10043020-180 = "Sim. Por favor, confie em mim!"
10043020-181 = "Como esses dois parecem ter perdido a razão..."
10043020-182 = "precisamos ajudá-los a esfriar a cabeça."
10043020-183 = "[s] \"É... é hora do treinamento pessoal...!\""
10043020-187 = "Suar com exercícios ajuda a aliviar o estresse..."
10043020-188 = "O treinamento é eficaz até mesmo em situações como esta."
10043020-190 = "Não sei que tipo de loucura você está falando!"
10043020-191 = "Não vou deixar barato!"
