[translation]
1005303-1 = "segredos de culinária científica"

1005303-2 = "Escola de Ciências do Milénio/Sala de Economia Doméstica"

1005303-4 = "Eh...sensei?"

1005303-5 = "P-por que você está aqui...?"

1005303-6 = "[s1] \"Ouvi dizer que Yuuka iria praticar culinária aqui...\"\n[s2] \"Eu queria ajudar Yuuka.\""

1005303-7 = "Ugh... eu não esperava que o Sensei viesse..."

1005303-8 = "Ugh... eu não esperava que o Sensei viesse..."

1005303-9 = "...Se eu soubesse, teria me vestido mais adequadamente."

1005303-10 = "[s] \"...Talvez tenha sido um incômodo?\""

1005303-11 = "Isso não é verdade!"

1005303-12 = "Mas... eu não queria mostrar minha aparência constrangedora para a Senseia."

1005303-13 = "Estava pensando em esperar melhorar antes de pedir para a Senseia comer..."

1005303-14 = "[s] \"Yuka está cozinhando...\""

1005303-15 = "...O que é esse rosto?"

1005303-16 = "Talvez você não possa comer minha comida?"

1005303-17 = "Não tenho experiência culinária, mas minha teoria é perfeita e tenho certa confiança."

1005303-18 = "Cozinhar é o processo de aquecer e misturar ingredientes para torná-los fáceis de comer."

1005303-19 = "Durante esse processo, os alimentos passam por inúmeras mudanças físicas e científicas."

1005303-20 = "Especialistas dizem que compreender a ciência é essencial para se tornar um cozinheiro melhor."

1005303-21 = "Em outras palavras...mesmo tendo um conhecimento perfeito de ciências, nunca falho na cozinha! #nNão é mesmo, senhor?"

1005303-22 = "[s3] \"Acho que há algumas semelhanças...\"\n[s4] \"Então, o que Yuuka faz?\""

1005303-23 = "É recomendado neste popular livro de receitas chamado ``Até os iniciantes podem fazer isso! Lancheiras fáceis que você pode usar todos os dias.''"

1005303-24 = "É recomendado neste popular livro de receitas chamado ``Até os iniciantes podem fazer isso! Lancheiras fáceis que você pode usar todos os dias.''"

1005303-25 = "Bardana Kinpira e ovo frito... e depois quero a linguiça de polvo padrão. #nSe isso for suficiente, até eu consigo..."

1005303-26 = "Ok, vamos começar preparando a raiz de bardana."

1005303-27 = "Qual...Para tirar a espuma, adicione 1 colher de sopa de vinagre em 2L de água..."

1005303-31 = "Bem..."

1005303-32 = "[s] \"O que há de errado?\""

1005303-33 = "……Sensei."

1005303-34 = "Esta receita não especifica a temperatura da água. #nQuantos graus de água você espera?"

1005303-35 = "[s] \"Quantas vezes é suficiente?\""

1005303-36 = "Não é bom! #nO volume da água muda dependendo da temperatura!"

1005303-37 = "Se seguir a receita terá que ajustar a temperatura! #n Diferenças na temperatura da água podem causar erros de densidade!"

1005303-38 = "Supondo que a diferença de densidade ocorra até 0,040g/ml devido à temperatura da água, a faixa de erro máxima é de 80g..."

1005303-39 = "E se a raiz de bardana azedar porque foi cozida em água a uma temperatura mais alta do que a receita espera?"

1005303-40 = "[s5] \"Você não precisa se preocupar com isso.\"\n[s6] \"Calma, Yuka. Vamos continuar.\""

1005303-41 = "Nossa, estou preocupado...."

1005303-42 = "Nossa, estou preocupado...."

1005303-44 = "(No entanto, as preocupações de Yuka continuaram mesmo depois disso.)"

1005303-46 = "Ei, Sensei, o que devo fazer? #nA receita leva açúcar mascavo, mas só temos açúcar branco na sala de treinamento!"

1005303-47 = "E se ocorrer uma reação química inesperada devido à adição de açúcar branco?"

1005303-49 = "Diz \"ferva por cerca de 2 minutos a cerca de 60 graus\"... mas quando medi agora, estava 50 graus...!"

1005303-50 = "Quantos segundos devo aquecê-lo neste caso? ? #nQuanto é “moderado” por cerca de 2 minutos? ?"

1005303-52 = "Bem, Senseia...! #nEste tamagoyaki é cozido perfeitamente! ?"

1005303-53 = "Não ria, por favor diga alguma coisa!"

1005303-57 = "Finalmente..."

1005303-58 = "Está concluído! Este é meu primeiro bento!"

1005303-59 = "[s] \"Obrigado pelo seu trabalho duro. Você trabalhou duro por três horas.\""

1005303-60 = "Bem, não pode ser ajudado!"

1005303-61 = "Foi a minha primeira vez e foi difícil ajustar o calor. #nE acima de tudo..."

1005303-62 = "...[NOME DE USUÁRIO]Não quero me ver fracassando na frente do meu Sensei."

1005303-63 = "[s] \"Você foi muito bom nisso.\""

1005303-64 = "Porém, se demorar 3 horas, pode ser difícil prepará-lo na manhã do festival."

1005303-65 = "Acho que vou pedir uma caixa de bento com antecedência ou pedir a um amigo que faça isso para mim."

1005303-71 = "Essa lancheira... o Sensei deveria comê-la."

1005303-72 = "[s] \"É a primeira vez que faço isso, posso aceitar?\""

1005303-73 = "sim. Se fosse Sensei... não, prefiro ser Sensei."

1005303-77 = ", claro, significa que gostaria que você avaliasse o sabor. #nRealmente, isso é tudo!"

1005303-83 = "...Mas quando você terminar de comer...#nPor favor, me diga o que você pensa."

1005303-85 = "(Depois, o bento que Yuka fez foi trazido de volta à placa de Petri e comido como lanche da meia-noite.)"

1005303-86 = "(...A lancheira deveria estar fria, mas de alguma forma estava quente e deliciosa.)"

