[translation]
10052075-9 = "Uau! Não há limite!"

10052075-13 = "Midori! Você ainda tem balas?"

10052075-28 = "Parece que vai acabar em breve..."

10052075-29 = "esse! É sua última revista, então use com cuidado, ok?"

10052075-31 = "Midori no Ha! ?"

10052075-32 = "Eu... ainda tenho metade dela!"
10052075-33 = "Não importa o quanto eu seja tratado como importante, a quantidade de inimigos é..."
10052075-34 = "É apenas hora de ganhar dinheiro."

10052075-38 = "[log]Luz! ! ![/log]"

10052075-44 = "Alice!!!"
10052075-45 = "Moim, Midori! Está tudo bem? Alice, você se juntou?"
10052075-46 = "sim! Perfeito!"

10052075-47 = "Hehe, Sensei. Como foi dirigir minha cadeira de rodas?"

10052075-48 = "Hirami-senpai, isso é... em bicicletas..."
10052075-49 = "Cadeira de rodas."
10052075-50 = "sim... "
10052075-54 = "Então, Sensei, você está bem? ? A tez...!"

10052075-55 = "[s]\"Está tudo bem... mas...\""

10052075-56 = "Da próxima vez vou levar remédio para enjôo comigo..."

