[translation]
10051005-1 = "Prólogo; Lámen e Conspiração"
10051005-3 = "[log]Como um ninja, nunca se esqueça disso.[/log]"
10051005-6 = "[log]Macarrão bem grosso![/log]"
10051005-8 = "[log]Adicione gordura das costas![/log]"
10051005-12 = "[log]E para finalizar, um fio de óleo de pimenta![/log]"
10051005-15 = "Uma loja de lámen em algum lugar de Hyakkiyako"
10051005-16 = "Este é o estilo ninja! Um novo método para saborear lámen!"
10051005-17 = "É o... \"Novo Conjunto Ninja\"!"

10051005-18 = "Pessoal, obrigado por esperarem! Nin-nin!"
10051005-19 = "O \"Diário Ninja da Michiru\"! Edição Ninja e Lámen!"

10051005-20 = "Começando!!!"
10051005-21 = "……Ah, espere um pouco!"
10051005-22 = "A câmera não está meio torta?"
10051005-23 = "Será que é o tripé……?"
10051005-24 = "Hã!? De, desculpe…… #nSe eu tivesse tomado mais cuidado……"
10051005-25 = "Não, não, fui eu quem ajustou."
10051005-26 = "Sem preocupações! Vai dar tudo certo se gravarmos de novo!"
10051005-27 = "Então, recompondo-nos――"
10051005-29 = "CRASH!"
10051005-32 = "Gerente! O que aconteceu com esse caldo!? #nEstá tão ralo que nem gruda no macarrão!"
10051005-33 = "O ponto do macarrão também não está bom!"
10051005-34 = "A harmonia entre o macarrão e o caldo sumiu!"
10051005-35 = "Não, a nossa receita de lámen é a mesma há anos……"
10051005-36 = "E mais importante! #nSó porque não gostou do sabor, não pode sair virando a mesa!"
10051005-37 = "Isso incomoda os outros clientes!"
10051005-42 = "O... o lámen atingiu a câmera em cheio, e ela……!"
10051005-43 = "Ugh…… ugh……"
10051005-44 = "Acabou……!"
10051005-45 = "Bu, Manager (Chefe)…… o que faremos agora……"

10051005-46 = "……"
10051005-50 = "(Ah, droga!! Aquele cliente problemático……! Não posso deixar passar assim――)"
10051005-51 = "(Mas…… será que eu consigo vencer eles?)"
10051005-55 = "(Não, eu não estou sozinha……)"
10051005-56 = "(Tsukuyo e Izuna estão comigo……!)"
10051005-57 = "……Como um ninja, mesmo em qualquer situação de aperto――"
10051005-58 = "Nunca se deve virar as costas para a injustiça……!"
10051005-59 = "Oh? O que foi?"
10051005-60 = "Chefe……?"
10051005-64 = "Tome isso! Arte Ninja: Técnica do Fogo Cintilante!"
10051005-72 = "Guaaa…… hã? Não aconteceu…… nada?"
10051005-73 = "……Fogos de artifício?"
10051005-74 = "Só está brilhando e não dói nem coça?"
10051005-75 = "De qualquer forma, isso significa que você comprou uma briga……!"
10051005-76 = "E o que é essa tal de arte ninja?"
10051005-77 = "Isso eu não――"
10051005-85 = "Por favor…… fique atrás de mim!"
10051005-86 = "Ah, obrigado!"
10051005-95 = "Ugh……!"
10051005-96 = "Distrair a atenção para atacar pelas costas, que covardia……"
10051005-101 = "Hehehe, distrair o oponente e atacar pelas costas. Isso sim é――"
10051005-102 = "O verdadeiro uso da 'Arte Ninja: Fogo Cintilante!'"
10051005-103 = "Como esperado da nossa chefe!#nEntão essa é a estratégia de que 'três ninjas juntos podem até domar um tigre'!"
10051005-104 = "Com certeza!"
10051005-105 = "……Ué, é mesmo?"
10051005-106 = "A-ah, com licença……."
10051005-107 = "Tsukuyo? O que houve?"
10051005-108 = "Eu limpei a sopa que caiu, mas……."
10051005-110 = "A câmera…… não quer ligar……!"
10051005-111 = "……."
10051005-112 = "……."
10051005-114 = "Eeeehhhhh!?"
10051005-118 = "Hum……."
10051005-119 = "Movimentos ágeis e precisos…… e ainda se preocupou com a segurança do dono da loja……."
10051005-120 = "Nyahaha. Desse jeito, talvez possamos até confiar a vocês uma missão de escolta……."
10051005-121 = "Eu já conhecia as habilidades do Clube de Pesquisa de Ninjutsu há algum tempo…… mas não esperava descobrir algo novo."
10051005-122 = "……Sendo assim."
10051005-123 = "Talvez não seja uma má ideia…… selecioná-las para 'aquela missão'?"
