[translation]
10056070-1 = "Episode 7; Blue Hole"
10056070-2 = "(The ship parted the waves as it moved towards its destination.)"
10056070-6 = "Sensei, we're here."
10056070-7 = "This is the spot marked on the map."
10056070-13 = "(The ship had stopped, so I went outside to take a look.)"
10056070-14 = "(In the midst of the vast ocean was a single spot dyed dark blue, as if someone#nhad dropped ink of a different color onto it.)"
10056070-15 = "[ns] \"...It has quite a mystical vibe to it.\""
10056070-18 = "Yes... But only from the surface."
10056070-19 = "Blue holes are formed when normal or karst caves become submerged, #nso if you venture too deep into one, you may not be able to find your way out."
10056070-20 = "That's why it's rewarding to tackle one on, yet equally as dangerous to do so."
10056070-21 = "Therefore, it's important that we be even more thorough than usual with our#npreparations!"
10056070-22 = "Is it even possible to be more meticulous?"
10056070-23 = "O-of course it is!"
10056070-24 = "Everything we check twice should be triple checked, and anything we check three#ntimes should be checked four times—"
10056070-25 = "The sun will have set by the time we finish doing all of that..."
10056070-26 = "Should we choose who will diving first?"
10056070-27 = "Me! Me me me! #nSayuri and I will go first!"
10056070-28 = "Really, Makina?"
10056070-29 = "Yep."
10056070-30 = "I was responsible for what happened this time, after all..."
10056070-31 = "B-but since we don't know what kind of dangers might be down there, as the club president, I should go first..."
10056070-32 = "Isn't it equally dangerous, no matter who goes anyway?"
10056070-33 = "Come on, you're worrying way too much. If it gets dangerous, we'll head back up#nimmediately."
10056070-37 = "Sayuri is fiirst~"
10056070-38 = "Wh-when you come up, be sure to go slowly, alright!?"
10056070-40 = "(Makina and Sayuri listened to Kokoro's frantic warnings before plunging into the ocean.)"
10056070-44 = "(Around an hour later...)"
10056070-47 = "Phew..."
10056070-52 = "Welcome back. You two returned faster than expected."
10056070-53 = "D-did something go wrong?"
10056070-54 = "Nope. The dive was a-okay."
10056070-55 = "There were whales!"
10056070-56 = "[s] \"Whales?\""
10056070-57 = "A pod of humpback whales swarmed in, so we couldn't dive any deeper. #nThis happened around 60 meters down."
10056070-58 = "I've never seen anything like this before... I wonder what happened?"
10056070-59 = "Perhaps there are predators further down below, #nlike that time with the sharks."
10056070-60 = "I didn't see anything that looked particularly dangerous though."
10056070-61 = "It's the Lusca…!"
10056070-62 = "Like I said, that's just a [ruby=UMA]cryptid[/ruby]."
10056070-67 = "Could it really be the treasure from then...?"
10056070-68 = "...Prez?"
10056070-72 = "N-no, it's nothing."
10056070-73 = "Anyway, good work. Kotone and I will go next."
10056070-74 = "Roger."
10056070-80 = "Ah, a seagull."
10056070-81 = "...That, it is."
10056070-86 = "Now a flying fish."
10056070-87 = "...You're right."
10056070-91 = "..."
10056070-92 = "[s] \"Is there something you want to ask?\""
10056070-93 = "Huh? Ah, no."
10056070-94 = "It's just that waiting around and doing nothing feels weird."
10056070-99 = "...So, um."
10056070-100 = "As Schale's Sensei, you have extrajudicial powers, right?"
10056070-101 = "Does that mean you can freely order students around or give them instructions on#nwhat to do?"
10056070-102 = "[s1] \"Pro...bably?\"\n[s2] \"Technically, I believe so.\""
10056070-105 = "Then could you get anything you want?"
10056070-106 = "Like, could you yoink 100k from a student?"
10056070-107 = "[s3] \"No way...\"\n[s4] \"Even if I could, I wouldn't.\""
10056070-110 = "If you have all that power, why do you only listen to your students?"
10056070-111 = "[s] \"What do you mean?\""
10056070-112 = "Like, you could totally resolve this current problem with a single word."
10056070-113 = "You could easily just order us to quit diving and that would be the end of it."
10056070-114 = "[s] \"You want to quit the Diving Club?\""
10056070-115 = "Of course not!"
10056070-116 = "But Island's all caught up in a fix 'cause of us."
10056070-117 = "From your perspective, aren't they your students too?"
10056070-118 = "[s] \"Of course.\""
10056070-119 = "You say its for us students' sakes, but it feels like all you do is wait for us to solve#nthings ourselves."
10056070-120 = "Whenever we get stuck struggling at a dead end..."
10056070-121 = "Don't you find it frustrating to watch?"
10056070-122 = "[s] \"It happens sometimes.\""
10056070-123 = "Can't you just finish things for us?"
10056070-124 = "[s5] \"I can't.\"\n[s6] \"I don't have that sort of authority.\""
10056070-130 = "Why? Don't you have the authority to order us around and instruct us on what to do?"
10056070-131 = "[s7] \"It's nothing more than 'instructing' at the end of the day.\"\n[s8] \"The ones who do something with those instructions, are the students themselves.\""
10056070-134 = "Hmm...? #nFeels like you're trying to dodge the question..."
10056070-135 = "You're smelling like a fishy grown up..."
10056070-136 = "Makina, Makina."
10056070-137 = "What's up? Is Prez back?"
10056070-138 = "Nope. There's someone coming over from the horizon."
10056070-139 = "But there's no shipping lanes in this area. #nWe're also too far out for that to be a Trident patrol..."
10056070-140 = "...Look, their flag."
10056070-144 = "Isn't that—!?"
10056070-145 = "The Sea Dragon's flag!?"
10056070-146 = "[s] \"They're that problem student, right?\""
10056070-147 = "Problem student is an understatement!"
10056070-148 = "The Sea Dragon's the honcho of Odyssey... No, Kivotos' most fearsome pirate#ncrew!"
10056070-149 = "Sensei, you have to run awa—"
10056070-150 = "Nevermind, how would you run away out here?"
10056070-151 = "For now, hide! #nSayuri, tell the Prez that pirates are coming!"
10056070-152 = "Mayday mayday!"
10056070-159 = "...Sensei!"
10056070-160 = "Ugh, how did they manage to sneak up on us..."
10056070-161 = "They're quite close already. It'll be difficult for us to return to the boat."
10056070-162 = "What should we do?"
10056070-163 = "Let's conduct a body check first. Any problems?"
10056070-164 = "No problems."
10056070-165 = "Sayuri, Makina said it was the Sea Dragon, right?"
10056070-166 = "Ye. Sayuri saw the flag too."
10056070-167 = "I don't know when they managed to secure such a fleet, but... #nJudging from how shallow their drafts are, they likely are not carrying much#nequipment."
10056070-168 = "Let's dive again to figure out where—"
10056070-169 = "It would be in your best interests to give up on trying anything foolish."
10056070-170 = "Your crew and Sensei are already in my hands."
10056070-174 = "When did they...?"
10056070-177 = "Sorry, Prez..."
10056070-178 = "We tried to buy you time until you surfaced, but..."
10056070-179 = "Sensei got snatched away..."
10056070-180 = "[s9] \"Sorry, I let my guard down...\"\n[s10] \"They couldn't be reasoned with...\""
10056070-183 = "I had been told that we would be welcoming my new retainers, but to think that#nSensei of Schale would be amongst them as well."
10056070-184 = "It's as if I had opened a clam and... Lo, a pearl."
10056070-190 = "First things first, what do you say to a pleasant discussion?"
10056070-191 = "Toumi Kokoro?"