[translation]
10057010-1 = "Episode 1; Special Class 183"
10057010-6 = "[ns1] \"So cold...\"\n[ns2] \"Is this really the way?\""
10057010-9 = "Yes. We'll be able to meet up if we keep going this way."
10057010-10 = "The problem here is the distance. It'll take us some time to reach there."
10057010-11 = "This is all because I asked you to do something so unreasonable."
10057010-12 = "I'm really sorry, Sensei."
10057010-13 = "[s3] \"I-it's fine...\"\n[s4] \"It's not your fault, Rana...\""
10057010-16 = "I'm firing a signal flare..."
10057010-23 = "With that... They should be able to come here and help us."
10057010-24 = "Assuming they see it... that is..."
10057010-28 = "It's so windy..."
10057010-29 = "I'm getting... sleepy..."
10057010-34 = "[ns5] \"Don't fall asleep... You can't...\"\n[ns6] \"I'll cover you from the wind...\""
10057010-40 = "(I'm so... sleepy...)"
10057010-53 = "Hey, wake up."
10057010-54 = "Fwah!? I-I wasn't sleeping!"
10057010-55 = "Sigh... I knew you'd fall asleep right after starting up the heater."
10057010-56 = "I wasn't sleeping! I was, umm... What was it called again...? #nR-right! I was just meditating!"
10057010-60 = "Unknown Location"
10057010-63 = "Where's Rana?"
10057010-64 = "She woke up a lil' bit ago and went off to wash her face."
10057010-65 = "I thought she'd just go buy the stuff and come back... #nWhy did she come back with some random person?"
10057010-66 = "Y'know what though? This person's kinda giving me de... deija..."
10057010-67 = "“Déjà vu”?"
10057010-68 = "That's it! That's the word! Aren't you feeling a lot of déjà vu when you look#nat them?"
10057010-69 = "I definitely do feel like I've seen them before... Who exactly is this...?"
10057010-74 = "[ns] \"I'm Schale's Sensei...\""
10057010-76 = "U-uwaaah!!"
10057010-77 = "Y-you were awake!?"
10057010-78 = "You scared me so bad! Are you feeling all better now?"
10057010-79 = "[s] \"Yep. My body's warm now, so I'm alright.\""
10057010-80 = "We saw your signal and came over as fast as we could. #nIt really was a surprise to see both you and Rana collapsed on the snowy#nmountain."
10057010-81 = "Luckily, Rana is safe as well."
10057010-85 = "But like, when you say that you're Sensei..."
10057010-89 = "You mean, THAT Sensei of Schale!? For real!?"
10057010-90 = "[s7] \"Th-that's right...\"\n[s8] \"Is it really that shocking...?\""
10057010-93 = "Wowwies, that's crazy~"
10057010-94 = "I thought you looked like someone I'd seen before in a magazine... But to think..."
10057010-95 = "Ah, right! Senseii Seeenseii! Was eeeverything they wrote in that article true!?"
10057010-96 = "[s] \"W-what article...!?\""
10057010-97 = "She's referring to the special feature article on the Red Bear. #nOf course, we don't believe in what they write."
10057010-98 = "Yep, exactly! The Red Bear's full of nooothing but sketchy articles!"
10057010-99 = "Buut... I've also heard they never actually lie outright in those..."
10057010-104 = "[ns9] （……）\n[ns10] （I'm gonna need to have a talk with Yakumo later.）"
10057010-109 = "A-ahahaha..."
10057010-112 = "I-I see... #nIt seems you had your own circumstances as well."
10057010-113 = "Ah, my apologies. #nWe haven't introduced ourselves yet."
10057010-117 = "I am the class president of Special Class 183 and its head of mechanical#nengineering. Please call me Anna. I look forward to working with you."
10057010-118 = "I am also an honorary federal inventor of the Red Winter Academy of Sciences'#nChief Operations Committee, a recipient of the First-Class Mustache Medal, and—"
10057010-119 = "Too much! How long're you gonna yap for!?"
10057010-120 = "'Kay, me next! I'm Erina!"
10057010-121 = "I'm theee... vice president of the same Special Class 183 and its head of chemistry! #nThat's it! The end!"
10057010-122 = "Must be nice having such a short descriptor."
10057010-123 = "Maybe if you studied a bit harder, your self-introduction could be longer."
10057010-124 = "Huuuh? #nI'm not jealous of you at all! If you love introducing yourself so much, then go#nahead and keep up that introduction forever!"
10057010-125 = "[s11] \"Special Class 183?\"\n[s12] \"Are you somehow related to Special Class 227?\""
10057010-130 = "227?"
10057010-131 = "What's that?"
10057010-135 = "Achoo!"
10057010-136 = "Oh geez. This is all because you aren't properly inside your futon when you sleep."
10057010-137 = "Ugh... Is there someone talking about me?"
10057010-140 = "I don't know about 227, but... #nOur 183 is a distinguished research organization here at Red Winter."
10057010-141 = "It's a place where Red Winter's finest scientists have gathered to develop all#nmanners of core technologies."
10057010-142 = "183 produces a variety of different goods, ranging from screws and drinks, to#nelectronic components and devices."
10057010-143 = "Yeh huh!"
10057010-145 = "[s] （They're perfectly in sync...）"
10057010-148 = "Hey, we should show Sensei the \"you know what!\""
10057010-149 = "Wait, you mean that!? Right now!?"
10057010-150 = "C-come on now, Erina... We've only just met Sensei. Aren't you moving a little too#nfast...?"
10057010-151 = "Isn't this something you would do after you build up rapport first...?"
10057010-152 = "What're you saying? It should be the other way around! It's better we show it now so we can win Sensei over to our side faster!"
10057010-153 = "W-we can't! I'm serious, it's too embarrassing!!"
10057010-154 = "C'mon, just brace yourself! It's not like it's the end of the world if we show it off!"
10057010-159 = "Sensei! I'll guide you there, so just hold my hand and close your eyes!"
10057010-160 = "[s] \"Huh? S-sure...?\""
10057010-164 = "I-I said don't!! Please don't go!!"
10057010-170 = "Senseeei, nooot yeeet!"
10057010-171 = "Seriously, just stop!"
10057010-172 = "Gosh, how long are you gonna keep saying that!? Go get it ready already!"
10057010-173 = "Agh, I don't care anymore!!"
10057010-177 = "Alright Sensei, we're ready!"
10057010-178 = "Just don't fall over from shock, 'kay?"
10057010-179 = "[ns13] （Open your eyes fearfully.）\n[ns14] （Open your eyes reluctantly.）"
10057010-184 = "[ns] \"What is this?\""
10057010-186 = "Tada!! Whaddya think? Cool, ain't it!?"
10057010-187 = "You knew that showing it off in this state was only ever going to lead to#ndisappointment, and yet you still...! Agh!"
10057010-188 = "No way! Heey, Sensei! You know what this is?"
10057010-189 = "[s15] \"Hmm... A really sick tractor...?\"\n[s16] \"Ah... An awesome armored vehicle...?\""
10057010-194 = "How rude!!!"
10057010-195 = "No matter how you look at it, it's clearly a tank!"
10057010-196 = "What's it with normal people, seriously!"
10057010-197 = "[s] \"A tank...?\""
10057010-198 = "Yeah, this is the tank we're currently building."
10057010-199 = "Ths here is the hull, and all that's left is to install the turret, but..."
10057010-200 = "That's enough explaining! Sensei should get it now!"
10057010-201 = "[s] \"T-taking another look at it... This thing's super cool!\""
10057010-205 = "Right!?"
10057010-206 = "I'm thinking of sloping the armor on the turret. #nBy doing that, shells will deflect off the armor, thereby increasing the tank's#ndefensive capabilities."
10057010-207 = "Huuuh? Didn't we say that we were gonna make it dome shaped so it wouldn't be so cramped!?"
10057010-208 = "Huh? Did we now?"
10057010-209 = "Quuit playing duumb!"
10057010-216 = "Sensei."
10057010-217 = "[s17] \"Rana! How are you feeling?\"\n[s18] \"What in the world is going on here...?\""
10057010-220 = "This is a \"deliberation.\""
10057010-221 = "There are two more rounds before it turns into \"persuasion.\""