[translation]
10056040-1 = "Episode 4;Dangerous Barnacles"
10056040-3 = "No way..."
10056040-4 = "We are cleaning the hull?!"
10056040-6 = "Odyssey Anchorage"
10056040-7 = "[ns1] \"You got it. Island wanted us to do it.\"\n[ns2] \"She said it is a job only the diving club can handle.\""
10056040-10 = "We certainly are the right people for the job, but..."
10056040-11 = "Ugh... I really hate cleaning ship hulls..."
10056040-12 = "[s] \"...Did I end up asking for something that makes you uncomfortable?\""
10056040-13 = "No... It is just a matter of feeling... #nDifficulty-wise, it is not a big deal."
10056040-14 = "It is just that... the smell is a bit..."
10056040-15 = "Still, we are not in a position to be picky about jobs..."
10056040-19 = "Everyone, are you ready?"
10056040-20 = "Safety first above all. Always dive in pairs and check each other's status!"
10056040-21 = "Make sure to prepare at least two means of communication with the surface. #nCheck the buoyancy of the buoys in advance, and have knives ready just in case. #nWhile diving, check your cylinder pressure every 5 minutes—"
10056040-26 = "Geez, you are worrying too much. How many times do you think we have done this?"
10056040-27 = "Buddies are the same as usual. Me and the president, and Makina and Sayuri."
10056040-28 = "Wearing gloves makes it hard to move my hands..."
10056040-29 = "President, can I go barehanded?"
10056040-30 = "No! There are lots of sharp things on the hull!"
10056040-31 = "If you cut your hand while working and get a bacterial infection, in worst cases you will suffer from high fever due to sepsis, and #nwait, it can even cause organ damage—"
10056040-40 = "...I see. #nSo that is why Sensei inquired about underwater work."
10056040-41 = "Does this mean the diving club's financial situation is as bad as expected?"
10056040-42 = "I cannot believe they are in debt..."
10056040-43 = "If left unattended, it would have put not only the diving club, #nbut the entire academy in a difficult spot."
10056040-44 = "Thank you for responding so promptly."
10056040-45 = "[s3] \"I did not do much.\"\n[s4] \"Ami, thank you for recommending the job to us.\""
10056040-48 = "It was a blessing in disguise."
10056040-49 = "It is easily overlooked, but the hull in contact with the sea is the most important part."
10056040-50 = "Neglecting maintenance increases the risk of accidents, so we regularly put ships in dry dock to service them, but..."
10056040-51 = "That method takes way too much time."
10056040-52 = "However, having the diving club help us saves a lot of trouble and is a huge help."
10056040-56 = "...30 minutes have passed."
10056040-57 = "This should be enough."
10056040-58 = "Alright. Let us take a 1-hour break starting now."
10056040-65 = "So stinky~"
10056040-66 = "Sayuri, you like stinky things, right? You are always eating sardine ice cream."
10056040-67 = "Sardines and barnacles smell completely different."
10056040-68 = "Good work. Kotone and I will dive next."
10056040-69 = "Whew, I am tired..."
10056040-71 = "[ns] \"What do you actually do when cleaning a hull?\""
10056040-72 = "We scrape off the attached barnacles."
10056040-73 = "[s] \"Barnacles?\""
10056040-74 = "Yes. #nBarnacle larvae float in the sea, but they attach themselves to the bottom of ships and grow."
10056040-75 = "If left alone, it leads to metal corrosion and reduced propulsion efficiency while sailing, #nso regular cleaning is necessary."
10056040-76 = "Especially when anchored like this, barnacles stick to it densely."
10056040-77 = "[s] \"That sounds troublesome.\""
10056040-78 = "Yes, it is really a pain."
10056040-80 = "Hey, Makina."
10056040-81 = "...Can we just use a grinder to zzzzt take them off?"
10056040-82 = "Didn't the president say not to use anything other than scrapers?"
10056040-83 = "But scrapers and grinders work on the same principle."
10056040-84 = "It is cordless, so there is no worry about electric shock either."
10056040-85 = "Hmm..."
10056040-86 = "Well, whatever. Pursuing efficiency is part of the work too."
10056040-87 = "Then go grab the grinder."
10056040-88 = "Okay~"
10056040-90 = "[ns] \"Can you eat barnacles?\""
10056040-91 = "I would not recommend it. #nDepending on where they attached, they might contain a lot of toxic chemicals and heavy metals."
10056040-92 = "Before that, the foul odor is terrible..."
10056040-93 = "The only ones who would be happy to see barnacles stuck to a ship are pirates."
10056040-94 = "[s] \"Pirates?\""
10056040-95 = "Yes."
10056040-96 = "From what I hear, that Sea Dragon of the Tidal Waters even uses barnacles for extortion—"
10056040-100 = "Ah, excuse me."
10056040-101 = "[s5] \"I have been wondering about this for a while...\"\n[s6] \"Who is the Sea Dragon of the Tidal Waters?\""
10056040-107 = "...It is embarrassing to admit, but our school also has a problematic student."
10056040-108 = "We decided that rehabilitation at the school was impossible and handed her over to Valkyrie's Correctional Bureau."
10056040-109 = "Able to manipulate even calm waves at will, she earned the moniker Sea Dragon of the Tidal Waters. #nShe had a fatal problem."
10056040-110 = "[s] \"Which is?\""
10056040-111 = "Inciting other students and proclaiming herself the Dragon Palace's—"
10056040-117 = "Boom!"
10056040-118 = "[ns7] \"W-What was that?\"\n[ns8] \"Did something explode...?\""
10056040-122 = "President, it is an emergency!"
10056040-123 = "A-Are you two okay? What happened!?"
10056040-127 = "The barnacles... had an explosion..."
10056040-128 = "Explosion... Barnacles did?"
10056040-129 = "Don't tell me you used equipment other than scrapers?"
10056040-130 = "Um, well..."
10056040-131 = "Scrapers had their limits, so we used a grinder..."
10056040-132 = "...Makina."
10056040-133 = "B-But it is true that the barnacles exploded!"
10056040-137 = "Trident, please dispatch an emergency work team to Pier 7 right away."
10056040-138 = "Yes, a puncture has occurred in the lower hull area. The damage is minor, but..."
10056040-139 = "Switch to Z-status. Seal all hatches and doors."
10056040-149 = "We messed up..."
