[translation]
10050070-1 = "Episódio 7; Uma Última Chance"
10050070-2 = "Ah... Sensei, olá."
10050070-3 = "Bem, eu já ouvi falar um pouco sobre o assunto... Por favor, entre."
10050070-4 = "[s] \"Desculpe, Ui.\""
10050070-5 = "N-não... Está tudo bem o Sensei vir aqui..."
10050070-6 = "Quer dizer, o Sensei, eu... e se juntarmos aquelas duas... somos 4 pessoas no total?"
10050070-7 = "U-uuh... Acho que 4 pessoas na biblioteca antiga é gente demais..."
10050070-8 = "[s] \"V-vou tentar ficar o mais quieto possível!\""
10050070-9 = "Sim... Então, por aqui, por favor..."
10050070-14 = "O-olá, Sensei. Você realmente veio até Trinity..."
10050070-15 = "Nunca imaginei encontrar o Sensei em Trinity... e ainda por cima neste lugar."
10050070-16 = "[s1] \"Parece ser uma emergência, então vou direto ao ponto.\"\n[s2] \"Yakumo, por que você fez isso?\""
10050070-19 = "Ugh... Nada de conversa fiada ou quebra-gelo, então...?"
10050070-20 = "Entendido, entendido... haah."
10050070-21 = "Em resumo, é para ganhar dinheiro."
10050070-22 = "Não está sendo sincera demais...?"
10050070-23 = "Mas é a verdade..."
10050070-24 = "...Hã? Isso não é o suficiente para te convencer...? Não parece algo que um empresário diria?"
10050070-25 = "Que fazer negócios em outros distritos autônomos é um risco grande demais para o retorno...?"
10050070-26 = "[s] \"Eu achei que a Yakumo calcularia algo assim.\""
10050070-27 = "Não, não, não, minha capacidade não é nada tão impressionante assim!?"
10050070-28 = "...Guh, não precisa me olhar com essa desconfiança."
10050070-29 = "...Haah."
10050070-30 = "Entendido, está bem. Parece que o Sensei também quer uma resposta imediata..."
10050070-31 = "Não estou acostumada a ir direto ao ponto tão rápido... Ah, será que isso é o que chamam de técnica de conversa de adulto?"
10050070-32 = "Sensei... do que você acha que a \"cultura\" se alimenta para crescer?"
10050070-33 = "[s] \"Hmm... do interesse e do amor das pessoas?\""
10050070-34 = "É mesmo? Entendo..."
10050070-35 = "Esse é um pensamento equivocado."
10050070-36 = "A cultura é... uma criatura que cresce devorando dinheiro. #nEssencialmente, não somos diferentes dela."
10050070-37 = "Achou que foi um comentário radical? Mas... essa é a realidade!"
10050070-38 = "Desfrutar de um meio cultural é... em outras palavras, consumir um valor de troca diferente do seu próprio tempo. Ou seja, gastar dinheiro."
10050070-39 = "...E as pessoas buscam uma contrapartida por suas ações de consumo. Diversão, sorrisos, coisas desse tipo."
10050070-40 = "Ou talvez emoção e lições de vida, também serve."
10050070-41 = "Sensei. Você já parou para pensar em quantos textos são escritos em um único dia?"
10050070-42 = "Muitos pensam que, se escreverem algo bom, serão lidos... mas isso é uma ilusão."
10050070-43 = "Porque, mesmo neste exato momento... há uma abundância excessiva de textos e informações."
10050070-44 = "Eu disse \"em um dia\", mas na verdade é a cada hora... não, a cada minuto e segundo."
10050070-45 = "A maior parte disso é esquecida e reduzida ao nada."
10050070-46 = "Isso não é um pouco... triste?"
10050070-47 = "[s] \"...\""
10050070-48 = "Se pelo menos conseguirem subir no ringue do mercado, já é um bom começo."
10050070-49 = "Alguns podem pensar \"vou me esforçar mais na próxima\", ou outros podem aprender algo com isso."
10050070-50 = "Ou talvez desistir, percebendo que aquele não era o caminho que buscavam."
10050070-52 = "Mas a grande maioria nem sequer consegue subir no ringue..."
10050070-53 = "E apenas invejam o campeão que segura o troféu."
10050070-54 = "Lembra de quando era criança? As crianças sempre querem ser algo que não são."
10050070-55 = "Querer criar algo assim. Querer provar a si mesmo e ser reconhecido..."
10050070-57 = "Bem, isso não se limita apenas às crianças. É natural que qualquer um pense assim."
10050070-58 = "Mas até os sonhos perdem o brilho com o passar do tempo."
10050070-59 = "É triste não ter sonhos, mas ficar preso a eles para sempre é uma tragédia... É o que dizem."
10050070-60 = "Se é para fazer alguém sonhar—"
10050070-61 = "—então também deveria ser dado o talento necessário. Não concorda?"
10050070-63 = "[ns3] \"Não querendo ser chato...\"\n[ns4] \"Você ainda é jovem, não é!?\""
10050070-66 = "…Pois é."
10050070-67 = "Mas com certeza existem crianças por aí que não conseguem evitar pensar assim."
10050070-68 = "Enfim. Era isso que eu queria dizer."
10050070-69 = "Para encarar seus próprios sonhos, enfrentar os obstáculos e seguir em frente, é preciso subir no ringue pelo menos uma vez."
10050070-70 = "E para subir no ringue, é preciso haver divulgação."
10050070-71 = "É demais ser forçado a declarar derrota sem nem ter a chance de lutar."
10050070-72 = "Por isso o dinheiro é importante. Ele é o que pavimenta o caminho até o ringue."
10050070-73 = "A cultura cresce no solo do dinheiro, e alguém precisa gerenciar esse solo."
10050070-74 = "Bem, então... foi por isso que o incidente de agora aconteceu, suponho."
10050070-78 = "[ns5] \"Mas, se precisa de tanto dinheiro assim...\"\n[ns6] \"Não poderia ser com outra coisa que não fosse publicação?\""
10050070-81 = "…Hã!?"
10050070-82 = "[s7] \"Deve haver muitos outros trabalhos que dão dinheiro.\"\n[s8] \"Como na área de distribuição ou finanças, por exemplo.\""
10050070-85 = "Guh!?"
10050070-86 = "Que... observação afiada."
10050070-91 = "[ns] \"Será que falei demais?\""
10050070-93 = "N-não! Foi uma observação muito pertinente, Sensei! Quando a chefe entra naquele estado, não tem quem a segure!"
10050070-94 = "Mas... eu entendo o que a chefe quer dizer."
10050070-95 = "Como o Sensei disse... se fosse apenas por dinheiro, ela não estaria no ramo editorial."
10050070-96 = "[s] \"Então, Yakumo...\""
10050070-97 = "Fufu. Quem sabe?"
10050070-98 = "E o fato de eu, uma crítica, estar ao lado da chefe também... Sim, como você deve ter imaginado."
10050070-99 = "No fim das contas, fazemos esse trabalho porque gostamos."
10050070-100 = "Se der para ganhar dinheiro e ainda fazer propaganda, melhor ainda."
10050070-101 = "Pode parecer uma pessoa egoísta, gananciosa e complicada. Mas a chefe é assim."
10050070-102 = "Acho que ela nunca admitiria isso na frente de outras pessoas, porém."
10050070-103 = "Porque ela é desse jeito. Falando sobre talento, sobre ringues..."
10050070-104 = "Por que você acha que ela se abriu tão honestamente sobre si mesma?"
10050070-105 = "Ter inveja do campeão... lamentar a falta de talento..."
10050070-106 = "Quem será que ela é?"
10050070-107 = "[s] \"Será que essa história é...\""
10050070-108 = "Fufu. Existem histórias que se aproximam da perfeição justamente por não serem contadas."
10050070-109 = "…Não diga coisas estranhas, Takane. Que agouro. O que pretende fazer se isso afetar as vendas?"
10050070-110 = "Sim, sim. Entendido."
10050070-112 = "[ns9] \"Entendi o que vocês duas querem dizer.\"\n[ns10] \"Mas ainda acho perigoso fazer as coisas mentindo.\""
10050070-115 = "Hm? Mentindo, como assim...?"
10050070-116 = "[s11] \"Como o fato de Takane ser uma princesa, por exemplo...\"\n[s12] \"Não houve várias outras coisas também?\""
10050070-119 = "P-por que o Sensei sabe disso...! Será que foi você, Takane!?"
10050070-120 = "Reflita sobre isso, chefe! Aquilo foi longe demais, não acha?"
10050070-121 = "Até agora eu morro de vergonha só de lembrar...!"
10050070-122 = "[s13] \"De qualquer forma, eu também vou conversar com elas.\"\n[s14] \"Vamos encerrar o assunto por aqui.\""
10050070-125 = "Tá bom..."
10050070-132 = "P-problema! Sensei! O Comitê de Justiça está... indo na sua direção!"
