[translation]
10054050-1 = "Episode 5;The Terrifying Kindergarteners"
10054050-2 = "Yes! Of course, I understand perfectly!"
10054050-3 = "It's lunchtime, isn't it! #nS-shall I bring you your meal?"
10054050-4 = "First, we have the Chinjao Rosu and steamed bun—"
10054050-9 = "……Is this a bell pepper?"
10054050-10 = "Ptooey! How dare you put something like this in here. #nWe hate bell peppers! Are you such a small-fry adult that you don't even know that?"
10054050-11 = "It can't be helped. We have to punish adults who make mistakes. Hehehe."
10054050-12 = "B-but! You said so yourself yesterday! #nThat you wanted to eat Chinjao Rosu……!"
10054050-13 = "This dish doesn't work without bell peppers, you know……?"
10054050-14 = "T-that's right! Originally, it uses green chili peppers, but that would be too spicy……!"
10054050-15 = "Don't care, don't care, don't care! I hate bell peppers!"
10054050-16 = "—Anyway. I've been wondering about this for a while. #nWhat is this? A goose?"
10054050-17 = "It's an ingredient!"
10054050-18 = "Huh!? You're going to eat it!? #nIsn't that pitiful? Let it go! Hurry!"
10054050-19 = "B-but this too! #nYou said you wanted to eat roast goose, so I prepared it!"
10054050-20 = "Hehehe. That was then, this is now."
10054050-21 = "HONK!"
10054050-22 = "Eek! W-what!? #nEven though it's a goose…… do something about it already!"
10054050-23 = "Eh, but you told me to let it go—"
10054050-24 = "That was then, this is now! #nYou're such a small-fry adult, you're so thick-headed."
10054050-29 = "[ns] \"I wonder who those kids are……?\""
10054050-31 = "Even without knowing that, that attitude toward an adult……."
10054050-32 = "They clearly weren't raised right."
10054050-37 = "Hmm……."
10054050-38 = "Sigh. My good mood is completely ruined."
10054050-39 = "I suppose a punishment is in order."
10054050-46 = "Ah…… the shop…… it's over……."
10054050-47 = "……It's okay. We can just start over."
10054050-48 = "Let's help each other out. Okay?"
10054050-49 = "Ew, gross."
10054050-50 = "Small-fry adult, soooooo gross."
10054050-51 = "Sigh…… I guess they still need the whip? Hehehe."
10054050-52 = "What are you all doing!!"
10054050-53 = "……Who are you?"
10054050-54 = "What's the meaning of this? #nNo one is supposed to come here except us……."
10054050-55 = "……It seems we're becoming a rumor online. #nThis is why I hate vertical videos."
10054050-56 = "Eh, whatever. I'll tell you as a special favor. #nI'm sure you'll want to join us too."
10054050-57 = "Yeah, yeah!"
10054050-58 = "Allow us to introduce ourselves. #nWe do whatever we want, play however we want, and never listen to discipline. #nOur name is—"
10054050-59 = "The Hinadori Gang!"
10054050-60 = "Suiko Takanosu! #nI'm the one who started this gang! Kyahaha!"
10054050-61 = "Nagomi Iojaku. #nIf you mess with us, we pay you back tenfold. Though we do it even if you don't mess with us."
10054050-62 = "Isn't that just being a nuisance……."
10054050-63 = "I'm Yoko Utou. #nHeh, hehehe…… Children's grudges…… are very deep, you know?"
10054050-64 = "Anyway, you……."
10054050-65 = "W-what……?"
10054050-66 = "Why don't you ditch the adults and come play with us?"
10054050-67 = "The Hinadori Gang is definitely more fun than adults who only say boring things, right?"
10054050-68 = "Because you don't have to do anything you don't want to. #nWe just blow away everything that's an eyesore!"
10054050-69 = "Children are beings filled with potential, after all. Hehehe……."
10054050-70 = "What are you talking about……."
10054050-73 = "U-um! I've brought you some Ummee-bo and strawberry milk! #nFor today, please, just take this……!"
10054050-74 = "Hmm? #nOh. This is the one I like."
10054050-75 = "Not bad taste for a small-fry adult."
10054050-76 = "In that case…… what should we do about the cleanup?"
10054050-77 = "Hmm……."
10054050-78 = "Today is special! We'll let you off the hook!"
10054050-79 = "But don't expect a next time, okay? #nNext time…… we'll turn this place into a sea of fire!"
10054050-80 = "It would look like fireworks even in the daytime. Hehehe……."
10054050-87 = "I-I'm saved……."
10054050-88 = "……Are you alright?"
10054050-89 = "I'm not alright, but…… it can't be helped."
10054050-91 = "[ns] \"Um. Who were those kids……?\""
10054050-92 = "They're a gang called the Hinadori Gang."
10054050-93 = "A gang!? #nThey only looked like kindergarteners to me……?"
10054050-94 = "Ah…… they are kindergarteners."
10054050-95 = "Is that some kind of metaphor, like 'kids these days are scary'?"
10054050-96 = "Something like that……."
10054050-97 = "Are they famous around here?"
10054050-98 = "No…… they just appeared out of nowhere."
10054050-99 = "Suddenly, they started saying they were going to make this their new base……."
10054050-100 = "You see the situation. #nThey're so selfish, I'm at my wit's end."
10054050-101 = "Then why do you let them do whatever they want? #nI don't think this is good for their education, either."
10054050-102 = "We tried a lot of things at first. #nBut…… those kids have strong backing."
10054050-103 = "Scolding them, resisting them…… nothing worked."
10054050-104 = "And they seem to like this place. #nThey're dead set on keeping it all to themselves."
10054050-105 = "Well, this valley is beautiful, after all."
10054050-106 = "It used to be a hidden gem, but #nrecently, we even had investors interested. #nWe were supposed to renovate the facilities, so how did it end up like this……."
10054050-107 = "As you can see, the Hinadori Gang started running wild, and now we're at a loss."
10054050-108 = "……."
10054050-109 = "At this rate, we can't even repair the facilities, let alone attract tourists."
10054050-110 = "[s] \"Do you know where their base is?\""
10054050-111 = "They seem to be staying at the oldest hotel in this valley."
10054050-112 = "It's connected directly to the ropeway, at the foot of that mountain."
10054050-113 = "Connected directly to the ropeway, you say."
10054050-114 = "Yeah. That's why it's an expensive hotel around here, but…… #nthey're not just anyone if they can afford to stay there for days on end."
10054050-115 = "But…… come to think of it, weren't they friendly to Kokona-chan?"
10054050-116 = "They probably wanted to gain an ally."
10054050-117 = "Whether it's true or not, they seem to intend to turn every kindergartener in Kivotos into a member of the Hinadori Gang."
10054050-118 = "I wouldn't dream of being friends with such rude kids!"
10054050-119 = "Kokona…… did you say?"
10054050-120 = "Eh? Yes, Kokona Sunohara."
10054050-121 = "Kokona is an adult, isn't she? Truly reliable. #nI wish those kids would learn from her."
10054050-122 = "Ahem, of course!"
10054050-124 = "[ns] \"Kokona is a fine lady, after all.\""
10054050-125 = "S-Sensei!? #nI-I'm happy, but, um…… please stop joking……."
10054050-126 = "Yes? You mean it……?"
10054050-127 = "Y-you've finally awakened to my charm, Sensei!"
10054050-128 = "……Wait? Hold on. #nDoes that mean……."
10054050-129 = "You were just teasing me all this time……?"
10054050-130 = "[ns] \"……You caught me.\""
10054050-131 = "SENSEI!!!"
10054050-134 = "(For a while, a game of tag with Kokona ensued)"
10054050-136 = "Once again, welcome. I'm glad you came."
10054050-137 = "This feeling, it's been a while……."
10054050-138 = "I'll provide the best hospitality I can, so please, take your time."
10054050-139 = "Thank you very much."
10054050-140 = "……."
10054050-141 = "In that case, could I have that Chinjao Rosu and steamed bun from earlier?"
10054050-142 = "I'll make it fresh, so please wait a moment."
10054050-143 = "Oh, no. The one from earlier is fine! #nDelicious Chinjao Rosu is delicious even when it's cold!"
10054050-144 = "Eh…… bell peppers…… but, better than carrots……."
10054050-145 = "No. I can't throw a tantrum like the Hinadori Gang!"
10054050-147 = "(The Chinjao Rosu was cold, but it was incredibly delicious)"
10054050-153 = "……You're eating it so happily."
10054050-154 = "Yes, this is it, this is it……."
10054050-155 = "This is what I started this business to see."
10054050-157 = "[ns] \"Well, it's about time…….\""
10054050-158 = "To decide how to solve this problem, right?"
10054050-159 = "As a premise, we are here as tourists."
10054050-160 = "Besides, this is outside of Shanhaijing. It wouldn't matter if we left the problems of this land alone."
10054050-161 = "But I assume that is not what you are thinking?"
10054050-162 = "Oh? #n……Then, what would you do?"
10054050-163 = "I think we should start by gathering information."
10054050-164 = "We cannot ignore the spirit of the merchants here."
10054050-165 = "Their will to protect this place even in the face of the Hinadori Gang's tyranny…… #nit was truly an attitude to be modeled after."
10054050-166 = "Abandoning them would go against righteousness and chivalry!"
10054050-167 = "Those are words truly worthy of you."
10054050-171 = "I agree too. As a fellow merchant, I can't overlook this. #nThere's a minimum standard of decency in business, after all."
10054050-172 = "I can't forgive it either!"
10054050-173 = "Rude and selfish—"
10054050-174 = "At Plum Blossom Garden, they'd get a spanking!"
10054050-175 = "[ns] \"What about you, Shun?\""
10054050-179 = "I agree."
10054050-180 = "……."
10054050-181 = "They were children who made me think about a great many things."
10054050-182 = "And on top of that…… #nas Lumi-san said, for the sake of the merchants here."
10054050-183 = "And…… for the sake of those children as well."
10054050-184 = "I cannot turn a blind eye."
10054050-185 = "In the first place, their actions are having a negative impact on the Xuanwu Chamber of Commerce's investments."
10054050-186 = "We visited this land for an inspection regarding those investments."
10054050-187 = "Therefore, this could be said to be an extension of our inspection activities."
10054050-188 = "[ns] \"The direction is set, then. Where should we start?\""
10054050-189 = "I think we should start by investigating the current state of the shopping district."
10054050-190 = "As for the Hinadori Gang…… hmm. #nGetting them to let us join would be the quickest way, but given our ages……."
10054050-191 = "That's why I wonder if we could ask Kokona. This is something only Kokona can do."
10054050-192 = "Ugh…… if that's the case, it can't be helped, but……."
10054050-193 = "But…… I still hate it! #nJoining an organization like that…… and pretending to be their ally……!"
10054050-194 = "Wait. #nIt's true that perhaps *only* Kokona-chan can be asked to do this right now."
10054050-195 = "But as Kokona-chan's family…… and furthermore, as her guardian, #nI cannot agree to anything dangerous."
10054050-197 = "[ns] \"Yeah. I think the same.\""
10054050-198 = "Shun-neesan…… Sensei too……."
10054050-199 = "Kokona-chan, you don't have to push yourself."
10054050-200 = "But then, how are we going to deal with the Hinadori Gang……."
10054050-201 = "I have an idea, dear sister."
10054050-202 = "I'm sure Kisaki-sama does as well."
10054050-203 = "Is that so……?"
10054050-208 = "(Shun and Kisaki made eye contact)"
10054050-209 = "(And then……)"
10054050-211 = "Yes. I have a clever plan."
10054050-212 = "However, it is late today. #nLet's get some rest, and start the investigation tomorrow."
10054050-213 = "Hmm…… I feel like I should know what you're planning, but I don't……."
10054050-214 = "But if Kisaki says it's fine, it probably is. #nLet's take charge of the shopping district."
10054050-215 = "Yes……!"
10054050-216 = "I have no objections either. Then, shall we head back to our rooms?"
10054050-226 = "[ns1] \"Could it be…….\"\n[ns2] \"Is that…… what it is?\""
10054050-230 = "Hehehe, who knows?"
10054050-231 = "But if Sensei could help us keep our stories straight, things might go even faster, you know?"
10054050-232 = "Indeed. It is in times like these that the 'power of an adult' is necessary."
10054050-234 = "(The two of them wore meaningful smiles)"
10054050-235 = "(I felt a cold sweat running down my spine……)"