[translation]
10056100-1 = "Episode 10; Breeching"
10056100-2 = "The next morning—"
10056100-7 = "Ahoy!"
10056100-8 = "Hehe, hear this and rejoice. I bring with me good tidings."
10056100-14 = "I have obtained the cylinders you asked for."
10056100-15 = "With this, you should be able to dive into the Graveyard of Whales, yes?"
10056100-16 = "Complete your preparations anon, Diving Club! It's time—"
10056100-20 = "Hm? It would seem you are all ready to go. Perfect timing."
10056100-25 = "Sea Dragon... No, Gonokami Nanami."
10056100-26 = "We cannot do anything that will disrupt the whales' rest."
10056100-27 = "Maintain an appropriate distance from marine wildlife and do not interfere with#ntheir ecologies. This is a diver's code of conduct."
10056100-28 = "Even if I am no longer able to dive... I will not follow your instruction."
10056100-33 = "Sigh... It would seem that you are misunderstanding something."
10056100-34 = "This is an order."
10056100-35 = "I believe I have said this before—defy me at the risk of your Sensei's safety."
10056100-36 = "Even if you were to escape, what is your plan?"
10056100-37 = "Do you actually intend on swimming all the way back?"
10056100-38 = "If there is no path forward, then breach your way to a new path."
10056100-39 = "Door breaching is not a skill that is applicable only on land."
10056100-40 = "But out here in this vast ocean? #nWhat door do you intend on opening?"
10056100-41 = "—You're plotting something, aren't you?"
10056100-42 = "But it's all in vain."
10056100-43 = "Even if you call for help, it will take Trident hours at the least to arrive."
10056100-44 = "I suggest you cease this tomfoolery—"
10056100-49 = "What are you..."
10056100-56 = "What is this!?"
10056100-57 = "A whale!?"
10056100-58 = "Good thing we called back to them yesterday with a whistle."
10056100-59 = "I didn't expect them to gather just by blowing it though."
10056100-60 = "Flying whale."
10056100-61 = "That's so freaking cool!"
10056100-62 = "Hold on tight, everyone! The boat's 'bouta rock!"
10056100-63 = "...All right!"
10056100-64 = "Sensei, it's go time!"
10056100-68 = "You fools... Abandoning your posts just because of a little shaking..."
10056100-72 = "Do not let Sensei get away!"
10056100-77 = "(As the whale came crashing down, the subsequent wave slammed against the#nship, causing it to shake violently. As a result, I fell into the sea.)"
10056100-81 = "(While I struggled beneath the waves, someone approached and pulled me to the surface.)"
10056100-82 = "(...I heard a familiar sound.)"
10056100-85 = "Sensei, are you all right?"
10056100-86 = "[s1] \"One way or another.\"\n[s2] \"Other than swallowing a bit of seawater...\""
10056100-92 = "Catch Sensei before they all manage to escape!"
10056100-93 = "There will likely never be another chance like this if they successfully get away!"
10056100-101 = "[ns] \"Okay, well, might be a bit early to say that we're safe though.\""
10056100-103 = "Sensei. Could you close your eyes?"
10056100-109 = "[ns] \"Agh, ngh... Mnnn...?\""
10056100-110 = "This is my octopus. Please keep it in your mouth. #nEven though it'll only last for around ten minutes..."
10056100-111 = "Those ten minutes will be more than enough."
10056100-117 = "Gonokami Nanami."
10056100-118 = "We will breach a path towards our objective."
10056100-119 = "By all means, do flail around as much as you'd like."
10056100-120 = "What's with that tone? Are you mocking me!?"
10056100-121 = "If you ever want to surrender, all you have to do is yell \"stop.\""
10056100-122 = "Until then, we won't be stopping."
10056100-123 = "Hahah, how truly laughable! Do you really believe that a threat of this level is#nenough to get me to quit?"
10056100-124 = "Prepare for anti-submarine combat! Begin dropping depth charges!"
10056100-125 = "Send them to their watery graves!"
10056100-137 = "Regulator, check. Final check, all green."
10056100-144 = "All hands, dive."