[translation]
1005906-1 = "cicatriz"

1005906-6 = "(Um funcionário me contou toda a história)."

1005906-7 = "...... Mika está atualmente em prisão domiciliar na #nReflection Room após um incidente violento no campus."

1005906-8 = "[s]\"Violência, é isso? ......? \""

1005906-9 = "Sim. Ele levantou a mão para outro aluno. ......"

1005906-10 = "[ns1] \"............! \"\n[ns2] \"O que diabos aconteceu? \"\n[ns2]"\n[ns2]"O que diabos aconteceu?""

1005906-13 = "Também não conheço os detalhes. ......"

1005906-14 = "Eu estava em uma aula de piscina hoje, e #nMika estava observando."

1005906-15 = "[s] \"...... tour? \""

1005906-16 = "Sim. Também aconteceu no final da aula, e ele não estava na piscina para uma visita, mas estava andando por toda parte. ......"

1005906-17 = "Também houve problemas com a atitude de Mika em sala de aula."

1005906-18 = "Alguns alunos ficaram insatisfeitos com isso e aparentemente protestaram. #nAo fazer isso, Mika levantou a mão para eles e ......"

1005906-22 = "[ns] \"............. \""

1005906-23 = "Felizmente, a aluna não ficou gravemente ferida e #nMika queria ser suspensa, então a história terminou aí. ......"

1005906-24 = "É uma situação um pouco complicada, #n e espero que não seja muito importante, devido à posição do Mika no momento. ......"

1005906-25 = "Então, ...... bem, eu estava pensando se poderia pedir à Mika para ser uma professora de placa de Petri. ......"

1005906-26 = "[s]\"...... entender. \""

1005906-30 = "Obrigado!"

1005906-34 = "Agora, se você me der licença, tenho alguns assuntos a tratar."

1005906-38 = "[ns] \"....... \""

1005906-44 = "(Ele deveria assumir a custódia de Mika, que estava em prisão domiciliar)."

1005906-50 = "[ns] \"Mika ....... \""

1005906-51 = "Haha. ...... Estou assim novamente."

1005906-52 = "Decepcionado ......? Mas você sabe, #n, que sou um mau aluno."

1005906-53 = "Se você o deixar sozinho, ele se meterá em todo tipo de problema. ...... Ele é uma criança problemática."

1005906-57 = "Estou me metendo em um monte de problemas. ...... Acho que está na hora..."

1005906-64 = "[ns] \"Mika ...... Talvez você esteja sendo assediada ou algo assim? Está tudo bem com você? \""

1005906-65 = "Você pode obter mais informações em ...... Umm, sim!"

1005906-66 = "[\"Fato de banho, você o perdeu? \""

1005906-70 = "I ......"

1005906-71 = "Comprei o traje de banho ...... do meu professor, e era um traje de banho ......."

1005906-78 = "Por que, por que, por que!"

1005906-79 = "Os trajes de banho estão disponíveis em ......! #n Huh? Onde ......!"

1005906-85 = "Pfft. ...... As "princesas" do Tea Party não conseguem nem mesmo administrar seus #n-lockers."

1005906-86 = "Bem, parece que até agora tudo foi feito por um acompanhante, então #n é assim que as coisas são."

1005906-87 = "Mas foi bom, não foi? Ele é um homem de status elevado. ......#n Ele não gostaria de estar na mesma piscina que pessoas comuns como nós, não é?"

1005906-88 = "Oh, minha ...... lixeira está cheia. Será que havia muito lixo #n? ...... Pfft."

1005906-89 = "............."

1005906-101 = "Não. ...... Procurei uma lixeira e um incinerador. ......"

1005906-102 = "Não foi encontrado em lugar nenhum: ......! #nPor que ......? #nÉ importante, mas ...... onde diabos está ......?"

1005906-107 = "Oh, há lixo aqui, não há?"

1005906-111 = "......!"

1005906-112 = "Lixo, ou melhor, um traje de banho?"

1005906-116 = "Bem, ele já está desfiado e não posso usá-lo."

1005906-125 = "Como vocês se atrevem? ......"

1005906-127 = "Oi, oi!"

1005906-128 = "O quê? Ouvi dizer que o Mica é um covarde que nem consegue mais se rebelar!"

1005906-129 = "Isso está me matando. ......!"

1005906-136 = "(...... não)"

1005906-137 = "(...... Se isso não funcionar, vou ter que voltar para ......)"

1005906-138 = "Bem, ela é uma bruxa. ...... #nta, me ajude!"

1005906-142 = "Espere, não me deixe!"

1005906-146 = "Não puxe nem um pouco. ...... Ugh, uau!"

1005906-152 = "Sim, foi. ......."

1005906-157 = "O traje de banho está disponível em ......"

1005906-159 = "......."

1005906-160 = "Desculpe-me, professor. ...... #nO traje de natação que meu professor comprou para mim está estragado. ......"

1005906-161 = "Bem, é claro. ......#nEu fiz tantas coisas terríveis em minha vida. ......#nSe eu fosse um "bom menino", isso não teria acontecido."

1005906-162 = "Mas, desta vez, o ...... realmente não funcionou ...... bem, embora eu tenha feito o melhor que pude ......#n... ...."

1005906-163 = "Desculpe-me. ...... Eu sempre estrago a boa vontade do professor. ...... #nEu estava ansioso para nadar com esse traje de banho. ......"

1005906-164 = "...... Eu sabia que não conseguiria. ......"

1005906-165 = "Não importa o que façamos, não podemos recuperá-la. ......"

1005906-166 = "[s]\"......Mika, você tem tempo hoje? \""

1005906-167 = "...... eh?"

1005906-168 = "Tempo ......? #n Umm, yeah. Ainda é bem antes do toque de recolher, mas ......"

1005906-174 = "[ns] \"Well, let's go and do swimming lessons. \""

1005906-175 = "...... eh?"

1005906-182 = "Varejistas de roupas designados pela Trinity."

1005906-185 = "...... Sim, é. #nEstá bastante danificado, mas não impossível de consertar."

1005906-187 = "......."

1005906-188 = "Acho que ele deixará algumas marcas de costura, mas não é um problema para o uso normal. Como você acabou de comprá-lo, nós o aceitaremos gratuitamente."

1005906-189 = "[\"Muito obrigado. \""

1005906-190 = "Isso acabará em breve, aguarde um momento."

1005906-194 = "Aqui está, por favor."

1005906-199 = "......."

1005906-200 = "Os trajes de banho também podem ser consertados. ......"

1005906-201 = "Eu não sabia. ......#nPensei que teria de comprar um novo quando ele estragasse. ......"

1005906-205 = "Se, senhor. ......? Para onde você está indo? ......#n Esta não é uma sala de aula. ......"

1005906-206 = "Aulas de natação, certo ......? #nNão sei o que eles fazem. ......"

1005906-207 = "Além disso, nenhum lugar deve estar aberto nesse momento..."

1005906-208 = "[\"Eu tenho um lugar agradável. \""

1005906-213 = "Campos de treinamento e piscinas"

1005906-215 = "Você pode encontrá-lo aqui: ......"

1005906-220 = "Entendo. ...... Lembro-me de que havia um lugar para isso."

1005906-221 = "[\"Um lugar inesquecível, certo? \""

1005906-222 = "...... Sim."

1005906-223 = "Ela foi deixada sozinha por muito tempo, descuidada e suja ......, #n realmente, embora estivesse tão bagunçada que era impossível de ser controlada ......"

1005906-224 = "É um renascimento muito bonito agora."

1005906-225 = "[s3] \"Sim, os trajes de banho também. \"\n[s4] \"Outros são iguais, eu acho. \"\"\n[s4] \"}"

1005906-228 = "......."

1005906-229 = "Então, agora você tem aulas de natação com o professor?"

1005906-230 = "Vocês dois estão sozinhos ...... no meio da noite ...... e em um lugar impopular? O #n está bem? Não seria muito ruim se eles descobrissem?"

1005906-231 = "[s]\"Oh! Estou vendo. ....... \""

1005906-232 = "Bem, estou bem☆#nEu vou me trocar, então me espere!"

1005906-236 = "[ns] \"Espere um pouco, Mika! \""

1005906-239 = "Pronto!"

1005906-240 = "Veja, doutor! Está um pouco apertado, mas já voltou ao normal!"

1005906-244 = "Qual é a minha aparência? Ele fica bem em mim? #nFica bem com o traje de banho da escola?"

1005906-245 = "Ei, ei?"

1005906-246 = "[s]\"Uh ...... Mika, você está um pouco ...... perto demais. \""

1005906-247 = "Ha-ha-ha! O que é isso, uma colegial em um traje de banho? Estou muito magoado por você ter fugido."

1005906-248 = "[s] \"....... \""

1005906-259 = "Uau. ...... Pensei sobre isso com calma e estou muito envergonhado. ......"

1005906-260 = "[\"Mika era o tipo de pessoa cujo corpo se movia antes que ele pudesse pensar. \""

1005906-261 = "Hahaha* Sim. #nAs raízes não parecem mudar tão facilmente."

1005906-265 = "Você quer entrar, professor? #É uma sensação tão boa."

1005906-266 = "[s]\"Não, nós nos recusamos. ....... \""

1005906-270 = "Dê uma olhada! Ali! #nEste lugar agora está fora dos limites!"

1005906-271 = "Calma, senhor! Os guardas de segurança estão aqui!"

1005906-272 = "[s5] \"Acabei de me lembrar de algo urgente, desculpe! Vejo vocês depois! \"\n[s6] Pegue o Mika e saia correndo a toda velocidade."

1005906-277 = "Se, senhor!"

1005906-282 = "Se, senhor!"

