[translation]
1006108-1 = "説明の場"
1006108-2 = "（言われた時間に合わせて、聖堂裏側の公園に向かった）"
1006108-3 = "（公園に人影は見当たらず、遠くからサクラコが現れた）"
1006108-7 = "先生、こちらです。お越しいただきありがとうございます。"
1006108-8 = "できれば一人で解決したいと思っていたのですが……"
1006108-9 = "問題が大きくなるばかりで、この場を設けさせていただきました。"
1006108-10 = "[s1] \"大丈夫だよ。\"\n[s2] \"問題が大きく……？\""
1006108-13 = "そうですね、単刀直入に申し上げますと……"
1006108-14 = "最近……"
1006108-20 = "私への「誤解」が、日に日に増していってるようです。"
1006108-24 = "[ns3] \"そ、そっか……\"\n[ns4] \"とうとうこの日が来たんだね。\""
1006108-29 = "やはり驚かれないんですね。先生もある程度予想していたということでしょうか。"
1006108-30 = "もちろん、シスターの皆様から気難しい人だと思われていたことは分かってましたが……"
1006108-31 = "仕事の性質上、ある程度威厳も必要と考えていたので、特に気に留めませんでした。"
1006108-32 = "流行を気にして起こした行動は除いて……ですね。"
1006108-33 = "……ですが、最近気づいてしまったのです。皆様が単に気難しい人と考えているのではなく――"
1006108-34 = "――「恐れている可能性がある」ということを！"
1006108-35 = "考え過ぎ……ですか？"
1006108-36 = "いえ……私もそうあってほしいと思っていましたが、残念ながら違うみたいです。"
1006108-37 = "これはかなり重要な問題ではないかと……シスターの皆様には、ここはどこよりも心安らぐ場所であってほしいのです。"
1006108-38 = "なので、これを解決するために事実を調査したり、"
1006108-39 = "時には皆様を一人ずつお呼びして、説明する場を設けたりもしたのですが……"
1006108-43 = "[ns5] \"えっ……！？\"\n[ns6] \"それじゃ疑惑が深まっちゃうよ……！\""
1006108-46 = "はい、結果的に……先生の仰る通りになったみたいで。"
1006108-47 = "他のことならまだ私の方で解決できそうなのですが、この問題ばかりはうまく解決できず……先生にお願いできればと思った次第です。"
1006108-48 = "シスターとして、自身の問題を先生にお願いするのは不躾だということ、よく存じております。"
1006108-49 = "しかし時には、自分のプライドや意志よりも、現状の解決を優先すべきとも言えるでしょう。"
1006108-50 = "今の状況が……まさにそうだと思います。"
1006108-51 = "……先生、"
1006108-52 = "厚かましいお願いということは重々承知ですが、"
1006108-53 = "どうか、お力を貸していただけませんでしょうか。"
1006108-54 = "[s7] \"もちろん。厚かましくも不躾でもないよ。\"\n[s8] \"賢明で、勇気のある行動だと思う。\""
1006108-57 = "先生……。"
1006108-58 = "ありがとうございます。快諾していただけるなんて思ってもみませんでした。"
1006108-59 = "他の方でもなく、先生からそう言っていただけて本当に気持ちが楽になりました。"
1006108-60 = "今日は、先生が忙しい時に備えて私一人でと考えていたのですが……"
1006108-61 = "[s] \"……\""
1006108-63 = "[ns] \"待って、何をするの？\""
1006108-67 = "それでは参りましょう。私についてきてください。"
1006108-68 = "皆様が待っています。先生のお言葉なら……きっと他の方たちも信じてくれます。"
1006108-81 = "[ns9] \"サ、サクラコさん、これは……\"\n[ns10] \"シスターのみんなが集まってる……\""
1006108-87 = "はい。皆様にお時間を作っていただき、この場に集まっていただきました。"
1006108-88 = "あとは、この場で先生から一言頂ければと。"
1006108-89 = "――私は、"
1006108-91 = "変な人ではないと！！！"
1006108-92 = "[s11] \"ま、待ってサクラコ！\"\n[s12] \"これはあまり良い方法じゃ――！！\""
1006108-95 = "皆様、お集まりいただきありがとうございます。今日は特別に、先生をお招きいたしました！"
1006108-100 = "これより、先生から心が軽くなるお話を頂けると思います。"
1006108-101 = "では皆様、ご静聴ください！"
1006108-105 = "ふふっ。"
1006108-106 = "では先生、"
1006108-107 = "……よろしくお願いいたします。"
1006108-112 = "（結局、みんなの前でサクラコは良い人であると説明することになった）"
1006108-113 = "（サクラコは満足げな笑顔を浮かべていたが……）"
1006108-117 = "（当然、更に誤解を招く結果になった）"
