[translation]
1006106-1 = "Hobbies inesperados"

1006106-2 = "(Ele foi ao escritório da catedral com Sacraco para consulta)."

1006106-6 = "O senhor está aqui, doutor?"

1006106-12 = "Obrigado por vir aqui, mesmo sendo uma situação pessoal."

1006106-13 = "Eu deveria ter visitado o local, mas não conseguiria sair do meu lugar agora. ......"

1006106-14 = "[s1] \"Tudo bem, tenho trabalho a fazer, certo? \"\n[s2] \"Está tudo bem, eu sei. \"\n[s2]""

1006106-17 = "...... Obrigado, doutor."

1006106-21 = "Agora, vamos direto ao argumento principal, pois não queremos tomar mais tempo do professor."

1006106-22 = "Portanto, esta é uma história sobre ...... 'hobbies'."

1006106-23 = "[s]\"Hobby? \""

1006106-24 = "Sim, nós fizemos. Recebi uma pergunta como essa há algum tempo."

1006106-25 = "Eu estava ouvindo uma das irmãs que disse que estava preocupada com o fato de ter menos tempo para seus hobbies. ......"

1006106-26 = "A irmã me perguntou quais eram meus hobbies."

1006106-27 = "E eu não pude responder."

1006106-28 = "Era a única maneira de fazer isso. Na verdade, eu não tinha hobbies para chamá-los de hobbies. ......"

1006106-29 = "Eu nem sei o que é um hobby."

1006106-30 = "Sei que, só porque as outras pessoas têm hobbies, não preciso me igualar a elas."

1006106-31 = "Mas ainda assim ......"

1006106-32 = "[s3]\"Você também quer entender as outras pessoas,\"\n[s4]\"Você quer saber sobre os sentimentos delas. \""

1006106-35 = "Sim, então essa não é a minha história."

1006106-36 = "Meu dia está definido e não tenho tempo extra."

1006106-37 = "Mesmo que consigam algum tempo, elas fazem uma retrospectiva dos eventos da Catedral e do itinerário das Irmãs."

1006106-38 = "Não se trata de algo que consome muito tempo e não é um fardo."

1006106-39 = "...... isso, senhor."

1006106-45 = "Gostaríamos de saber o que você faz quando tem tempo e quais são seus hobbies."

1006106-46 = "Disseram-me que o professor tem uma agenda mais ocupada do que a minha, mas também tem hobbies pelos quais é apaixonado."

1006106-47 = "Então, como você pode ter um hobby e por que você quer ter um hobby?"

1006106-48 = "-- Sim?"

1006106-49 = "É um hábito ...... em vez de um ato intencional ou significativo?"

1006106-53 = "...... Entendo."

1006106-54 = "Eu achava que os hobbies eram algo que você ...... fazia conscientemente para se curar ou adquirir um novo ego."

1006106-55 = "É mais inconsciente do que eu imaginava. Acho que entendo um pouco."

1006106-56 = "Meu hobby também pode ser ......,"

1006106-57 = "[\"Lembre-se de seu comportamento recente. \""

1006106-61 = "[ns5] \"O que você fez inconscientemente, ou ߋ"\n[ns6] \"O que você fez sem propósito ou significado. \""

1006106-66 = "Estou vendo: ......"

1006106-67 = "Ações que tomamos inconscientemente e coisas que fizemos sem motivo: ......"

1006106-68 = "Isso significa tempo de espera composto por intervalos durante o trabalho ou tempo gasto em movimento?"

1006106-69 = "Se for esse o momento, visite ......"

1006106-70 = "Principalmente enviando momotalks para professores,"

1006106-71 = "Você pode falar com seu professor sobre qualquer assunto que lhe vier à mente. ......"

1006106-72 = "Quando tiver um problema, você pode oferecer orientação e ......"

1006106-73 = "Acho que eu estava..."

1006106-74 = "......"

1006106-84 = "[ns7] \"......Sakurako? \"\n[ns8] \"What's wrong? \""

1006106-89 = "Oh, ...... eh,"

1006106-90 = "Desculpe-me também: ......"

1006106-94 = "...... isso, senhor."

1006106-95 = "Eu realmente sinto muito, mas posso terminar esta história agora?"

1006106-96 = "Acho que posso lhe dar essa resposta ....... Eu só queria um tempo sozinho. ......"

1006106-97 = "Estou ciente de que esse é um comportamento rude sem qualquer preâmbulo,"

1006106-98 = "Por favor, tenha paciência conosco. ......"

1006106-99 = "Kyou, hoje: ......"

1006106-100 = "Não vamos mais longe, por favor. ......"

1006106-105 = "[ns] \"............. \""

1006106-107 = "[ns] \"......? \""

1006106-109 = "(Ele saiu da catedral, sendo acompanhado por Sakurako, que, por algum motivo, estava com uma expressão de maluca)."

