[translation]
1006103-1 = "「流行」"
1006103-3 = "（シャーレの業務用品を買うために商店街を訪ねた）"
1006103-4 = "（様々な店が立ち並ぶなか、アクセサリーショップの前にサクラコがいる）"
1006103-8 = "……ふむ……うーん。"
1006103-12 = "これは……いえ、違いますね。#nやはり……"
1006103-13 = "……ううーん。"
1006103-14 = "[s1] \"サクラコ、こんにちは。\"\n[s2] \"ここで何してるの？\""
1006103-19 = "……っ！！？せ、先生！？#nこ、こんにちは……！"
1006103-20 = "……私、ですか？"
1006103-21 = "わ、私はたまたま……こちらを通りがかったので……"
1006103-22 = "少し気になる物があって、眺めていたところです。"
1006103-23 = "その……ベールや、アクセサリーを変えてみようかなと思いまして。"
1006103-27 = "あ、好みとかそういう話ではなく、"
1006103-28 = "なんといいますか……"
1006103-29 = "どのように見えるかは、少し分かりませんが……"
1006103-36 = "他の方々はアクセサリーを変えているのに、私だけつけてなかったりすると、"
1006103-37 = "その、遅れてると思われるというか……"
1006103-38 = "[s3] \"うんうん、分かるよ。\"\n[s4] \"流行の話だよね。\""
1006103-41 = "私はいつも聖堂におりますので、#n外部の用事は他のシスターが担当してくださっていて……"
1006103-42 = "ご一緒したい時もありますが、"
1006103-43 = "やはり一人は聖堂に残らなくてはなりません。"
1006103-44 = "そうなると、自然と外部との隔たりができてしまいますし、"
1006103-45 = "他のシスターが話す内容を基に、想像して理解するしかありません。"
1006103-46 = "ですが、こういった想像は事実と異なるものなので……"
1006103-50 = "……その、先ほどの、"
1006103-51 = "モモトークのように……なってしまう事も……。"
1006103-52 = "[s5] \"そういう事だったんだね。\"\n[s6] \"大丈夫だよ、新鮮だったし。\""
1006103-55 = "お心遣い、痛み入ります。"
1006103-56 = "それで……"
1006103-57 = "何か新しいアクセサリーを買おうと思うのですが……"
1006103-58 = "先生は、最近流行してるデザインなど、ご存知ですか？"
1006103-59 = "もしご存知でしたら、ご教示いただけますと……"
1006103-63 = "ああ、そうでしたか。"
1006103-64 = "そうですよね……先生はお忙しいのですから、致し方ありません。"
1006103-68 = "失礼いたしました。"
1006103-69 = "これ以上先生のお時間を奪うのも申し訳ないので、ここは自分で――"
1006103-76 = "お客様！先ほどからずっとご覧になってますが、何かお探しの物でもありますか？"
1006103-77 = "あっ、邪魔をしてしまい申し訳ありません。"
1006103-78 = "その、どれも素敵で選べずにおりまして……"
1006103-79 = "こういった分野は、少々疎くて……"
1006103-83 = "なるほど、そうでしたか！"
1006103-85 = "そういうことでしたら、ご心配なく！"
1006103-90 = "私がお客様にピッタリの商品をお探しします！"
1006103-95 = "ささ、中へどうぞ！#nお客様、素敵ですからどんな物でもお似合いですよ！"
1006103-96 = "ええっと、その……まっ、待ってください――！？"
1006103-101 = "ひゃぁぁああああぁっ！？！？"
1006103-106 = "[ns7] そのままにしておけないので、ついていく。\n[ns8] サクラコが困っているのでついていく。"
1006103-114 = "（サクラコと店主の後を追って、店内に足を踏み入れた）"
1006103-121 = "（店内でいろいろな商品を紹介されて困っていたサクラコを連れ、店を出た）"
1006103-126 = "……ふぅ、すごい一日でしたね。"
1006103-127 = "今日は何から何まで、ありがとうございました先生。"
1006103-128 = "先生がいなかったと思うと……考えるだけで恐ろしいです。"
1006103-129 = "やはり、流行に乗るというのは容易ではありませんね。"
1006103-130 = "……？無理についていく必要は無い、ですか？"
1006103-131 = "……ですが、私はシスターですし、他者を理解するためには様々な知識が……"
1006103-132 = "[s9] \"変わらないものが、良いことだってあるよ。\"\n[s10] \"心を開ける場所というのは、そういう場所だから。\""
1006103-135 = "先生……。"
1006103-136 = "ふふっ。"
1006103-137 = "そう言ってくださって、少し気持ちが楽になりました。"
1006103-138 = "最後まで助けていただいてしまいましたね。#nシスターなのに助けてもらってばかりで……お恥ずかしい限りです。"
1006103-139 = "……。"
1006103-140 = "ですが……あまり嫌な感じではありません。"
1006103-141 = "どうしてでしょうか。#n自分の至らなさに、何度もくじけそうになった一日なのに……"
1006103-142 = "……もしかすると、"
1006103-143 = "私に言っていただいたように、先生も……"
1006103-147 = "私にとって「変わらないもの」だからかもしれませんね。"
1006103-149 = "（微笑むサクラコを大聖堂の前まで送って、シャーレに帰った）"
