[translation]
1007703-1 = "não é grande coisa"

1007703-2 = "(Passei em um shopping para fazer uma pausa depois do trabalho...)"

1007703-6 = "(Eu vi Ichika na frente da loja de música)"

1007703-7 = "……sim?"

1007703-8 = "Pronto, senhor. O que você está fazendo em um lugar como este?"

1007703-9 = "Bem, sou eu."

1007703-10 = "Bem, deixando isso de lado, estou feliz em conhecê-lo."

1007703-11 = "...... peido?"

1007703-12 = "O que você estava olhando...? #nOh, estou curioso sobre isso."

1007703-13 = "Não há grande razão, mas estou tocando violão..."

1007703-14 = "...Você está interessado no violão? #nHmm, nunca tive interesse nisso até agora."

1007703-15 = "Eu nunca toquei nisso em primeiro lugar."

1007703-19 = "Haha, essa é uma boa reação."

1007703-20 = "Bem, eu vi alguém tocando e cantando na rua esta manhã."

1007703-21 = "Há algo nessa aparência..."

1007703-22 = "Eu acho legal ser apaixonado por algo que você gosta."

1007703-23 = "Isso me fez sentir que deveria tentar algo novo."

1007703-24 = "Porém, quando vi isso na minha frente..."

1007703-25 = "……mãe."

1007703-26 = "Bem, eu realmente não entendo... Mesmo que eu me imagine tocando violão, simplesmente não consigo entrar no assunto."

1007703-27 = "Bem, mas! Quando experimentei, de repente fiquei interessado nele!"

1007703-28 = "…………."

1007703-29 = "Estou brincando. ...Isso nunca aconteceu antes."

1007703-30 = "...Talvez."

1007703-31 = "Ser capaz de ser apaixonado por algo pode ser um talento."

1007703-35 = "……sim?"

1007703-36 = "Por que você não tenta uma vez...?"

1007703-37 = "Você quer perguntar...?"

1007703-38 = "...Meu desempenho?"

1007703-39 = "EU……"

1007703-40 = "Uma guitarra...?"

1007703-41 = "...Bem..."

1007703-45 = "Não, não, não! Do que você está falando, de repente! ?"

1007703-46 = "Eu não acabei de dizer que nem toquei nisso?"

1007703-47 = "[s1] \"Por que não começamos com algo fácil?\"\n[s2] \"Vou praticar com você.\""

1007703-50 = "Ah, mas..."

1007703-51 = "Mesmo se você de repente disser algo assim... estou com problemas..."

1007703-52 = "Tenho a sensação de que quero experimentar..."

1007703-53 = "Afinal..."

1007703-54 = "Hum..."

1007703-55 = "...Hum."

1007703-56 = "Bem... vai dar certo de alguma forma! #nAlém disso, o Sensei disse que queria ouvir!"

1007703-57 = "Por favor, não ria, mesmo que seja ruim!"

1007703-58 = "[s3] \"Claro que não farei isso.\"\n[s4] \"Vamos com calma!\""

1007703-61 = "Pois bem, vamos começar com...o mais barato para iniciantes...!"

1007703-67 = "(Quando Ichika entrou na loja, ela comprou um violão que estava exposto na vitrine.)"

1007703-68 = "(Então, carreguei meu violão nas costas e fui para um rio próximo.)"

1007703-70 = "Não... é uma guitarra de verdade."

1007703-71 = "Por alguma razão, pensei que era bom, mas nunca pensei que fosse comprá-lo... até comprei a partitura."

1007703-72 = "Seria constrangedor se eu jogasse num rio como este porque as pessoas pensariam que eu era bom. mãe."

1007703-73 = "Bem, mas... por enquanto, vamos dar uma olhada no livro para iniciantes..."

1007703-74 = "Se eu fizer como está escrito, vai funcionar de alguma forma...? #nTalvez."

1007703-75 = "[s5] \"Talvez você não consiga tocar bem imediatamente, mas...\"\n[s6] \"Vamos tentar tocar levemente primeiro.\""

1007703-78 = "Hmm...talvez eu devesse segurar isso...?"

1007703-79 = "Hmm... o código... espere aqui..."

1007703-80 = "...Então, assim?"

1007703-84 = "...É assim que parece?"

1007703-88 = "[ns7] \"Esta é realmente sua primeira vez...?\"\n[ns8] \"Não acredito que você jogou tão facilmente...\""

1007703-91 = "peido?"

1007703-92 = "Bem, é uma guitarra para iniciantes! #nAcho que não é tão difícil."

1007703-93 = "Acho que todo mundo vai conseguir fazer isso na hora se olhar o livro, certo? #n Qualquer um pode cozinhar seguindo a receita."

1007703-94 = "Então eu me pergunto se os instrumentos musicais são parecidos... assim como os utensílios de cozinha, eles foram feitos pelas mesmas pessoas."

1007703-95 = "Qualquer um pode fazer isso se souber como."

1007703-96 = "Depois de entender o básico, tudo o que você precisa fazer é aplicá-lo."

1007703-97 = "Não é grande coisa."

1007703-98 = "……sim?"

1007703-99 = "Ainda incrível...?"

1007703-100 = "Você já ouviu das pessoas ao seu redor que você pode fazer qualquer coisa...?"

1007703-101 = "Bem, não é zero..."

1007703-102 = "...Mesmo que eu te elogie tanto, nada resultará disso!"

1007703-103 = "Eu gostaria de praticar um pouco mais do que isso."

1007703-107 = "Posso pedir ao Sensei que escolha sua música preferida desta partitura? #nVou tentar brincar um pouco."

1007703-110 = "(Depois passamos um tempo à beira do rio ouvindo o violão de Ichika)"

1007703-111 = "(Ichika disse que era sua primeira vez, mas nenhuma de suas performances parecia uma habilidade para iniciantes.)"

