[translation]
1007305-1 = "até a última garfada"

1007305-5 = "(Ui ficou ocioso na praia à noite)."

1007305-10 = "...... Ah, senhor. Por aqui."

1007305-16 = "Eu não sabia que era tão cedo. #Na verdade, eu me arrependi um pouco depois de enviar o Momotalk."

1007305-17 = "De fato, não é uma tarefa importante. Eu só quero dar uma pequena caminhada ...... então, eu apenas pensei."

1007305-18 = "......, mas o médico veio até mim com duas palavras."

1007305-19 = "Bem, em vez disso, eu diria: ......"

1007305-23 = "Visite ...... conosco. Gostaria de se juntar a nós?"

1007305-24 = "[s1] \"Claro, com prazer. É um Americano, não é? \"\n[s2] Receba uma xícara de ui."

1007305-31 = "(Caminhando à beira-mar com Ui, com o Americano na mão)"

1007305-34 = "...... A Congregação dos Santos sempre encontrou um lugar tão agradável."

1007305-38 = "Sempre achei que se tratava de uma organização inflexível e rígida. ......"

1007305-39 = "Isso pode não ser sempre o caso."

1007305-40 = "Hmmm... ......"

1007305-41 = "......?"

1007305-42 = "Senhor, o que há de errado? Bem, se você ficar me olhando assim, ......"

1007305-43 = "[s3]\"Hoje o Ui está com uma expressão mais suave do que o normal. \"\n[s4]\"Você está se acostumando a estar em uma ilha deserta? "

1007305-48 = "Hum, ...... Sim."

1007305-49 = "Então, tomei coragem para entrar em contato com o médico pelo e-mail ......."

1007305-50 = "Ele pode ser encontrado em ......"

1007305-51 = "...... O sol já se pôs."

1007305-52 = "Não há ninguém por perto, é um lugar tranquilo. #nQuando está escuro assim, você não precisa se preocupar em ser visto."

1007305-53 = "Para mim, o ambiente não poderia ser melhor."

1007305-54 = "...... é como um vampiro em um [ruby=fairy tale]conto de fadas[/ruby] se você apenas cortasse as linhas agora."

1007305-55 = "Ufa. Não me dei ao trabalho de explicar, você podia prever isso. ...... professor."

1007305-56 = "O professor está familiarizado com uma variedade de alunos, portanto..."

1007305-57 = "Alguns deles certamente devem ter sido mesquinhos ......#n inseguros de si mesmos e preocupados com o que os outros pensariam deles."

1007305-58 = "...... Não acredito que eu seja especial."

1007305-59 = "[s5] \"Mas oui é oui. \"\n[s6] \"Você não acha que isso é mesquinho? "

1007305-64 = "...... Sim, o que é?"

1007305-65 = "Estou vendo: ......"

1007305-66 = "Quando um professor lhe diz o que fazer, você pode agir naturalmente. ......"

1007305-67 = "......E provavelmente estou mais perto de ser difícil do que petulante."

1007305-68 = "Não, não quero ser humilhante. #nMas deve ser verdade, e estou ciente disso."

1007305-69 = "Às vezes, intencionalmente, eles se comportam dessa maneira. ......"

1007305-70 = "Porque assim menos pessoas entrarão em meu espaço pessoal."

1007305-71 = "......, mas estou tendo problemas com isso ultimamente porque acho que não está funcionando."

1007305-75 = "............."

1007305-76 = "......, mas não vou dizer quem."

1007305-77 = "Ou devo colocar isso em palavras?"

1007305-78 = "[s7] \"Haha, também estamos em apuros. \"\n[s8] \"Mais uma vez, que piada. "

1007305-81 = "...... Huh, isso foi intencional. Eu sabia disso, no entanto."

1007305-82 = "Quanto a mim, não me importo, porque não gosto de conversas mal resolvidas e ...... prefiro ajudar."

1007305-83 = "Você é um professor, então deve ser muito importante para você estar presente para eles, certo?"

1007305-84 = "Graças a você, sinto que eu também posso mudar, pouco a pouco, ......."

1007305-85 = "......, mas não pretendo continuar sendo pressionado."

1007305-86 = "Às vezes, você sabe, ...... às vezes, você sabe, você os estraga ou algo assim. ......"

1007305-87 = "...... Professores, vingue-se."

1007305-88 = "Por exemplo, vocês podem ter um momento particular juntos, como este, em ......."

1007305-89 = "...... ugh."

1007305-90 = "Como você pôde dizer uma coisa tão entediante ...... ah ...... pior ......"

1007305-91 = "...... Você não tem sorte de ser pego por mim, doutor."

1007305-92 = "[s9] \"Assumirei a responsabilidade de seu professor até o fim. \"\n[s10] \"Estarei sempre ao seu lado, cuidando de você ߋ "ߋ""

1007305-95 = "...... Huh. Lá vem você de novo."

1007305-96 = "Vamos terminar essa história. ......"

1007305-97 = "Como eu disse no início ...... hoje, eu só queria caminhar um pouco."

1007305-98 = "Essa xícara ainda está lá, não está?"

1007305-99 = "Você não precisa nos contar nada. ......"

1007305-103 = "Pelo menos até você terminar de beber: ......"

1007305-104 = "Por que você não faz uma pequena caminhada: ......"

1007305-105 = "...... está bem?"

1007305-109 = "[ns11] Tomar um gole em uma xícara. \Saia com passos curtos."

1007305-112 = "...... phew."

1007305-114 = "...... Nada mal."

