[translation]
1007703-1 = "大したことじゃない"
1007703-2 = "（仕事終わりに休憩でショッピングモールに寄ったところ……）"
1007703-6 = "（楽器屋の前でイチカの姿を見かけた）"
1007703-7 = "……ん？"
1007703-8 = "あれ、先生。こんなところでどうしたんすか？"
1007703-9 = "って、それは私の方っすよね。"
1007703-10 = "ま、それは置いといて、会えて嬉しいっす。"
1007703-11 = "……へ？"
1007703-12 = "何を見てたか……？#nああ、そりゃ気になりますよね。"
1007703-13 = "大した理由があるわけじゃないんすけど、ちょっとギターを……"
1007703-14 = "……ギターに興味があるのかって？#nんー、今までまったく興味なかったんすけどね。"
1007703-15 = "そもそも触ったことすらないんで。"
1007703-19 = "はは、いい反応っすね。"
1007703-20 = "まあ、その……今日の朝、路上で弾き語りしてる人を見かけたんすよ。"
1007703-21 = "その姿がなんか……"
1007703-22 = "自分の好きなものに熱中するのって、なんかカッコいいなって。"
1007703-23 = "それで、自分も新しいことに挑戦しようかなって気持ちになったんす。"
1007703-24 = "でも、いざこうして目の前にしてみると……"
1007703-25 = "……はは。"
1007703-26 = "やっぱ、よく分かんないっす……ギターを弾いてる自分を想像しても、なんとなく夢中になれる気はしなくて。"
1007703-27 = "ま、でも！やってみたら、急に興味がワッと溢れたりして！"
1007703-28 = "…………。"
1007703-29 = "なんて、冗談っすけど。……これまでもそういう事なかったんで。"
1007703-30 = "……もしかしたら。"
1007703-31 = "何かに熱中できるのも、才能なのかもしれないっすね。"
1007703-35 = "……ん？"
1007703-36 = "一度やってみたらどうかって……？"
1007703-37 = "聞いてみたいんすか……？"
1007703-38 = "……私の演奏を？"
1007703-39 = "私が……"
1007703-40 = "ギターを……？"
1007703-41 = "……えーっと。"
1007703-45 = "いやいやいや！なに言ってるんすか、いきなりそんな！？"
1007703-46 = "触ったことすらないってさっき言ったじゃないすか！"
1007703-47 = "[s1] \"まずは簡単なところから始めてみたらどうかな？\"\n[s2] \"練習なら付き合うよ。\""
1007703-50 = "や、でも……"
1007703-51 = "いきなりそんなこと言われても……困るっす……"
1007703-52 = "やってみたい気持ちはあるっすけど……"
1007703-53 = "やっぱその……"
1007703-54 = "ううーん……"
1007703-55 = "……う～ん。"
1007703-56 = "まあ……なんとかなるっすよね！#nそれに、先生が聞きたいって言ったんすから！"
1007703-57 = "下手でも笑わないでくださいよ、絶対！"
1007703-58 = "[s3] \"もちろん、そんなことしないよ。\"\n[s4] \"気楽にいこう！\""
1007703-61 = "じゃ、じゃあまずは……初心者用で一番安いやつを……！"
1007703-67 = "（イチカは店に入ると、ショーウィンドウに飾られていたギターを買ってきた）"
1007703-68 = "（そして、ギターを背負い近くの川沿いへと向かった）"
1007703-70 = "いやー……本物のギターっすね。"
1007703-71 = "なんとなーく、いいなと思ってただけなのに、まさか本当に買っちゃうなんて……楽譜も買っちゃったっす。"
1007703-72 = "こんな川沿いで弾いてたら、うまいと勘違いされそうで恥ずかしいっすね。はは。"
1007703-73 = "まぁ、でも……とりあえず初心者用の教本を見て……"
1007703-74 = "書いてある通りにやれば、なんとかなりますかね……？#nたぶん。"
1007703-75 = "[s5] \"すぐにはうまく弾けないかもしれないけど……\"\n[s6] \"まずは軽く鳴らしてみよっか。\""
1007703-78 = "ええっと……ここを、握ればいいんすかね……？"
1007703-79 = "んー……コードは……ここを押さえて……"
1007703-80 = "……で、こう？"
1007703-84 = "……こんな感じっすかね？"
1007703-88 = "[ns7] \"本当に初めて触ったの……？\"\n[ns8] \"そんなにサラッと弾いちゃうなんて……\""
1007703-91 = "へ？"
1007703-92 = "まあ、初心者向けのギターっすから！#nそんな難しくないんじゃないっすかね。"
1007703-93 = "教本を見れば、みんなすぐできるようになると思うっすよ？#n料理もレシピ通り作れば、誰でもできるように。"
1007703-94 = "だから楽器も似たようなものかなって……調理器具と一緒で、同じ人間が作ったものですし。"
1007703-95 = "やり方さえ分かれば、誰でもできるっすよ。"
1007703-96 = "どれも基本を理解すれば、後は応用するだけなんで。"
1007703-97 = "そんなに大したことではないっす。"
1007703-98 = "……ん？"
1007703-99 = "それでもすごいって……？"
1007703-100 = "周りから何でもできるね、って言われたこと……？"
1007703-101 = "ま、ゼロではないっすけど……"
1007703-102 = "……そんなに褒めたって何も出ないっすよ！"
1007703-103 = "それより、もうちょっと練習したいっす。"
1007703-107 = "この楽譜から先生の好きな曲を選んでもらってもいいっすか？#nちょっと弾いてみるんで。"
1007703-110 = "（その後、イチカのギターを聴きながら川辺で過ごした）"
1007703-111 = "（イチカは「初めて」と言っていたが、どの演奏も初心者の腕前には思えなかった）"
