[translation]
1008215-1 = "fita branca da juventude"

1008215-2 = "(Cheguei bem a tempo para a reunião.)"

1008215-8 = "Ah, acabei de chegar também!"

1008215-9 = "Como esperado de um mestre!"

1008215-10 = "Pois bem, vamos dar uma olhada por aqui hoje."

1008215-14 = "Ah, isso é legal."

1008215-19 = "Olha, aquela máscara Hyottoko..."

1008215-20 = "...Seria interessante se meu mestre o colocasse."

1008215-26 = "Ahaha! Cara estranha!"

1008215-27 = "A propósito, se você enrolar esse furoshiki na cabeça..."

1008215-31 = "Ahahaha! O melhor...!"

1008215-32 = "すみません、これくださいー！"
1008215-33 = "Dona! Não há desconto para casais, mas dou uma sacola com cordão grátis!"

1008215-34 = "Ou um casal! ? Não, nós..."

1008215-35 = "[s1] \"Mestre e discípulo---\"\n[s2] \"Casal proibido... hein? Entendo.\""

1008215-38 = "Não, o Sensei também deveria vir! ?"

1008215-39 = "Ou melhor, não é a regra de usar máscara! ?"

1008215-40 = "[s3] \"Hehehe. Tem alguma coisa que você queira astrágalo?\"\n[s4] \"Eu também quero te dar um presente...\""

1008215-43 = "E-eu entendo, então por favor pare de rir desse jeito estranho!"

1008215-44 = "É meio engraçado..."

1008215-45 = "Ah, isso é juventude...!"

1008215-49 = "[ns] \"Agora que penso nisso...\""

1008215-51 = "[ns5] \"Astragalus parece gostar de fitas brancas.\"\n[ns6] \"Você usa outras cores também?\""

1008215-54 = "fita……?"

1008215-55 = "Ah, é isso?"

1008215-56 = "[s] \"Eu me pergunto se há algum tipo de obsessão juvenil.\""

1008215-57 = "Bem, não sou muito específico sobre isso..."

1008215-58 = "...Porque é uma relação Sensei-aluno. Não há segredos desta vez!"

1008215-59 = "O personagem principal do meu romance juvenil favorito é..."

1008215-60 = "Ela estava usando uma fita branca como esta."

1008215-61 = "À primeira vista é apenas uma fita, mas é especial para o protagonista..."

1008215-62 = "Está profundamente ligado à sua juventude."

1008215-63 = "Achei legal ler isso, então tentei imitá-lo."

1008215-64 = "[s] \"Então vou te dar uma fita com o mesmo desenho!\""

1008215-65 = "Se for esse o caso..."

1008215-66 = "Que tal este?"

1008215-67 = "Você estava ouvindo?"

1008215-72 = "[ns] \"Ok, já decidi!\""

1008215-75 = "Mas me pergunto se é realmente bom...."

1008215-76 = "Se você receber isso do seu mestre..."

1008215-77 = "[s] \"Você gostaria de um design diferente?\""

1008215-78 = "Não, não! Estou muito feliz em recebê-lo, mas...!"

1008215-79 = "Ah, isso..."

1008215-80 = "Se sim, por favor aceite...!"

1008215-81 = "Ahhh já!"

1008215-82 = "Entendido. Ah, obrigado Sensei... vou adorar..."

1008215-83 = "[s] \"Sobre o personagem principal de um romance?\""

1008215-84 = "...! Essa história acabou!"

1008215-90 = "Bem, agora...me diverti fazendo compras, então vamos encerrar as atividades juvenis de hoje!"

1008215-94 = "Obrigado pela fita! Até lá!"

1008215-98 = "[ns] \"...eu fui.\""

1008215-99 = "O conteúdo do romance juvenil de que aquela criança estava falando..."

1008215-103 = "Parece que você não sabe."

1008215-104 = "Quando estou em uma loja, muitas vezes me deparo com situações como essa. Hahaha."

1008215-105 = "Na verdade, aquela fita branca..."

1008215-107 = "(O dono da loja me ensinou o significado da fita.)"

1008215-109 = "O que devo fazer..."

1008215-110 = "eu recebi...."

1008215-114 = "O personagem principal..."

1008215-118 = "A primeira fita que recebi do meu amante...!"

1008215-119 = "Nunca esperei que algo assim acontecesse..."

1008215-120 = "Mestre, gostaria de saber se você leu aquele romance...?"

1008215-121 = "Ou é apenas uma brincadeira?"

1008215-122 = "Mas e se..."

1008215-127 = "Ah, já! Por que isso está acontecendo...!"

1008215-131 = "[ns] \"Renge, posso entrar?\""

1008215-133 = "! ? Bem, tudo bem, mas..."

1008215-137 = "[ns] \"Achei que você estivesse aqui.\""

1008215-138 = "Tem algo que te incomoda...?"

1008215-139 = "[s] \"Essa fita, se o romance se desenvolver depois disso...\""

1008215-140 = "Mestre! ?"

1008215-141 = "Afinal, você sabia?"

1008215-142 = "[s7] \"Opa... o que você quer dizer?\"\n[s8] \"Não ouvi nada. Hehe.\""

1008215-145 = "Isso é definitivamente uma mentira!"

1008215-146 = "[s] \"...Mas acho que recriar cenas de romances também é uma atividade juvenil.\""

1008215-147 = "...! !"

1008215-148 = "Sim, é verdade…!"

1008215-149 = "Eca! E-eu não odeio isso, mas…!"

1008215-150 = "Bem, então... acho que terei que colocar uma fita nele."

1008215-151 = "Mas me provocar ainda mais é proibido...!"

1008215-158 = "(Depois disso, colocamos fitas no astrágalo e aproveitamos nossa juventude só nós dois.)"

