[translation]
1008005-1 = "気配り"
1008005-2 = "[ruby=しょくほう]（食蜂と[/ruby]商店街を歩いていると……）"
1008005-8 = "……ふぅん。"
1008005-14 = "[ns1] \"食蜂？\"\n[ns2] \"何か気になることでも……？\""
1008005-17 = "気になった、というかぁ……"
1008005-18 = "どこの世界でも、女子ってグループを作るものなのねぇ。"
1008005-19 = "私もここに来る前はグループの中心だったのよぉ？"
1008005-20 = "状況が変わった今、客観的に観察できるようになったというか？"
1008005-21 = "周りから見た私の姿も、あんな風に映ってたのかもねぇ。"
1008005-22 = "別に悪い意味じゃないわよ。#nむしろ、友人を作るのは自然なことでしょう？"
1008005-23 = "……友達は多かったのか、って？"
1008005-27 = "……そうねぇ。"
1008005-28 = "多かったとは言えないかしら。"
1008005-32 = "もちろん、大切な人は居たわよ？#nでも、私は能力が能力だから、そのあたりの感覚が難しいのよねぇ。"
1008005-33 = "一応言っておくけどぉ、能力を使っていたからといって、一方的な関係だったわけではないのよ？"
1008005-34 = "……先生はそうは思ってない？……そう。"
1008005-35 = "ふふっ……本心なのか、それともリップサービスなのか、どっちでしょうね？"
1008005-36 = "ま、いいわ。別に追求しても仕方ないもの。"
1008005-37 = "……なに？"
1008005-38 = "そんな目でみなくても、別にここで使うつもりはないゾ☆"
1008005-39 = "……[ruby=メンタルアウト]心理掌握[/ruby]は、友達を作るためのものじゃないしぃ？"
1008005-40 = "というか……使おうとしても先生が止めるでしょ？"
1008005-41 = "今は集中できないし、能力も弱まってる気がするけどぉ……"
1008005-42 = "ま、その気になれば使えなくもないのよねぇ。"
1008005-46 = "……あら、動揺しないのね？"
1008005-47 = "[s3] \"悪用するとは思ってないから。\"\n[s4] \"その気だったら、最初の段階で使ってるはずだからね。\""
1008005-50 = "……そうね。#nもし私が動くとしたら、真っ先に先生を「確認」してたわ。"
1008005-51 = "でも、その必要はないというかぁ……"
1008005-52 = "ここでの私は、あくまで訪問客であって、部外者に過ぎないでしょう？#n責任を負う気もなければ、口出しする気もないわよ。"
1008005-53 = "……それに、[ruby=ひと]他人[/ruby]を操作するのは、楽しいわけじゃないもの。"
1008005-54 = "しなくて済むのなら、それに越したことはないしねぇ。"
1008005-55 = "そうね……だから意外と、今は気楽に過ごせてるわぁ。"
1008005-56 = "……もし、能力の存在しない世界だったら、こんな生活を送ってたのかしら。"
1008005-57 = "なぁんて、柄にもないことを思ったりして☆"
1008005-58 = "……あらら？"
1008005-64 = "何の騒ぎ？"
1008005-65 = "お、お客様……困ります。こちらは先着順でして……"
1008005-66 = "いいじゃねえかよ、1個くらい。"
1008005-67 = "野次馬が集まるのは、お店のイメージ的にもマイナスだろ？#nちょっとくらい構わないじゃんか。ほら、な？"
1008005-68 = "そ、そう言われましても……決まりですので……"
1008005-69 = "冷たいな～、それを何とかするのが店員さんの仕事だろ？"
1008005-73 = "[ns5] \"……困ってるみたいだね。\"\n[ns6] \"ちょっと助けに行ってくるね。\""
1008005-76 = "…………はぁ、せっかくの時間が台無しよ。"
1008005-81 = "[ns7] \"……あれ？\"\n[ns8] \"今の音は……\""
1008005-84 = "……！"
1008005-85 = "ルールを守って、あちらにお並びください！"
1008005-86 = "……わっ、分かったって！そんな大声出さなくたっていいだろ……！"
1008005-87 = "次に同じようなことをした場合、責任者を呼ばせていただきますからね！！"
1008005-88 = "チッ、ったくもう……。"
1008005-89 = "[ns] \"…………？\""
1008005-91 = "[ns] \"……食蜂？\""
1008005-94 = "― [log=쇼쿠호]……[wa:300]なぁに？[/log]"
1008005-96 = "[wa:500]― [log=쇼쿠호]どうかしたのかしらぁ。[/log]"
1008005-99 = "[wa:700]― [log=쇼쿠호]いずれにせよ、[wa:870] [/log]"
1008005-100 = "― [log=쇼쿠호]いつかこうなる事だったと[wa:1120]思うのだけど？[/log]"
1008005-103 = "― [log=쇼쿠호]そうでしょう？[/log]"
1008005-106 = "― [log=쇼쿠호]……[wa:500]リモコン？[wa:1100] [/log]"
1008005-107 = "― [log=쇼쿠호]……[wa:500]それ、[wa:750]聞いちゃう？[/log]"
1008005-110 = "[wa:400]― [log=쇼쿠호]ちょっと[wa:230]気配り力が足りないかもぉ？[/log]"
1008005-113 = "[wa:1090]― [log=쇼쿠호]女の子が[wa:620]話そうとしていないならぁ……[/log]"
1008005-115 = "[wa:450]― [log=쇼쿠호]無理に[wa:290]聞こうとしちゃ[wa:540]ダメだゾ☆[/log]"
1008005-118 = "[wa:500]― [log=쇼쿠호]いい？[wa:1140]あなたは[wa:360]何も見ていないし、[wa:1640] [/log]"
1008005-119 = "― [log=쇼쿠호]そもそも[wa:1130]何も起きてなかった。[/log]"
1008005-122 = "― [log=쇼쿠호]……[wa:400]そうよねぇ、[wa:1190]先生？[/log]"
1008005-126 = "（……有無を言わさぬ食蜂の前では、ただ頷くしかなかった）"
