[translation]
1008602-1 = "Garotas e vestidos (1)"

1008602-2 = "Olá, doutor. Desculpe-me por incomodá-lo."

1008602-3 = "[s1] \"Bem-vindos, garotas! Vocês querem beber alguma coisa? \"\n[s2] \"Café? Ou chá? Temos chá oolong e cola também! \"\"\n[s2]]"

1008602-6 = "Então, café, por favor."

1008602-7 = "[\"Ok, eu cuidarei disso! \""

1008602-11 = "Escritório da Sherle, ou ......"

1008602-12 = "...... Sinto que faz muito tempo que não venho aqui."

1008602-13 = "[s]\"De fato, é um sonho que se tornou realidade ter pintinhos aqui. ......\""

1008602-14 = "Além disso, você já está ...... exagerando, senhor."

1008602-18 = "...... hmm? #n...... Isso tudo é macarrão de xícara, certo?"

1008602-19 = "Eles deixaram suas roupas e ...... os pratos ainda estão no ......"

1008602-20 = "Professores e até brinquedos. ......"

1008602-21 = "[s]\"erm, é ......\""

1008602-22 = "...... Professor."

1008602-23 = "[s3] \"Tenho estado ocupado trabalhando na placa de Petri ultimamente, ......, não é? \"\n[s4] \"Eu ia limpar mais tarde, realmente ......! \""

1008602-26 = "Não, não estou tentando culpar o professor."

1008602-27 = "Porque me lembro de quando estava tão ocupado no trabalho que negligenciava minha vida pessoal."

1008602-28 = "Mas eu não me importaria: ......"

1008602-29 = "Mas pensei que, como muitos alunos diferentes entram e saem da placa de Petri, talvez as outras crianças se importassem."

1008602-30 = "[s]\"Ugh, a Hina tem razão. ......\""

1008602-31 = "Então, se ao menos aquele professor ......#n viesse e me ajudasse a limpar a placa de petri de vez em quando ......?"

1008602-32 = "Apesar disso, sou bom em limpeza. ......"

1008602-33 = "também, é claro, se o professor não se importar. ......"

1008602-34 = "[s5] \"hmmm, Hina também está ocupada com o trabalho do Comitê de Disciplina Pública. \"\n[s6] \"Como esperado, não posso incomodá-la muito. "

1008602-37 = "........................ Ah, sim."

1008602-38 = "............."

1008602-42 = "Se o médico disser que sim, tudo bem."

1008602-43 = "[s]\"Uh ...... chicks? Eu disse algo que a ofendeu ......? \""

1008602-44 = "Como eu poderia me sentir ofendido?"

1008602-45 = "...... Então, vou direto ao ponto."

1008602-46 = "[s]\"yes......! \""

1008602-47 = "Kohon......"

1008602-48 = "...... Na verdade, trata-se da consulta."

1008602-49 = "[ruby=Pandemonium Society]A pedra-chave da [ruby=Pandemonium Society]Manmaden[/ruby] Vou fazer uma festa social no [ruby=Pandemonium Society]Keystone of Manmaden[/ruby] Job."

1008602-50 = "[\"Na Gehenna, eles até fazem festas como essa. \""

1008602-51 = "Parece que as principais figuras do Gehenna e as grandes pessoas da sociedade fiscal dos Kivotos estarão presentes."

1008602-52 = "É um incômodo e não faz sentido."

1008602-53 = "...... ainda, como a Gehenna é a organizadora, tenho que mostrar meu rosto como presidente do comitê de moral pública."

1008602-54 = "Não tenho escolha, estou dentro."

1008602-55 = "...... É uma verdadeira dor de cabeça."

1008602-59 = "...... Como isso aconteceu?"

1008602-60 = "[s] (sinceramente incômodo ......)"

1008602-61 = "Então, isso ...... Tenho vergonha de dizer isso, mas ......"

1008602-62 = "Não estou acostumado com esse tipo de lugar. ......"

1008602-63 = "Eu precisava me preparar rapidamente, mas não sabia por onde começar."

1008602-64 = "Entrei no site ...... hoje para pedir conselhos porque achei que meu professor poderia me ajudar."

1008602-65 = "Sou membro do comitê de moral pública, mas sei que não é bom estar sempre contando com os professores."

1008602-66 = "Mas ......"

1008602-67 = "[\"Não, estou muito feliz por você estar confiando em mim. \""

1008602-68 = "O quê, realmente ......?"

1008602-69 = "[s]\"É claro. Se você vai participar de uma festa, deve começar com ......\.""

1008602-71 = "[ns] \"Hina, você tem um vestido? \""

1008602-72 = "Vestido ......?"

1008602-73 = "[s7] \"É importante vestir-se adequadamente para o TPO. \"\n[s8] \"Talvez seja óbvio demais, mas não é óbvio demais. ......\""

1008602-76 = "Não, o médico está certo."

1008602-77 = "Sim, é verdade, ......, é claro, se você me perguntar."

1008602-78 = "É uma festa, e se eu fosse com meu uniforme habitual, pareceria deslocado."

1008602-79 = "Preciso preparar meu vestido."

1008602-80 = "Além do vestido, ...... acessórios e calçados também estão disponíveis juntos ......"

1008602-81 = "Obrigado, doutor. Graças ao #n, sei por onde começar a me preparar."

1008602-82 = "[\"Fico feliz por ter ajudado. \""

1008602-84 = "[ns] \"Então, vamos comprar um vestido juntos ......\.""

1008602-85 = "Não, você não precisa comprar um vestido. Não, você não precisa comprar um vestido."

1008602-87 = "[ns] \"...... onde estamos? \""

1008602-88 = "É o armazém que costumo usar."

1008602-89 = "Mantenho aqui coisas que não uso com muita frequência."

1008602-90 = "O vestido que usei antes provavelmente também está por aqui."

1008602-91 = "[s]\"hmmm, como um déjà vu ......\""

1008602-92 = "Onde posso encontrá-lo? ...... Espere um pouco."

1008602-96 = "Bem, eu me lembro de tê-lo colocado em uma caixa por aqui: ......"

1008602-97 = "...... hmm?"

1008602-101 = "[ns] \"Found? \""

1008602-105 = ".................. Ah."

1008602-106 = "[s]\"............ gosta de fantasias de balé? \""

1008602-107 = "Não, não é! Professor! É ......!"

1008602-113 = "...... Phew. Sim, você veio à procura de um vestido."

1008602-114 = "[s]\"Hina, esse traje de balé é ......\.""

1008602-115 = "Então, vamos procurar um vestido, certo?"

1008602-116 = "[\"Sim, sim. \""

1008602-120 = "Hmmm, parece que também não está aqui. Onde diabos está o ......"

1008602-124 = "Desta vez: ......"

1008602-125 = "Ah."

1008602-129 = "[ns] \"Have you found it? \""

1008602-132 = "[ns] \"Você está com roupas de ginástica. ......\""

1008602-133 = "Não sabia que estava aqui. Fiquei imaginando onde você a teria perdido."

1008602-134 = "[s] \"......................... \""

1008602-142 = "Professor ......! O que você acabou de tentar fazer?"

1008602-143 = "[\"Nah, nada! \""

1008602-144 = "Ou, para chegar mais perto do rosto: ......"

1008602-145 = "...... Não, não é nada."

1008602-146 = "Talvez eu tenha me preocupado demais."

1008602-147 = "[s9] \"Desculpe! \"\n[s10] \"...... Provavelmente é apenas minha imaginação. \"\"\n[s10] \""

1008602-148 = "Ei, ei!"

1008602-149 = "...... Huh. Todo cuidado é pouco."

1008602-150 = "Umm, sim. ...... Certo."

1008602-151 = "Fu ...... e eu tenho que encontrar um vestido de qualquer maneira."

1008602-152 = "Ok, então, aquele ali é o próximo: ......"

1008602-154 = "(Depois continuou a procurar no armazém e finalmente encontrou o vestido)"

1008602-156 = "Eu a encontrei, doutor."

1008602-157 = "É o vestido que eu costumava usar."

1008602-162 = "Que bom que você encontrou. #Agora parece que não precisarei desperdiçar meu dinheiro."

1008602-163 = "[s]\"Hmmm, garotas. Não é assim que parece ......\.""

1008602-164 = "Espere aqui um pouco, eu vou me trocar."

1008602-165 = "Quero que o médico veja se é adequado para mim."

1008602-166 = "[s]\"Isso é bom, mas talvez ......\""

1008602-167 = "Eu já volto."

1008602-171 = "Vejamos como: ......"

1008602-172 = "...... Huh?"

1008602-173 = "Não entre. ......"

1008602-177 = "...... Ah."

1008602-178 = "["Hina! Você está bem? Ouvi algo estranho. ......! \""

1008602-179 = "Está tudo bem, está tudo bem! Não é nada. ......"

1008602-180 = "Apenas um pequeno ...... rasgado quando tentei me forçar a usá-lo!"

1008602-181 = "[s]\"Isso não é um grande problema! Reme imediatamente ......\""

1008602-182 = "E, de qualquer forma, doutor ...... não venha até aqui agora!"

1008602-183 = "Realmente, não. ......!"

1008602-184 = "[s] \"...... Sim. \""

1008602-188 = "...... Ha. Bem, no fim das contas, tudo deu errado."

1008602-189 = "Achei que dessa vez também não haveria problema."

1008602-190 = "...... Acho que eu também havia crescido um pouco."

1008602-191 = "[s]\"......Quando foi a última vez que você usou esse vestido? \""

1008602-192 = "Hmm ......? Provavelmente porque a última vez que o usei foi em uma festa de Natal da escola primária: ......"

1008602-193 = "...... quando eu estava na segunda série do ensino fundamental?"

1008602-194 = "[\"Quão mais impossível pode ser! \""

1008602-195 = "Então, ......?"

1008602-196 = "Crescer também é preocupante. ......"

1008602-197 = "Acabei de encontrá-lo. ......"

1008602-198 = "[\"Hina, vamos comprar um vestido juntos. \""

1008602-199 = "...... professor e o vestido?"

1008602-200 = "Hmmm, eu me pergunto se isso seria melhor. Seria difícil preparar o #n sozinho. ......"

1008602-201 = "É por isso que o médico veio até aqui."

1008602-202 = "...... Professor. Posso pedir-lhe que faça algo para mim que possa me causar problemas novamente?"

1008602-203 = "["É claro! Eu cuidarei disso! \""

1008602-204 = "...... Sim, obrigado."

1008602-205 = "Está bem, prometo."

