[translation]
1008005-1 = "Atenção"

1008005-2 = "Enquanto caminhava pela zona comercial...)"

1008005-8 = "...Hmph."

1008005-14 = "[ns1] \"Shokuhou?\"\n[ns2] \"Você tem alguma preocupação...?\""

1008005-17 = "Fiquei curioso, ou melhor..."

1008005-18 = "Não importa onde você esteja no mundo, as meninas tendem a formar grupos."

1008005-19 = "Antes de vir para cá, eu também era o centro do grupo."

1008005-20 = "Agora que a situação mudou, você acha que pode observar as coisas objetivamente?"

1008005-21 = "Talvez fosse assim que eu parecia quando os outros me viam."

1008005-22 = "Não quero dizer isso de uma maneira ruim. #nNa verdade, não é natural fazer amigos?"

1008005-23 = "...Você tinha muitos amigos?"

1008005-27 = "……deixe-me ver."

1008005-28 = "Eu não diria que foram muitos."

1008005-32 = "Claro, havia pessoas importantes, certo? #nMas, para mim, habilidades são habilidades, então é difícil para mim me sentir assim."

1008005-33 = "Só para deixar claro, só porque você estava usando suas habilidades não significa que era um relacionamento unilateral, certo?"

1008005-34 = "...Seu professor não pensa assim? ……sim."

1008005-35 = "Hehe... é verdade ou é apenas conversa fiada?"

1008005-36 = "Bem, ok. É algo que não pode ser perseguido de outra forma."

1008005-37 = "……o que?"

1008005-38 = "そんな目でみなくても、別にここで使うつもりはないゾ☆"
1008005-39 = "……[ruby=メンタルアウト]心理掌握[/ruby]は、友達を作るためのものじゃないしぃ？"
1008005-40 = "というか……使おうとしても先生が止めるでしょ？"
1008005-41 = "Não consigo me concentrar agora e sinto que minhas habilidades estão enfraquecendo..."

1008005-42 = "Bem, se você quiser, você pode usá-lo."

1008005-46 = "……あら、動揺しないのね？"
1008005-47 = "[s3] \"Não acho que você fará mau uso dele.\"\n[s4] \"Se você quisesse, você o teria usado em primeiro lugar.\""

1008005-50 = "...Isso mesmo. #nSe eu fizesse um movimento, a primeira coisa que faria seria “verificar” o professor."

1008005-51 = "Mas acho que isso não é necessário..."

1008005-52 = "Sou apenas um visitante aqui, um estranho, certo? #nNão quero assumir responsabilidades ou interferir."

1008005-53 = "...E não é exatamente divertido de operar."

1008005-54 = "Se você não precisa fazer isso, é melhor."

1008005-55 = "Isso mesmo... Então, surpreendentemente, estou aproveitando meu tempo agora."

1008005-56 = "...Se existisse um mundo onde não existissem habilidades, me pergunto se seria assim que eu viveria minha vida."

1008005-57 = "Bem, eu estava pensando em algo que nem estava no padrão☆"

1008005-58 = "...Oh?"

1008005-64 = "Qual é o alvoroço?"

1008005-65 = "Oh, você... estou com problemas. Isto é por ordem de chegada..."

1008005-66 = "Tudo bem, apenas um."

1008005-67 = "Não é ruim para a imagem da loja atrair muitos curiosos? #nEu não me importo nem um pouco. Ver?"

1008005-68 = "Bem, mesmo que você diga... já está decidido..."

1008005-69 = "Está frio, não é função do balconista fazer algo a respeito?"

1008005-73 = "[ns5] \"...Você parece estar com problemas.\"\n[ns6] \"Eu irei ajudá-lo.\""

1008005-76 = "......Suspiro, meu precioso tempo foi desperdiçado."

1008005-81 = "[ns7] \"...Huh?\"\n[ns8] \"O som agora...\""

1008005-84 = "...!"

1008005-85 = "Por favor, siga as regras e faça fila lá!"

1008005-86 = "...Uau, eu entendo! Você não precisa gritar assim...!"

1008005-87 = "Se você fizer algo assim da próxima vez, ligarei para o responsável! !"

1008005-88 = "Tsk, tanto..."

1008005-89 = "[ns] \"…………?\""

1008005-91 = "[ns] \"...Shokuhoku?\""

1008005-94 = "― [log=쇼쿠호]...[wa:300]O quê? [/registro]"

1008005-96 = "[wa:500]― [log=쇼쿠호]どうかしたのかしらぁ。[/log]"
1008005-99 = "[wa:700]― [log=쇼쿠호]いずれにせよ、[wa:870] [/log]"
1008005-100 = "- [log=쇼쿠호]Acho que isso iria acontecer algum dia [wa:1120]? [/registro]"

1008005-103 = "― [log=쇼쿠호]Não é mesmo? [/registro]"

1008005-106 = "― [log=쇼쿠호]……[wa:500]Controle remoto? [wa:1100] [/log]"

1008005-107 = "― [log=쇼쿠호]...[wa:500]Você gostaria de ouvir isso [wa:750]? [/registro]"

1008005-110 = "[wa:400]― [log=쇼쿠호]ちょっと[wa:230]気配り力が足りないかもぉ？[/log]"
1008005-113 = "[wa:1090]― [log=쇼쿠호]女の子が[wa:620]話そうとしていないならぁ……[/log]"
1008005-115 = "[wa:450]― [log=쇼쿠호]無理に[wa:290]聞こうとしちゃ[wa:540]ダメだゾ☆[/log]"
1008005-118 = "[wa:500]― [log=쇼쿠호]いい？[wa:1140]あなたは[wa:360]何も見ていないし、[wa:1640] [/log]"
1008005-119 = "― [log=쇼쿠호]Em primeiro lugar, [wa:1130] nada estava acontecendo. [/registro]"

1008005-122 = "- [log=쇼쿠호]...[wa:400]Não é mesmo, [wa:1190]Sensei? [/registro]"

1008005-126 = "(...Na frente de Shokuhou, que não perguntou nada, tudo que pude fazer foi acenar com a cabeça.)"

