[translation]
1009205-1 = "Toque para você."

1009205-4 = "(Eles foram para o ponto de encontro no horário combinado)."

1009205-10 = "(A sala estava vazia, sem luzes acesas)."

1009205-14 = "[ns1] \" \"창 "창 "창 "창" Ainda não há Yoshimi, ......? \"\n[ns2] Acenda as luzes."

1009205-22 = "...... phew."

1009205-23 = "Eu estava esperando por você, doutor."

1009205-27 = "[ns3] \"......Yoshimi? \"\n[ns4] \"Que situação é essa ......? \"\"\n[ns4] \n[ns5] \"?"

1009205-30 = "Bem, em poucas palavras, vou jogar agora."

1009205-31 = "Pratiquei até a morte, mas ...... ainda fico nervoso quando se trata disso."

1009205-35 = "É a primeira vez que escuto alguém de verdade."

1009205-36 = "...... hmm?"

1009205-37 = "O que, explicação?"

1009205-41 = "...... Huh."

1009205-42 = "Você precisa de mais alguma palavra?"

1009205-43 = "Não importa o quanto você seja um professor, você sabe o que quero dizer."

1009205-44 = "Pensei em ouvir os resultados da minha prática de ......."

1009205-45 = "Aqui, feche a boca se estiver entendendo."

1009205-46 = "Eu estava muito nervosa. ...... para convidá-los e prepará-los."

1009205-47 = "...... Estou falando sério, não fique tirando sarro de mim."

1009205-51 = "[ns5] \"Sim, tudo bem. \"\n[ns6] Senta-se silenciosamente em uma cadeira próxima."

1009205-56 = "...... Phew."

1009205-57 = "Quando seu professor é tão sério, você fica nervoso. ......"

1009205-58 = "Em seguida, acesse ......."

1009205-59 = "...... hmm?"

1009205-60 = "Músicas?"

1009205-61 = "Além do que eu fazia na banda,"

1009205-62 = "Um praticante pessoal."

1009205-63 = "Eu escolhi... corretamente."

1009205-68 = "...... haha."

1009205-69 = "Ótimo, não peça detalhes."

1009205-70 = "Apenas cale a boca e ouça, está bem?"

1009205-79 = "Em seguida, acesse ......."

1009205-80 = "Ufa. ......."

1009205-81 = "......."

1009205-82 = "Hmmm. ......."

1009205-83 = "Hmmm. ......."

1009205-87 = "Ummm. ......!"

1009205-90 = "...... Ainda não é bom."

1009205-95 = "[ns7] \"Você já se sentou ......? \"\n[ns8] \"Você não precisa ficar tão nervoso. \""

1009205-99 = "Desculpe-me. Eu ainda vou cometer um erro, então vou me sentar e fazer como fizemos no treino."

1009205-100 = "Pode ser um pouco de postura, mas não se preocupe com ......."

1009205-101 = "Em seguida, acesse ......."

1009205-106 = "......."

1009205-112 = "(A performance de Josimi ecoa pela sala)"

1009205-113 = "(Pude ouvir diretamente o som ao vivo, sem estar conectado a um amplificador ou alto-falantes)"

1009205-114 = "(Para ver um desempenho desse tipo, consulte ......)"

1009205-118 = "(...... era muito bom nisso)"

1009205-121 = "[wa:580]- [log=요시미 밴드]Fuu......[wa:1020] Fuu....... [/log]"

1009205-124 = "- [log=요시미 밴드]...... e [wa:1030]did ....... [/log]"

1009205-126 = "- [log=요시미 밴드]Conseguimos. ....... [/log]"

1009205-129 = "[ns9] \"Foi realmente incrível. \"\n[ns10] \"Foi incrível, tocou meu coração. \"\n[ns10]""

1009205-130 = "[wa:400]- [log=요시미 밴드]Então, [wa:550]então ......? [/log]"

1009205-131 = "[wa:400]- [log=요시미 밴드]Então, [wa:550]então ......? [/log]"

1009205-133 = "- [log=요시미 밴드]A sensação de que o professor estava [wa:470]ouvindo [wa:550]também era [wa:550]so......? [/log]"

1009205-136 = "- [log=요시미 밴드]Você não está [wa:550]brincando, está? [/log]"

1009205-138 = "- [log=요시미 밴드]Isso é ......[wa:1020] realmente o que você acha? [/log]"

1009205-141 = "[wa:1350]- [log=요시미 밴드]Que ......[wa:1180] pancada ....... [/log]"

1009205-144 = "- [log=요시미 밴드]Esta é a [wa:1250]primeira vez que vejo algo assim. ....... [/log]"

1009205-147 = "[wa:650]- [log=요시미 밴드]...... Teacher ....... [/log]"

1009205-150 = "- [log=요시미 밴드]Se você pensar bem e analisar,[/log]"

1009205-152 = "- [log=요시미 밴드]Acho que mostrei o professor [wa:400]pela primeira vez. [/log]"

1009205-155 = "[wa:1160]- [log=요시미 밴드]O que posso dizer ......[wa:1630] que ....... [/log]"

1009205-158 = "- [log=요시미 밴드]...... my [wa:500] 'cool' look......[wa:1650]... ... [/log]"

1009205-162 = "......, sim! Acabou!"

1009205-163 = "As tarefas terminaram, então nos dispersamos!"

1009205-167 = "Veja, isso é o suficiente!"

1009205-168 = "Ou algo assim..."

1009205-172 = "...... O quê?"

1009205-176 = "Além disso, mais uma vez ......? Encore ......?"

1009205-177 = "Ei, do que você está falando?"

1009205-178 = "Não se trata de um show ou algo do gênero. ......"

1009205-179 = "[Ainda assim, eu queria ouvir. \"\n[s12] \"Eu gostaria de um bis pela primeira vez, você não gostaria? "

1009205-182 = "......！！！！"

1009205-183 = "Droga ...... ugh ......! De verdade!"

1009205-184 = "Você pode saber mais sobre essa boca que está diminuindo em ......!"

1009205-188 = "～～～～～～～～！！！！！！"

1009205-189 = "Huh. ...... Já chega."

1009205-193 = "...... Bom."

1009205-194 = "Se você disser isso, eu o farei."

1009205-195 = "Mas você precisa estar preparado."

1009205-196 = "Se essa for sua intenção: ......"

1009205-197 = "Professor 'firsts' --."

1009205-202 = "-Vou levar tudo comigo."

1009205-204 = "(E assim ouvi várias apresentações de Yoshimi)."

1009205-208 = "(Ele estava exausto desde o meio da corrida, talvez ficando sem energia. ......)"

