[translation]
1009605-1 = "ライフセーバーの特権"
1009605-3 = "どうして先生がこちらに……？"
1009605-4 = "[s1] \"手伝いに来たよ。\"\n[s2] \"二人でやったほうが早いと思って。\""
1009605-7 = "……。"
1009605-8 = "たしかに、ヘルプの人員が来るとは聞いていましたが。"
1009605-9 = "まさか、先生だとは思いもしませんでした。"
1009605-10 = "[s] \"これで、今日は同僚だね！"
1009605-11 = "……分かりました。"
1009605-12 = "ですが今日は作業が多いので、前のように遊ぶ時間はないかと。#nそれでも、よろしいでしょうか？"
1009605-13 = "[s] \"もちろんだよ、一緒に頑張ろう。\""
1009605-14 = "では、清掃道具を持って移動しましょう。"
1009605-15 = "屋外の施設に向かいます。"
1009605-17 = "私たちの担当は、「ヒーリングスパ」になります。"
1009605-18 = "プライベート空間でスパを楽しめる施設ですね。"
1009605-19 = "普段は行列ができるほどの人気だそうで。"
1009605-20 = "[s] \"カップルが多そうだね……。\""
1009605-21 = "そうかもしれません。"
1009605-22 = "では、私はあちらから始めるので、先生はこちらから。"
1009605-23 = "隅々まで、きれいにお願いします！"
1009605-24 = "[s3] \"は、はい！\"\n[s4] （……ごくっ）"
1009605-28 = "（しばらく熱心に清掃を行なった……）"
1009605-30 = "ふう、これで終わりですね。"
1009605-31 = "お疲れ様でした、先生。"
1009605-32 = "[s5] \"カンナもお疲れ様。\"\n[s6] \"きれいになると気持ちが良いね。\""
1009605-35 = "はい、責任者に報告をしてきます。"
1009605-39 = "こちら、ヒーリングスパ清掃担当。#n本部、応答を願います。"
1009605-40 = "何かありましたか？"
1009605-41 = "施設の清掃、及び点検を終え待機中です。#n次の指示を。"
1009605-42 = "お疲れ様でした。#n手が離せないので、次の指示が決まったら連絡を入れます。"
1009605-43 = "……切られてしまいました。"
1009605-44 = "どうやら本部は忙しいようです。#nしばらく待機を命じられました。"
1009605-45 = "[s7] \"ずっと作業してたから、疲れたね。\"\n[s8] ストレッチをして体を伸ばす。"
1009605-50 = "では、次の指示が来るまで休むとしましょうか。"
1009605-51 = "せっかくですし、「ヒーリングスパ」を利用するのはどうですか？"
1009605-52 = "[s] \"え、良いの？\""
1009605-53 = "ええ、もちろんです。"
1009605-56 = "[wa:750]― [log=칸나 수영복]ふう……[/log]"
1009605-58 = "― [log=칸나 수영복]たしかに疲労が[wa:750]取れた感じがしますね。[/log]"
1009605-61 = "[wa:750]― [log=칸나 수영복]大丈夫です。[/log]"
1009605-63 = "― [log=칸나 수영복]これも点検項目の[wa:850]一つですから。[/log]"
1009605-66 = "― [log=칸나 수영복]それに……[/log]"
1009605-68 = "― [log=칸나 수영복]働き者には[wa:800]褒賞がなければ。[/log]"
1009605-71 = "[wa:750]― [log=칸나 수영복]……あと、[/log]"
1009605-73 = "― [log=칸나 수영복]先生にはいつも[wa:1350]お世話になっていますから。[/log]"
1009605-76 = "― [log=칸나 수영복]だから[wa:400]これは……[/log]"
1009605-78 = "― [log=칸나 수영복]私から先生に送る[wa:1750]小さなプレゼントです。[/log]"
1009605-81 = "[ns9] \"つまり……。\"\n[ns10] \"「カンナとスパを楽しむ時間」がプレゼントってこと？\""
1009605-82 = "[wa:500]― [log=칸나 수영복]えっ！？[/log]"
1009605-83 = "[wa:500]― [log=칸나 수영복]えっ！？[/log]"
1009605-85 = "― [log=칸나 수영복]そ、[wa:450]そんなわけ[wa:600]ないじゃないですか！[/log]"
1009605-88 = "[wa:830]― [log=칸나 수영복]私がいるのは、[wa:1300]その……[/log]"
1009605-91 = "― [log=칸나 수영복]……[wa:1150]先生の安全を[wa:800]守るためです！[/log]"
1009605-93 = "― [log=칸나 수영복]私は[wa:1000]ライフセーバーですから！[/log]"
1009605-96 = "まったく、先生は……。"
1009605-97 = "ヒーリングスパ担当者、こちらはパーク本部です。"
1009605-98 = "そろそろ作業終了時間なので、戻ってきてください。#nお疲れ様でした。"
1009605-103 = "……とのことです。#n戻りましょう、先生。"
1009605-104 = "あらためて、清掃お疲れ様でした。"
1009605-105 = "[s] \"お疲れ様、楽しかったね。\""
1009605-109 = "[ns] \"カンナはどうだった？\""
1009605-110 = "任務に楽しさを求めるのは、主義に反しますが……。"
1009605-111 = "それでも、あえて言うのなら……。"
1009605-113 = "……私も楽しかったです、先生。"
