[translation]
1010702-1 = "Escriba da Casa Universal dos Demônios"

1010702-3 = "Olá! #n 'Manmaden Weekly'!"

1010702-4 = "[\"A porta está aberta, você pode entrar. \""

1010702-9 = "Olá~!"

1010702-10 = "Ah, talvez você estivesse no meio do processo?"

1010702-11 = "[\"Não, eu só estava entediado. \""

1010702-12 = "Estou vendo! Agora, se você me der licença~."

1010702-16 = "Ah, não, as placas de Petri são boas! Confortáveis! O Dr. #n sempre trabalha aqui?"

1010702-17 = "Talvez seja por causa do bom ar, mas a pele do professor também está brilhando!"

1010702-18 = "[A pele está como sempre? \""

1010702-19 = "Bem, bem, vamos deixar os detalhes de fora!"

1010702-20 = "Agora, um presente para os professores! É hora do show!"

1010702-21 = "Muito bem! A última edição da Manmaden Weekly!"

1010702-22 = "É a primeira vez que você vê o site ......?"

1010702-23 = "É isso mesmo? ......"

1010702-24 = "Você ainda não viu o imensamente popular e confiável semanário [ruby=Panma] Manmaden[/ruby] in Gehenna em ......#n? ......!"

1010702-25 = "Esse ...... não é muito ......."

1010702-26 = "[s]\"Cheaki? \""

1010702-27 = "É o melhor dos melhores!"

1010702-28 = "Não acredito que vou ver o momento de ler o Weekly Manmaden pela primeira vez com meus próprios olhos!"

1010702-29 = "Fico feliz em observar as reações brutas do professor bem ao meu lado. ...... É emocionante!"

1010702-30 = "Dê uma olhada por si mesmo! -- "Recurso especial! Uma visita ao lounge de Manmadono", #n "Exclusivo! O registro de Ibuki brincando na areia", etc! Esta semana também está repleta de informações!"

1010702-31 = "Esperamos que você goste!"

1010702-32 = "["Oh, sim. Obrigado. \""

1010702-33 = "Se quiser, posso ler para você."

1010702-34 = "Um serviço especial que você pode ler comigo, [ruby=Motomiya]Motomiya[/ruby] Chiaki, a secretária, repórter, editora-chefe e editora do Weekly Manmaden!"

1010702-35 = "O que você acha? Você faria isso?"

1010702-36 = "[s1] \"Não se preocupe, eu o lerei sozinho. \"\n[s2] \"Bem, vou perguntar a ele. \"\n[s2]""

1010702-37 = "Ah, é mesmo? De verdade?"

1010702-38 = "Esse é um serviço muito raro, sabe? Se você perder essa oportunidade, poderá se arrepender, sabe?"

1010702-42 = "O quê? Uma piada, hein?"

1010702-43 = "Haha! É isso que você quer dizer? Os professores são engraçados, não são?"

1010702-44 = "Boa escolha~!"

1010702-45 = "Então deixe isso conosco!"

1010702-46 = "Primeiro, vamos começar com a primeira página! Este [ruby=Pandemonium Society]é[/ruby] o escritório do administrador[/ruby] da Manmaden!"

1010702-47 = "É onde eu e outros conselheiros visitamos todos os dias. Geralmente estou aqui quando não tenho aulas!"

1010702-48 = "Os sofás aqui são tão macios e confortáveis! Você também pode se deitar nele mais tarde, professor!"

1010702-49 = "É o Salão Oval, mas o trabalho é, não é?"

1010702-50 = "Bem, bem, eu sou o secretário e, quando estou em uma reunião, estou devidamente ......"

1010702-51 = "Pensando bem, parece que não tenho reuniões com muita frequência. ......Quando escrevi as atas? ......Bem, não sei."

1010702-52 = "Agora, próxima página!"

1010702-53 = "Oh, eu me esforcei muito neste artigo! Vou ler em voz alta!"

1010702-55 = "(Depois disso, ele e Thiaki também leram o Manmaden Weekly: ......)"

1010702-57 = "Ah, já é a última página."

1010702-58 = "Bem, tudo aconteceu muito rapidamente."

1010702-59 = "O que o senhor acha, doutor? Como você se sente ao lê-lo pela primeira vez?"

1010702-60 = "[\"Sim, foi interessante. \""

1010702-61 = "Hehe, eu sabia que você tinha um olho para isso!"

1010702-62 = "Agora, então, aqui está o problema principal!"

1010702-63 = "Assinatura, como você gostaria?"

1010702-64 = "Você receberá um novo Manmaden semanal com conteúdo novo toda semana!"

1010702-65 = "Agora ele também vem com um presente de luxo!"

1010702-66 = "[Bom. Devo fazer a assinatura? \""

1010702-67 = "Ah, é mesmo?"

1010702-68 = "Muito bem! Muito obrigado! Talvez eu seja o primeiro assinante fora da Gehenna!"

1010702-69 = "[s]\"Qual é o valor da taxa de assinatura? \""

1010702-70 = "Ah, e é gratuito."

1010702-71 = "Não faço isso para ganhar dinheiro. É meio que um hobby!"

1010702-72 = "Todos os custos de impressão e publicação e outras despesas gerais são cobertos pelo orçamento da Manmaden!"

1010702-73 = "[s]\"...... Está tudo bem, não está? \""

1010702-74 = "Makoto-senpai também diz que não faz objeção à divulgação do nome Manma-dono. ......"

1010702-75 = "Bem, isso é bom, não é?"

1010702-76 = "[s] (Tem certeza? ......)"

1010702-80 = "Então! Por favor, assine aqui!"

1010702-81 = "É isso mesmo? Uma lista de assinantes!"

1010702-85 = "Sim, tenho uma pergunta sobre o "Não tenho certeza se isso é uma boa ideia"! Obrigado!"

1010702-86 = "Eu não tinha ideia de que eles estariam tão dispostos a se inscrever no ...... shire com tanta disposição, valeu a pena a viagem!"

1010702-87 = "[\"Você sempre faz propagandas assim? \""

1010702-88 = "Faço muitas conversas sobre pêssegos ou vendas por telefone. ...... Quando tenho tempo, eu os visito assim."

1010702-89 = "Gosto de conversar com novos alunos e de ver o número de leitores crescer com meus próprios olhos!"

1010702-90 = "Ele pode ser encontrado em ......"

1010702-91 = "'Entrevista! Conheci essa pessoa!" Eu tento conhecer pessoas o máximo possível, pois isso me ajuda a encontrar material para a seção!"

1010702-92 = "...... Mas eu gostaria de entrevistar um professor um dia - tenho certeza de que adoraria!"

1010702-93 = "[\"Sempre que não tiver um emprego, você ficará bem. \""

1010702-94 = "Tem certeza? Obrigado!"

1010702-95 = "Como agradecimento, enviarei a você dois exemplares da próxima edição da Weekly Manmaden!"

1010702-96 = "Se você gostar, eu adoraria ver outros alunos - entre em contato comigo!"

