[translation]
1011902-1 = "百花繚乱式射撃術"
1011902-2 = "百花繚乱紛争調停委員会・部室"
1011902-3 = "（他の用事が早く片付いて、約束の時間よりも前に百花繚乱の部室に到着できた）"
1011902-6 = "（中庭で訓練中のナグサを見つけた）"
1011902-13 = "はっ……はぁっ！"
1011902-17 = "……先生？"
1011902-18 = "もう約束の時間……？"
1011902-19 = "ごめんなさい、訓練に集中しすぎて――"
1011902-20 = "[s1] \"いや、まだ時間じゃないよ。\"\n[s2] \"私が早く着いただけ。\""
1011902-23 = "そっか。"
1011902-24 = "でも、訓練を見られるのは……ちょっと恥ずかしいな。"
1011902-25 = "少し待っててくれる？#n汗だけ拭いてくるから。"
1011902-26 = "[s3] \"私のことは気にしないでいいよ。\"\n[s4] \"まだ時間はあるんだし、続けて続けて。\""
1011902-29 = "でも……。"
1011902-30 = "[s] \"噂の「百花繚乱式射撃術」を見てみたかったんだ。\""
1011902-31 = "興味あるの？"
1011902-32 = "……そんな大したものじゃないよ。"
1011902-33 = "訓練だし。撃って、的を交換して、の繰り返しだから。#n見ててもつまらないかも。"
1011902-34 = "……それに、私はこれまでの委員長ほど才能があるわけでもない。"
1011902-35 = "先生の期待に応えられるかは分からないけど。"
1011902-36 = "[s] \"ナグサの「百花繚乱式射撃術」が見てみたいんだ。\""
1011902-40 = "[ns5] \"たとえ自信がなくても、諦めず努力する背中には――\"\n[ns6] \"何者にも負けない想いがこもってるからね。\""
1011902-43 = "そう……なのかな。"
1011902-44 = "先生が見たいなら、やるけど――"
1011902-45 = "危ないから、絶対にその場所を動かないで。"
1011902-46 = "[s] \"どうして……？\""
1011902-47 = "「百花繚乱式射撃術」は全方向に対応できるから。#n前提として、安全な場所がないんだよ。"
1011902-48 = "私たちは、一人で複数を相手にすることも多い。#nそういう戦いだと、ほんのわずかな死角が命取りになる。"
1011902-49 = "それを補うために培われてきたのが「百花繚乱式射撃術」なの。"
1011902-50 = "結果として、回避と同時に複数の敵を狙い撃ちする形に発展してきた。"
1011902-51 = "……これが「百花繚乱式射撃術」の基本。"
1011902-52 = "だから、後ろにも敵がいると思って対応してる。"
1011902-53 = "[s7] \"考え方はカンフーに近いのかも……？\"\n[s8] \"なんか奥深い……。\""
1011902-54 = "カンフーを教えてくれる人が山海経にいるんだっけ。機会があったら習ってみたいな。"
1011902-56 = "話を戻すね。まずは前と後、右と左の的を順番に撃っていくよ。"
1011902-57 = "いつもよりゆっくりやるから。"
1011902-58 = "さっきも言ったけど、絶対に動かないで。"
1011902-60 = "ふぅ……。"
1011902-64 = "……はぁっ！"
1011902-73 = "……どうだった？"
1011902-74 = "[s9] \"……？\"\n[s10] \"今、何が起きたの……？\""
1011902-77 = "的を順番に撃っただけ。"
1011902-78 = "[s11] \"何が何だか……。\"\n[s12] \"的が一瞬で破壊されたように見えたけど……。\""
1011902-81 = "そんなに難しいことはしてない。#n一個ずつ説明しようか。"
1011902-82 = "まず、体を左に回しながら右を撃って一つ。#n続いて脇の下に銃を構えて、左を撃って二つ。"
1011902-83 = "流れで銃そのものを相手に投げて、三つ目を落とす。#nその反動で空中にある銃を持ち直して、最後の的を撃てば、四つ。"
1011902-84 = "これで、四方向から来る敵を同時に制圧できる。"
1011902-85 = "もちろんこれは訓練だから、実践に比べれば簡単な動きだったけど。"
1011902-86 = "[s] \"簡単……？\""
1011902-87 = "今のは基本的な形。"
1011902-88 = "これくらいはできて当然。"
1011902-89 = "……まだ時間はあるし、他にもいくつかやってあげる。"
1011902-91 = "（その後もナグサの訓練を見届けたけれど――）"
1011902-92 = "（一つとして「簡単」そうには見えなかった）"
