[translation]
1012402-1 = "O mar não vai esperar"

1012402-2 = "...É por isso."

1012402-7 = "(Não há espaços em branco na planilha de horários que Hasumi trouxe. #n Os horários foram escritos em todos os dias.)"

1012402-8 = "[ns1] \"Todo mundo está tão ocupado assim?\"\n[ns2] \"Acho que é um pouco difícil demais...\""

1012402-11 = "Não, não estou tão ocupado."

1012402-12 = "Afinal, este é o plano de todo o comitê. #nO responsável é diferente para cada horário."

1012402-13 = "(Quando olhei para trás, o nome da pessoa responsável estava listado para cada programação.)"

1012402-14 = "Além disso, fora do horário de trabalho, você pode passar seu tempo livremente."

1012402-15 = "Como disse a professora, o mar é um lugar precioso."

1012402-16 = "Este é um pequeno presente para todos vocês que estão sempre trabalhando duro."

1012402-17 = "[s3] \"Mas Hasumi...\"\n[s4] \"Todos os planos têm nomes...?\""

1012402-20 = "Claro. Eu sou o vice-presidente."

1012402-21 = "Porém, a maior parte do trabalho é cerimonial, por isso não vale a pena fazer muito barulho."

1012402-22 = "Não é mais fácil do que o normal porque você está livre de patrulhas e trabalhos administrativos?"

1012402-23 = "……o que está errado?"

1012402-24 = "Devo gastar meu tempo também?"

1012402-25 = "Hehe... Obrigado pela sua preocupação. #nMas isso é suficiente para mim."

1012402-26 = "[s5] \"Por que você não traz um maiô por precaução?\"\n[s6] \"Pode haver lacunas na sua agenda...\""

1012402-29 = "……professor."

1012402-30 = "[s7] \"Além disso, você vai trabalhar na praia, certo?\"\n[s8] \"E se seu uniforme molhar...!\""

1012402-33 = "Suspirar..."

1012402-34 = "Você quer mesmo que eu curta a praia de maiô?"

1012402-35 = "[s9] \"...Você descobriu?\"\n[s10] (Minha mente... está sendo lida...!)"

1012402-38 = "Quando os alunos se envolvem... isso transparece no rosto do professor."

1012402-43 = "Ah, não me entenda mal. Não é que eu não goste. #nNa verdade, me sinto feliz."

1012402-44 = "Recentemente percebi que não sou muito bom em autocontrole."

1012402-45 = "[s] (eu estava ciente disso...)"

1012402-46 = "Além disso, acho que a opinião do professor de que “é um problema se o uniforme molhar” tem razão."

1012402-47 = "Entendido."

1012402-48 = "[s] \"Isso significa...!\""

1012402-51 = "Sim. Não posso me dar ao luxo de desrespeitar a gentileza do meu professor."

1012402-52 = "Não há problema mesmo se você vier trabalhar com uma roupa um pouco diferente da habitual."

1012402-53 = "No entanto, não tenho intenção de mudar meus planos."

1012402-54 = "Se eu sair, alguém terá que tomar o meu lugar..."

1012402-55 = "Quero evitar colocar um fardo sobre os outros."

1012402-56 = "[s11] \"Eu respeito a decisão de Hasumi sobre isso.\"\n[s12] \"A propósito, você tem maiô?\""

1012402-59 = "Pensando bem... o tamanho não cabe mais..."

1012402-60 = "Não, meu peso não mudou muito! ?"

1012402-61 = "Porém, eu diria que cresci um pouco no último ano..."

1012402-62 = "[s13] \"Está tudo bem, compre um novo.\"\n[s14] \"Ok, vamos comprar um maiô agora!\""

1012402-65 = "Rejeitar."

1012402-66 = "[s] \"Ah, você tem algum plano para a tarde? Pois bem, amanhã...\""

1012402-67 = "Rejeitado."

1012402-68 = "[s] \"H-Hasumi...?\""

1012402-69 = "Uma semana...."

1012402-73 = "...Por favor, me dê uma semana de graça! #nVou deixar perfeito!"

1012402-74 = "[s15] \"V-Você está tão entusiasmado...!\"\n[s16] \"Não é certo ir às compras com uma mentalidade casual...?\""

1012402-77 = "Não há nada melhor do que se preparar...!"

1012402-78 = "Vejo você na próxima semana."

1012402-79 = "Por favor, desculpe-me por isso."

1012402-84 = "(Hasumi saiu, parecendo ter se decidido...)"

