[translation]
1012606-1 = "それは……私じゃないよ"
1012606-4 = "（ひとまず、今日の仕事のためにオフィスを出発した）"
1012606-5 = "ニャーオ……ンニャーオォ……。"
1012606-6 = "ガァー！ガァー！"
1012606-7 = "[ns] \"……黒猫とカラス？\""
1012606-13 = "[ns] \"……！？\""
1012606-14 = "イ……ヒ……ヒッ……。"
1012606-15 = "[ns1] （……いつにも増してオーラが！）\n[ns2] （言われた通り無視しないと……！）"
1012606-21 = "ニャーオ！ンニャーオォ！"
1012606-25 = "……。"
1012606-26 = "[ns] \"なっ……！？\""
1012606-30 = "ガァー！ガァー！"
1012606-33 = "……。"
1012606-34 = "[ns] \"ここにも！？\""
1012606-38 = "……。"
1012606-39 = "[ns] \"どうして！？\""
1012606-41 = "（……どこに行っても、視界にカノエがいる）"
1012606-45 = "（仕事は予定通り片づいたものの……）"
1012606-60 = "（ずっと、行く先々にカノエがいた……）"
1012606-63 = "[ns] \"はぁ、はぁ……。\""
1012606-64 = "あ、いらしたのですね、先生。#n今日のご予定は伺っております。"
1012606-65 = "随分と息を切らしていますが、そんなに急がれなくとも……。"
1012606-66 = "[s] \"そ、それが……。\""
1012606-68 = "（これまでの出来事を説明する）"
1012606-70 = "カノエ……？[ruby=いたがき]板垣[/ruby]カノエのことですか？#n存在そのものがオカルトだという、あの？"
1012606-71 = "[s] \"それは、どういう……？\""
1012606-72 = "あの子、いつも黒猫やカラスと一緒なんでしょう？"
1012606-73 = "全然知らない子だと本人は言ってるみたいですが……#nどう考えてもおかしいじゃないですか。"
1012606-74 = "（……たしかに、猫やカラスたちはカノエの言うことをよく聞いていた）"
1012606-75 = "手は冷たいし、肌も青白くて……。"
1012606-76 = "しかも異常なほどたくさんの声色を持っていて、#n「どれが本当の声か分からない」と噂されているんですよ。"
1012606-78 = "（カノエに何度かイタズラをされているので、否定しづらい……）"
1012606-80 = "もしかするとあの子……幽霊なのかもしれません。"
1012606-81 = "今もどこかで私たちを見ていたりして……！"
1012606-82 = "[ns] \"……！\""
1012606-89 = "（びっくりして周りを見渡すが、カノエの姿は見当たらなかった）"
1012606-90 = "……なんて。#nこうは言ったものの、うちの学院は変わり者が多いですから。"
1012606-91 = "ただのイタズラかもしれませんし、あまりお気になさらないでください。"
1012606-92 = "私たちも適当に対応していますから。"
1012606-93 = "[s] \"そ、そうだよね？はは……。\""
1012606-95 = "（急いで仕事を終わらせて、オフィスに帰ってきた）"
1012606-96 = "（翌日……）"
1012606-99 = "（カノエからだ）"
1012606-100 = "（たしか、安全になったら連絡するって……）"
1012606-105 = "先生……昨日は無事だった……？"
1012606-106 = "もう大丈夫だから、いつも通りにしていいよ……。"
1012606-107 = "[s3] \"昨日のあれは何だったの？\"\n[s4] \"どこに行ってもカノエがいたんだけど……。\""
1012606-110 = "まずは謝らせて……。"
1012606-111 = "昨日のことは、全部私がミスしたせい。ごめんね。"
1012606-112 = "完璧な儀式のはずだったのに、失敗するなんて……。"
1012606-113 = "[s] \"ぎ、儀式……？\""
1012606-114 = "悪霊召喚の儀だよ。"
1012606-115 = "でも、失敗して……#nその代償に私と瓜二つの存在を[ruby=よ]喚[/ruby]び出してしまった。"
1012606-116 = "性格も同じだったから……すぐに先生を求めて動きだしたんだ。"
1012606-117 = "[s] \"じゃあ、昨日私が見てたカノエは……？\""
1012606-118 = "そう。全部、私そっくりの悪霊だよ。"
1012606-119 = "でも心配しないでねぇ。今は「元いたところ」へ帰してやったから……。"
1012606-120 = "[s5] \"本当に悪霊だったの？\"\n[s6] \"カノエ本人じゃなくて……？\""
1012606-123 = "うん……。仕事で忙しい先生を遠くから眺めていたかったとか――"
1012606-124 = "苦労して手に入れた外出許可を有意義に使おうとか……#n悩んでたわけでもないからねぇ……。"
1012606-125 = "[s] \"絶対カノエ本人でしょ！？\""
1012606-126 = "解釈は任せるよ。#n私はちゃんと、儀式に失敗した代償って説明したからねぇ……？"
1012606-127 = "イヒヒ……。"
1012606-132 = "（……昨日見たカノエの正体は何だったのか）"
1012606-133 = "（結局、この日の真相は、闇の中へ溶けていった……）"
1012606-134 = "イヒッ……。"
1012606-135 = "イヒヒヒッ……！"
