[translation]
1012403-1 = "決戦の日"
1012403-2 = "D.U. 郊外のショッピングモール"
1012403-3 = "（待ち合わせ場所に指定されたのは、トリニティ自治区からかなり離れたショッピングモールだった）"
1012403-4 = "（ハスミは随分前から待機していたようだ）"
1012403-5 = "お待ちしておりました、先生。 "
1012403-6 = "[s1] \"普段と違う場所で会うと、なんだか新鮮だね。\"\n[s2] \"でも、なんで遠くのお店を選んだの？\""
1012403-7 = "ふふっ。そうですね。"
1012403-8 = "こうしてトリニティの外へ出る機会は、ほとんどありませんから。"
1012403-9 = "ええと、それは……。"
1012403-10 = "水着のサイズが流出するのは……避けたく……。"
1012403-11 = "いつもと違う土地であっても、支障はありません。"
1012403-12 = "このモールに「ベロニカ」が出店しているのを確認しておりますから。"
1012403-13 = "[s3] \"ベロニカって……。\"\n[s4] \"あ、生徒のみんながよく着てるブランドかな？\""
1012403-16 = "ええ。現代までクラフトマンシップを継承している、数少ない高級ブランドでして……。"
1012403-17 = "トリニティ総合学園との取り引きも長く、その品質は折り紙付きです。"
1012403-18 = "あっ、お電話くださったトリニティの生徒さまですね？"
1012403-24 = "お待ちしておりました。本日[ruby=わたくし]は私が[/ruby]ご案内させていただきます。"
1012403-25 = "ふふっ。よろしくお願いしますね。"
1012403-27 = "[ns5] （……「デキる人」って感じだ）\n[ns6] （ハスミ、正義実現委員会のエリートだもんね……）"
1012403-30 = "それでは先生、行きましょうか。"
1012403-32 = "ベロニカ店内"
1012403-33 = "水着をお探しでしたら、こちらへどうぞ。#nちょうど今夏の最新アイテムをご用意しておりまして。"
1012403-34 = "試着させていただいても大丈夫でしょうか？"
1012403-35 = "もちろんです。お気に召すものが見つかるまで何着でもどうぞ。"
1012403-36 = "ふふっ、ありがとうございます。"
1012403-37 = "それでは先生、後ほど。"
1012403-41 = "[ns] （……いいお店過ぎて、緊張するな）"
1012403-44 = "馬鹿な……！こ、こんなことが……！"
1012403-45 = "[s] \"ハスミ？\""
1012403-46 = "あっ、先生。す、すみませんが……店員の方は、そちらにいらっしゃいますか？"
1012403-47 = "はい、こちらに。"
1012403-48 = "ええっと……。"
1012403-49 = "こちら、もうワンサイズ上のものはありますか？"
1012403-50 = "ええ、もちろん。すぐにお持ちいたしますね！"
1012403-53 = "こちらになります！"
1012403-54 = "ありがとうございます。……今度こそ！"
1012403-59 = "そ、そんなはずは……！"
1012403-60 = "……店員さん。"
1012403-61 = "えっと……少し小さかった、でしょうか？"
1012403-62 = "大丈夫です！当店ではさらに大きなサイズも取り扱っておりますので！"
1012403-63 = "くっ……それを、お願いします！"
1012403-65 = "ええと……どこだったかな……。"
1012403-72 = "お待たせいたしました！"
1012403-73 = "……ありがとうございます。"
1012403-78 = "……。"
1012403-79 = "……？"
1012403-84 = "……店員さん。"
1012403-85 = "え、ええと……大変申し上げにくいのですが……。"
1012403-87 = "今試着されたものが、当店でご用意できる……最大のものになります。"
1012403-88 = "……。"
1012403-89 = "……。"
1012403-90 = "[ns] \"……。\""
1012403-92 = "[ns] \"ハスミ……。\""
1012403-95 = "[wa:1300]― [log=하스미 수영복]くぅ……[wa:2010]ふんっ！[wa:1390]ぬ[wa:403]ぬぬ……。[/log]"
1012403-97 = "― [log=하스미 수영복]はっ、[wa:883]入りました！[/log]"
1012403-100 = "― [log=하스미 수영복]ギリギリ、[wa:760]ですが……。[/log]"
1012403-103 = "[wa:1950]― [log=하스미 수영복]ご覧の通り！[wa:2330]何の問題も！[/log]"
1012403-105 = "― [log=하스미 수영복]ございません！[/log]"
1012403-108 = "[wa:400]― [log=하스미 수영복]もう少し体を絞れば、[/log]"
1012403-110 = "― [log=하스미 수영복]ジャストサイズになります！[/log]"
1012403-113 = "[ns] \"い、一旦落ち着こう、ハスミ！\""
1012403-114 = "[wa:1550]― [log=하스미 수영복]大丈夫です！[/log]"
1012403-116 = "― [log=하스미 수영복]水着は[wa:430]これにします！[/log]"
1012403-119 = "[wa:400]― [log=하스미 수영복]むしろ、[wa:1000]これが良いんです……！[/log]"
1012403-127 = "こちらにします……！"
1012403-128 = "[s7] \"は、ハスミ！？\"\n[s8] \"無理しなくても……！\""
1012403-131 = "いいえ！私は覚悟を決めたのです！"
1012403-132 = "サイズが合うものが見つかったのであれば、任務は達成です！ギリギリですが――"
1012403-133 = "もう少し時間があれば……さらなる完璧な仕上がりも……！"
1012403-134 = "[s9] \"（そんなに無理して……）\"\n[s10] \"（仕上げなくても……）\""
1012403-137 = "さあ、店員さん！早く会計を！"
1012403-138 = "お、お会計を承ります！"
1012403-140 = "（結局、ハスミは試着した水着をそのまま購入した）"
1012403-141 = "（会計を済ませる際も、ハスミは熱い闘志を燃やしていた……！）"
