[translation]
1013906-1 = "Crachá de Nico"
1013906-2 = "Placa de Petri/escritório"
1013906-3 = "(O dia em que Nico visitou o escritório de Petri para ficar de plantão...)"
1013906-4 = "[ns] \"...Hein?\""
1013906-7 = "O que há de errado, senhor? \r\n"
1013906-8 = "[s1] \"Minha gaveta estava cheia de caixas de grampos.\"\r\n[s2] \"Achei que tinham acabado, então pedi uma nova ontem...\""
1013906-11 = "Ah... acho que temos muito estoque."
1013906-12 = "Quantos pedidos você recebeu?"
1013906-13 = "[s3] \"Cerca de um ano...\"\r\n[s4] \"Acho que o aluno responsável pela contabilidade vai levar uma bronca...\""
1013906-16 = "Existem alguns alunos que têm medo de seus professores."
1013906-17 = "No entanto, os grampos do grampeador não são prejudiciais, então acho que não há problema em usar um pouco mais de grampos."
1013906-18 = "Mesmo na SRT Gakuen, houve momentos em que acidentalmente acabamos com estoque demais."
1013906-19 = "Quando pensei que tinha ficado sem minas terrestres antipessoal e encomendado mais, descobri que depois disso caixas de minas terrestres não lacradas foram empilhadas no armazém subterrâneo ――\r\n"
1013906-20 = "[s] \"Tudo bem!?\""
1013906-21 = "Tudo bem. É comum encontrar caixas de bombas com proprietários desconhecidos."
1013906-22 = "No entanto, é um problema se a fonte for do SRT Gakuen. \r\n"
1013906-23 = "Desde então, a SRT estabeleceu como regra sempre colocar crachás em pertences pessoais e armários."
1013906-24 = "[s] \"...Está decidido?\""
1013906-25 = "sim. Muitos dos suprimentos compartilhados têm formato semelhante, por isso é comum que outras pessoas levem consigo os itens errados."
1013906-26 = "É comum trocar as meias na lavanderia..."
1013906-27 = "Estranhamente, isso não parece acontecer com tanta frequência em outros pelotões, mas no pelotão FOX eles costumam trocar de roupa íntima... Eu me pergunto por quê. \r\n"
1013906-28 = "[s5] (provavelmente posso adivinhar o motivo...)\r\n[s6] \"Certamente, isso seria um problema.\""
1013906-31 = "Então, por que não colocar crachás também nos suprimentos da sua placa de Petri? \r\n"
1013906-32 = "Acabei de comprar um novo crachá para meus suprimentos."
1013906-33 = "Se você anotar o que vai, onde e quem é o proprietário, acho que será menos provável que você acabe com muito estoque como fez hoje."
1013906-34 = "Sim, comprei muito para o sensei. \r\n"
1013906-35 = "[s7] \"Essa é uma boa ideia.\"\r\n[s8] \"Então, que tal também organizarmos os materiais de escritório e colocarmos crachás neles?\""
1013906-38 = "sim!"
1013906-43 = "(Depois disso, Nico e eu colocamos crachás no equipamento da placa de Petri.)"
1013906-44 = "(...Enquanto colava as etiquetas de nome, consegui encontrar algo que pensei ter perdido.)"
1013906-47 = "[ns] \"...Demorou mais do que eu esperava.\""
1013906-48 = "Eu concordo."
1013906-49 = "Mas agora você pode ver rapidamente o que está onde e quem é o proprietário. \r\n"
1013906-50 = "Eu uso esta gaveta quando procuro utensílios de escrita, e todo o toner e papel de cópia da minha impressora ficam guardados na caixa ao lado da impressora..."
1013906-54 = "Huh? Ainda tenho um crachá. \r\n"
1013906-55 = "Gostaria de saber se houve algo que esqueci de colar..."
1013906-56 = "[s9] \"Você pode usá-lo em qualquer lugar que Nico quiser.\"\r\n[s10] \"Você gostaria de colocá-lo nas coisas de Nico?\""
1013906-59 = "……Concordo."
1013906-60 = "Agora, colocarei esse crachá em “meu”. \r\n"
1013906-66 = "...Sim. \r\n"
1013906-70 = "[ns] \"P-por que você de repente me deu um tapa nas costas!?\""
1013906-73 = "Hehe, nada. \r\n"
1013906-78 = "É importante escrever o nome do proprietário para não confundir o proprietário. \r\n"
