[translation]
1013105-1 = "festival do broto de feijão"

1013105-2 = "Cozinha do refeitório da 3ª escola pública"

1013105-3 = "[ns] \"Takane gosta de broto de feijão?\""

1013105-4 = "Sim. O rebento de feijão é o vegetal mais simples e pode ser usado como acompanhamento... mas é por isso que o acho tão apelativo."

1013105-5 = "É barato e você ainda obterá muitas vitaminas e fibras alimentares."

1013105-6 = "Além disso, cozinha muito rápido. #nGraças a isso, posso comê-lo apenas fritando-o levemente..."

1013105-7 = "O problema é que você se cansa disso rapidamente. #nÉ aí que sua habilidade entra em ação novamente."

1013105-8 = "[s] \"Entendo... Então o que é o "Festival do Broto de Feijão"? \""

1013105-9 = "...Esse é apenas o nome que eu dei."

1013105-10 = "Uma vez a cada duas semanas, às quartas-feiras, faço um prato de broto de feijão."

1013105-11 = "...Por favor, não me pergunte sobre meus pratos especiais."

1013105-12 = "Gostaria de aproveitar esta oportunidade para criticar hoje os “brotos de feijão”."

1013105-13 = "O broto de feijão é um ingrediente muito simples e direto."

1013105-14 = "Já falei sobre o contorno do broto de feijão antes, então vou omitir isso."

1013105-15 = "A beleza dos brotos de feijão é que eles são macios o suficiente para ficarem deliciosos mesmo depois de um rápido branqueamento."

1013105-16 = "Claro que o controle da temperatura é importante, mas se você cometer um erro, estragará a textura."

1013105-17 = "Por outro lado, se usar, é perfeito para fazer sopas ou absorver molhos."

1013105-18 = "A sopa de missô com broto de feijão, em particular, tem um aroma único e é considerada perfeita para as manhãs em que você não se sente bem."

1013105-19 = "[s] \"Você realmente critica tudo...\""

1013105-20 = "professor. Esta é apenas uma história..."

1013105-21 = "Nos dias de hoje, os críticos não conseguem sobreviver sem ter uma palavra a dizer sobre tudo!"

1013105-22 = "Afinal, a crítica é uma profissão que só tem sentido se suscitar debate. Vamos chamar isso de normal!"

1013105-27 = "...Ha, ficou um pouco quente demais. Um lugar sem graça...."

1013105-28 = "Sinto muito, senhor."

1013105-29 = "[s] \"Não se preocupe, está tudo bem.\""

1013105-30 = "Pois bem, vamos começar o “Festival do Broto de Feijão” de hoje mais uma vez!"

1013105-31 = "O que sempre faço é broto de feijão refogado e carne de porco com ostras!"

1013105-32 = "Quando você coloca carne de porco misturada com temperos em brotos de feijão levemente cozidos e frita junto..."

1013105-33 = "A umidade liberada pelos brotos de feijão transfere o sabor para a carne de porco e, inversamente, a gordura e o molho da carne de porco penetram nos brotos de feijão."

1013105-34 = "No inverno vermelho, onde os dias frios continuam, este é um excelente prato que pode facilmente fornecer-lhe vitaminas, fibras alimentares e energia!"

1013105-35 = "[s] \"Oh, estou começando a ansiar por isso.\""

1013105-36 = "Pois bem, por favor, espere um pouco!"

1013105-40 = "Está feito, senhor!"

1013105-41 = "Você pode apreciá-lo com arroz ou como acompanhamento."

1013105-42 = "Ou você prefere pão? Também é delicioso como sanduíche instantâneo. Fica ainda melhor com pão de centeio."

1013105-46 = "[ns1] \"Está uma delícia! Eu como!\"\n[ns2] \"É meio reconfortante...o sabor é suave...\"\n[ns3] \"Comida caseira feita por um estudante...\""

1013105-50 = "foto? Bem... sou apenas um estudante comum da Red Winter."

1013105-51 = "Mais do que isso, há muitas recargas. #nFique à vontade para aproveitar o quanto quiser!"

1013105-53 = "(Assim, sentei-me com Takane em uma mesa que aqueceu meu coração.)"

