[translation]
1013706-1 = "companheiro"
1013706-2 = "(Peguei um ônibus e vim para o interior para conhecer Konoka.)"
1013706-4 = "Sensei, aqui!"
1013706-5 = "Obrigado pelo seu trabalho duro. #nEu realmente preciso de um amigo..."
1013706-6 = "No entanto, havia uma sessão regular de treinamento na Valkyrie e ninguém estava disposto a vir comigo."
1013706-7 = "[s] \"O que devo fazer?\""
1013706-8 = "Investigação de entrevista!"
1013706-9 = "Há um suspeito em fuga e parece que entrou num autocarro que vinha para cá."
1013706-10 = "Como ele é um estranho, provavelmente se destacará e, se você perguntar a ele, será um sucesso!"
1013706-11 = "Parece que vai chover à tarde, então vou terminar rápido e ir para casa!"
1013706-12 = "Shutsudo~!"
1013706-25 = "Suspirar..."
1013706-26 = "O que você quer dizer com ninguém está assistindo?"
1013706-27 = "Mesmo se eu te perguntar mais do que isso, é um pouco estranho..."
1013706-28 = "Talvez ele tenha fugido para as montanhas...? #nVou cavar nas raízes da árvore para encontrá-lo!"
1013706-29 = "[s] \"Sinto pena dos animais da montanha, então pare com isso!\""
1013706-30 = "Claro que vou restaurar as coisas ao normal. #n Ou melhor, é apenas um exemplo..."
1013706-31 = "Está ficando tarde, então tenho que me apressar e resolver isso..."
1013706-36 = "Huh?"
1013706-37 = "Eca! Está frio! !"
1013706-38 = "Parece que podemos nos proteger da chuva ali! #nAh, também! !"
1013706-41 = "(Ele correu para um lugar para ficar longe da chuva com Konoka.)"
1013706-42 = "(Os ombros de Konoka caíram por causa de seus repetidos fracassos e de repente ela começou a tirar a jaqueta.)"
1013706-45 = "[wa:2172]― [log=코노카]Ah, [wa:1075]Encharcado... [/log]"
1013706-47 = "― [log=코노카]Uh...[wa:570]Samu. [/registro]"
1013706-50 = "[wa:1586]― [log=코노카]A descida [wa:162] começou. [/registro]"
1013706-52 = "― [log=코노카]Parece que não para até a noite...[wa:2261]Suspiro... [/log]"
1013706-55 = "― [log=코노카]Bem, [wa:994][wa:1173]foi perfeito para esfriar minha cabeça. [/registro]"
1013706-58 = "[ns] \"Você está bem? Acalme-se?\""
1013706-59 = "[wa:517]― [log=코노카]Huh?[wa:973]ah,[wa:860]Hum.[/log]"
1013706-61 = "― [log=코노카]Se eu disser [wa:487] que não me arrependo, [wa:995] estarei mentindo. [/registro]"
1013706-64 = "― [log=코노카]Um monte de coisas [wa:273]Vou ser uma perda de tempo, [wa:1480]Vou ser um rato molhado... [/log]"
1013706-67 = "[wa:556]― [log=코노카]No entanto, [wa:816] adivinhação [wa:481] está correta. [/registro]"
1013706-69 = "― [log=코노카]Meu amigo estava [wa:217] ao meu lado, então [wa:1039] tive um bom dia [wa:425]. [/registro]"
1013706-72 = "- [log=코노카]...Obrigado ao sensei [wa:1002]. [/registro]"
1013706-75 = "[wa:870]― [log=코노카]Então, [wa:934]Em vez――[/log]"
1013706-77 = "― [log=코노카]Estou feliz. [/registro]"
1013706-80 = "― [log=코노카]...Ah, [wa:376]Não, [wa:607]Isso! [/registro]"
1013706-82 = "― [log=코노카]Assim eu [wa:337] posso me proteger da chuva, [wa:1249] tenho sorte [wa:490] estou feliz [wa:430] [wa:315]! [/registro]"
1013706-85 = "― [log=코노카]Bem, [wa:456]É isso...[wa:806]Então... [/log]"
1013706-88 = "……."
1013706-89 = "Ah... bem, o que quero dizer com felicidade. #nBem, evitei o pior, então..."
1013706-90 = "Especialmente o significado profundo..."
1013706-95 = "Oh, havia um cliente na minha frente."
1013706-96 = "Está muito quente lá dentro. Choveu de repente."
1013706-97 = "...?"
1013706-98 = "O que, você está sendo perseguido também? #nSinto que você é parecido conosco."
1013706-99 = "Ah, isso mesmo. Você viu um peixe-doce aqui perto?"
1013706-103 = "Seriamente...?"
1013706-105 = "[ns] \"Se for Valkyrie, aqui...\""
1013706-107 = "Eh..."
1013706-108 = "Ah~! De repente tenho vontade de ir a uma cachoeira! #nEntão vá primeiro! !"
1013706-112 = "Espere! ! !"
1013706-116 = "Uma operação policial é covardia! !"
1013706-117 = "Sim, duplique as taxas!"
1013706-118 = "Por que! ?"
1013706-119 = "Isso é um crime grave de obstrução!"
1013706-121 = "(Konoka correu em direção ao delinquente na chuva e prendeu rapidamente o suspeito.)"
1013706-122 = "(No caminho para casa, Konoka estava olhando pela janela enquanto era balançada pelo ônibus.)"