[translation]
1013106-1 = "Princesa parada no céu noturno"

1013106-3 = "[ns] \"De qualquer forma, Aurora...\""

1013106-4 = "Sim. Às vezes você pode vê-los em Red Winter."

1013106-5 = "Existe algum aplicativo de previsão de aurora como este?"

1013106-6 = "[s] \"Você gosta de tirar fotos?\""

1013106-7 = "Sim... isso mesmo."

1013106-8 = "Quando se trata de fotografia, prefiro tirar paisagens do que pessoas."

1013106-9 = "Além disso...acredito que a crítica e a fotografia têm algo em comum."

1013106-10 = "[s] \"Nunca pensei nisso assim.\""

1013106-11 = "...Cohon. Pois bem, deixe-me explicar."

1013106-12 = "A crítica é a imagem mental que surge quando você vê algum tipo de criação cultural."

1013106-13 = "É como juntar tudo usando sua própria teoria e “desenvolvê-la” em texto."

1013106-14 = "Em outras palavras, o ato de “consertar” a impressão que você tem naquele momento com sua própria interpretação."

1013106-15 = "E essa interpretação, ou “crítica”, é lida e recebida por outros..."

1013106-16 = "Adquire um certo grau de “objetividade”."

1013106-17 = "Acho que há algo em comum com a fotografia."

1013106-18 = "[s] \"Então, de certa forma, as fotografias também têm objetividade?\""

1013106-19 = "Sim, mas ao mesmo tempo..."

1013106-20 = "Dependendo da habilidade e sensibilidade de quem tira a foto, pode dar uma impressão completamente diferente, certo?"

1013106-21 = "Crítica que parte da subjetividade, mas visa a objetividade."

1013106-22 = "Fotografias que partem de uma perspectiva objetiva, mas que exalam subjetividade."

1013106-23 = "Esta estrutura aparentemente contraditória, mas de alguma forma ressonante... não é interessante?"

1013106-24 = "É assim que me sinto."

1013106-25 = "Tenho certeza de que a relação entre criação e crítica é a mesma."

1013106-26 = "[s] \"Criação... huh...\""

1013106-27 = "foto? Você já pensou que gostaria de tentar criar algo?"

1013106-28 = "Bem, isso é..."

1013106-29 = "……isso é……."

1013106-30 = "um……!"

1013106-34 = "professor! É Aurora!"

1013106-41 = "...A natureza é ótima, não é?"

1013106-42 = "Quando olho para a aurora, percebo que os humanos são seres minúsculos..."

1013106-43 = "Às vezes me pergunto se vale a pena criticar em primeiro lugar..."

1013106-44 = "Ainda assim, a criatividade é um dos resultados mais bonitos que uma pessoa pode produzir."

1013106-45 = "...Você conhece essa palavra? #n ``Mesmo que as próprias pessoas não sejam bonitas, o que elas criam pode ser lindo.''"

1013106-46 = "...Se não acho bonito, não tenho vontade de criar algo."

1013106-47 = "Portanto, a crítica é, em certo sentido, sobre a beleza criada pelo ser humano."

1013106-48 = "Talvez seja a minha maneira de expressar respeito..."

1013106-49 = "[s1] \"Nesse caso.\"\n[s2] \"Posso tirar uma foto do Takane na próxima vez?\""

1013106-52 = "Ei, ei? ! A professora...! ? #nIsso é...é uma grande honra...mas por que, de repente...!"

1013106-53 = "Huh! ? Vamos decidir um conceito e filmar...?"

1013106-54 = "Bem, eu quero que você “crie” você mesmo…! ? #nÉ muito irracional! ?"

1013106-55 = "[s3] \"Mas pense nisso!\"\n[s4] \"Tanto a aurora quanto a criação são lindas, então se você combiná-las, pode ficar ainda mais linda!\""

1013106-58 = "Se somar “lindo” e “lindo”, fica ainda mais lindo...! ?"

1013106-59 = "Então, não é teoria que takoyaki com calda de chocolate e menta seria uma delícia? ?"

1013106-63 = "Acima de tudo... a escrita criativa... não é domínio dos críticos."

1013106-64 = "É verdade que já vi muitas criações, mas..."

1013106-65 = "No entanto, presumir que você mesmo pode fazer isso nada mais é do que desrespeito à criatividade."

1013106-66 = "...Esse tipo de coisa só vai acabar machucando alguém. #nJá vi muita gente assim."

1013106-67 = "foto? Esta é uma criação secreta disponível apenas aqui? #nE se apenas o professor estivesse na plateia...?"

1013106-68 = "Mesmo que seja apenas um sonho, tente representar quem você quer ser...?"

1013106-69 = "[s] \"Sim. Serei o ``crítico Takane'' agora. \""

1013106-70 = "...!"

1013106-71 = "Pois bem...."

1013106-72 = "Pelo menos as palavras-chave devem ser decididas pelo professor..."

1013106-73 = "[s5] \"Então, digamos que você seja uma princesa caída e exilada!\"\n[s6] \"Em sua fuga, você vê a aurora boreal e vai às lágrimas!\""

1013106-76 = "...Eu realmente não sei por que todo mundo que me conhece corre nessa direção pelo menos uma vez."

1013106-77 = "Entendido. Estas são palavras-chave determinadas pelo professor."

1013106-78 = "Hum, cohon!"

1013106-79 = "Eu tinha três irmãs mais velhas. Nasci como a filha mais nova de uma família famosa..."

1013106-80 = "Cresci sendo amado por todos. Porém... meu corpo não era muito forte desde que eu era jovem."

1013106-81 = "Acho que foi uma reação por não poder brincar lá fora... acabei fazendo brincadeiras com as pessoas ao meu redor."

1013106-82 = "Minhas irmãs costumavam me chamar de ``.'' #nSou especialmente próxima da minha terceira filha, Irmã Maria..."

1013106-83 = "Nos dias em que me sentia bem, dormia no mesmo travesseiro que ele e pela manhã tomávamos banho frio juntos."

1013106-84 = "Eu realmente não queria tomar banho frio, mas #n-sama disse que isso me deixaria mais saudável, então..."

1013106-85 = "Mas esses dias pacíficos chegaram ao fim. A família #n caiu e as irmãs seguem caminhos separados..."

1013106-87 = "Nos dispersamos, acreditando que um dia nos encontraríamos novamente..."

1013106-94 = "[wa:320]― [log=타카네]先生、[wa:1290]ご覧ください……[/log]"
1013106-96 = "- [log=타카네]É a aurora. [/registro]"

1013106-99 = "― [log=타카네]Na história,[/log]"

1013106-101 = "― [log=타카네]Os guardiões do céu――[/log]"

1013106-104 = "― [log=타카네]Aproveitando a festa[/log]"

1013106-106 = "― [log=타카네]Diz-se que [wa:750] é assim que parece. [/registro]"

1013106-109 = "[wa:320]― [log=타카네]いつも一緒にいられると[wa:1000]思っていた方々とは[/log]"
1013106-111 = "― [log=타카네]Não poderei ver você de novo...[wa:1940]Mas. [/registro]"

1013106-114 = "[wa:2130]― [log=타카네]世界はこれまで通り、[/log]"
1013106-116 = "― [log=타카네]Está frio e [wa:2100] longe. [/registro]"

1013106-119 = "― [log=타카네]Mesmo assim, eu [wa:930] olhei para a aurora, [/log]"

1013106-121 = "― [log=타카네]Ter esperança――[/log]"

1013106-124 = "[wa:770]― [log=타카네]この場所で、[wa:1600]最後まで私と[wa:980]共にいてくださる[/log]"
1013106-126 = "― [log=타카네]Acho que é porque você tem um \"parceiro\" [wa:480]. [/registro]"

1013106-129 = "[ns] \"Entendo. Sou o \"parceiro\" de Takane agora.\""

1013106-131 = "[wa:280]― [log=타카네]ふふっ。[wa:1530]ええ、[/log]"
1013106-133 = "― [log=타카네]Essa é a configuração [wa:720]agora, [wa:1550]``Professor.'' [/log]"

1013106-136 = "― [log=타카네]Eu apreciaria suas [wa:1240]fotos [wa:520], certo? [/registro]"

1013106-139 = "……."

1013106-140 = "[s] \"P-por que você está tão inquieta, princesa...?\""

1013106-141 = "Eu não sou uma princesa! Essa história acabou! #nEu sou apenas Takane - e sempre serei."

1013106-142 = "Enfim...se fosse um trabalho criativo escrito por outra pessoa, no momento em que virei a primeira página..."

1013106-143 = "Foi um trabalho que me deu vontade de criticá-lo e dizer: ``Com apenas uma linha você conseguiu a proeza de me fazer desistir de ler.''"

1013106-144 = "[s] \"Mas você mesmo escreveu, certo?\""

1013106-145 = "Não é porque seu professor lhe disse para fazer isso? ! !"

1013106-146 = "Ugh... #nEstá tudo bem... por favor, mostre-me sua foto."

1013106-147 = "[s] \"O que você acha?\""

1013106-148 = "……."

1013106-149 = "...É uma foto muito bonita..."

1013106-150 = "Obrigado, senhor."

1013106-151 = "Bom, só tenho um pedido..."

1013106-152 = "Essa foto... e o que aconteceu aqui..."

1013106-153 = "Você poderia, por favor, não contar a ninguém?"

1013106-154 = "[s] \"Você está tão envergonhado?\""

1013106-155 = "Isso também... claro que existem alguns..."

1013106-160 = "Quero manter tudo em segredo, apenas entre você e eu."

