[translation]
1013902-1 = "Recomendações de Nico"
1013902-2 = "(Alguns minutos depois de receber o misterioso Momotalk...)"
1013902-6 = "(De repente, o interfone do escritório tocou)"
1013902-8 = "Boa noite, aqui é \"FOX EATS\"."

1013902-9 = "O produto encomendado foi entregue!"
1013902-10 = "[s1] Abra a porta. \r\n[s2] Não consigo abrir a porta."
1013902-14 = "Parece que está trancado novamente..."
1013902-15 = "Eu não posso evitar. Branqueamento de porta novamente..."
1013902-16 = "[ns] \"Eu-eu vou abrir agora mesmo!!\""
1013902-21 = "Boa noite, sensei. Esta é a FOX EATS."
1013902-22 = "Você ainda não jantou, não é?"
1013902-23 = "Você tem que comer corretamente. Se você não fizer três refeições corretamente, faz mal à saúde."
1013902-24 = "[ns] \"Ainda não comi...\""
1013902-26 = "[ns3] \"Como você sabia?\"\n[ns4] \"Você está me monitorando de algum lugar?\""
1013902-29 = "Hehe. Ele é um membro das forças especiais. #nExistem muitas maneiras de coletar informações."
1013902-30 = "Quando verifiquei a geladeira da placa de Petri esta tarde, quase não havia mais comida."
1013902-31 = "E ninguém veio à placa de Petri com comida depois do almoço."
1013902-32 = "Além disso, o mensageiro do sensei estava sempre online, então pensei que ele devia estar trabalhando sem parar."
1013902-33 = "[s] \"...Isso mesmo.\""
1013902-34 = "Também não é uma boa ideia trabalhar sentado no mesmo lugar o tempo todo."
1013902-35 = "Prepararei sua refeição imediatamente, então, por favor, faça uma pausa, sensei."
1013902-36 = "[s] \"Acho que vou acreditar na sua palavra e fazer uma pausa...\""
1013902-38 = "[ns] \"A propósito, o que você trouxe?\""
1013902-39 = "n / D. Tudo que trouxe foram os ingredientes. \r\n"
1013902-40 = "A comida é melhor quando preparada na hora."
1013902-41 = "Eu comprei muitas coisas, então você poderia me dizer o que gostaria de comer?"
1013902-42 = "Eu acho que você pode fazer a maioria das coisas."
1013902-43 = "[s] \"Eu ficaria feliz se Nico pudesse fazer isso para mim...\""
1013902-47 = "[ns] \"Então...Recomendação do Nico .\""
1013902-48 = "Minha... recomendação? \r\n"
1013902-49 = "Quando questionado sobre o prato em que tenho mais confiança... é verdade. #nÉ o sushi inari que sempre faço para todo mundo?"
1013902-50 = "[s] \"Está tudo bem. Vou deixar isso para Nico.\"\"\n1013902-51 = \"Eu entendi. Por favor, espere um momento. \r\n\"\n1013902-55 = \"...Quando faço sushi assim, meio que me lembra daqueles dias. \r\n\"\n1013902-56 = \"[s] \"E a primeira vez que você conheceu Nico?\"\"\n1013902-57 = \"sim. Naquela época, a professora também comia muito sushi inari.\"\n1013902-58 = \"Essa foi uma estratégia para aliviar a cautela do sensei, mas...\"\n1013902-59 = \"Mesmo assim, pelo menos o sushi inari foi feito com sinceridade.\"\n1013902-60 = \"É um prato que todos do pelotão também adoram.\"\n1013902-61 = \"[s] \"Por que você começou a fazer sushi inari?\"\"\n1013902-62 = \"Foi isso que desencadeou isso? Isso mesmo.\"\n1013902-63 = \"Pouco depois da criação do pelotão FOX, percebi que precisávamos de uma lancheira para quando as operações fossem longas.\"\n1013902-64 = \"Mas naquela época eu não era muito bom em cozinhar... o máximo que conseguia fazer era sushi inari.\"\n1013902-65 = \"Mesmo isso... eu não era muito bom nisso...\"\n1013902-66 = \"Mesmo assim, todos me incentivaram e disseram que estava uma delícia... isso me deixou feliz e comecei a fazer de novo.\"\n1013902-67 = \"Hehe, essa é uma história estranha. #nNaquela época, eu não tinha nenhum apego especial ao sushi inari.\"\n1013902-68 = \"[s] \"De alguma forma, sinto que entendo.\""

1013902-72 = "[ns5] \"O sabor da comida também é o tempero das memórias.\"\r\n[ns6] \"O Inarizushi de Nico está imbuído de tantas memórias.\""
1013902-75 = "……Concordo. É um prato especial para mim."
1013902-76 = "Então, enquanto conversávamos, o sushi inari foi concluído! \r\n\r\n"
1013902-77 = "[s7] \"Já?\"\r\n[s8] \"É cedo.\""
1013902-80 = "É um prato simples, basta rechear tofu frito cozido com arroz."
1013902-81 = "Leva tempo para fritar o tofu frito do zero, mas se não fizer isso, você pode prepará-lo imediatamente."
1013902-82 = "[s] \"Ok, eu aceito--\""
1013902-83 = "Espere um minuto, senhor. \r\n"
1013902-84 = "n / D. Você disse isso antes, certo? #nO jantar de hoje é minha recomendação."
1013902-89 = "Este é o kitsune udon que fiz enquanto fervia o tofu frito. #nPor favor, aproveite esta noite. \r\n"
1013902-90 = "Está frio esta noite, então acho que udon quente seria melhor para o corpo. \r\n"
1013902-91 = "[s] \"Fico muito feliz pela sua consideração, mas e o sushi inari...?\""
1013902-92 = "Tudo bem se estiver pronto, mas o sushi inari fica melhor se você deixar descansar um pouco... \r\n"
1013902-93 = "……sensei. De qualquer forma, você estava planejando não tomar café da manhã amanhã ou apenas tomá-lo em uma réplica, certo? \r\n"
1013902-94 = "[ns] \"...Isso também é resultado da coleta de informações?\""
1013902-95 = "Não, é apenas um palpite."
1013902-96 = "O sensei é surpreendentemente fácil de entender."
1013902-97 = "Guarde este sushi inari na geladeira e saboreie-o amanhã de manhã."
1013902-98 = "Além disso... por favor, não se esforce demais."
1013902-99 = "Pois bem, sensei, boa noite."
1013902-101 = "(Depois, comi o udon kitsune que Nico fez e tive uma noite quente pela primeira vez em muito tempo.)"
