[translation]
1013103-1 = "hóquei no gelo"
1013103-2 = "Bem-vindo, sensei!"
1013103-3 = "[s] \"Desculpe incomodá-lo!\""
1013103-4 = "Pois bem, vamos para a sala de projeção imediatamente."
1013103-5 = "foto? Você não deveria assistir aqui? #nNão, isto é apenas um workshop."
1013103-6 = "Acima de tudo, não temos nenhum equipamento para transmitir vídeo."
1013103-7 = "aqui vamos nós! Siga-me, por favor!"
1013103-12 = "[ns] \"Huh...? É uma instalação incrível, não é?\""
1013103-13 = "A Senseia está chegando. Claro que vou preparar isso."
1013103-14 = "[s1] \"Agradeço sua opinião, mas...\"\n[s2] \"O departamento editorial tem instalações como esta?\""
1013103-17 = "Ah, isso mesmo..."
1013103-18 = "Bem...o departamento editorial é nominalmente um departamento editorial, mas..."
1013103-19 = "Acho que você poderia dizer que isso foi simplesmente o resultado de o gerente gostar um pouco demais de dinheiro."
1013103-20 = "Sou bastante ativo em todos os projetos culturais do Red Winter...#nNão, estou organizando a maioria deles."
1013103-21 = "Então... sim..."
1013103-22 = "[s] \"...o escritório não disse nada?\""
1013103-23 = "Les, Red Winter tem o estilo de Red Winter. #nO departamento editorial também possui procedimentos para o departamento editorial!"
1013103-24 = "E nunca tiramos pessoalmente nenhuma vantagem injusta!"
1013103-25 = "Bem, mais do que isso, sensei! #nÉ hóquei, é hóquei no gelo!"
1013103-26 = "Como mencionei outro dia, as semifinais começarão em breve!"
1013103-27 = "Devido à natureza da escola de Red Winter, os esportes de inverno são populares..."
1013103-28 = "O hóquei no gelo também tem fãs apaixonados!"
1013103-32 = "Obrigado por esperar tanto tempo! #nAs semifinais da Liga de Hóquei no Gelo vão começar agora!"
1013103-33 = "Já começou, senhor!"
1013103-34 = "Como você já deve saber, os times de hóquei no gelo são compostos por seis jogadores. Não é surpreendentemente pequeno?"
1013103-35 = "A partida foi disputada três vezes de 20 minutos, totalizando 60 minutos. #n Cada um desses 20 minutos é chamado de \"período\"."

1013103-36 = "As regras são bastante simples. Basta acertar o disco com o taco e colocá-lo no gol."
1013103-37 = "Ah, a propósito, no hóquei no gelo, é costume chamar o jogador de “goleiro” em vez de goleiro."
1013103-38 = "Verificação corporal intensa! Isso é incrível! É uma defesa agressiva!"
1013103-39 = "[s] \"Você acabou de derrotar seu oponente com um ataque corporal!?\""
1013103-40 = "Sim, esse nível é aceitável para o hóquei no gelo Red Winter."
1013103-41 = "Mais importante ainda, você que ficou impressionado! Levante-se rapidamente! Atrasar o jogo resultará em pênaltis!"
1013103-42 = "[s3] \"É seguro bater violentamente em alguém...\"\n[s4] \"É falta se a pessoa cair...\""
1013103-45 = "sim! Isso é Hóquei no Gelo de Inverno Vermelho!"
1013103-46 = "[s] \"Oh, você acabou de bater em alguém com um pedaço de pau.\""
1013103-47 = "Você não pode! Isso é um banimento de 5 minutos!"
1013103-48 = "O que? ! Juiz, o que diabos você está fazendo? ? Leva apenas 2 minutos! #nNão é como se o árbitro estivesse guardando isso na manga! ?"
1013103-49 = "[s5] \"Talvez seja uma retaliação pelo ataque corporal anterior?\"\n[s6] \"Agora mesmo, um jogador foi completamente surpreendido por uma combinação de três ataques corporais seguidos...\"\n[s7] \"O vidro dos assentos da plateia estava rachado, mas...este hóquei do Red Winter também!?\""
1013103-53 = "Ah... fui longe demais. Se o vidro quebrar, o jogo será suspenso até que seja substituído."
1013103-54 = "Além disso, se você fizer esse tipo de verificação corporal violenta, contínua e deliberada, você definitivamente receberá pelo menos 10 minutos de penalidade de expulsão por comportamento pouco cavalheiresco."
1013103-55 = "Este é o sinal para reiniciar o jogo! O árbitro de hoje é surpreendentemente generoso!"
1013103-56 = "Julgamento! ? Você não quer ver o nascer do sol amanhã? ? ! ?"
1013103-57 = "[s] \"Ah. Uma briga começou.\""
1013103-58 = "Claro! Isso é algo que precisa ser consertado de uma vez por todas!"
1013103-59 = "Em primeiro lugar, é estranho que não haja brigas no hóquei no gelo."
1013103-60 = "Quando o time da casa está perdendo feio, eles até provocam brigas intencionalmente como parte do fan service."
1013103-61 = "Quando uma partida fica fora de controle, é pelo menos para dar aos espectadores que estão relutantes em pagar pelos ingressos a chance de assistir."
1013103-62 = "Em primeiro lugar, a armadura do hóquei no gelo é fortemente blindada..."
1013103-63 = "A regra tácita é largar os gravetos e lutar entre si com as próprias mãos, então é surpreendentemente grande..."
1013103-69 = "[ns8] \"Parece que os espectadores estão invadindo o rinque agora...\"\n[ns9] \"Eles estão queimando a bandeira do time lá fora...\""
1013103-72 = "……falta."
1013103-73 = "...A comoção ficou um pouco mais alta."
1013103-74 = "Isso também é comum?"
1013103-75 = "……."
1013103-76 = "É isso mesmo... embora isso não aconteça com muita frequência."
1013103-77 = "Não é uma visão difícil de ver... é?"
1013103-81 = "...Portanto, condenamos a secretaria!"
1013103-82 = "Condenação! Condenação!"
1013103-83 = "Ainda está frio hoje! A semana de trabalho de 3 dias não foi estabelecida! Sempre havia apenas uma ração de pudim, e às vezes era diluída em água!"
1013103-84 = "Foi assim que perdi no hóquei no gelo! É tudo culpa do escritório!"
1013103-85 = "Isso mesmo! Isso mesmo!"
1013103-86 = "Camaradas! Vamos para o escritório!"
1013103-87 = "vamos! vamos!"
1013103-90 = "[ns10] \"Isso é...de jeito nenhum...\"\n[ns11] \"Inverno Vermelho... saudação matinal!?\""
1013103-93 = "Onde diabos você ouviu essa expressão? ?"
1013103-94 = "...Lamento dizer isso, mas como aluno do Red Winter...me dói um pouco os ouvidos."
1013103-95 = "Ah, ah, teste de microfone, teste de microfone"
1013103-96 = "Olá pessoal. Caros alunos do Red Winter, gostaríamos de informar que acaba de ocorrer um golpe de estado no principal estádio de hóquei no gelo."
1013103-97 = "Nós, do Secretariado, prometemos fazer o nosso melhor para lidar com esta situação e aproveitaremos este momento para declarar a lei marcial local e fazer tudo o que estiver ao nosso alcance para manter a ordem."
1013103-98 = "Pedimos que todos os alunos não fiquem chateados e se concentrem nos estudos e no trabalho."
1013103-99 = "Gostaria de reiterar isso. O Inverno Vermelho é seguro. o inverno vermelho é seguro"
1013103-100 = "Ei, quanto tempo você acha que pode correr e se esconder dessa vez?"
1013103-101 = "Eu vejo isso como 2 dias"
1013103-102 = "eu tenho 3 dias"
1013103-103 = "Você quer apostar?"
1013103-104 = "legal"
1013103-105 = "Vocês ainda não desligaram o microfone! ! !"
1013103-106 = "Peeeeee"

1013103-111 = "……."
1013103-112 = "[s] \"…….\""
1013103-113 = "Hum, sensei?"
1013103-114 = "Como esperado hoje... parece que muitas coisas serão perigosas..."
1013103-115 = "Até você se acalmar um pouco, gostaria de assistir comigo uma coleção de jogos famosos de hóquei no gelo?"
1013103-117 = "(Foi assim que assisti a uma coleção de jogos famosos de hóquei no gelo com Takane...)"
