[translation]#[Não revisado] - Filipe 09/06/26
1014102-1 = "Encontro inesperado"
1014102-3 = "(No caminho de volta do trabalho)"
1014102-10 = "(Haruka andava de um lado para o outro na frente de um local de exposição?)"
1014102-17 = "(Vendo que Haruka não entrava no local...) "
1014102-19 = "(Resolveu chamá-la)"
1014102-25 = "P-professor!?"
1014102-30 = "[ns] \"Olá, Haruka.\""
1014102-31 = "O-olá!"
1014102-32 = "D-desculpa! Não percebi que o senhor estava aí...!"
1014102-33 = "[s] \"Isso é uma exposição?\""
1014102-34 = "Hã? Ah, sim... mais ou menos."
1014102-35 = "Hmm, que tipo de exposição..."
1014102-36 = "Exposição de horticultura de Kivotos –"
1014102-37 = "Um grande evento que exibe e vende árvores de rua, arbustos, equipamentos de jardinagem... foi o que ouvi."
1014102-38 = "[s] \"Entendo, por isso você veio toda arrumada.\""
1014102-39 = "Hã?"
1014102-40 = "Hããã!?"
1014102-41 = "L-linda!? Nada disso!"
1014102-42 = "Por mais lindo que seja o vestido, uma pessoa sombria como eu..."
1014102-43 = "[s] \"Mas está mesmo.\""
1014102-44 = "F-fueeee!"
1014102-45 = "N-não precisa mentir para me agradar..."
1014102-46 = "[s] \"Estou falando sério...\""
1014102-47 = "Aaaaah!"
1014102-48 = "Desculpa desculpa desculpa!"
1014102-50 = "(Acariciou suavemente a cabeça de Haruka, que estava em pânico, para acalmá-la)"
1014102-52 = "Uuuh..."
1014102-53 = "Desculpa... me descontrolei de novo..."
1014102-54 = "Hã? Por que não entra, é isso?"
1014102-55 = "É porque..."
1014102-56 = "Eu não tenho o direito de entrar..."
1014102-57 = "[s1] \"Hã?\"\n[s2] \"O que você quer dizer?\""
1014102-60 = "N-não, é que..."
1014102-61 = "Hoje eu vim como segurança daqui."
1014102-62 = "Então não preciso entrar."
1014102-63 = "[s] \"Segurança...?\""
1014102-64 = "Ah, será que eu entendi errado o significado de segurança!? Devia ter virado o portão em vez de guarda?"
1014102-65 = "[s] \"Aí já não é segurança!?\""
1014102-68 = "(Ao ouvir a história, Haruka foi contratada como segurança do evento)"
1014102-72 = "[ns] \"Então o motivo do vestido também...\""
1014102-73 = "Sim, código de vestimenta... algo assim."
1014102-74 = "Os seguranças também precisam de uma certa formalidade..."
1014102-75 = "... Essa roupa não é formal?"
1014102-76 = "[s] \"Não, está tudo bem.\""
1014102-77 = "É mesmo?"
1014102-78 = "Então tudo bem –"
1014102-82 = "BOOOOOM!"
1014102-86 = "[ns] \"Explosão...!?\""
1014102-87 = "Foi dentro do recinto!"
1014102-88 = "É uma briga!?"
1014102-92 = "A melhor árvore de rua de Kivotos é o ginkgo! O resto é tudo heresia!"
1014102-93 = "Humpf, seu cabeça-dura! O que tem de bom essa árvore fedorenta?"
1014102-94 = "O quê! Fedorenta!? O plátano que você defende também espalha uma porção de sementes nojentas na primavera!"
1014102-95 = "O que foi!? Nojentas!?"
1014102-96 = "Não aguento mais! Atirem!"
1014102-101 = "Parece que estão brigando por causa de árvores de rua..."
1014102-102 = "O que fazemos? Devíamos intervir?"
1014102-103 = "Uuuh, isso não estava no manual..."
1014102-107 = "[ns] \"Ora? Lascas de madeira estão voando –\""
1014102-111 = "[ns] \"Ai.\""
1014102-113 = "[ns] \"Ai... Haruka? O que foi?\""
1014102-114 = "Es..."
1014102-115 = "Seus vermes...!"
1014102-116 = "[s5] \"Haruka!?\"\n[s6] \"Eu estou bem, não se preocupe –\""
1014102-127 = "Como ousaram machucar o rosto do professor!?"
1014102-128 = "V-você quem é!?"
1014102-129 = "Morram morram morram morram!!"
1014102-130 = "Vou enterrar todos debaixo de uma árvore!"
1014102-131 = "M-me ajudem!"
1014102-139 = "(E assim, Haruka subjugou a confusão num instante)"
1014102-140 = "(... O preço foi a destruição do local)"
1014102-142 = "Beco atrás da feira"
1014102-144 = "[ns] \"Bom trabalho, Haruka.\""
1014102-145 = "U-uh..."
1014102-146 = "D-desculpa, desculpa, desculpa."
1014102-147 = "O senhor ainda teve que se explicar para a organização..."
1014102-148 = "[s] \"Você só fez o seu trabalho, Haruka.\""
1014102-149 = "Uuh..."
1014102-150 = "Obrigada, professor..."
1014102-152 = "(Depois de sentar e descansar um pouco)"
1014102-153 = "(Acompanhou Haruka de volta ao escritório da Empresa de Conveniência)"