[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
1014203-1 = "A Garota da Praia" 
1014203-2 = "（Alguns dias depois. Visitei a cidade de\nHyakkiyako a trabalho...）" 
1014203-5 = "Ei, ficou sabendo do boato?" 
1014203-6 = "Boato? De quê?" 
1014203-7 = "Dizem que uma Yuki-onna (Mulher das Neves)\napareceu na Costa de Torii!" 
1014203-8 = "Eh? Uma Yuki-onna?\n\n" 
1014203-10 = "（Em outro lugar também...）" 
1014203-12 = "Não, espera. Se uma Yuki-onna estivesse na praia,\nela não derreteria com o sol?" 
1014203-13 = "Será que é assim que funciona?\nDe qualquer forma, é o boato do momento." 
1014203-14 = "Dizem que a Yuki-onna tá vagando\nsozinha pela praia!" 
1014203-16 = "[ns1] （Boatos estranhos estão se espalhando...）\n[ns2] （Não me diga que...）" 
1014203-20 = "（Fui às pressas para a sala do clube da Hyakkaryouran.）" 
1014203-22 = "Sensei? O que houve de repente?" 
1014203-24 = "（Falei sobre os boatos que estão\nse espalhando pela cidade.）\n" 
1014203-26 = "......\n" 
1014203-27 = "Isso deve ser sobre mim." 
1014203-28 = "Eu tenho ido bastante à Costa de Torii ultimamente." 
1014203-29 = "Estava nadando sozinha para não chamar a atenção,\nmas parece que teve o efeito contrário.\n" 
1014203-30 = "......Como eu imaginava, não importa o que eu faça,\neu sempre acabo atraindo olhares.\n" 
1014203-31 = "[ns3] \"I-Isso é culpa minha...!\"\n[ns4] \"Eu que te incentivei a ir mais à praia...\"" 
1014203-34 = "[ns] \"Certo, já pensei numa solução!\"" 
1014203-35 = "Hm? O que vai fazer?" 
1014203-37 = "Vá à praia comigo!" 
1014203-40 = "......\n" 
1014203-41 = "Já que o boato é sobre a Yuki-onna\nestar vagando sozinha..." 
1014203-42 = "Se o Sensei estiver ao meu lado,\nos boatos vão sumir naturalmente, é isso?\n" 
1014203-43 = "......\n" 
1014203-44 = "Você só quer usar isso como desculpa\npara ir brincar comigo na praia." 
1014203-45 = "O Sensei é realmente bem astuto." 
1014203-46 = "Mas bem... parece divertido." 
1014203-47 = "Entendido. Vamos lá, Sensei.\n" 
1014203-48 = "[s] \"Isso...!\"" 
1014203-50 = "（E então, na praia onde fui com a Nagusa...）\n" 
1014203-58 = "（Muitas alunas estavam se divertindo.）" 
1014203-63 = "Hoje tem mais gente que o normal." 
1014203-65 = "Ah! Nagusa-san!" 
1014203-66 = "A Nagusa-san também veio\nver a Yuki-onna?" 
1014203-68 = "......Hm?\n" 
1014203-69 = "[s] \"Será que o fato de ter tanta gente...\né por causa disso?\"" 
1014203-70 = "......" 
1014203-71 = "A tal Yuki-onna dos boatos,\nprovavelmente sou eu." 
1014203-73 = "Eh?!" 
1014203-75 = "Eu estava agindo para não chamar a atenção,\nmas parece que isso gerou um mal-entendido." 
1014203-77 = "N-Nós nem sabíamos disso...!" 
1014203-79 = "Tudo bem. Não se preocupem com isso." 
1014203-86 = "Então, Sensei...\nvamos curtir a praia juntos." 
1014203-87 = "Para desfazer o mal-entendido de todo mundo." 
1014203-88 = "[s] \"Com certeza!\"" 
1014203-110 = "（Nós realmente tivemos\num tempo muito divertido...）\n" 
1014203-117 = "Nossa... já é essa hora.\n" 
1014203-118 = "Graças a você, Sensei,\neu me diverti muito." 
1014203-119 = "Até esqueci o motivo de\ntermos vindo à praia.\n" 
1014203-120 = "Viemos para desfazer um mal-entendido,\nmas acabei me empolgando brincando..." 
1014203-121 = "[ns] \"O motivo não importa.\"" 
1014203-123 = "[ns] \"Se o tempo que passamos juntos foi divertido,\nisso já é o suficiente.\"" 
1014203-125 = "......\n" 
1014203-126 = "......Sim. Tem razão." 
1014203-127 = "Se for assim, posso te convidar de novo?" 
1014203-128 = "[s] \"É claro!\"" 
1014203-129 = "Obrigada, Sensei." 
1014203-134 = "Já está tarde... vamos voltar.\n" 
1014203-136 = "（Depois disso, acompanhei a Nagusa\naté a sala do clube da Hyakkaryouran.）" 
1014203-137 = "（Mal posso esperar pelo dia em que\niremos à praia novamente.）" 