[translation]
1014505-1 = "Journey to the Heavens"
1014505-2 = "I did some research last night—"
1014505-3 = "It seems that riding a boat in this valley is a 'must'."
1014505-4 = "[s] \"Oh, really?\""
1014505-5 = "Indeed."
1014505-6 = "Riding a rowboat and enjoying the passing scenery... that seems to be quite popular."
1014505-7 = "I imagine the crowds will start pouring in once the afternoon hits."
1014505-8 = "Therefore, I had no choice but to come early if I wanted to spend some time in peace."
1014505-9 = "[s1] \"The view is nice even from here, though.\"\n[s2] \"I bet it's even more amazing from the water.\""
1014505-12 = "Indeed. Shall we go?"
1014505-14 = "—That concludes the explanation."
1014505-15 = "The river water is cold even in summer, so please be careful not to fall in."
1014505-16 = "Now, please, this way."
1014505-17 = "Hehe, I'm looking forward to this."
1014505-18 = "That must be the boat in question. I believe they said it holds up to four people? #nIt should be quite spacious for just the two of us."
1014505-19 = "I've heard the mist and the mountains are spectacular... I wonder just how much so."
1014505-20 = "There are days when you can't see them, so that part is just up to luck, unfortunately..."
1014505-21 = "Beyond the mist spreading across the river, the majestic mountains tower over everything."
1014505-22 = "You'll feel just like a legendary immortal!"
1014505-23 = "Hehe. That is something to look forward to."
1014505-24 = "Come, let us be off."
1014505-28 = "(As I go to follow Kisaki onto the boat)"
1014505-29 = "Oh, excuse me. A quick explanation for the guardian."
1014505-30 = "[s] \"Hm? Oh, sure.\""
1014505-31 = "I have a small addition."
1014505-32 = "This boat is equipped with the latest autonomous driving system."
1014505-33 = "The traditional look is purely decorative."
1014505-34 = "So, there's no need to struggle with the oars. #nJust a light touch is all it takes!"
1014505-35 = "[s] \"That's high-tech.\""
1014505-36 = "Also, please rest assured if you lose your way due to thick fog or the like."
1014505-37 = "If you switch to autonomous mode, it will automatically return here."
1014505-38 = "Well then, have a pleasant voyage!"
1014505-39 = "Sensei? Is something the matter?"
1014505-40 = "[ns] \"Coming!\""
1014505-42 = "(I boarded the boat with Kisaki)"
1014505-43 = "(The boat moved smoothly without needing any effort on the oars)"
1014505-45 = "…It is quiet."
1014505-46 = "I am leaving it all to you, but... are you not tired?"
1014505-47 = "[s] \"I'm still fine.\""
1014505-48 = "I see. Your arms are sturdier than I expected."
1014505-49 = "A thousand peaks tower above, and the river, embraced by the mountains, traces its path."
1014505-50 = "Do you see, Sensei? #nTwo egrets are gazing at each other so affectionately."
1014505-51 = "..."
1014505-52 = "Could you stop the boat for a moment?"
1014505-53 = "Water constantly gathers in the sea, and time cares not for man..."
1014505-54 = "But here, in this moment with you, it feels as if everything has come to a standstill."
1014505-55 = "..."
1014505-57 = "Birds return to the clear waters."
1014505-58 = "The river flows on, never ceasing."
1014505-59 = "The world questions the meaning of wealth and honor."
1014505-60 = "With you here, I raise my cup to the sky."
1014505-62 = "…Hmm."
1014505-63 = "[s] \"Is something wrong?\""
1014505-64 = "Look."
1014505-65 = "The fog is getting thicker."
1014505-66 = "I see, so this is..."
1014505-67 = "Perhaps this is the kind of scenery one experiences when one becomes an immortal."
1014505-70 = "[wa:740]— [log=키사키 수영복]What do you think, [wa:1260]Sensei?[/log] "
1014505-72 = "— [log=키사키 수영복]The scenery that was so full of color—[wa:1600] [wa:1470]is now like this.[/log] "
1014505-75 = "— [log=키사키 수영복]Indeed, [wa:1290]it has become refined.[/log] "
1014505-78 = "[wa:1180]— [log=키사키 수영복]The river, [wa:1090]the water, [wa:1100]the mist, [wa:1380]the mountains...[/log] "
1014505-80 = "— [log=키사키 수영복]And Sensei... [wa:2530]you are the only thing [wa:1850]reflected in my eyes.[/log] "
1014505-83 = "[wa:2860]— [log=키사키 수영복]What is reflected [wa:2070]in your eyes?[/log] "
1014505-85 = "— [log=키사키 수영복]Amidst me and this scenery...[/log] "
1014505-88 = "— [log=키사키 수영복]Are you [wa:1450]trapping me [wa:2240]within your gaze?[/log] "
1014505-91 = "[wa:200]— [log=키사키 수영복]Hehe... [wa:2280]have you ever heard [wa:1090]a tale like this?[/log] "
1014505-94 = "— [log=키사키 수영복]That a celestial maiden rides the wind—[/log]"
1014505-96 = "— [log=키사키 수영복]And dances in the sky [wa:1760]like a feather.[/log] "
1014505-99 = "[wa:870]— [log=키사키 수영복]Close your eyes [wa:2170]and take a deep breath, [wa:2280]Sensei.[/log] "
1014505-101 = "— [log=키사키 수영복]If you do, [wa:1570]perhaps even there—[/log] "
1014505-104 = "— [log=키사키 수영복]You might be able [wa:1140]to feel me?[/log] "
1014505-107 = "…The fog?"
1014505-109 = "[ns] \"The sun is coming out, it's clearing up.\""
1014505-110 = "Hehe, I see."
1014505-111 = "It wouldn't have been so bad to pretend to be immortals with you, but..."
1014505-112 = "..."
1014505-113 = "It cannot be helped. Those of the mortal world must live a mortal life."
1014505-114 = "Shall we take our leave then?"
1014505-115 = "[s] \"Yes, Gatekeeper.\""
1014505-120 = "(I took the helm myself and slowly headed back)"