[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
1014206-1 = "Um Sinal Só Nosso" 
1014206-2 = "（E quando fomos à praia...）\n" 
1014206-7 = "Belo corte~!\n" 
1014206-8 = "M-Me pegou...!\n" 
1014206-9 = "Essa voz é...?" 
1014206-10 = "Sensei. Vamos lá dar uma olhada." 
1014206-16 = "[ns] \"Vocês estão jogando vôlei de praia?\"" 
1014206-17 = "Ah! Nagusa-san! Sensei!\n" 
1014206-18 = "Vocês dois não querem jogar\nvôlei de praia com a gente?" 
1014206-23 = "Por mim tudo bem, e você, Sensei?" 
1014206-24 = "[s1] \"Eu vou só assistir.\"\n[s2] \"Acabaria sendo um peso morto para a Nagusa.\"" 
1014206-27 = "Mas é mais divertido jogarmos juntos." 
1014206-28 = "Ah..." 
1014206-29 = "Por acaso... você é do tipo que prefere\nolhar em vez de participar?" 
1014206-33 = "Como eu imaginava, o Sensei é..." 
1014206-34 = "[s] \"Não sei o que você tá pensando,\nmas tá errado!\"" 
1014206-36 = "（No fim das contas, acabamos todos\njogando vôlei de praia juntos...）\n" 
1014206-38 = "Certo, então o Sensei e a Nagusa-san\nvão ser um time!" 
1014206-39 = "Acho que assim as equipes\nficam mais equilibradas!" 
1014206-40 = "[s] \"Vou dar o meu melhor\npara não ser um peso morto.\"" 
1014206-44 = "Eu não te acho um peso morto.\n" 
1014206-45 = "Meu braço direito está em\nótima forma hoje, aliás." 
1014206-46 = "Fique tranquilo. A eu de hoje...\né invencível." 
1014206-47 = "[s3] \"M-Mas eu não posso deixar\ntudo nas suas costas.\"\n[s4] \"Tem alguma estratégia onde eu possa ser útil?\"" 
1014206-54 = "Estratégia..." 
1014206-55 = "Que tal usarmos sinais simples?" 
1014206-56 = "Assim podemos nos comunicar durante a partida\nsem que o oponente perceba..." 
1014206-57 = "Sinais secretos que só nós dois entendemos." 
1014206-59 = "（Um tempo depois, a hora do confronto chegou...）\n" 
1014206-61 = "[fffbab]N[-]" 
1014206-62 = "[fffbab]A[-]" 
1014206-63 = "[fffbab]G[-]" 
1014206-64 = "[fffbab]U[-]" 
1014206-65 = "[fffbab]SA[-]" 
1014206-68 = "[ffaecd]A[-]" 
1014206-69 = "[ffaecd]lu[-]" 
1014206-70 = "[ffaecd]nas[-]" 
1014206-71 = "[ffaecd] d[-]" 
1014206-72 = "[ffaecd]a[-]" 
1014206-73 = "[ffaecd] H[-]" 
1014206-74 = "[ffaecd]ya[-]" 
1014206-75 = "[ffaecd]kki[-]" 
1014206-76 = "[ffaecd]yako[-]" 
1014206-81 = "[fffbab]VS[-]" 
1014206-85 = "O saque inicial é da equipe adversária." 
1014206-86 = "Para ganharmos vantagem,\na primeira recepção é crucial." 
1014206-90 = "[wa:1451]― [log=나구사 수영복]Vamos começar com essa estratégia.[/log]" 
1014206-92 = "― [log=나구사 수영복]Afinal, elas provavelmente virão [wa:1690]com tudo desde o início.[/log]" 
1014206-95 = "[wa:3201]― [log=나구사 수영복]......[wa:1520]Sensei?[/log]" 
1014206-97 = "― [log=나구사 수영복]Você está [wa:1880]prestando atenção no meu sinal?[/log]" 
1014206-100 = "― [log=나구사 수영복]Olhar para o outro lado logo no começo [wa:2450]não é do seu feitio.[/log]" 
1014206-102 = "― [log=나구사 수영복]Para o que exatamente você está olhando...[/log]" 
1014206-105 = "[wa:4161]― [log=나구사 수영복]Ah... [wa:1800]Entendi.[/log]" 
1014206-107 = "― [log=나구사 수영복]Me desculpe.[/log]" 
1014206-110 = "― [log=나구사 수영복]Acho que assim você não vai conseguir se concentrar, né.[/log]" 
1014206-112 = "― [log=나구사 수영복]Como eu sou... [wa:1740]uma garota linda [wa:1240]e misteriosa.[/log]" 
1014206-115 = "[wa:2081]― [log=나구사 수영복]No vôlei de praia, é assim que se faz os sinais, mas...[/log]" 
1014206-117 = "― [log=나구사 수영복]Mesmo agora, [wa:1590]será que é melhor mudarmos o jeito de fazer?[/log]" 
1014206-120 = "[wa:2321]― [log=나구사 수영복]...Não vai dar, [wa:1970]já é tarde para isso.[/log]" 
1014206-123 = "[wa:691]― [log=나구사 수영복]Vamos continuar assim, [wa:1202]Sensei.[/log]" 
1014206-125 = "― [log=나구사 수영복]Nós vamos ficar... [wa:2490]bem.[/log]" 
1014206-128 = "（E assim, a partida começou.）\n" 
1014206-129 = "（Independente de ganharmos ou perdermos,\nfoi um momento muito divertido.）\n" 
1014206-138 = "（Com a partida encerrada...）" 
1014206-140 = "Ahahaha! Foi muito divertido mesmo!\n" 
1014206-141 = "Então, até a próxima! Continuem aproveitando\no tempo de vocês juntos~!\n" 
1014206-146 = "C-Continuar aproveitando o tempo juntos...\nO que será que ela quis dizer com isso?\n" 
1014206-147 = "[s5] \"Acho que o sentido literal?\"\n[s6] \"Significa para continuarmos nos divertindo juntos.\"" 
1014206-150 = "......" 
1014206-151 = "......Sim. Tem razão." 
1014206-152 = "Muita coisa aconteceu até agora." 
1014206-153 = "Se não fosse por você, Sensei, acho que meu braço\nainda estaria engolido por aquele crepúsculo escuro e sinistro." 
1014206-154 = "Graças a você, Sensei..." 
1014206-155 = "Eu aprendi a estender a mão para os outros." 
1014206-156 = "Eu aprendi... como devo seguir em frente." 
1014206-157 = "Mesmo que as coisas ainda não tenham\nvoltado totalmente ao normal..." 
1014206-158 = "Se você continuar ao meu lado,\nnão terei com o que me preocupar." 
1014206-159 = "......Ah." 
1014206-160 = "Falei demais." 
1014206-165 = "[ns] \"N-Nagusa...?\"" 
1014206-166 = "Já que eu falei até aqui, vou ser direta.\n" 
1014206-167 = "Ainda sou inexperiente, e..." 
1014206-168 = "Fora o fato de ser uma beldade,\nnão tenho nenhuma outra qualidade especial, mas..." 
1014206-169 = "Por favor, continue cuidando de mim\ndaqui pra frente, Sensei.\n" 
1014206-171 = "（Depois disso, me diverti na praia\ncom a Nagusa até tarde.）" 