[translation]
102070-1 = "第7話;「山海経」自治区防衛"
102070-6 = "う、うわああ！！化け物だ！！"
102070-11 = "敵がやってきたのだ！ "
102070-12 = "こちらは梅花園にお任せを！#nココナちゃんは市民の避難誘導をお願いします！"
102070-14 = "う、うん！分かった！シュン姉さん。"
102070-20 = "それじゃ、行こっかー！"
102070-22 = "ずいぶんと賑わっているのう。"
102070-27 = "き、キサキ会長……！？"
102070-31 = "仮にも門主じゃからな。山海経の危機を静観しているわけにもいかぬじゃろうて。"
102070-32 = "ああ、そうじゃ。守りが薄い場所に執行部長を送っておいた。好きに使うと良かろう。"
102070-33 = "門主様……ありがとうございます。"
102070-43 = "ふっ……まさに「友は近くに、敵はもっと近くに置け」――だな。"
102070-44 = "え？……いきなり何の話ですか？"
102070-45 = "どうせまた、何かの映画の受け売りでしょ。"
102070-46 = "やかましい！不朽の名作、「ゴッドマーザー」のセリフじゃい！"
102070-47 = "まったく……そら、行くぞ！門主様のご命令だ！"
