[translation]
102150-1 = "第15話;第4サンクトゥム「カタコンベ内バシリカ」"
102150-8 = "第4サンクトゥムに向かう道は、今のところ1つだけです。#n火力を集中させるのは容易ではないと思いますが……他に方法がありません。"
102150-10 = "大丈夫です、ハナコさんの指揮を信じております。"
102150-11 = "ええ。ハナコさん、どうぞ遠慮なく私たちにご命令を。"
102150-12 = "あらあら……♡マリーちゃんは悪気なくそんな言葉を使うから、#n余計ダメなんですよ。"
102150-16 = "ですが……この状況では後方の防衛が手薄に……"
102150-17 = "リスクを冒して進めるしか――"
102150-19 = "私たちに、手伝わせてもらえないだろうか。"
102150-27 = "……あなたは。"
102150-28 = "後方の防衛を任せてほしい。"
102150-30 = "……。"
102150-31 = "私たちの事は、あまり信用できないだろうが……それでも――"
102150-32 = "もちろんです、サオリさん。#n「スクワッド」には後方の防衛をお願いしますね。"
102150-33 = "……！"
102150-35 = "ほ、本当ですか？#nこんな簡単に信じていただいて良いのでしょうか……！？"
102150-36 = "……私たちが何者かは知ってるはずだけど……一体どういうつもり？"
102150-38 = "あなた達も「シャーレの先生」の要請を受けたから手伝ってくださるのでしょう？#nそれを私が断ることはできません……それに――"
102150-39 = "……私たちには、共通の大切な友人がいますから。"
102150-41 = "……。"
102150-42 = "あなた達を信用する理由は、それで十分です。"
102150-43 = "そうか……理解した。"
102150-44 = "……。"
102150-45 = "ですが、防衛だけをお願いするわけでは無いので、ご覚悟を。うふふっ♡"
102150-46 = "いったい何を……"
102150-47 = "は、はい！きっと、辛くて苦しいんでしょうけど……#n頑張ります……よろしくお願いします……！"
102150-52 = "みなさん、準備はできたようですね。"
102150-53 = "……ええっと、サクラコさんの姿が見えませんが……一体どちらに？"
102150-54 = "遅れて申し訳ありません。"
102150-62 = "さ、サクラコ様……？#nそ、その格好は……いったい……！？"
102150-63 = "……そ、その衣装は……"
102150-64 = "さ……サクラコさん！？"
102150-66 = "これは最後の聖徒会長が残した、ユスティナ聖徒会の礼装……"
102150-67 = "……ええ。これが私の覚悟です。"
102150-68 = "これまで続いてきた憎悪の連鎖を断ち切り、新しく――"
102150-69 = "――サクラコさん。"
102150-73 = "それが……「覚悟」なのですか！？"
102150-74 = "その、[ruby=・   ・   ・]破廉恥[/ruby]な衣装が！？"
102150-75 = "それが本当に！シスターフッドが引き継いだ、聖徒会の意志なのですか！？"
102150-76 = "その……つまり、これから、シスターのみなさんにその衣装を着用させるということなのでしょうか！？"
102150-78 = "そ、そう……なのですか！？ "
102150-79 = "わ、私は……そのような格好は……あう……。"
102150-80 = "え、ええっと、いったい何をおっしゃっているのか……！？"
102150-81 = "着るのにかなりの覚悟が必要とされる、#nギリギリラインのハイレグレオタードを……！？"
102150-82 = "歩くたびに後ろ姿が気になって仕方がないであろう、#n非合理的な布面積のデザインを……！？"
102150-83 = "それが本当に……サクラコさんの覚悟だとおっしゃるのですか！？"
102150-84 = "は、はい……？#nそ、それは……"
102150-85 = "サクラコさん、正直におっしゃってください。私すごく気になっているのです。中に下着は？いえ――よく考えれば、物理的に存在できない……なるほど。理解しました。"
102150-86 = "つまりサクラコさんは今――#nその薄い布一枚でここに居るということなのですね！！"
102150-87 = "い、いったい何をおっしゃっているのでしょうか！？"
102150-88 = "……。 "
102150-89 = "私たちの罪をお赦しください……"
102150-90 = "ええ……私、偉大なる意志の前に、またもや自身の至らなさを悟りました。"
102150-91 = "……サクラコさんの覚悟、しかと受け取りました。#n私もまた、至らなさゆえの覚悟を決めなくてはなりませんね……"
102150-97 = "……。"
102150-98 = "……。"
102150-99 = "……。"
102150-100 = "これで、全ての準備が整いました。"
102150-101 = "は、はいっ？じゅ、準備が整ったって……"
102150-102 = "では、これより第4サンクトゥムの攻略を開始します！！"
102150-103 = "ほ、本当にこのまま開始して良いのでしょうか……？"
