[translation]
102120-1 = "Episódio 12;3º Sanctum \"Parque de Diversões em Ruínas\""
102120-9 = "Vamos começar por aqui também. Estão prontas?"
102120-14 = "Sim! Pessoal, nos vemos na frente do chefe!"
102120-18 = "S-sim… tomem cuidado, Alice-chan…"
102120-19 = "Será que aquelas duas vão ficar bem sozinhas mesmo…?"
102120-20 = "…Sim, acredito que não haverá problemas."
102120-22 = "E-então…"
102120-23 = "Avant-Garde-kun… iniciar operação!"
102120-31 = "O que é AQUILO!?"
102120-32 = "Ele apareceu! É o Avant-Garde-kun, nosso novo aliado!!"
102120-38 = "Oooh! Então chegou a hora do Avant-Garde-kun Mk.3!"
102120-39 = "Aliás, o Mk.1 foi o modelo original criado pela presidente Rio, o Mk.2 foi modificado pela Veritas, e este Mk.3 aqui é nada menos que――#numa unidade exclusiva da Yuzu!"
102120-40 = "A grande característica do Avant-Garde-kun Mk.3 é o controle personalizado, criado especialmente para acompanhar a percepção absurda da Yuzu, permitindo comandos em nível de frame!"
102120-41 = "Exatamente! Essa é a máquina exclusiva da gamer suprema \"UZQueen\"!"
102120-42 = "Ééé…"
102120-43 = "Uuuh… a pressão tá… pesada…"
102120-52 = "Kotori! Já chega da explicação…#nPreciso que você analise os dados daqui!"
102120-56 = "A sensação dos controles é praticamente igual a um jogo de luta――ah, parece que alguém precisa das minhas explicações de novo! Então fico por aqui! Boa sorte, UZQueen!"
102120-61 = "…Então, vamos começar?"
102120-62 = "S-sim…!"
102120-67 = "A captura do 3º Sanctum…"
102120-76 = "vai começar…!!"