[translation]
102160-1 = "第16話;「ミレニアム」自治区防衛"
102160-2 = "さあ、私たちの番だよ。"
102160-4 = "はい！準備バッチリです！"
102160-5 = "ミレニアム自治区の防衛、私も手伝わせていただきます。 "
102160-7 = "はぁ……サンクトゥムの素材分析に、データ分析……#nその上、今度は防衛戦……体が10個あっても足りない……"
102160-14 = "おや、AMASが……？"
102160-16 = "私たちを手伝ってくれるのでしょうか？じゃあ、これはヴェリタスが……？"
102160-17 = "ん、違うよ。あれをハッキングできるのはヒマリ部長だけのはず……"
102160-18 = "おや、私でもありませんよ？"
102160-19 = "えっ、そ、それじゃあ一体誰が……#nま、まさか幽霊が動かして……！？"
102160-24 = "……。"
102160-25 = "……。"
102160-26 = "……まあ、いいんじゃないんでしょうか。人手はいつも足りてないですし。"
102160-27 = "……そうだね。じゃ、行こうか。"
102160-31 = "出発！"
