[translation]
102195-4 = "はっはっはっはっ！こちらも無事に片付いたな！"
102195-5 = "では、皆の衆！また機会があれば会いたいものだな！"
102195-6 = "回り続けるレールはやがて……正義の未来へと繋がる！"
102195-7 = "無限回転寿司戦隊・カイテンジャー！退場！"
102195-12 = "……。"
102195-13 = "彼女らは一体何者だったんだろう……。"
102195-15 = "こちら、処理完了しています。ヒマリ部長。"
102195-16 = "トキ……？"
102195-17 = "……あら早い。なかなか優秀ですね。#nそれでは、次の座標を指定しますので、そちらに移動していただけますか？"
102195-18 = "イエス、マム。"
102195-19 = "……トキ、大丈夫？無理してない？"
102195-20 = "心配してくださりありがとうございます、エイミ。私は大丈夫です。#nまだ「武装」のエネルギーも残っていますから。"
102195-22 = "トキ、「[ruby=Abi-Eshuh]アビ・エシュフ[/ruby]」の能力は……「名もなき神」の技術が一部反映されていると仮定しても、要塞都市「エリドゥ」があったからこそ発揮できたものです。"
102195-23 = "未知の領域が多い技術を制御すべく、都市一つをまるごと使用したからこそ、破壊的な性能を――いえ、悪趣味と言える性能を引き出せたのです。"
102195-24 = "それを用いて「名もなき神々の王女」と戦うというリオの計画も、決して無謀な話ではなかったのかもしれません……"
102195-25 = "ですが「エリドゥ」が解体されてしまった今、その「武装」に以前と同等の性能は期待できないでしょう。"
102195-26 = "今は平凡なスーツと考えるべきかと……いいですね？"
102195-27 = "……イエス、マム。"
102195-28 = "……いえ、平凡なスーツではありませんね。超天才ハッカーの私が手を加えたのですから……反則レベルとまではいかないものの、天才の息吹を感じられる……素晴らしいマスターピースと言えるでしょう。"
102195-29 = "はい。ありがとうございます、ヒマリ部長。"
102195-32 = "……トキ、私も手伝おうか？"
102195-33 = "大丈夫です、エイミ。一人で戦うのには慣れていますから。"
102195-38 = "目標地点に到着次第、再び連絡します。それでは。"
102195-42 = "なんか、寂しいね。"
102195-43 = "元々トキはC&Cですから。#nもしかしたら、エージェントと一緒に戦いたかったのかもしれません。"
102195-44 = "一緒に戦えばいいんじゃないの？"
102195-45 = "そうですね……自分にそんな資格は無い、と悩んでいるのかもしれません。"
102195-46 = "ん－……でも、トキは命令に従っただけだよ。"
102195-47 = "ええ。元凶はビッグシスターにあります。"
102195-48 = "……とはいえ、自分に全く非が無い、とも割り切れないのでしょう。"
102195-49 = "そっか……難しいね。"
102195-50 = "……ええ。不器用な人たちです。#nトキも、リオも。"
102195-55 = "次回;最終防衛戦「シャーレ」"
