[translation]
103160-1 = "Episódio 16; Contra-ataque"

103160-2 = "Depressa... volte logo."

103160-3 = "Por favor, se apresse!"

103160-4 = "……."

103160-8 = "……."

103160-9 = "Pessoal, se apressem...."

103160-10 = "……."

103160-12 = "Configuração da \"sequência de autodestruição\" concluída. Tudo que você precisa fazer é pressionar o botão Executar."

103160-13 = "Não há problemas com os resultados da simulação. #nCom isso, a \"Arca de Atla Hasith\" pode ser definitivamente destruída."

103160-14 = "Não vai haver uma grande explosão? #nFragmentos da Arca podem cair sobre Kivotos."

103160-16 = "...Os preparativos aqui estão completos. #nAvise-me quando estiver pronto para escapar."

103160-17 = "Espere um minuto! !"

103160-18 = "...Rio?"

103160-19 = "Algo está errado - deveríamos estar no controle da Arca agora..."

103160-20 = "...Himari! #nPor favor, dê uma olhada no sistema central de Utnapishtim agora mesmo."

103160-21 = "...Um sistema central?"

103160-25 = "……."

103160-26 = "...O que diabos é isso?"

103160-27 = "... Aconteceu."

103160-31 = "Com números como este... quem diabos... e quando..."

103160-32 = "O \"navio principal de Utnapishtim\" foi hackeado! !"

103160-34 = "O que é isso...? ?"

103160-35 = "Algo está errado...! #nPor que a \"sequência de autodestruição\" está começando agora...! ?"

103160-36 = "P-por que...? Você já apertou o botão? #nAcho que você ainda não terminou de se preparar para escapar! ?"

103160-37 = "Não, isso é...!"

103160-39 = "Execute a \"sequência de autodestruição\"."

103160-53 = "---! ? ! ?"

103160-55 = "foto……? “Sequência de autodestruição” ativada?"

103160-56 = "sim……? E agora...?"

103160-57 = "O que é isso...?"

103160-58 = "Todos, deitem-se! !"

103160-68 = "……."

103160-69 = "Por que diabos...?"

103160-70 = "O que está acontecendo...?"

103160-71 = "Isso é... a autodestruição da nave...? #n, por que...?"

103160-75 = "O que diabos está acontecendo...?"

103160-77 = "Geho, Geho... Estão todos bem...?"

103160-78 = "Ei, o que está acontecendo? ?"

103160-79 = "Ah...! !"

103160-80 = "Felizmente, a explosão não foi tão grande..."

103160-81 = "Este estado... está bem, certo?"

103160-84 = "Diretor Himari. Posso pedir-lhe que explique a situação atual?"

103160-85 = "...Fui derrotado."

103160-86 = "Eh, você foi atingido... o quê?"

103160-87 = "...Enquanto prosseguíamos com a ocupação da \"Arca de Atla Hasith\", o inimigo..."

103160-88 = "--- Ele estava ganhando o controle de \"Utnapishtim\" pela porta dos fundos."

103160-89 = "...O que! ?"

103160-92 = "...Atualmente, a propriedade do \"navio principal de Utnapishtim\" passou para o inimigo."

103160-93 = "Ah, antes que eu percebesse...! Na verdade, requer contato físico interno! ?"

103160-94 = "Não me lembro de ter deixado ninguém entrar..."

103160-105 = "Bem... eu nunca pensei que dessa vez..."

103160-106 = "Longe da autodestruição da Arca... o \"Navio Principal Utnapishtim\" ajudou na interpretação multidimensional da \"Arca Atra Hasith\"."

103160-107 = "Se as coisas continuarem assim, haverá outro “Santuário da Ilusão”..."

103160-113 = "……isso é."

103160-114 = "Ah, o céu...! ?"

103160-115 = "Mais uma vez... Santuário da Ilusão...! ?"

103160-127 = "O que...! ?"

103160-128 = "Bem, o céu de novo..."

103160-131 = "……."

103160-133 = "……."

103160-134 = "... Confirme a situação de emergência."

103160-141 = "……."

103160-142 = "professor……"

103160-144 = "Ah, o céu...! O que devemos fazer, Senpai? ?"

103160-145 = "Yuka-chan... Professora..."

103160-147 = "O céu..."

103160-148 = "Bem, algo deve ter acontecido com o professor..."

103160-149 = "Isso é..."

103160-153 = "……."

103160-160 = "Ei, Seia-san, Mika-san!"

103160-161 = "Você está atrasado, Nagi-chan. #n Seia-chan acabou de ir a algum lugar."

103160-162 = "...Hum?"

103160-163 = "Você disse que sentiu algum tipo de “presença” ameaçadora e queria se preparar para isso, certo?"

103160-164 = "--- \"Se acontecer alguma coisa enquanto eu não estiver aí, pedirei que você cuide de mim.\""

103160-165 = "Entendo... então vamos começar imediatamente."

103160-166 = "Sim. Entendido☆"

103160-167 = "Você ficará desapontado se seu professor não lidar bem com as coisas quando chegar em casa!"

103160-168 = "――É por isso que terei que me preocupar com o professor mais tarde."

103160-170 = "Oh, o céu-! ?"

103160-171 = "Hiyori, você não precisa dizer isso."

103160-172 = "O-O que você quer dizer, Misaki-san...tenho a impressão de que você só diz coisas negativas como \"minha vida acabou\" ou \"este mundo está cheio de dor\"...? Uh... não, é verdade, mas...!"

103160-174 = "...Vamos."

103160-175 = "Sim, não importa o que aconteça, você não deve parar de tentar."

103160-177 = "Sim... vamos!"

103160-178 = "……Sim. Vamos fazer o que pudermos."

103160-180 = "O controle atual de \"Utnapishtim\" foi entregue à outra parte..."

103160-181 = "No momento, estamos rastreando o local do hacker..."

103160-182 = "...Confirmação concluída. Esta é a parte central da 4ª área de ``A Arca de Atlas Hasith''."

103160-183 = "……foto? Esse é o nome do lugar?"

103160-184 = "Sala de Controle do Motor de Interpretação Multidimensional, ``Trono de Naram Singh'' --"

103160-185 = "Eles estão hackeando Utnapishtim daqui... Eu tenho que parar com isso! !"

103160-187 = "Estão todos bem?"

103160-188 = "Sim... está tudo bem. Não tenho nenhum ferimento específico, mas..."

103160-189 = "É disso que se trata, certo?"

103160-190 = "……."

103160-191 = "...Aquela \"Shiroko\" nos incomodava muitas vezes..."

103160-192 = "...Acho que você só queria ganhar algum tempo."

103160-193 = "Ah, é isso... Então, o que fizemos até agora..."

103160-195 = "A estratégia falhou... Todos os esforços até agora foram em vão..."

103160-196 = "Eca. Ainda não."

103160-197 = "Shiroko-senpai...?"

103160-199 = "[ns] \"Ainda é muito cedo para desistir.\""

103160-200 = "Bem, sensei... você está com Shiroko-senpai? #nPara que lado você está agora...! ?"

103160-209 = "sim. Meu professor e eu estamos indo para a área onde estão hackeando Utnapishtim, no centro da 4ª área."

103160-211 = "...Eh! ?"

103160-212 = "[s] \"Shiroko e eu tentaremos impedir a invasão. Por favor, cuide do resto.\""

103160-213 = "...! !"

103160-214 = "O que, hein! ?"

103160-215 = "...! !"

103160-216 = "……professor."

103160-224 = "A sala de controle apareceu."

103160-225 = "Depois de entrar, você será capaz de suprimir o inimigo."

103160-226 = "[s] \"...Ok, vamos!\""

103160-242 = "[ns] (Aqui...)"

103160-244 = "Inimigo descoberto."

103160-247 = "Aquele cara que me sequestrou...!"

103160-250 = "parar--! !"

103160-251 = "Se ele se mover um pouco... eu atiro! !"

103160-253 = "É melhor parar com sua fraca resistência."

103160-254 = "Aqui... tem um \"professor de placa de Petri\". #nEntão está tudo acabado agora."

103160-255 = "Eu silenciosamente me entreguei e imediatamente..."

103160-257 = "\"………….\""

103160-258 = "U-não se mexa...! Levante as mãos! !"

103160-260 = "Caso contrário... eu atiro em você."

103160-261 = "...e pare!"

103160-275 = "\"...desejamos os tempos de Jericó.\"#n\"...nos lembramos dos sete.\""

103160-280 = "Droga------! ?"

103160-292 = "As balas... todas erraram...?"

103160-293 = "A esta distância, por que...?"

103160-296 = "[ns1] (Isso é...)\n[ns2] (Se não me engano ---)"

103160-297 = "S-Sensei...?"

103160-298 = "S-Sensei...?"

103160-299 = "Professor... não, alguma coisa... alguma coisa não está certa."

103160-300 = "[s] \"...Shiroko, você deveria se afastar.\""

103160-301 = "foto……?"

103160-303 = "[USERNAME] Autenticação biométrica do professor concluída."

103160-304 = "[s3] \"Meu... nome?\"\n[s4] \"Você me ligou...?\""

103160-308 = "O administrador do sistema e principal sistema operacional residente nesta “Shittim Box” ――"

103160-315 = "--A.R.O.N.A, aguardando ordens."

103160-316 = "[s5] \"……………………\"\n[s6] \"…………...A...Rona?\""

103160-320 = "``A Arca de Atlas Hasith'' ativa o sistema de recuperação."

103160-321 = "Com a autoridade da “Arca de Shittim”, a destruída “Arca de Atla Hasith” será substituída e reparada pelo mesmo ser multidimensional."

103160-322 = "Após cerca de 30 minutos, espera-se uma recuperação de 100%."

103160-323 = "Após 800 segundos, a \"nave principal Utnapishtim\" que entrou na Arca entrou em sua sequência final de autodestruição."

103160-325 = "...É por isso que eu disse isso."

103160-330 = "Que você não pode mudar seu destino."

103160-334 = "Kivotos termina conforme planejado."

103160-337 = "Meu -- [NOME DE USUÁRIO] professor."

103160-339 = "Final.;Continua no Capítulo 4"

