[translation]
104060-1 = "Episódio 6; Em Pé de Igualdade"
104060-7 = "Analisando a situação... Confirmação da desconexão com a Utnapishtim. Tentando rota alternativa."
104060-11 = "……Tentativa falhou. O acesso à Utnapishtim está bloqueado. Impossível intervir."
104060-15 = "Confirmando que a supressão da 'interpretação multidimensional' foi mantida――Acelerando os cálculos e tentando destruição novamente."
104060-19 = "Aceleração de cálculos impossível. Confirmando processo de manifestação do Sanctum na superfície. Manifestação temporária confirmada."
104060-23 = "Dano no objeto temporário confirmado. Manifestação impossível."
104060-24 = "……Se continuar assim, o plano vai falhar."
104060-25 = "……。"
104060-36 = "……Confirmando status. Confirmação de que a 'Sequência de Autodestruição' da 'Arca de Atrahasis' está sendo preparada."
104060-37 = "Quando a sequência for ativada, a Arca entrará em processo de explosão e eliminação final. A função de 'interpretação multidimensional' será apagada permanentemente."
104060-38 = "……Tomando providências imediatamente――"
104060-42 = "――Cálculo impossível. Devido à falta de recursos, o processo de manifestação do Sanctum na superfície foi――"
104060-43 = "……Cancelado."
104060-51 = "A gente conseguiu... né?"
104060-52 = "Ei, o que vai acontecer agora~?#nIsso aqui vai explodir...?"
104060-53 = "Acho que é por aí, né?"
104060-58 = "……。"
104060-59 = "Ué, Fuuka-san?"
104060-64 = "Provavelmente a tensão passou... Bom trabalho, Fuuka-san."
104060-65 = "Então, os preparativos já terminaram, né?"
104060-66 = "Sim, teoricamente sim, mas..."
104060-67 = "Ufufu..."
104060-68 = "Ué, por que esse sorriso suspeito de novo..."
104060-70 = "Ah! A gente tem que ir salvar o Sensei!!"
104060-71 = "A-Ah é... o Sensei..."
104060-72 = "Isso aí. Um jantar completo só acaba quando a gente devora até o último prato."
104060-73 = "A batalha ainda não acabou.#nBora dar o toque final."
104060-74 = "A amizade é uma coisa linda mesmo, né★"
104060-75 = "Bom, eu já imaginava... não tem jeito, né."
104060-80 = "Vamos nessa!!"
104060-81 = "A Fuuka eu levo nas costas~! Vamo nessa~!!"
104060-83 = "A cor do céu mudou de novo...!"
104060-84 = "Finalmente conseguimos!#nA sequência de autodestruição da 'Arca' também começou."
104060-85 = "Então agora é só... pegar o Sensei e a Shiroko-chan e dar o fora daqui antes que exploda, né?"
104060-86 = "……Nós vamos até onde o Sensei tá!#nAyane-chan, pode ir na frente e fugir!"
104060-87 = "Não... Eu também vou fugir junto com o Sensei e as senpais!#nMe deixem ir com vocês."
104060-88 = "Mas..."
104060-89 = "Então, conto com você até o fim, Ayane-chan.#nA gente deixa você guiar o caminho."
104060-90 = "Sim! Então vamos logo!!"
104060-91 = "Vamos nessa!!"
104060-94 = "Vocês ouviram, né? Se apressem aí também!#nVamos usar a 'Sequência de Evacuação' que a Presidente Rio preparou!"
104060-95 = "Ué, peraí... Onde o Departamento de Desenvolvimento de Jogos tá agora?"
104060-96 = "No momento, estamos indo pro centro da Arca!"
104060-97 = "Isso aí! A gente tá indo salvar o Sensei!"
104060-98 = "Sim, é logo ali na frente...!!"
104060-99 = "E-A gente pode fugir a qualquer hora, então...!"
104060-100 = "Peraí!?"
104060-104 = "Aaaah, que saco... Já entendi!#nMas quando o Sensei voltar, a gente foge na mesma hora, hein!?"
104060-105 = "Sim! Pode deixar com a gente, Yuuka!"
104060-110 = "O céu..."
104060-111 = "Tá vendo? Até que foi de boa, né?"
104060-112 = "Sim. Confirmamos o desaparecimento do 'Sanctum da Falsidade' que havia surgido."
104060-113 = "A limpeza já acabou e a gente já despachou a Toki-chan, o que mais a gente faz~?"
104060-114 = "Ué, só tem uma coisa pra fazer, né?"
104060-117 = "Esperar o Sensei voltar."
104060-118 = "……Uhum! Se for isso, eu garanto que sou boa~!"
104060-119 = "Mas a situação ainda não permite que a gente baixe a guarda...#nTemos que ficar de olho nas outras regiões também."
104060-120 = "É, tem razão. Mas, com certeza vai dar tudo certo."
104060-122 = "Aviso. A 'Sequência de Autodestruição' da 'Arca de Atrahasis' está em andamento. Se a sequência for ativada, a probabilidade de sobrevivência a bordo após a explosão é inferior a 0,0003%."
104060-123 = "Sunaookami Shiroko, Sunaookami Shiroko, Sensei [USERNAME]. Previsão de óbito de todos os indivíduos. Necessário criar uma contramedida com urgência――"
104060-127 = "……Entendi."
104060-128 = "Então... era só pra ganhar tempo.#n――Eles confiaram que vocês iam conseguir."
104060-129 = "[s] \"Porque eu confio em todo mundo.\""
104060-133 = "É verdade――Não importa se eu não ganhar."
104060-134 = "Desde que [ruby=・]t[/ruby][ruby=・]o[/ruby][ruby=・]d[/ruby][ruby=・]a[/ruby][ruby=・]s[/ruby] nós ganhemos juntas, tá valendo."
104060-135 = "Todas juntas, né..."
104060-136 = "[s] \"Uhum. Logo, logo, todo mundo vai chegar.\""
104060-137 = "O Comitê de Medidas de Precaução――e a 'Schale'."
104060-141 = "[ns] \"Eu vou te impedir até elas chegarem. ――Tem uma coisa que eu preciso te falar.\""
104060-142 = "Uma coisa que precisa me falar..."
104060-143 = "Criando contramedida. Existe uma solução. A partir de agora, por uma rota alternativa, a Utnapishtim será――"
104060-144 = "……Não, não precisa."
104060-148 = "Se a gente tentar, só vai dar no mesmo resultado. #nO Sensei com certeza vai dar um jeito de superar isso de novo."
104060-149 = "Juntar forças com todo mundo pra enfrentar os problemas――Isso sim é uma verdadeira ameaça."
104060-150 = "Porque é assim que o Sensei――tem feito milagres até hoje."
104060-156 = "Então, a gente só precisa se livrar do 'Sensei' primeiro."
104060-157 = "Se a gente fizer isso, a autodestruição da Arca, a manifestação dos Sanctums...#ndá pra refazer quantas vezes a gente quiser."
104060-158 = "Se o [ruby=・]S[/ruby][ruby=・]e[/ruby][ruby=・]n[/ruby][ruby=・]s[/ruby][ruby=・]e[/ruby][ruby=・]i[/ruby] não estiver aqui."
104060-159 = "Isso mesmo. Se o Sensei não estiver aqui... tudo vai desmoronar."
104060-160 = "Por isso, nós vamos usar todas as nossas forças."
104060-166 = "……Instrução confirmada. Interrompendo suporte de cálculos da 'Arca de Shittim'.#nMudando para o modo de suporte de combate."
104060-172 = "[ns] \"O lugar... mudou?\""
104060-173 = "A partir de agora, vou direcionar todas as minhas habilidades para o suporte de combate."
104060-174 = "[s1] \"Eu também tenho a superpoderosa Arona-chan comigo!!\"\n[s2] \"Arona--!!\""
104060-177 = "Sim!! A partir de agora a Super Arona vai te ajudar, Sensei!!"
104060-178 = "Não importa quem seja, a Arona aqui não vai perdoar quem tentar fazer mal pro Sensei [USERNAME]!"
104060-179 = "Aham, não vou deixar que machuquem o Sensei."
104060-180 = "……Entendi. Acho que vocês duas sentem a mesma coisa."
104060-181 = "Mas, Sensei. Não ache que estamos em pé de igualdade.#nAs batalhas pelas quais eu passei são de uma escala totalmente diferente das suas."
104060-182 = "Mesmo que as 'Arcas de Shittim' tenham o mesmo poder, a diferença de experiência é insuperável."
104060-183 = "[ns3] \"…………。\"\n[ns4] Tiro o cartão de adulto."
104060-187 = "……Ah é, o Sensei tinha isso, né."
104060-188 = "É verdade, com isso, você pode ignorar todas as nossas cartas na manga e garantir a vitória."
104060-189 = "Mas... você não se esqueceu, não é, Sensei?"
104060-190 = "De [ruby=・]q[/ruby][ruby=・]u[/ruby][ruby=・]e[/ruby][ruby=・]m[/ruby] é o Phrenapates que está na sua frente."
104060-199 = "S-Sensei...!? O-O Phrenapates também tirou alguma coisa...!!"
104060-200 = "A-Aquilo é...!!?"
104060-203 = "……!?"
104060-204 = "[ns] \"......................!!\""
104060-205 = "'Cartão de adulto' contra 'cartão de adulto'..."
104060-206 = "Nesse caso, qual dos dois 'cartões' vai ganhar?"
104060-208 = "Próximo episódio; Mesma Situação, Mesma Escolha"