[translation]
11001-2 = "Por alguma razão, sinto que as batalhas foram mais fáceis que o normal..."
11001-3 = "... Acho que sim, certo?"
11001-4 = "Graças à orientação do Sensei, a luta foi muito mais fácil que o normal."
11001-5 = "Entendo... esse é o poder de um sensei...#nBem, é natural já que ele foi escolhido pelo Presidente do Conselho Estudantil da Federação..."
11001-7 = "Pois bem, estou ansioso pela sua próxima batalha, Sensei."
