[translation]
11008-3 = "None"

11008-5 = "None"

11008-7 = "None"

11008-9 = "Conectando-se à [FF6666]Caixa de Shittim...[-]"

11008-12 = "Por favor, digite sua senha de conexão do sistema."

11008-14 = "[ns] \"......A senha é......\""

11008-16 = "[ns] Digite a frase que lhe vier à mente."

11008-18 = "[FF6666]...Desejamos sete [-][ruby=nage][FF6666] lamento[-][/ruby][FF6666] desejos. [-]"

11008-20 = "[FF6666]...Lembramos a [-][ruby=koku][FF6666]velha regra[-][/ruby][FF6666] de Jericho. [-]"

11008-23 = "……."

11008-25 = "Aprovação da senha de conexão. #nAs informações de conexão atuais são [NOME DE USUÁRIO] e foram confirmadas."

11008-28 = "Bem-vindo à "Caixa de Shittim", Sr. [NOME DE USUÁRIO]."

11008-29 = "Converta para o sistema operacional principal A.R.O.N.A para autenticação biométrica e geração de certificados."

11008-35 = "? ? ?"

11008-36 = "(Numa sala de aula que nunca vi antes, uma menina cochila de bruços sobre uma mesa.)"

11008-37 = "Kuuuuuu...Zzzz"

11008-38 = "Kuuuuuu...Zzzz"

11008-39 = "Hmmm, para castella... prefiro leite de banana ao invés de leite de morango..."

11008-40 = "Kuuuuu...Zzzzzzz"

11008-43 = "Hehe... ainda tem muito mais..."

11008-44 = "[s1] Acorde sacudindo-o. \n[s2] Tente cutucá-lo na bochecha."

11008-45 = "(coisa grande balançando)"

11008-46 = "Eca..."

11008-47 = "... Ei... ei! ?"

11008-48 = "(Gatat)"

11008-49 = "(Tsun)"

11008-50 = "Unya... ainda não... tenho que mastigar direito..."

11008-52 = "(Tsun-tsun)"

11008-53 = "Ah, mas..."

11008-56 = "(Tsun-tsun-tsun)"

11008-57 = "...Uuuun."

11008-58 = "(Gatat)"

11008-60 = "(mukuri)"

11008-61 = "Mmm... Hmmm... Isso é verdade?"

11008-62 = "Sim, sim...?"

11008-63 = "foto? Huh? É isso?"

11008-64 = "Ei, professor! ?"

11008-65 = "O fato de você ter entrado neste espaço significa, tudo bem, de jeito nenhum, Sr. [NOME DE USUÁRIO]...? !"

11008-66 = "[s3] \"Sim.\"\n[s4] \"Quem é você?\""

11008-67 = "Uau! ? Ah, isso mesmo! ? Já faz tanto tempo! ?"

11008-68 = "Uau! ? Ah, isso mesmo! ? Já faz tanto tempo! ?"

11008-69 = "Uau, uau? Calma, calma...."

11008-70 = "Hum... hum... ah, isso mesmo! Primeiro, vamos nos apresentar!"

11008-71 = "Eu sou Alona!"

11008-72 = "Ela é a administradora do sistema, o sistema operacional principal e a secretária que estará auxiliando o professor nesta "Caixa do Merda"!"

11008-73 = "やっと会うことができました！ Faz muito tempo que estou esperando por você aqui!"

11008-74 = "[s] \"Você não estava dormindo?\""

11008-75 = "Ah, tudo bem... mas é claro que às vezes eu cochilo..."

11008-76 = "[s] \"Prazer em conhecê-lo.\""

11008-77 = "sim! obrigado!"

11008-78 = "Meu corpo ainda está em um nível baixo e preciso fazer ajustes principalmente nas cordas vocais..."

11008-79 = "De agora em diante, farei o meu melhor para apoiá-lo de várias maneiras!"

11008-80 = "Ah, isso mesmo! Primeiramente, embora seja uma formalidade, realizaremos autenticação biométrica♪"

11008-81 = "Ugh... é um pouco constrangedor, mas não tem jeito, já que é uma formalidade. Por favor, venha por aqui."

11008-84 = "Quase lá."

11008-88 = "Agora, por favor, coloque seu dedo no meu dedo."

11008-92 = "Hehehe. É como cortar o dedo e fazer uma promessa, não é?"

11008-93 = "sim? Parece uma cena de um filme alienígena?"

11008-94 = "Na verdade, é assim que verificamos as impressões digitais biométricas!"

11008-95 = "Verifico visualmente as impressões digitais deixadas na tela... mas logo acaba! #nMesmo parecendo assim, meus olhos estão bons."

11008-98 = "vamos ver……."

11008-99 = "Eca..."

11008-100 = "(Hmm...talvez eu não consiga ver bem...)"

11008-101 = "(...Bem, está tudo bem?)"

11008-103 = "……sim! Confirmação concluída ♪"

11008-104 = "foto? Você quer falar sério? Então, parece que estou cortando atalhos? #nHum... isso não é verdade!"

11008-105 = "……."

11008-106 = "É verdade que as máquinas modernas só fazem reconhecimento automático de impressões digitais? Espere, leva menos de um segundo? #nUau, não tenho esses recursos de ponta..."

11008-107 = "Bom, mesmo que você não tenha essa habilidade, Alona será útil! ? Você pode verificar com seus olhos!"

11008-108 = "...Parece que você não acredita em nada..."

11008-109 = "……."

11008-110 = "Eca..."

11008-111 = "(Urrr)"

11008-112 = "Nesse caso, por que não procurar o Sr. Nantoka que está na vanguarda!"

11008-113 = "[s] Eu a consolei dizendo que era uma piada."

11008-114 = "Chato...."

11008-116 = "(eu te consolei muito)"

11008-118 = "……."

11008-119 = "Entendo... entendo a situação do professor."

11008-120 = "O Presidente do Conselho Estudantil da Federação desapareceu e, por causa disso, não há como controlar a Torre Kivotos..."

11008-121 = "[s5] \"Você sabe sobre o Presidente do Conselho Estudantil da Federação?\"\n[s6] \"Quem é o Presidente do Conselho Estudantil da Federação?\""

11008-122 = "Conheço muitas informações sobre Kivotos, mas sei muito pouco sobre o Presidente do Conselho Estudantil da Federação. #nEu me pergunto quem ela é e por que desapareceu..."

11008-123 = "Conheço muitas informações sobre Kivotos, mas sei muito pouco sobre o Presidente do Conselho Estudantil da Federação. #nEu me pergunto quem ela é e por que desapareceu..."

11008-124 = "Desculpe, não posso ajudá-lo."

11008-125 = "...No entanto, parece que posso de alguma forma resolver o problema da Torre Sanctum."

11008-126 = "[s] \"Então, por favor, Alona.\""

11008-127 = "sim! Entendido. Agora vamos reparar os direitos de acesso à Torre Sanctum!"

11008-128 = "por favor espere um momento!"

11008-130 = "(Wiiiiiiin――――)"

11008-138 = "……."

11008-139 = "サンクトゥムタワーのadmin権限を取得完了……。"

11008-140 = "professor. Recuperamos com sucesso o controle da Torre Sanctum. #nSanctum Tower agora está sob meu controle, Alona."

11008-141 = "Kivotos está agora sob o controle do Sensei!"

11008-142 = "Se o professor aprovar, o controle da Torre Sanctum pode ser transferido para o Conselho Estudantil da Federação."

11008-143 = "Mas... você está bem? Mesmo que o controle seja entregue ao Conselho Estudantil da Federação..."

11008-144 = "[s7] \"Ok.\"\n[s8] \"Aprovar.\""

11008-145 = "Entendido. De agora em diante, o controle da Torre Sanctum será transferido para o Conselho Estudantil da Federação!"

11008-146 = "Entendido. De agora em diante, o controle da Torre Sanctum será transferido para o Conselho Estudantil da Federação!"

11008-148 = "……sim. Entendido."

11008-149 = "(clique) Confirmamos que temos o controle da Torre Sanctum."

11008-150 = "A partir de agora, a gestão administrativa prosseguirá da mesma forma que quando existia um Presidente do Conselho Estudantil da Federação."

11008-151 = "Obrigado pelo seu trabalho duro, professor. #nEm nome do Conselho Estudantil da Federação, gostaria de expressar minha mais profunda gratidão por evitar o caos em Kivotos."

11008-152 = "Não se preocupe, iremos rastrear e subjugar os delinquentes que atacaram este lugar e os alunos que foram suspensos da escola."

11008-153 = "Pois bem, eu lhe dei a “Caixa de Shittim” e parece que meu papel acabou."

11008-154 = "...Ah, tem mais uma coisa."

11008-155 = "Por favor, siga-me. Gostaríamos de apresentar a você a "Placa de Petri" do Departamento de Investigação Federal."

11008-158 = "Este é o lobby principal da placa de Petri."

11008-159 = "Já faz muito tempo que está vazio, mas finalmente chegou a hora de receber seu marido."

11008-160 = "(bater palmas, bater palmas)"

11008-164 = "E esta é a sala do clube da placa de Petri."

11008-165 = "Este é um bom lugar para começar sua carreira como professor."

11008-166 = "[s] \"O que devo fazer agora?\""

11008-167 = "...A placa de Petri é uma organização que tem autoridade, mas não tem objetivos, portanto não há compulsão para fazer nada em particular."

11008-168 = "Eles podem entrar e sair livremente de qualquer distrito autônomo de qualquer escola em Kivotos, e os professores podem ter qualquer aluno que desejarem como membros, independentemente de sua afiliação..."

11008-169 = "É interessante, não é? #nEmbora seja chamado de Departamento de Investigação, o Presidente do Conselho Estudantil da Federação não mencionou especificamente essa parte."

11008-170 = "Em outras palavras, você pode fazer o que o professor quiser..."

11008-171 = "……."

11008-172 = "...Mesmo se eu quisesse perguntar a ele, o Presidente do Conselho Estudantil da Federação continua desaparecido."

11008-173 = "Estamos fazendo tudo o que podemos para encontrá-la, por isso não temos recursos para lidar com os problemas que surgem em torno de Kivotos."

11008-174 = "Mesmo agora, o Conselho Estudantil da Federação continua recebendo todo tipo de reclamações... #nPedidos de suprimentos de ajuda, melhorias ambientais, aulas especiais para alunos reprovados, pedidos de apoio do clube, etc..."

11008-175 = "...Talvez, se você tiver uma ``placa de Petri'' com bastante tempo, você poderá resolver essas reclamações incômodas."

11008-176 = "Deixei muitos documentos relacionados a isso na mesa do professor. Por favor, leia se você quiser."

11008-177 = "Tudo fica a critério do professor."

11008-178 = "Então não tenha pressa. Entraremos em contato novamente quando necessário."

11008-181 = "Sim. Confirmei que o Conselho Estudantil da Federação recuperou o controle da Torre Sanctum."

11008-182 = "ワカモは自治区に逃げてしまったのですけど……すぐ捕まるでしょう。私たちはここまで。"

11008-183 = "Deixo o resto para o responsável."

11008-184 = "Obrigado pelo seu trabalho duro, professor. O trabalho do Sensei se espalhará por Kivotos. Pode se tornar um tema quente no SNS imediatamente, certo?"

11008-185 = "[s] \"Obrigado a todos pelo seu trabalho duro.\""

11008-186 = "Isto é uma despedida, mas por favor, passe por Trinity Sogo Gakuen em um futuro próximo. professor."

11008-188 = "(Pekori)"

11008-189 = "Também voltarei a reportar hoje ao Presidente do Comitê de Disciplina. Por favor, venha nos visitar quando vier à Gehenna Academy."

11008-190 = "Se você vier para a Millennium Science School, talvez possamos nos encontrar novamente? Sensei, até breve!"

11008-192 = "[ns] Volte ao escritório de Petri."

11008-194 = "……."

11008-195 = "Ah... isso é um problema..."

11008-196 = "フフ……フフフ。"

11008-198 = "...Ufufufufufufu♡"

11008-200 = "Haha... parecia um pouco agitado, mas...#nParece que as coisas se acalmaram até certo ponto. obrigado pelo seu trabalho duro."

11008-201 = "[s] \"Obrigado pelo seu trabalho duro, Arona.\""

11008-202 = "sim! Mas o verdadeiro problema começa agora, certo?"

11008-203 = "A partir de agora, junto com o professor, resolveremos os problemas que os alunos do Kivotos estão enfrentando...!"

11008-204 = "Embora possa parecer simples, não é nada fácil... é muito importante."

11008-205 = "Muito obrigado pelos seus Kivotos e placa de Petri, Professor."

11008-206 = "[s9] \"Prazer em conhecê-la, Alona.\"\n[s10] \"Bem-vindo.\""

11008-207 = "Agora vamos começar nossa primeira missão oficial como “Placa de Petri” do Departamento de Investigação Federal!"

11008-208 = "Agora vamos começar nossa primeira missão oficial como “Placa de Petri” do Departamento de Investigação Federal!"

