[translation]
1101-1 = "Cotidiano do Grupo de Pesquisa Gourmet (1)"
1101-2 = "Gehenna, em algum lugar nos subúrbios"
1101-4 = "Haa, haa... #n Ele não virá mais atrás de você, certo?"
1101-5 = "Parece tudo bem. Não importa quão persistente seja o Presidente do Comitê de Disciplina, ele provavelmente não será capaz de acompanhá-lo até aqui."
1101-6 = "Hmm... parece que o comitê disciplinar da #n Gehenna tem muito tempo livre para fazer barulho em uma daquelas cafeterias estudantis pouco apetitosas."
1101-7 = "Não... esse é o trabalho de um comitê disciplinar em primeiro lugar..."
1101-8 = "Junko-san, por exemplo. Como você se sentiria se deixasse água correndo em uma pia que ninguém usa?"
1101-9 = "Hmm... você acha que eu deveria fechar a torneira?"
1101-10 = "Sim, está certo. #nQuando vejo um restaurante que serve comida desagradável, tenho essa vontade."
1101-11 = "...Não preciso mais explicar. #nEu não sei de qualquer maneira."
1101-12 = "A propósito, não consigo encontrar Izumi há algum tempo. #nVocê não estava me seguindo?"
1101-13 = "Izumi desistiu há muito tempo. #nTenho certeza que Hina-san já deve ter pego você."
1101-14 = "Sim, isso é mentira! ? Por que você está dizendo algo tão importante agora? ?"
1101-15 = "Porque não havia necessidade de dizer isso. #nIzumi nos deixou algo quando foi eliminada. Um grito sincero e apaixonado."
1101-16 = "O grito da alma? #nBem, de jeito nenhum...! Para nós..."
1101-17 = "...É assim mesmo? Seu sacrifício não será esquecido. #nO que Izumi ainda tinha a dizer?"
1101-20 = "Ei, ei! espere! ! #nEspere, sem sangue ou lágrimas! ? Não me deixe para trás!"
1101-21 = "Huh! ? (calúnia)"
1101-23 = "(Baque!!!)"
1101-24 = "Não me deixe para trás! Uau! #nLembre-se! Mesmo se eu morrer, vou me vingar! !"
1101-26 = "Parece..."
1101-27 = "……."
1101-28 = "……."
1101-29 = "Hehehe☆"
1101-32 = "Kun-kun... hein? Tem um cheiro delicioso."
1101-34 = "Em um parque como este?"
1101-35 = "Tem um cheiro único... cheire, aqui está!"
1101-37 = "(gaguejar)"
1101-39 = "(estrondo)"
1101-40 = "te peguei! É o cheiro deste cogumelo!"
1101-41 = "Ah, isso é..."
1101-42 = "Trufas...! Isto é uma trufa!"
1101-43 = "Trufas...?"
1101-44 = "É um cogumelo muito valioso que também é chamado de diamante negro...!"
1101-46 = "Seu valor de raridade é superior ao do atum dourado, que é chamado de atum fantasma!"
1101-47 = "Ei! ? então! ?"
1101-48 = "Em particular, este perfume rico e único só pode ser sentido quando recém colhido."
1101-49 = "Você tem sorte de gostar desse perfume."
1101-50 = "Eu também ouvi isso. É um ingrediente extremamente raro que só pode ser descoberto pelo olfato de uma porca faminta!"
1101-51 = "Como esperado de Junko-san, você tem um talento incrível."
1101-52 = "Você acabou de postar uma palavra estranha sob o pretexto de um elogio. Você quer morrer? #nVou enterrar você em vez de trufas, ok?"
1101-54 = "Este não é o momento para fazer isso. #nAs trufas devem ser preparadas em até 5 minutos após serem colhidas. #nPara manter esse frescor..."
1101-55 = "Você precisará de um pano limpo."
1101-56 = "Não, não... tenho corrido numa estrada cheia de terra como esta, não tenho como encontrar um pano limpo. #nTodo mundo está coberto de lama..."
1101-57 = "Se sim, que tal isso?"
1101-58 = "um pouco! ! Isso é roupa íntima! ! !"
1101-59 = "É novo e ainda não foi aberto? Além disso, é feito 100% de seda de alta qualidade, por isso pode parecer um pouco estranho, mas é essencialmente o mesmo que um lenço limpo."
1101-60 = "Bem, isso é verdade, mas.... #nMas Presidente, está tudo bem?"
1101-61 = "Sem problemas. Não, eu diria que foi realmente bom. #nNão posso acreditar que a limpeza de Akari será útil em momentos como este."
1101-62 = "(ssssssssss...)"
1101-63 = "Agora, tudo bem. #nAgora só me resta voltar e cozinhar esta trufa...! !"
1101-64 = "……."
1101-65 = "Não, antes disso... eu tenho que resgatar Izumi de seu prisioneiro. #nPara desfrutar de ingredientes tão preciosos, até mesmo um membro da pesquisa deve estar presente."
1101-66 = "Como esperado do presidente! É isso mesmo, tenho que voltar e explodir os membros do comitê disciplinar e salvar Izumi também! !"
1101-67 = "Amor e Violência☆#nÉ amizade entre garotas!"
1101-70 = "Quem sopra quem?"
1101-71 = "Ei, ei! ! ? ? Comitê de disciplina! Antes que eu percebesse! ?"
1101-75 = "(Zaza…)"
1101-77 = "Ah... estou cercado."
1101-78 = "Suspiro, fugir é muito incômodo. Livre-se de todos--"
1101-79 = "(Mandril!)"
1101-81 = "...Não, vai ser problemático, então vou deixar isso com hálito de inseto."
1101-83 = "(Kokuri)"
1101-84 = "Todos, por favor, não resistam em vão."
1101-87 = "(Tatatatatatatatatan!!)"
1101-89 = "(Ele foi preso depois disso)"
