[translation]
11070-2 = "第7話;新たなる脅威？"
11070-3 = "対策委員会・教室"
11070-4 = "みなさん、お疲れ様です。"
11070-5 = "セリカちゃん、ケガはない？"
11070-6 = "うん、私は大丈夫。見てよ、ピンピンして……"
11070-7 = "（ぐらっ……）"
11070-8 = ""
11070-9 = "（バタンッ）"
11070-10 = "セリカちゃん！"
11070-11 = "私が保健室に連れていく。"
11070-12 = ""
11070-15 = "Flak41の対空砲を食らったんだもん、歩けるほうがおかしいって。ゆっくり休ませてあげよー。"
11070-16 = "大変なことになるところでした。先生がいなかったら……。"
11070-17 = "うんうん。先生のおかげでセリカちゃんの居場所を逃さず追跡できました。やっぱりすごいです☆"
11070-18 = "確かに、ただのストーカーじゃなかったってことだね。"
11070-19 = "……それと、皆さんこれを見てください。"
11070-20 = "戦闘中に回収した、散らばった戦車の部品を確認したところ、キヴォトスでは使用が禁止されている違法機種と判明しました。"
11070-21 = "もう少し調べる必要はありますが……ヘルメット団は、自分たちでは入手できない武器まで保有しているそうです。"
11070-22 = "この部品の流通ルートを分析すれば、ヘルメット団の裏にいる存在を探し出せますね！"
11070-23 = "はい。ただのチンピラが、なぜここまで執拗に私たちの学校を狙っているのかも、明らかになるかもしれません。"
11070-24 = "うん、わかった。じっくり調べてみよっかー。"
11070-25 = ""
11070-26 = "高層オフィスビル"
11070-27 = "……。"
11070-28 = "……格下のチンピラごときでは、あの程度が限界か。#n主力戦車まで送り出したというのに、このザマとは。"
11070-29 = "ふむ……となると、目には目を、生徒には生徒を……か。#n専門家に依頼するとしよう。"
11070-30 = ""
11070-31 = "（プルルル、プルルル）"
11070-32 = "（ガチャ）"
11070-33 = "はい、どんなことでも解決します。便利屋68です。"
11070-34 = "仕事を頼みたい、便利屋。"
11070-35 = "……"
11070-37 = "カタカタヘルメット団のアジト"
11070-38 = ""
11070-39 = ""
11070-40 = "はあ……はあ……。"
11070-41 = "うわああっ！！"
11070-42 = "（タタタタタタタタンッ！！）"
11070-43 = "ぐうっ！！"
11070-44 = "！"
11070-45 = ""
11070-46 = "（バタッ）"
11070-47 = "あーあー、こっちは終わったよー。"
11070-48 = "こっちも制圧完了だ、ボス。"
11070-50 = "う、うう……何者だ、貴様らは……。"
11070-51 = "……ふふふ。"
11070-52 = ""
11070-53 = "（グリッ）"
11070-54 = ""
11070-55 = "うあああっ！！ま、まさか、アビドスの！？よくも我々を……。"
11070-56 = "はあ、こんな不潔で変な匂いのする場所がアジトだなんて。#nあなたたちも冴えないわね。"
11070-57 = "……いいわ。あなたたちを、労働から解放してあげる。"
11070-58 = "なっ、何だって！？"
11070-59 = "要するにクビってこと。現時刻をもって、アビドスは私たちが引き受けるわ。"
11070-60 = "ふっ、ふざけた真似を！貴様らは一体……。"
11070-61 = ""
11070-62 = "（ガツッ！！）"
11070-63 = "うわああっ！！"
11070-64 = "……"
11070-67 = "……"
11070-68 = "私たちは、[ruby=シックスティーエイト]便利屋68。       [/ruby]"
11070-69 = "金さえもらえれば、何でもする……。"
11070-72 = "なんでも屋よ。"
11070-74 = "（ガラッ）"
11070-75 = "はあ……。"
11070-76 = "あ、れ……？先生！？ど、どうしたの？"
11070-77 = "[s] \"お見舞いに来たよ。\""
11070-78 = "……ああ、私なら大丈夫。いつまでもこうしちゃいられないし。"
11070-79 = "アヤネちゃんや他のみんなも心配してるし……バイトにも行かなきゃだし。"
11070-80 = "だ、だから、お見舞いとかいいから！ほら見て、元気だし。"
11070-81 = "[s] \"それは良かった。\""
11070-82 = "……。"
11070-83 = "あ、あの！！"
11070-84 = "……え、ええとね……。"
11070-85 = "そういえば、先生にちゃんとお礼を言ってなかったなあって、思って……。"
11070-86 = "あ、ありがとう……色々と……。"
11070-87 = "……でもっ！この程度でアビドスの役に立てたなんて思わないでよね！#nこの借りはいつか必ず返すんだから！"
11070-88 = "……。"
11070-89 = "な、何よ！？何ヘラヘラ笑ってんの！？"
11070-90 = "はあ、まったく。"
11070-91 = "じゃあ……また明日ね！"
11070-92 = "えっと、せ……"
11070-93 = "……先生。"
11070-94 = ""
11070-97 = "次回;便利屋参上！"
