[translation]
11090-2 = "第9話;恩知らずの血戦"
11090-3 = "それじゃあ、気を付けてね！"
11090-4 = "お仕事、上手くいきますように！"
11090-5 = "あははっ！了解！あなたたちも学校の復興、頑張ってね！私も応援してるから！"
11090-6 = "じゃあね！"
11090-9 = "ふう……いい人たちだったわね。"
11090-10 = "……。"
11090-11 = "……。"
11090-12 = "社長。#n……あの子たちの制服、気づいた？"
11090-13 = "えっ？制服？何が？"
11090-14 = "アビドスだよ、あいつら。"
11090-16 = "なななな、なっ、何ですってーーーーーー！！！？？？"
11090-18 = "あはははは、その反応うけるー。"
11090-19 = "はあ……本当に全然気づいてなかったのか……。"
11090-20 = "えっ？そ、それって私たちのターゲットってことですよね？わ、私が始末してきましょうかっ！？"
11090-21 = "あははは、遅い、遅い。#nどうせもうちょっとしたら攻撃を仕掛けるんだし、その時暴れよっ、ハルカちゃん。"
11090-22 = "う、うそでしょ……あの子たちが？アビドスだなんて……#nう、うう……何という運命のいたずら……。"
11090-23 = "何してんの、アルちゃん。仕事するよ？"
11090-24 = "バイトのみんなが、命令が下るのを待ってる。"
11090-25 = "本当に……？私、今から……あの子たちを……。"
11090-26 = "あはは、心優しいアルちゃんに、この状況はちょっとキツいねー。"
11090-27 = "「情け無用」「お金さえもらえればなんでもやります」がうちのモットーでしょ？#n今更何を悩んでるの？"
11090-28 = "そ、そうだけど……。"
11090-29 = "（これ、完全に参ってるね……）"
11090-30 = "こ、このままじゃダメよ、アル！一企業の長として、このままじゃ！"
11090-32 = "行くわよ！バイトを集めて！"
11090-38 = "なんだよ～、遅かったじゃん。"
11090-39 = "少し野暮用よ。準備はできてるわね？"
11090-40 = "もちろん。何でもいいけど、残業はナシでね。時給も値切られてるし。"
11090-41 = "細かいことは今は置いておいて！#nさあ、行きましょう！アビドスを襲撃するわよ！"
11090-43 = "出動～！"
11090-44 = "はあ……。"
11090-45 = "アル様！わっ、私、頑張りますから！"
11090-47 = "ひとり残らず、ぶっ潰しちゃいますっ！"
11090-49 = "校舎より南15㎞地点付近で大規模な兵力を確認！"
11090-50 = "まさか、ヘルメット団が？"
11090-51 = "ち、違います！ヘルメット団ではありません！"
11090-52 = "……傭兵です！おそらく日雇いの傭兵！"
11090-53 = "へえー、傭兵かあ。結構高いはずだけど。"
11090-54 = "これ以上接近されるのは危険です！#n先生、出動命令を！"
11090-55 = "[s]\"出動だー！\""
11090-57 = "前方に傭兵を率いている集団を確認！"
11090-58 = "あれ……ラーメン屋さんの……？"
11090-59 = "ぐ、ぐぐっ……。"
11090-60 = "誰かと思えばあんたたちだったのね！！#nラーメンも無料で特盛にしてあげたのに、この恩知らず！！"
11090-61 = "あははは、その件はありがと。それはそれ、これはこれ。こっちも仕事でさ。"
11090-62 = "残念だけど、公私はハッキリ区別しないと。受けた仕事はきっちりこなす。"
11090-63 = "……なるほど。その仕事っていうのが、便利屋だったんだ。"
11090-65 = "もう！学生なら、他にもっと健全なアルバイトがあるでしょう？それなのに便利屋だなんて！"
11090-66 = "ちょっ、アルバイトじゃないわ！れっきとしたビジネスなの！肩書だってあるんだから！"
11090-67 = "私は社長！"
11090-68 = "あっちが室長で、"
11090-69 = "こっちが課長……。"
11090-70 = "はあ……社長。ここでそういう風に言っちゃうと、余計薄っぺらさが際立つ……。"
11090-73 = "誰の差し金？……いや、答えるわけないか。"
11090-74 = "（カチャッ）力尽くで口を割らせるしか。"
11090-75 = "ふふふ、それはもちろん企業秘密よ？"
11090-76 = "総員！攻撃！"
