[translation]
12195-2 = "Ei, Hoshino-chan."
12195-3 = "Sabe,"
12195-4 = "quando conheci a Hoshino-chan pela primeira vez, achei que fosse um sonho e me belisquei várias vezes."
12195-5 = "Ter uma kouhai tão fofa, forte e confiável como a Hoshino-chan ao meu lado... é algo tão parecido com um sonho que eu fico realmente feliz..."
12195-6 = "Hum, talvez eu não esteja conseguindo explicar direito..."
12195-7 = "Mas, poder estar aqui com a Hoshino-chan é como um milagre para mim."
12195-8 = "……Nós estamos juntas assim todos os dias, não estamos?"
12195-9 = "Ontem, hoje e amanhã também. Por que fazer tanto drama por algo tão natural?"
12195-10 = "Hau... é que..."
12195-11 = "Um \"milagre\" é algo muito mais grandioso e raro, sabe?"
12195-12 = "……Não, Hoshino-chan."
12195-13 = "Eu não penso assim."
12195-14 = "Ei, Hoshino-chan. Se um dia você também tiver uma kouhai fofa, nessa hora—"
12195-16 = "……"
12195-19 = "A senpai deve estar bem ali!!"
12195-20 = "Nn, não quebra... mais uma vez..."
12195-22 = "Ah, Ayane-chan!? Por que você está aqui!?"
12195-23 = "Vim no helicóptero que o Schale emprestou! Onde está a Hoshino-senpai!?"
12195-24 = "Aqui! Mas a porta não abre...!!"
12195-25 = "Droga!!"
12195-26 = "(BOOOOOM!!!)"
12195-28 = "(O que foi isso...)"
12195-29 = "(Meu corpo está livre...? Será que estou sonhando...)"
12195-30 = "(Ouvi a voz de todo mundo, deve ser um sonho mesmo...)"
12195-31 = "(Voz...)"
12195-36 = "(É por aqui, será...)"
12195-37 = "(Mesmo que seja um sonho... só mais uma vez, antes de acabar...)"
12195-40 = "(CLACK!)"
12195-42 = "Hoshino-senpai!!!!"
12195-46 = "Ah, ué... como..."
12195-47 = "Por que... mas, eu estava..."
12195-50 = "[ns] \"Hoshino.\""
12195-52 = "Hoshino"
12195-53 = "……Ah."
12195-56 = "Hoshino"
12195-57 = "Entendi... todo mundo, o Sensei..."
12195-60 = "Hoshino"
12195-61 = "Os adultos, né... haha."
12195-66 = "Serika"
12195-67 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-68 = "……B-bem-vinda de volta! Senpai!"
12195-71 = "Nonomi"
12195-72 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-73 = "Ah, a Serika-chan me passou a perna! #nVocê disse que não ia falar porque tinha vergonha, que trapaça!"
12195-76 = "Serika"
12195-77 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-78 = "C-cala a boca! Não importa quem falou primeiro!"
12195-81 = "Shiroko"
12195-82 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-83 = "……Que bom que você está bem."
12195-86 = "Ayane"
12195-87 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-88 = "Hoshino-senpai, bem-vinda de volta!!"
12195-91 = "Nonomi"
12195-92 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-93 = "Bem-vinda de volta!!"
12195-96 = "Shiroko"
12195-97 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-98 = "Bem-vinda de volta, Hoshino-senpai."
12195-102 = "Hoshino"
12195-103 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-104 = "Ahaha..."
12195-107 = "Hoshino"
12195-108 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-109 = "...Vocês todas estão com uma cara de quem está esperando alguma coisa."
12195-112 = "Hoshino"
12195-113 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-114 = "...É aquela frase que vocês querem ouvir?"
12195-117 = "Serika"
12195-118 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-119 = "Ah, qual é! Se você já sabe, não faz a gente esperar!"
12195-124 = "Hoshino"
12195-125 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-126 = "Uhee..."
12195-129 = "Hoshino"
12195-130 = "[7cd0ff]Comitê de Contramedidas[-]"
12195-131 = "Ai, ai... já que é um pedido das minhas kouhais fofas, não tenho escolha..."
12195-134 = "Cheguei"
