[translation]
1301306-1 = "本に包まれて"
1301306-2 = "（モミジに招待されて、レッドウィンターの図書館に向かった）"
1301306-3 = "図書館内部"
1301306-7 = "お待ちしてました、先生！"
1301306-8 = "[s] \"あれ、他の利用者は？\""
1301306-9 = "あ、それが……今日は休館日なんです。"
1301306-10 = "休館日なのに先生を呼んだ理由、ですか……？"
1301306-11 = "……。"
1301306-12 = "とりあえず、奥に来てください！"
1301306-15 = "どうですか？外は寒かったですよね？"
1301306-16 = "[s1] \"うん、ここは暖かいし居心地がいいね。\"\n[s2] \"それで、休館日に呼んでくれた理由は……？\""
1301306-19 = "そ、それは……！"
1301306-20 = "えっと……実は臨時休館にしたんです。"
1301306-21 = "こ、答えになってない……ですか？すみません。"
1301306-25 = "……先生。"
1301306-26 = "その……図書館でお昼寝をしてみませんか……？"
1301306-27 = "[s] \"えっ、司書さんがそんなこと言っていいの！？\""
1301306-28 = "せ、説明させてください！"
1301306-29 = "時々……チェリノ会長や利用者の生徒が、図書館でお昼寝をしてるんです。"
1301306-30 = "その度に注意したり、追い出したりしていたんですが……"
1301306-31 = "……。"
1301306-32 = "図書館ってそんなに寝心地がいいのかな、と気になって試してみたら……"
1301306-33 = "[s] \"思ってた以上に気持ち良かったんだね。\""
1301306-34 = "……はい。"
1301306-35 = "わざわざ休館日にした理由ですか……？"
1301306-36 = "そ、それは……！"
1301306-37 = "[s] \"司書として、いつもは注意してる立場だもんね。\""
1301306-38 = "うう……！"
1301306-39 = "間違っては、いないんですが……"
1301306-40 = "やっぱり、変ですよね……ダメですよね。"
1301306-41 = "図書館の管理を任されている司書が、私用で臨時休館にしてしまうなんて……"
1301306-42 = "い、一応、このようにパーティーションで区切ってはおきました。"
1301306-43 = "他の学園には、図書館に仮眠室があると聞いたので、それなら私たちも、休館にして擬似的な仮眠室を作っちゃおうと思って……！"
1301306-47 = "……。"
1301306-48 = "ごめんなさい、先生……言い訳ばかり……"
1301306-49 = "[s3] \"あ～、徹夜続きで眠くなってきたなぁ！\" \n[s4] \"図書館が温かいからかな？急に眠気が……\""
1301306-52 = "ほ、本当ですか！？"
1301306-53 = "……私に気を遣って、そう言ってくださったわけではなく？"
1301306-57 = "わ、笑ってないで返事してください、先生！恥ずかしいじゃないですか……！"
1301306-58 = "……。"
1301306-59 = "あの、先生。"
1301306-65 = "それでは……一緒にお昼寝、しましょう……？"
1301306-66 = "[s] \"うん、すぐにでも眠っちゃいそうだよ。\""
1301306-67 = "えへへ……じゃあ、こちらへどうぞ。#nゆっくりお休みください。"
1301306-72 = "（モミジの言う通り、とても寝心地が良く……）"
1301306-73 = "（本の優しい香りに包まれながら、ゆっくりと眠りに落ちた）"
1301306-75 = "どうですか、先生？"
1301306-76 = "……もう寝息が……お疲れだったんですね。"
1301306-77 = "……。"
1301306-78 = "ねえ、先生。"
1301306-79 = "いつも、私に寄り添ってくださって……ありがとうございます。"
1301306-83 = "……おやすみなさい。"
