[translation]
13070-1 = "第7話;肉体の限界"
13070-6 = "……シロコちゃん？"
13070-7 = "さっきからずっと付いてきてるけど、おじさんに何の用事かなー？"
13070-8 = "ん、尾行してるだけ。"
13070-9 = "それはちょっと困るなー……#nそもそも女子高生がおじさんを尾行だなんて、逆にどういう状況？"
13070-10 = "……どうしてここに来たの？#nもう誰も住んでないのに……"
13070-11 = "……うん。"
13070-12 = "もう……誰もいないね。"
13070-13 = "ここは、ユメ先輩と初めて会った場所でさ。"
13070-14 = "前の、生徒会長……。"
13070-15 = "だから、気づいたら足が向いてたっていうか……うん、そんな感じ。"
13070-19 = "先輩に何があったのか、私も知らない。"
13070-20 = "……。"
13070-21 = "でも、これ以上みんなに隠し事をするのは良くないと思う。"
13070-22 = "……。"
13070-23 = "アヤネもノノミもセリカも、みんな不安がってる。#nそれも、失踪した生徒会長に関係あること？"
13070-28 = "あぁっ！#nあんなところに誰も護送してない現金輸送車が！"
13070-38 = "ホシノ先輩！"
13070-47 = "逃さない。"
13070-49 = "のああぁっ！？#nまた速くなったねぇシロコちゃん！？"
13070-50 = "っていうかさっきの、おじさんなりの思いやりなんだけどなあ……！#nちょっとは空気読んでくれない！？"
13070-51 = "やだ、捕まえる。"
13070-52 = "ああもう……っ！#nちょっと一人にしてほしいんだけど！？"
13070-59 = "シロコ先輩、遅いわね……"
13070-60 = "……やっぱり、執事さんに連絡してみます。"
13070-61 = "……ネフティスの、ですよね？"
13070-62 = "はい、ネフティスなら何か知っているはずです。#n今はそれ以外に、手がかりもありませんし……"
13070-63 = "だ、大丈夫ですか？#nあの時は、なんだか気まずそうでしたけど……"
13070-64 = "長いこと、家と連絡を取っていなかったので……#nあまり良くは思われていないのでしょう。"
13070-65 = "……私はあまり、気にしてないのですが。#n連絡先は、たしか……"
13070-66 = "……無理はしないでくださいね、ノノミ先輩。"
13070-67 = "……はい。"
13070-75 = "ごめん、逃げられた。"
13070-76 = "シロコ先輩っ！"
13070-77 = "そうでしたか……"
13070-78 = "ん……まだまだ力不足。"
13070-79 = "お、落ち込んじゃった……"
13070-80 = "シロコ先輩で無理だったら、誰も追いつけませんから。"
13070-81 = "……ホシノ先輩が言ってた。#n明日は学校に行くから心配しないで、って。"
13070-83 = "そう、でしたか……"
13070-84 = "……今のホシノ先輩には、時間が必要なのかもしれません。"
13070-85 = "……。"
13070-89 = "……あっ。"
13070-93 = "……お嬢様。"
13070-94 = "執事さん、あの……"
13070-95 = "砂漠横断鉄道について、お知りになりたいと？"
13070-96 = "……はい。"
13070-97 = "やっぱり、何か知っているんですね？"
13070-98 = "勿論、存じております。"
13070-99 = "ネフティスは何を企んでいるんですか？#n私募ファンドの目的は？"
13070-100 = "前生徒会長の失踪と、契約書の関係は……？"
13070-101 = "存じてはおります――#nですが仕事に関する内容を、お嬢様が気にされる必要は無いのでは？"
13070-102 = "……それは。"
13070-103 = "そうかも、しれませんが……"
13070-107 = "……こうしてきちんとお話をするのは二年ぶりですね。#nお変わりはありませんか？"
13070-108 = "……はい。"
13070-109 = "カードの限度額は足りていますか？#n必要でしたら、上限を引き上げた新しいカードをお渡ししますので、#nいつでも仰ってくださいね。"
13070-110 = "い、いえ……大丈夫です。#n今でも、困ってはいないので……"
13070-111 = "……。"
13070-112 = "私のことは、大丈夫です……#n執事さん、ネフティ――"
13070-114 = "お嬢様は何もせずに、これまで通りにお過ごしください。#n……あれだけの損害を与えたこと、お忘れではないでしょう？"
13070-115 = "……。"
13070-120 = "ん……"
13070-122 = "お言葉ですが、お嬢様はネフティスを常々非難しておられました。#n今になってというのは、「虫がいい」と思われる方も多いと思いますが……？"
13070-123 = "それは……"
13070-124 = "……厳しい物言いになってしまい、申し訳ございません。#nですがネフティスは、現在危機に陥っているのです。"
13070-125 = "……えっ？"
13070-126 = "二日後の総会で、#n社の存亡が決まると言っても過言ではございません。"
13070-127 = "その総会で、いったい何が……"
13070-128 = "……今、アビドスの皆様もいらっしゃいますか？"
13070-134 = "……。"
13070-136 = "明日、そちらへ直接お伺いします。#n今日はもう遅いですから、詳しいお話はその時に。"
13070-137 = "それとお嬢様は、カードをお忘れなく。交換いたしますので。#nでは、今日のところは失礼いたします。"
13070-138 = "え？それは大丈――"
13070-142 = "……。"
13070-143 = "ノノミ先輩……"
13070-144 = "……気にしないでください。#nそれよりも、ネフティスの存亡が懸かっているだなんて……"
13070-145 = "思っていた以上に、複雑な状況なのかもしれません……"
13070-146 = "私も情報を集めてみます。"
13070-147 = "大丈夫……？#nアヤネちゃんも疲れてるでしょ。"
13070-148 = "それは……でも……！"
13070-149 = "[s] \"今日は早めに帰って休もう。\""
13070-150 = "先生？"
13070-151 = "……そうしましょう、アヤネちゃん。#nこういう時は、休むことも大切ですから。"
13070-152 = "シロコちゃんも、セリカちゃんも、そして先生も……"
13070-154 = "私は大丈夫。"
13070-155 = "いやいや、シロコ先輩も顔疲れてるから。#n帰ってちゃんと休んでよね？"
13070-156 = "……ん。"
13070-157 = "あはは……ホシノ先輩を全力で追いかけたわけですし……"
13070-158 = "[s1] \"私もシャーレに戻って色々と調べてみるよ。\"\n[s2] \"また明日、みんなで集まろう。\""
13070-161 = "ん、分かった。"
13070-162 = "では皆さん、また明日。"
13070-163 = "うん、またね。"
13070-168 = "……。"
13070-169 = "どうかしたの、アヤネちゃん？"
13070-170 = "……何だか、変な感じがしませんか？"
13070-171 = "変な感じって？"
13070-172 = "砂漠横断鉄道、債権者団体の総会、アビドス生徒会……"
13070-173 = "偶然発見された契約書の日付と、ユメ先輩の失踪日……"
13070-174 = "私たちの知らない、大きな何かが動いているような……"
13070-175 = "うん、だから明日また集まるんでしょ？"
13070-176 = "そうなんだけど、そうじゃなくて……"
13070-177 = "何だろ、違和感っていうのかな……"
13070-178 = "[s] \"違和感？\""
13070-179 = "……はい。"
13070-181 = "誰かの、まだ見えてない意図と言いますか……#n悪意を感じるような……"
13070-182 = "悪意って……いったい誰が？"
13070-183 = "[s] \"……。\""
13070-184 = "……そう、だよね。#n私の考えすぎかも。"
13070-185 = "先生も、気にしないでください。"
13070-186 = "……恐らく情報が足りないせいで、混乱しているんだと思います。"
13070-187 = "明日はネフティス側と会う予定ですし、#n少しでも情報収集をしておきます。"
13070-188 = "[s] \"分かった、でもあんまり無理しないでね。\""
13070-189 = "……はい。#n帰ろう、セリカちゃん。"
13070-190 = "ま、待ってよアヤネちゃん。"
13070-195 = "[ns] シャーレに戻る。"
13070-199 = "攻略法その1――「既に起きた出来事は変えられない」。"
13070-200 = "先生が未来をことごとく変えてしまうというのなら、#n過去を利用すれば良いだけのこと。"
13070-201 = "例え先生であっても、過去を変えることは不可能でしょう。"
13070-207 = "つまり、攻略の鍵は――「過去」にあるのです。"
13070-216 = "私は……"
13070-219 = "さあ、先生よ……ヒヒ、ヒヒヒッ……。"
13070-221 = "攻略法は、全部で4つ。"
13070-222 = "1つ目は既に進行中……#nそして2つ目もまた、じきに……ヒヒッ。"
13070-223 = "いやはや、4つ目の攻略法は出る幕も無いかもしれませんね。果たして……"
13070-224 = "その選択、楽しませてもらうとしましょう……ヒヒッ、ヒヒヒヒッ……"
13070-228 = "[ns] \"アロナ、プラナ。\""
13070-230 = "はい、先生！"
13070-231 = "確認、命令待機中。"
13070-232 = "[ns] \"朝までにやらなきゃいけないことがあるんだ。\""
13070-234 = "[ns5] \"もし途中で寝ちゃってたら、\"\n[ns6] \"どうにか起こしてもらえるかな？\""
13070-237 = "徹夜だなんて……だ、大丈夫ですか、先生？"
13070-238 = "う、ううっ……分かりました！#nでも、ちゃんと休憩を挟んでくださいね！"
13070-239 = "理解。#nモーニングコールですね、お任せください。"
13070-240 = "[ns] \"……あ、それと。\""
13070-242 = "[ns] \"……ゲマトリアに何か動きはある？\""
13070-243 = "ゲマトリア、ですか？#nあれ以来、特には……"
13070-244 = "どのような用件でしょうか、先生？"
13070-245 = "[s] \"……ううん、それなら大丈夫。\""
13070-254 = "おはよ～。"
13070-255 = "おはようございます。"
13070-256 = "うんうん☆#nアヤネちゃんもセリカちゃんも、元気そうで何よりです。"
13070-257 = "……ノノミ先輩、寝られなかったんですか？"
13070-258 = "ふふっ……すみません、少しは寝たのですが。"
13070-263 = "おはよう。"
13070-264 = "シロコ先輩は問題なさそうね。"
13070-265 = "ん？"
13070-266 = "元気そうで良かったってだけ。#nそれで、ホシノ先輩は？"
13070-267 = "まだ連絡は来てない。#nでも、来るって言ってたから。"
13070-268 = "ところで、先生は……？"
13070-269 = "先生のことですから、#nきっと何か調べているんだと思います。"
13070-270 = "……まさか、夕方頃にふらふら来るつもりじゃないわよね？"
13070-271 = "明日は総会当日、あまりに遅くなると準備が……"
13070-275 = "むにゃ……んん、ふひひ……"
13070-276 = "……先輩、アロナ先輩。"
13070-277 = "ふあぁ……プラナちゃん？#nどうかしました……？"
13070-281 = "のあっ、もう朝ですか！？#n先生を起こしてあげないと……！"
13070-282 = "問題ありません。#n先生は朝までずっと起きていました。"
13070-283 = "なら良か……"
13070-284 = "いえ、また徹夜だなんて、良いことではないんですけど……"
13070-285 = "それは確かに……ところでアロナ先輩。#n本日、工事の予定なんてありましたでしょうか？"
13070-286 = "工事？いえ、無いはずですが……？"
13070-287 = "……ガスの配管システムに、異常が検知されました。"
13070-288 = "……え？"
13070-290 = "混乱、初めて見る現象です……#nガスの配管が、変わっています。"
13070-291 = "まるで何者かが強制的に介入しているような……捻じれて、歪んでいて、不快な……"
13070-292 = "……ま、待ってください！"
13070-296 = "先生っ！！！"
13070-305 = "……攻略法、その2。"
13070-306 = "奇跡の担い手とはいえ、肉体には物理的な限界がある。"
13070-307 = "それが先生……あなたの弱点でしょう？#nヒヒッ、ヒッ……"
13070-308 = "ヒヒヒッ、ヒヒヒヒヒッ！"
13070-310 = "イヒヒヒヒヒヒヒヒヒッ！！"
13070-312 = "\n次回;アビドス生徒会（１）"
