[translation]
13110-1 = "第11話;明かされる秘密"
13110-8 = "こちらにお座りください。"
13110-9 = "ありがとうございます……ここが対策委員会の教室なんですね。#nこんな形で来ることになるとは、思っておりませんでしたが……。"
13110-14 = "こちらのスオウ監督官は、昨日も申し上げた通りネフティス側の者です。#n今日も私の護衛を務めてくださいました。"
13110-15 = "……とのことだ。"
13110-19 = "直接お会いするのは、二年ぶりですね。#nお変わりありませんでしたか？"
13110-20 = "……はい、おかげさまで。"
13110-21 = "でしたら何よりです。……電話でお伝えしたように、限度額を増やした新しいカードをお持ちしました。"
13110-22 = "……い、いえ。それは大丈夫です。#n特に困っていませんし……。"
13110-23 = "……お嬢様、今からでも戻ってくるつもりはありませんか？"
13110-24 = "戻る、とは……？"
13110-25 = "もちろん、ハイランダー鉄道学園に。"
13110-26 = "それは……。"
13110-28 = "ノノミちゃんが困ってるでしょ。"
13110-29 = "ん、本題に入って。"
13110-31 = "……はい、失礼しました。"
13110-32 = "これくらい構わないだろう。"
13110-33 = "元々、ネフティスはハイランダーと協力関係を結ぶはずだった。#nにもかかわらず、そこのご令嬢がアビドスに行ったせいで、破綻しかけたわけだ。"
13110-35 = "……。"
13110-36 = "自分のわがままを聞いてくれた相手に対して、#nあまりにも失礼な態度を取っている自覚は無いのか？"
13110-42 = "我慢して、シロコ先輩！"
13110-43 = "ん……別に、何もするつもりはない。"
13110-45 = "その気なら、かかってくると良い。#n――勝てると思っているのならな。"
13110-46 = "……スオウさん、あまり挑発なさらないでください。"
13110-47 = "……ふん。"
13110-51 = "……ご安心を。#n何も、連れ戻すために来たわけではありません。"
13110-53 = "早く本題に移ってもらっても良いでしょうか？"
13110-54 = "そう、ですね……。"
13110-56 = "……。"
13110-57 = "……。"
13110-62 = "結論から申しますと、「砂漠横断鉄道」の裏には……。"
13110-63 = "アビドス生徒会とネフティス間で秘密裏に進めていた、#n「非対称戦力兵器」計画がありました。"
13110-69 = "……はい！？"
13110-70 = "生徒会が……？"
13110-72 = "非対称戦力兵器？"
13110-73 = "な、何よそれ……。"
13110-75 = "その名は――"
13110-76 = "――「列車砲シェマタ」。"
13110-82 = "シェマタは破壊力も射程距離も、従来の規格と比べ物になりません。#n列車砲……いえ、要塞兵器と言ったほうが良いでしょう。"
13110-83 = "1トン以上の爆弾を500km先まで飛ばす、超長距離砲。"
13110-84 = "そんな代物が、鉄道路線の上を走り回る計画です。"
13110-85 = "話している私でさえ、本当に実現できるのか信じられません。"
13110-86 = "ですが……もし完成すれば、#n周辺自治区に対して圧倒的な抑止力となることでしょう。"
13110-89 = "……そんな兵器がねぇ。"
13110-94 = "い、いったいなぜ……！？"
13110-95 = "簡単じゃないか。"
13110-96 = "借金を返済するため、だろう。"
13110-97 = "……？"
13110-98 = "強力な兵器の使い道なんて、いくらでもあるからな。"
13110-100 = "そ、そんな……。"
13110-101 = "「シェマタ」……もしかして名前の由来は、あの生徒会長ですか？"
13110-103 = "よく知っているな。#n……鉄拳政治のシェマタを。"
13110-105 = "……しぇまた？"
13110-106 = "同時に70人の生徒会長が存在した混乱期を治めて、#nアビドス全盛期を率いた伝説的な生徒会長の二つ名だよ。"
13110-107 = "70人って、意味が分からないんだけど……。"
13110-109 = "……アビドス出身ではない私も知っているくらいだ。"
13110-110 = "全盛期のアビドスは圧倒的な兵力、資金力を誇り、#n全自治区から恐れ、羨まれていた、と。"
13110-111 = "そう考えると、列車砲の名付けは興味深い。"
13110-112 = "強力な武器さえあれば、借金を返済できると思ったのかな。"
13110-114 = "……ホシノ先輩。"
13110-115 = "つまり……砂漠横断鉄道はシェマタを隠蔽するために作られたんですか？"
13110-120 = "お嬢様、それは違います。#nあくまでも非対称戦力兵器計画は、#n鉄道事業が動き出してから話に出たものです。"
13110-121 = "おそらく、アビドス生徒会に入れ知恵をした者がいたのでしょう。"
13110-122 = "誰がそのようなことを……！"
13110-123 = "そこまでは私も……。#nなにせ、詳しく説明されぬまま、秘密裏に進められたものでして……。"
13110-125 = "落ち着いて話を聞くんだな、ご令嬢。#nすでに、この計画は破綻している。"
13110-126 = "ええ、その通りです。"
13110-127 = "シェマタほどの常識外れな要塞兵器が、正常に動くはずありません。"
13110-128 = "結局、エンジンが動くことはありませんでした。#n今も未完成のまま、アビドス砂漠のどこかに放置されています。"
13110-129 = "そして、計画は中止――"
13110-130 = "……となっていたのです。#nほんの少し前までは。"
13110-136 = "最近になって再度シミュレーションをしたところ、#nシェマタの実現性は限りなく高いものとなっていました。"
13110-137 = "設計者は、数年先を見据えて設計をしていたのか、#nそれともただの偶然なのかは当人しか知り得ませんが……。"
13110-139 = "いずれにせよ、砂漠横断鉄道の重要性が一気に増したわけだ。"
13110-140 = "保有しているだけで抑止力となり得る存在。#n時代を先取りした革新的な技術。"
13110-141 = "これらの事実が明らかとなった以上、行動しない手はない。"
13110-142 = "「私募ファンド」が砂漠横断鉄道の権利に執着しているのは、#nまさにこれが理由なのです。"
13110-146 = "鉄道の権利さえ得てしまえば、列車砲も手に入れられますから。"
13110-147 = "もちろん、私募ファンドも一枚岩ではないでしょうが。"
13110-150 = "そして、あの者たちだけで債権の購入資金を集めることは叶わず、#nネフティスの力を借りに……。"
13110-151 = "我々としても、砂漠横断鉄道はできれば保存しておきたかったので、#n非対称戦力兵器計画の再始動を知らずに手を結んでしまいました。"
13110-154 = "……。"
13110-155 = "後に計画の全貌を知った頃には、私募ファンドから手を引ける状況になく……。"
13110-156 = "このまま、あの者たちに列車砲の権利を渡してはいけません。"
13110-157 = "そうだね。#nそんな兵器が悪党の手に渡ったら、必ず争いの種になる。"
13110-159 = "私たちが先に見つけて壊そう。"
13110-160 = "列車砲がどこにあるのか、執事さんはご存知ですか？"
13110-162 = "いえ……申し訳ありません。#n私たちも皆目検討がつかないのです。"
13110-163 = "この計画自体、極秘事項でしたから。#n当時の書類は見つからず……。"
13110-168 = "そっか……。"
13110-169 = "今に思うと、私募ファンドが我々に接近した理由は、#n列車砲の位置を知るためでもあったのでしょう。"
13110-170 = "その企みは叶わなかったわけですが、いずれにせよ時間の問題。"
13110-171 = "[ruby=Central Control Center]中央管制センターは[/ruby]列車砲の存在も、この計画も知らないはずです。#nしかし、工事が再開されれば、近いうちに見つけてしまうでしょう。"
13110-172 = "……私募ファンドは、正式な契約をもって列車砲の権利を手に入れようとしています。"
13110-173 = "正式な契約、ですか……？"
13110-174 = "ええ。#n権利関係について、何度も尋ねてきましたので。"
13110-175 = "実際、アビドス生徒会とネフティスだけでなく、#n設計者も一部権利を有しているため、複雑になっていますから……。"
13110-176 = "事業家としては、優れているのでしょう。#n権利関係を明白にしておけば、あとから生じるトラブルを避けられますし。"
13110-177 = "……カイザーは列車砲の存在を知らなかったんですか？"
13110-178 = "どうでしょう。仮に知っていたとしても、関心が薄いのだと思います。カイザープレジデントは、サンクトゥムタワーの方に関心があると話に聞いていますので。"
13110-179 = "真偽の定かではない噂に振り回されるくらいなら、#n債権を売って資金を集めておくのが良いと判断したのかと……。"
13110-183 = "……しかし、誰にも予想できなかった事態が発生しました。"
13110-187 = "アビドス生徒会長とネフティスの間で交わされた契約書が発見されたのです。"
13110-189 = "経緯までは分かりませんが……#nこれがある以上、列車砲の権利は私募ファンドのものになりません。"
13110-190 = "契約書について、ネフティスは本当に何も知らないの？"
13110-191 = "それと、ユメ先輩の身に、何が起きたのかも……！"
13110-193 = "……ホシノ先輩。"
13110-198 = "……申し訳ありません。#n私たちも契約書の存在を知りませんでしたので……。"
13110-199 = "……。"
13110-200 = "当時の状況に鑑みると、#nおそらく破産を避けるために少しでも現金が欲しかったのでしょう。"
13110-201 = "その過程で売られた権利のひとつが、砂漠横断鉄道だったというだけかと。"
13110-202 = "……。 "
13110-203 = "とにかく、私募ファンドは先に契約書の問題を解決しようとするでしょう。"
13110-204 = "あの者たちにとって、それが最優先事項のはずですから。"
13110-209 = "……明日の12時に、アビドス中央駅旧庁舎で行なわれる総会ですね。"
13110-210 = "ええ、そうです。"
13110-211 = "生徒会の代表者が総会で契約を破棄するか、#n欠席した時点で契約は無効に。#nそして、権利はネフティスに渡ります。"
13110-215 = "ということは……！？"
13110-216 = "……いえ、お嬢様。#nネフティスが権利を完全に得るわけではありません。"
13110-217 = "合同で債権を購入した以上、持ち分は互いに発生します。"
13110-222 = "……それじゃ、残った方法はひとつしかないね。"
13110-228 = "私が総会に参加して、契約継続の意思表示をするよ。"
13110-229 = "……そうしていただけるのなら、私としても幸いです。"
13110-230 = "お金は少しずつ支払うしかないだろうけど、#nとりあえず手出しできなくなるなら安心だね。"
13110-231 = "その間に砂漠中を探し回って、列車砲を見つければ良いだけじゃん？"
13110-233 = "なんだ、思ったより簡単で拍子抜けだわ。"
13110-234 = "それは――"
13110-236 = "それはどうだろうな。"
13110-241 = "私募ファンドは、あんたらの出席を妨害するに決まっている。"
13110-242 = "いくら何でも、それは……。"
13110-243 = "多少考えれば分かると思うが？#n数百名規模の兵士で旧庁舎を封鎖し、入ってこられないようにするはずだ。"
13110-244 = "……そんな！"
13110-249 = "すでに動き出しているだろうな。#n……ありとあらゆる手段を駆使して。"
13110-251 = "中央駅旧庁舎東側地域"
13110-256 = "……あなたたちには、あちらを任せましたよ。"
13110-258 = "行くぞ、仕事だー！！"
13110-264 = "中央駅旧庁舎・西側広場"
13110-270 = "よし、ヘリも到着したか。"
13110-271 = "戦車は指定地点を死守しろ。#nマーケットガードは封鎖区域を徹底的に守れ。#nネズミ一匹通すんじゃないぞ。"
13110-276 = "中央駅旧庁舎・南側広場"
13110-278 = "……計画は聞いているでしょうね？"
13110-280 = "ああ、もらった金の分だけ働いてやる。"
13110-286 = "列車砲……あのゲヘナの雷帝が残した遺産ですからね。#nくくっ、必ず手に入れてみせますよ。"
13110-288 = "中央駅旧庁舎・北側広場"
13110-293 = "ここにバリケードを積むのだ。"
13110-297 = "ショベルカー、ブルドーザー、フォークレーン……#n動員できるものは、すべて持ってきなさい。"
13110-307 = "……明日の12時までに来られなければ、列車砲は私たちの物に。"
13110-308 = "ふっふっふ……精々、頑張ることですね。"
13110-310 = "えっ！？"
13110-311 = "……なるほどねぇ。"
13110-312 = "うーん……。"
13110-313 = "それだけの規模に対して、私たちは……。"
13110-315 = "せ、先生さえいれば、なんとかなるんじゃない？"
13110-316 = "「シャーレ」の先生は、#nどんな大義名分を掲げて私的な取引に介入するんだ？"
13110-320 = "妨害してるあいつらが悪いのに、#n先生に助けてもらって何がいけないの！"
13110-322 = "……セリカちゃん、考えてみて。"
13110-324 = "どういうこと？"
13110-325 = "総会が開かれる場所は、中央駅旧庁舎。#nあそこは、砂漠横断鉄道の路線がいくつも交差する中心部。"
13110-326 = "すでに鉄道の権利は私募ファンドにありますから……。"
13110-327 = "あいつらは、自分が所有している場所を守っているだけ。"
13110-328 = "そ、そんな言い分が許されるの！？"
13110-334 = "ところで、総会に出席するのは――君たち[ruby=・   ・   ・   ・   ・]対策委員会[/ruby]なのか？"
13110-336 = "……？"
13110-337 = "全員で行く。"
13110-342 = "聞き方が悪かったな。"
13110-343 = "君たちは「アビドス生徒会」として出席するのか、#nそれとも「対策委員会」として出席するのか、という話だ。"
13110-344 = "そ、それは……。"
13110-345 = "[ruby=くちなし]梔子[/ruby]ユメが結んだ契約書上、名義人はアビドス生徒会になっている。#nしかし、それは今となっては名前だけが残っているのだろう？"
13110-346 = "だとすれば、まずは生徒会の立場を明確にする必要があるんじゃないのか？"
13110-347 = "と言っても、総会の場にたどり着けなければ、#nこんな議論をしたところで無意味だがな。"
13110-348 = "……。 "
13110-350 = "……強行突破しよう。"
13110-351 = "だから、それが難しいから困ってるんでしょ。"
13110-353 = "どうにかして、ほかの方法を探さないと……。"
13110-355 = "……方法ならあります、お嬢様。"
13110-363 = "それも、皆様が正面から戦うよりも、遥かに簡単な方法が。#nお嬢様がハイランダーに入学して、生徒会長になってくだされば良いのです。"
13110-364 = "……はい！？"
13110-370 = "「ネフティス」の幹部として権力を行使すれば、この契約を取り消せます。"
13110-371 = "ネフティス、ハイランダー、私募ファンド……三勢力のうち、二つの勢力が反対すれば、残る私募ファンドはどうすることもできません。"
13110-372 = "……で、でも。"
13110-373 = "そうすると、私はアビドスから……。"
13110-375 = "却下ー。"
13110-376 = "なに訳の分からないこと言ってるのよ！#nノノミ先輩が犠牲になる必要なんてない！"
13110-381 = "……執事さん。#nその方法はお断りします。"
13110-382 = "私はアビドスを去りたくありません！"
13110-383 = "……そう仰ると、思っておりました。"
13110-384 = "そこで、第三の方法を提案いたします。#nおそらく、不可能でしょうが。"
13110-388 = "……第三の、方法？"
13110-389 = "少々、過激ではありますが……。"
13110-390 = "構いません、教えてください！"
13110-394 = "はい、その方法は……。"
13110-395 = "……砂漠横断鉄道の売買契約そのものを、無効にしてしまえば良いのです。"
13110-396 = "……？"
13110-397 = "契約を結んだ「アビドス生徒会」に、生徒会としての権限がなかったとしたら……？"
13110-398 = "……！？"
13110-404 = "[ruby=くちなし]梔子ユ[/ruby]メと[ruby=たかなし]小鳥遊[/ruby]ホシノの二名によって構成された「アビドス生徒会」は、非認可の組織だった、と宣言するのです。"
13110-405 = "な、何を言って……。"
13110-406 = "前生徒会長は、挙手投票で梔子ユメに会長職を押し付けたそうですね？#nつまり、その正当性を否定することは不可能ではありません。"
13110-407 = "その事実を、総会に出席して明らかにするのです。"
13110-408 = "すると、契約そのものが存在しなかったことになり……。"
13110-409 = "砂漠横断鉄道の権利は我々ネフティスのものになるため、#n私募ファンドは手出しできなくなります。"
13110-410 = "何を言っているんですか！？#nそんな方法……！"
13110-411 = "……だから言ったのです、不可能だと。"
13110-412 = "……。"
13110-413 = "……とにかく、砂漠横断鉄道の秘密を教えはしましたが、#nこれといった解決手段はなさそうですね。"
13110-417 = "――期限は明日の12時です。"
13110-418 = "私のほうからも、良い解決策があればご連絡いたします。"
13110-419 = "明日の総会で会えることを願っております。"
13110-420 = "では、失礼する。"
13110-429 = "うーん。"
13110-430 = "ん。"
13110-435 = "……。"
13110-440 = "みんな、ぼーっとしてないで会議を始めるよ。"
13110-441 = "ホシノ先輩……。 "
13110-442 = "おじさんは大丈夫だよ、ノノミちゃん。"
13110-443 = "それより、解決策を考えないとね。"
13110-445 = "うん、みんなで考えれば何とかなるはず。"
13110-447 = "はい……。"
13110-448 = "いや～シロコちゃんはいつも前向きで良いね。"
13110-450 = "……ん。"
13110-452 = "なに照れてるのよ、シロコ先輩。"
13110-453 = "あはは……。"
13110-457 = "皆さん疲れたでしょうし、少し休んでからにしましょう。"
13110-459 = "次回;対策委員会の始まり"
