[translation]
13130-1 = "第13話;人質"
13130-9 = "……ただいま。"
13130-13 = "おかえり、シロコ先輩。"
13130-14 = "……あ、ドアちゃんと閉めてよ。風が入ってくるじゃない。"
13130-15 = "ご、ごめん。"
13130-20 = "おかえりなさい、先輩。"
13130-21 = "あ、そうだ。#nついでに電気もつけてくれない？"
13130-23 = "う、うん。"
13130-27 = "いや～セリカちゃん。先輩をそうやってこき使ってると、#nいつかバチが当たるかもしれないよ？"
13130-28 = "なっ、"
13130-29 = "みんなも面倒くさがって電気つけようとしなかったじゃない！"
13130-34 = "……それで、先生は？"
13130-36 = "詳しい情報は、何も……。"
13130-37 = "病院に搬送されたけど、命に別状はないみたいだね。#nでも、まだ目は覚めないって。"
13130-39 = "うーん……。"
13130-41 = "あんな事故に巻き込まれて傷ひとつなかっただけでも、#n不幸中の幸いでしょう。"
13130-42 = "ひとまず安心だわ。"
13130-44 = "……でも、先生の手は借りられそうにないね。"
13130-50 = "どうにかして、方法を探さないと。#nまずは契約を継続して、それから列車砲を……。"
13130-52 = "……ほかの学園に協力してもらうのは、どうでしょうか？"
13130-54 = "先生がいないと、難しいんじゃないかなぁ。"
13130-55 = "……旧庁舎までの距離を考えたら、そろそろ出発しないと。"
13130-59 = "……。"
13130-60 = "はぁ……やるしかないわね。"
13130-64 = "ところで、ノノミは？"
13130-65 = "先輩なら、用事があると言って出ていきましたよ。"
13130-66 = "……いつ戻ってくるんだろ？"
13130-68 = "ちょっと心配だね……。"
13130-77 = "執事さん……指示された通り、みんなには内緒で来ました。"
13130-84 = "そのようだな。"
13130-90 = "学校からずっと[ruby=つ]尾[/ruby]けてきたが、間違いない。"
13130-91 = "……あなたは！#n執事さんはどこですか！？"
13130-96 = "……私ならこちらにおります、お嬢様。"
13130-97 = "ですが、まさかそちらからいらっしゃるとは思っていませんでした。"
13130-98 = "それは……。"
13130-99 = "もしかして、考えが変わったのですか？"
13130-100 = "ハイランダーに入学し、ネフティスに戻ってくる決心がついた、と。"
13130-101 = "ち、違います！"
13130-105 = "でしたら、なぜわざわざこちらに……？"
13130-106 = "私がハイランダーの生徒会長にならなくても……。"
13130-107 = "列車砲の問題を解決する方法はあるはずです。#n……ネフティスになら。"
13130-108 = "……。"
13130-109 = "ネフティスは、私募ファンドともハイランダーとも協力関係にありますよね。"
13130-110 = "会社の力を集約すれば、きっと……。"
13130-116 = "アビドス生徒会も、対策委員会も、かけがえのない場所なんです。"
13130-117 = "……どうか、お願いします。"
13130-123 = "それは難しいお願いですね。"
13130-124 = "どんな犠牲も払わずに、望んだものを手に入れようだなんて。"
13130-125 = "……！"
13130-126 = "お嬢様、世間はそこまで甘くありません。"
13130-127 = "わがままを言えば何とかなるとお思いですか？#n中学生の頃から、成長していないのですね。"
13130-128 = "方法なら、すでにお伝えしました。#nお嬢様がハイランダーに入学すれば解決するのです。"
13130-129 = "そ、それは……。"
13130-130 = "強制的に入学させてしまっても良いのですが……#nできればご自身の意志で決めていただきたく思っています。"
13130-131 = "もっとも、ほかに手がないとは言いませんが。"
13130-132 = "そ、それは何ですか！？"
13130-133 = "……教えてもらいたいのなら、何か言うことはありませんか？"
13130-134 = "……！！"
13130-135 = "お嬢様がセイント・ネフティスグループに反抗して損害を与えた結果、#nどれだけの人が苦労したのかご存知で？"
13130-137 = "身内に頭を下げさせたところで、何になるんだ。"
13130-138 = "スオウさん、あなたの意見は求めていません。#nこれは、[ruby=・   ・   ・   ・   ・]ネフティス[/ruby]の話ですので。"
13130-145 = "……はい。"
13130-146 = "……申し訳、ありませんでした。#n執事さんだけでなく、ネフティスの皆さんにまでご迷惑をおかけして……。"
13130-147 = "本当に、申し訳ありませんでした……。"
13130-148 = "……それくらいで良いでしょう。#n失礼な物言いをしてしまい、こちらこそ謝罪いたします。"
13130-149 = "では、私たちの計画をお教えします。"
13130-155 = "我々は、こう考えていました。"
13130-156 = "対策委員会が列車砲の存在を知れば、放っておくはずはない。"
13130-157 = "なんとかして総会に出席し、契約の継続を申し出る、と。"
13130-158 = "……「シャーレ」の手を借りてでも。"
13130-161 = "先生の力は、我々も知っております。"
13130-162 = "小鳥遊ホシノ不在の状況でも、カイザーPMCは歯が立たなかったほどですから。"
13130-166 = "そこで対策に、私募ファンドは大量の兵士を動員するだろうと考えました。"
13130-167 = "……おそらく先生なら、どうにかしてしまうでしょうが。"
13130-170 = "ただ、それも私たちの思惑なのです。"
13130-172 = "……え！？"
13130-173 = "「シャーレ」と「私募ファンド」が正面衝突すれば、どちらも損害は免れません。"
13130-174 = "そのタイミングでネフティスは兵力を投入し、#n漁夫の利を得る手はずになっています。"
13130-175 = "……え！？ "
13130-176 = "ま、待ってください！#nネフティスと私募ファンドは協力関係にあるのでは……！？"
13130-177 = "……表向きは、お嬢様が仰る通りですね。"
13130-178 = "……！"
13130-179 = "い、いつからそんな計画を！？"
13130-180 = "始めからです。#n元はと言えば、私たちの所有物だったのですよ。"
13130-181 = "あれさえ手に入れてしまえば、ネフティスの復活は早まることでしょう。"
13130-182 = "当時はとんだ損失を与えてくれましたが、#n巡り巡って宝の山になってくれるとは。"
13130-186 = "にしても、先生はいつ戻ってくるのやら。"
13130-187 = "シャーレの助けなしに、お嬢様が会場にたどり着くことは不可能でしょうし……。"
13130-191 = "計画が狂ってしまうのではないかと、不安でしたが……。"
13130-196 = "こうして、のこのこやって来てくださるとは。"
13130-201 = "あんたは利用されたんだ、ご令嬢。"
13130-211 = "きゃっ……！？"
13130-215 = "（執事さん……）"
13130-216 = "（初めから、こうするつもりで……）"
13130-222 = "ユメ先輩、どうして……。"
13130-223 = "どこにいるんですか、先輩……。#nお願いです……帰ってきてください。"
13130-224 = "先輩、私が間違ってました……。"
13130-228 = "……ユメ先輩。"
13130-230 = "（ああ……）"
13130-231 = "（今日も見つけられなかったんですね……）"
13130-232 = "（いったい、いつまであの砂漠を彷徨うのでしょうか……）"
13130-238 = "（毎日、毎日……）"
13130-239 = "（どうして、そこまで……）"
13130-240 = "（全部忘れて、ここを去っていれば……）"
13130-244 = "（夢だったことに、していれば……） "
13130-245 = "（ここまで苦しまずに済んだのに……）"
13130-246 = "（どうして……）"
13130-252 = "（これは、私にも言えることです……）"
13130-253 = "（忘れてしまえば……全部夢だったのなら良かったのに）"
13130-257 = "（あの日、私は……）"
13130-261 = "……ホシノ、先輩。"
13130-266 = "ご苦労様でした、スオウさん。#nお嬢様から学生証とカードを取り上げてください。"
13130-267 = "……ハイランダーの生徒会長になるよう言っていたのは、嘘だったのか？"
13130-268 = "当然でしょう。"
13130-269 = "お嬢様には、生徒会長よりも相応しい[ruby=役割]人質[/ruby]を果たしてもらいます。"
13130-270 = "仮にも、ネフティスのご令嬢なんじゃないのか？"
13130-271 = "ええ。ですが、これは理事会が決定した方針ですので。#nもちろん、危害を加えるつもりはありませんが。"
13130-272 = "では、対策委員会に連絡して、総会に出席するよう伝えるとしましょう。"
13130-273 = "もし欠席した場合、お嬢様がハイランダーに転校することになる、とも。"
13130-275 = "……契約を続行させて良いのか？"
13130-276 = "その逆です。"
13130-277 = "「アビドス生徒会」には、生徒会組織としての実態がなかったと主張させます。 #nそうすれば、契約そのものが無効となり、鉄道の権利はネフティスのものに。"
13130-279 = "……なるほど。"
13130-280 = "シャーレの先生こそいませんが、#nお嬢様の身を預かっていると言えば、それなりにやってくれるでしょう。"
13130-281 = "……まあ、どちらが勝とうと構いません。#n最後に立っているのは、ネフティスですから。"
13130-282 = "どう転ぼうと、列車砲はネフティスのものになる算段というわけか。"
13130-283 = "ええ、ではお嬢様をお連れしてください。"
13130-284 = "私は対策委員会に連絡をしてきます。"
13130-294 = "ごめんなさい、皆さん……。"
13130-295 = "けほっ、けほっ……。"
13130-299 = "最初から、アビドスにいてはいけない存在だったんです。"
13130-300 = "どこまで行っても、ネフティスの者ですから。"
13130-301 = "罪悪感でアビドスに来たような私に、残る資格はありません。"
13130-302 = "皆さんは、私の存在なんて忘れてください。"
13130-303 = "生徒会長を……アビドス生徒会を、なかったことにしなくて良いんです。"
13130-304 = "先生なら、列車砲を見つけて破壊してくださいます。"
13130-313 = "……とのことです。"
13130-314 = "対策委員会の皆様は、債権者団体の総会で#nアビドス生徒会は非認可の存在だったと宣言するだけで良いのです。"
13130-315 = "そうすれば、あの契約自体が無効になります。"
13130-316 = "お嬢様は先ほど、ああ言っておりましたが……#n本心では皆様と過ごしたいことでしょう。"
13130-320 = "……総会まで、猶予は残されていません。"
13130-321 = "皆様が賢い選択をしてくださるよう、祈っています。"
13130-326 = "……。"
13130-329 = "……ノノミ先輩。"
13130-330 = "そ、そんな……。"
13130-331 = "ノノミ……。"
13130-333 = "……。"
13130-338 = "せ、先輩、どこ行くの！？"
13130-339 = "……総会だよ。"
13130-340 = "あの執事の言いなりになるってこと！？"
13130-341 = "これ以上、大切な人を失いたくないんだ。"
13130-343 = "で、ですが、私たちだけでは……。"
13130-344 = "そうだよ、ホシノ先輩。#n先生の連絡を待とう。"
13130-346 = "……みんなは待ってて。"
13130-351 = "はい！？"
13130-353 = "一人で行くの！？#nあんな数の敵、どうやっても勝てないでしょ！"
13130-354 = "……勝てるよ、[ruby=・]私[/ruby]なら。"
13130-355 = "……ノノミを助けたら、今度は私募ファンドとネフティスを倒すつもりだよね？"
13130-356 = "……。"
13130-357 = "えっ！？"
13130-358 = "あとのことは、気にしなくて良いよ。"
13130-359 = "対策委員会[ruby=・   ・]には[/ruby]、何の責任もないから。"
13130-360 = "どういう意味よ、先輩！"
13130-361 = "責任を負うのは、私だけで良い。"
13130-362 = "だから、みんなはここに残って。"
13130-364 = "……！！"
13130-365 = "……。"
13130-366 = "ホシノ先輩が言う、「みんな」って？"
13130-371 = "対策委員会のみんなだよ。#nシャーレの認可を受けた、本当の生徒会組織。"
13130-389 = "し、シロコ先輩！？"
13130-391 = "……危ないでしょ、シロコちゃん。"
13130-396 = "勝負しよう、先輩。#n……付いてきて。"
13130-402 = "ちょっ、シロコ先輩！"
13130-403 = "しょ、勝負……！？"
13130-411 = "……久しぶりの勝負だね。"
13130-412 = "おじさん、年甲斐もなくワクワクしてきたよ。"
13130-420 = "ま、待ってください……！#nホシノ先輩、シロコ先輩！？ "
13130-421 = "どうして、こんなことに……。"
13130-422 = "せ、セリカちゃん……。"
13130-423 = "ああ、もう！行くしかないでしょ！"
13130-429 = "次回;[ruby=みんな]対策委員会[/ruby]"
