[translation]
13150-1 = "第15話;副生徒会長の命令"
13150-7 = "ねえ、ホシノちゃん。"
13150-8 = "私はね。ホシノちゃんと初めて会った時、これは夢なんじゃないかなって思って、何度も頬をつねったの。"
13150-9 = "ホシノちゃんみたいな、可愛くて強くて、頼れる後輩がそばにいてくれるなんていう夢みたいなことが、本当に嬉しくて……。 "
13150-10 = "うーん、上手く説明できてないかもしれないけど……。"
13150-11 = "ただ、こうしてホシノちゃんと一緒にいられることが、私にとっては奇跡みたいなものなの。"
13150-13 = "……毎日毎日、こうして一緒にいるじゃないですか。 "
13150-14 = "昨日も今日も、明日もそうです。こんな当たり前なことで、何を大袈裟なことを。"
13150-15 = "はぅ……だって……。"
13150-16 = "「奇跡」というのはもっとすごくて、珍しいもののことですよ。"
13150-17 = "……ううん、"
13150-18 = "ホシノちゃん。"
13150-22 = "私は、そうは思わないよ。"
13150-23 = "ねえ、ホシノちゃん。いつかホシノちゃんにも可愛い後輩ができたら、その時は――"
13150-24 = "いつも、そばにいてあげてね？#nそういう時間こそ、奇跡みたいなものだから。"
13150-25 = "きっと、いつかホシノちゃんにも分かるよ。"
13150-27 = "こんな学校に後輩が来るなんて、"
13150-28 = "たしかに奇跡ですね。"
13150-29 = "もう、そうじゃないよホシノちゃん。"
13150-30 = "はいはい、分かりましたって。"
13150-31 = "……ふふっ。#nじゃあ、もしホシノちゃんに後輩ができたら……。"
13150-32 = "何があっても、必ず守ってあげるんだよ？"
13150-33 = "まあ、善処しますよ。"
13150-45 = "うっ……。"
13150-46 = "あれだけ攻撃したのに、"
13150-47 = "息すら上がってないなんて……。"
13150-51 = "……ごめんね。"
13150-52 = "ヘリ3台が相手じゃ、うまく手加減できなくってさ。"
13150-53 = "……これでアヤネちゃんの言う通り、前と同じことの繰り返しになっちゃったね。"
13150-54 = "先生にも、謝っておいてもらえるかな。"
13150-55 = "せっかく助けてもらったのに、ごめんって。"
13150-58 = "……。"
13150-59 = "……。"
13150-62 = "……二人はアビドスの「未来」だよ。"
13150-63 = "こんな状態の学校に来てくれて、私は嬉しかったんだ。"
13150-64 = "だから、守らなくちゃいけない。#n先輩は後輩のことを守ってあげるものだからね。"
13150-70 = "……。"
13150-71 = "でも、"
13150-72 = "それじゃあ先輩が……！"
13150-74 = "大丈夫だよ、セリカちゃん。"
13150-75 = "私は三年だから、どっちにしろ卒業が近いしね。"
13150-76 = "今度はアヤネちゃんとセリカちゃんが、後輩を守ってあげて。"
13150-79 = "みんなには、アビドスの未来を背負う役目がある。"
13150-80 = "列車砲さえなくなれば……きっと、全部解決するから。"
13150-81 = "いなくなるのは、おじさんだけで良い。"
13150-84 = "ノノミちゃん、シロコちゃん、アヤネちゃん、セリカちゃん……#nみんなで力を合わせれば、大丈夫。"
13150-85 = "ユメ先輩と私のアビドス生徒会は、今日をもって解散。#nでも対策委員会は、これからも続くから。"
13150-91 = "そしたら、次の後輩にもバトンをつないであげて。"
13150-92 = "これが、アビドス生徒会長・[ruby=くちなし]梔子[/ruby]ユメの意志を継いだ……。"
13150-94 = "副生徒会長・[ruby=たかなし]小鳥遊[/ruby]ホシノからの、最後の命令。"
13150-103 = "みんな、大丈夫？"
13150-105 = "シロコ先輩……。 "
13150-106 = "先輩が一番怪我してるじゃん……。"
13150-108 = "……ん。ホシノ先輩は？"
13150-109 = "止められませんでした……。"
13150-110 = "……力不足。"
13150-111 = "シロコ先輩、これからどうしたら良いのかな……？"
13150-112 = "私も、分からない……。"
13150-114 = "こんな先輩の姿、"
13150-115 = "初めて見るような気がしますね……。"
13150-117 = "……。"
13150-130 = "そういえば、生徒会長の契約書……。"
13150-132 = "あれがどうかしたの？"
13150-137 = "今日で、あの契約書が結ばれてから二年が経ちます。"
13150-138 = "ということは……。"
13150-140 = "会長が失踪したのは、二年前の今日……。"
13150-156 = "……ノノミちゃん、待っててね。"
13150-158 = "もう二度と……。"
13150-161 = "……あの過ちは、繰り返さない。"
13150-163 = "次回;反撃"
