[translation]
13170-1 = "Episódio 17; Perseguição"
13170-5 = "……Muito bem."
13170-6 = "O próximo é você, Sensei [USERNAME]…… é a sua vez."
13170-7 = "Em um jogo, o ataque e a defesa sempre se alternam."
13170-8 = "Claro, não pretendo ficar apenas na defensiva. Heh, hehehe……."
13170-9 = "Esta campanha é, acima de tudo, a minha busca pelo caminho.#nNão é um experimento, nem uma pesquisa, nem um ritual.#nNão há necessidade de se prender a regras."
13170-10 = "Terceira estratégia — \"O coração não pode ser previsto nem controlado\"."
13170-11 = "Desejos, culpa, medo, obsessão, lamento……."
13170-12 = "……O caos gerado pelo choque dessas coisas#nirá cair sobre você."
13170-16 = "Bem, será interessante ver como você, agora um jogador, irá superar isso."
13170-19 = "As interpretações legais apresentadas nesta obra são ficção#ne não têm relação com a realidade."
13170-24 = "[ns] \"Descobri a localização da Nonomi.\""
13170-25 = "Onde ela está!?"
13170-26 = "[ns] \"No antigo prédio administrativo da Estação Central de Abydos.\""
13170-27 = "Aquele lugar……."
13170-28 = "É onde a assembleia geral do grupo de credores será realizada."
13170-29 = "Eu até considerei a possibilidade de nos dividirmos, mas……#nisso ajuda muito."
13170-30 = "Obrigado, Sensei."
13170-31 = "Com isso, podemos capturar a Hoshino-senpai, manter o contrato e resgatar a Nonomi……#ntudo resolvido de uma vez."
13170-33 = "Como esperado, o Sensei é incrível."
13170-34 = "Sim. Quando a Serika foi levada pela Gangue dos Capacetes,#no Sensei também nos ajudou assim."
13170-35 = "Q-quando foi isso!?#nJá disse para esquecer!"
13170-36 = "……É que eu estava preocupada."
13170-37 = "Dito assim, fico um pouco envergonhada……."
13170-39 = "Ahaha……#nmas eu fiquei realmente surpresa, sabe?"
13170-40 = "Hum, a Hoshino-senpai era quem estava mais ansiosa por dentro."
13170-41 = "Ela disse que pediria ajuda ao Sensei e saiu sozinha."
13170-42 = "Isso é verdade……?"
13170-43 = "[ns1] \"É porque a Serika é muito importante para ela.\"\n[ns2] \"Mesmo que ela não costume dizer isso em voz alta.\""
13170-48 = "Você tentou ligar para ela?"
13170-49 = "……Sim. Mas parece que o celular está desligado há algumas horas……."
13170-50 = "Ela saiu do trabalho no horário de costume. Será que ela não voltou para casa depois disso?"
13170-51 = "Ela nunca ficou fora até tão tarde antes……?"
13170-52 = "Será que…… a Gangue dos Capacetes?"
13170-53 = "O quê!? A Gangue dos Capacetes pegou a Serika……!?"
13170-54 = "Por enquanto, vamos esperar. A Hoshino-senpai e o Sensei estão investigando."
13170-55 = "……."
13170-57 = "(Click)"
13170-58 = "Pessoal, esperei por vocês."
13170-59 = "Hoshino-senpai! Sensei!"
13170-60 = "[s] \"Chegamos.\""
13170-61 = "Como foi, senpai?"
13170-62 = "Usando a autoridade que o Sensei possui, conseguimos acessar a rede central gerenciada pelo Conselho Estudantil Geral."
13170-63 = "A rede central……#nProfessor, você realmente tem esse tipo de autoridade……."
13170-64 = "Uhe~ claro, foi tudo escondido. Se descobrirem, terei que escrever uma carta de desculpas, sabe?"
13170-67 = "Então foi assim……."
13170-68 = "A senpai não chegou a dizer isso, mas……"
13170-69 = "……Parece que faz tanto tempo, não é?"
13170-70 = "Hum."
13170-71 = "……Obrigada, pessoal."
13170-73 = "[ns] \"Como sensei, é o meu dever.\""
13170-78 = "08:5X AM"
13170-80 = "Bem, vamos começar a reunião!"
13170-84 = "Precisamos comparecer à \"Assembleia Geral do Grupo de Credores\" que será realizada no antigo prédio da administração da Estação Central de Abydos.#nO prazo final é hoje ao meio-dia."
13170-85 = "Nosso objetivo é resgatar a Nonomi-senpai, que está sendo mantida em cativeiro."
13170-86 = "E, antes que a Hoshino-senpai negue a existência do Conselho Estudantil de Abydos,#nreivindicaremos a legitimidade do Comitê de Contramedidas."
13170-87 = "Entendido, Presidente do Conselho Estudantil."
13170-88 = "……."
13170-89 = "O que foi, Ayane-chan?#nVocê é a presidente do conselho, precisa se acostumar logo."
13170-90 = "E-eu só me tornei presidente do conselho por causa do contrato, então……."
13170-91 = "[s3] \"Vamos mostrar o poder da Presidente Ayane!\"\n[s4] \"Contamos com você, Presidente Ayane.\""
13170-94 = "……Como preciso me pronunciar na assembleia, desta vez eu também irei ao local."
13170-96 = "Ah, ela desconversou."
13170-97 = "Ela fugiu."
13170-99 = "Vamos passar para a próxima reunião de estratégia!"
13170-100 = "Atualmente, a rota que leva à Estação Central de Abydos#nestá bloqueada pelas forças do fundo de investimento privado."
13170-102 = "Antigo Prédio da Administração da Estação Central - Distrito Leste"
13170-103 = "O Distrito Leste está sendo guardado pelo Grupo dos Capacetes Fofos."
13170-104 = "Deixando de lado a força individual, o número deles é avassalador."
13170-105 = "Como nosso tempo é limitado, devemos evitar esta rota."
13170-107 = "Antigo Prédio da Administração da Estação Central - Distrito Oeste"
13170-111 = "O Distrito Oeste está concentrado com a Guarda do Mercado."
13170-112 = "É muito provável que eles estejam usando helicópteros de combate, tanques e armas pesadas poderosas."
13170-113 = "A menos que tenhamos uma vantagem tática, também queremos evitar este local."
13170-115 = "Antigo Prédio da Administração da Estação Central - Distrito Sul"
13170-117 = "O Distrito Sul é do Grupo Kurokame."
13170-118 = "Como eles possuem uma grande quantidade de torres de artilharia não tripuladas, não acho que será fácil chegar perto……."
13170-120 = "Antigo Prédio da Administração da Estação Central - Distrito Norte"
13170-123 = "O Distrito Norte parece ser um grupo de mercenários contratados, mas#nparece que barricadas especiais foram instaladas lá."
13170-124 = "A capacidade de combate deles não é tão alta, mas#nserá difícil romper com equipamentos comuns."
13170-127 = "……Qual rota devemos escolher?"
13170-128 = "Não deveríamos escolher o caminho que a Hoshino-senpai usaria?"
13170-129 = "Nesse caso, precisamos pensar sob a perspectiva da senpai……."
13170-130 = "A Shiroko-senpai deve saber!"
13170-132 = "Hmm……."
13170-133 = "É verdade……#nShiroko-senpai, qual rota você acha que ela escolheria?"
13170-134 = "……A força da Hoshino-senpai é o combate corpo a corpo."
13170-135 = "Ouvi dizer que, antigamente, o estilo de luta dela era ainda mais imprudente."
13170-136 = "Provavelmente, ela está acostumada a lutar contra oponentes com muitas armas pesadas."
13170-137 = "Por isso……."
13170-142 = "Antigo Prédio da Administração da Estação Central - Distrito Oeste"
13170-146 = "Quem está aí!"
13170-154 = "A-aquela ali é……!"
13170-155 = "Ela veio, é a Takanashi Hoshino!"
13170-164 = "P-para onde ela foi!?"
13170-188 = "……Acho que é o Distrito Oeste."
13170-189 = "Então, vamos nessa!"
13170-196 = "Concentrem todas as forças na Takanashi Hoshino!"
13170-197 = "Não a deixem passar de jeito nenhum até a assembleia começar!"
13170-199 = "S-sim, senhor!"
13170-204 = "……De novo um helicóptero?"
13170-207 = "Posição do alvo confirmada!"
13170-208 = "Às 6 horas!!"
13170-213 = "Alvo confirmado, travado."
13170-219 = "Míssil ar-terra AGM-114, disparar!"
13170-226 = "Alvo atingido!"
13170-231 = "O quê……!?"
13170-239 = "Está vindo na nossa direção……!"
13170-240 = "Do que você está falando?#nNós estamos no ar――"
13170-248 = "A, aonde ele foi parar!?"
13170-249 = "Em, embaixo!#nEle está pendurado no trem de pouso do helicóptero!"
13170-255 = "A, aaah!?"
13170-264 = "O que está acontecendo……."
13170-269 = "Droga……."
13170-274 = "Parece que falhamos."
13170-276 = "Cale a boca, Nephthys!"
13170-288 = "O que significa isso?"
13170-289 = "Os planos de vocês, eu já sei há muito tempo."
13170-290 = "Planos, é……."
13170-291 = "Vocês estão tentando trair o fundo privado, não estão?"
13170-304 = "Ka, Kaiser PMC!?"
13170-310 = "Cuidado com o que diz."
13170-311 = "O canhão ferroviário é nosso desde o início."
13170-317 = "A, ataquem!"
13170-331 = "E, esse som é……?"
13170-333 = "……."
13170-338 = "Antigo Edifício da Estação Central - Distrito Oeste"
13170-348 = "Ca, capturem ele!"
13170-357 = "09:4X AM"
13170-360 = "O que está acontecendo aqui!"
13170-361 = "A Hoshino-senpai está……."
13170-366 = "……Encontrei, a 600 metros de distância!"
13170-367 = "700m, 750m…… está se afastando cada vez mais!"
13170-369 = "Não está rápido demais……!?"
13170-370 = "Vamos persegui-lo."
