[translation]
1402-1 = "GUNS N' PEPPERS（２）"
1402-2 = "エンジニア部・作業室"
1402-3 = "準備はいいかい、コトリ？"
1402-4 = "もちろんです、先輩！準備万端です！"
1402-5 = "さあ……お披露目の瞬間。"
1402-7 = "じゃーん！遂に完成です！#nこれが私たちエンジニア部の新しい発明品、チャバスコ噴射装置の付いたサブマシンガン！"
1402-8 = "思ったより、見た目は普通のサブマシンガンといった感じだね。#nでも、ちゃんと作動するんだろう？"
1402-9 = "もちろんです、先輩！銃弾の代わりに、唐辛子とお酢を配合した特製の弾丸が必要ですが！"
1402-10 = "その特殊弾をマガジンに入れて引き金を引けば、火薬の爆発によって唐辛子の成分が超速発酵して……"
1402-11 = "ブシュッッッ！！"
1402-12 = "こうして銃口からチャバスコが噴射されます！"
1402-13 = "どれどれ……。"
1402-16 = "……なるほど、これは確かにチャバスコだ。それに、お店で売ってるのと同じ味だね？"
1402-17 = "この味を再現するため、実験に実験を重ねましたから！#nミレニアムの技術の真髄を、全てこの銃に詰め込みました！"
1402-18 = "しかも、フルオートモードに変更すれば、1秒間に1Lのチャバスコを噴射することができる……。"
1402-19 = "ダダダダダダダッ！"
1402-20 = "ふふっ！この銃さえあれば、これからはいつどこでピザを食べるとしても、思う存分チャバスコがかけられます！"
1402-21 = "なるほど、これは驚きだ。想像以上だね。"
1402-22 = "この銃は本当に、完璧なまでに……"
1402-23 = "……何の役にも立たないな？"
1402-24 = "それは、そうですね……。#nこの銃を持ち歩くぐらいなら、小分けのチャバスコを持ち歩く方が、圧倒的に楽で経済的ですし。"
1402-25 = "それに使った後は、銃口がチャバスコでべったりになるから掃除も面倒……#n衛生的にも問題がある……。"
1402-27 = "ふふ……まあ、面白いから良いさ。"
1402-28 = "発明というのは、いつも満足できる成果が出るというわけでは無い。どんなものでも、その過程を楽しむことができてこそ、いつか自然と偉大な成果も伴ってくるというもの。"
1402-29 = "そうですね！今回の実験を進めるに当たって、液体噴射装置について幾つものノウハウを手に入れることができました。これらの技術は今後、色々と応用していけると思います。"
1402-30 = "失敗は成功の母って言うし……。"
1402-33 = "……ところで、改造に使われたこの銃は誰のだい？"
1402-34 = "え？この銃ってウタハ先輩の物じゃなかったんですか？"
1402-35 = "私のはこれよりもっと小さい物だよ。#nそれに、あれは厳密に言えば銃床がないマシンピストルだ。これはサブマシンガンだろう？"
1402-36 = "でも、これ私のではないですよ？"
1402-37 = "……私のでもない。"
1402-38 = "……待って。この、無駄に派手な龍の模様……。"
1402-39 = "こんな模様を銃に刻み込むような人といえば……。"
1402-42 = "ああ、ようやく修理が終わったのか？#nエンジニア部にしては珍しく時間かかったな。"
1402-43 = "ね、ネル先輩……！？#nど、どうしてここに？"
1402-44 = "あぁん？どうしてって、前に修理に出したあたしの銃を受け取りに来たんだけど。#n何か問題でもあんのか？"
1402-45 = "そ、そ、そうでした……そうでした！？#nう、うっかりしてました。あはは……。"
1402-46 = "ん、何だ、うっかりって言いつつ、ちゃんとあたしの銃出して待ってたんじゃねぇか。#n修理は終わったんだろ？じゃあ引き取らせてもらうからな。"
1402-47 = "ま、待ってください！この銃にはまだ問題が……！"
1402-48 = "はぁ？あんなに時間あったのにまだ修理終わってねぇのか？#nじゃあさっき遠くから聞こえた「完成です」ってのは何だったんだよ？"
1402-49 = "……まさかてめぇら、あたしの銃の修理を受けておいて、その間に他のことをしてたんじゃねぇだろうな！あぁん？！"
1402-50 = "い、いえ、そんなことは……！"
1402-51 = "あっそ、なら問題ないな。#nじゃ、受け取ってくぞ。"
1402-53 = "は、はいっ……お、お気をつけてー……。"
1402-54 = "ああ、ご苦労さん。またがっつり使わせてもらうぜー。"
1402-56 = "せ、せせせせ先輩！どうしましょう！？#nネル先輩が、改造された銃をそのまま持っていっちゃいました！？"
1402-57 = "自分の銃がチャバスコ・ディスペンサーにされたことがわかったら、私たちきっと、ただじゃすまないだろうね……。"
1402-58 = "もう終わりです……今すぐにでも激怒したネル先輩が戻ってきて、私たちをチャバスコまみれにしてしまうに違いありません……！"
1402-59 = "二人とも落ち着いて、まだバレたわけじゃない。"
1402-60 = "ネルに気づかれないうちに銃を取り戻して、修理さえできれば、穏便に済む話だ。"
1402-61 = "ネル先輩に気付かれずに銃を奪うってことですか！？そんな、それならむしろ、怒ったライオンの首輪に鈴を付けてくるミッションの方が、まだ現実味があります！"
1402-62 = "それ、どっちにしろ最後は死ぬのは既定路線、ってことだよね……。"
1402-63 = "まず私が、ネルの銃と入れ替える用のダミーを作る。それが出来るまで、二人はネルが引き金に触れないように気を引いておいてほしい。"
1402-64 = "ですが……それが完成する前に、ネル先輩が自分の銃の異常に気が付いてしまったらどうしましょう？"
1402-65 = "それは、考えたくもないが……。"
1402-66 = "どうか彼女の忍耐が途切れないことを、祈るとしよう。"
