[translation]
1502-1 = "Trouble & Trackers（２）"
1502-2 = "ミレニアム・セミナー執務室"
1502-4 = "ユウカ、身体測定に使った体重計を持ってきた。これで最後。"
1502-5 = "お疲れ様、エイミ。"
1502-6 = "ふぅ……もしかしたら身体測定の結果に不満を持った生徒たちが騒ぎたてるんじゃないかって心配してたけど、幸いなことに今回は何も起きなかったわね。"
1502-7 = "今回「は」？"
1502-8 = "ミレニアムの生徒は曲者揃いだから、身体測定がある度に、自分で開発した発明品を持ち込んで騒ぎ立てたりする生徒が結構いるのよ。"
1502-9 = "ジェット装置付きの靴を履いたまま体重を計らせてっていう生徒とか、パワードスーツを着てきてこのまま筋力を測定してほしいっていう生徒とか……。"
1502-10 = "どうしてみんな、身体測定は「自分の正確な発育状態の現状」を把握するための検査だってことを理解できないのかしら。"
1502-11 = "そうなんだ、不思議だね。"
1502-12 = "もちろん、その気持ちは分からないわけじゃないわ。#n私も今回の身体測定、体重計の目盛りをゴリっといじりたかったし。"
1502-13 = "うう……ゲーム開発部のあの子たちに付き合いながら、お菓子食べ過ぎた……。"
1502-14 = "ユウカの権限があれば、学籍データの記録ぐらい簡単に修正できるでしょ？"
1502-15 = "それはダメ！セミナーの役員ともあろう者が権限を悪用した暁には、学校の風紀がめちゃくちゃになっちゃうでしょ？"
1502-16 = "セミナーの会計は、誰よりも公正でないといけないの！"
1502-17 = "そうなんだ……。"
1502-22 = "ユウカ。学籍データに新しい記録を入力したいんだけど、パスワードなに？"
1502-23 = "学籍データのパスワード？特に設定した記憶はないから、初期設定のままのはずだけど？"
1502-24 = "＜1q2w3e4r＞って入力してみて。"
1502-29 = "……あ、行けた。ありがとう。"
1502-31 = "ヴェリタス・ハッカー休憩所"
1502-32 = "……傍受完了。"
1502-33 = "さっすがコタマ先輩！"
1502-34 = "で、学籍データのサーバーに接続するパスワードは分かった？"
1502-35 = "はい、ユウカさんは初期設定のパスワードをそのまま使っていました。"
1502-36 = "え？ミレニアムの会計ともあろう人が、パスワードを変えずにそのまま使ってるの？#n……セキュリティ意識低すぎない？"
1502-37 = "そのお陰で私たちみたいなハッカーとかは、こうやって容易く侵入とかできちゃうわけだけど。"
1502-38 = "これで私のドローンの出番だね。ちょっとだけ待ってて。#nローカルネットワークに接続できる物理サーバーのところまで、ドローンを行かせる。"
1502-44 = "……侵入完了、接続端子を繋げたよ。"
1502-45 = "ここからはマキ、できるよね？"
1502-46 = "もっちろん、任せて！"
1502-50 = "ハレ先輩のドローンが接続したノードから、繋がった装置をスキャンして……。"
1502-54 = "プロキシサーバーに過負荷をかけて無力化させた後に……。"
1502-58 = "傍受したパスワードを使って管理者権限を乗っ取れば……。"
1502-64 = "イエス！身体測定記録の修正権限、手に入れた！"
1502-65 = "さあ、どこから修正しようか？"
1502-66 = "とりあえず体重を10kg減らして、背は10cmぐらい伸ばして、胸囲を90cmに……。"
1502-67 = "その体型でその体重、いくらなんでも現実離れし過ぎてない？"
1502-68 = "マキ、私もそんな感じでお願いします。"
1502-69 = "ふふっ、どんどん言って。いくらでも直しちゃうから！"
1502-74 = "ん？なに、このデータ。#nセミナーの会計……あ、ユウカ先輩の身体測定記録だ。"
1502-75 = "最近ちょいちょい邪魔されてばっかりだし……この機会にいたずらでもしちゃおっか？"
1502-76 = "いたずら？"
1502-77 = "データを操作して、ユウカ先輩の体重を100kgに変えておこうかなって！"
1502-78 = "そしたら、後で自分の体重を確認した時にびっくりするんじゃん？ふふふっ……。"
1502-79 = "堂々と口にした割には、些細な復讐だね……。"
1502-88 = "あ、あれ？急にキーが効かなくなった！どうなってるの！？"
1502-89 = "誰かがサーバーの向こう側から、逆方向にハッキングを仕掛けてきているようです。あと10秒……！"
1502-90 = "マキ、今すぐログを消して接続を遮断！"
1502-91 = "で、でも！#nやっと手に入れたデータを諦めるのは、勿体ないし……！"
1502-92 = "ん、近くに何か別のノードが……えぇぃっ、分かんないけど！とりあえずどこでもいいからコピー！"
1502-98 = "＜SYSTEM＞「student_data」フォルダから「social_network」フォルダに、ファイルをコピーしています……"
1502-99 = "っ！マキ、今何してる！？"
1502-100 = "え？権限を奪われる前にデータをバックアップしておこうかと……。"
1502-101 = "今学籍データをアップロードしたところ、全体公開のSNSサーバー！"
1502-102 = "……やっちゃった。"
1502-104 = "ミレニアム・セミナー執務室"
1502-105 = "……あれ？"
1502-106 = "どうしたの、エイミ？珍しく驚いた顔してるけど。"
1502-107 = "ユウカ。まさかとは思うけど、生徒たちの身長と体重って、外部に公開される情報？"
1502-108 = "え？そんなわけないじゃない。今日測定した生徒たちの情報は、最高レベルのセキュリティシステムで厳重に管理されてるわ。たとえヴェリタスのハッカーたちだとしても、あの情報には手が出せないはずよ？"
1502-109 = "でも今校内SNSに、みんなの身体測定記録がアップロードされてるよ。"
1502-110 = "な、なんですって！？"
1502-115 = "ほ、本当だ。誰がこんなことを？#n……それに、どうやって？"
1502-119 = "ユウカ。"
1502-120 = "な、なに？"
1502-121 = "確かに太ったね。これはちゃんとした食事管理が必要そう。"
1502-122 = "はあっ？？き、急になによその暴言は！？"
1502-123 = "も、もちろん去年に比べたら体重がちょっとだけ増えたけど……まだ平均体重の範囲内よ！？"
1502-124 = "でも、SNSに上がってるユウカの記録には、体重が100kgって……。"
1502-129 = "そんなわけっ、ないでしょうがああぁぁぁぁーーー！！"
