[translation]
1503-1 = "Trouble & Trackers (3)"
1503-2 = "Sala de Descanso dos Hackers da Veritas"
1503-4 = "Confirmei comandos maliciosos via injeção de código, um backdoor foi criado."
1503-5 = "Ah, não, tem um hack vindo de outro caminho também..."
1503-7 = "Hare-senpai, socorro! Dá um jeito nisso!"
1503-8 = "Eu não sou um robô gato milagroso, então não adianta pedir para eu dar um jeito..."
1503-9 = "Mas se continuar assim, além de não conseguirmos corrigir os dados acadêmicos, até o nosso PC vai ser invadido!"
1503-10 = "Com a minha força é impossível! Por favor, me ajuda!"
1503-14 = "Haa, não tem jeito. Criar códigos de defesa não é minha especialidade, mas vou tentar fazer um pouco..."
1503-19 = "Se eu camuflar o conteúdo do pacote e induzi-lo a entrar no caminho errado... hein? Já foi bloqueado?"
1503-23 = "Então, vou plantar uma bomba lógica na pasta onde o ataque é esperado para induzir uma sobrecarga... isso também?"
1503-28 = "Hum, que problema. Com a minha força, isso pode ser difícil..."
1503-29 = "N-não pode ser! A Hare-senpai tendo dificuldades com um hack!?"
1503-30 = "É como se estivessem prevendo nossas ações, respondendo em tempo real a todos os padrões."
1503-31 = "É difícil acreditar que existia alguém tão habilidoso fora da Veritas."
1503-32 = "Hare. Por causa do atraso na conexão, o tráfego está aumentando cada vez mais."
1503-33 = "Se continuar assim, corremos o risco de nossa identidade ser descoberta pelo Seminar..."
1503-34 = "Exatamente. #n Maki, desta vez é uma pena, mas vamos desistir de corrigir os registros dos dados acadêmicos."
1503-36 = "Uuu... não tem jeito. Não quero ser chamada pelo Seminar para levar bronca..."
1503-37 = "Conexão encerrada. Hare-senpai, recolha os drones também."
1503-38 = "<SYSTEM> Deletando logs... Encerrando o sistema."
1503-40 = "(No entardecer do dia do incidente...)"
1503-44 = "Cheguei."
1503-45 = "Ah, quanto tempo, senpai..."
1503-46 = "...Aconteceu alguma coisa? Por que estão todos tão desanimados?"
1503-47 = "É que sentimos o limite das nossas capacidades novamente..."
1503-48 = "O mundo é vasto e há muitas pessoas habilidosas..."
1503-50 = "Estávamos hackeando de manhã, quando um hacker desconhecido contra-atacou no meio do caminho."
1503-51 = "Até a Hare-senpai foi derrotada em um instante. #n Quem diria que existia alguém tão habilidoso fora da Veritas..."
1503-52 = "Sério? Alguém tão habilidoso que até a Hare se rendeu, isso é incrível..."
1503-53 = "Falando em 'hacker desconhecido', eu também encontrei alguém incrível enquanto inspecionava o servidor de dados acadêmicos agora pouco."
1503-54 = "Não sei por que, mas era um hacker que insistia em pegar apenas os registros de medição física. A resposta foi incrivelmente rápida, quase fui pega também."
1503-55 = "...Hm? Servidor de dados acadêmicos?"
1503-56 = "Então, será que a pessoa contra quem lutamos agora pouco era..."
1503-57 = "A vice-presidente, por acaso?"
1503-59 = "...Hein? Não me diga que quem hackeou os dados acadêmicos e causou aquele alvoroço agora pouco... foram vocês?"
1503-60 = "Haa, eu estava achando que o método era familiar..."
1503-61 = "Então estávamos lutando uma batalha perdida desde o início."
1503-62 = "Se eu tivesse perdido para um hacker que nem conheço, ficaria frustrada, mas se a oponente é a vice-presidente da Veritas, não tem jeito."
1503-63 = "I-isso mesmo! Ficou provado que não existem hackers mais competentes que nós da Veritas, que bom, que bom!"
1503-65 = "Não é nada bom!! #n O que vocês acham que são as informações pessoais dos outros?"
1503-69 = "Já que chegamos a esse ponto, vou ter que ensinar a ética hacker para vocês com rigor... Vamos, venham aqui agora!"
1503-70 = "Isso não, por favor!? Senpai, me desculpa, me perdoa, aaaaah!"
1503-72 = "Corredor do prédio escolar de Millennium"
1503-73 = "(Alguns dias após o incidente...)"
1503-77 = "Aquela é a pessoa dos boatos...?"
1503-78 = "Sim, a Yuuka da contabilidade, que descobriram na última medição física que pesa 100kg."
1503-79 = "Olhando assim, ela não parece tão gorda... será que ela usa algum equipamento especial?"
1503-80 = "Talvez ela esteja usando um holograma sobre o corpo para projetar uma 'imagem de quando ela era magra'!"
1503-81 = "...Não tem como ser isso, né!? Se eu tivesse tempo para desenvolver um equipamento tão inútil, eu teria começado a me exercitar desde o início!"
1503-82 = "Eu já publiquei um aviso dizendo que a informação anterior era mentira! Por que os rumores estão aumentando a cada dia!?"
1503-87 = "Ah, chega! Quem diabos é o culpado? Quando eu pegar essa pessoa, não vou perdoar!!!"
1503-88 = "Trouble & Trackers"
