[translation]
1600706-1 = "Eu não cometi falha alguma, e isso também não consta nos registros."
1600706-2 = "Seja muito bem-vindo, Sensei."
1600706-3 = "Eu acreditava piamente que, se fosse o Sensei, você certamente viria correndo ao ver um aluno em apuros."
1600706-4 = "[s] \"Correndo... ou sendo ameaçado, no caso...\""
1600706-5 = "Ora, que ameaça? Eu apenas fiz um pedido, nada mais."
1600706-6 = "[s] \"Se eu fugisse e desse errado, você me levaria junto, não é?\""
1600706-7 = "Isso é óbvio. Afinal, o Sensei e eu compartilhamos o mesmo destino."
1600706-8 = "Minha falha é a falha do Sensei; se eu for expurgada, o Sensei também será..."
1600706-9 = "O que chamamos de responsabilidade solidária!"
1600706-10 = "[ns] \"Entendi... mas, por que estamos na cozinha?\""
1600706-14 = "É porque o desafio que tenho em mãos agora é o \"desenvolvimento de um novo doce\"."
1600706-15 = "A propósito... Sensei, você conhece algum doce feito com pimentão?"
1600706-16 = "[s] \"Doce feito com pimentão...?\""
1600706-17 = "Sim. Na verdade, mês passado, por um erro de um membro do Departamento de Refeições, uma quantidade enorme de pimentões foi encomendada na Academia Red Winter."
1600706-18 = "Embora o responsável pela cozinha tenha sido expurgado imediatamente, a Presidente Cherino disse: \"Não comerei pimentão de jeito nenhum, dê um jeito de resolver isso\"..."
1600706-19 = "Então, pensei em desenvolver um doce com pimentão para agradar até mesmo a Presidente, que é muito seletiva com a comida."
1600706-20 = "[s] \"Você é como uma guardiã, ou algo do tipo...\""
1600706-21 = "Fufu, ver a Presidente Cherino comendo algo com gosto é algo que acalma o coração, não é?"
1600706-22 = "No entanto, estou preocupada em como transformar o pimentão, com seu amargor e adstringência, em um doce..."
1600706-23 = "Eu adoraria ouvir a sua opinião, Sensei."
1600706-24 = "[s1] \"Que tal começar secando eles...?\"\n[s2] \"E se você os deixar de molho no açúcar?\""
1600706-25 = "Entendo... De fato, já vi vegetais secos sendo vendidos como petiscos."
1600706-26 = "Além disso, se perderem a água e se concentrarem, talvez o gosto do vegetal diminua...?"
1600706-27 = "Entendo... De fato, a doçura do açúcar parece ser capaz de esconder o amargor até certo ponto."
1600706-28 = "Além disso, ao perder a umidade, a textura deve ficar mais macia..."
1600706-29 = "Que ideia maravilhosa. Como esperado do Sensei!"
1600706-30 = "Então, vou preparar tudo para o cozimento imediatamente."
1600706-35 = "Depois disso, tentamos preparar o pimentão de várias maneiras."
1600706-37 = "Hmm... ainda falta aquele toque final, por assim dizer..."
1600706-38 = "Não importa o quanto eu adicione doçura ou tente aproximar a textura de um doce, o amargor característico do pimentão ainda persiste um pouco..."
1600706-39 = "É duvidoso que a Cherino-chan aceite comer isso como um doce..."
1600706-40 = "[s] \"Será que ela não aceitaria se soubesse que você se esforçou ao máximo?\""
1600706-41 = "Isso significa que devo relatar o fracasso à Presidente?"
1600706-42 = "Não posso fazer isso. Em nome da Presidente, falhas não devem existir! A Presidente deve estar sempre correta!"
1600706-43 = "Hmm... se a Cherino-chan perguntar sobre os pimentões depois, talvez se eu preparar um pudim de luxo..."
1600706-47 = "...Então, o plano de fazer doces com pimentão nunca existiu desde o início. Ficamos assim, certo, Sensei?"
1600706-48 = "[s] \"Mas e essa montanha de doces de pimentão...?\""
1600706-49 = "Isso também é apenas uma questão de descartar e fingir que nunca aconteceu."
1600706-50 = "Dito isso, seria um desperdício jogar fora... Sensei, você vai me ajudar a eliminar as evidências, não vai?"
1600706-52 = "Depois disso, dividi os doces de pimentão com a Tomoe e comemos juntos."
1600706-53 = "...Ainda assim, o que sobrou foi distribuído para os alunos da Red Winter que estavam com fome."
