[translation]
1600603-1 = "Izumi e o ingrediente secreto"
1600603-3 = "[ns1] \"Então, Izumi, para onde estamos indo?\"\n[ns2] \"Não deveríamos ir para a praia?\""
1600603-4 = "Fufufu..."
1600603-5 = "Fufufu..."
1600603-6 = "Você ainda é muito ingênuo, Sensei! As iguarias de verão não estão apenas na praia, sabia!"
1600603-7 = "De acordo com a minha pesquisa, tem uma loja bem famosa por aqui...!"
1600603-8 = "[s] \"Alguém do Clube de Pesquisa Gastronômica te contou isso?\""
1600603-9 = "Não, foi uma vovó que passou por mim na praia!"
1600603-10 = "Ela parecia estar com dificuldades com a bagagem, então eu ajudei, e ela me deu um biscoito de arroz."
1600603-11 = "Aquele biscoito de camarão era tão delicioso... parecia comum, mas no momento em que dei uma mordida, o aroma concentrado de camarão..."
1600603-12 = "[s] \"Izumi, você está divagando completamente...\""
1600603-13 = "Ah! *Babando*..."
1600603-14 = "E-ei, sobre o que estávamos falando mesmo?"
1600603-15 = "Ah, é verdade! Aquela vovó me contou que tem uma barraca famosa por servir \"Hiyashi Chuka\" logo ali na frente!"
1600603-16 = "Eu queria muito ir comer lá hoje!"
1600603-20 = "Chegamos!"
1600603-21 = "É aqui a tal loja de Hiyashi Chuka!"
1600603-22 = "[s] \"Mas, como posso dizer...\""
1600603-25 = "Ué, deveria ser uma especialidade local, mas não tem ninguém aqui...?"
1600603-26 = "Será que... faliu!?"
1600603-27 = "Ah não, e eu andei 30 minutos debaixo desse sol escaldante!"
1600603-28 = "Foi tudo em vão!? Que droga!"
1600603-29 = "[s] \"Ei, é melhor não dizer essas coisas na frente da loja...\""
1600603-30 = "E-eu ainda não fali!"
1600603-31 = "Droga... tudo isso é culpa daquela nova casa de praia que abriram ali perto..."
1600603-32 = "Eles roubaram todos os nossos clientes para aquela loja administrada pelo tal \"Campeão de Derrubada de Postes de Kivotos\"..."
1600603-33 = "Ah, então não faliu?"
1600603-34 = "Então, dois Hiyashi Chuka, por favor!"
1600603-35 = "[s] \"Deveríamos ouvir um pouco mais o que ele tem a dizer!\""
1600603-37 = "Dois Hiyashi Chuka saindo!"
1600603-39 = "Uau, que lindo! E parece delicioso!"
1600603-40 = "Então, vamos lá, itadakimasu...!"
1600603-45 = "[ns] \"E então?\""
1600603-46 = "...Hmm, está gostoso, mas... falta alguma coisa."
1600603-47 = "Isso é, hum, o que será... Ah, já sei!"
1600603-49 = "[s] \"Izumi, o que você acabou de colocar aí?\""
1600603-50 = "Isso? É a minha manteiga de amendoim caseira!"
1600603-51 = "Misturando tudo assim... pronto, perfeito!"
1600603-52 = "Agora deve ter ficado ainda mais gostoso! Quer provar, Sensei?"
1600603-53 = "[s3] \"Hiyashi Chuka com manteiga de amendoim...!?\"\n[s4] \"Você disse que era caseira, mas que tipo de...\""
1600603-60 = "Aqui, Sensei! Aaaah!"
1600603-61 = "(...)"
1600603-62 = "(Preparei-me e provei o Hiyashi Chuka com manteiga de amendoim que a Izumi me ofereceu)"
1600603-63 = "(Mastigando...)"
1600603-64 = "(...Engolindo)"
1600603-67 = "(Isso é... o caldo e os ingredientes do Hiyashi Chuka combinados com a doçura rica da manteiga de amendoim criaram um conjunto sublime!)"
1600603-68 = "[s] \"P-por que!? Por que isso está gostoso!?\""
1600603-69 = "Viu só!? Eu sabia que ia combinar!"
1600603-70 = "Vou comer o meu também!"
1600603-73 = "Hum, continua delicioso!"
1600603-74 = "[s] \"P-por que……?\""
1600603-77 = "（No dia seguinte……）"
1600603-78 = "Eeeehhhhhhh!? P-por que tem tanta gente aqui hoje!?"
1600603-79 = "[s] \"Não parece o mesmo lugar de ontem, né.\""
1600603-80 = "Eu queria comer outra coisa, não macarrão frio!"
1600603-81 = "Desse jeito, nós, a dupla gourmet do verão, não vamos ter onde sentar! O que a gente faz, Sensei!?"
1600603-82 = "[s] \"Você gostou mesmo desse nome, hein…….\""
1600603-83 = "Hmmmm…… não tem jeito, vamos para outro restaurante."
1600603-84 = "Aquela senhora também me indicou um lugar gostoso que não é de macarrão frio."
1600603-85 = "É uma pena, mas vamos lá hoje!"
1600603-87 = "[ns] \"Aqui?\""
1600603-88 = "Sim, dizem que é um restaurante famoso por \"Unaju\"."
1600603-89 = "Mas aqui também não tem quase ninguém……"
1600603-90 = "Será que faliu!?"
1600603-91 = "Não pode ser, né!? É só porque ainda não abriu, né!?"
1600603-92 = "N-não faliu, cliente……!"
1600603-93 = "É que a maioria dos clientes foi para o restaurante do \"Campeão de Bo-taoshi de Kivotos\" e, por algum motivo, para a barraca de macarrão frio que começou a lotar do nada esta manhã……."
1600603-95 = "Ainda bem!"
1600603-96 = "Dois Unaju, por favor!"
1600603-98 = "Obrigado pela espera, aqui está o Unaju!"
1600603-100 = "Eba! Então, vamos lá……"
1600603-105 = "……Hmmmmmm?"
1600603-106 = "Hmm, hummmm……?"
1600603-107 = "[s] \"Por acaso, isso é…….\""
1600603-108 = "Sim, é gostoso, com certeza…… mas……."
1600603-109 = "Por que será, hmm……."
1600603-110 = "[s] \"Sente que falta alguma coisa?\""
1600603-111 = "Sim, isso! Falta um pouquinho de alguma coisa!"
1600603-112 = "Sinto que falta aquele toque final, hmm…… isso só pode ser……."
1600603-117 = "[ns] \"Por acaso, isso seria……?\""
1600603-118 = "Sim, nessas horas, acho que a minha manteiga de amendoim caseira resolve!"
1600603-123 = "Então, vamos lá de novo, nham nham nham……"
1600603-124 = "Sim, eu sabia! Ficou ainda mais gostoso!!"
1600603-125 = "Quer um pouco, Sensei?"
1600603-126 = "[s] \"Bem…….\""
1600603-131 = "Vamos lá, Sensei. Aaaaa……!"
1600603-134 = "（O sabor doce e defumado da enguia se espalha pela boca com um leve amargor, e o sabor da manteiga de amendoim, que envolve tudo suavemente, cria uma harmonia……）"
1600603-135 = "（O Unaju evoluiu!）"
1600603-136 = "Viu, é gostoso, né?"
1600603-137 = "A manteiga de amendoim tem um poder misterioso! Dizem até que, se você passar no pão, o lado com manteiga sempre cai virado para baixo!"
1600603-138 = "Manteiga de amendoim é incrível!"
1600603-139 = "[s5] \"Isso parece um pouco diferente……?\"\n[s6] \"Mas é gostoso…… por que isso é gostoso……?\""
1600603-140 = "Humpf! Eu sou um membro do Clube de Pesquisa Gourmet, sabia?"
1600603-141 = "Humpf! Eu sou um membro do Clube de Pesquisa Gourmet, sabia?"
1600603-142 = "Pode deixar a comida com a gente, esse tipo de arranjo é o básico!"
1600603-143 = "（Embora a mente não conseguisse entender, a língua estava feliz, e o mistério só aumentava……）"
1600603-146 = "（No dia seguinte, ao ir ao restaurante de Unaju……）"
1600603-147 = "Uéééé!? Está lotado de novo!?"
1600603-148 = "Até ontem, estava às moscas, parecia que ia fechar a qualquer momento! Por quê!?"
1600603-149 = "[s] \"Izumi, tente ser um pouco mais gentil no jeito de falar…….\""
1600603-150 = "Waaaaah! E eu que estava com tanta vontade de comer um \"umaki\" hoje!"

1600603-151 = "Mas por que isso acontece em todos os lugares que eu vou...?"
1600603-156 = "Ah, é aquela garota! Quando ela coloca as mãos em qualquer prato, ele vira um sucesso instantâneo...!"
1600603-157 = "Eu sei que parece surpreendente, mas é verdade!"
1600603-158 = "É ela!"
1600603-159 = "Entendo, então aquela garota é...!"
1600603-160 = "A lendária consultora gastronômica que consegue reviver qualquer restaurante à beira da falência num piscar de olhos!?"
1600603-161 = "[s] \"...Hã?\""
1600603-162 = "Por favor, por favor, nos ajude também!"
1600603-163 = "Conte-nos o segredo! Dê-nos um conselho!"
1600603-164 = "Ajude-nos, mocinha!"
1600603-166 = "Hueeeeh!? O-o que, o que é isso! O que está acontecendo!?"
1600603-167 = "[s] \"Izumi, vamos fugir daqui agora.\""
1600603-168 = "Ma-mas eu só queria comer um monte de iguarias de verão~~~!!"
1600603-170 = "(Conseguimos nos desvencilhar dos donos de restaurantes que nos cercavam e fugimos com a Izumi até a beira da praia)"
