[translation]
1600320-1 = "大切なパートナー"
1600320-2 = "（到着したよ、とスズミにメッセージを送った）"
1600320-6 = "（ほどなくして、遠くから近づいてくるスズミの姿が見えた）"
1600320-11 = "はぁ……はぁ。も、申し訳ありません、先生。#nお待たせすることになってしまい……。"
1600320-12 = "……あ。"
1600320-20 = "……し、失礼しました。"
1600320-21 = "[s1] \"あれ、何かあった？\"\n[s2] \"ヘッドホンを外してどうしたの？\""
1600320-24 = "い、いえ、大したことでは……。"
1600320-25 = "……すみません、こちらを外しておりまして。"
1600320-32 = "その……。"
1600320-33 = "普段からパトロールの時に、よく使っているヘッドホン、なのですが……。"
1600320-34 = "急いでいたので、つけたまま来てしまって……。#nも、もちろん曲は停止していたのですが、ただ……。"
1600320-35 = "……いえ、何でもありません。私の話で足を止めてしまいましたね。#n先生のスケジュールを遅らせるわけにはいきませんので、急ぎご案内いたします。"
1600320-36 = "で、では、行きましょう……。"
1600320-44 = "…………。"
1600320-45 = "[s3] \"スズミ、大丈夫……？\"\n[s4] \"どこか上の空だけど、何かあったの……？\""
1600320-51 = "は、はい！？あ、いえ……。"
1600320-52 = "うーん……。"
1600320-53 = "すみません。#nかえって気を遣わせてしまいましたね。"
1600320-54 = "その……先ほどのヘッドホンについてです。"
1600320-55 = "あれからずっと気がかりで……。"
1600320-56 = "なんだか、先生に変な印象を与えてしまったのではないかと……。"
1600320-57 = "[s5] \"変な印象……？\"\n[s6] \"えっと……どういう意味？\""
1600320-60 = "その……自警団としてパトロールしているというのに、ヘッドホンをしながら、だなんて……。"
1600320-61 = "もちろん、音量は抑えていますし、いつもというわけではありません。#n基本的に聞くのは、パトロールの休憩中です。"
1600320-62 = "ただ……パトロールが長時間続くと、気分転換したくなりまして……。"
1600320-63 = "けして、自警団の活動をおろそかにしているわけではありません。"
1600320-64 = "ですが、そんな私の姿を先生が見て、変な印象を抱いていないか、と。#n不安に……なってしまって。"
1600320-65 = "……え？"
1600320-66 = "気にしてない、ですか？#nそ、それなら、良いのですが……。"
1600320-67 = "[s7] \"本心からそう思ってるよ。\"\n[s8] \"だって、スズミが頑張ってることを知ってるからね。\"\n[s9] \"私が見てないところでも、ね。\""
1600320-71 = "それは……。"
1600320-72 = "…………。"
1600320-73 = "…………はい。"
1600320-74 = "ありがとうございます。#n私は先生に対しての印象を意識するばかりで、大切なことを忘れていたようです。"
1600320-75 = "パトロールは、自分の意志で始めたことなのに。"
1600320-76 = "普段ならこんなこと全然思わないのに、先生の前となると、どうにも自分のペースが崩れてしまうようで……。"
1600320-77 = "反省しないといけないですね。"
1600320-78 = "……ですが、そう言っていただいたおかげで、心が楽になりました。"
1600320-79 = "本当にありがとうございます、先生。"
1600320-80 = "……はい？"
1600320-81 = "ヘッドホンですか？#nいえ、何か改造してるわけではありません。"
1600320-82 = "お店で普通に売られている何の変哲もないものです。"
1600320-83 = "昔から使っているくらいでしょうか……？#nそこまで特別というわけでは。"
1600320-84 = "外に持ち歩くことも多いので、少し傷がありますね。"
1600320-85 = "パトロール中、ヘッドホンをした状態で交戦することもありましたが、運が良かったのか、壊れるようなことはありませんでした。"
1600320-86 = "もし壊れてしまったら、ですか？"
1600320-90 = "うーん……。#nたぶん、修理を依頼して使い続けると思います。"
1600320-91 = "[s10] \"大切にしてるんだね。\"\n[s11] \"ヘッドホンもスズミにとってパートナーなんだね。\""
1600320-94 = "パートナー……"
1600320-95 = "そうですね……先生にそう言われると、なんとなくそう思えてきます。"
1600320-96 = "……ふふっ。"
1600320-97 = "先生と過ごしていると……何でもないようなお話も、とても楽しく感じます。"
1600320-98 = "……不思議な、気持ちです。"
1600320-99 = "ずっと、一人でパトロールをしていると思っていましたが、そうではなかったのですね。私のそばには、いつも銃やヘッドホンがいてくれました。"
1600320-100 = "[s12] \"うん、それに私もいるよ。\"\n[s13] \"いつでも呼んでね。もちろん、パトロール以外でも。\""
1600320-103 = "……なっ。"
1600320-107 = "……う。"
1600320-108 = "その、えっと……。"
1600320-109 = "す、すみません。言葉が出てこなくて。"
1600320-111 = "お気持ちはありがたいのですが、#nそこまでしていただくわけにはいきません。"
1600320-112 = "先生がお忙しいのは、よく知っていますから。"
1600320-113 = "なので……。"
1600320-116 = "……うーん。"
1600320-117 = "……すみません、今のはなかったことにしても……いいでしょうか？"
1600320-118 = "先生には、いつも感謝しています。"
1600320-119 = "仕事でお忙しいなか、私のことまで……本当にありがとうございます。#n先生さえよろしければ、その、時々でいいので……。"
1600320-120 = "……お願い、できれば。"
1600320-126 = "……いえ。#nぜひお願いします、先生。"
