[translation]
1601605-1 = "O eu de agora e"
1601605-5 = "（Enquanto eu esperava na sala de descanso, Mine apareceu）"
1601605-6 = "Com licença, Sensei."
1601605-14 = "[ns1] \"...Eu sabia.\"\n[ns2] \"Você está preocupada com o traje, não é?\""
1601605-17 = "...Sim."
1601605-18 = "Uma preocupação tão pequena minha..."
1601605-19 = "Você já tinha percebido, Sensei?"
1601605-20 = "...Eu deveria ter vindo pedir conselhos mais cedo."
1601605-21 = "Bem, serei direta."
1601605-22 = "Sensei, eu..."
1601605-27 = "...Estou preocupada sobre o que fazer com este traje."
1601605-28 = "[ns] \"...\""
1601605-30 = "[ns3] \"...Descartar, de repente!?\"\n[ns4] \"Houve algum problema com ele!?\""
1601605-32 = "Sim, descartar."
1601605-34 = "Exatamente."
1601605-35 = "Como você sabe, eu sirvo como líder da Unidade de Socorro da Trinity."
1601605-36 = "...Eu gosto das atividades de idol, mas #nisso não significa que eu possa negligenciar minhas atividades principais."
1601605-37 = "Será que é realmente possível conciliar as duas?"
1601605-40 = "...No fundo, eu quero continuar usando este traje."
1601605-41 = "No entanto, se eu fizer isso, minha identidade como líder da Unidade de Socorro será perdida."
1601605-44 = "Eu inventava várias desculpas para usar o traje de idol e #nvinha adiando o problema."
1601605-45 = "Mas, se continuar assim, uma das duas coisas será negligenciada. #nIsso não pode acontecer."
1601605-46 = "Os membros da unidade disseram que #ntudo bem fazer um show de vez em quando, mas..."
1601605-47 = "...Eu recusei."
1601605-48 = "Porque eu mesma sei que ficar em cima do muro #né a pior coisa a se fazer."
1601605-49 = "[s5] \"Você já tomou sua decisão, Mine.\"\n[s6] \"Você acha que conciliar é difícil demais?\""
1601605-52 = "Sim, esta é a minha conclusão."
1601605-56 = "Ao imaginar um futuro onde continuo tanto com as atividades de idol quanto com as de socorro..."
1601605-57 = "...Cheguei à conclusão de que, inevitavelmente, um dos lados acabaria sendo prejudicado."
1601605-58 = "Por isso, Sensei..."
1601605-63 = "Você poderia guardar este traje para mim?"
1601605-67 = "[ns7] \"Eu deveria... guardar isso?\"\n[ns8] \"Você quer que eu fique com ele?\""
1601605-70 = "É como um tipo de \"selo\"."
1601605-71 = "Se estiver comigo, ficarei pensando no traje o tempo todo, mas #nnão tenho coragem de descartá-lo."
1601605-72 = "...Não pretendo negar quem sou agora, e este traje está cheio de memórias preciosas."
1601605-73 = "Achei que a melhor opção seria pedir para você cuidar dele."
1601605-77 = "Sensei..."
1601605-78 = "...Por favor."
1601605-79 = "[s] \"...\""
1601605-81 = "[ns] \"...Mine.\""
1601605-85 = "[ns9] \"Sinto muito, mas não posso fazer isso.\"\n[ns10] \"Esse traje deve ficar com você, Mine.\""
1601605-90 = "...Entendido."
1601605-91 = "Se é isso que você diz, Sensei, não tenho escolha."
1601605-95 = "Vou seguir em frente com o descarte deste traje..."
1601605-99 = "...Não há necessidade disso?"
1601605-100 = "Mas, se eu continuar com ele..."
1601605-101 = "Por que..."
1601605-105 = "...Ah."
1601605-106 = "Por acaso, você pretende me convencer do contrário?"
1601605-107 = "Esta é a conclusão que alcancei após pensar muito."
1601605-108 = "……Eh?"
1601605-109 = "Não é esse o caso……?"
1601605-110 = "[s11] \"Eu também vou pensar junto com a Mine.\"\n[s12] \"Eu te direi quando você deve usar.\""
1601605-113 = "……?"
1601605-117 = "Sensei vai……."
1601605-118 = "Você vai me dizer quando devo usar este traje?"
1601605-119 = "Por que chegar a esse ponto……."
1601605-120 = "……Peço desculpas."
1601605-121 = "Não consegui entender exatamente o que você está pensando, Sensei……."
1601605-122 = "……Entendo."
1601605-127 = "É verdade……."
1601605-128 = "Certamente, se o Sensei me disser o momento certo para usar……."
1601605-129 = "Parece que não precisarei mais me preocupar com o traje."
1601605-130 = "……Fufu."
1601605-131 = "Entendido."
1601605-132 = "Acho que vou confiar no Sensei."
1601605-133 = "Mas, pedir para o Sensei escolher as roupas que vou vestir……."
1601605-134 = "……Sinto-me um pouco envergonhada, na verdade."
1601605-138 = "[ns13] \"I-Isso é……!\"\n[ns14] \"É apenas para resolver o dilema da Mine……!\""
1601605-143 = "Fufu, é brincadeira."
1601605-144 = "Confio a idol Aomori Mine aos seus cuidados, Sensei."
1601605-145 = "De agora em diante, não apenas como professor e aluna……."
1601605-150 = "Como a relação que temos agora, conto com você."
