[translation]
1701-1 = "O Fantasma do Andar Vazio (1)"
1701-2 = "Hospital Geral Santa Teresa - Quarto"
1701-3 = "Esquadrão de Socorro, chegamos!"
1701-4 = "Onde estão os pacientes? Quem não estiver se sentindo bem, por favor, levante a mão e responda em voz alta!"
1701-5 = "Shiii...! Hanae-chan, você está falando alto demais. #nEste é um setor onde há muitas pessoas doentes, então vamos ser um pouco mais silenciosas, certo?"
1701-6 = "Eu sei, mas senpai, #nnão dizem que a doença vem da mente e que um sorriso é o melhor remédio para todos os males?"
1701-7 = "Se conversarmos e cantarmos com um sorriso, tenho certeza de que todos ficarão bem logo!"
1701-8 = "Haha, é verdade. #nGraças à energia da Hanae-chan ao falar com a gente, a vida no hospital não fica entediante."
1701-9 = "Ver o sorriso da Hanae-chan me faz sentir melhor naturalmente."
1701-10 = "Fufu, fico feliz que pensem assim."
1701-11 = "Ora, Sr. Shiroyagi. O pão do almoço ainda... foi deixado de lado?"
1701-12 = "É que... não estou com muita fome..."
1701-13 = "Mas se você não ingerir nutrientes suficientes, seus ferimentos não vão sarar rápido, sabe?"
1701-17 = "Vamos lá, eu vou te ajudar, então diga 'ah'!"
1701-18 = "Ei, isso não vale! Serina-chan, dê um 'ah' para mim também!"
1701-19 = "E, e para mim também!"
1701-20 = "Ah, gente! Se ficarem mimados assim, vou contar para a enfermeira-chefe! Não adianta me olhar desse jeito!"
1701-21 = "Então, em troca, para quem está com a mão machucada, a Hanae vai dar o pão na boca!"
1701-25 = "Mesmo sendo tão ocupadas na escola, vir ao hospital todo fim de semana para cuidar dos pacientes como voluntárias... as meninas do Esquadrão de Socorro são verdadeiros anjos."
1701-26 = "É verdade. Só de olhar, sinto até minha alma purificada... Diante de anjos assim, não tenho dúvidas de que até o ser mais maligno se tornaria um cachorrinho dócil."
1701-27 = "Ah, com certeza."
1701-29 = "Hospital Geral Santa Teresa - Lobby"
1701-30 = "Chefe, terminamos a ronda no 3º andar. Todos estão se recuperando bem."
1701-31 = "Bom trabalho, vocês duas. Houve algum paciente que fez travessuras ou que estava irritado?"
1701-32 = "Não, todos foram gentis e atenciosos conosco, foi muito divertido!"
1701-33 = "Fico feliz em ouvir isso. De fato, ultimamente a atmosfera do setor ficou mais alegre e o número de pacientes reclamando diminuiu bastante. Isso é graças ao Esquadrão de Socorro."
1701-34 = "Nós apenas fizemos o que precisava ser feito. Fufu."
1701-35 = "Se houver alguém se sentindo mal, por favor, chame o Esquadrão de Socorro a qualquer momento!"
1701-37 = "Aquele... tem uma coisa que me deixa curiosa."
1701-38 = "Sim, o que seria?"
1701-39 = "Sempre que venho a este hospital, fazemos a ronda até o 3º andar, mas não há pacientes no 4º andar?"
1701-40 = "No mapa do lobby central, dizia que havia quartos no 4º andar também..."
1701-41 = "...Sobre isso, é que antigamente, começou a circular um boato ruim entre os pacientes que estavam internados no 4º andar."
1701-42 = "Um boato ruim?"
1701-43 = "Dizem que, quando o sino bate meia-noite... aparece um fantasma todo enfaixado."
1701-44 = "Fa-fantasma!? É sério!?"
1701-45 = "Claro que não acredito que seja um fantasma de verdade... mas como muitos pacientes ficaram com medo, não tivemos escolha a não ser transferi-los."
1701-46 = "Por isso, o 4º andar não é mais usado e tornou-se um andar vazio."
1701-47 = "Que, que medo... #nEn-então, vamos evitar chegar perto do 4º andar..."
1701-49 = "Não pode, senpai. Mesmo que seja um fantasma, se ele está enfaixado, significa que é um paciente, certo!?"
1701-50 = "Se a Comandante Mine souber que nós, do Esquadrão de Socorro, ignoramos um paciente doente e fugimos, ela certamente ficará triste!"
1701-51 = "Ma-mas nós somos o Esquadrão de Socorro que trata os vivos, não somos um grupo de exorcistas para lidar com fantasmas..."
1701-52 = "E-eu acho melhor fingirmos que não ouvimos nada sobre isso..."
1701-53 = "Não, até eu ver com meus próprios olhos, não saberei se é um fantasma ou não!"
1701-54 = "Além disso, se o boato continuar e o 4º andar continuar inutilizado, não poderemos receber mais pacientes — isso também é pelo bem dos pacientes!"
1701-55 = "Uuu... ela tem razão...!"
1701-56 = "Fufu, então está decidido! #nVamos nos reunir novamente hoje às 11 da noite para verificar o fantasma do andar vazio, senpai!"
1701-58 = "Se, se, se aparecer um fantasma de verdade, eu vou embora, viu!? #nNão importa o que aconteça, vou fugir em velocidade máxima sem olhar para trás!!"
