[translation]
2000209-1 = "行方不明のネズ助"
2000209-2 = "サヤの研究室"
2000209-3 = "先生、大変、大変なのだ！ネズ助が……ネズ助が……。"
2000209-4 = "ネズ助がいなくなったのだ！"
2000209-5 = "もしかしてどこかに隠れてるのかなと思って研究室を探したけど、どこにもいない！"
2000209-7 = "ネズ助が何も言わずいなくなったのなんて今回が初めてで……ど、どうしよう？うわああん！"
2000209-8 = "[s] サヤを落ち着かせる。"
2000209-10 = "くすん、くすん。でも……もしネズ助に何かあったら……。"
2000209-11 = "え、ネズ助が行きそうな場所？#nネズ助は、ぼく様と相棒でいつでも一緒だったから、一人ではどこにも行ったことがない。"
2000209-12 = "[s] \"錬丹術研究会の他の部員たちに聞いてみよう。\""
2000209-13 = "分かった……くすん。"
2000209-15 = "山海経・教室"
2000209-16 = "ネズ助がいなくなった？それは大変ですね……。"
2000209-17 = "今日、ネズ助見たりした？"
2000209-18 = "いえ、私は、先輩の研究室以外の場所でネズ助を見たことはないですね。"
2000209-19 = "でも珍しいですね。ネズ助が一匹でいなくなるなんて……。"
2000209-20 = "どうしよう、くすん……。"
2000209-21 = "こんなこと言うのもあれなのですが……もしかしてネズ助は家出をしたんじゃないでしょうか？"
2000209-22 = "……家出？"
2000209-23 = "はい、先輩が毎日のように、実験を言い訳にしてネズ助のことをいじめましたし……。"
2000209-24 = "逆に今まで逃げなかったのがすごい、と言いますか。"
2000209-25 = "いじめるだなんて！ぼく様は実験を手伝ってもらっていただけで、ネズ助をいじめたことはないのだ！"
2000209-26 = "でもネズ助は、実験に参加するのを嫌がってたでしょう？#nよく変な姿にさせられるし、ネズ助の気持ちも分かります。"
2000209-27 = "うう……。"
2000209-28 = "[s] \"他の部員にも聞いてみよう。\""
2000209-29 = "分かったのだ……。"
2000209-31 = "うそ、ネズ助さんがいなくなったんですか？"
2000209-32 = "うん。今日、どこかでネズ助見てたりしないか？"
2000209-33 = "ううん……今日はネズ助さんを見た覚えはないですね。"
2000209-34 = "本当、どこに行っちゃったのだ……くすん。"
2000209-35 = "あのう、お言葉ですが……ネズ助さんは家出をしたのではないでしょうか。"
2000209-36 = "みんな……なんでそう思うの？"
2000209-37 = "みんな……？えっと、それはその、ネズ助さんはいつもサヤ先輩にいじめられてましたから……。"
2000209-38 = "いじめるつもりじゃなかったのに、ううう……。"
2000209-39 = "[s] \"校内を回ってネズ助を探してみよう。\""
2000209-40 = "うん……。"
2000209-42 = "山海経高級中学校"
2000209-47 = "ネズ助――本当に、どこに行っちゃったの……。"
2000209-48 = "[s] \"あっちも探してみよう。\""
2000209-49 = "……ううん、もういい。#nネズ助は、メイとキンが言った通り、家出をしたに違いないのだ。"
2000209-50 = "今までぼくがいじめすぎたせいなのだ。うう……#nネズ助はぼくにがっかりして、もう帰ってこないのだ。"
2000209-51 = "[s] 諦めないで、と言う。"
2000209-52 = "先生も今までぼくの実験のせいで辛かったでしょう？#nなのに……どうしてぼくにこんなに良くしてくれるの？"
2000209-53 = "[s1] \"私はサヤと一緒で楽しかったよ。\"\n[s2] \"先生だからね。\""
2000209-55 = "先生……。"
2000209-57 = "先生……。"
2000209-60 = "チュ、チューチュー……。"
2000209-61 = "ああっ、ネズ助ぇっ……！どこに行ってたのさ、うああああん！"
2000209-62 = "チューチュー……。"
2000209-63 = "くすん、くすん……今までぼく様がひどく扱ったから家出してたのか？#n本当ごめんね……。"
2000209-64 = "チューチュー、チュ。"
2000209-65 = "え？商会で大きなひまわりの種を配ると聞いて行ってきた？#nならどうして何も言わずに行ったのだ！一日中探したじゃんか！"
2000209-66 = "くすん……でもごめんね。これからはもうひどいいたずらはしないから……#nもう二度と、何も言わないでいなくなっちゃダメだからな？"
2000209-67 = "チュー……。"
2000209-70 = "うん、約束するのだ！これからは真面目な実験にしかお前を付き合わせない！"
2000209-71 = "チューッ！"
2000209-72 = "このやろう、ネズ助！バタバタするな！#nもう絶対に逃さないからな！"
2000209-74 = "チュ、チュチュー！"
2000209-76 = "その後、サヤはネズ助と仲良く研究室に帰った。"
