[translation]
2000008-1 = "O sentimentalismo de um dia chuvoso"
2000008-2 = "Escola Millennium - 42ª Biblioteca"
2000008-5 = "Ah, Sensei."
2000008-6 = "Você também veio procurar um livro?"
2000008-7 = "Hm? Eu?"
2000008-8 = "Hehe, está curioso sobre o que estou lendo?"
2000008-9 = "Tente adivinhar."
2000008-10 = "[s1] \"Sem dúvida, BL.\"\n[s2] \"Uma revista científica?\"\n[s3] \"Um livro de poesias...?\""
2000008-11 = "Hehe, errou tudo."
2000008-12 = "Hehe, errou tudo."
2000008-13 = "Hehe, errou tudo."
2000008-14 = "Tcharam, é este aqui."
2000008-15 = "[s] \"'Introdução à Psicologia para Garotas'?\""
2000008-16 = "Todo mundo reage com surpresa quando vê."
2000008-17 = "Mas... ultimamente, enquanto criava várias coisas com você, Sensei..."
2000008-18 = "Percebi que preciso valorizar a consideração pelos sentimentos alheios tanto quanto a racionalidade."
2000008-19 = "A física e a psicologia são completamente diferentes,"
2000008-20 = "e, para ser sincera, ainda não estou acostumada."
2000008-21 = "A física é pensar no porquê de uma ondulação surgir na água quando se joga uma pedra nela."
2000008-22 = "A psicologia é pensar no porquê de uma ondulação surgir no coração quando se diz algo a alguém."
2000008-23 = "Hoje, eu queria estudar mais sobre isso... a parte que falta em mim agora."
2000008-24 = "Se eu fizer isso... talvez eu consiga criar algo ainda mais útil para você, Sensei."
2000008-26 = "Hehe, obrigada pelo elogio."
2000008-27 = "Hm? Mas..."
2000008-28 = "Você não veio aqui para pegar um livro emprestado?"
2000008-29 = "[s] \"Começou a chover de repente, então queria pegar um guarda-chuva emprestado.\""
2000008-30 = "Entendo, era isso."
2000008-31 = "Nesse caso, tenho algo perfeito. Um que eu mesma fiz..."
2000008-32 = "[s] \"Um guarda-chuva comum, por favor.\""
2000008-33 = "Hmm, não é como se ele tivesse uma função de autodestruição ou algo do tipo, mas..."
2000008-34 = "Entendido."
2000008-35 = "Atender a qualquer pedido é o dever de uma meister da Millennium."
2000008-36 = "Então, veja este aqui, este guarda-chuva é..."
2000008-37 = "Algo que muda completamente o paradigma, a estrutura do conceito de \"guarda-chuva\" até hoje."
2000008-38 = "[s] \"Por favor, eu só quero um guarda-chuva normal...\""
2000008-39 = "Hmm, não tem jeito."
2000008-40 = "Um guarda-chuva comum... se for o meu..."
2000008-41 = "..."
2000008-42 = "...Hehe."
2000008-43 = "Quer ir comigo?"
2000008-44 = "O caminho até o Schale é o mesmo que o meu."
2000008-45 = "Ah, espere só um pouquinho. #nVou devolver o livro."
2000008-51 = "Vamos, Sensei."
2000008-54 = "...Às vezes, um guarda-chuva comum também é bom."
