[translation]#[Texto Final. mas eventualmente pode haver alterações na formatação de texto. - Filipe 03/07.]
200003-1 = "Episódio 3: Um Sonho Estranho"
200003-4 = "\"Esta é―― a história sobre \"você\",\no Sensei da Schale, e um \"smartwatch\".\""
200003-5 = "\"Você leva uma vida desregrada,#nmas ainda assim se esforçava\npara acordar cedo.\""
200003-6 = "\"O smartwatch na mesa de cabeceira é o\nassistente único e insubstituível\nque o ajuda a despertar.\""
200003-10 = "[ns1] \"Arona……?\"\n[ns2] \"Ué, Onde é que eu enfiei o Baú de Shittim?\""
200003-13 = "\"Ao que parece, você ainda está dentro\nde um sonho.#nAfinal, procura um tablet que não\nhá de ser encontrado.\""
200003-14 = "\"……Sendo que o único aparelho que recebeu da\nPresidente do Conselho é um smartwatch\nchamado \"Cajado de Shaked\".\""
200003-15 = "[s] Procurar o Baú de Shittim."
200003-16 = "\"Você vasculha o quarto, mas a busca\nterminará em vão.\""
200003-17 = "\"E então pensa: será que não esqueceu\no tablet em algum lugar?\""
200003-18 = "\"Com um gesto habitual, você veste o\nsmartwatch e segue para a sala de descanso.\""
200003-22 = "\"Na sala de descanso ainda às escuras,#nvocê liga a máquina de café, como sempre,\ne tira um espresso.\""
200003-23 = "\"O som dos grãos moídos ecoa, e o líquido\nnegro preenche a xícara.#nUm café barato, quase sem aroma,\nmas perfeito para espantar o sono.\""
200003-30 = "\"Você o vira de um gole só e segue\npara o escritório.\""
200003-34 = "\"Ao chegar ao escritório, você nota\numa nova anomalia.\""
200003-35 = "\"A aluna de plantão, que sempre está lá,\nnão apareceu.#nMas você não deu muita importância:\natrasos acontecem.\""
200003-36 = "\"……Até abrir as cortinas.\""
200003-43 = "[ns] \"Quê……?\""
200003-44 = "\"Enfim você nota a terceira anomalia.\""
200003-45 = "\"O mundo estava em preto e branco. A Kivotos\nradiante, pintada de cores vivas, havia\nperdido a cor e se tingido de cinza.\""
200003-46 = "\"Não era um céu nublado. O mundo inteiro\nhavia se tornado monocromático.\""
200003-47 = "\"……E não havia sinal de ninguém.\""
200003-48 = "\"Como se todos tivessem partido,\ndeixando apenas você.\""
200003-49 = "[ns] \"Que voz…… é essa?\""
200003-50 = "\"Confuso com tantas anomalias, você passa a\nduvidar até das palavras que surgem\nna própria mente.\""
200003-51 = "\"Mas fique tranquilo. Isto, ao menos,\nnão é uma anomalia.\""
200003-52 = "\"Ao tecer uma história―― começar em primeira\npessoa pela riqueza das emoções, empacar no\nenredo e migrar para a terceira pessoa.#nÉ um fenômeno comum em quem escreve\npela primeira vez.\""
200003-56 = "\"……Perdão. Talvez seja um assunto difícil\nde gerar empatia.\""
200003-57 = "\"Voltemos à história. Você veste um casaco\ne corre para o hospital.#nHá de querer esclarecer o que está\nacontecendo com você.\""
200003-58 = "[ns] Ir ao prédio do Conselho Estudantil Geral."
200003-59 = "\"……Não. Você tomou outro caminho.\""
200003-62 = "\"No trajeto até o Conselho, a paisagem\nao redor não muda.\""
200003-63 = "\"Até o interior do veículo que balança está\nmonocromático, como se tivesse esquecido\nas cores.\""
200003-64 = "\"Você…… se lembra de uma cena\nque já viu antes.\""
200003-66 = "\"Naquela ocasião, o mundo se tingiu de um\nvermelho intenso. Ainda assim――\""
200003-67 = "\"os alunos estavam ao seu lado.\""
200003-73 = "\"Mas―― agora é diferente.\""
200003-75 = "\"Ao chegar ao prédio do Conselho, você o\nvasculha de ponta a ponta.#nMas continua sem sinal de ninguém.\""
200003-76 = "\"Nem a administradora de óculos que\nresmungava, mas cuidava de você;#nnem a funcionária de cabelo rosa sempre\nmastigando salgadinho de mentaiko―― ninguém.\""
200003-77 = "\"……Por fim, você se dirige 'àquele lugar'.\""
200003-78 = "\"Subiu as escadas correndo, como se algo\no impelisse.\""
200003-79 = "\"Rumo ao lugar onde tudo começou.\""
200003-87 = "\"O gabinete da Presidente do Conselho.\nLá, uma garota desconhecida――\""
200003-88 = "\"Não. Uma garota que evocava certa\nnostalgia estava sentada lá.\""
200003-89 = "[ns] \"Essa voz…… é você?\""
200003-90 = "\"Sim. Mas, ao mesmo tempo…… também é não.\""
200003-91 = "\"Este mundo é a reminiscência da garota,\ne o seu sonho.\""
200003-92 = "\"Assim como você observa a garota,\na garota observa você.\""
200003-93 = "[ns] \"Quem é você?\""
200003-98 = "É um prazer te conhecer, Sensei."
200003-99 = "Eu sou, de Kivotos, a――"
200003-109 = "[ns] \"Onde estou……\""
200003-114 = "Sensei!! O Senhor está bem?!"
200003-115 = "Você não parava de gemer dormindo,\neu fiquei preocupada!"
200003-116 = "[s] \"Um sonho……?\""
200003-117 = "Suposição: um pesadelo, talvez?"
200003-118 = "[s] \"Não. Pesadelo não era, mas……\""
200003-129 = "[ns] \"Um sonho estranho, isso com certeza.\""
200003-130 = "Fico aliviada por não ser um pesadelo……"
200003-131 = "Recomendo exames de saúde periódicos.\nDistúrbios do sono escondem\nas mais variadas causas."
200003-132 = "É porque você leva uma vida desregrada!#nA super Arona sabe de tudo, viu?!"
200003-133 = "De agora em diante\nvou te avisar na hora das refeições.\nQuero ver o senhor comendo bem direitinho!"
200003-134 = "[s] \"Desculpa deixar vocês preocupadas. E valeu.\""
200003-138 = "[ns] \"……Conhecem o 'Cajado de Shaked'?\""
200003-139 = "……Negativo. Não há registros\nna minha memória."
200003-140 = "Hmmm…… acho que já ouvi…… ou não……"
200003-141 = "Onde foi que você ouviu isso, Sensei?"
200003-142 = "[s] \"Pois é…… Eu também não consigo lembrar direito……\""
200003-146 = "[ns3] \"O sonho fica pra depois……\"\n[ns4] \"Eu sei que ainda é cedo e o sol nem rachou no asfalto ainda, mas vamos começar o trabalho de hoje?\""
200003-149 = "Mas Sensei, ainda são 4 da manhã!!"
200003-150 = "Recomendação: pela sua saúde,\nvolte a dormir."
200003-151 = "Isso mesmo! Volta pra debaixo da coberta agora!"
200003-152 = "Se não pegar no sono, eu canto uma canção de ninar\npara o senhor apagar logo de uma vez!"
200003-153 = "Não possuímos plugin de canto,\nmas…… farei o possível."
200003-159 = "Próximo Episódio: O Trapezoedro Cintilante"