[translation]
2000703-1 = "O dilema da cantora virtual"
2000703-5 = "Camarim da casa de shows"
2000703-7 = "（Ao chegar no camarim, Miku estava conversando com alguém）"
2000703-11 = "O quê, você não consegue mais cantar!?"
2000703-12 = "Sim... não sei o motivo, mas de repente..."
2000703-13 = "Como assim, sem causa aparente..."
2000703-14 = "Eu consigo conversar assim, mas por algum motivo, minha voz não sai..."
2000703-15 = "Droga, e eles disseram que a manutenção do corpo estava perfeita...!"
2000703-16 = "Quer dizer, isso é um problema, o show vai..."
2000703-17 = "Digo, seria possível cancelar ou adiar a partir de agora...?"
2000703-18 = "Não, é difícil agora... Nesse caso, uma quantia absurda de dinheiro seria..."
2000703-19 = "Sem falar nos custos de publicidade, o dinheiro da casa de shows e os gastos técnicos não seriam reembolsados..."
2000703-20 = "Mesmo que não fosse cancelado, receberíamos uma fatura de valor astronômico...!"
2000703-21 = "De qualquer forma, cancelar é impossível! Eu vou procurar uma solução do meu lado, mas tente fazer algo para resolver isso...!"
2000703-22 = "S-sim..."
2000703-27 = "Ufa..."
2000703-28 = "[s] \"Miku, você está bem?\""
2000703-30 = "Ah, Sensei. Você veio."
2000703-31 = "Desculpe, o momento foi ruim. Acabei deixando você ver uma cena vergonhosa."
2000703-32 = "[s] \"Aquele era o organizador do show?\""
2000703-33 = "Sim. Parece que ele é o responsável pelo planejamento deste show."
2000703-34 = "Eu pretendia ficar em silêncio enquanto tentava encontrar uma solução até o último minuto, mas..."
2000703-35 = "Acho que o tempo está ficando curto."
2000703-36 = "Você deve ter ouvido, mas parece que realmente não é possível cancelar ou adiar o show..."
2000703-37 = "[s] \"São as chamadas 'coisas de adulto'...\""
2000703-38 = "Parece que sim... Mas, no fundo, a responsabilidade é minha."
2000703-39 = "Além disso, se for cancelado, vou decepcionar todos os fãs que estavam ansiosos para me ouvir cantar. Por isso, eu também quero conseguir realizar esse show."
2000703-40 = "[s1] \"Não se cobre tanto.\"\n[s2] \"Com você, Miku, vai dar tudo certo.\""
2000703-41 = "……Obrigada."
2000703-42 = "……Obrigada."
2000703-43 = "Ah, aliás, Sensei. Quais seriam esses \"vários métodos\" que você mencionou no MomoTalk...?"
2000703-44 = "[s] \"Pensei em tentar um por um, sem exceção.\""
2000703-51 = "Isso é... uma cebolinha?"
2000703-52 = "Quando se está resfriado ou doente, enrolar uma cebolinha no pescoço melhora a garganta... é isso?"
2000703-53 = "De fato, acho que já ouvi falar disso, mas..."
2000703-54 = "Será que esse tipo de medicina popular funciona em mim, que sou uma cantora virtual?"
2000703-55 = "[s] \"Primeiro, vamos tentar.\""
2000703-59 = "Sim, você tem razão. Certamente, agora não é hora de duvidar ou ser exigente."
2000703-66 = "Eita... ah, sinto que, ao enrolar, minha garganta está ficando um pouco mais quente."
2000703-67 = "Talvez, com isso..."
2000703-68 = "……Então, Hatsune Miku, vai cantar!"
2000703-74 = "……Não funcionou."
2000703-75 = "Será que não funciona porque sou uma cantora virtual? Não que eu não goste de cebolinha..."
2000703-76 = "[s3] \"Ainda é cedo para desistir.\"\n[s4] \"O próximo é este!\""
2000703-85 = "Isso é... um energético?"
2000703-86 = "Acho que já vi isso em algum lugar... Além disso, tem um pássaro com uma aparência estranha desenhado na lata, que..."
2000703-87 = "[s5] \"É um energético popular entre algumas alunas.\"\n[s6] \"Dizem que, se beber, você ganha asas como o Peroro.\""
2000703-88 = "I-isso, será que é seguro beber...? Não que eu esteja duvidando de você, Sensei, mas..."
2000703-89 = "I-isso, será que é seguro beber...? Não que eu esteja duvidando de você, Sensei, mas..."
2000703-90 = "……Espero que minha garganta não piore."
2000703-91 = "Então..."
2000703-95 = "Hatsune Miku, vou tentar!"
2000703-98 = "(...Depois disso, tentei vários métodos que o Sensei preparou, mas o estado da Miku não mudou em nada.)"
2000703-100 = "Hmm, não está funcionando..."
2000703-101 = "[s] \"Nem mesmo chocolate com menta funcionou...\""
2000703-102 = "Perguntando agora, o sorvete de chocolate com menta tinha alguma relação com a garganta...? Com certeza refrescou um pouco, mas..."
2000703-103 = "De alguma forma, passamos a segunda metade apenas comendo vários doces, acabou parecendo uma pequena festa de sobremesas."
2000703-104 = "Mas, graças a isso, consegui mudar um pouco os ares. Obrigada. Por acaso... era isso que você pretendia?"
2000703-105 = "Pensando bem, ultimamente eu só pensava no show e não tinha tempo para fazer ou pensar em outras coisas..."
2000703-106 = "Faz tempo que não passamos um tempo divertido assim, brincando um pouco um com o outro."
2000703-107 = "[s] \"D-desculpe, eu não tive a intenção de brincar...\""
2000703-108 = "Ah, não! Desculpe, eu não estava culpando o Sensei...!"
2000703-109 = "Para mim, que nasci para levar músicas a muitas pessoas, poder sentir esse tipo de emoção é algo novo, ou melhor, uma sensação um pouco estranha."
2000703-110 = "É uma sensação estranha. Então isso é... \"diversão\"."
2000703-111 = "[s] \"Fico feliz que você tenha se divertido, Miku. Isso me deixa feliz também.\""
2000703-112 = "...Ao ouvir isso, eu também me sinto \"feliz\"."
2000703-113 = "Obrigada por hoje também, Sensei."
2000703-119 = "Conto com você daqui para frente!"
