[translation]
2001202-1 = "負傷者なので"
2001202-2 = "（流石に心配になったので、セナの言っていた場所へと訪れた）"
2001202-3 = "（ゲヘナではよくあることとはいえ、あちこちに少し怪我をした生徒たちの姿が見える）"
2001202-6 = "（そして生徒たちの傍で、救急医学部の部員たちを指揮しているセナの姿が見えた）"
2001202-7 = "死体……ではなく負傷者は救急車に積載してください。歩ける方は一旦向こうの方へ。"
2001202-8 = "「歩くのが面倒だから」と気絶したふりをする生徒は、射撃して本当に気絶状態なのかどうか確認してください。"
2001202-9 = "……では、始め。"
2001202-11 = "はいっ！！"
2001202-16 = "のあぁぁっ！？分かった分かった！歩ける、歩けるから！"
2001202-17 = "確認だからってそう簡単に撃つな！本当に歩けなくなるから！？"
2001202-18 = "……輸送を終えましたら、再度こちらに集合。"
2001202-19 = "まだ向こうの方で戦闘は続いてますので死た……負傷者は増えるでしょう。ですので次は……"
2001202-23 = "……聞いてください。"
2001202-24 = "はいっ！"
2001202-25 = "私はしばらく離脱します。みなさんは予定通り、作業を行ってください。"
2001202-26 = "……それでは、始め。"
2001202-27 = "はいっ！！"
2001202-34 = "まさか先生が来ていたとは。どうしてここに……？"
2001202-35 = "メッセージ、届いてましたよね？ここは危ないので、他の場所へ行かれた方が…"
2001202-36 = "……はい？"
2001202-37 = "心配で来た……？"
2001202-38 = "……あぁ。"
2001202-39 = "なるほど、そうでしたか……まあ確かに、先生の立場であればむしろ無視する方が難しいと……。"
2001202-40 = "結果として、先生のことを呼び出す形になってしまいましたね。すみません、私のミスです。"
2001202-41 = "これからはああいったことが無いように、設定を修正します。"
2001202-42 = "そういう話ではない、ですか？"
2001202-43 = "気にしないでと言われましても……。"
2001202-44 = "……はい。では先生がそう仰るのでしたら。"
2001202-45 = "……手伝えること、ですか？"
2001202-46 = "お気持ちはありがたいですが、大丈夫です。基本的にいつも通りですから。"
2001202-47 = "確かに今回は予想以上に長期戦で、死……"
2001202-48 = "いえ、負傷者の数が多くなりそうなのは確かですが。"
2001202-49 = "もう少しで風紀委員会も来るはずです。その後はもう、ほぼ私たちの管轄外ですので。"
2001202-50 = "ああ、言った傍から来ましたね。"
2001202-56 = "よしっ、全員確保！！"
2001202-57 = "取り急ぎ一掃し、状況を収めろ！"
2001202-67 = "……まあ、ここまでいつも通りですね。"
2001202-68 = "[s1] \"いつも通りなんだ……。\"\n[s2] \"いつものゲヘナだね……。\""
2001202-69 = "はい。そして後は片付き次第、私たちも負傷者への対応を行うのみ。"
2001202-70 = "はい。そして後は片付き次第、私たちも負傷者への対応を行うのみ。"
2001202-71 = "それ以上のことを考えるには、現状どうしても手が足りませんから。"
2001202-72 = "それでは仕事に戻って……"
2001202-73 = "そこ！"
2001202-79 = "救急医学部か？"
2001202-80 = "はい、部長の[ruby=ひむろ]氷室[/ruby]セナです。何かご用でしょうか？"
2001202-81 = "ぶ、部長……？こ、これは失礼を。"
2001202-82 = "実はそこの横たわっている負傷者の中に、事件の首謀者が一名いまして。"
2001202-83 = "……はい、そうですか。"
2001202-84 = "……それで？"
2001202-85 = "そ、それでというのは……"
2001202-86 = "それで、私に何をどうしろと言っているのか、と聞いているのです。"
2001202-87 = "そ、それはもちろん、連れて行って尋問をしなきゃですので、身元を引き渡していただきたく……。"
2001202-88 = "お断りします。"
2001202-89 = "……え？"
2001202-90 = "救急医学部が引き受けた負傷者は、その瞬間から私たちの管轄です。例外はありません。"
2001202-91 = "その生徒についての措置は、治療が終了してからにしてください。"
2001202-92 = "で、ですが、こちらとしても経緯を調べる必要が……！"
2001202-93 = "くそっ、かくなる上は強引にでも……"
2001202-94 = "……そうですか。"
2001202-100 = "[ns] \"えっと、セナ……？\""
2001202-103 = "……気絶してしまいましたね。"
2001202-104 = "患者、もう一名追加です。"
2001202-105 = "すぐに救急車で搬送を。"
2001202-106 = "はいっ！！"
2001202-110 = "[ns3] \"えぇ……？\"\n[ns4] \"強硬手段すぎる……。\""
2001202-111 = "大丈夫です。衝撃で気絶させただけであって、実際に撃ち込んだわけでも、傷を負わせたわけでもありませんから。"
2001202-112 = "大丈夫です。衝撃で気絶させただけであって、実際に撃ち込んだわけでも、傷を負わせたわけでもありませんから。"
2001202-113 = "静かに事を済ませるには、これが最善だと判断しました。"
2001202-114 = "……さて。"
2001202-121 = "もうおよそ死体の積載は終わったようですし……。"
2001202-122 = "[s5] \"セナ、修正できてないよ……。\"\n[s6] \"もう全く隠せなくなってるけど……。\""
2001202-127 = "とにかく申し訳ないのですが、今日は後片付けもありますのでこれにて。"
2001202-128 = "それでは……。"
2001202-134 = "[ns] \"……。\""
2001202-136 = "（そうして「負傷者」たちを全員車に積み、セナと救急医学部一同はすごい勢いで消えてしまった……）"
