[translation]
2001905-1 = "Case3. 勉強の時間ですね？"
2001905-3 = "（一時的に仕事の山から離れて、市内を歩いていた）"
2001905-4 = "（次の瞬間）"
2001905-8 = "奇遇ですね、ご主人様！"
2001905-12 = "[ns] \"あ、アカネ！？\""
2001905-13 = "はい！ご主人様のアカネです。"
2001905-14 = "偶然ご主人様と出会うために、ずっとここで待っておりました。"
2001905-15 = "[s] \"こ、ここで……偶然に？\""
2001905-16 = "はい、偶然です。"
2001905-17 = "――それを偶然とは言わない、ですか？"
2001905-18 = "そう、でしょうか……？私は偶然だと思っております。"
2001905-19 = "なぜこの大通りを通ると分かっていたのか……？"
2001905-20 = "それくらい、ミレニアムの……"
2001905-21 = "……いえ、運命です。"
2001905-22 = "ご主人様のセキュリティはシャーレに守られているはず、とおっしゃりたいのでしょうか？"
2001905-23 = "ですので、ヴェリタスから衛星映像をまとめて……"
2001905-27 = "いえ、素敵な偶然もあるものだなと思いまして。"
2001905-33 = "こうしてお会いできたことも、奇跡のようなものです。"
2001905-34 = "本日はどのようなご奉仕をお望みでしょうか、ご主人様？"
2001905-35 = "[s] \"もしかして、ここまでバニーガールの格好で？\""
2001905-36 = "何か気になるところでもございますか？"
2001905-37 = "バニーガールといっても、ご奉仕するための服装に変わりはありませんから。"
2001905-42 = "（周りの冷たい視線が刺さる）"
2001905-50 = "（急いでアカネの手を引いて、近くのカフェに避難した）"
2001905-57 = "わぁ……"
2001905-58 = "[s] \"ここは一体……？\""
2001905-59 = "バニーガールカフェですね！#nこのようなコンセプトカフェまであるとは！"
2001905-60 = "そうでしたか。ご主人様の深いお考えを露知らず、私は……"
2001905-61 = "――誤解？#n謙遜はおやめください。"
2001905-62 = "ふふっ……そんなに照れることはありませんよ。"
2001905-63 = "私はご主人様が誰よりもお優しいことを、よく分かっていますから。"
2001905-67 = "ご注文はお決まりですか？ご主人様、お嬢様。"
2001905-68 = "あれ……ここでは私もお嬢様になるのですね。"
2001905-69 = "面白いものです。私にはお仕えしているご主人様がいるのにも関わらず。"
2001905-70 = "お店にいる間だけとはいえ、私には大切なご主人様が……"
2001905-74 = "ご主人様、どうされましたか？"
2001905-75 = "お疲れのようなので、私が代わりに注文いたしますね。"
2001905-76 = "まずは……"
2001905-81 = "……なるほど。バニーガールとはこのように振る舞うのですね……。"
2001905-85 = "きれいな立ち姿勢を維持しながら、お皿の音を立てないように……"
2001905-86 = "ふむ、ふむ。"
2001905-90 = "バニーガールの衣装に袖を通せば良いというわけではない、と。"
2001905-91 = "仕草や振る舞い方、周囲の環境と調和して行うご奉仕こそ……"
2001905-92 = "真のバニーガールと呼ぶのですね！"
2001905-96 = "とても参考になりました、"
2001905-97 = "ありがとうございます。"
2001905-98 = "まさか、ご主人様がこのような分野にまで[ruby=ぞうけい]造詣[/ruby]が深いとは。"
2001905-99 = "私も完璧なご奉仕を目指して、これからも精進いたします。"
2001905-105 = "さすがは私のご主人様です！"
2001905-106 = "[s1] \"あはは……\"\n[s2] \"誤解なんです、アカネさん……。\""
2001905-110 = "（アカネは最後まで誤解（？）したままだった……）"
