[translation]
2002805-1 = "Uma confissão a sós"
2002805-4 = "Ah, Sensei. Por aqui!"
2002805-5 = "Obrigada por vir! E, sinto muito. Por ter que lidar com os meus caprichos..."
2002805-6 = "[s1] \"Como seu Sensei, é o meu dever.\" \n[s2] \"Os caprichos da Hinata são preciosos, sabe.\""
2002805-7 = "Haha... fico feliz em ouvir isso."
2002805-8 = "......S-sério...?"
2002805-9 = "Bem..."
2002805-10 = "O favor que eu queria pedir não é algo que eu possa fazer em qualquer lugar..."
2002805-11 = "......Digo, seria difícil se houvesse mais alguém por perto..."
2002805-15 = "Tinha que ser apenas eu e você, Sensei..."
2002805-16 = "E-então... bem..."
2002805-17 = "[s3] \"Pode ficar mais relaxada.\" \n[s4] \"Pode me contar qualquer coisa.\""
2002805-20 = "......!!"
2002805-21 = "E-então...! E-eu vou te contar...!"
2002805-25 = "E-eu..."
2002805-27 = "Quero praticar a confissão de pecados...!!!"
2002805-32 = "[ns] \"Confissão de pecados...?\""
2002805-33 = "Sim! N-na verdade... eu já pedi para as outras irmãs da Sisterhood me ajudarem algumas vezes..."
2002805-34 = "Mas eu sempre fico tão nervosa que não consigo terminar."
2002805-35 = "Elas me encorajaram dizendo que eu ficaria menos nervosa com o tempo, mas... como estou agora, acabaria sendo um incômodo para quem viesse me procurar..."
2002805-36 = "Por isso, tenho evitado ficar responsável pelas confissões."
2002805-37 = "Como uma irmã, não posso fugir disso para sempre, mas..."
2002805-38 = "Por outro lado, tenho vergonha de pedir para as irmãs da Sisterhood praticarem comigo tantas vezes..."
2002805-39 = "[s5] \"Então, quer que eu me confesse para você?\" \n[s6] \"Que tal começarmos agora?\""
2002805-44 = "H-hein!? Agora...!? A-aqui!?"
2002805-45 = "Mas, tem gente por perto..."
2002805-52 = "......Não tem ninguém!"
2002805-53 = "Foi por isso que pedi para o Sensei vir até aqui!"
2002805-54 = "Uuu... agora que vamos começar, estou ficando nervosa..."
2002805-55 = "......É só um treino, tente ficar mais relaxada...?"
2002805-56 = "V-verdade."
2002805-57 = "Isso é um treino... um treino... suspiro..."
2002805-62 = "......Então, vamos começar."
2002805-67 = "O segredo da confissão nunca será revelado, independentemente do motivo, então pode ficar tranquilo."
2002805-68 = "......Sensei."
2002805-69 = "Que tipo de preocupação você tem hoje...? Poderia me contar?"
2002805-70 = "[s] \"Você vai ouvir meus sentimentos sinceros?\""
2002805-71 = "Com certeza. Não importa o conteúdo, como uma irmã, ouvirei sua confissão."
2002805-72 = "Por favor, diga-me suas palavras sinceras, Sensei. Por favor, conte-me o que está guardado no fundo do seu coração."
2002805-73 = "[s] \"Então, por favor.\""
2002805-74 = "Sim, estou ouvindo atentamente..."
2002805-75 = "Pode começar quando quiser."
2002805-76 = "[s7] \"...Não quero ir embora.\" \n[s8] \"Quero ficar brincando aqui para sempre.\""
2002805-79 = "Entendo. Sem ir embora, ficar aqui para sempre..."
2002805-84 = "......Eh?"
2002805-85 = "Sensei...? O que você acabou de dizer..."
2002805-86 = "[s9] \"Posso dizer qualquer coisa, não posso!\" \n[s10] \"Não quero mais ir embora! Quero brincar para sempre!\" \n[s11] \"Não quero saber de trabalho! Quero brincar com a Hinata!\""
2002805-92 = "S-Sensei...!? C-calma... primeiro, por favor, se acalme!"
2002805-93 = "Eu entendo perfeitamente como você se sente, mas...!"
2002805-94 = "Eu também quero passar mais tempo a sós com você!"
2002805-95 = "……。"
2002805-96 = "……ah."
2002805-97 = "N-não! Não, não, não, não, não, não!!"
2002805-98 = "O que eu disse agora, é que, n-não é isso! Ah, não... b-bem, não é que não seja... é que, sabe...!"
2002805-99 = "Eu, eu não acredito que pensei em algo assim...! Sendo uma irmã da igreja...!"
2002805-100 = "[s12] \"E-está tudo bem. Isso é uma confissão, lembra?\"\n[s13] \"V-vamos nos acalmar um pouco?\""
2002805-103 = "Me desculpe, me desculpe!! Me desculpem, todos!! Sensei, me desculpe também!!"
2002805-104 = "Huu..."
2002805-106 = "Hiaaaaaaaah---!!"
2002805-111 = "(Depois disso, acalmei Hinata, que estava muito desanimada, e passamos o resto do tempo juntos)"
2002805-115 = "(Decidimos deixar a prática da confissão para outra oportunidade)"
