[translation]
2003703-1 = "ポリス・ストーリー～流れるプール編～"
2003703-3 = "お、先生も手伝いに来てくれたの～？"
2003703-4 = "これで楽が……#nいや、監視を徹底できるね。"
2003703-5 = "特別に、同行させてあげるよ。"
2003703-6 = "[s1] \"……どうして浮き輪を持ってるの？\"\n[s2] \"仕事してるんじゃなかったの？\""
2003703-9 = "なに言ってるのさ、先生。#nこれもライフセーバーの装備だよ。"
2003703-10 = "パーク全体を見回るためには……。"
2003703-11 = "当然、効率良く移動する必要があるじゃん？"
2003703-12 = "[s] \"……浮き輪に乗って見回りをする、ってこと？\""
2003703-13 = "その通りっ！"
2003703-14 = "ここのウォーターパーク、#nすっごく長い流水プールがあるでしょ？"
2003703-15 = "浮き輪をつけて流れに身を任せとけば、#nパーク内の監視ができるってわけ。"
2003703-16 = "これが夢に描いた「自動パトロールシステム」だよ！"
2003703-17 = "[s3] \"……遊ぶ気満々だよね。\"\n[s4] \"流水プールで遊んでるだけじゃない？\""
2003703-20 = "いやいや！#n正真正銘、パーク内のパトロールだよ！"
2003703-21 = "ふふっ。#nもちろん、楽しい任務になると思うけどね。"
2003703-22 = "それじゃ、さっそく仕事しちゃおっかな。#n浮き輪を置いて、っと……。"
2003703-27 = "ほっ！"
2003703-33 = "……あれ？"
2003703-36 = "[wa:700]― [log=후부키 수영복]あ、[wa:1090]あれれ……？[/log]"
2003703-39 = "[wa:1170]― [log=후부키 수영복]んぐぐぐっ！[/log]"
2003703-40 = "[wa:3020]― [log=후부키 수영복]……[wa:770]くうぅ。[/log]"
2003703-43 = "[wa:1430]― [log=후부키 수영복]ぬ、[wa:1040]抜けない……[/log]"
2003703-44 = "[wa:2390]― [log=후부키 수영복]まさか[wa:1480]一生このままじゃないよね……？[/log]"
2003703-47 = "[wa:1430]― [log=후부키 수영복]ねえ、[wa:580]先生。[/log]"
2003703-48 = "[wa:1300]― [log=후부키 수영복]ちょっと助けて！[/log]"
2003703-51 = "― [log=후부키 수영복]これからはサボる回数も減らすし、[/log]"
2003703-52 = "[wa:2730]― [log=후부키 수영복]仕事も真面目にするから……[/log]"
2003703-55 = "[wa:900]― [log=후부키 수영복]あと、[wa:1200]秘蔵のドーナッツもあげるから！[/log]"
2003703-58 = "― [log=후부키 수영복]ひゃっ！？[/log]"
2003703-59 = "[wa:920]― [log=후부키 수영복]う、[wa:620]後ろから触るのは[wa:1540]ちょっと！？[/log]"
2003703-62 = "（フブキを浮き輪から出してあげた……）"
2003703-64 = "はぁ、はぁ……。"
2003703-65 = "……どうなることかと思った。"
2003703-66 = "当分、浮き輪はコリゴリだよ……。"
2003703-67 = "[s] \"真面目に歩いてパトロールしないとね。\""
2003703-68 = "はぁ……めんどくさいなぁ。"
2003703-73 = "そうだ！浮き輪じゃなくてライフジャケットなら！"
2003703-75 = "（その後、サボろうとするフブキを連れてパトロールをした）"
