[translation]
2003302-1 = "A grande presidente do Pandemônio!"
2003302-2 = "（Cheguei em frente ao Pandemônio no horário combinado, mas...）"
2003302-7 = "[ns] \"...Aconteceu alguma coisa?\""
2003302-10 = "Vamos! Apressem-se! Onde está a estátua da presidente!?"
2003302-11 = "Recebemos a notificação do veículo de transporte de que chegará em breve!"
2003302-13 = "Muito bem, como estão os preparativos para a cerimônia de recepção do convidado de honra?"
2003302-15 = "Assim que terminarmos o último ensaio, ficaremos de prontidão atrás do edifício do conselho!"
2003302-17 = "Hum... está tudo correndo bem, mas é justamente nessas horas que devemos ter o máximo de cuidado."
2003302-18 = "Não se esqueçam! A presidente Makoto deu a máxima importância a esta reunião."
2003302-19 = "O convidado que vamos receber é alguém de altíssimo escalão. #nNão podemos permitir um único erro."
2003302-20 = "Garantir que tudo corra perfeitamente para provar a autoridade da presidente Makoto é a nossa missão!"
2003302-21 = "Hoje é o dia de mostrar o verdadeiro poder do Pandemônio!"
2003302-24 = "Sim, senhor!!!"
2003302-30 = "[ns] \"Olá, vocês estão ocupados?\""
2003302-31 = "Ah, professor [USERNAME]. Faz tempo que não nos vemos."
2003302-32 = "Desculpe por recebê-lo em um momento tão caótico."
2003302-33 = "[s] \"Aconteceu alguma coisa?\""
2003302-34 = "Ah, é que... a presidente Makoto nos informou que um convidado VVIP chegará às 13h."
2003302-35 = "Quem é essa pessoa, você pergunta?"
2003302-36 = "Bem, é uma informação ultrassecreta, então nem eu fui avisado..."
2003302-37 = "Só ouvi dizer que é alguém que está prestes a dominar todo o Kivotos com um ímpeto imparável."
2003302-38 = "[s] \"E-entendo... bem, boa sorte então?\""
2003302-41 = "Em frente à sala da presidência do Pandemônio"
2003302-42 = "（Depois de cumprimentar os membros do Pandemônio que trabalhavam com eficiência, cheguei ao meu destino após alguns minutos）"
2003302-47 = "[ns] \"Com licença...\""
2003302-48 = "Não! Isso também não serve!"
2003302-52 = "[ns] \"...Hum?\""
2003302-54 = "Hum, hum, hum... se não for isso... então não é aquilo..."
2003302-55 = "E olha que o tempo está acabando...!"
2003302-56 = "Como é possível que eu não consiga pensar em nenhuma ideia...!?"
2003302-60 = "Opa!? Nem vi que horas eram...!?"
2003302-61 = "Grrr...! O que eu faço... qual seria a melhor forma..."
2003302-62 = "[s] （Makoto... o que será que ela está pensando com tanta seriedade?）"
2003302-67 = "Quando o professor do Schale entrar na sala... com que expressão e pose devo recebê-lo!? #nPara mostrar a dignidade de Hanuma Makoto...!"
2003302-68 = "[s] \"Você estava preocupada com isso!?\""
2003302-69 = "Nuoaaahhh!?"
2003302-73 = "Cof, cof, cof, cof...!!!"
2003302-74 = "[s] \"Makoto! Você está bem!?\""
2003302-75 = "Cof, cof, haa... haa..."
2003302-76 = "...Haaa."
2003302-77 = "...Ufa."
2003302-78 = "Ah, é você, professor."
2003302-79 = "Hum, eu estava te esperando."
2003302-80 = "[s] （Até agora há pouco, ela parecia estar desesperada...）"
2003302-81 = "Hum? Mas por que o professor já está aqui..."
2003302-82 = "Agora deveria ser o horário da cerimônia..."
2003302-83 = "[s1] （Eu suspeitava, mas será que aquela preparação era...）\n[s2] （Teria sido vergonhoso se eu tivesse entendido errado, então fingi que não sabia...）"
2003302-86 = "Kiki-ki. Entendo... então é isso."
2003302-87 = "Cerimônias formais não significam nada..."
2003302-88 = "Se é para desperdiçar tempo com essas coisas, é melhor irmos direto ao ponto!"
2003302-89 = "[s] \"Não, não é que eu ache que seja um desperdício...\""
2003302-90 = "Kikikiki! Como esperado, você realmente conquistou o coração desta Makoto-sama!"
2003302-91 = "Ah! É exatamente por isso que você é digno desta Hanuma Makoto!"
2003302-92 = "Como eu pensei, meu julgamento nunca falha!"
2003302-93 = "[s] \"Ser elogiado desse jeito até me deixa sem graça, sabia!?\""
2003302-94 = "Muito bem, decidi!"
2003302-95 = "Vou avisar os membros para cancelarem todos os eventos."
2003302-96 = "Hoje, eu e o Sensei vamos ter uma conversa confidencial."
2003302-97 = "Então, espere lá fora por um tempo."
2003302-98 = "Assim que eu terminar os preparativos, eu te chamo."
2003302-99 = "[s] \"C-certo.\""
2003302-101 = "(E assim, enquanto eu esperava do lado de fora...)"
2003302-102 = "Isso fica aqui... ah, isso fica ali..."
2003302-108 = "Hum! Onde você está se escondendo! \"Imperador Lionmaru Júnior III\"! É a sua vez!"
2003302-118 = "Droga! Que bicho rápido!!"
2003302-119 = "Fique quieto...!"
2003302-120 = "Isso!"
2003302-121 = "[ns] \"..............\""
2003302-122 = "(...Finalmente os barulhos pararam)"
2003302-123 = "Haa... haa... hum, pode entrar."
2003302-124 = "[s] \"Bem, com licença...\""
2003302-130 = "[wa:500]― [log=마코토]Kishishi, [wa:1100]Sensei, [wa:1300]eu estive observando suas conquistas.[/log]"
2003302-133 = "[wa:200]― [log=마코토]Você ajudou os outros, [wa:1350] resolveu incidentes...[/log]"
2003302-134 = "[wa:1350]― [log=마코토]E elevou a fama do Schale![/log]"
2003302-137 = "[wa:500]― [log=마코토]Kikiki, [wa:1400]chegando a este ponto,[/log]"
2003302-138 = "[wa:1400]― [log=마코토]não há como não [wa:550]admitir――[/log]"
2003302-141 = "― [log=마코토]Sim, [wa:1300]que você é alguém capaz de [wa:1300]ficar lado a lado com esta Makoto-sama,[/log]"
2003302-142 = "[wa:900]― [log=마코토]uma pessoa de grande talento![/log]"
2003302-145 = "[ns] \"U-um talento...?\""
2003302-146 = "[wa:1000]― [log=마코토]Avalio sua capacidade muito bem...[/log]"
2003302-147 = "[wa:2100]― [log=마코토]e gostaria de lhe fazer [wa:1300]uma proposta importante que você não poderá recusar.[/log]"
2003302-150 = "― [log=마코토]Sensei do Schale, [wa:2700]junte-se ao meu Pandemonium...[/log]"
2003302-151 = "[wa:2900]― [log=마코토]Não, [wa:1400]junte-se a esta Hanuma Makoto [wa:1100]e vamos formar uma aliança![/log]"
2003302-154 = "[ns] \"B-bem...\""
2003302-155 = "[wa:1600]― [log=마코토]Se unirmos nossas forças,[/log]"
2003302-156 = "[wa:1800]― [log=마코토]conquistar Kivotos [wa:700]será fácil![/log]"
2003302-159 = "[wa:200]― [log=마코토]Se isso acontecer,[/log]"
2003302-160 = "[wa:1400]― [log=마코토]eu lhe darei metade de Kivotos para o Schale.[/log]"
2003302-163 = "― [log=마코토]E então, [wa:900]não é um bom negócio?[/log]"
2003302-166 = "[wa:500]― [log=마코토]Vamos! [wa:300]Sensei! [wa:1000]Comigo! [wa:1200]Vamos realizar [wa:1100]este sonho grandioso![/log]"
2003302-167 = "[wa:2100]― [log=마코토]Kikiki, [wa:1200]kishishishishishi![/log]"
2003302-170 = "Kikiki. E então, o que acha da minha proposta?"
2003302-171 = "Sensei [USERNAME], uma proposta tão atraente que nem você seria capaz de recusar――"
2003302-175 = "Uou!? Lionmaru! E-ei, você!? Pare de morder!!"
2003302-176 = "......A-a-atchim!!!"
2003302-181 = "[ns3] \"Ah, bem... agradeço a proposta, mas sinto muito.\"\n[ns4] \"Já estou ocupado o suficiente com o trabalho no Schale.\""
2003302-184 = "O que você disse...!?"
2003302-185 = "V-você recusou a proposta atraente desta Hanuma Makoto... tão facilmente assim...!?"
2003302-186 = "Disseram que o Sensei não tem interesse em riqueza ou fama..."
2003302-187 = "A Chiaki me avisou que você provavelmente não aceitaria a proposta desta Makoto, mas... #nquem diria que você realmente recusaria!"
2003302-188 = "[s5] （……riqueza？）\n[s6] （……fama？）"
2003302-191 = "Kiki... kikiki..."
2003302-192 = "Kya-hahahaha!"
2003302-193 = "[s] \"V-você está bem...?\""
2003302-194 = "Mas! Eu não estou desapontada nem um pouco! Sensei!"
2003302-195 = "Eu, Hanuma Makoto, como uma verdadeira líder, sei quando é a hora de recuar!"
2003302-196 = "Se você está ocupado com o trabalho no Schale, não tem problema. #nA Makoto-sama aqui sabe ser flexível e se adaptar aos outros!"
2003302-197 = "Sim. Por hoje, ficarei satisfeita apenas com este encontro."
2003302-198 = "É só uma questão de tempo até o Sensei cooperar com o Pandemonium!"
2003302-199 = "Kikikiki!!"
2003302-200 = "Então, conto com você daqui para frente! Sensei [USERNAME] do Schale!"
2003302-201 = "[s] \"S-sim... conto com você também, Makoto.\""
2003302-203 = "（……E assim, o memorável encontro com Makoto terminou de forma... pacífica?）"
