[translation]#[Não revisado] - Filipe 09/06/26
2005905-1 = "Diabinha e as férias"
2005905-2 = "(Naquela noite, preocupado com a mensagem de Mutsumi, foi ao hotel)"
2005905-8 = "Saguão do hotel"
2005905-12 = "[ns] (Este será o quarto?)"
2005905-14 = "Hmm? Quem é?"
2005905-15 = "Ora, Sensei? A essa hora?"
2005905-19 = "Hmm, você veio mesmo?"
2005905-20 = "Sério? É um hotel onde uma garota está sozinha, sabia?"
2005905-21 = "Kufufu. Você é bem ousado, hein?"
2005905-22 = "[s] \"Está tudo bem? Não aconteceu nada?\""
2005905-23 = "... Hã? Ficou preocupado?"
2005905-24 = "Ahaha! Eu disse que não aconteceu nada. Sabe por quê?"
2005905-37 = "– Então fui atrás dos remanescentes e, como esperado, eles estavam lá."
2005905-38 = "Juntaram dinheiro para comprar armas e planejavam te fazer refém."
2005905-39 = "Mas não se preocupa. Eu fiz com que virassem pó."
2005905-40 = "O dinheiro que eles ganharam vendendo bombas, também peguei tudo."
2005905-41 = "Olha aí."
2005905-46 = "(A bolsa de Mutsumi estava cheia de dinheiro)"
2005905-50 = "[ns] \"Isso tudo!?\""
2005905-51 = "Kufufu, surpreso?"
2005905-52 = "Aí, por via das dúvidas, vim para um hotel seguro."
2005905-53 = "Não se sabe se tem mais alguém querendo pegar isso."
2005905-54 = "[s] \"O que vai fazer com esse dinheiro?\""
2005905-55 = "Hmm, não tem como devolver..."
2005905-56 = "Quem talvez fique com ele seja eu, que me dei todo esse trabalho?"
2005905-57 = "O que você acha, Sensei?"
2005905-58 = "[s1] \"Acho que pode.\"\n[s2] \"Acho melhor não...\""
2005905-59 = "Ah, é mesmo?"
2005905-60 = "Kufufu, eu sabia que você ia dizer isso."
2005905-61 = "Bem, eu também pensei a respeito."
2005905-62 = "Se eu ficar com esse dinheiro..."
2005905-63 = "Não seria divertido!"
2005905-64 = "[ns] \"... Hã?\""
2005905-65 = "Pensa comigo. Se eu ficar com esse dinheiro, vou usar para manter a empresa. Isso não é chato?"
2005905-66 = "A Empresa tem que viver no limite para ser divertida."
2005905-67 = "Ah, isso é segredo, hein? Kufufu."
2005905-68 = "[s] \"Então tem algum lugar para guardar?\""
2005905-69 = "Sim! Esse dinheiro..."
2005905-70 = "Vou deixar tudo com você!"
2005905-73 = "[wa:974]– [log=무츠키 드레스]Quer saber? [wa:1119]Mesmo parecendo que não, [wa:637]eu confio [log]"
2005905-75 = "– [log=무츠키 드레스]bastante em você, [wa:1890]Sensei.[/log]"
2005905-78 = "[wa:952]– [log=무츠키 드레스]O quê, [wa:626]surpreso?[/log]"
2005905-80 = "– [log=무츠키 드레스]... Porque só fico pregando peças?[/log]"
2005905-83 = "– [log=무츠키 드레스]Kufufu. [wa:926]Eu não vou [wa:1189]com qualquer um, sabia.[/log]"
2005905-86 = "[wa:2098]– [log=무츠키 드레스]Bem, [wa:932]então... [wa:1416]o que fazer com ele, [wa:1690]deixo com você.[/log]"
2005905-88 = "– [log=무츠키 드레스]Você vai [wa:1166]usar para algo que [wa:1502]vale a pena, né?[/log]"
2005905-91 = "– [log=무츠키 드레스]Pode doar [wa:754]para alguma instituição...[/log]"
2005905-93 = "– [log=무츠키 드레스]Ou usar para financiar [wa:1529]as suas atividades...[/log]"
2005905-96 = "[wa:740]– [log=무츠키 드레스]Se não quiser, [wa:1225]pode só guardar –[/log]"
2005905-98 = "– [log=무츠키 드레스]Deixar guardado para [wa:569]o nosso futuro, [wa:2393]quem sabe?[/log]"
2005905-101 = "[wa:1285]– [log=무츠키 드레스]Hã? [wa:755]O que eu estou dizendo?[/log]"
2005905-104 = "[wa:882]– [log=무츠키 드레스]Kufufu![wa:993] Sei lá?[/log]"
2005905-106 = "– [log=무츠키 드레스]O que será que eu quero dizer?♪[/log]"
2005905-110 = "(Depois, aproveitou o tempo com Mutsumi, rindo das suas brincadeiras)"
2005905-111 = "(Preocupado, ficou com ela até tarde, mas nenhum problema aconteceu)"
2005905-116 = "(Pagou a conta do hotel escondido depois)"
2005905-117 = "(Ainda bem que não deu em nada maior...)"