[translation]
21010-1 = "第1話;冒険の始まり"
21010-2 = "……"
21010-4 = "私の声が、聞こえますか……"
21010-6 = "そこにいますか？この世界を救う――"
21010-11 = "――勇者よ。"
21010-12 = "あなたのことを、ずっと待っていました。"
21010-13 = "今こそ、全てを話しましょう。太古、天族と魔族が……"
21010-14 = "……"
21010-15 = "カットカット、カッーーート！"
21010-16 = "ダメダメ、ありきたりすぎ！これだと発売と同時にこけそうな感じ！"
21010-17 = "私がユーザーだったら、プロローグでこのテキストが出た瞬間に「あ、やめよ」ってなるよ！"
21010-18 = "もう一回！うーん……"
21010-20 = "……勇者よ、あなたを待っていました。"
21010-21 = "私は、女神「モモリア」。"
21010-22 = ""
21010-23 = "私たちの世界「ミレニアムランド」は今、過去に類を見ない危機に瀕しています。"
21010-24 = "この危機を乗り越え、生徒会の廃部命令からゲーム開発部を……いえ、ミレニアムランドを救えるのは、あなただけです。"
21010-25 = "過酷な道のりになるかもしれません……それでも、どうかお願いいたします。"
21010-27 = "これから始まる、あなたの冒険のその先に……。"
21010-28 = "どんな試練や逆境が待ち受けているのか、今はまだ分かりません。"
21010-29 = "ですが……どうか最後まで、勇気だけは失わないでください。"
21010-30 = "勇者様のそばには、旅路を共にする少女たちもいるはずですから。"
21010-32 = "新しい世界で、あなたはその少女たちから「勇者」ではなく……。"
21010-34 = "もっと特別な、ふさわしい名で呼ばれることになるでしょう。"
21010-36 = "その名前とは――"
21010-39 = "先生！！"
21010-41 = "？？？"
21010-42 = "……"
21010-43 = "[s1] \"見慣れない天井……。\"\n[s2] \"ここは、どこ……？\""
21010-44 = "あっ、目覚めた！？"
21010-45 = "あっ、目覚めた！？"
21010-46 = "気がついたか？君は運がいいな！"
21010-47 = ""
21010-48 = "急に変な喋り方しないで、先生が戸惑ってるでしょ。"
21010-49 = "へへっ、嬉しくってつい……先生、大丈夫？このまま目を覚まさないのかと思ったよ。"
21010-50 = "本当に良かったです。お姉ちゃんが窓の外に投げたプライステーションが、偶然とはいえ先生の頭に命中した時は……このまま殺人事件の容疑者になってしまうかと思いました。"
21010-51 = "お姉ちゃんの代わりに謝ります。ごめんなさい、先生。"
21010-52 = "ふーんだ。そう言うミドリだって、私が「もしかして先生に当たっちゃったかも！？」って叫んだ時、第一声は「プライステーションは無事！？」だったじゃん。"
21010-53 = "そ、それは、私たちゲーム開発部の財産リスト第1号だし、思わず……。"
21010-54 = "と、とにかく！！"
21010-55 = "先生は、あのシャーレから来たんですよね？"
21010-56 = "うわっ、本当に！？じゃあ私たちが送った手紙、読んでくれたんだ！もし読んでくれたとしても、本当に来てくれるなんて思ってなかった！"
21010-57 = "[s] \"手紙って、あの…… \""
21010-59 = "シャーレ・執務室"
21010-60 = "先生、ミレニアムサイエンススクールから要請が届きました。"
21010-61 = "送り主は……ミレニアムのゲーム開発部？みたいです。読んでみますね。"
21010-62 = "「ゲーム開発部は今、存続の危機に陥ってます。生徒会からの廃部命令により破滅が目前に迫っている今、助けを求められる相手はあなただけです。勇者よ、どうか私たちを助けてください！」"
21010-63 = "なるほど。すごく面白いと言いますか……かなり切羽詰まっているということは、ひしひしと伝わってきますね……。"
21010-64 = "あ、先生はミレニアムサイエンススクールについてご存じですか？"
21010-65 = "[s3] \"うん、少しくらいなら。\"\n[s4] \"あんまり……。\""
21010-66 = "そうでしたか、ミレニアムサイエンススクールはご存じの通り――"
21010-67 = "トリニティ、ゲヘナと合わせてキヴォトス三大学園と呼ばれる大きな学校です。"
21010-68 = "通称ミレニアム、他のどんな学園よりも合理と技術に重きを置いています。"
21010-69 = "科学の研究に特化しており、理系の生徒さんたちが多く集まっていることが特徴ですね。"
21010-70 = "伝統ある名家のような他の二つ、ゲヘナとトリニティに比べると歴史は長くありませんが、影響力という点においては引けを取りません。"
21010-71 = "キヴォトスで「最新鋭」或いは「最先端」の名を冠するものは、そのほとんどがミレニアムから生まれると言っても過言ではないくらいです。"
21010-72 = "そんな学校なのですが……一体何があったのでしょうか？"
21010-73 = "ではご説明しますね。ミレニアムサイエンススクールとは、トリニティ、ゲヘナと合わせてキヴォトス三大学園と呼ばれる大きな学校です。"
21010-74 = "通称ミレニアム、他のどんな学園よりも合理と技術に重きを置いています。"
21010-75 = "科学の研究に特化しており、理系の生徒さんたちが多く集まっていることが特徴ですね。"
21010-76 = "伝統ある名家のような他の二つ、ゲヘナとトリニティに比べると歴史は長くありませんが、影響力という点においては引けを取りません。"
21010-77 = "キヴォトスで「最新鋭」或いは「最先端」の名を冠するものは、そのほとんどがミレニアムから生まれると言っても過言ではないくらいです。"
21010-78 = "いかがでしょう、行ってみますか？"
21010-79 = "……"
21010-80 = ""
21010-81 = "ミレニアム・ゲーム開発部"
21010-82 = "あらためて……ゲーム開発部へようこそ、先生！"
21010-83 = "先生に来ていただけて、嬉しいです。"
21010-84 = "私はゲーム開発部、シナリオライターのモモイ！"
21010-85 = "私はミドリ。イラストレーターで、ゲームのビジュアル全般を担当してます。"
21010-86 = "あと今はここにいないけど、企画周りを担当してる私たちの部長、ユズを含めて……"
21010-87 = "私たちが、ミレニアムサイエンススクールのゲーム開発部だよ！"
21010-88 = "よしっ！じゃあ先生も来たことだし、「廃墟」に行くとしよっか！"
21010-89 = "[s5] \"廃墟……？\"\n[s6] \"あの、もうちょっと詳しく状況を説明してくれる？\""
21010-90 = "あ、じゃあ最初から順に説明するね。"
21010-91 = "あ、うん！"
21010-92 = "えっとね、まず私たちゲーム開発部は今までずっと、平和に16ビットのゲームとかを作ってたんだけど。"
21010-93 = "ある日……急に生徒会から襲撃されたの！"
21010-94 = "一昨日には、生徒会四天王の一人であるユウカから最後通牒を突きつけられて。"
21010-95 = "[s] \"最後通牒？\""
21010-96 = "それに関しては、私から直接ご説明しましょうか？"
21010-97 = "こ、この声は！？"
21010-99 = "次回;セミナーの会計、ユウカ"
