[translation]
21070-1 = "第7話;銃と呼ぶには大きすぎる"
21070-2 = "ミレニアム・ゲーム開発部"
21070-3 = "ミレニアム……ううん、キヴォトスの生徒は、みんなそれぞれ自分の武器を持ってるの。"
21070-4 = "だから、アリスにも武器を見繕ってもらわないとね。"
21070-5 = "調達する方法は色々あるけど、このミレニアムで一番手っ取り早く、ちゃんとした武器が手に入る場所と言えば……"
21070-6 = "……やっぱりエンジニア部かな。"
21070-7 = "エンジニア、部……？"
21070-8 = "機械を作ったり、修理したりする専門家たちのことを、ミレニアムでは「マイスター」って呼んでるんだけど。"
21070-9 = "エンジニア部はそのマイスターがたくさん集まってる、ハードウェアに特化した部活なの。"
21070-10 = "機械全般に精通してるのはもちろん、武器の修理とか改造なんかも担当してる部活だから。"
21070-11 = "多分、使ってない武器とかが色々残ってるんじゃないかなって。"
21070-12 = "というわけで、早速行ってみよっか！"
21070-14 = "エンジニア部・作業室"
21070-15 = "……なるほど、だいたい把握できたよ。"
21070-16 = "新しい仲間に、より良い武器をプレゼントしたい……と。"
21070-17 = "そういうことであれば、エンジニア部に来たのは素晴らしい選択だね。"
21070-18 = "ミレニアムにおける勝敗というのは、優れた技術者の有無に大きく左右されてしまうものだ。"
21070-19 = "そっちの方に、私たちがこれまで作ってきた試作品が色々と置いてある。"
21070-20 = "そこにあるものであれば、どれを持って行っても構わないよ。"
21070-21 = "やった！ありがとう、先輩！"
21070-22 = ""
21070-23 = ""
21070-24 = "やあ……1年生のヒビキだよ。良ければ私が、何か良いものを見繕ってあげる……。"
21070-25 = "……これはどう、アリス？"
21070-27 = "へえ、拳銃？"
21070-28 = "見た感じ、多分だけど……これまでにあまり戦闘経験は無いはず……。"
21070-29 = "その言葉は否定します。アリスはこれまでに人類を27回救い、魔王軍との46回に渡る戦闘を行い、三桁を超えるダンジョン探索を行ってきました。経験値はそれなりに豊富です。"
21070-31 = "……。"
21070-32 = "それは、すごいね……。"
21070-33 = "とにかく、銃器を使用した経験は……あまり無さそう。"
21070-34 = "そういう人にはやっぱり拳銃が良い……これはプラスチック製だから軽いし、反動も少ない……。"
21070-35 = "そういう意味でも、色々と初心者に優しいはず……それに、何より……。"
21070-36 = ""
21070-37 = "この銃にはミレニアム史上、今まで存在しなかった機能が搭載されてる。"
21070-39 = "な、何それ？"
21070-40 = "何か聞く前から凄そう……いったいどんな機能なの？"
21070-41 = "それはね……"
21070-42 = "「Bluetooth」機能、だよ。"
21070-43 = "……えっ？"
21070-44 = "Bluetoothを通じて、音楽鑑賞やファイルの転送まで可能な拳銃……調べた限り、そんなものは今までに存在しなかった。"
21070-45 = "……もちろん、スモモ機能も搭載。乗り場のICパネルにタッチして、交通機関を利用することもできる。"
21070-46 = "それにNFC機能も付いてるから、コンビニペイだって使えちゃう……。"
21070-47 = "す、すごいと言えば、すごい気もするけど……。"
21070-48 = "コンビニで「これで決済を」って拳銃を突き出したら、店員の人がびっくりしちゃうよ！"
21070-49 = "あれ、そういえばアリスちゃんはどこに……？アリスちゃん、アリスちゃーん？"
21070-50 = "……あ、あそこに。"
21070-51 = "……あれは、"
21070-52 = ""
21070-54 = "（じーっ……）"
21070-55 = ""
21070-57 = "これは……？"
21070-58 = "ふっふっふっ……お客さん、お目が高いですね。"
21070-59 = "え、えっと……？"
21070-60 = "説明が必要なら、いつでもどこでも答えをご提供！エンジニア部のマイスター、コトリです！"
21070-61 = "……？"
21070-62 = "あなたがアリスですね。ゲーム開発部、四人目のメンバー！"
21070-64 = "あ、コトリちゃん久しぶり。ところで、アリスちゃんが見てるこの大きいのは何？"
21070-67 = "まるで……「大砲」、みたいだけど。"
21070-68 = "良い質問ですね、ミドリ。これはエンジニア部の下半期の予算、その内の約70%近くをかけて作られた……"
21070-69 = "エンジニア部の野心作、「宇宙戦艦搭載用レールガン」です！"
21070-70 = "宇宙戦艦、って……また何かとんでもないことを……。"
21070-71 = "前にも、確かコールドスリープしようとして、「未来でまた会おう」って言いながら冬眠装置を作って大騒ぎした挙句、みんなして風邪ひいてなかった？"
21070-72 = "……その「未来直行エクスプレス」なら、今でもよく使っているよ。"
21070-73 = "……まあ、冷蔵庫として、だがね。食べ物をもっと先の未来にまで送れるようになったから、失敗ではないさ。"
21070-74 = "使い道の割に、名前が大袈裟！"
21070-75 = "話を戻しますとエンジニア部は今、ヘリコプターや汎用作業ロボットに続いて、宇宙戦艦の開発を目標としているのです！"
21070-76 = "このレールガンは、その最初の一歩です。大気圏外での戦闘を目的として開発された実弾兵器！これはミレニアム史上、明らかに類を見ない初の試みです！"
21070-77 = "かっこいい……聞いただけでワクワクしてくる！"
21070-78 = "さすがミレニアムのエンジニア部！今回は上手く行ってるんだね！？"
21070-79 = "ふっふっふっ、もちろんです！"
21070-80 = "と言いたいところだったのですが、ちょっと今は中断してまして……。"
21070-81 = "えええっ！？なんで！期待したのに！"
21070-82 = "いつものことながら技術者たちの足を引っ張るのは、いつの世も想像力や情熱の欠如ではなく、予算なんです……。"
21070-83 = "このレールガンを作るだけで下半期の予算の70%もかかったのに、宇宙戦艦そのものを作るには果たして、この何千倍の予算がかかることやら……。"
21070-84 = "そんなの計画段階で分かることじゃん！どうしてこのレールガン、完成まで持って行っちゃったのさ！？"
21070-85 = ""
21070-87 = "愚問だね、モモイ。"
21070-88 = "……ビーム砲は、ロマンだからだよ。"
21070-89 = "（コクリ）"
21070-90 = "その通りです！ビーム砲の魅力が分からないなんて、全くこれだからモモイは。"
21070-91 = "バカだ！頭良いのにバカの集団がいる！"
21070-92 = ""
21070-93 = "エンジニア部の情熱が注ぎ込まれた、この武器の正式名称は……"
21070-94 = "「光の剣：スーパーノヴァ」！"
21070-95 = "また無駄に大げさな名前を……。"
21070-96 = "……！"
21070-97 = "ひ、光の剣……！？"
21070-98 = "あ、アリスの目が輝いてる……！？"
21070-99 = "わぁ、うわぁ……！"
21070-100 = "アリスちゃんがこんなに興奮してるの、初めて見たかも。"
21070-101 = "……これ、欲しいです。"
21070-102 = "……え？"
21070-103 = ""
21070-104 = "偉大なる鋼鉄の職人よ、あの龍の息吹が欲しいのだ。"
21070-106 = "うーん、そう言ってくれるのは嬉しいのだけど……。"
21070-107 = "申し訳ないのですが、それはちょっと出来ないご相談です！"
21070-109 = "何で！？この部屋にあるものなら何でも持っていって良いって言ったじゃん！"
21070-110 = "……それは、理由があって。"
21070-111 = "理由？"
21070-112 = "もしかして、私のレベルが足りてないから……装着可能レベルを教えてください！"
21070-113 = "いや、悪いがそういった問題ではなくてだね……"
21070-114 = "もっと現実的な問題なんだ。"
21070-115 = "お金かー……。"
21070-116 = "心配しないでアリス。私が、ミドリのプライステーションを売り払ってでも……"
21070-117 = "……お金の問題でもないよ。"
21070-118 = "現実にお金以上の問題なんて無いでしょ！"
21070-119 = "まあ、製作における予算という意味では、ある程度同意はするけれど……。"
21070-120 = "……この武器は、個人の火器として使うには大きくて重すぎる。"
21070-122 = "なんと、基本重量だけで140kg以上です！さらに光学照準器とバッテリーを足した上で砲撃を行うと、瞬間的な反動は200kgを超えます！"
21070-124 = "……。"
21070-125 = "これをカッコいいと言ってくれただけで、私たちは嬉しいよ。ありがとう。持って行けるのならば、本当にあげたいところなのだけど……。"
21070-126 = "……？"
21070-127 = "……！"
21070-128 = "……汝、その言葉に一点の曇りもないと誓えるか？"
21070-129 = "ん？この子、また喋り方が……"
21070-130 = "た、多分ですが、「本当なのか」って聞いてるんだと思います。"
21070-131 = "もちろん嘘は言っていないが……それはつまり、あれを持ちあげるつもり、ということかい？"
21070-132 = "（こくり）"
21070-133 = ""
21070-134 = "（スッ……）"
21070-135 = "この武器を抜く者……"
21070-136 = "……此の地の覇者になるであろう！"
21070-137 = "ふふふっ、なるほど。意気込みは素晴らしいですね！"
21070-138 = ""
21070-139 = "（グッ）"
21070-140 = "ふっ……！"
21070-141 = "無理は、しない方がいい……クレーンでも使わないと持ち上がらな――"
21070-142 = ""
21070-143 = "んんんんっっ……！"
21070-144 = "……まさか。"
21070-145 = "えぇぇっ！？"
21070-146 = "（グググググッ――！）"
21070-147 = "……も、持ち上がりました！"
21070-148 = "嘘……信じられない……。"
21070-149 = "えっと、ボタンは……これがBボタンでしょうか……？"
21070-150 = "ま、待って……！"
21070-152 = "……っ、光よ！！！"
21070-153 = ""
21070-155 = "（ドカアアァァァァン！）"
21070-156 = "あああああっ！わ、私たちの部室の天井がぁっ！？"
21070-157 = "……すごいです。"
21070-158 = "アリス、この武器を装着します。"
21070-159 = "ほ、本当に使えるなんて……で、ですがそれだけは、その……！予算とか諸々の問題で、できれば他のでお願いしたく……！"
21070-160 = "……いや、"
21070-161 = "構わないさ、持っていってくれ。"
21070-162 = "ウタハ先輩……本当に良いんですか？"
21070-163 = "ああ。どちらにせよ、この子以外には使えないだろうからね。"
21070-164 = "ヒビキ、後でアリスが持ち運びやすいように、肩紐と取っ手の部分を作ってあげてくれ。"
21070-165 = "分かった。"
21070-166 = "……前向きに考えると、実戦データを取れるようになったのはありがたいかも。"
21070-167 = "うわ、何だかものすごい武器をもらっちゃったね！ありがとう！"
21070-168 = "あ、ありがとうございます！"
21070-169 = "いや、お礼にはまだ早いさ。"
21070-170 = "え？"
21070-171 = ""
21070-172 = "さて……ヒビキ、以前に処分要請を受けたドローンとロボット、全機出してくれるかい。"
21070-173 = "……うん。"
21070-175 = "えっと……ウタハ先輩？なんだか展開がおかしいような……。"
21070-176 = "これってもしかして、「そう簡単に武器は持って行かせない！」みたいなパターンじゃない！？"
21070-177 = "その通りさ。"
21070-178 = "その武器を本当に持って行きたいのなら……"
21070-179 = ""
21070-181 = "私たちを倒してからにしてください！"
21070-182 = "！？"
21070-183 = "えええっ！そんな、ウタハ先輩どうして！？"
21070-184 = "ぶ、武器一つのためにここまで……？"
21070-186 = "他の武器なら、喜んで渡しただろうけれど……。"
21070-187 = "その武器については、確認が必要かなと思ってね。"
21070-188 = "か、確認？"
21070-189 = "いや……「資格」と呼んだ方が相応しいかな。"
21070-190 = "資格？それって……。"
21070-191 = ""
21070-193 = "前方に戦闘型ドローン及びロボットを検知、敵性反応を確認。"
21070-194 = "来ます！"
21070-195 = "ああもうっ！"
