[translation]
21090-1 = "Episódio 9;As Perguntas de Yuuka."
21090-2 = "Millennium · Departamento de#nDesenvolvimento de Jogos"
21090-3 = "……Aris. Se você está aqui#ncontra a vontade, coagida pelo#nDepartamento de Desenvolvimento de#nJogos, pisca o olho esquerdo."
21090-4 = "……?"
21090-5 = "Ei, que pergunta é essa logo de#ncara!? Mesmo falando baixinho dá#npra ouvir, viu! E, aliás, a gente#nnão faria uma coisa dessas!!"
21090-10 = "Olha só pra esta carteirinha#nreluzente! Prova irrefutável de que#nela é aluna da Millennium!"
21090-11 = "Hmm…… de fato, eu confirmei que#na Aris está registrada na lista de#nalunas também, mas……"
21090-12 = "Eu não sou mulher de me deixar#nenganar assim tão fácil."
21090-14 = "(Estremece)"
21090-15 = "(D-descobriu!?)"
21090-17 = "Bom, então vamos retomar o#ninterrogatório."
21090-18 = "Você nem tá mais tentando#ndisfarçar……"
21090-20 = "Aris, o que te levou a entrar#npro Departamento de Desenvolvimento de#nJogos?"
21090-21 = "Não é \"quando me dei conta, já#nestava aqui\", e sim……"
21090-22 = "Momoi, por que você tá encarando#na Aris desse jeito? Para com isso."
21090-23 = "Bom, é que eu queria jogar#n\"Castelo do Rei Demônio Drácula\"……#ne aí fiquei sabendo da existência do#nDepartamento de Desenvolvimento de#nJogos……"
21090-24 = "Hmm…… ah, é?"
21090-25 = "(Boa! Aris, é isso aí!)"
21090-26 = "Mas aqui não é Departamento de#nJogos Retrô, é Departamento de#nDesenvolvimento de Jogos."
21090-27 = "Ou seja, você também participa da#ncriação dos jogos, certo? Do que você#ncuida?"
21090-28 = "Tank e atacante de atributo Luz……"
21090-29 = "Hã?"
21090-30 = "Quer dizer, ãh, p-p-p……#nprogramadoira!"
21090-31 = "……Hã? Programadora, você não#nquer dizer?"
21090-32 = "Ah, sim. É isso mesmo, exatamente.#nSem dúvida alguma, eu sou uma#nprogramadora impecável."
21090-33 = "(Essa foi por pouco……!?)"
21090-34 = "Programadora, né…… Ouvi dizer#nque é um papel bem difícil."
21090-35 = "Sim, i-isso mesmo. P-programar é#npuxado. Às vezes, de tanto trabalhar,#neu até perco a consciência."
21090-36 = "C-como é que é!?"
21090-37 = "Mas mesmo assim tá tudo bem!"
21090-38 = "Não, não tá nada bem…… descansa#ndireito, vai……"
21090-39 = "É só dormir e acordar na#nestalagem, ou pagar uma graninha na#ncatedral, que eu ressuscito junto com#nos companheiros!"
21090-40 = "C-claro que não funciona assim!?"
21090-41 = "Não funciona……? Mas isso é o#nbásico…… não me diga que você não#nconhece o \"Mito dos Heróis\" nem a#n\"Lenda da Lança Sagrada\"?"
21090-43 = "São \"jogos divinos\" de verdade."
21090-44 = "……"
21090-46 = "Acabou, tudo está……"
21090-48 = "……"
21090-49 = "……Obrigada, já entendi."
21090-50 = "Foi pouco tempo, Aris, mas, no#ngeral, consegui compreender quem você#né."
21090-52 = "(Já era de vez!)"
21090-53 = "(E agora, o que a gente faz……!?)"
21090-56 = "……!?"
21090-57 = "Tem umas coisinhas meio#nsuspeitas, mas……"
21090-58 = "que você gosta de jogo, e que#ngosta de aventurar por um mundo#nnovo e de histórias em que se#nrealiza algo junto com os#ncompanheiros, isso ficou mais do que#nclaro……"
21090-60 = "Uma garota assim ser membra do#nDepartamento de Desenvolvimento de#nJogos não tem nada de estranho."
21090-62 = "Hã……?"
21090-63 = "Quer dizer que……!?"
21090-65 = "Como o número exigido de membros#nfoi cumprido, reconheço de novo o#nDepartamento de Desenvolvimento de#nJogos como departamento oficial……#naprovo a sua continuidade como#ndepartamento."
21090-67 = "Ebaaa!"
21090-68 = "Que aliviooo!"
21090-69 = "E-então a gente também ganha#nverba, e pode continuar usando a sala#ndo departamento, né!?"
21090-70 = "Sim, claro."
21090-71 = "Até o \"fim deste semestre\"……#nviu."
21090-72 = "Eeebaa…… hã?"
21090-73 = "P-p-por quê!?"
21090-74 = "Como assim! A gente cumpriu o#nnúmero de membros!?"
21090-76 = "Ora, vocês não sabiam?"
21090-77 = "Agora não basta só cumprir o#nnúmero de membros: ao mesmo tempo,#n é preciso provar um resultado como#ndepartamento."
21090-78 = "Claro, como é um requisito que#nmudou de repente, há um prazo de#ntolerância, mas……"
21090-79 = "Esse prazo vai até o fim deste#nmês. Se até lá vocês não#napresentarem resultado, o#ndepartamento de vocês, tendo 4 ou#n400 membros, será dissolvido."
21090-80 = "Mentira, é impossível!"
21090-81 = "É possível, sim! Isso foi#nexplicado direitinho outro dia, na#nreunião geral dos presidentes de#ndepartamento."
21090-82 = "Só que a presidente de vocês, a#nYuzu, não estava lá."
21090-83 = "!?"
21090-84 = "Ou seja, a responsabilidade é de#nvocês."
21090-85 = "Kh…… sua desleal!"
21090-86 = "\"Megera\" até passa, mas o que é#nque seguir as regras à risca tem de#n\"desleal\"……"
21090-87 = "Sinceramente, a identidade da#nAris é suspeita, e, na verdade, eu#naté pensei em pedir a saída de vocês#nhoje mesmo, mas……"
21090-88 = "!?"
21090-89 = "……Identidade à parte, esse#nsentimento puro de gostar de jogo,#nesse eu achei verdadeiro."
21090-90 = "Concedi o prazo porque espero#nque vocês consigam, de fato, um#nresultado à altura desse sentimento."
21090-91 = "Momoi, você disse, não disse?#nQue no Prêmio Millennium ia#napresentar um resultado de cair o#nqueixo."
21090-92 = "I-isso eu disse, mas……"
21090-93 = "Agora que entrou membra nova,#nvocês vão conseguir fazer um jogo de#nverdade divertido, mais do que antes,#nné?"
21090-94 = "Então, vou ficar no aguardo. Até#nmais~."
21090-97 = "Ei, peraí! Vigarista! Quadrada!#nAaaaargh!"
21090-98 = "Ela foi embora……"
21090-100 = "Hmm……"
21090-101 = "No fim das contas, o#nDepartamento de Desenvolvimento de#nJogos ainda tá em risco de#ndissolução…… é isso, né."
21090-102 = "Mas isso, por qualquer ângulo, é#ngolpe! É conspiração!!"
21090-103 = "……Desculpem. Por minha causa, por#neu não ter ido à reunião dos#npresidentes……"
21090-104 = "N-não é culpa sua, Yuzu! Nesses#ncasos, era a mana que devia ir no#nseu lugar, não era?"
21090-105 = "……Não teve jeito."
21090-106 = "É que naquela hora tava rolando a#ncampanha de taxa de drop de item em#ndobro……"
21090-107 = "No fim das contas a culpa é sua,#nmana! Apaga esse jogo agora mesmo!"
21090-108 = "Uuh…… enfim, agora só resta uma#ncoisa a fazer."
21090-109 = "É isso."
21090-110 = "Criar um jogo incrível, capaz de#nganhar o prêmio no Prêmio#nMillennium."
21090-111 = "Quer dizer que, no fim, a gente#nprecisa mesmo da G.Bible! Ir de novo#npra aquelas Ruínas!? Nãão!!"
21090-112 = "……"
21090-116 = "……Eu preciso assumir a#nresponsabilidade."
21090-117 = "Hã, Yuzu?"
21090-118 = "Se for pra procurar a G.Bible e#nvoltar pras Ruínas…… eu também vou#njunto."
21090-119 = "H-hã!? Mentira!?"
21090-120 = "Yuzu, faz quase meio ano que#nvocê não põe o pé pra fora do#nprédio da colégio. Até as aulas você#nsó assiste pela internet……"
21090-121 = "……No início, a culpa foi minha……#npor isso. E esta sala do#ndepartamento…… já não é só minha."
21090-122 = "……Eu quero protegê-la, junto com#nvocês."
21090-123 = "Yuzu……"
21090-126 = "Tcharaaam, Yuzu entrou na party."
21090-127 = "……Sim, boa! Não tem outro jeito,#nbora!"
21090-128 = "Aris, pega a arma e o#nequipamento também!"
21090-131 = "Item selecionado: \"Espada de#nLuz: Supernova\" equipada."
21090-134 = "Beleza, bora! Dessa vez é pra#nvaler, pra colocar a mão na G.Bible!"
21090-135 = "……"
21090-136 = "……Sim!"
21090-137 = "Vamos todas juntas proteger a sala#ndo departamento!"
21090-139 = "Próximo Episódio;De Novo, Rumo às Ruínas."