[translation]
211-1 = "怪談の末路"
211-4 = "ふむ――いやはや、此度は誰が道に迷ったのかと思えば……よりによって[ruby=そち]其方[/ruby]か。"
211-5 = "嗚呼――ふむ、そういうことかの。"
211-6 = "眼前の惨事と比べれば――"
211-7 = "妾との邂逅など、怪談の一つ足り得ぬ――然程、不思議なことでもないのじゃろな。"
211-8 = "…………。"
211-9 = "ほう……どういう意味、とな？"
211-10 = "其方も知っておろう？#n[ruby=・   ・]其処[/ruby]で起きたことじゃ。"
211-11 = "騒々しくも愉快な祝祭の舞台――その陰で必要とされた「猫の手」。"
211-12 = "人々の悪意から生まれ、使役され――使い潰され……そうして、破棄された物語の切れ端。"
211-13 = "――其の名を、幻魎百物語「[ruby=みょうき]猫鬼[/ruby]クロカゲ」。"
211-14 = "今この瞬間も尚、人々が去った地を燃やしては、慟哭を上げる…… "
211-15 = "結末を迎えることのない[ruby=ひゃくものがたり]、怪談。[/ruby]"
211-17 = "此れらはみな――深き夜、燃ゆる灯の前で百の物語を紡ぐ遊戯より生まれしもの。"
211-18 = "……さあ、先生よ。こうして巡り会えたのも何かの縁。"
211-19 = "其方なら、この悲しき怪談を、相応しい結末に導くことができるじゃろうか……？"
211-20 = "……妾は期待しておるぞ、ふふ。"
