[translation]#[Texto Final , mas eventualmente pode haver alterações na formatação de texto. - Filipe 29/06.]
21135-3 = "Millennium · Corredor"
21135-4 = "Fufu, de fato, é uma comporta de um nível bem\ndiferente daquela liga de antes. Bom, e agora,\no que a gente faz?"
21135-5 = "Então, Akane, já que ficamos tão amigas, presas\njuntas assim, que tal eu começar uma divertida\naula sobre a teoria da relatividade?"
21135-8 = "……Aqui é a codinome Zero-Três! Fiquei presa na\nseção A-11! Codinome Zero-Um, por favor, responda!"
21135-12 = "O destinatário está offline."
21135-13 = "Asuna! Onde é que você se meteu, hein, francamente!\nPelo menos deixa o aparelho ligado, ora……!"
21135-15 = "(Bip-bip)"
21135-17 = "Conectando, Nova Mensagem……"
21135-18 = "Não sei onde a Asuna está…… mas fica tranquila, Akane."
21135-20 = "O Clube de Desenvolvimento de Jogos\njá está dentro do meu alcance de tiro."
21135-22 = "De: Codinome 02."
21135-24 = "Próximo episódio: Maids VS Meisters."