[translation]#[Texto Final , mas eventualmente pode haver alterações na formatação de texto. - Filipe 29/06.]
21140-1 = "Episódio 14: Maids VS Meisters."
21140-2 = "Millennium · Corredor"
21140-4 = "Última comporta destravada! Fufu, agora este andar\nexclusivo do Conselho está à minha mercê~ ♪ Bom,\nmais um pouquinho e a gente chega no depósito de\napreensões, onde está o \"Espelho\"……"
21140-5 = "Momoi, abaixa!"
21140-7 = "Hã?"
21140-8 = "(KABÃÃM!)"
21140-9 = "Uaaaah!"
21140-10 = "A-agora, por cima da minha cabeça, passou uma bala\ncom um poder de fogo monstruoso!? Abriu um\nburaco na parede!?"
21140-11 = "Munição antimaterial de 13,97 mm!? Ainda bem;\nse a mana fosse 5 cm mais alta, teria acertado\nem cheio bem na testa dela……"
21140-12 = "Iih, é verdade. Que bom que eu sou baixinh……\nnão é nada disso!"
21140-13 = "Quer dizer que essa região já entrou\nno raio de ação de um franco-atirador."
21140-14 = "……Da atiradora de elite do C&C, a Karin."
21140-15 = "Midori, abaixa! Vem mais!"
21140-16 = "(DOGÃÃÃM!)"
21140-17 = "Uaaah!?"
21140-19 = "Millennium · Terraço do 3º Prédio"
21140-20 = "……Entendo, não são nada ruins."
21140-21 = "Pequenas, ágeis e difíceis de acertar……"
21140-22 = "……Mas já captei a velocidade e o padrão. O vento\ntambém está fraco, e não há nada bloqueando a\nvisão…… talvez elas pensem que, \"de costas pra\nparede, estão a salvo\", sei lá."
21140-23 = "Que pena. Da próxima, acerto com 100%\nde certeza……"
21140-24 = "Será mesmo?"
21140-25 = "!?"
21140-26 = "O resultado do meu cálculo é um pouco diferente.\nA probabilidade de a sua bala acertar aquelas\ngarotas é de 0%."
21140-27 = "Quem é!?"
21140-30 = "(Vííín, tchác)"
21140-31 = "……Hã?"
21140-34 = "(Ratatatatá!)"
21140-36 = "Q-que negócio é esse!?"
21140-37 = "Deixa eu apresentar."
21140-38 = "A mais nova criação do Clube de Engenharia, uma\n\"cadeira\" de combate bípede capaz de operar em\nqualquer clima: o Trono do Trovão."
21140-40 = "Por que fazer uma cadeira andar…… e ainda\ntem uma catapulta nela!?"
21140-41 = "Que pena que você não consegue entender o charme\ndo \"Raio-zinho\" aqui……"
21140-42 = "……Entender eu não consigo, mas, no geral,\njá deu pra captar."
21140-43 = "Sempre me incomodou uma coisa. Como é que o\nClube de Desenvolvimento de Jogos conseguiu furar\na segurança do Conselho da Millennium e chegar até aqui."
21140-44 = "……Eram vocês que estavam ajudando\naquele \"Sensei\"."
21140-45 = "Então a informação da Himari também era uma\narmadilha pra nos confundir……?"
21140-46 = "Quer dizer que……"
21140-52 = "!!"
21140-55 = "Raio-zinho!"
21140-56 = "Entendo. Não perfurar com isso significa que é bem\nresistente…… embora tenha tropeçado e esteja\nsacudindo as perninhas."
21140-57 = "Uma cadeira que dispara, que interessante……"
21140-58 = "Mas, se você queria mesmo me deter, devia ter vindo\nde emboscada. Mesmo com essa \"cadeira\", vir me\nencarar de frente……"
21140-59 = "isso é um erro de cálculo, Utaha."
21140-60 = "Num terraço tão amplo, sem nada bloqueando, você\nachou mesmo que ia me vencer no confronto direto?"
21140-61 = "……"
21140-62 = "Você tem razão. Aqui não há nada\nque bloqueie……"
21140-65 = "Isso, nem mesmo o teto."
21140-67 = "?"
21140-69 = "(Fooon——)"
21140-70 = "……Esse som!?"
21140-71 = "(DOGÃÃM!)"
21140-73 = "Não pode ser, tiro indireto!? De onde, afinal!?"
21140-74 = "Da nossa Hibiki, lá do lado oposto\nda Torre Millennium."
21140-75 = "Pra você atingir a Hibiki num tiro, teria que\nperfurar várias paredes e tetos.#nDo mesmo jeito, você só conseguiria com tiro\nindireto. E então, comigo bem na sua frente,\nserá que você consegue fazer uma dessas duas coisas?"
21140-76 = "Kh……!?"
21140-77 = "Fufu, quer que eu repita?"
21140-79 = "Tudo conforme o cálculo."
21140-81 = "Millennium · Interior do Prédio"
21140-82 = "……O franco-atirador parou."
21140-83 = "É a Utaha e a Hibiki! Enquanto elas seguram\na Karin, bora correr!"
21140-85 = "(GRGRGRGRGR——!)"
21140-86 = "Heein! Q-que foi, terremoto?"
21140-87 = "Parece uma explosão…… não me diga!?"
21140-89 = "Millennium · Prédio"
21140-94 = "Kh…… a aula ainda…… não acabou……!"
21140-95 = "Iih, achei que ia morrer! Onde é que ela escondia\ntanta bomba assim……!"
21140-98 = "Ufa, eu não queria muito destruir as instalações\nda colégio, mas……"
21140-99 = "Yuuka, sinto muito, mas eu destruí as comportas na\nmarra. Qual a posição atual do Clube de\nDesenvolvimento de Jogos?"
21140-100 = "Até agora há pouco a Karin estava segurando elas,\nmas eu as perdi de vista."
21140-101 = "Mas…… dá pra saber pra onde elas estão indo."
21140-102 = "Pra banda do depósito de apreensões do Conselho,\nonde está o \"Espelho\", né. Então, vou pra lá\nagora mesmo de elevador."
21140-103 = "(Bip-bip——)"
21140-106 = "!?"
21140-107 = "O que houve? Yuuka? Yuuka??"
21140-108 = "Não pode ser, cortaram a energia……!?"
21140-109 = "Kh, chegar a esse ponto……!!"
21140-111 = "Millennium · Interior do Prédio"
21140-112 = "Aquela queda de energia agora foi a Utaha\ne a Hibiki, o plano delas deu certo, né?"
21140-113 = "Sim, deve ter sido. Ah, Sensei. O chão está\nescuro, então cuidado, viu."
21140-114 = "Se a gente passar daqui……"
21140-115 = "Sim, já deve ser o depósito de apreensões do\nConselho. Finalmente, com isto……!"
21140-116 = "Oh, até que enfim chegaram!"
21140-117 = "?"
21140-118 = "!?"
21140-120 = "Demoraram, hein~, eu esperei um bocado~."
21140-121 = "Bem-vindas, Clube de Desenvolvimento de Jogos!\nE, ãh…… veterano, né?"
21140-122 = "Ah, não, não, lembrei! É o \"Sensei\"!"
21140-123 = "Eu tava louca pra te encontrar~, viu?"
21140-124 = "A-a Asuna!? Por que você está aqui!?"
21140-125 = "Por que, né~…… sei lá, num impulso?"
21140-126 = "Pressentimento, intuição, essas coisas existem,\nné? \"Se eu esperar aqui, quem sabe eu encontre o\nSensei e vocês também\", foi o que pensei."
21140-127 = "Tive um pressentimento desses!"
21140-128 = "Não são palavras difíceis, mas não dá pra\nentender nadinha do que ela fala……"
21140-129 = "Bom, então vamos começar?"
21140-130 = "Ãh, só pra garantir, eu pergunto: começar o quê……?"
21140-131 = "A batalha! Eu adoro lutar!"
21140-132 = "Ah, é mesmo. Ainda não tinha me apresentado, né."
21140-133 = "C&C, codinome Zero-Um, Asuna!"
21140-134 = "Lá vou eu!"
21140-135 = "Eu sabiaaa!?"
21140-137 = "Próximo episódio: A Ameaça à Espreita."