[translation]
221130-1 = "Episode 13;The Final Voyage"
221130-10 = "Hello to all Chronos Channel viewers, good morning!#nThis is Mai Kazamaki of the Chronos News Department!"
221130-11 = "Even though the sun has yet to rise, I am currently here at Aohama Port, where the Odyssey fleet is anchored!"
221130-12 = "According to information confidentially obtained by the Chronos News Department, the Odyssey student council -- The Island -- is preparing to set sail alone!"
221130-13 = "As if to prove it, the flagship Olympus has removed its boarding gate and is raising its anchor!"
221130-14 = "It is unprecedented for the Odyssey fleet to set sail again less than a month after finishing its scheduled voyage!"
221130-15 = "It seems various speculations are flying around on social media regarding the reason for departure."
221130-16 = "Could this be related to the General Student Council President and Sensei from Schale who made a special visit to Odyssey the other day?"
221130-17 = "No official announcement has been made yet, but as soon as new information comes in --"
221130-21 = "Senior, we have breaking news."
221130-25 = "Ah, breaking news has just come in!"
221130-26 = "Moments ago, the Olympus notified the Port Authority of the reason for its departure."
221130-27 = "The purpose of the voyage is stated as \"to see off a friend,\" but --"
221130-31 = "Huh? See someone off, what does that mean?"
221130-32 = "Is there some student heading out to sea...?"
221130-34 = "Island Flagship Olympus - 1st Bridge"
221130-37 = "5 minutes until departure!"
221130-43 = "We will now shift to departure posture.#nSwitch the ship-wide broadcast from the boarding gate to the bridge."
221130-49 = "Boarding gate removal complete!"
221130-50 = "Alright. All hands, retrieve the mooring lines."
221130-51 = "All hands, retrieve the mooring lines!"
221130-56 = "Set sail!"
221130-66 = "As expected, just crossing the breakwater changes the color of the sea."
221130-71 = "...Meow."
221130-75 = "Sammy, can you see?"
221130-76 = "It is the sea. The sea of Kivotos you used to gaze at for so long."
221130-77 = "There are no other ships around today, so it is a little different from usual, but..."
221130-78 = "Consider this a parting gift."
221130-83 = "......Meow."
221130-84 = "What is it? Do you want to open the side window?"
221130-85 = "There is nothing out that way --"
221130-89 = "Huh? That ship is..."
221130-94 = "Captain, we have a communication request from the Golden Elysium of the Cruise Operations Department!"
221130-98 = "Permission granted."
221130-103 = "...Communication request permitted. Connecting to Channel 6."
221130-109 = "This is the Golden Elysium.#nMitsuki Sengoku, head of the Cruise Operations Department."
221130-110 = "We heard about it.#nAre you planning to offer a tribute to Sammy?"
221130-111 = "If so, we will accompany you."
221130-112 = "If this golden ship is not by your side, Sammy might feel lonely, right?"
221130-113 = "Therefore... although this is after the fact, we request permission from the Cruise Operations Department to set sail."
221130-114 = "Wait... didn't the Cruise Operations Department return to D.U. and aren't you guys still operating?"
221130-115 = "Is it okay to set sail without checking the guests' schedules?"
221130-116 = "Just for a little while.#nBesides, our customers will likely be delighted by the surprise."
221130-117 = "I bet this month's department budget of the Cruise Operations Department that not a single complaint will be filed!"
221130-122 = "...Permission granted."
221130-124 = "Captain, we also have a communication request from the Rhodes."
221130-125 = "...Switching to Channel 8."
221130-131 = "This is the Rhodes!#nSumika Komori, Trident communications duty officer!"
221130-132 = "Sorry for cutting in without permission.#nThere is something Trident simply has to tell you as well...!"
221130-133 = "That is terrible, Captain! Leaving us behind when seeing off Sammy!"
221130-134 = "We are also Odyssey! If both the white and black uniforms are not gathered together, Sammy will be lonely!"
221130-135 = "Please leave the safety of this voyage to Trident as well!"
221130-136 = "W-Wait! Everyone, please calm down~!#nI am the communications duty officer today, you know!?"
221130-137 = "Umm... Captain, please grant departure permission to the Trident patrol ships, including the Rhodes!"
221130-141 = "Alright, let's go together."
221130-142 = "...Requests for departure permission have been arriving one after another from multiple other clubs."
221130-143 = "This way, we can show Sammy the everyday scenery."
221130-144 = "Yeah, I am glad."
221130-148 = "Sammy, can you see?#nEveryone from the academy you love -- and who loves you."
221130-150 = "...Meow."
221130-151 = "Your favorite seat is over there, right? Let's go."
221130-158 = "...It is the sea breeze."
221130-159 = "As the morning sun rises and the temperature rises, you would gaze out at the academy with the wind right here."
221130-162 = "What do you think, Sammy? About our Odyssey."
221130-163 = ".............."
221130-167 = "(Reflected in those eyes are fellow sailors)"
221130-168 = "(In your usual spot, looking out at the familiar scenery, surrounded by friends --)"
221130-176 = "(-- with a fulfilled expression, you quietly closed your eyes)"
221130-181 = "(...And thus, Sammy's voyage came to an end)"
221130-183 = "Next Episode;The Presence of a Vacant Seat"
