[translation]
22135-3 = "Ooooi~!"
22135-12 = "Ahaha! Tudo tá explodindo!"
22135-13 = "Essa é a trigésima unidade..."
22135-17 = "...Não vejo o fim disso."
22135-18 = "Pois é, tem muito mais do que esperávamos."
22135-19 = "Bom, pelo menos o nosso objetivo de 'causar um estrondo e atrair a atenção' está sendo cumprido, mas..."
22135-23 = "...! Ali!"
22135-33 = "Ara."
22135-34 = "Uau! Demais~!"
22135-35 = "...A hora chegou."
22135-41 = "Estava esperando por vocês, senpais."
22135-44 = "C&C, codinome Zero Quatro. Asuma Toki, apresento-me."
22135-46 = "Próximo Episódio; Cidade-Fortaleza Eridu"