[translation]
22175-6 = "Agora que os movimentos do Avant-Garde-kun diminuíram, é a nossa chance! #n Vamos lá, Clube de Engenharia!"
22175-7 = "Sim! Entendido!"
22175-8 = "Certo. Vou instalar 'aquilo'."
22175-16 = "[ns] \"O, o que vai começar agora!?\""
22175-17 = "Além da função de rastreamento autônomo, está totalmente equipado com proteção contra água e poeira."
22175-18 = "Além disso, com certificação de segurança ultra-ultra-ultra-ultrassuper garantida, ostentando estabilidade até no zero absoluto ou em temperaturas acima de 3 mil graus...!"
22175-19 = "A arma mais forte que criamos gastando metade do nosso orçamento anual――"
22175-21 = "O Alto-falante Remoto de Última Geração!"
22175-26 = "......"
22175-30 = "(Confusa)"
22175-31 = "[ns] \"............Por que um alto-falante precisaria de tantas funções?\""
22175-32 = "Essa é uma pergunta boba, Sensei."
22175-33 = "Antes de tudo, a regra de ouro das funções é! Quando você pode adicioná-las――"
22175-34 = "......É adicioná-las o máximo possível."
22175-35 = "É exatamente isso."
22175-36 = "Muito bem――"
22175-37 = "Fogo!"
22175-44 = "(......Gulp)"
22175-45 = "......E, eu estou me coçando de vontade de dizer aquela frase...!"
22175-46 = "Mana, tenta se segurar um pouco!"
22175-47 = "......N, não tem necessidade nenhuma de dizer."
22175-55 = "......Como esperado, os alto-falantes que construímos têm uma ótima acústica!"
22175-56 = "[s] \"Era um alto-falante nesse sentido!?\""
22175-57 = "Bem, bem, vamos deixar os detalhes de lado! #n De qualquer forma, com isso...!"
22175-58 = "......Sim. Finalmente conseguimos derrotar."
22175-60 = "Ebaaa! Conseguimos derrotar!"
22175-61 = "[s1] \"Acabou antes que eu entendesse o que estava acontecendo......\"\n[s2] \"Nossa... o Avant-Garde-kun foi um oponente formidável.\""
22175-62 = "......G, graças ao esforço de todos, nós c, conseguimos derrotar."
22175-63 = "......G, graças ao esforço de todos, nós c, conseguimos derrotar."
22175-64 = "É verdade. Bem, como posso dizer..."
22175-65 = "É como se tivéssemos derrotado um Chefe de Raid!!"
22175-67 = "Bom trabalho a todos. Mas o show principal começa agora."
22175-68 = "Precisamos nos mover enquanto ainda conseguimos manter a rede através do 'Espelho'...... #n Por enquanto, vou guiando vocês."
22175-69 = "Ah, falando nisso..."
22175-70 = "Bem..."
22175-71 = "......Desculpem, parece que nós ficamos por aqui."
22175-76 = "[ns] \"D, dá para acreditar!?\""
22175-77 = "......Aquele momento, até instalarmos o alto-falante, estava tudo bem."
22175-78 = "Para alguém sedentário como eu... e, eu fiz movimentos excessivamente imprudentes..."
22175-79 = "............Agora, não consigo mover nem um dedo."
22175-80 = "Como podem ver. Sinto muito por não conseguir acompanhar vocês até o fim, mas nos despedimos aqui."
22175-82 = "Utaha-senpai......"
22175-86 = "Não, não! Está tudo bem! Obrigada por nos ajudar! #n Aquele alto-falante de agora há pouco! Foi super legal!"
22175-87 = "Nós vamos dar um jeito daqui para frente!"
22175-92 = "[ns] \"Não se preocupem. Vamos trazer a Aris de volta custe o que custar.\""
22175-94 = "......Entendi. Se vocês dizem com tanta convicção."
22175-95 = "Momoi."
22175-96 = "Hm?"
22175-97 = "Tome isso. #n Deve ser útil em uma emergência."
22175-98 = "Isso é......"
22175-99 = "Sim, entendi."
22175-100 = "Então, pessoal...... conto com vocês daqui para frente!"
22175-101 = "Boa sorte a todos."
22175-103 = "Próximo Episódio; O Muro que Ainda Não Pode ser Transposto"