[translation]#[Texto Final , mas eventualmente pode haver alterações na formatação de texto. - Filipe 29/06.]
22200-1 = "Episódio 20: Como Gamer, Como Amiga."
22200-2 = "Por ora, a gente fugiu pra um prédio aqui perto, mas……"
22200-9 = "[ns] \"Todo mundo tá bem? Algum ferimento!?\""
22200-10 = "……A gente tá bem, mas."
22200-11 = "A veterana Neru……"
22200-13 = "A consciência da presidente ainda não…… voltou."
22200-14 = "Pelo visto, os ferimentos são mais graves do que pareciam."
22200-15 = "No fim, com o impacto da queda, ela parece ter se machucado feio…… e agora, mestre……"
22200-16 = "[s] \"Neru……\""
22200-17 = "……É a pior das situações, né."
22200-18 = "Na luta contra o Avant-Garde, o Clube de Engenharia saiu de cena……"
22200-19 = "Até o ponto em que nós, da Veritas, conectamos na rede, foi bom, mas……#nno fim, o suporte à distância tem limite."
22200-20 = "Quanto ao Clube de Desenvolvimento de Jogos…… sinceramente, está fora de combate, né."
22200-21 = "Uuh! I-isso é verdade, mas!"
22200-22 = "Não dá pra negar……"
22200-24 = "Na prática, o único que dá pra chamar de força de combate, o C&C……"
22200-25 = "[s] \"……Não é só a Neru, todo mundo já chegou ao limite.\""
22200-26 = "……Haah, eu não queria muito dizer isto, mas."
22200-27 = "Pode ser que seja…… até aqui…… já não tem mais o que fazer……"
22200-32 = "No fim, a gente……"
22200-33 = "……só com a gente, será que falta força?"
22200-34 = "[s] \"Momoi……\""
22200-35 = "Só com a gente…… será que não dá pra salvar a Aris?"
22200-36 = "A Aris, e a gente……#nninguém fez nada de errado……"
22200-37 = "E, mesmo assim, por quê…… por que isso……"
22200-39 = "Midori……"
22200-40 = "Até aqui…… todo mundo ajudou……"
22200-41 = "O esforço de todo mundo se somou…… e, até que enfim, a gente conseguiu chegar até aqui……!"
22200-42 = "Será que não tem outro jeito senão desistir agora…………?"
22200-43 = "……Um…… um final ruim desses……#nde jeito nenhum…… de jeito nenhum……!"
22200-47 = "Isso eu não aceito de jeito nenhum!!"
22200-48 = "Uaaah!?"
22200-49 = "Ah! Presidente!"
22200-50 = "Você acordou!?"
22200-51 = "[s] \"Neru, o corpo tá bem?\""
22200-53 = "Hãã……?"
22200-58 = "Presidente! Não se force!#nOs ferimentos são bem fundos!"
22200-59 = "Para de fazer escândalo, pi-pi-pi……tá tudo bem."
22200-60 = "Não, pela aparência não tá nada bem……"
22200-61 = "Mais que isso…… o que aconteceu?#nPor que todo mundo tá com cara de velório?"
22200-62 = "[s] \"É que……\""
22200-64 = "Haah…… ou seja, pela situação, vocês acham que já era?"
22200-65 = "……"
22200-66 = "Hã? Tá de brincadeira."
22200-67 = "Hã……?"
22200-68 = "Ei, baixinhas."
22200-73 = "Os sentimentos de vocês não passavam disso, no fim?"
22200-74 = "N-no fim…… que história é essa! Não fala desse jeito!"
22200-75 = "Bom, de fato os braços não parecem que vão mexer,"
22200-76 = "e a perna também tá com o ligamento rompido, pelo visto……"
22200-77 = "Sério, se eu der um passo que seja, sinto que vou vomitar, mas……"
22200-78 = "Isso aí já se chama estar em frangalhos!?"
22200-79 = "Mas, sabe…… desistir por causa de só isso……"
22200-80 = "A determinação de vocês é tão frágil assim?"
22200-81 = "M-mas, veterana Neru, o seu corpo já……!"
22200-82 = "Há! Para de se preocupar com os outros, não é a sua cara."
22200-83 = "Isso aqui eu aguento na raça."
22200-84 = "Vocês vieram até aqui pra salvar a Aris, não foi?"
22200-85 = "Então vão até o fim sem desistir, e empurrem isso até o final. Entenderam?"
22200-86 = "A-a gente também não quer desistir!"
22200-87 = "M-mas, contra um personagem cheat daqueles…… como é que a gente vence……?"
22200-88 = "Pois é……"
22200-89 = "Talvez…… exista um jeito…… quem sabe."
22200-93 = "Heein!?"
22200-94 = "[s] \"Yuzu, s-sério!?\""
22200-95 = "Sim, naquela hora, por um instante de verdade…… foi num átimo, mas."
22200-97 = "(Agora……!)"
22200-99 = "Eu vi o ataque da veterana Neru acertar."
22200-100 = "[s] \"Naquele tempinho tão curto……?\""
22200-101 = "Essa é a Yuzu! UZQueen! A prodígio da visão dinâmica!"
22200-102 = "Mas por que será que funcionou?#nSe é como a presidente disse, contra o \"armamento\" da Toki nada deveria funcionar."
22200-103 = "I-isso eu também não sei direito……"
22200-105 = "……Isto é só uma hipótese."
22200-106 = "……Uma hipótese mesmo, no fim só uma suposição."
22200-107 = "E se o \"armamento\" da Toki tiver uma brecha?"
22200-108 = "……Brecha?"
22200-109 = "A presidente disse, né. Que o \"armamento\", recebendo suporte da rede de Eridu,#npor meio do processamento, consegue abater e desviar qualquer ataque."
22200-110 = "[s] \"Sim. E na prática foi mais ou menos isso.\""
22200-111 = "É verdade. Pelo que eu vi com os meus olhos, não é mentira.#nSó que……"
22200-112 = "É que, até agora, eu não vi ela fazer essas duas coisas ao mesmo tempo."
22200-113 = "……!#nEntendi, então é isso."
22200-114 = "Hã? Hm? Hã……?"
22200-115 = "Ãh…… como assim?"
22200-117 = "A capacidade do \"armamento\" é, de fato, de chamar de cheat."
22200-118 = "Mas, pode ser que só pareça assim, e que#no \"armamento\" também tenha um limite…… coisas que ele não consegue fazer."
22200-119 = "Quando ela caiu do prédio, a presidente disse que até aquela queda estava nos cálculos, né."
22200-120 = "Ou seja, naquela hora, ela usou a capacidade de processamento na queda, e por isso……"
22200-121 = "[s] \"Não conseguiu bloquear o ataque da Neru…… e abriu uma brecha……?\""
22200-122 = "Ah! É isso!"
22200-123 = "E-então, se a gente conseguir criar uma brecha como a daquela hora……!"
22200-124 = "talvez dê pra derrotar……?"
22200-125 = "Mas como? Não dá pra acreditar que a adversária não entenda esse ponto fraco."
22200-126 = "Não tem como o método de jogar do terraço funcionar duas vezes……"
22200-127 = "A-a veterana Neru, à curta distância…… ganha…… foi isso que você disse, né?"
22200-128 = "……Ah, ganho.#nMas, antes disso, vai ser preciso dar um jeito naquela habilidade de cheat."
22200-129 = "E-então eu tenho uma ideia."
22200-130 = "Contra um cheat……"
22200-131 = "dentro das regras que foram dadas, uma coisa que a gente pode usar…… um \"golpe-trava\"."
22200-141 = "Veterana Neru……"
22200-147 = "……Não sei o que vocês estão tramando, mas é inútil."
22200-148 = "Toki."
22200-149 = "……Sim, senhora."
22200-150 = "Ah, é assim que tem que ser……"
22200-151 = "Dessa vez, vamos acertar as contas de uma vez, nós duas!"
22200-153 = "Próximo episódio: O Que Aquele Nome Revela."