[translation]#[Texto Final , mas eventualmente pode haver alterações na formatação de texto. - Filipe 29/06.]
22230-1 = "Episódio 23: Pavana para a Princesa (2)"
22230-2 = "……Falha na garantia de recursos. Sistema em desligamento."
22230-3 = "Pessoal, tão todas bem!?"
22230-4 = "Yuuka……!"
22230-5 = "Veterana Noa!"
22230-6 = "C-como é que vocês chegaram aqui……?"
22230-7 = "Que a situação não é nada normal, isso ficou bem claro, Sensei!"
22230-8 = "No início, a intenção era só passar a localização da cidade e nos retirar, mas……"
22230-9 = "Fufu, a Yuuka disse que, no fim, só isso não bastava……#nque a gente tinha que dar um jeito até o fim. Foi o que ela falou, viu?"
22230-10 = "[s] \"Essa é a Yuuka! O timing foi perfeito!\""
22230-11 = "Isso é o mínimo."
22230-12 = "Mais que isso, presidente!!"
22230-14 = "!!"
22230-15 = "Desviar o orçamento da Seminar pra construir uma cidade dessas……#ndepois tem sermão, viu! Pode se preparar!"
22230-16 = "……Yuuka."
22230-20 = "Erro no processo de garantia de recursos.#nSituação de emergência: energia Divi:Sion, reunir na torre central de Eridu para proteger o executor do protocolo………"
22230-24 = "……Intrusos?"
22230-25 = "Isso é impossível—— as forças remanescentes dentro da cidade são zero."
22230-26 = "Erro lógico detectado. Para verificação, exibindo a tela."
22230-35 = "Ah, aquilo não pode ser……!"
22230-39 = "[ns] \"………O Avant-Garde e o Clube de Engenharia!"
22230-40 = "Captamos a presença suspeita de antemão! O Clube de Engenharia ressurgiu em grande estilo~!"
22230-41 = "Tem um monte de máquina de design esquisito pra todo lado, né."
22230-42 = "Provavelmente isto é…… a ameaça que transbordou das Ruínas, de que a presidente falava."
22230-43 = "Fufu…… então nós também não podemos ficar pra trás."
22230-44 = "Se a adversária é um monstro que rastejou pra fora das Ruínas……"
22230-45 = "deste lado estão as engenheiras que miram o espaço."
22230-52 = "A gente acaba de ganhar uma aliada armada com o senso de design supervisionado pela Maki."
22230-53 = "Sim! Inimigo do inimigo é aliado! E inimigo que a gente modificou também é aliado!"
22230-54 = "Sim…… em especial, porque eu coloquei nela uma arma de fogo que dá pra usar até no futuro encouraçado espacial."
22230-55 = "Por mais que seja um monstro das Ruínas, não é páreo pro \"Avant-Garde Mk.2\"."
22230-56 = "Então, vamos lá! Investidaaa!"
22230-57 = "Sim! Bora fazer uma faxina nos zé-ninguém das Ruínas!"
22230-58 = "Aaa~!"
22230-66 = "Modificar o Avant-Garde…… pra um encouraçado espacial……"
22230-67 = "Hã? Que é que você tá falando?"
22230-68 = "[s] \"Se é encouraçado espacial, não tem jeito! Porque é o sonho de todo mundo!\""
22230-69 = "Ãh…… eu não tô entendendo muito bem o que o Sensei está dizendo……"
22230-70 = "Compreensão impossível. Julgamento da situação impossível."
22230-71 = "Correção e reexecução da ordem. Os seguidores devem evitar combate com a força imprevista e se reunir na torre central de Eridu………"
22230-72 = "Sinto muito, mas essas garotas não vão conseguir chegar até aqui.#nA entrada da torre está bloqueada pela Eimi e pelas membros do C&C."
22230-75 = "[ns] \"Hã? Himari!? Por que você tá aqui!?\""
22230-76 = "Ufufu. Digamos que…… umas coisas aconteceram, vai~?"
22230-77 = "Himari…… você não tinha fugido……"
22230-78 = "Fugido…… que coisa mais triste de se dizer."
22230-79 = "É que eu já tinha, até certo ponto, uma noção da situação que estava por vir."
22230-80 = "Depois de escapar da instalação de isolamento, vim correndo pra cá."
22230-81 = "Conhecendo a Rio…… eu já previa que ela ia causar mais um incidente."
22230-82 = "E aí?#nFufu—— acertei?"
22230-83 = "…………"
22230-84 = "Bom, isto é a ＜Key＞……#na IA-gatilho para acionar o \"OOPArt\" do sacerdote sem nome."
22230-85 = "Se a gente deixar assim, com certeza a personalidade da Aris vai ser substituída pela ＜Key＞……#ne ela vai despertar como a \"Princesa dos Deuses Sem Nome\", do jeito que o sacerdote sem nome deseja."
22230-86 = "E-então……!"
22230-87 = "!!#nVeterana Himari…… isso quer dizer……"
22230-88 = "A Aris, do jeito que tá……"
22230-89 = "Claro que também há um jeito de evitar isso."
22230-90 = "[s] \"……Afinal, o que é que a gente precisa fazer?\""
22230-91 = "A situação é uma corrida contra o tempo…… porque o sacerdote sem nome já entrou em movimento."
22230-108 = "Por isso, antes que o sacerdote sem nome chegue, primeiro, com as nossas próprias mãos, a Aris——"
22230-109 = "a gente precisa despertar a Aris, que ficou isolada nas profundezas da base de dados pela ativação da ＜Key＞."
22230-111 = "Fazendo isso, deve ser possível deter esta situação."
22230-115 = "Uma coisa dessas…… é mesmo possível?"
22230-116 = "Quer dizer que a gente consegue trazer a Aris de volta!?"
22230-117 = "Conseguem, claro.#nRio, vocês têm equipamento de imersão, não têm?"
22230-118 = "Sim, temos.#n……Mas uma coisa dessas, na prática, não tem como……!"
22230-119 = "[s] \"Ué?\""
22230-120 = "É perigoso demais. Mesmo que consigam invadir o mundo mental da Aris,#nse vacilarem, podem nunca mais conseguir voltar."
22230-121 = "Pra começar, uma coisa dessas, quem é que——"
22230-122 = "No estado atual, quem pode trazer a Aris de volta é só o Clube de Desenvolvimento de Jogos e o Sensei."
22230-123 = "Há riscos envolvidos…… mas, fora isso, não há outro jeito."
22230-125 = "……A gente faz."
22230-126 = "Se for pra……"
22230-127 = "trazer a Aris de volta."
22230-128 = "Tá vendo?"
22230-129 = "…………"
22230-130 = "Então, eu vou agora analisar o psiquismo da Aris e abrir uma fresta."
22230-131 = "Vocês entrem no mundo mental da Aris e tragam ela de volta."
22230-136 = "[ns] \"……Entendido. Vamos!\""
22230-138 = "Sim, então vamos começar."
22230-143 = "……Preparação concluída."
22230-144 = "Então, pessoal, conto com vocês."
22230-148 = "Próximo episódio: Aquilo que Quero Ser."