[translation]
2300003-1 = "Ingestão de açúcar"
2300003-2 = "Café Mille-Feuille"
2300003-3 = "Fiquei surpresa... não achei que você realmente viria."
2300003-4 = "O trabalho está bem? Parece que você tem estado muito ocupado ultimamente..."
2300003-5 = "Sinto muito, foi tudo por causa do meu convite repentino..."
2300003-6 = "O trabalho está realmente bem?"
2300003-7 = "[s1] \"Está tudo bem, só uma pequena pausa.\"\n[s2] \"O meu 'eu' do futuro vai dar um jeito.\""
2300003-8 = "Ahahaha..."
2300003-9 = "Ahahaha..."
2300003-10 = "Se é assim, fico feliz que você tenha vindo, Sensei."
2300003-11 = "Eu estava pensando em comer alguns doces e acabei me lembrando de você."
2300003-12 = "Além disso, você parecia tão ocupado o tempo todo, que pensei que talvez não estivesse conseguindo descansar direito..."
2300003-13 = "Ehehe..."
2300003-14 = "[s] \"Obrigado. Aliás, o que vamos pedir?\""
2300003-15 = "Ah, não se preocupe."
2300003-16 = "Eu já fiz o pedido."
2300003-17 = "Não posso desperdiçar o seu tempo!"
2300003-18 = "Acho que já deve estar chegando..."
2300003-19 = "Desculpem a demora. Aqui estão o café mocha, o latte de menta com chocolate, o tiramisu e o bolo de chocolate que pediram."
2300003-20 = "Ah, chegou na hora certa. Muito obrigada."
2300003-23 = "O que achou, Sensei?"
2300003-24 = "Pensei em pedir coisas à base de chocolate para ajudar no seu trabalho..."
2300003-25 = "[s] \"Chocolate para o trabalho?\""
2300003-26 = "É que eu ouvi dizer que açúcar ajuda a recuperar da fadiga..."
2300003-27 = "Ah, desculpe perguntar só agora, mas... você gosta de chocolate?"
2300003-28 = "[s3] \"Sim, eu adoro.\"\n[s4] \"Meu corpo é feito de açúcar, começando pelo chocolate.\""
2300003-29 = "Ah... que bom, fico aliviada."
2300003-30 = "Ah... que bom, fico aliviada."
2300003-31 = "Fiquei preocupada pensando no que faria se você não gostasse."
2300003-32 = "Afinal, o cérebro precisa de açúcar para funcionar!"
2300003-33 = "Eu costumo comer bastante quando estou estudando para as provas, ehehe."
2300003-34 = "Então!"
2300003-35 = "Vamos comer!"
2300003-37 = "(Depois disso, esqueci por um momento da pilha de documentos no escritório e me dediquei à ingestão de açúcar junto com a Airi.)"
