[translation]
2300003-1 = "糖分摂取"
2300003-2 = "カフェ・ミルフィーユ"
2300003-3 = "びっくりしました……本当に来てくれるだなんて。"
2300003-4 = "お仕事、大丈夫だったんですか？最近もずっとお忙しいみたいですし……。"
2300003-5 = "すみません、私が思い付きでご連絡してしまったせいで……。"
2300003-6 = "お仕事の方、本当に大丈夫ですか？"
2300003-7 = "[s1] \"大丈夫、ちょっとだけ休憩。\"\n[s2] \"未来の私が頑張ってくれるから。\""
2300003-8 = "あははは……。"
2300003-9 = "あははは……。"
2300003-10 = "そういうことでしたら、私は先生が来てくださって嬉しいです。"
2300003-11 = "スイーツを食べに行きたいなと考えていたら、先生のことを思い出しまして。"
2300003-12 = "それに、ずっと忙しそうでしたし、もしかしたらちゃんと休憩も取れてないんじゃないかな……って思ってたので。"
2300003-13 = "えへへ……。"
2300003-14 = "[s] \"ありがとね。ところで注文、どうする？\""
2300003-15 = "あ、大丈夫です。"
2300003-16 = "注文はもうしてありますから。"
2300003-17 = "先生の時間を無駄にするわけにはいきませんので！"
2300003-18 = "そろそろ来ると思うんですが……。"
2300003-19 = "お待たせいたしました。ご注文のカフェモカ、チョコミントラテ、それからティラミスと生チョコケーキです。"
2300003-20 = "あっ、ちょうど来ましたね。ありがとうございます。"
2300003-23 = "どうですか、先生！"
2300003-24 = "先生のお仕事のためにも、チョコをメインに注文してみたんですが……。"
2300003-25 = "[s] \"仕事のためにチョコ？\""
2300003-26 = "その、糖分は疲労回復にも良いって聞いたことがあったので……。"
2300003-27 = "あの、今さらですが……チョコレートは好き、ですか？"
2300003-28 = "[s3] \"うん、大好きだよ。\"\n[s4] \"私の体はチョコを始めとした糖分でできてるから。\""
2300003-29 = "あ……で、でしたら良かったです。"
2300003-30 = "あ……で、でしたら良かったです。"
2300003-31 = "今になって、苦手だったらどうしようって思ってしまいました。"
2300003-32 = "脳を働かせるには、糖分が必要ですからね！"
2300003-33 = "試験勉強をする時なんかにもよく食べてます、えへへ。"
2300003-34 = "では！"
2300003-35 = "いただきま～す！"
2300003-37 = "（その後、執務室に積まれた書類のことは一旦忘れて、アイリと一緒に糖分摂取に勤しんだ）"
