[translation]
2300108-1 = "A chefe do Clube de Merenda quer dar o seu melhor!"
2300108-2 = "（Hoje é o dia de ajudar Fuuka no refeitório de Gehenna）"
2300108-3 = "（Sendo assim, quando cheguei ao refeitório estudantil...）"
2300108-4 = "Hoje eu recebi reclamações dos alunos de novo!"
2300108-5 = "[s] \"F-Fuuka?\""
2300108-7 = "（Isso é... mirin?）"
2300108-8 = "[s] \"Fuuka, por acaso você provou isso?\""
2300108-9 = "Sim! Eu provei só um pouquinho! Não tinha como evitar! É para preparar a comida, afinal...!"
2300108-10 = "[s] \"Mirin, se não me engano, tem álcool...\""
2300108-11 = "O que importa agora não é o mirin, Sensei!"
2300108-12 = "Eu sempre me esforço e dou o meu melhor porque quero que todos comam uma comida deliciosa...!"
2300108-13 = "[s] \"E-eu sei. Eu sei muito bem o quanto você se esforça, Fuuka.\""
2300108-14 = "Claro, eu entendo que a qualidade da comida pode cair quando preciso preparar tudo de uma vez, e entendo a insatisfação deles."
2300108-15 = "Além disso, o fato de eles não reconhecerem o meu esforço também..."
2300108-16 = "Dói o coração, mas ao mesmo tempo penso que não tem jeito, então não é como se eu não entendesse o lado deles."
2300108-17 = "MA! S! A! S! S! I! M!"
2300108-18 = "Como eles podem confundir mostarda com karashi por conta própria, só porque o molho é amarelo, e achar que está tudo bem?"
2300108-19 = "E depois reclamar comigo que a comida está picante, o que você quer que eu faça!?"
2300108-20 = "Se estão tão insatisfeitos, por que não fazem a própria comida!?"
2300108-21 = "Você está querendo dizer que o trabalho duro da chefe do Clube de Merenda não conta como trabalho duro!!? Hein!?"
2300108-22 = "[s] \"M-meus pêsames pelo seu trabalho.\""
2300108-23 = "Hm? ...Espere um pouco."
2300108-24 = "...E se, em vez disso, eu trocasse toda a mostarda que vai na comida por karashi de uma vez? Assim, talvez eu não recebesse mais reclamações?"
2300108-25 = "Será que uma pequena mudança de perspectiva pode trazer sinais de mudança para o refeitório de Gehenna...?"
2300108-26 = "[s] \"N-não desista!\""
2300108-27 = "É brincadeira, eu não faria isso. Como Clube de Merenda, ser negligente com a comida é um pecado."
2300108-28 = "[s] \"Como esperado da Fuuka! Tão sincera com a culinária!\""
2300108-29 = "Ah, mas o trabalho no Clube de Merenda não é só sofrimento."
2300108-30 = "Fico extremamente feliz quando dizem que a comida que fiz está gostosa, sinto que vale a pena, e acima de tudo..."
2300108-31 = "Só de você vir aqui e me ajudar, Sensei, um cantinho do meu peito fica quentinho."
2300108-32 = "Hehe, hehehe..."
2300108-35 = "[s] \"Fuuka?\""
2300108-36 = "……"
2300108-37 = "[s] \"F-Fuuka-tan...?\""
2300108-38 = "Zzz..."
2300108-39 = "（Nesse momento, notei o rótulo no verso do mirin）"
2300108-40 = "（Teor alcoólico: 0,00003%）"
2300108-42 = "（Depois disso, decidi que nunca mais deixaria álcool perto da Fuuka）"
