[translation]
2501-1 = "ゲームの道はマナーから（１）"
2501-2 = "ミレニアム・ゲーム開発部"
2501-7 = "んっ、くっ……んぅっ……！"
2501-8 = "何してるの、お姉ちゃん？"
2501-9 = "ちょっと待って！今大事なとこだから！"
2501-10 = "あと一発、あと一発当たれば、勝て、るっ……！"
2501-11 = "あ、『スチューデントファイター2』？最近よくやってるね。"
2501-12 = "そう、この間オンライン機能が、追加され……てっ！ゲーセンのユーザーとも、オンライン対戦が、できるように……！"
2501-13 = "今までは割とっ、余裕だったん、だけど……！"
2501-14 = "久しぶりに強い人、がっ……！"
2501-20 = "追い詰めた！ガードされても掴み技で――"
2501-22 = "なっ、ここで回避！？からのアッパーカット！？"
2501-23 = "ちょっ、立て続けに連続コンボって……そこで必殺技ぁ！？"
2501-29 = "<SYSTEM> 「Peach_Fighter」選手の負け！"
2501-30 = "うわぁんっ！最後の判断ミスで逆転されたぁっ！？"
2501-31 = "惜しかったね、本当にもう少しだったのに……。"
2501-32 = "うん……まあ仕方ない、勝負は勝負。"
2501-33 = "良い試合だったし、相手にメッセでも送っとこ。"
2501-35 = "＜Peach_Figther：Sukeban312さん対戦ありがとう！良い勝負だったね、今度また機会があったらやろう！＞"
2501-36 = "＜Sukeban312：出直せ下手くそ＞"
2501-37 = "ちょっ、はぁ！？何それ！？"
2501-39 = "＜Peach_Figther：ねえその言い方は無いでしょ！？子供じゃないんだし！＞"
2501-40 = "＜Sukeban312：子供はそっちでしょ。いや、操作も反応も遅かったし、子供っていうよりもしかしておばあちゃん？＞"
2501-41 = "お、おばあちゃん……！？"
2501-43 = "＜Peach_Figther：そんなこと言って、そっちだってギリギリだったじゃん！＞"
2501-44 = "＜Sukeban312：顔真っ赤。ほら、涙拭けよ。にしても負け犬ほどよく吠えるってほんとだな＞"
2501-45 = "こんのっ……そっちどこ住み！？住所教えて！こうなったら真っ正面から――"
2501-46 = "<SYSTEM> 対戦相手があなたのことをブロックしました。"
2501-47 = "……っ！"
2501-49 = "うわー、これはひどい……。"
2501-50 = "……なっ、"
2501-52 = "何てマナーのなってないやつ！！！"
2501-54 = "というわけで……"
2501-55 = "今からリアルファイトに行くよ！"
2501-57 = "えぇ……というか、わ、わたしも……？"
2501-58 = "……私も、ですか？"
2501-59 = "もっちろん！まあリアルファイトっていうかリア凸っていうか、別に銃は使わないし、対面で試合するだけだけど……こういう時に一番大事なのは、何よりも勢い！"
2501-60 = "どうせ相手はゲームしてばっかりのオタクに違いないから、みんなで行けば怯えてすぐに謝ってくるはず！"
2501-61 = "前半部分については、こっちも同じだと思うけど……。"
2501-62 = "ねえお姉ちゃん、たかが一回ゲームでからかわれただけで、ここまでする必要ある……？"
2501-63 = "「たかが」じゃないよ！これはゲーム開発部としてのプライドに関わる大事件！"
2501-64 = "私がせっかく優しい言葉をかけたのにあんな言い方をするわ、私のことを「おばあちゃん」呼ばわりするわ……！"
2501-65 = "絶対に……"
2501-66 = "絶対に許せない！"
2501-67 = "後者の方が本音っぽいけど……。"
2501-68 = "そもそも、ああいうマナーのなってないゲーマーを放置するわけにはいかない。"
2501-69 = "あんなユーザーがいると、この界隈に入ったばっかりの人とかが不快な思いをして、どんどん廃れていっちゃうでしょ？"
2501-70 = "良い環境作りのためにも、ああいうマナーの悪いユーザーにはしっかりお仕置きしないと！"
2501-71 = "それはその通りだと思います。アリスも昨日始めたオンラインRPGで、レベルMAXのユーザ[ruby=プレイヤーキル]ーにPKされ[/ruby]た時にはもうプレイをやめようかと思いました……。"
2501-72 = "もちろん、一日でそのレベルまで追いついて、すぐに仕返しをしましたが！"
2501-73 = "一日にレベルをMAXに……すごい執念だね……。"
2501-74 = "それにお姉ちゃんだって時々、ゲームで勝って相手を挑発したりするでしょ？"
2501-75 = "この間だって、私と『フルゼリー』やってた時に「これなら足で操作しても勝てる」って言ってたし……。"
2501-76 = "うっ、それは……だってその……。"
2501-77 = "み、身内はセーフ！会ったこともない人を相手に暴言を吐くのはダメ！"
2501-78 = "と、とにかく！相手の対戦記録を検索してみたら、10分前に近所のゲーセンに接続した記録が見つかったから……"
2501-79 = "今すぐそのゲーセンに行けば、あのユーザーが見つかるはず。ちゃんとあのことについて、謝ってもらわないと！"
2501-80 = "うーん、まあ私もちょうどゲーセンに用事あったし……一緒に行くのは全然良いけど。"
2501-81 = "邪悪な魔王を倒しに行くんですね、いざ四人レイドへ！"
2501-82 = "えっと、わたしはゲーセンに用事もないし、喧嘩もしたくないんだけど……。"
2501-83 = "行かなくてもいい、かな……？"
2501-84 = "ダメ！こういう多人数での攻略は、一人一人の役割分担が大事だから！"
2501-85 = "討伐戦と同じ！四人で四方を囲まないと、逃げられちゃうでしょ！"
2501-86 = "で、でも……"
2501-87 = "……あ、そういえばユズが楽しみにしていたあの新しい据え置き型ゲーム機、確かゲーセンでお試し会をやってた気が……？"
2501-88 = "え、あの新型ゲームコンソール……！？"
2501-89 = "ユズ一人じゃ、絶対行かないでしょ？せっかくの機会だし、一緒に見に行こ？ね？"
2501-90 = "う、うぅ……分かった。"
2501-91 = "わ、わたしは、介入しないで、遠くから見守ってるから……。"
2501-92 = "うん、それでも十分！"
2501-93 = "パンパカパーン！四人パーティーが結成されました！"
2501-96 = "よし！じゃあ今から、あのゲーマーを懲らしめに行こっか！"
