[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
2601003-1 = "A Forma de Deixar Lembranças" 
2601003-3 = "（Enquanto dava um passeio para me distrair, vi a Miyu andando de um lado para o outro na praia.）" 
2601003-9 = "[ns1] \"Bom dia, Miyu.\"\n[ns2] \"O que está fazendo por aqui?\"" 
2601003-13 = "……U-Ué……?\nS-Sensei…… O que faz aqui……?" 
2601003-14 = "Entendo, você conseguiu me ver de longe e……" 
2601003-15 = "Eu estava, ahm, como sempre…… sabe……" 
2601003-16 = "……Procurando pedrinhas." 
2601003-17 = "[s] \"Encontrou a pedrinha que queria?\"" 
2601003-18 = "Não estou procurando nada em específico, mas……\nElas são completamente diferentes das pedrinhas que encontro nas montanhas." 
2601003-19 = "Tanto nos formatos, quanto nos padrões e texturas…… cada uma tem a sua própria individualidade……" 
2601003-20 = "Já que estamos na praia…… Pensei que seria legal levar algumas pedrinhas bonitas de volta comigo……" 
2601003-21 = "Acabei me empolgando muito…… Me desculpe por te preocupar à toa, Sensei……" 
2601003-22 = "……Eh, você quer procurar pedrinhas comigo, Sensei?" 
2601003-23 = "Não tem nada de muito divertido nisso, e elas não têm valor algum, por que você iria……" 
2601003-24 = "[s3] \"Porque é algo que você gosta, Miyu.\"\n[s4] \"É a minha chance de procurar as pedrinhas que a Miyu gosta!\"" 
2601003-27 = "V-Você não precisa se dar a esse trabalho todo……" 
2601003-28 = "Mas…… já que você ofereceu……" 
2601003-29 = "C-Conto com você……" 
2601003-31 = "（Depois disso, andamos juntos pela praia coletando pedrinhas.）" 
2601003-32 = "（Tentei procurar por aquelas pedras discretas, mas com um charme rústico que a Miyu parece gostar tanto, e as reuni em um só lugar.）" 
2601003-34 = "Acho que já demos uma boa olhada por aqui. Hmm……" 
2601003-35 = "……Você encontrou alguma coisa, Sensei……?" 
2601003-36 = "[s] Entrego as pedrinhas que reuni a ela." 
2601003-37 = "A-Ah, muito obrigada……" 
2601003-41 = "……!!" 
2601003-42 = "Sensei……!\nC…… Como você encontrou uma pedrinha tão perfeita assim……!!" 
2601003-43 = "Sim, é essa mesma……! Era exatamente esse tipo de pedra que eu estava procurando!\nO tamanho, a aparência……!" 
2601003-44 = "U-Ué? ……Esta aqui foi você que encontrou também, Sensei?\nUau, ela é tão linda……" 
2601003-45 = "Eh, hã…… Essa aqui também…… ah, e essa também!" 
2601003-46 = "…………" 
2601003-47 = "……Sensei……" 
2601003-48 = "Por acaso…… você já trabalhou como 'avaliador' de joias em algum lugar……?" 
2601003-49 = "[s5] \"Não. Mas fico muito feliz que tenha gostado.\"\n[s6] \"Ver a sua alegria faz todo o esforço ter valido a pena.\"" 
2601003-52 = "Sim…… Elas são todas tão maravilhosas…… Eu nem sei quais levar comigo……" 
2601003-53 = "Por exemplo…… Esta pedrinha provavelmente foi desgastada pelas ondas, ganhando esse tamanho e cor completamente medianos, que você encontra em qualquer lugar……" 
2601003-54 = "Esta aqui…… tem essa cor avermelhada rara, quase como se tivesse sido pintada, mas mesmo assim possui uma aura misteriosa que a faz se misturar perfeitamente com os arredores……" 
2601003-55 = "E essa tem uma forma que, por algum motivo, atrai os olhos, mas ainda assim me faz lembrar daquelas pedrinhas perdidas nos parques da cidade……" 
2601003-56 = "[s] \"O mundo das pedrinhas é muito profundo e fascinante……\"" 
2601003-57 = "Uuu…… Qual eu devo escolher……" 
2601003-58 = "……S-Sensei…… Você poderia escolher por mim?" 
2601003-62 = "[ns7] \"……Tudo bem, deixe comigo.\"\n[ns8] Escolho as pedrinhas que a Miyu mais gostaria." 
2601003-66 = "（Então, sentei-me de frente para a Miyu e passamos um longo tempo analisando as pedras espalhadas no chão.）" 
2601003-73 = "（……Como não conseguimos nos decidir nem mesmo quando o sol se pôs, decidimos levar todas as pedrinhas que coletamos para casa por hoje.）" 