[translation]#[Texto Final, Mas eventualmente pode haver uma alteração. - Filipe 21/06.]
2601002-1 = "Uma Sniper no Píer" 
2601002-2 = "Vila de Pescadores - Píer" 
2601002-3 = "（No dia seguinte, fui até o píer onde a Miyu disse que estaria treinando.）" 
2601002-4 = "（Havia vários pescadores no local, mas nem sinal da Miyu.）" 
2601002-5 = "……Ué?" 
2601002-6 = "Sensei……?" 
2601002-7 = "[s1] \"……Miyu?\"\n[s2] \"De onde essa voz tá vindo……?\"" 
2601002-10 = "Estou aqui, Sensei…… bem na pontinha do píer……" 
2601002-11 = "Aqui……" 
2601002-14 = "[ns] \"Então você estava aí.\"" 
2601002-15 = "[wa:600]― [log=미유 수영복]Fufu, [wa:1200]até o Sensei [wa:700]demorou para me notar,[/log]" 
2601002-17 = "[wa:100]― [log=미유 수영복]Parece que hoje [wa:500]a minha camuflagem foi perfeita.[/log]" 
2601002-20 = "[wa:1800]― [log=미유 수영복]Como dizem: se quer esconder uma árvore, [wa:1000]esconda-a na floresta……[/log]" 
2601002-23 = "[wa:100]― [log=미유 수영복]Para me misturar [wa:900]entre os pescadores,[/log]" 
2601002-25 = "― [log=미유 수영복]Pescar é a [wa:800]atitude mais natural.[/log]" 
2601002-28 = "[wa:1700]― [log=미유 수영복]……Embora as gaivotas e aves marinhas [wa:1300]fiquem tentando pousar na minha cabeça o tempo todo,[/log]" 
2601002-30 = "[wa:200]― [log=미유 수영복]o que é um pouco problemático……[/log]" 
2601002-33 = "― [log=미유 수영복]Eu já estou…… [wa:1700]acostumada com isso……[/log]" 
2601002-35 = "― [log=미유 수영복]Fufu, [wa:1600]fufufu……[/log]" 
2601002-38 = "[wa:1800]― [log=미유 수영복]Eu escolhi este lugar [wa:500]por acaso só porque tinha equipamento de pesca por aqui, [wa:1200]mas,[/log]" 
2601002-40 = "[wa:100]― [log=미유 수영복]É um local perfeito [wa:1200]para uma emboscada furtiva.[/log]" 
2601002-43 = "― [log=미유 수영복]A vista daqui [wa:700]é ótima,[/log]" 
2601002-45 = "― [log=미유 수영복]O que o torna ideal [wa:1800]para monitorar os arredores.[/log]" 
2601002-48 = "― [log=미유 수영복]A brisa do mar é refrescante, [wa:2200]então não faz calor,[/log]" 
2601002-50 = "― [log=미유 수영복]E também [wa:500]tenho esse chapéu de palha para me proteger do sol……[/log]" 
2601002-53 = "[wa:1600]― [log=미유 수영복]E, [wa:1300]e…… [wa:2300]além do mais, hoje……[/log]" 
2601002-56 = "― [log=미유 수영복]O, [wa:1400]o, [wa:1700]Sensei também……[/log]" 
2601002-58 = "― [log=미유 수영복]……está ao meu lado.[/log]" 
2601002-62 = "Uhyah……!?" 
2601002-63 = "M-Me desculpe……!\nNão sabia que você estava aí……!" 
2601002-64 = "N-Não…… a culpa é da minha falta de presença……" 
2601002-65 = "[s] \"Miyu, você está bem?\"" 
2601002-66 = "……Sim. Eu só me assustei com o barulho repentino……" 
2601002-67 = "Minha presença é tão fraca aqui também que até os pescadores atracam seus barcos bem na minha frente……\nE as aves marinhas continuam se amontoando em mim……" 
2601002-68 = "Então não consigo me concentrar muito na pesca……" 
2601002-69 = "Mas é o de sempre, eu já estou acostumada…… fufu……" 
2601002-70 = "[s5] \"V-Vamos pensar pelo lado positivo!\"\n[s6] \"Como você está numa missão de infiltração, isso acaba sendo uma grande vantagem!\"" 
2601002-73 = "V-Você acha mesmo……" 
2601002-79 = "……Ué?" 
2601002-80 = "……Q-Que sensação é essa……?" 
2601002-81 = "[s7] \"Tá puxando……!\"\n[s8] \"É um peixe! É um peixe, Miyu!\"" 
2601002-84 = "Ugh…… tenho que enrolar rápido……!" 
2601002-85 = "Nngh……!\nÉ-É muito mais pesado do que eu pensei…… uuu……!!" 
2601002-86 = "Auuu……!!" 
2601002-95 = "E-Eu pesquei…………?" 
2601002-97 = "……I-Isso é……" 
2601002-101 = "[ns9] \"……É um grandão.\"\n[ns10] \"Isso…… é enorme, não é?\"" 
2601002-104 = "……V-Você acha?" 
2601002-105 = "Para ser sincera, eu não tenho muita experiência em pesca no mar, então não sei avaliar direito, mas――" 
2601002-109 = "……!\nE-Ei, olhem só! Aquela aluna pescou algo incrível!" 
2601002-110 = "É um monstro gigantesco!\nComo você conseguiu pescar uma presa tão grande!?" 
2601002-111 = "Ahm…… E-Eu não entendo muito de pesca……" 
2601002-112 = "Mas que coisa mais curiosa." 
2601002-113 = "Esse peixe é famoso por ser cauteloso e fugir assim que sente a presença de humanos……" 
2601002-114 = "Por acaso, você seria uma pescadora famosa……?" 
2601002-115 = "N-Não…… uma pessoa como eu……" 
2601002-116 = "É só que a minha presença é apagada mesmo……" 
2601002-117 = "[s11] \"Conseguir pescar um peixe tão grande e cauteloso assim……\"\n[s12] \"Miyu, você tem um talento incrível.\"" 
2601002-120 = "Q-Que nada……" 
2601002-121 = "Poder lançar a linha na água sem que os peixes sintam a sua presença é invejável." 
2601002-122 = "É um talento que eu daria tudo para ter……" 
2601002-123 = "Você recebeu algum treinamento especial para isso?" 
2601002-128 = "Ahm…… Eu, hum…… Sabe……" 
2601002-129 = "Fueeeh……" 
2601002-131 = "（Depois disso, resgatei a Miyu, que estava em pânico com o bombardeio de perguntas dos pescadores, e fugimos do píer.）" 