[translation]
2601005-1 = "A forma do céu"
2601005-2 = "（Decidi procurar a Miyu porque queria ver o céu com ela）"
2601005-5 = "Ah... Sensei...?"
2601005-6 = "O que eu estava fazendo aqui, você pergunta...?#nBem, é que..."
2601005-7 = "Não é como se eu estivesse fazendo algo especial... Eu só estava aqui, olhando para o céu..."
2601005-8 = "Uuu..."
2601005-9 = "É por causa daquela mensagem no MomoTalk de mais cedo, não é?#nNão tinha... nenhum significado profundo, na verdade."
2601005-10 = "Eu só... queria compartilhar com você o que achei do céu..."
2601005-11 = "Desculpe... deve ter sido um incômodo, né..."
2601005-12 = "[s] \"Eu queria saber o que você estava sentindo, Miyu.\""
2601005-13 = "Se for esse o caso... por favor, venha aqui."
2601005-14 = "Sente-se aqui no bloco e vamos... juntos..."
2601005-15 = "...Olhar para o céu e a linha do horizonte do mar."
2601005-16 = "Fufu... É uma paisagem comum, não é?"
2601005-17 = "Mas... para mim, foi um pouco... incomum."
2601005-18 = "Eu sempre fico esperando em pontos de sniper apertados ou me escondendo em lugares escuros, então..."
2601005-19 = "Aqui... a vista é aberta e o vento é agradável...#nDe alguma forma, me sinto calma, e além disso..."
2601005-20 = "...Tem um espaço vazio, é bom, não é?"
2601005-21 = "[s] \"Espaço vazio...?\""
2601005-23 = "O céu que eu costumo olhar tem muitas coisas bloqueando a visão..."
2601005-24 = "A cidade é cheia de prédios e as montanhas são cobertas por árvores, então..."
2601005-25 = "O céu que eu via sempre parecia embaçado..."
2601005-27 = "Mas... este céu tem uma linha do horizonte que parece ter sido desenhada com uma régua."
2601005-28 = "Sinto que, sob um céu assim, eu seria capaz de acertar qualquer alvo..."
2601005-29 = "...É estranho até para mim, mas de repente senti uma onda de confiança."
2601005-30 = "Por isso, fiquei com vontade de voltar aqui algum dia, de vez em quando..."
2601005-31 = "E acabei mandando aquela mensagem para você, Sensei..."
2601005-32 = "...Você não entendeu nada, né?#nDe-desculpe. Esqueça o que eu disse..."
2601005-33 = "[s1] \"...É uma bela vista, Miyu.\"\n[s2] \"Vamos vir ver de novo juntos da próxima vez?\""
2601005-36 = "N-não... eu não disse isso com essa intenção...!"
2601005-37 = "Uuu... Eu não deveria ter falado nada..."
2601005-38 = "Parece que estou sendo egoísta com você, Sensei..."
2601005-39 = "[s3] \"Não é nada disso.\"\n[s4] \"Eu também gosto deste céu.\""
2601005-42 = "S-sério...?"
2601005-43 = "Você também... realmente gosta... dele?"
2601005-47 = "S-se... se por acaso..."
2601005-48 = "Se você também... gosta desta paisagem... então..."
2601005-49 = "Bem... é que..."
2601005-50 = "...E-então..."
2601005-51 = "[s] \"Vamos vir juntos de novo.\""
2601005-52 = "…………！！"
2601005-53 = "……Ah."
2601005-54 = "Ahuuu..."
2601005-55 = "…………Sim."
2601005-57 = "...É uma promessa... tá bom...?"
