[translation]
2601606-1 = "NC、ND。"
2601606-2 = "特集記事の最後は――"
2601606-3 = "先生の刺激的なネタが……ちょっぴり欲しいな～なんちゃって。"
2601606-4 = ""
2601606-6 = ""
2601606-7 = "[ns] \"やっぱり、それが目的だったんだね！\""
2601606-8 = "いえいえいえー！目的というか、取材はあくまで過程ですので！"
2601606-9 = "そういうわけで、最近何かないですか？気になる人とか？"
2601606-10 = "それか、変なポーズで被写体になってくれるのでもいいですよ？"
2601606-11 = "[s] \"無難な記事で十分だから！\""
2601606-12 = "特集はインパクトが大事なのにぃー！"
2601606-13 = "ちぇー"
2601606-14 = "[s1] \"私は持ってきた仕事をするから、チアキも最終調整がんばってね。\"\n[s2] \"言っておくけど、スクープは渡さないから！\""
2601606-17 = "減るもんじゃないでしょーに！"
2601606-18 = "[s] \"減るよ！名誉とか、尊厳とか！もう減ってるし！\""
2601606-19 = "あははっ！"
2601606-22 = "（ノートパソコンで仕事をしていると……）"
2601606-23 = "（隣でチアキがむくっとした顔をして、こちらをにらんでいた）"
2601606-24 = ""
2601606-26 = ""
2601606-27 = ""
2601606-29 = ""
2601606-30 = "あの……こんなことを言うのは失礼ですが……。"
2601606-31 = "集中して面白い表情になるかと思ったのに、隙がないですね……。"
2601606-32 = "[s] \"私はスクープにはならない！\""
2601606-33 = "ちぇー"
2601606-34 = "うーん。"
2601606-35 = ""
2601606-37 = ""
2601606-38 = "！"
2601606-39 = ""
2601606-41 = ""
2601606-42 = "ああー！先生！テーブルの下にコインを落としちゃいました！"
2601606-43 = "ちょっと拾ってくれませんか？先生の方に転がっちゃって！"
2601606-44 = "[s3] \"そうなの？分かった！\"\n[s4] テーブルの下に入る。"
2601606-47 = "かかりましたねっ！"
2601606-49 = "えいっ！"
2601606-52 = "[wa:450]― [log=치아키 수영복]ふふっ！[wa:960]スキあり！[wa:1020]シャッターチャンス！[/log]"
2601606-55 = "― [log=치아키 수영복]あはっ！[wa:830]先生、[wa:960]小さく丸まっちゃって……[/log]"
2601606-57 = "― [log=치아키 수영복]これは表紙に[wa:860]ピッタリの構図ですね！[/log]"
2601606-60 = "― [log=치아키 수영복]ふっ[wa:510]ふ～ん！[/log]"
2601606-62 = "― [log=치아키 수영복]スクープがなければ[wa:1460]作ればいいんです！[/log]"
2601606-65 = "[ns] \"ち、チアキ！？コインはどこにいったの？\""
2601606-67 = "[wa:1060]― [log=치아키 수영복]チッ[wa:420]チッ[wa:360]チッ[wa:320]チッ[wa:340]チッ～！[wa:1260]甘いですね！[/log]"
2601606-69 = "― [log=치아키 수영복]落としたのは[wa:1840]これのキャップです！[/log]"
2601606-72 = "― [log=치아키 수영복]文字通り[wa:1110]一銭もかけずに[wa:950]おいしい場面になりましたね！[/log]"
2601606-75 = "[wa:770]― [log=치아키 수영복]面白くない先生は[wa:3450]「テーブルの下閉じ込めの刑」に処します！[/log]"
2601606-78 = "― [log=치아키 수영복]もっと面白いネタを[wa:1440]教えてくれたら[/log]"
2601606-80 = "― [log=치아키 수영복]解放してあげないことも、[wa:2840]ないですよ？[/log]"
2601606-83 = "― [log=치아키 수영복]あれ、[wa:920]どうしました？[/log]"
2601606-85 = "― [log=치아키 수영복]目をそらして……。[/log]"
2601606-88 = "[ns] \"それが……目のやり場に困るというか……。\""
2601606-90 = "[wa:610]― [log=치아키 수영복]まだインタビュー中ですよ！[/log]"
2601606-92 = "― [log=치아키 수영복]ちゃんとこっちを見てください！[/log]"
2601606-95 = "― [log=치아키 수영복]なんでこっちみてくれないんですかぁ？[/log]"
2601606-98 = "― [log=치아키 수영복]って、[wa:1340]これ……！[/log]"
2601606-101 = "[wa:4470]― [log=치아키 수영복]ひゃあああっ！[/log]"
2601606-103 = "― [log=치아키 수영복]ちょっ！[wa:610]見ちゃダメですっ！[/log]"
2601606-106 = "[wa:1000]― [log=치아키 수영복]出るのもダメ！[/log]"
2601606-108 = "― [log=치아키 수영복]じっとしててください！[/log]"
2601606-111 = "（周りの人たちが少なくなるまで、そのままテーブルの下に閉じ込められた）"
2601606-112 = "（その後……チアキは急用を思い出したと言って、逃げるように帰っていった）"
