[translation]
31090-1 = "Episódio 9: Sombras que oscilam sob a superfície"
31090-4 = "Ora, Sensei. Bom trabalho."
31090-5 = "Como estão as coisas com o Clube de Estudos Suplementares?"
31090-6 = "……Embora eu diga isso, já ouvi o que aconteceu. Parece que o primeiro exame não correu muito bem, não é?"
31090-7 = "Mas ainda restam duas tentativas, então……"
31090-8 = "……Ah, isso? É xadrez, um passatempo meu."
31090-9 = "[s] Você olha para o tabuleiro de xadrez nas mãos de Nagisa."
31090-10 = "……Provavelmente é um tipo que você não está acostumado a ver, certo?"
31090-11 = "As pretas têm o rei e a rainha, e o resto são apenas peões."
31090-12 = "As brancas têm três ou quatro de cada: rei, torre, bispo e cavalo…… Certamente é uma configuração incomum."
31090-13 = "[s] \"Você estava jogando sozinha?\""
31090-14 = "Sim, agora estou sozinha. A barulhenta da Mika também não está aqui."
31090-15 = "Eu tinha algo para lhe contar hoje, Sensei…… mas parece que você tem algo a dizer antes disso."
31090-16 = "[s] \"O que acontecerá com o pessoal do Clube de Estudos Suplementares se eles reprovarem nas três tentativas?\""
31090-17 = "……."
31090-18 = "Você ouviu por aí? A fonte foi…… a Hifumi, suponho."
31090-19 = "Ela tem esse hábito, sabe. Bem, esse também é um dos pontos positivos da Hifumi……."
31090-20 = "Bem, respondendo à sua pergunta, é simples. Se eles continuarem reprovando nos exames, não conseguirem evitar a repetência e não puderem ajudar uns aos outros…… então, infelizmente, não restará alternativa a não ser expulsá-los todos juntos."
31090-21 = "[s] \"Expulsão!?\""
31090-22 = "Claro, originalmente existem regras escolares aqui em Trinity sobre repetência, suspensão e expulsão."
31090-23 = "No entanto, os procedimentos são longos e trabalhosos, exigindo muitas confirmações e debates. Ao contrário de Gehenna, nós levamos os procedimentos muito a sério."
31090-24 = "Mas o Clube de Estudos Suplementares, criado às pressas desta vez, foi ajustado para ignorar tais regras. Como incorporamos um pouco da autoridade do Schale, esse tipo de medida tornou-se possível."
31090-25 = "Na verdade, o Clube de Estudos Suplementares foi……"
31090-30 = "criado justamente para expulsar as alunas."
31090-31 = "[s] \"……!?\""
31090-33 = "[s] \"Por que você faria algo assim……!?\""
31090-34 = "……."
31090-35 = "Porque entre elas, existe uma traidora de Trinity."
31090-36 = "[s] \"Uma traidora……?\""
31090-39 = "O objetivo dessa traidora é impedir a assinatura do Tratado do Éden."
31090-40 = "Para que você entenda o peso dessas palavras…… preciso explicar o que é o \"Tratado do Éden\"."
31090-42 = "O Tratado do Éden…… simplificando, é um tratado de não agressão a ser firmado entre Trinity e Gehenna."
31090-43 = "O cerne disso é o estabelecimento de uma organização neutra, onde todos os membros centrais de Gehenna e Trinity estarão presentes."
31090-44 = "Esta organização, que provavelmente será chamada de \"Organização do Tratado do Éden\" ou \"ETO\", intervirá e resolverá qualquer conflito que surja entre Trinity e Gehenna."
31090-45 = "É o que chamamos de \"inimigos no mesmo barco\". Uma aliança de paz hostil, forçada a navegar junta em um navio instável que balança constantemente."
31090-46 = "Com isso, uma guerra total entre as duas escolas não acontecerá. Se alguém atacar, ambos os lados acabarão caindo juntos."
31090-48 = "……Sensei."
31090-49 = "A longa relação de hostilidade entre Trinity e Gehenna é um grande fardo para ambos os lados."
31090-50 = "O Tratado do Éden é, provavelmente, a única maneira de evitar esse desgaste sem sentido e também uma forma de manter o equilíbrio de poder em Kivotos."
31090-51 = "Esta também foi a solução proposta pela Presidente do Conselho Estudantil Geral. Quando ela desapareceu, o projeto quase desmoronou, mas consegui reconstruí-lo até este ponto sob minha liderança."
31090-52 = "E agora, justamente quando estamos prestes a assinar este tratado tão esperado…… recebi informações de que há pessoas tentando sabotá-lo."
31090-53 = "Ainda não sei quem são. Não consegui identificá-los. Portanto, como segunda melhor opção…… reuni todos os suspeitos em um só lugar."
31090-54 = "……A traidora está lá. Mas não sei quem é."
31090-55 = "Sendo assim, vamos colocá-los todos em uma única caixa…… para que, quando chegar a hora, seja fácil descartar todos de uma vez."
31090-56 = "……Você já deve ter entendido, essa \"caixa\" é o Clube de Estudos Suplementares. E você, Sensei, colaborou na criação dessa \"caixa\"."
31090-57 = "……Sinto muito."
31090-58 = "Envolvi você em algo tão sangrento. Pode me xingar, se quiser."
31090-59 = "[s] \"……Mas se você realmente quisesse me usar, não estaria me contando isso agora, estaria?\""
31090-60 = "……Como esperado, você entende rápido."
31090-61 = "Eu me perguntava se você acreditaria em mim se eu contasse, mas como você disse, é exatamente isso. Sendo assim, nossa conversa será bem mais rápida."
31090-62 = "Professor."
31090-63 = "……Poderia procurar pelo traidor que está no Esquadrão de Aulas de Reforço para mim?"
31090-64 = "[s] \"…….\""
31090-65 = "Há alguém tentando enganar você, Professor, e enganar a Trinity."
31090-66 = "É um terrorista que deseja destruir a paz. Eles estão colocando a paz não só nossa, mas de todo o Kivotos, na balança em troca de seus próprios interesses."
31090-67 = "Encontrar esse traidor está diretamente ligado à paz em Kivotos. O que me diz? Espero que possa entender como o Schale, o Departamento Federal de Investigação――"
31090-68 = "[s] \"……Eu lidarei com esse problema do meu próprio jeito.\""
31090-71 = "……Entendo. Compreendido."
31090-72 = "……Mas, Professor. Quando é difícil separar e descartar o lixo minuciosamente, descartar a caixa inteira também é uma opção…… não acha?"
31090-73 = "E mais uma coisa…… sobre os exames, eles estão basicamente sob nosso controle."
31090-74 = "Por exemplo, coisas como \"o conteúdo do exame mudar de repente\", \"o local do exame mudar\" ou \"o nível de dificuldade mudar\"……."
31090-75 = "Espero que nada disso aconteça, mas……."
31090-76 = "……Peço desculpas, não foi uma boa forma de dizer. Então, continue cuidando do Esquadrão de Aulas de Reforço, Professor."
31090-77 = "Da nossa parte, não causaremos nenhum prejuízo ou dano a você…… é o que eu gostaria de dizer, mas……."
31090-78 = "[s] \"……Não pode garantir isso?\""
31090-79 = "……Pois é. Não posso prometer isso facilmente."
31090-80 = "Mas, dito isso, acredito que você não é o tipo de pessoa que abandonaria seus alunos…… então, nem eu mesma consigo prever o que acontecerá daqui para frente."
31090-81 = "Só espero que este desfecho…… seja o menos doloroso possível."
31090-82 = "Ah, mas deixarei uma coisa clara……"
31090-83 = "No primeiro exame, nós não realizamos nenhum tipo de manipulação. Posso jurar que isso não é uma mentira."
31090-84 = "[s] \"…….\""
31090-85 = "Espero que o seu jeito de fazer as coisas…… seja algo que beneficie a Trinity."
31090-86 = "……Até logo."
31090-89 = "Próximo episódio: Acampamento, começar!"
