[translation]
31160-1 = "Episódio 16;Uma Pequena Fresta"
31160-2 = "Ufa, que alívio!"
31160-3 = "Já tomou banho, que rápido, Hifumi."
31160-4 = "Ufufu, pois é. Afinal, a Hifumi não pôde tomar banho de manhã, e o dia todo ficou com o aroma ao natural――"
31160-5 = "Uawa! E-esse jeito de falar é vergonhoso……! Uu, se eu não tivesse dormido demais……."
31160-6 = "……Mas isso foi porque você estava preparando o simulado pra gente."
31160-7 = "Desculpa, Hifumi. Se amanhã de manhã também for difícil acordar, me fala. Da próxima, eu lavo o seu corpo."
31160-8 = "N-não, isso eu vou dispensar……!?"
31160-9 = "Você pode se lavar sozinha, oras! Você não é criança!"
31160-10 = "É uma questão de eficiência. As vantagens de todo mundo se lavar junto não são poucas. E, claro, também economiza água."
31160-11 = "Como não tem um ofurô grande, o evento de todo mundo se lavar junto com afinco parece meio difícil, mas……"
31160-12 = "Ah, tive uma boa ideia. Da próxima vez, em vez de banho, que tal todo mundo pular pelada na piscina?"
31160-13 = "Como é que você solta isso assim, tão de leve!? Não pode! Uma coisa absurda dessas é proibidíssima!!"
31160-14 = "Não acho a ideia ruim, mas existe alguma vantagem em fazer isso justamente na piscina?"
31160-15 = "Não acham que dá uma sensação de liberdade? Sob o céu azul, expor tudo e se ensaboar de um lado pro outro; só de imaginar…… ufufu♡"
31160-16 = "Sei, isso de fato eu não tinha pensado. Sensação de liberdade, é……"
31160-21 = "Boba, boba, boba, boba!! Não pode pensar, não pode imaginar, esse tipo de coisa não pode!"
31160-26 = "Não vai pintando a Azusa de um jeito estranho! Uma tarada em Trinity, você já é suficiente!!"
31160-27 = "Aliás, a Koharu também é do time que quer nadar totalmente nua, né?"
31160-28 = "Ignorando o contexto por completo!? Você é invencível!? A-aliás, eu nunca disse isso! Na piscina, maiô normal! Essa é a justiça! Você mesma, ontem, tava vestindo direitinho!"
31160-29 = "Ora……?"
31160-34 = "Pensa bem, Koharu. Aquilo que eu estava vestindo ontem na piscina……"
31160-35 = "Hã, a-aquele maiô, o que tem……?"
31160-41 = "Você acha, de verdade,[wa:1500] que aquilo era um MAI[wa:1000] Ô[wa:1000] ……?"
31160-42 = "!?!!?"
31160-43 = "S-se não era maiô, então era o quê……!?"
31160-45 = "A lingerie de hoje em dia tem um design bem elaborado; não acha difícil dizer, num relance, se é maiô ou não? E ainda tem a possibilidade de ser pintura……♡"
31160-46 = "……!?!?"
31160-47 = "Hã, mentira!? Peraí, isso quer dizer……!?"
31160-48 = "Ora, o que foi?"
31160-49 = "Se aquilo, por acaso, não fosse um maiô, alguma coisa mudaria? Né, Koharu?"
31160-50 = "Hã, é-é que……"
31160-51 = "Por exemplo, a diferença entre maiô e lingerie…… qual é? Função à prova d'água? Proteção da pele? Design? A área de exposição?"
31160-52 = "Você, Koharu, não conseguiu dizer pela aparência, né? Naquele lugar, naquela hora, acreditava-se que aquilo era um \"maiô\", né?"
31160-53 = "……???"
31160-54 = "Se, na verdade, aquilo fosse lingerie…… como se poderia provar esse algo que talvez fosse a \"verdade\"?"
31160-55 = "Não há nada mais impotente que uma verdade que não se pode provar…… não acha?"
31160-56 = "N-não entendo nada do que você tá falando…… n-no fim, é o quê!?"
31160-57 = "É só uma conversa de que aquele maiô era uma graça♡"
31160-58 = "……Hãã!? Era tudo brincadeira!?"
31160-59 = "……Sei, aquela lá, a quinta."
31160-60 = "……!"
31160-61 = "A quinta……? É que, Azusa, do que você tá falando……?"
31160-62 = "……."
31160-66 = "É só uma coisa que ouvi por aí, mas…… as sete regras antigas que se transmitem em Kivotos desde muito tempo. Se não me engano, era a quinta delas."
31160-67 = "\"É possível provar a verdade daquele que chegou ao paraíso?\"…… acho que era mais ou menos assim. As outras eu não sei."
31160-68 = "Ou seja, será que pode existir um paraíso que ninguém consegue provar…… era um tipo de enigma zen assim, é o que eu lembro."
31160-69 = "Azusa, como é que você sabe disso……."
31160-70 = "Quem conhece essa história é……"
31160-71 = "Não me diga, Azusa, que você encontrou a Seia……!?"
31160-72 = "……."
31160-74 = "……Seia?"
31160-75 = "Isso é a senhorita Seia, do Tea Party……?"
31160-76 = "……."
31160-77 = "……Não sei. Essa história eu só tenho a lembrança de ter ouvido em algum lugar, e……."
31160-78 = "……."
31160-79 = "Ah, sei…… aliás, a Azusa é transferida, né……."
31160-80 = "Vanitas vanitatum…… sendo assim……"
31160-84 = "……Não, não é nada. Já tá tarde, então acho melhor a gente ir dormir logo."
31160-88 = "Então, bom trabalho a todas por mais um dia!"
31160-91 = "Quarto do Sensei"
31160-93 = "Naquela noite……"
31160-94 = "……Sensei."
31160-95 = "É sobre a Hanako, é que……."
31160-96 = "[s] \"………\""
31160-97 = "……Enquanto eu juntava os gabaritos, por algum motivo estavam guardados num maço. Não sei se foi guardado por ser algo raro, ou por qual razão, mas……."
31160-98 = "As folhas de resposta de todas as provas do ano passado, do 1º ao 3º ano, estavam reunidas. Por alguma razão, parece que houve alguém que respondeu a todas elas……"
31160-99 = "[s] \"E essa pessoa……\""
31160-102 = "……Sim, era a Hanako."
31160-104 = "Seguindo as notas do 1º ano que eu achei ontem, acabei bisbilhotando de novo, mas……."
31160-105 = "A Hanako, ainda no estágio de 1º ano do ano passado, tirou nota máxima em \"todas as provas\", incluindo o conteúdo tido como difícil até pra turma dos brilhantes do 3º ano…… é de um nível que dá pra chamar de gênio sem sombra de dúvida……."
31160-106 = "Vendo o resultado das provas do 1º ano, a Hanako com certeza pensava \"foi este ano que minhas notas caíram de repente\". Mas, pelo que este resultado mostra, não é bem assim……."
31160-107 = "[s] \"Já no estágio do ano passado, ela devia conseguir resolver qualquer questão. Ou seja……\""
31160-108 = "……Sim. A Hanako, agora…… só dá pra concluir que ela está reprovando de propósito……."
31160-109 = "Hanako…… por quê……."
31160-111 = "Alojamento de Acampamento - Saguão"
31160-116 = "……."
31160-123 = "……."
31160-124 = "Azusa, de novo de vigília……?"
31160-125 = "……."
31160-129 = "Fáá……."
31160-130 = "……Bom dia."
31160-133 = "……Muito bem."
31160-134 = "……."
31160-135 = "Nnh……?"
31160-136 = "（……Ué? Aliás, desde de manhã, o Sensei não tá em lugar nenhum……）"
31160-137 = "（Onde será que ele foi……?）"
31160-139 = "Alojamento de Acampamento - Piscina"
31160-140 = "Uau, tá com água!"
31160-141 = "Aha, fazia tempo que eu não via água aqui dentro. Não me diga que vocês vão nadar agora? Ou é festa na piscina com todo mundo?"
31160-142 = "[s] \"Desculpa a demora. Posso saber o que você quer?\""
31160-143 = "……Ehehe."
31160-149 = "É que eu fiquei pensando se o Sensei tá se saindo bem."
31160-151 = "Próximo Episódio;O Traidor de Trinity"
