[translation]
3202-1 = "和楽姫の特別な公演（２）"
3202-2 = "（そして、いよいよチセの「百鬼夜行感謝祭」公演当日）"
3202-3 = "今日は待ちに待ったチセ様の公演だ！！"
3202-4 = "前回の感謝祭も良かったよね！今回どんなだろ？"
3202-5 = "チセ様の写真いっぱい撮るぞ～～～！"
3202-6 = "結局、当日になっても聞けず仕舞いだったね。"
3202-7 = "……はい。"
3202-8 = "ですが、チセちゃんから話してくれるまで聞くべきではありません。"
3202-9 = "私たちはただ、チセちゃんが安心して公演を終えられるようサポートするだけです。"
3202-10 = "見守るだけってこと？"
3202-11 = "今みたく？"
3202-12 = "ええ、そうです。舞台の上はチセちゃんのものですから。"
3202-13 = "私たちはチセちゃんの気持ちを汲み取って、全力でサポートするのです。"
3202-14 = "ふむ、我々は暗躍する側の存在、と。"
3202-15 = "にゃはは！そういうのも好きだわぁ。"
3202-16 = "ニヤ様、それは少々違うように思いますが……"
3202-17 = "ここはチセちゃんを信じて見守りましょう。"
3202-26 = "では、これより「百鬼夜行感謝祭」を開催します！"
3202-31 = "「百鬼夜行感謝祭」は、百鬼夜行連合学院の伝統的な公演で、学院に携わる皆さんに日頃の感謝を伝えるために行われてきました。"
3202-32 = "本日の公演は百鬼夜行のアイドル、和楽姫！#n[ruby=わらく]和楽[/ruby]チセ様がお届けします。"
3202-33 = "それではチセ様、お願いします！"
3202-34 = "うん、やるね～"
3202-39 = "初めは、傘を使った舞踊です。"
3202-40 = "百鬼夜行連合学院の工芸品である藍染を使用し不屈の精神を表す藍色の――"
3202-46 = "――ではなく、も、桃色の傘で……#nえ、えーっと、まるで桜の花びらのように美しい舞を披露してくださっています！"
3202-50 = "次は、百鬼夜行の伝統技法で作られたこけし人形――"
3202-54 = "――ではなく！#nか、可愛らしいキツネのお人形とだるまの登場です！"
3202-59 = "にゃは、どうやら他の人にも秘密にしてたみたいやね。"
3202-60 = "前回とは全く違う形の感謝祭……"
3202-61 = "これではきっと、会場に集まってくださった方たちも戸惑って……！"
3202-62 = "きゃーー！チセ様、かわい～！！"
3202-63 = "チセ様ーーー！"
3202-64 = "今日のチセ様も最高！"
3202-66 = "……はないようですが、しかし！"
3202-71 = "そして、いよいよ「百鬼夜行感謝祭」も……終わりの時間が近づいてまいりました。"
3202-72 = "最後に本日の主役、チセ様からのご挨拶を頂きます。"
3202-73 = "では、一言お願いします！"
3202-74 = "どうか、ご挨拶だけでも台本通り……！"
3202-75 = "みんな、今日は来てくれてありがと～"
3202-79 = "実は、いつもの公演とは違ったんだけど、みんな気づいてくれた？"
3202-80 = "今日は特に感謝を伝えたい人がいて、ちょっと変えてみたんだ～"
3202-81 = "や、やはりそうだったのですね……！"
3202-82 = "では、チセ様の特別な方とは一体、どなたなのでしょう！"
3202-83 = "それはね～"
3202-85 = "ニヤ部長と～カホ副部長～"
3202-90 = "へ！？"
3202-91 = "あら……あららら？"
3202-95 = "部長と副部長はね、いつも私が楽しく公演ができるように頑張ってくれてるの～"
3202-96 = "だから今日は、二人にありがとうって言いたくて。"
3202-97 = "それでは、公演の道具が違ったのは……"
3202-98 = "私とニヤ様のために……？"
3202-99 = "そういうことだったんね、にゃはは。"
3202-100 = "たしかに、桃色はカホが一番好きな色。"
3202-102 = "お人形も、私とニヤ様に似ているものを用意したのですね。"
3202-103 = "ん、んー？カホもそう思ってたん？"
3202-104 = "オレンジジュースも……よく見れば、いつもニヤ様がよく飲んでいるメーカーの……"
3202-105 = "儀式用のコップは、私の好きなキャラクターグッズですし……"
3202-106 = "プリンだって、私とニヤ様の好物……"
3202-107 = "なぁんだ。一本取られたね、これは。"
3202-108 = "チセもそういうとこがあるのね。後でお礼を伝えますか。"
3202-109 = "でも、だるまが私に似てるかどうかは――"
3202-111 = "うわぁあん……！チセちゃん、ありがとうございます！"
3202-112 = "そうとは知らず、チセちゃんを疑ってしまい……！"
3202-113 = "だいじょーぶ。"
3202-114 = "ニヤ部長、カホ副部長。いつもありがとう。"
3202-115 = "だから……"
3202-116 = "これからも、よろしくね？"
3202-118 = "はい！チセちゃん！！"
3202-119 = "にゃはは、任せなさい～"
3202-121 = "……それで、だるまなんだけど……"
3202-126 = "――ということがあったの。"
3202-127 = "[s1] \"カホとニヤ、感動しただろうね。\"\n[s2] \"喜んでもらえて良かったね。\""
3202-130 = "うん、カホはずっと泣いてた～"
3202-131 = "ニヤ部長も、感激してて……"
3202-132 = "作戦成功～"
3202-133 = "[s] \"チセは陰陽部のみんなが大好きなんだね。\""
3202-134 = "うん、大好き。"
3202-135 = "部長と副部長とは――これからもずっと一緒。"
3202-136 = "みんなそろって陰陽部だから～"
3202-138 = "和楽姫の特別な公演"
