[translation]
32060-1 = "第6話;真夜中の大騒ぎ（２）"
32060-2 = "……美食研究会？"
32060-3 = "ところで先輩、今どちらです？早くご命令を頂かないと、このままだとツルギ先輩が発射……飛び出ちゃいそうっすけど。"
32060-4 = "つ、ツルギはとりあえず止めてください。私は今その、私用で少々外に……。"
32060-5 = "いやー無理っすよ。ハスミ先輩以外じゃそうそう止められな……"
32060-6 = "あっ、ツルギ先輩！行かないでください！あとそっちはドアじゃなく壁――"
32060-7 = ""
32060-11 = "あー……とりあえずあたしらも一旦追いかけて、出撃しますね。"
32060-12 = "（ピッ）"
32060-13 = "……。"
32060-14 = ""
32060-16 = ""
32060-18 = "近いな。爆発音からして、ここから1km以内のところか。"
32060-19 = "え、えぇっ……！？"
32060-20 = "……みなさん。"
32060-21 = "突然のことですみませんが、みなさんの力が必要です。お願いできますでしょうか？"
32060-22 = "今はエデン条約を目前に控えて、色々と過敏な時期です。この問題が傍から見て「トリニティの正義実現委員会とゲヘナ間の衝突」と捉えられてしまうと、状況が不利になることは想像に難くありません。"
32060-23 = "つまり、補習授業部と「シャーレ」が一緒に解決してくださる……そういう構図が望ましいのです。先生、お願いできますでしょうか……？"
32060-24 = "[s] \"うん。よし、じゃあ補習授業部一同出発。\""
32060-26 = "了解した。先生の指示に従う。"
32060-27 = "えぇっ！？い、いきなり戦闘ですか……！？あ、あうぅ……。"
32060-28 = "ふふっ……まあ、先生がそう仰るのであれば♡"
32060-29 = ""
32060-31 = ""
32060-32 = "あっ、わ、私も……？先生と……ハスミ先輩と、一緒に……？"
32060-33 = "いつかこうして肩を並べる時期が来るとは思っていましたが……想像より早かったですね、コハル。"
32060-34 = "は、はい！頑張ります……！"
32060-35 = "そういえば、しっかり先生の指揮の下で戦うのは初めてか。遠慮は要らない、先生。私のことは存分に使って。"
32060-36 = "あらまぁ……♡"
32060-37 = "[s] \"じゃあ、安全第一で。\""
