[translation]
32065-2 = "O atuuuum!!!"
32065-3 = "Eu queria muito que fosse na forma de sashimi, mas virou tempura, né……."
32065-4 = "Hmm, pelo visto a gente ficou cercada★ E agora?"
32065-6 = "Ha, se a gente fugir cada uma pra um lado, a taxa de sobrevivência não sobe!?"
32065-11 = "Sei, boa ideia, Junko★ Então, vai depender da rapidez das pernas, mas é a lei do mais forte♪"
32065-16 = "Ufufu, pois é. Vai ficar por conta da sorte, mas isso também é uma espécie de tempero! Então, vamos!"
32065-21 = "Hãã!? P-peraí! Espera! Não me deixem pra trás só a mim――!?"
32065-26 = "N-não me deixem pra trás, oras! Buááá! Ah, vão ver! Um dia eu me vingo, com certeza――!!"
32065-33 = "Gh, que atrevidas……! Cada uma se separa e vai à caça!!"
32065-34 = "Sim!"
32065-36 = "Aqui é o distrito autônomo de Trinity! Fugir da gente é impossível!"
32065-38 = "Haa, haa……."
32065-39 = "V-vindo até aqui, agora sim tá tudo bem, né……?"
32065-45 = "……Hã?"
32065-46 = "Ora, Junko……."
32065-47 = "A-Akari!? Q-que foi, nesse estado todo cambaleante!?"
32065-48 = "Bom, indo direto ao ponto…… não deu★"
32065-53 = "Akari!?"
32065-57 = "Kuhihi…… kihihihihi……."
32065-58 = "……Hã? Q-quê!? Um demônio……!?"
32065-60 = "Kyahahahahahahaah!!!"
32065-61 = "Nãããão!? Me desculpaaa――!?"
32065-66 = "Próximo Episódio;Um Novo Ponto de Vista"
