[translation]
32070-1 = "第7話;新しい視点"
32070-3 = "あら、ジュンコさんにアカリさん。"
32070-4 = "あ、ハルナ。あんたも捕まったの？"
32070-5 = "ふふっ、10メートルくらいは頑張ったのですけれど。"
32070-6 = "みじか……。"
32070-7 = "では、無事脱出に成功したのはイズミさんだけということでしょうか。良かったですね、私たちの犠牲は無駄ではなかったようです。"
32070-8 = "いや犠牲っていうか、最初はほぼ逆の構造だったけど……。"
32070-9 = "正義実現委員会……なるほど、流石はトリニティきっての武力集団ですわね。凄まじい戦闘能力です。"
32070-10 = "びっくりしたよ！あのアカリが一瞬で潰れた缶ジュースみたいに……マジでびっくりした……。"
32070-11 = "もう、だからトリニティの本拠地まで来るなんて……いくらマグロだからって、どうしてこんなところにまで……！"
32070-12 = "それはですねジュンコさん。つまるところ、こういうことですわ。誰もいない流し台で水が流しっぱなしになっていたら――"
32070-13 = "それ前にも聞いたから！！"
32070-14 = ""
32070-16 = ""
32070-17 = "……私たち、これからどうなるのかな？"
32070-18 = "まあ順当に考えて、風紀委員会に引き渡しじゃないでしょうか？"
32070-19 = "びっっっくりしたぁ！？無言で起き上がらないでよ！？無事で良かったわねアカリ！？"
32070-20 = "ふふ、まあそうそう簡単にはやられませんよ★"
32070-21 = "っていうか、そっか、風紀委員会か……やだなぁ、もう考えるだけで……。"
32070-22 = "参りましたわね……ヒナさんの手に私たちの命運が託されるのは、できれば避けたかったのですが……。"
32070-23 = "まあちょっと今回は無茶をし過ぎましたね★仕方ないかもしれません。"
32070-24 = ""
32070-26 = ""
32070-27 = "（どうして私まで……）"
32070-29 = "トリニティ自治区の境界付近"
32070-30 = "（一方その頃、イズミは……）"
32070-31 = "こ、ここはどこ……？私はイズミ……うわーん！もう、どこに行けばいいのぉ！？"
32070-32 = ""
32070-34 = ""
32070-36 = "お疲れ様でした。先生、そして補習授業部のみなさん。お陰様で、事態を無事に収拾することができました。"
32070-37 = "あ、あはは……途中からはもう、無我夢中という感じでしたが……。"
32070-38 = "正義実現委員会の戦術を目の前で見ることができて、良い勉強になった。"
32070-39 = "や、役に立てたのかどうかは、分かりませんが……！"
32070-40 = "ところで、あの方々はこの後どうなるのですか？"
32070-41 = "本来ならば私たちの方でこの後の処遇を決めるのですが……今回は時期が時期ですので、ゲヘナの風紀委員会に託そうかと。"
32070-42 = "[s] \"なるほど。\""
32070-43 = "はい。そこで、先生にもう一つお願いがあるのですが……。"
32070-44 = "[s] \"うん、何をしたら良い？\""
32070-45 = "エデン条約のことを考えると、ここから先も私たちが能動的に動くのは少々避けたいところです。"
32070-46 = "ですので、風紀委員会への引き渡し……この部分を先生にお願いできませんでしょうか？"
32070-47 = "「シャーレ」が生徒を引き渡す……この形でしたら、私たちにとってもゲヘナ側にとっても、政治的な憂慮がだいぶ減るのです。"
32070-48 = "[s] \"分かった、任せて。\""
32070-49 = "はい。何から何までありがとうございます、先生。それでは、私たちは一旦引いた位置にいますので……よろしくお願いいたします。"
32070-51 = "トリニティ自治区・外郭の大橋"
32070-52 = "（風紀委員会の車両の到着を待っていると……）"
32070-53 = ""
32070-59 = ""
32070-60 = "……お待たせしました、死体はどこですか？"
32070-61 = "[s] \"……え？\""
32070-62 = "……失礼。死体ではなく負傷者でしたね。たまに混同してしまって。"
32070-63 = "えー……納品リストには、新鮮な負傷者3名と人質1人……と書かれていましたが。"
32070-64 = "[s] \"新鮮な……？\""
32070-65 = "……ところであなたは？正義実現委員会ではなさそうですが……？"
32070-66 = "[s] \"えっと……。\""
32070-67 = ""
32070-69 = ""
32070-72 = "その方は、「シャーレ」の[USERNAME]先生。"
32070-73 = ""
32070-75 = ""
32070-76 = "[ns] \"ヒナ！\""
32070-77 = "久しぶりね、先生。いつぶりかしら。……ところで、ここで何をしてたの？"
32070-78 = "知り合いでしたか、風紀委員長。"
32070-79 = "うん……まあ、そうね。"
32070-81 = "なるほど。このタイミングでお互い政治的な問題にしないために、先生が……。"
32070-82 = "確かに、問題にしたくないのはこちらも同じ。だからこそ、公的には今回こうして風紀委員会ではなく、こっちの「救急医学部」が来たってことになってる。私は基本的に、ただの付き添い。"
32070-83 = "……救急医学部の部長、[ruby=ひむろ]氷室[/ruby]セナです。以後よろしくお願いいたします、先生。"
32070-84 = "死た……いえ、負傷者がいたらいつでもお呼びください。配送料は頂きませんので。"
32070-85 = "[s] \"よ、よろしくね……。\""
32070-86 = "「救急医学部」はゲヘナの中でも、特に政治的な部分に関わりが薄い立場にいる。だから今回、こうしてお願いしたの。"
32070-87 = "政治ごっこは風紀委員長にお任せします。私は死体以外に興味ありませんので。"
32070-88 = "「負傷者」でしょう？それに、本物の死体を見たことないでしょうに。"
32070-89 = "はい、負傷者でした。そのことについては、風紀委員長も無いでしょう？"
32070-90 = ""
32070-92 = ""
32070-93 = "とにかく……美食研究会はこの中？じゃあ、こっちに移してもらえる？"
32070-94 = ""
32070-96 = ""
32070-98 = "……ふふっ。ヒナさん、お久しぶりですわね。"
32070-99 = "ハルナ、相変わらず……いや、詳しい話は帰ってからで。"
32070-100 = "あら、やはり「救急医学部」の方でしたか★ちょっと私の腕の角度があり得ない方向に曲がってるのですが、診ていただけます？"
32070-101 = "うぇっ、酔った……吐きそう……。"
32070-102 = "た、助かった……。"
32070-103 = "あら、給食部の……今日一日見てないと思ったら、こんなところに。"
32070-104 = "今、学園でジュリが……いや、やっぱり説明は帰りながらで。"
32070-105 = "なんだか、美食研究会がもう一人足りてない気がするけど……まあ面倒だから良いわ。"
32070-107 = "色々と配慮していただいてありがとうございます、先生。今度ゲヘナにいらした際には、何か美味しいものでおもてなし致しますね。"
32070-108 = "ではまた今度～★"
32070-109 = "……うるさい、早く入って。"
32070-110 = "[s] \"えっと、じゃあまた。気をつけてね……。\""
32070-114 = "……積載完了しました。出発の準備もできてます。"
32070-115 = "……少し待ってて。"
32070-116 = "……。"
32070-117 = "先生……トリニティで、何をしてるの？"
32070-118 = "[s] \"補習授業部っていうところの担任を……。\""
32070-119 = "それはもう知ってる。色々と情報は入ってきてるから……。"
32070-120 = "そうじゃなくて、シャーレは中立的な組織だったはず。この時期にトリニティにいるとまるで……"
32070-121 = "[s] \"………。\""
32070-122 = "……やっぱり今のは無し、気にしないで。先生がそんなことするわけが無い。"
32070-123 = "[s] \"ヒナ、こっちからも一つ聞きたいんだけど。\""
32070-124 = "うん？聞きたいこと……？"
32070-125 = "[s] エデン条約についてヒナの考えを聞く。"
32070-128 = "（今の状況とこの先の展望について、ヒナに詳しく話した。）"
32070-129 = ""
32070-131 = ""
32070-133 = ""
32070-135 = ""
32070-137 = ""
32070-140 = "なるほど……先生、結構複雑な状況にいるのね。"
32070-141 = "……いや、待って。何か今、変な場面が混ざってなかった？"
32070-142 = "[s1] \"気のせいだと思う。\"\n[s2] \"間違いなく気のせいです。\""
32070-143 = "……。"
32070-144 = "……。"
32070-145 = "まあ、とにかく……。"
32070-146 = "「トリニティの裏切り者」……ね。"
32070-147 = "数多くの言葉が飛び交い、誰の言葉が真実なのか、誰が嘘をついているのか分からない状況……。"
32070-148 = "[s3] \"色んな見方がありそうだなって思って。\"\n[s4] \"見方によって、真実は変わるかもしれないから。\""
32070-149 = "慎重なのか楽天的なのか、ほんと分からないわね……。"
32070-150 = "慎重なのか楽天的なのか、ほんと分からないわね……。"
32070-151 = "……ところで、こんな大事なことを私に話して良いの？"
32070-152 = "[s] \"うん、ヒナのこと信じてるから。\""
32070-153 = "……。"
32070-154 = "……そういうのが、先生の悪いところ。"
32070-155 = "[s] \"……？\""
32070-156 = "……独り言よ。"
32070-157 = "エデン条約が軍事同盟、ね……まあ、興味深い見方ではあるかもしれない。"
32070-158 = "ただ、少なくとも私はそうは思わない。あれはれっきとした平和条約、私はそう考えてる。"
32070-159 = "[s] \"なるほど……？\""
32070-160 = "条約によって生み出される[ruby=ETO]エデン条約機構[/ruby]……あれを武力集団と捉えたところで、あれはナギサが単身で統制できるようなものじゃない。"
32070-161 = "万魔殿のリーダーであるマコトも、ナギサと同様の権限を持つことになる。"
32070-162 = "それだけじゃなく、他のティーパーティーや万魔殿のメンバーに対してもある程度の権限が分割される。だからETOが誰かひとりの意志で本来の目的を失って、暴走するようなことは考えにくい。"
32070-163 = "もちろん、その全員が協力するなんて事態になれば、理論的にはあり得ることかもしれないけれど……。"
32070-164 = "そもそもの話として、もしそんなことができるのなら、初めから両学園の統合でもしておけば良いだけのはず。"
32070-165 = "それに、マコトは誰かと協力するだなんてことができない[ruby=たち]質[/ruby]だから……。"
32070-166 = "[s] \"……じゃあマコトは、どうしてエデン条約に賛同してるの？\""
32070-167 = "……賛同というか多分、何も考えてないんじゃないかしら。そもそも、ゲヘナ側でエデン条約を推進したのは、私だったから。"
32070-168 = "[s] \"ヒナが……？どうして？\""
32070-169 = "……色々面倒だし、引退するのもアリかなって。"
32070-170 = "ETOができたら、今よりも遥かにゲヘナの秩序はマシになるはず。そうなったらもう、私が風紀委員長じゃなくても良いでしょう。"
32070-171 = "[s] \"なるほど……。\""
32070-172 = "風紀委員長、まだですか？"
32070-173 = "……ええ、今行く。"
32070-174 = "じゃあお疲れ様、先生。また……"
32070-175 = ""
32070-177 = ""
32070-178 = ""
32070-179 = ""
32070-181 = "……補習授業部のことは、先生が守るのよね？"
32070-182 = "[s] \"うん。\""
32070-183 = "……そう。"
32070-185 = "……じゃあ、またね。"
32070-186 = ""
32070-188 = ""
32070-194 = "何だか、怒涛の一日でしたね……。"
32070-195 = "そうですね、夜のお散歩がこんなハードなことになるなんて……。"
32070-196 = "うん、でも楽しかった。"
32070-197 = "……えへへ。"
32070-198 = "コハルちゃんは、あれからずっと嬉しそうですね？やはり、ハスミさんをしっかり手助けして共闘できたからですか？"
32070-199 = "そうよっ、悪い！？ハスミ先輩と一緒に戦えるのなんて、初めてだったし……。"
32070-201 = "私が役に立てたなんて、嬉しい……！えへ、えへへへっ……！"
32070-202 = "うふふ、それは何よりです♡あとはハスミさんが願っている通り、落第を免れないといけませんね？"
32070-203 = "わ、分かってる！大丈夫よ、わ、私はエリートなんだから！"
32070-204 = "はい……私も、頑張らないとです♡"
32070-205 = ""
32070-207 = ""
32070-208 = "あはは……もう遅いですし、そろそろ寝ましょうか。明日の勉強に支障が出ると良くないですし……。"
32070-209 = "では、お疲れ様でした。"
32070-210 = "[s] \"みんなお疲れ様、お休み。\""
32070-212 = "（そうして、長い一日が終わって……。）"
32070-214 = "次回;差し込む希望"
