[translation]
33010-1 = "Episódio 1; Post-mortem (1)"
33010-4 = "Sala secreta"
33010-6 = "……Yurizono Seia?"
33010-7 = "Ah, sim, sou eu. Eu estava esperando por você, Shirasu Azusa, da Escola Filial de Arius."
33010-8 = "……Esperando? Por mim?"
33010-9 = "Sim, porque eu já tinha visto essa cena até mesmo em sonhos."
33010-10 = "Como seria melhor explicar…… Bem, pense nisso como uma espécie de \"sonho premonitório\"."
33010-11 = "Às vezes, tenho sonhos assim. Sonhos que acabam se tornando realidade mais tarde, além de vários outros tipos de sonhos."
33010-12 = "……Ou seja, você sabe o que eu vou fazer a partir de agora?"
33010-13 = "Ah, você veio para destruir o meu halo, não foi?"
33010-14 = "Parece que havia outros companheiros, mas apenas você chegou até aqui. Um poder impressionante, Shirasu Azusa."
33010-15 = "……Sabendo disso, por que não fugiu?"
33010-16 = "……Porque é inútil."
33010-17 = "\"Tudo é vaidade\"…… Essa era uma frase que Arius adorava, não era? É a mesma coisa. Para mim, que consigo ver o futuro, lutar contra ele é inútil."
33010-18 = "É verdade que o conceito de \"morte\" é difícil de ser visto em Kivotos. Ainda assim, nós estamos vivas, e não há como a \"morte\" não estar lado a lado conosco."
33010-20 = "\"Destruir o halo\"…… Ou seja, alguém deseja a minha morte."
33010-21 = "E você invadiu esta sala secreta sem que ninguém mais percebesse. Já que você é capaz de fazer tudo isso, lutar é inútil mesmo…… Do seu ponto de vista, você não acha o mesmo, Shirasu Azusa?"
33010-23 = "Bem, não é como se não houvesse outros motivos além desse…… A propósito, você já destruiu um halo antes?"
33010-24 = "……Não, nunca. Mas aprendi como fazer."
33010-25 = "\"Aprendi\"……"
33010-26 = "Causar um dano fatal e irreversível ao corpo…… continuar causando dano."
33010-27 = "Normalmente, não importa quantos tiros de 5.56mm você dispare, dificilmente seria um ferimento fatal."
33010-28 = "Mas não é como se não causasse dano. Uma quantidade absurda de munição, uma vantagem esmagadora para continuar causando dano e tempo para isso. Se você despejar tudo isso de forma \"anormal\"…… não é impossível destruir um halo apenas com armas de fogo."
33010-29 = "Além de armas de fogo, existem inúmeras outras formas. Não é como se doenças não existissem. Por exemplo, privar alguém de água e comida por um longo período, trancar alguém em um ambiente onde não se pode respirar, causar uma perda de sangue que interrompa as funções corporais, manter alguém contido em um estado onde a temperatura corporal caia abaixo do limite……"
33010-30 = "Deve haver inúmeras maneiras de levar alguém à \"morte\"."
33010-31 = "Além disso, ouvi dizer que \"Yurizono Seia tem uma saúde frágil\"."
33010-32 = "……Então, essas armas de fogo seriam o suficiente?"
33010-33 = "……Isso não é impossível. Mas, no momento, não tenho tempo nem vantagem garantida."
33010-34 = "Por isso, usarei esta bomba especial. Com isso, vou \"destruir o halo\"."
33010-35 = "Ou seja, é uma \"bomba que destrói halos\"? É uma tecnologia que nunca ouvi falar, mas……"
33010-36 = "……Entendo, Arius faz pesquisas desse tipo. O \"método para destruir halos\", ou seja, o \"método para matar pessoas\"."
33010-37 = "……Ah, e foi isso que eu aprendi. \"Escola\" é um lugar onde se \"aprende\" essas coisas, não é?"
33010-38 = "……"
33010-39 = "Entendo…… Arius chegou a esse ponto……"
33010-44 = "……Shirasu Azusa, deixe-me perguntar uma coisa. Você está preparada para se tornar uma \"assassina\"?"
33010-45 = "……"
33010-47 = "Eu vi. Eu vi você temendo se tornar uma \"assassina\"."
33010-48 = "Se você desejava isso ou se havia outras opções…… na verdade, isso não é o ponto principal."
33010-49 = "\"Um assassino é um assassino\". Essa proposição clara, absoluta e, acima de tudo, desesperadoramente fácil de entender, ficará gravada em seu corpo. E continuará existindo neste mundo."
33010-50 = "O desespero, o sofrimento, a raiva, o arrependimento e a frustração, e a sensação de impotência que você sentirá depois que isso acontecer…… tudo isso desaparecerá no vazio, sem chegar a ninguém."
33010-51 = "Se você é de Arius, não tem como não conhecer. \"Vanitas vanitatum\"…… a verdade deste mundo."
33010-52 = "……No entanto, eu sei. Sei que, embora você concorde com essas palavras, em algum lugar, você as nega."
33010-54 = "……Não é?"
33010-55 = "Enquanto olhava para aquela flor, você pensava nisso."
33010-56 = "\"Tudo é vaidade\"…… mas, ainda assim, é preciso lutar."
33010-57 = "Isso é o que está enraizado no seu âmago, a imagem mental que define você…… embora eu não tenha entendido muito bem."
33010-58 = "Sendo assim, na verdade, você……"
33010-60 = "……Não veio aqui para me matar, mas sim para me pedir um conselho, não foi?"
33010-61 = "Sobre como você deve lutar daqui para frente."
33010-63 = "Sala de reuniões da Sisterhood"
33010-65 = "……[USERNAME] sensei?"
33010-66 = "[s1] \"……Desculpe, eu acabei cochilando um pouco.\"\n[s2] \"Sinto como se tivesse tido um sonho……\""
33010-67 = "……Sei que está ocupado, mas agradeceria se pudesse se concentrar um pouco mais."
33010-68 = "……Sei que está ocupado, mas agradeceria se pudesse se concentrar um pouco mais."
33010-69 = "[s] \"Desculpe……\""
33010-70 = "Ouvi dizer que, ultimamente, você tem corrido para todo lado resolvendo as consequências dos incidentes…… até mesmo em assuntos fora da sua jurisdição."
33010-71 = "[s] \"É que me sinto impotente…… há tantas coisas que não consegui resolver……\""
33010-72 = "……Entendo."
33010-73 = "Muita coisa aconteceu em sequência, então talvez seja melhor organizarmos as ideias."
33010-74 = "Será uma conversa entediante. Não acho que seja algo interessante, mas…… organizar as coisas pode nos ajudar a seguir em frente. É o que chamamos de \"post-mortem\"."
33010-75 = "……Então, vamos ao que interessa."
33010-76 = "O quarto da Seia-san foi explodido por volta das 3 da manhã."
33010-77 = "Logo depois, a primeira a chegar ao local foi a líder Mine, da \"Brigada de Socorro\"."
33010-80 = "Após confirmar a situação no quarto, a líder Mine relatou o fato imediatamente ao Tea Party."
33010-81 = "O Tea Party entrou em caos, mas logo iniciou o trabalho de ocultação de informações e a busca pelo culpado."
33010-85 = "No entanto, aproveitando-se da confusão, a líder Mine desapareceu levando o corpo da Seia-san. Dizem que nem mesmo os outros membros da Brigada de Socorro sabiam do paradeiro dela."
33010-87 = "……Até aqui, essa é a situação sob a perspectiva do Tea Party. Mas, na verdade, a informação sobre o \"corpo da Seia-san\" era falsa. A líder Mine espalhou o boato de que o \"halo dela havia sido destruído\" enquanto a escondia em um local seguro."
33010-88 = "Pensando bem, uma \"aluna com o halo destruído\" não deveria ser um alvo. Pode-se dizer que foi a melhor forma de proteger a Seia-san."
33010-89 = "Uma situação anormal onde membros do Tea Party são atacados…… Ela deve ter pensado: \"Antes de decidir em quem confiar, farei isso com minhas próprias mãos\"."
33010-90 = "Considerando que a culpada era, na verdade, a Mika-san do Tea Party — o local onde as informações deveriam estar centralizadas —, a decisão dela acabou sendo correta, mas……"
33010-91 = "……No entanto, a Seia-san ainda não acordou."
33010-92 = "Embora os ferimentos da explosão tenham cicatrizado, ela continua dormindo profundamente…… A líder disse que nem ela sabe a causa."
33010-93 = "Até agora, a líder Mine e a Seia-san continuam escondidas em um lugar que ninguém conhece."
33010-94 = "……Embora seja apenas um resumo, é isso o que aconteceu em relação ao ataque contra a Yuri-zono Seia."
33010-100 = "[ns] \"Hanako!\""
33010-101 = "Pensei que você estivesse sofrendo por estar presa com a entediante Sakurako-san, então vim te salvar, Sensei. Fufu♡"
33010-102 = "……Não é hora para brincadeiras, Hanako-san."
33010-103 = "A Sakurako-san continua a mesma de sempre…… Que tal lermos um livro um pouco mais ousado juntas da próxima vez?♡"
33010-104 = "Tenho a impressão de que a Sakurako-san não tem muita imunidade para esse tipo de coisa…… Ufufu♡"
33010-109 = "……Hanako-san. Você não esqueceu daquela promessa, esqueceu?"
33010-110 = "……Claro que não."
33010-113 = "[ns] \"Achei você, Hanako.\""
33010-114 = "Ora. Sensei, por que você está aqui……"
33010-118 = "[ns] \"Sobre aquela promessa com a Sisterhood que você mencionou……\""
33010-119 = "Ah, isso……"
33010-120 = "……Sensei do Schale, este não é um problema no qual você deva intervir."
33010-121 = "[s] \"A Hanako é minha aluna do Clube de Estudos Suplementares.\""
33010-122 = "Ora, ora……"
33010-123 = "……"
33010-124 = "Desculpe…… é que, eu……"
33010-125 = "Mari-chan……"
33010-129 = "Fui eu quem pediu. Para ajudar a Hanako-san, eu persuadiria a Sakurako-sama……"
33010-130 = "E, como promessa em troca,"
33010-131 = "Fazer com que a expulsão da Hanako-san fosse revogada……"
33010-132 = "……"
33010-133 = "Eu não consegui impedir a Hanako-san…… não consegui entender o que se passava no fundo do coração dela……"
33010-134 = "Sinto muito por ter chegado a esse ponto…… mas eu queria que a Hanako-san continuasse na escola……"
33010-135 = "……Não, Mari-chan."
33010-136 = "Não é você quem deve se desculpar. Fui eu quem agiu por conta própria e deixou todos preocupados. Na verdade, quem deve pedir desculpas sou eu."
33010-137 = "Desculpe, Mari-chan…… deixei você preocupada, não foi?"
33010-138 = "Hanako-san..."
33010-139 = "Eu não estou pensando em abandonar a escola agora. Por favor, fique tranquila."
33010-140 = "É verdade...?"
33010-141 = "Sim. Aprendi no Clube de Aulas de Reforço que... eu deveria "lutar" um pouco mais. Não é, Sensei?"
33010-142 = "[s] \"...Sim.\""
33010-143 = "...Muito obrigada. Hanako-san, Sensei [USERNAME]."
33010-147 = "...Mas, apenas isso não é o suficiente."
33010-148 = "Sakurako-sama...?"
33010-149 = "Tenho mais um pedido, Hanako-san."
33010-150 = "..."
33010-151 = "É sobre..."
33010-155 = "\"Apenas a nudez será permitida como vestimenta escolar\"... Você queria que eu ajudasse no plano de criar essa regra escolar e transformar Trinity em um \"paraíso de nudez\"... era isso, não era?"
33010-156 = "Sim, é isso mesmo..."
33010-157 = "...Sim?"
33010-158 = "Não acredito que a Sisterhood estava tramando uma conspiração dessas... Como esperado da Sakurako-san, a líder de um grupo secreto envolto em mistérios."
33010-159 = "Além disso, aquela cláusula sobre a exceção, \"Em princípio, nudez total. No entanto, apenas a Sisterhood tem permissão para usar véus ao ir para a escola\"..."
33010-161 = "Até eu fiquei impressionada. Nudez com véu, que mundo novo é esse..."
33010-162 = "Sim...!? "
33010-163 = "Mas, na minha posição atual, não tenho escolha a não ser cooperar... E já que vou fazer isso, farei com que seja um sucesso!"
33010-164 = "Porém, essa parte do véu é injusta demais. Por isso, minha proposta é: \"Em princípio, nudez total. No entanto, todas as alunas podem usar meias!\" O que acha?"
33010-165 = "Se você aceitar isso, eu cooperarei com o plano!"
33010-166 = "Sa, sa, sa, Sakurako-sama!? U, um plano desses...!?"
33010-167 = "Não é isso!"
33010-168 = "Que..."
33010-169 = "\"Que...\" nada! O que você está dizendo de repente?!"
33010-171 = "\"Em troca de atendermos ao pedido da Hanako-san, a Hanako-san também atenderá a um pedido nosso\", esse foi o trato, não foi?!"
33010-172 = "...Ah, houve uma conversa dessas também, não é?"
33010-174 = "Haa..."
33010-175 = "Se fosse possível, o melhor seria que você entrasse para a Sisterhood... mas isso seria apenas intimidar e encurralar você."
33010-176 = "...Com este incidente como ponto de partida, nosso \"isolacionismo\" até agora vai mudar. Começaremos a nos envolver gradualmente em questões políticas também."
33010-177 = "Nesse processo, certamente haverá muitas coisas. Naquela hora, poder contar com alguém como a Hanako-san pode ser a chave. É apenas sobre isso."
33010-178 = "Bem, se for só isso, não me importo... haa..."
33010-179 = "Por que você está com essa expressão tão decepcionada... Não, por favor, não volte a falar disso..."
33010-180 = "[s] \"...Hanako, você realmente não se importa?\""
33010-181 = "Sensei..."
33010-182 = "...Não usarei métodos forçados. De qualquer forma, é uma forma de \"pedir ajuda\" à Hanako-san, e não pretendo exigir nada absurdo."
33010-183 = "...Muito obrigada, Sakurako-sama."
33010-184 = "O assunto se desviou... Vamos voltar ao tópico principal. Bem..."
33010-185 = "Sobre a \"ida à escola em nudez total\", certo? ♡"
33010-186 = "Sim, esse assunto... não é isso! Eu disse para não voltar a falar disso...!"
33010-187 = "Ufa,"
33010-192 = "Não tem jeito, não é... Vamos voltar ao assunto do ataque à Seia-chan. Como você sabe, a culpada parece ter sido a Azusa-chan."
33010-193 = "...O quarto da Seia-chan foi explodido às 3 da manhã. No entanto, a invasão ao quarto ocorreu por volta das 2 da manhã."
33010-194 = "Aqui, temos um intervalo de cerca de 1 hora. A invasora... ou seja, a Azusa-chan, ficou 1 hora naquele quarto com a Seia-chan."
33010-195 = "Durante esses 60 minutos, que tipo de conversa as duas tiveram..."
33010-196 = "A Azusa-chan não me contou muitos detalhes, mas..."
33010-198 = "Sala de Consulta"
33010-201 = "Shirasu Azusa-san, pode entrar."
33010-202 = "..."
33010-204 = "Próximo episódio: Post-mortem (2)"
