[translation]
34030-1 = "第3話;檻の中のお姫様"
34030-2 = "エデン条約の事件以来、トリニティ総合学園の情勢は複雑になりました。"
34030-3 = "特にミカさんに対する世論はかなり悪化している状況です……。"
34030-4 = "ミカさんは既に自身の所属していた勢力のパテル分派から追放され、明日行われる聴聞会でティーパーティーの資格も剥奪されることが決定しています。"
34030-5 = "過程や真相はともあれ――ミカさんはアリウス分校と結託してエデン条約の事件を起こした主犯ですから。"
34030-6 = "[s] \"……！！\""
34030-7 = "聴聞会が開かれるまでにも、断罪を要求する騒動がたびたび発生し、私刑としてミカさんのいる檻の中に石を投げ込む生徒が現れたり……。"
34030-8 = "学園の掲示板にはミカさんに対する非難の書き込みが殺到し……パテル分派はミカさんが所属していたというだけで冷たい目で見られ……。"
34030-9 = "ミカさんが使っていた本や所持品は押収され、大事に集めていた服やアクセサリーも焼却されて……。"
34030-10 = "[s] \"そんな事態に……。\""
34030-11 = "……正義実現委員会が取り締まっていますが、学園全体に広がっているこの空気を払拭することは不可能に近いです。"
34030-12 = "[s1] \"……。\"\n[s2] \"そうだったんだ……。\""
34030-13 = "……ミカさんはトリニティにおいて公共の敵になっています。"
34030-14 = "……ミカさんはトリニティにおいて公共の敵になっています。"
34030-15 = "それらすべてを、ミカさんの負うべき罰だと切り捨てる事もできますが……。"
34030-16 = "……それでも、私はミカさんを弁護したいです。彼女は既に自分が犯した罪以上の代償を払っていますので。"
34030-17 = "[s3] \"そうだね……私も手伝うよ。\"\n[s4] \"私にできることはないかな？\""
34030-18 = "……はい、ありがとうございます先生。ですが……。"
34030-19 = "……はい、ありがとうございます先生。ですが……。"
34030-20 = "ミカさん本人が……ご自身を弁護する意思がないようで……。"
34030-21 = "[s] \"ミカが……？\""
34030-22 = "ミカさんは聴聞会を欠席しようとしています。そんな状態で行われる聴聞会は……間違いなく彼女の退学に直結するでしょう。"
34030-23 = "ですが……私では彼女に出席するよう説得することが叶わず……。"
34030-24 = "セイアさんならできたのかもしれませんが……彼女は今、それどころではありませんし。"
34030-25 = ""
34030-27 = ""
34030-28 = "……そこで、お願いがあるのですが。"
34030-29 = "[s] \"うん……私がミカに会って説得してみるね。\""
34030-30 = ""
34030-32 = ""
34030-33 = "ありがとうございます。先生のお言葉ならきっと……。"
34030-34 = "それに、ミカさんは先生を待っているようですので……。"
34030-35 = "……ふう。"
34030-36 = "少し、安心しました。まだ何も解決してはいませんが……。"
34030-37 = "[s] \"ナギサは大丈夫……？\""
34030-38 = "私……？ああ……。"
34030-39 = "私は大丈夫ですよ……いつもと変わりありません。"
34030-40 = "……ふふ、私のことを心配してくださるのは先生くらいですね。ありがとうございます。"
34030-41 = "それでは……後はよろしくお願いいたします。"
34030-43 = "ナギサと別れ、ミカの元に向かっていると……。"
34030-46 = "セイア様を害そうとした裏切り者を引きずり出せ！"
34030-47 = "アリウスと手を組んでエデン条約を台無しにした罪人がティーパーティーだなんて、許せません！"
34030-48 = "罪人には罰を！断罪を！"
34030-50 = "み、みなさん！この線の中から出ないでください！"
34030-51 = "裏切り者に罰を！！私たちを騙した代償を！！"
34030-52 = ""
34030-54 = ""
34030-55 = "[ns] （すごい空気だ……）"
34030-58 = "ミカが幽閉されている檻"
34030-59 = "[ns] \"ミカ……？\""
34030-60 = ""
34030-61 = "しーっ。"
34030-62 = ""
34030-64 = ""
34030-65 = "[ns5] \"……？\"\n[ns6] （……かすかに音楽が聞こえる）"
34030-66 = ""
34030-67 = ""
34030-69 = ""
34030-70 = "……お待たせ。礼拝の時間だったの。今日は賛美歌を聞く日。"
34030-71 = "ここでも礼拝だけは必ず参加しなきゃいけないなんて、ちょっと過酷じゃない？"
34030-72 = "こういうとこくらいは大目に見てくれてもいいのにね。"
34030-73 = "[s] \"でも、いい曲だね。\""
34030-74 = "そうかな？聞いてて退屈じゃない？「ご慈悲を」とか「憐れみたまえ」とか――"
34030-75 = "[ruby=キリエ]Kyrie eleison[/ruby]なんて、名前も気に入らない。どうして見えもしない存在に縋らなきゃいけないの？"
34030-76 = "「憐れみたまえ」だなんて口にしたところで悲惨なだけじゃん。そんなの自分にも、他人にもするものじゃないよ。"
34030-77 = "でも歌は好きだよ！歌詞はちょっと微妙だけど。"
34030-78 = "あ、そうだ先生。私の歌聞いたことないよね？"
34030-79 = "本来ならタダで聞かせるものじゃないけど、先生なら特別っていうか。こうやって会いに来てくれたし！"
34030-80 = "塔に幽閉されたお姫様が、運命の人にセレナーデを歌うの。どう？物語のワンシーンみたいでしょ！"
34030-81 = "[s] \"塔じゃなくて檻だけどね。\""
34030-82 = "うわぁ、そこで現実に戻しちゃう……？まぁ、事実だけど。"
34030-83 = ""
34030-85 = ""
34030-86 = "……それで、今日はどうしたの先生？"
34030-87 = "[s7]  \"一通りの事情は聞いたよ、ミカ。\"\n[s8]  \"聴聞会を欠席するんだって？ナギサが心配してるよ。\""
34030-88 = "……。"
34030-89 = "……。"
34030-90 = "ナギちゃんは元気、だよね？……うん、良かった。"
34030-91 = "多分、ナギちゃんの側にシスターフッドと救護騎士団長が一緒にいたでしょ？"
34030-92 = "……やっぱり。ティーパーティーの立場が危うくなればなるほど、他の勢力が幅を利かせるようになる。"
34030-93 = "ここまで直接的にティーパーティーを牽制するとは思わなかったけど……。"
34030-94 = "……ナギちゃんのストレス、ひどそうだね。"
34030-95 = "[s] \"そうだね……ところで、来る時に広場の集団を見たよ。\""
34030-96 = "あー……うん、そっか。"
34030-97 = "……まあ、今の私の立場は見た通りだよ。仕方ないよね。"
34030-98 = "ナギちゃんは、私が聴聞会に出席すれば全てが丸く収まると思っているみたいだけど……トリニティはそんなに甘くない。"
34030-99 = "……あの事件以来、ティーパーティーの権威は地に墜ちた。"
34030-100 = "学園内の世論も、政治的な立場もそう……当然だよね、私があんなことをしちゃったんだから。"
34030-101 = "そんなボロボロの状態で、ナギちゃんが私を庇えば庇うほど……"
34030-102 = "「ティーパーティー」の……ナギちゃんはおろか、セイアちゃんの立場すら危うくなっちゃう。"
34030-103 = "私なんかのために、そうなってほしくない。"
34030-104 = "これは全て、私が払わなきゃいけない代償だから。"
34030-105 = "[s9]  \"でも、退学になるかもしれないって……。\"\n[s10] \"それに、ミカもこれまで色んな仕打ちを受けて……。\""
34030-108 = "……。"
34030-109 = "[s] \"もう十分、代償は払ってるんじゃない？\""
34030-110 = "で、でも……。"
34030-111 = "……それでも、私のせいだから。"
34030-112 = "ナギちゃんと一緒に集めた、思い出が詰まった大切な宝物は、燃えちゃったみたいだけど……。"
34030-113 = "私は、それでも許されない……セイアちゃんにもまだ、恨まれたままで……。"
34030-114 = "[s11] \"セイアはミカを恨んでない。私が保証するよ。\"\n[s12] \"セイアはもうミカを許してるよ。\""
34030-115 = "………ち、違う！そんなわけない……だって、何度も謝ろうとしたけどダメだった……。"
34030-116 = "………ち、違う！そんなわけない……だって、何度も謝ろうとしたけどダメだった……。"
34030-117 = "この間会った時だって……。"
34030-119 = ""
34030-120 = "セイアちゃん、今日も顔色良くないよ。眠れなかったの？お肌もガサガサだよ？保湿クリーム貸してあげようか？"
34030-121 = "……。"
34030-122 = "えっと、セイアちゃん……？"
34030-123 = "……あのさ、もし良かったらその……"
34030-124 = "一緒にご飯でも食べない？まあご飯って言っても、檻の中でロールケーキなんだけど！"
34030-125 = "まったく、ナギちゃんも心が狭いよね。三食全部ロールケーキにするなんて！"
34030-126 = "……ミカ。"
34030-127 = "う、うん？食べる？"
34030-128 = "済まないが、今は……。"
34030-129 = "あっ……そ、そうだよね？やっぱり、その……。"
34030-130 = "少し体調がすぐれなくてね……申し訳ないが、部屋に戻らせてもらうよ。"
34030-131 = ""
34030-133 = ""
34030-134 = ""
34030-135 = ""
34030-137 = "[ns] \"セイアが……？\""
34030-138 = "……。"
34030-139 = "セイアちゃん、最近自分の部屋から出てこないし、誰も部屋に入れてないみたいで……。"
34030-140 = "寝たきりになってるって噂もあるくらいで……セイアちゃん、元々体が弱いから。"
34030-141 = "それに、なんだか他にも悪い噂ばかりで……セイアちゃんの部屋からすすり泣きが聞こえたとか……。"
34030-142 = "セイアちゃんの言葉は、いつも分かりづらいけど……"
34030-143 = "多分、私は許されてないんだろうなって……。"
34030-144 = "[s13] \"セイアはミカを許すってたしかに言ってたよ。\"\n[s14] \"何か行き違いがあったんじゃないかな？\""
34030-145 = "……ありがとう、先生。でもね、セイアちゃんが私を恨むのは別に構わないんだ……。"
34030-146 = "……ありがとう、先生。でもね、セイアちゃんが私を恨むのは別に構わないんだ……。"
34030-147 = "私はまだ、セイアちゃんにちゃんと「ごめんね」って言えてないから……。"
34030-148 = "そんな状態で、私のせいでセイアちゃんの体調がもっと悪くなったり……。"
34030-149 = "セイアちゃんが、また無理をしてしまったら……私は……自分のことを絶対許せないと思う……。"
34030-150 = "[s] \"私がセイアに会ってみるよ。\""
34030-151 = "せ、先生が……？"
34030-152 = "[s] \"ミカがセイアにちゃんと「ごめんね」を言えるように。\""
34030-153 = "……！"
34030-154 = "[s15] \"そうしたら……私とナギサ、セイア、ミカ、みんなで一緒に、\"\n[s16] \"みんなで明日の聴聞会に出席しよう！\""
34030-155 = "……。"
34030-156 = "……。"
34030-157 = "……ちょ、ちょっと待って。どうしてそんな……。"
34030-158 = "わ、私にそこまでする価値、あるかな……？"
34030-159 = "私……二度と泣かないって誓ったのに、どうしてそんな……。"
34030-160 = "……そんなこと言っちゃうの。"
34030-161 = ""
34030-163 = ""
34030-164 = "……うん、わかった。"
34030-165 = "そこまで言うなら……みんなと一緒に、聴聞会に行く。"
34030-166 = "[s] \"うん。決断してくれてありがとう、ミカ。\""
34030-167 = "……。"
34030-168 = "……正直、二度目のチャンスなんてないと思ってた……でも、これが運命なら……。"
34030-169 = "私はやっぱり、塔の中に閉じ込められたお姫様だったのかな……?"
34030-170 = ""
34030-172 = ""
34030-173 = "あ……な、何でもないよ、先生！"
34030-174 = "それじゃあセイアちゃんを……よろしくね、先生。"
34030-176 = "[ns] セイアの部屋に足を運ぶ。"
34030-181 = "セイアの治療室"
34030-182 = ""
34030-183 = "……先生？"
34030-184 = "[s] \"セイア大丈夫？顔が真っ青だよ。\""
34030-185 = "先生……無事、だったのか。いや、私の都合の良い夢かもしれないな。幻か、虚構か、或いはいずれも同じことかもしれないが……"
34030-186 = "[s] \"ど、どうしたの……？\""
34030-187 = "……。"
34030-188 = "いや、違うようだね……その瞳は――"
34030-189 = "……そうか。今日は、君がトリニティを訪れる日だったな。"
34030-190 = "済まない。最近の私はこれまでにも増して、夢と現実の境界が曖昧でね……。"
34030-191 = "現在、過去、未来……それらが絶え間なく私を包み込み、私が今何処に立っているのかも不明瞭になるくらいだ。"
34030-192 = "まあ、つまるところ気にしなくても良い……そう捉えてもらっても構わない。"
34030-193 = "[s] \"みんなが心配しているよ。何があったの？\""
34030-194 = "……そうか。"
34030-195 = "何があったか、という問いに正確に答えることは難しい――ただ、一つ言えるとするならば。"
34030-196 = "私は今、誰にも告げられない未来を手にしてしまっている。だが先生、君になら……。"
34030-197 = "……私の言葉に、耳を傾けてもらえるかい？"
34030-198 = "[s] \"うん、もちろん。\""
34030-199 = "ここからは、今まで君が経験してきた事件とは全く別種の……完全に異なる類のものだ。"
34030-200 = "だがどうか……荒唐無稽だと感じても、どうか聞いてほしい。"
34030-201 = "[s] \"……分かった。\""
34030-202 = "……過日、夢の使者が私に告げたんだ。"
34030-203 = "言うなれば「予知夢」といった類の――つまりは何時しか至る未来の片鱗……もちろん、それ自体は日頃私が視ている世界の一つだが。"
34030-204 = "しかし、その日だけは様子が違っていた。そう、あの日私は――"
34030-205 = "……世界が、キヴォトスが終焉を迎える光景を視たんだ。"
34030-207 = "次回;夢と蜃気楼の狭間で"
