[translation]
34105-9 = "……!!"
34105-10 = "……."
34105-16 = "Ufu, eu sabia que vocês viriam pra cá. Na mosca!"
34105-17 = "Mika…… Misono……."
34105-18 = "Entrada da vilã☆ é mais ou menos isso! ……Então vocês ainda lembravam de mim?"
34105-19 = "Não parece uma cara de \"que bom te ver\"…… que foi?"
34105-24 = "Essa cara, como se tivessem visto uma bruxa."
34105-26 = "Próximo Episódio;A Perseguidora"
