[translation]
34120-1 = "Episódio 12; Distrito Autônomo de Arius"
34120-6 = "Então, a Atsuko... por ordens daquela mulher... na Basílica do distrito autônomo de Arius..."
34120-7 = "E-Era só isso que nós sabíamos..."
34120-13 = "Humm... Foram para o distrito autônomo de Arius para salvar a amiga... e levaram o Sensei junto?"
34120-14 = "Entendi... é claro."
34120-15 = "Se é o Sensei, com certeza ele faria isso."
34120-16 = "......"
34120-17 = "Mas..."
34120-18 = "Ainda assim..."
34120-22 = "Eu vou... atrás deles.#nVou alcançá-las e ter a minha vingança."
34120-23 = "Será que ele vai me desprezar... ou ficar desapontado...#nEu não queria que o Sensei me odiasse..."
34120-24 = "......Mas, mesmo assim――Eu não consigo me segurar."
34120-25 = "Me desculpe... Afinal..."
34120-26 = "Eu jamais perdoarei o Esquadrão Arius――Mesmo que eu continue sendo chamada de bruxa, eu tenho que persegui-las até o fim do mundo e me vingar."
34120-30 = "......Então, Sensei, por favor não me pare."
34120-39 = "......"
34120-40 = "......E-Está tudo bem! Podem subir!"
34120-41 = "[ns] Sobe."
34120-45 = "A segurança deve ser fraca por aqui... Foi a escolha certa."
34120-46 = "P-Pois é..."
34120-47 = "Phew... Guh..."
34120-48 = "[s] \"Este é o distrito autônomo de Arius...?\""
34120-49 = "......Antigamente sim, agora é só uma ruína."
34120-50 = "......"
34120-51 = "O verdadeiro distrito autônomo fica um pouco mais adiante.#nMas como elas já sabem que estamos a caminho, acho que não conseguiremos nos aproximar tão fácil."
34120-52 = "......Isto aqui era um campo de treinamento."
34120-53 = "[s] \"Campo de treinamento?\""
34120-54 = "Originalmente eram ruínas, mas depois que a guerra civil acabou, também começou a ser usado como campo de treinamento."
34120-55 = "[s] \"Guerra civil...?\""
34120-57 = "É sobre a guerra que dividiu o distrito autônomo de Arius em dois, cerca de 10 anos atrás.#nQualquer aluna de Arius da nossa idade sabe disso."
34120-58 = "[s] Presta atenção nas palavras de Misaki."
34120-59 = "......Não é uma história muito legal de se ouvir."
34120-60 = "E não tem nada a ver com a nossa missão atual... Então não estou com muita vontade de contar."
34120-61 = "Eu..."
34120-62 = "Eu ainda me lembro――foi aqui que conhecemos a Azusa-chan pela primeira vez, não foi?"
34120-63 = "......"
34120-67 = "Que treinamento era aquele mesmo... tiro ao alvo, ou fabricação de bombas...?#nUma garota que não obedeceu às 'ordens' dos adultos estava apanhando muito..."
34120-68 = "[s] \"......\""
34120-69 = "Todos em volta apenas observavam...#nMas aquela garota levantava várias e várias vezes, e continuava encarando os adultos..."
34120-70 = "Se deixassem continuar assim, parecia que o halo daquela garota seria destruído... mas eu estava com tanto medo que não conseguia me mexer..."
34120-71 = "Foi então que a Saori-nee-san... quero dizer, a Líder, veio correndo e..."
34120-72 = "......Vamos deixar a nostalgia para depois. Agora precisamos focar na missão."
34120-76 = "E então... o que vamos fazer agora?"
34120-81 = "......"
34120-82 = "Nós até trouxemos um adulto conosco, mas é impossível para nós lutar contra todo esse distrito autônomo e contra 'ela'. Como vamos salvar a Princesa?"
34120-86 = "......Líder?"
34120-91 = "[ns] \"Saori?\""
34120-92 = "L-Líder!?"
34120-93 = "Ugh... guh..."
34120-96 = "......Que febre alta. Como você aguentou ficar assim até agora..."
34120-97 = "F-Febre!?"
34120-98 = "......A Líder não descansa há quase 4 dias. Além dos ferimentos, há a falta de sono e a exaustão...#nAcho que aguentar tudo isso apenas na força de vontade chegou ao limite."
34120-99 = "O-O-O que vamos fazer!?"
34120-103 = "[ns] Tira um antitérmico do kit de primeiros socorros."
34120-104 = "R-Remédio...!?"
34120-105 = "......Então você anda com isso."
34120-106 = "[s1] \"Eles vendem em lojas de conveniência, sabe.\"\n[s2] \"Eu também tenho remédio pro estômago, petiscos para gatos, barra de chocolate...\""
34120-107 = "Então é isso... Adultos dão medo..."
34120-108 = "Então é isso... Adultos dão medo..."
34120-109 = "Ainda bem... Obrigada."
34120-113 = "......Líder, beba isso. Vai se sentir melhor."
34120-119 = "*Glup*... Haa, phew..."
34120-120 = "Líder..."
34120-121 = "[s] \"Vamos descansar um pouco aqui.\""
34120-122 = "......Sim, concordo."
34120-123 = "S-Sim... Então, eu posso ficar de vigia...?"
34120-124 = "Vamos nos revezar. Você também precisa descansar, Hiyori."
34120-125 = "Sensei, durma um pouco também. Eu fico no primeiro turno de vigia."
34120-126 = "[s] \"Certo, muito obrigado.\""
34120-127 = "S-Sim. Entendido..."
34120-134 = "(Decidi me sentar em um lugar qualquer e descansar...)"
34120-140 = "......Sensei, a minha voz está alcançando você...?"
34120-141 = "Se a minha voz estiver te alcançando... por favor... escute com atenção..."
34120-142 = "Neste momento, estou presa no mundo intermediário, entre o sonho e a realidade...#nE não tenho certeza de quanto tempo mais poderei permanecer aqui."
34120-143 = "Não nos resta muito tempo... Eu preciso te contar a situação atual, Sensei..."
34120-144 = "Eu... cometi um erro terrível..."
34120-146 = "Eu acabei conhecendo a Gematria――a reunião deles, em meus sonhos..."
34120-155 = "A Beatrice, que está controlando o distrito autônomo de Arius, planeja realizar um ritual na Basílica..."
34120-167 = "E no fim desse ritual... Kivotos encontrará o seu fim..."
34120-169 = "Ainda não consegui descobrir exatamente o que ela pretende com esse ritual..."
34120-170 = "Mas suponho que ela esteja tentando invocar 'algo' que não existe em Kivotos..."
34120-173 = "Eu fui atacada pela Beatrice dentro do sonho lúcido#n――e acabei entrando em contato com a entidade que existe além do ritual..."
34120-174 = "Sim――Ao tocar 'aquilo', o meu receptáculo começou a desmoronar..."
34120-176 = "......E foi assim, que eu machuquei a Mika."
34120-177 = "Ao entrar em contato com o fim de Kivotos, entrei em pânico e ataquei a Mika com minhas palavras... enquanto meu próprio corpo desmoronava..."
34120-181 = "Eu sempre... só faço machucar aquela garota..."
34120-183 = "A Mika vai se culpar, e cometerá um pecado irreversível..."
34120-187 = "E esse ritual da Beatrice, tem potencial para ser o estopim que guiará Kivotos para a sua perdição."
34120-188 = "――Durante esse processo, a Atsuko do Esquadrão Arius perderá a flor da sua vida."
34120-189 = "Como eu estou presa neste mundo intermediário, que não é sonho nem realidade#n――A única coisa que posso fazer é lançar essas palavras a você, Sensei, sem saber se elas irão te alcançar."
34120-190 = "Ah, e mais uma coisa, Sensei... tome cuidado. A Beatrice tem você como alvo."
34120-191 = "......"
34120-192 = "É impossível resolver todos esses problemas sozinho."
34120-193 = "Você já fez o suficiente por nós, Sensei.#nEntão, por favor, não tente carregar o peso de todos os problemas nas suas costas."
34120-194 = "Eu vou escapar daqui e, com a ajuda da Nagisa e das outras, vou trazer a Mika de volta."
34120-195 = "Desta vez, eu quero finalmente pedir desculpas a ela."
34120-196 = "Portanto, Sensei..."
34120-197 = "Sensei... Se a minha voz estiver te alcançando... Eu imploro..."
34120-202 = "Fuja――e afaste-se o máximo possível do distrito autônomo de Arius."
34120-209 = "Senão... você, Sensei... vai..."
34120-211 = "............................................."
34120-213 = "Próximo Episódio; O Nosso Passado"