[translation]
34130-1 = "第13話;私たちのこれまで"
34130-3 = "[ns1] （セイア……）\n[ns2] （ミカ……）"
34130-7 = ""
34130-8 = "せ、先生？"
34130-9 = "……ごめん、起こした？"
34130-10 = "夢でも見たの？#n――まぁ、こんな環境じゃ熟睡は難しいよね。私たちは慣れてるけど。"
34130-11 = "[s] \"……みんなは何をしていたの？\""
34130-12 = "リーダーの様子を見てました。解熱剤が効いたみたいで、もう熱はありません。今は眠っています……。"
34130-13 = "いつまでも休んでるわけにはいかないけどね。#n……まだ追手は来てないから、あと30分くらいしたら出発しよう。"
34130-14 = "[s] \"30分か……。\""
34130-15 = "うん。何か必要なものある？"
34130-16 = "[s3] \"……さっきの話の続き、聞かせてくれる？\"\n[s4] \"みんなの話を聞かせてほしい。\""
34130-17 = "えっと……そ、それは……。"
34130-18 = "えっと……そ、それは……。"
34130-19 = "そんな事聞いてどうするの……聞いてて楽しい話じゃないよ。"
34130-20 = ""
34130-22 = ""
34130-23 = "……まぁ、私が知ってる範囲でよければ話すけど。どうせ時間も余ってるし。"
34130-24 = "……。"
34130-26 = "――最初の記憶は、長年続いた内戦の終わりを宣言する「マダム」の姿。"
34130-27 = "私たちは幼かったから、内戦の事も「マダム」の事も、何一つ知らなかった。#nただ、そうなんだ、って漠然と受け止めていた。"
34130-28 = "「マダム」は自分がアリウスの新たな生徒会長であり、主人であり、支配者だと言ってた。そうして、残っていた生徒に多くのことを教えるようになっていったの。"
34130-30 = "[ruby=Vanitas vanitatum et omnia vanitas]全ては虚しい。どこまで行こうとも、全てはただ虚しいものだ[/ruby]。"
34130-32 = "様々な戦闘技術……そして『全ては虚しいもの』という真理……。"
34130-33 = "わ、私たちが経験する苦痛は全て「トリニティ」のせいで……#n「ゲヘナ」は、そもそも共存などできない存在だと教えられました……。"
34130-34 = "[ns] \"……。\""
34130-36 = "わ、私たちは、誰かを憎み嫌う「殺害の意志」を持っているから……#n「人殺し」と同じなのだと……。"
34130-37 = "そしてこの自治区以外に、「人殺し」の居場所はない、とも……。"
34130-38 = "「彼女」は、自分こそが真実を教える真の存在であり、生徒たちが従い、尊敬すべき大人なのだと言ってました……。"
34130-39 = "お、大人の話だから……疑う事なく、受け入れてました……。"
34130-40 = ""
34130-41 = "みんなその教えに従ってました。#n反抗すると、怒られるから……アズサちゃんとか、姫ちゃんみたいに。"
34130-42 = "[s] \"……。\""
34130-43 = "ひっ……！？せ、先生！？すごい顔になってますが……！？"
34130-44 = "……言ったでしょ。楽しい話じゃないって。"
34130-45 = "怖い……大人って怖いです……。"
34130-46 = "[s5] \"……ごめんね。アツコについて教えてもらえる？\"\n[s6] \"アツコはどうして「姫」って呼ばれてるの？\""
34130-47 = "ひ、姫ちゃんがなんでそう呼ばれているか……。"
34130-48 = "ひ、姫ちゃんがなんでそう呼ばれているか……。"
34130-49 = "えっと……お、お姫様だから……？"
34130-50 = "姫は……私たちが幼い頃からお姫様だった。"
34130-52 = "自治区を統治していた、かつてのアリウス生徒会長の血を引いてるんだって。#nだから「ロイヤルブラッド」って呼ばれてたみたい。"
34130-53 = "アリウス自治区の会長はそれまで世襲制だったらしいから。#n――本来なら、彼女がアリウス分校の生徒会長になるはずだった。"
34130-54 = "……リーダーと私、ヒヨリは幼い頃から貧民街でろくでもない生活をしていたの。"
34130-55 = "私の記憶の姫ちゃんは……昔から気品あふれる服を着ていました。#nわ、私たちとは全然違って……へ、へへ……。"
34130-56 = ""
34130-57 = "私やリーダーにとって、姫ちゃんは羨望の的でした。#n……ミサキさんはあまり興味なさそうでしたけど……。"
34130-58 = "……いや、私も全く興味がないわけじゃなかったよ。ただ、表に出さなかっただけ。"
34130-59 = "そ、そうだったんですか！？"
34130-60 = "姫はすごく優しかった。私みたいなのにも、手を差し伸べてくれて……。"
34130-61 = "そういえばマスクを被ってなかった頃は、よく笑ってたっけ……。#nアツコは……私にとっても大切な人だよ。"
34130-62 = "……。"
34130-63 = "――内戦が終わった後、姫は「彼女」の手で生贄として捧げられるらしいって噂が流れ始めた。"
34130-64 = "一体どうしてなのか、私たちはよく分かってなかったけど……。"
34130-65 = "皆に尊敬される[ruby=とうと]貴[/ruby]い存在だから、選ばれたんだって思ってた。"
34130-66 = "……。"
34130-67 = "でも、リーダーはそれに納得しなかった。#nだから、生贄として捧げられるはずだった姫を私たちの元に連れてきた。"
34130-68 = "どうやって連れてこられたのかは、分からないけど……。"
34130-69 = "「彼女」が素直に姫を解放するとは思えないから……リーダーと「彼女」の間で何か、約束でもしたんだと思う。"
34130-70 = "[s] \"……。\""
34130-73 = "姫の運命を変えたいなら、彼女の命令に従えと……。"
34130-74 = "そうすれば、姫だけでなく……他の仲間も助けてやると。"
34130-75 = ""
34130-76 = "そうして、姫は顔と声を隠して、私たちと一緒に訓練を受けるようになったの。"
34130-77 = "リーダーは……私とヒヨリ、姫――そして後から合流したアズサを自ら指導した。今思い返しても、辛い記憶でしかないけど。"
34130-78 = "思い出したくもないです……あの時のリーダーはすごく怖かったから……。"
34130-79 = "その後、私たちは「スクワッド」と呼ばれ、アリウスの多くの任務を遂行することになった。"
34130-80 = "……でも、結果的に私たちは任務を果せなかったし、姫は約束通り「生贄」として捕まってしまったけど。"
34130-81 = "……。"
34130-82 = "……それに、私たちは元々ターゲットだった「シャーレ」の先生と一緒に、裏切り者としてアリウスに戻ってるし――本当に笑えない話だね。"
34130-83 = ""
34130-85 = ""
34130-87 = "面白い話をしているな。"
34130-88 = "り、リーダー！？"
34130-89 = "……目が覚めたんだ。体調はどう？"
34130-90 = "動けないほどじゃない……助かった。"
34130-91 = "よ、よかったです……へへ……全部終わってしまったと思ってましたけど……。"
34130-92 = "そう……熱が下がってるなら大丈夫かな。"
34130-93 = "でも、今が正常なコンディションじゃない事を忘れないでね。"
34130-94 = "……それで、これからどうする？"
34130-95 = "今から姫ちゃんを助けるんですよね……？"
34130-96 = "ああ。"
34130-97 = "アリウスのバシリカに向かい、姫を救出する。最初から目標はそれだけだ。"
34130-98 = "……。"
34130-99 = "……。"
34130-100 = "バシリカにはどうやって進入するつもり？#n既に私たちが自治区に潜入してる事は、彼女も知っているよ。"
34130-101 = "ルートは既に考えてある。――アリウス分校の旧校舎に向かう。"
34130-102 = ""
34130-104 = ""
34130-106 = "きゅ、旧校舎ですか？#nあ、あそこは、かなり長い事放置されていた廃墟ですよ……！？"
34130-107 = "そこに何があるの？"
34130-108 = "……姫から聞いた話だが。かつて聖徒会がアリウス分校を建設する時、バシリカと分校をつなぐ地下回廊を作ったのだとか。"
34130-109 = "[s] \"聖徒会がアリウス分校を……？\""
34130-110 = "……うん。その昔――トリニティ連合に反対したアリウスの脱出を支援したのが、ユスティナ聖徒会。"
34130-111 = "アリウスを最も糾弾した彼女らが、アリウスの[ruby=エクソダス]トリニティ自治区外脱出[/ruby]と再建を主導したの。"
34130-112 = "回廊はかなり昔に作られたものだから「彼女」も見落としている可能性が高い。"
34130-113 = "遠回りにはなるが、安全にバシリカまで進入できるはずだ。"
34130-114 = "その回廊の場所は知ってるの？"
34130-115 = "いや……まずは回廊を探すところからだ。"
34130-116 = "そう……。"
34130-117 = "で、でも他に方法はありませんよね？#nそ、それともやっぱり、バシリカに強行突破します……？絶対無理ですけど……。"
34130-118 = "強行突破は無理でしょ。……そうだね。普段ならそんな噂を頼りに探すなんて絶対しないけど、今は先生もいるし……やれるんじゃない？"
34130-119 = "[s] \"うん。とりあえず行ってみよう。\""
34130-120 = "は、はい！"
34130-121 = ""
34130-123 = ""
34130-125 = ""
34130-126 = ""
34130-127 = "旧校舎はここからそう遠くない。目立たないように移動するぞ。"
34130-128 = ""
34130-130 = ""
34130-131 = ""
34130-132 = "了解。"
34130-133 = "出発です！"
34130-134 = ""
34130-136 = ""
34130-140 = "アリウス自治区の某所"
34130-143 = "けほ、けほっ……。"
34130-144 = "うーん……最近ずっと部屋にいたからか、鈍ったなぁ……ロールケーキのせいかも？"
34130-145 = ""
34130-147 = ""
34130-148 = ""
34130-149 = ""
34130-150 = "……まあ、でもとりあえず着いたみたい。"
34130-151 = ""
34130-153 = ""
34130-156 = ""
34130-157 = ""
34130-158 = "な、なんだ！？お前は誰だ！！"
34130-159 = "お、お前は！？"
34130-160 = "あはは、こんにちは☆……そうだ、ちょうどよかった！"
34130-161 = "ねえねえ、アリウスのバシリカってどっち？"
34130-162 = "し、侵入者がここに！早く本隊に連絡を……。"
34130-163 = ""
34130-165 = ""
34130-166 = ""
34130-169 = "ねえ、ダメだよ――夜中に騒いだら迷惑でしょ。そういうの、教わらなかったの？"
34130-171 = "う、撃て！！総員、攻撃！！"
34130-172 = ""
34130-174 = ""
34130-175 = "いったぁ……。"
34130-176 = "まあ、こうなるとは思ってたけどさ。"
34130-177 = ""
34130-179 = ""
34130-180 = ""
34130-183 = "次回;邂逅"
