[translation]
34155-3 = "*Cof, cof*..."
34155-4 = "Haa... guh..."
34155-5 = "Finalmente conseguimos dominá-la..."
34155-6 = "U-Ugh... conseguimos mesmo derrotar ela?"
34155-10 = "Hmm... Isso doeu... Então as coisas ficam mesmo complicadas quando o Sensei está no comando..."
34155-11 = "[s1] \"Mika... a Seia provavelmente está a salvo.\"\n[s2] \"Por isso, volte para a Trinity... Eu não quero machucar você.\""
34155-12 = "Sensei..."
34155-13 = "Sensei..."
34155-14 = "Me desculpe... Eu estou sempre agindo assim, não é..."
34155-15 = "Eu sei muito bem que... uma aluna problemática como eu, que só traz problemas para o Sensei, não pode ficar ao seu lado..."
34155-19 = "Mas... eu..."
34155-21 = "Eu... para mim..."
34155-23 = "Eu não tenho mais um lugar para voltar... Nem na Trinity... nem em lugar nenhum..."
34155-24 = "Eu sou uma traidora da Trinity, e a inimiga de todos...#n――A bruxa que machucou a Seia-chan várias e várias vezes..."
34155-25 = "Se eu for expulsa da academia, eu não vou conseguir ver a Nagi-chan, nem as outras pessoas que são importantes para mim, nunca mais..."
34155-26 = "Se eu não for mais aluna... até mesmo o Sensei, não vai mais querer se encontrar com uma garota problemática como eu..."
34155-27 = "E eu também sei muito bem que não me resta um futuro feliz..."
34155-28 = "A-Afinal, eu sou... uma vilã... uma assassina..."
34155-29 = "É por isso... que [ruby= •  •  •  •  • ]isso[/ruby] é tudo o que me resta..."
34155-30 = "E mesmo assim, vocês... por quê?"
34155-31 = "Eu perdi tudo o que era importante para mim!#n――Tudo, tudo foi tirado de mim!!"
34155-32 = "E vocês... por quê?"
34155-34 = "......"
34155-35 = "......"
34155-36 = "......"
34155-40 = "Como é possível que vocês não paguem nenhum preço, que não tenham nada tomado de vocês..."
34155-41 = "Se eu permitir isso... Eu..."
34155-42 = "Eu... não serei absolutamente ninguém..."
34155-43 = "Não sobrará nenhum sentido para a minha existência..."
34155-44 = "Eu..."
34155-45 = "O que eu devo fazer..."
34155-46 = "......"
34155-47 = "Eu não posso deixar o Esquadrão――a Saori impune..."
34155-48 = "É inadmissível que essa mulher receba a proteção do Sensei sem pagar nenhum preço por isso..."
34155-49 = "......"
34155-50 = "Por isso, Sensei, por favor não me pare."
34155-63 = "[ns] \"Mika!\""
34155-64 = "E-Ela foi embora...?"
34155-65 = "Mas qual é a dessa... mulher."
34155-66 = "Você... me odeia tanto assim, Mika."
34155-67 = "......Mas talvez eu realmente mereça isso."
34155-68 = "O que nós vamos fazer, Líder? É provável que ela continue a nos perseguir... e invadir a Basílica nestas condições talvez seja perigoso."
34155-69 = "O pessoal de Arius, a Sociedade dos Santos... e agora uma perseguidora psicopata... Nós não conseguiremos lidar com todos eles."
34155-70 = "......Nós vamos continuar em frente pelos corredores do antigo prédio escolar e invadir a Basílica."
34155-71 = "Não me importo com o que ela esteja planejando. Vamos... não temos tempo a perder."
34155-75 = "E-Entendido!"
34155-79 = "......Então é isso."
34155-80 = "Vamos, Sensei."
34155-85 = "[ns3] Eu a acompanho.\n[ns4] (Mika...)"
34155-91 = "Próximo Episódio; Corredor Subterrâneo"