[translation]
34180-1 = "第18話;もう一人の私たち"
34180-9 = "こっちだよ、ヒヨリ、ミサキ。#nここに隠れよう。"
34180-10 = "さ、サオリ姉さん……"
34180-11 = "しーっ！静かに。もっと頭を下げて。"
34180-12 = "は、はいぃ……ところで、あの中央にいるのは誰ですか？#nす、す、すごくきれいな服を……き、着てるけど……。"
34180-13 = "私もよく知らない……えらい人なんじゃないかな。"
34180-14 = "お姫様なんだって。高貴な血を引いているとかなんとか。"
34180-15 = "お、お姫様！？お姫様なんですか？"
34180-16 = "よ、世の中にはお姫様もいるんですね？わ、私たちのような底辺とは違って……。"
34180-17 = "飢えたりもしないだろうし……怪我もしないだろうし……#nみ、道端で寝たりもしないですよね……？そうですよね？"
34180-18 = "う、うん……そうなんじゃない？"
34180-19 = "……この世には苦しみしかないと思っていたのに……あんなにきれいで、幸せに過ごせているお姫様もいるんですね……なんだか感動です。うわぁぁぁんー！"
34180-20 = "きゅ、急に泣かないで！バレるでしょ！"
34180-21 = "す、すみませんサオリ姉さん……うわぁぁぁん！#nでも……うわぁぁぁん！"
34180-22 = "……お姫様っていっても私たちと変わらない境遇か、もしかしたらそれ以下の扱いだと思うよ。"
34180-23 = "……？"
34180-24 = "パレードに見えるけど、あれは人質を敵に送る行列だよ。#n内戦中だからなのかな……こんな事もあるんだね。"
34180-25 = "あのお姫様も、きっと監獄で飢えることになる。#n食べ残しをもらえたらラッキーなくらいの生活になるよ。"
34180-26 = "あ、あうう……。"
34180-27 = "やめて、ミサキ。ヒヨリが怖がってるでしょ。"
34180-28 = "……で、どうするのサオリ姉さん？#nここまで来たのに見物だけして帰るつもり？"
34180-29 = "いや、当然襲うよ。#nあの人だかりに紛れ込んで、役立ちそうなものを拝借する。"
34180-30 = "さあ、行こう。"
34180-38 = "やめろ！！"
34180-39 = "どけ、第8分隊長。"
34180-40 = "ヘイローを壊すつもりなのか！？#nやめろ！！"
34180-41 = "ど、どうか……どうか、もうやめてください……うっ、うぅっ……。"
34180-42 = "あいつは我々に抵抗したから当然だ。#n退かなければ、お前らも同じ目に遭うことになるぞ。"
34180-43 = "ゲホ、……ゲホ。#n笑わせないで……だれが……。"
34180-44 = "こいつ、よくも！！"
34180-45 = "待て！！"
34180-46 = "……私が、指導しよう。"
34180-47 = "指導……？"
34180-48 = "……また無駄なことを。"
34180-49 = "ヒヨリも、ミサキも私が指導した生徒だ。姫も同じく――皆、成績が良いだろう？"
34180-50 = "だから、任せてくれ――私が責任を持ってこいつを指導する。"
34180-53 = "……痛い。"
34180-54 = "ミサキ……二度と、二度とそんな事をするな！#n絶対にだ……！！"
34180-55 = "……どうして？"
34180-56 = "なに……？"
34180-57 = "どうしてダメなの？#nなんで、こんな意味のない苦痛の中で生き続けなきゃいけないの？"
34180-58 = "――寒くて、空腹で、辛くて。#nただ苦痛が繰り返される日々なのに。"
34180-59 = "どうして姉さんはこの無意味な苦痛を私たちに強要するの？#nそれに一体何の意味があるの？"
34180-60 = "そ、それは……"
34180-61 = "それ……は……。"
34180-62 = "……ほら、答えられないじゃん。#n何でも知っているフリをして、姉さんだって私たちと同じくせに。"
34180-63 = ""
34180-65 = "……み、ミサキ！待て……。"
34180-66 = "待て！わ、私は……"
34180-68 = "……許してください……申し訳ございません……。"
34180-69 = "二度と……二度とこのような事は……。"
34180-70 = "二度と、大人の言葉を破りません……反抗しません……将来に希望を抱かないよう努めます……。"
34180-71 = "二度と幸福を望みません……祈りません……。"
34180-72 = "だから、どうか……"
34180-74 = "どうか……慈悲を……。"
34180-75 = "慈悲を……。"
34180-77 = "……どうしてそこまで抵抗するんだ、アズサ？"
34180-78 = "和解の象徴……？いや、それは欺瞞にすぎない。#nお前はそんな存在ではない。"
34180-79 = "お前が準備し、勉強してきたことはすべて「その任務」のためだ。"
34180-80 = "だから、諦めて受け入れろ――すべては虚しいだけなのだから。"
34180-81 = "アズサ……？"
34180-82 = "今、何と？#n待て……。"
34180-85 = "ど、どこへ？アズサ！"
34180-86 = "待て！何を……お前はどこに行くんだ？#n私たちはまだ「ここ」にいるのに……。"
34180-87 = "アズサ……"
34180-88 = "お、お前は……知ったのか？#nお前には……その答えが分かっているのか………？"
34180-89 = "教えてくれ、私は……"
34180-90 = "私は一体……どうすれば……"
34180-92 = ""
34180-93 = "……アズサ。"
34180-94 = "……アズサ？"
34180-95 = "……！！#nく、ぐっ……。"
34180-96 = ""
34180-98 = ""
34180-99 = "……う、ぐっ。"
34180-100 = ""
34180-103 = "……その傷じゃ無理だよ、サオリ。"
34180-104 = "……そうか。"
34180-105 = "そうだな……私は負けたのか。"
34180-106 = "……もういい。"
34180-107 = "もう、いい……？"
34180-108 = "……ああ。これ以上もう、何が正しいことなのか分からない。"
34180-109 = "今まで、これが正しいと思って突き進んできた……#nだが、いざ振り返ってみたら、すべてが間違っていた……。"
34180-110 = "……[ruby=しらす]白洲[/ruby]アズサ。"
34180-111 = "……？"
34180-112 = "あなたはアズサちゃんに、何を聞きたかったの？"
34180-113 = "……聞いていたのか。"
34180-114 = "補習授業部のアズサちゃん。#nそもそも私のクーデター計画を手伝うために選ばれたスパイだったでしょ？"
34180-115 = "先生の助けがなければ、ただのコマの一つだったはずなのに……"
34180-116 = "……アズサは。"
34180-117 = "もともと、スパイとして選んだわけではない。"
34180-118 = "……えっ？"
34180-119 = ""
34180-121 = ""
34180-122 = ""
34180-123 = "あの子は……"
34180-124 = "……「和解の象徴」になる予定だった。"
34180-125 = "……。"
34180-126 = "なっ……"
34180-127 = "トリニティとアリウスの……#n最初にその表現を使ったのはお前だったな、ミカ。"
34180-128 = "何言ってるの……それは……#nうん、思い出したよ……先生を騙すために適当に言い繕った……"
34180-129 = "――いや。お前が初めて訪ねてきた時に使った言葉だった。"
34180-130 = "セイアの襲撃が起こる前――そもそもエデン条約も、お前のクーデター計画も、何一つ計画されていなかった頃。"
34180-131 = "……。"
34180-132 = "お前はあの時、アリウスと和解したいと言った。"
34180-133 = ""
34180-134 = "はじめまして☆誰だか知らないけど、あなたがアリウスの生徒だよね……？"
34180-135 = "今日、とてもいい天気だね？すごくのどかで……"
34180-136 = "用件だけ言え、トリニティ。"
34180-137 = "うわぁ……アイスブレイクとか嫌いなんだね。#n……うん、じゃあ仕方なく本題から。"
34180-138 = ""
34180-140 = ""
34180-142 = "――私は、あなた達アリウスと和解したい。"
34180-143 = "和解……？"
34180-144 = "うん。ちょっと過激な主張かもしれないけど、でも……"
34180-145 = "あなた達は多分、まだ私たちを憎んでいるよね？"
34180-146 = "だから私たちの助けも、連邦生徒会の助けも断って、秘匿された自治区で孤立しているんでしょ？過去の憎悪が残っているから。"
34180-147 = "……。"
34180-148 = "でも、これを解決するには……互いの憎悪が大きすぎる……#nそれに、積み重なった誤解も相当だろうし……まぁ、簡単じゃないよね。"
34180-149 = "ナギちゃんも、セイアちゃんも反対するのは当たり前だよ……。"
34180-150 = "でもさ……仲良くするって、そんなに難しいのかな？#nお互いに少しずつ歩み寄れば、いつかは叶うものじゃない？"
34180-151 = "私はそう思うの……だから、少しずつ努力しようと思って、ここに来たの。"
34180-152 = "……その言葉が本心であると、どうやって信じろと？"
34180-153 = "うん……その反応も理解できるよ。#nだから、考えてみたの。"
34180-154 = "あなた達アリウスの生徒1人をトリニティに転校させるのはどうかな？#nもちろん内緒で。"
34180-155 = "私が後見人になれば何とかなるよ。#nこう見えても、私はティーパーティーだからね。"
34180-156 = "……。"
34180-157 = "それで、アリウス生が何の問題もなく、私たちの学園で仲良く過ごしながら幸せになれるということを証明するの。"
34180-159 = "言わばその子が「和解の象徴」になってくれるってこと。#nどうかな？"
34180-160 = ""
34180-162 = ""
34180-163 = "……荒唐無稽な計画だな。"
34180-164 = "で、でも……そんな存在がいたら、きっとセイアちゃんも、ナギちゃんも納得してくれると思うんだ！"
34180-165 = "……。"
34180-166 = "いいだろう。だが、私一人で決められる問題ではない。#n次の連絡を待ってもらうことになる。"
34180-167 = "え？ちょ、ちょっと待って！#nそんな子、本当にいるの？"
34180-168 = "……。"
34180-169 = ""
34180-171 = ""
34180-172 = ""
34180-175 = "アズサ、任務だ。"
34180-176 = ""
34180-179 = "……なに？"
34180-181 = "和解？呆れるほど純真無垢な発想ですね。罠でなければおかしいくらいです。"
34180-182 = "ふむ……まあ、急ぐことはないでしょう。#n無垢なのか、それとも腹黒い蛇なのか、ひとまず見守ることにしましょうか。"
34180-183 = "一旦断ってください。#nそして適度に言いくるめて関係を保ち、トリニティの情報を得なさい。"
34180-184 = "それは断るという……事ですか？"
34180-185 = "もちろんです。和解の象徴？何を寝ぼけているのでしょう。#n彼女は、トリニティの情報を得る道具として利用して差し上げましょう。"
34180-186 = "……。"
34180-187 = "サオリ……何か問題でもありますか？#nまさか私の許可を得ず、何か準備でも？"
34180-188 = "い、いえ……違います、マダム。"
34180-189 = "まさか、忘れてはいませんよね？#nあなた達が苦しんでいる理由を――寒さに震え、飢え続ける理由の根源を？"
34180-190 = "……はい。それはすべて私たちを追放したトリニティのせいです。"
34180-191 = "ええ。仇と和解なんて未来永劫あり得ません。#n――ゆめゆめ、その憎悪を忘れぬように。"
34180-192 = "はい、マダム。#n私は憎悪を忘れません。"
34180-194 = "何故だったのかは私もよく分からない……でもアズサなら……#nあの、アズサなら……。"
34180-195 = "私は……アズサにそんな存在になってほしいと思っていたのだろう……。"
34180-196 = "……。"
34180-197 = "だが、それを確認できる機会は永遠に来なかった……。"
34180-198 = ""
34180-199 = ""
34180-200 = ""
34180-201 = "……セイアちゃんはここにいる。"
34180-202 = "静かに、病院にでも送ってくれれば……。"
34180-203 = "そういうことだから、よろしくね。"
34180-205 = "……。"
34180-206 = "……マダムはその機会を逃さなかった。#nセイアはマダムにとって目障りな存在だったから。"
34180-207 = "お前は私たちを便利な私兵くらいに思ってたのだろう。#nそうでなければ極秘であるセイアの位置を教えるはずがない。"
34180-208 = "だが、私たちはそんな便利な存在なんかじゃない。#n私たちは……。"
34180-210 = "「ヘイローを壊す方法」を学び、訓練し、その道具を持っている………#n人殺し集団だ。"
34180-212 = "「ヘイローを破壊する爆弾」でセイアを殺す任務が私たちに下った。"
34180-216 = "アズサは……和解の象徴となるべくトリニティの多くの知識を持っていたから、その任務に投入されることになった。"
34180-224 = "……ナギちゃんが変なことを企んでる。"
34180-225 = "……。"
34180-226 = "セイアちゃんが死んでしまってから気が抜けちゃったみたい。#nゲヘナと平和条約だなんて、全く。ナギちゃんったら……。"
34180-227 = "だから――そう。この前私が提案した計画を始めてほしいな。"
34180-229 = "トリニティ内部にスパイを送り込むの。#nセイアちゃんの時とは違って、慎重な方法でね。"
34180-231 = "ミカ……"
34180-232 = "私はお前のことが理解できなかった。#n一体何を望んでいるのか、全く見当がつかなかった。"
34180-233 = "ただ単にバカなのかもしれないとも思った……だが、もしも本当にそう思ってくれているのなら……"
34180-234 = "お前から「和解」という言葉を初めて聞いた時も……何の[ruby=うわごと]譫言[/ruby]だと頭では理解しつつも……"
34180-235 = "もしも、「そんな未来」が私たちにあるのなら、と……。"
34180-236 = "そんな考えを、完全に消すことはできなかった……。"
34180-237 = "……。"
34180-238 = "ミカ､お前は……"
34180-239 = ""
34180-241 = ""
34180-242 = ""
34180-243 = "本当に、心から私たちと和解したかったのだろう。"
34180-244 = "……。"
34180-245 = "お前は善意を持って私たちを訪ねてきた。#nそんなお前の心を踏みにじり、騙し、この地獄に導いたのは私だった。"
34180-246 = "そして、お前はこの地獄を受け入れられなかった……だから、自分自身の記憶に蓋して否定した。"
34180-247 = "そう、お前だけじゃなく……。"
34180-248 = "……姫が声と顔を隠して生きなければならなくなったことも、#nヒヨリとミサキをスクワッドに引き込んだことも……"
34180-249 = "「和解の象徴」ではなく、「人殺し」として――皆を欺いて踏みにじらなければならない「スパイ」として、再びトリニティに送られたアズサも……"
34180-250 = "――すべてが私のせいだ。"
34180-251 = "私は……猟犬なんかじゃない。私は……"
34180-252 = "周囲のすべてに苦痛を撒き散らす……疫病神だ。"
34180-253 = "……。"
34180-254 = "アズサに聞きたかったこと、か……#nそう……あったな……。"
34180-255 = "そのすべてを押しつけられたにも関わらず、アズサは……"
34180-256 = "……幸せそうに見えたんだ。"
34180-257 = "誰にも感情を表さず、私たちを最後まで受け入れず、#n孤独を貫いていたあのアズサが……。"
34180-259 = "水底の貝のように固く心を閉ざしていたあの子が……。"
34180-270 = "友達と……大人と一緒に力を合わせて……"
34180-271 = "最後には、苦難を乗り越えて……。"
34180-272 = "晴れやかで幸福に満ちた青空の下に……進んで行った……。"
34180-274 = "いや……そんな事ない。#nあんな……あんなもの嘘だ。偽物だ！"
34180-275 = "いつかは消えてしまう蜃気楼のような幸福だ！"
34180-276 = ""
34180-279 = "[ruby=こうべ]頭[/ruby]を垂れ、祈り縋ったって何も変わらない！"
34180-280 = "アズサ、私たちは結局幸せになどなれない。#nよくわかっているだろう？――すべては虚しいものだということを。"
34180-282 = "しかし……結局、認めざるを得なかった……。"
34180-285 = "ああ……そうか。"
34180-286 = "私たちの憎悪も……「すべては虚しいもの」という言葉も……#nやってきたすべてが……"
34180-287 = "――全部、嘘だったんだ……。"
34180-288 = "[ruby=ぐどん]愚鈍[/ruby]で[ruby=だじゃく]惰弱[/ruby]だった私は……疫病神のように周囲を破滅に追い込んだんだ……。"
34180-290 = ""
34180-299 = "――嗚呼、結局そういう事だったんだな。#n全て、私が原因だった。"
34180-300 = "アズサは私から離れられたから幸せになれたんだ。"
34180-301 = "私は、その真実を最後まで否定したかったのだろう……。"
34180-303 = "アズサ、お前なら……正解が分かるのか？"
34180-304 = "アズサ……私は……。"
34180-305 = "――幸せに、なれるだろうか？"
34180-306 = "どうすれば、私もお前のようになれるのだろうか。#nそんな機会は存在するのだろうか？私が、そんなことを願ってもいいのだろうか……？"
34180-307 = "もし……私が……。"
34180-310 = "……いい大人に、もう少し早く出会えていたら……。"
34180-311 = "こんな私にも……他の人生があったのだろうか……。"
34180-312 = "こんな悲惨な結末ではなく、他の未来を迎えられたのだろうか……。"
34180-313 = "私にも……そんな……機会が……。"
34180-314 = "アズサ……お前はあの時……何と言っていたんだ？"
34180-315 = "私は……それを……"
34180-316 = ""
34180-319 = "……ミカ。"
34180-320 = "もう、この有様だ。#n――好きにするといい。お前が奪われた分だけ、奪うといい。"
34180-321 = "優しい心を持っていたお前を……憎悪の「魔女」にしてしまったのは、#n他でもない私なのだから。"
34180-322 = "私は他人からたくさん奪ってきた……これで少なくとも公平になるだろう……。"
34180-323 = ""
34180-326 = ""
34180-327 = ""
34180-329 = ""
34180-330 = ""
34180-332 = "ああ……この役目が来るとしたら、アズサだと思っていたのだが……#nお前だったんだな、ミカ。"
34180-333 = ""
34180-337 = ""
34180-339 = ""
34180-340 = "……？"
34180-341 = "……わ、私は……"
34180-342 = "私には……できない。"
34180-343 = "そんなこと、できない……#nだって……"
34180-344 = "私も……"
34180-345 = "あなたみたいに、そんな機会を望んでいたの……"
34180-346 = "私も……幸せになりたかった……。"
34180-347 = "私も、あなたのように……先生にもう少し早く会っていたら。#nそうしたら……過ちを取り返せたのかな……って思ってた……。"
34180-348 = ""
34180-349 = ""
34180-350 = ""
34180-351 = ""
34180-352 = "これは当然の罰だと受け入れていた……#nでも、やっぱり慈悲がほしいと、数えきれないほど祈った。"
34180-353 = "でも……無駄だったの。"
34180-354 = "私が犯した取り返しのつかないことの数々を、#nどうすれば許されるのか、全然わからない……。"
34180-355 = "二度目のチャンスが……"
34180-356 = "先生やみんなが私のために集まってくれて……やり直すことができる。#nそんなチャンスが、私にもあるって信じてた……でもなかった……そんな未来はなかったの……。"
34180-357 = "すべてが虚しいことばかりのこの世界で、ただ救いを願って苦しむだけだった……。"
34180-359 = "あなたは……私だよ、サオリ……。"
34180-360 = "あなたは幸せになれない。#n私が幸せになれないのと同じように。"
34180-361 = "そんなの無理だよ。もう取り返しがつかなくなってしまった私たちに、二度目のチャンスなんてあるはずがない。"
34180-363 = "だから、私はあなたに「公平」な痛みを願っていたのかもしれない……。"
34180-364 = "でも、だからこそ……私にはできない……。"
34180-365 = "私が、あなたの結末をこんな風に決めてしまったら……。"
34180-366 = "私に救いなどないと、自ら証明する事になってしまう……。"
34180-367 = ""
34180-369 = ""
34180-370 = ""
34180-371 = "ミカ……お前は……。"
34180-372 = "ねえ、どうして「ヘイローを壊す爆弾」を使わなかったの？"
34180-373 = "……！！"
34180-374 = "あなたが持っているって聞いたよ……使うチャンスは十分あったじゃない？#nどうして使わなかったの？"
34180-375 = "それを使ってくれていたら……私は……。"
34180-376 = "それは……そもそも私は持っていない。"
34180-377 = "先生に、没収されたから……。"
34180-378 = "……え？"
34180-379 = "……没収？先生に？"
34180-380 = "え、どうして……？"
34180-381 = ""
34180-383 = ""
34180-384 = ""
34180-385 = "[ns] \"危険なものは先生が没収するよ。\""
34180-386 = "！？"
34180-387 = "せ、先生……！？"
34180-388 = "せ、先生……ど、どうしてここに……！？"
34180-390 = "次回;無限の可能性"
