[translation]
34225-3 = "Guh, ah…… não pode ser……!!#nMinha autoridade está……!!"
34225-4 = "Não pode ser…… será que o ritual ainda não foi concluído……?#nO poder ainda…… ah……"
34225-5 = "Como se…… como se eu fosse perder para alguém como vocês……!!"
34225-6 = "Barbara…… não, tragam todas as forças militares presentes na Basílica para cá……!!"
34225-7 = "Voltem para cá agora!"
34225-12 = "Haa…… guh……."
34225-13 = "Ai, ainda estão vindo……?#nUwaa……."
34225-14 = "Guh…… não aguento mais……."
34225-15 = "Mantenha a calma! Ainda não acabou!!"
34225-16 = "Antes que o reforço chegue, rápido……!!"
34225-17 = "――Soldados da Basílica, protejam-me!!"
34225-19 = "Próximo episódio: Kyrie pelas garotas (1)"
