[translation]
34240-1 = "Episódio 24; Kyrie para as garotas (2)"
34240-2 = "……."
34240-3 = "……Por que você não vem……?"
34240-4 = "E Barbara?#nPor que ninguém ainda……"
34240-9 = "……！！"
34240-14 = "Essa música……."
34240-15 = "Isso é…… Kyrie eleison……?"
34240-16 = "[s] \"Mika……!\""
34240-18 = "Não permitirei!!!"
34240-19 = "Não permitirei! Que uma música que fala de misericórdia ecoe no meu território!"
34240-20 = "Que tipo de método você usou……?"
34240-21 = "Mesmo tendo destruído todos os instrumentos e fonógrafos!――Acha que um milagre aconteceu?"
34240-22 = "Não permitirei!!#nOs alunos devem cantar sobre ódio, desprezo…… e maldições!"
34240-23 = "Eles deveriam ser seres explorados por nós, dentro deste inferno onde enganam e ferem uns aos outros!"
34240-27 = "[ns] \"Cale a boca.\""
34240-29 = "……O quê!?"
34240-30 = "[s] \"Não fale com a minha preciosa aluna.\""
34240-31 = "……!!!"
34240-32 = "[s1] \"Você jogou as crianças no abismo com ensinamentos falsos.\"\n[s2] \"Eu nunca vou te perdoar.\""
34240-33 = "C-como ousa me dizer tal coisa……"
34240-34 = "C-como ousa me dizer tal coisa……"
34240-38 = "Essas palavras――!!"
34240-43 = "E-está começando a mudar de novo……!?"
34240-45 = "Ah, é isso, Saori――"
34240-46 = "Vou oferecer você como o novo sacrifício!"
34240-48 = "……!!"
34240-49 = "Já que você arruinou meus planos, você pagará o preço por isso!!"
34240-53 = "――Pode levar o quanto quiser, Madame."
34240-55 = "L-Líder!?"
34240-56 = "……Que tipo de besteira você está dizendo!?"
34240-58 = "Se ainda existe um preço que eu possa pagar…… eu até agradeceria."
34240-62 = "Vamos, Madame.#nEu estou aqui!! Pode levar!"
34240-64 = "Droga, Sensei……! Rápido……!"
34240-66 = "[ns] \"É a batalha final! Vamos, pessoal!\""
34240-67 = "S-sim!!"
34240-69 = "Argh, ……Ah, AAAAAA!"
