[translation]
41070-1 = "第7話;ニンジン作戦（１）"
41070-2 = "（数日後、みんなが無事に過ごせているかを確認するため再び公園を訪れていた）"
41070-3 = ""
41070-5 = "子ウサギ公園前"
41070-8 = "モエ、どうしてお前が焼肉弁当を持っていくんだ！？"
41070-9 = "どうしても何も、私が持ってきたんだから文句ないでしょ！"
41070-10 = "お前は昨日しょうが焼き弁当を食べただろ！今日はおとなしく、もやし弁当でも食ってろ！"
41070-11 = "知るか、サキがもやし食べれば良いじゃん！"
41070-12 = ""
41070-15 = "じゃあ、私はこのソーセージ弁当を……。"
41070-17 = ""
41070-18 = "ダメ！！"
41070-20 = ""
41070-22 = ""
41070-23 = "みんな、落ち着いてください。SRTが食べ物を巡って喧嘩なんて、みっともないですよ。"
41070-24 = "何の保証もないこの状況で、質を争うのはナンセンスです。今はお腹が満たされるだけで良いとしましょう。"
41070-25 = "じゃあミヤコはどれにするんだよ。"
41070-26 = "私は、"
41070-27 = "この唐揚げ弁当で。"
41070-28 = "一番高いやつじゃんか！！！"
41070-29 = "[s] \"や、色々と大丈夫そう？\""
41070-30 = ""
41070-32 = ""
41070-33 = "………。"
41070-35 = "よりによってこのタイミングで……。"
41070-36 = "いえその、これは、お弁当で喧嘩していたわけではなく……。"
41070-37 = "ああ、仲良くお昼ご飯の話をしてただけだ。"
41070-38 = "[s1] \"仲良く……？\"\n[s2] \"喧嘩してないなら良かったけど……。\""
41070-39 = "喧嘩に見えたなら、目でも洗ってきた方が良い。"
41070-40 = "喧嘩に見えたなら、目でも洗ってきた方が良い。"
41070-41 = "私たちは至って正当な協議をしてただけ。"
41070-42 = "その結果がどうであれ、同じ訓練を共にした身としてその時は……"
41070-43 = "じゃあ、焼肉弁当は譲ってもらおっと。"
41070-44 = "まだ協議中だろ！良いから一旦置け！！"
41070-45 = ""
41070-47 = ""
41070-49 = ""
41070-50 = "……恥ずかしいところをお見せしました。"
41070-51 = "ですが、はい。特に問題があるわけではありません。"
41070-52 = "食料の面も、まあ……。"
41070-54 = "例の廃棄弁当で、当面の解決はできましたし。"
41070-55 = "ふふっ、先生はそれで屈辱を与えて心を折ろうとしたのかもしれないけど、そうは行かないよ。私たちはそんなの全然気にしないから。"
41070-57 = "作戦のためなら、私たちは何だってやる。"
41070-58 = "もう先生がいなくたって、私たちはこのまま……！"
41070-59 = "[s] \"でも、顔色が悪い気が……。\""
41070-61 = "[s] \"大丈夫？具合悪い？\""
41070-62 = ""
41070-64 = ""
41070-65 = ""
41070-67 = "ま、待て！近寄るな！"
41070-68 = ""
41070-70 = ""
41070-71 = "それ以上近づいたら本気で殴るぞ！？"
41070-72 = "[s] \"え、えぇ……？\""
41070-74 = "それは、まあ……"
41070-75 = ""
41070-77 = ""
41070-79 = ""
41070-81 = "さり気なく近づかないでください。足を狙いますよ。"
41070-82 = "[s] \"そ、そんな……。\""
41070-84 = "だって、匂いが……。"
41070-85 = "[s3] \"……匂い？\"\n[s4] \"ここに来る前に、シャワーは浴びてきたけど……？\""
41070-88 = "いやだから、そうじゃなくて……！"
41070-89 = "[s5] \"最近湯船に入ってないからかな……。\"\n[s6] \"それは生徒に避けられるのも仕方ない……。\""
41070-92 = "そうじゃなくて！問題は私たちの方だよ！"
41070-94 = "あーあ、言っちゃった……。"
41070-95 = "し、仕方ないだろ！もう4日もシャワー浴びてないんだから！"
41070-96 = "[s] \"ご、ごめん……じゃあ銭湯に行くとかは……？\""
41070-98 = "食料を買うお金も無いのに、銭湯に行く余裕があると思うのか？"
41070-99 = "洗顔くらいでしたら、公園の水で何とかなるのですが……。"
41070-100 = "作戦中は汗をかいても気にしませんが、長期戦となると衛生面的に……。"
41070-101 = "[s] \"シャーレのシャワー室、使っても大丈夫だよ？\""
41070-102 = ""
41070-104 = ""
41070-105 = "……最っ低。"
41070-106 = "……度し難いです。"
41070-107 = "わ、私たちが武装を解除した瞬間に、何を……！？"
41070-109 = "シャワーを浴びさせてその隙に何しようっての？もしかして実物より残滓の方が好み？ひゅーっ！！"
41070-110 = "[s] \"私は一体なんだと思われて……。\""
41070-112 = "信頼できない大人。"
41070-113 = "変質者。"
41070-114 = "燃えないゴミみたいな……。"
41070-115 = "別に、何も……。"
41070-116 = "[s] \"そっかぁ……。\""
41070-118 = "とにかく、それはそれで解決策を考えますが、しばらく先生はこの公園に近寄らないでください。"
41070-119 = "とはいえ、解決策も何も……。"
41070-120 = "外で水を被ったら、それこそ風邪を引くだろうし……。"
41070-122 = "……トイレの貯水槽に、ミサイルでも撃ち込む？"
41070-123 = "余計に汚れると思うけど……。"
41070-124 = "[s] \"キャンプでお風呂なら、ドラム缶とか……？\""
41070-126 = "……ドラム缶？"
41070-127 = "ああ、下から火を焚くのか。"
41070-128 = "以前、百鬼夜行連合学院で似たようなものを見た気がします。"
41070-130 = "それ、どうやって身体を洗うんだろうね？"
41070-131 = "っていうかセンスが古い。"
41070-132 = "それは同感、まあ先生なら仕方ないか？"
41070-134 = "……ですが、"
41070-135 = "それくらいしか方法は無いかもしれません。"
41070-136 = "きちんとした設備は準備できませんし……。"
41070-137 = ""
41070-139 = ""
41070-140 = ""
41070-141 = "モエ。資源管理システムに接続して、ドラム缶を使ってる現場を探してくれませんか？"
41070-142 = "それが見つかったら、すぐに出動しましょう。"
41070-143 = "出動って、つまり……"
41070-144 = "衛生面は、部隊の存続に直結する重要な問題です。どんな手を使ってでも、できるだけ早期に解決しなければなりません。"
41070-145 = "では今から、浴槽の確保……"
41070-147 = "「ニンジン作戦」を開始します！"
41070-149 = "次回;ニンジン作戦（２）"
