[translation]
41080-1 = "Episódio 8: Operação Cenoura (2)"
41080-2 = "Porto de D.U."
41080-6 = "Aqui RABBIT1, horário 21:00. Chegamos ao Ponto Delta."
41080-7 = "Sem problemas até agora. Seguiremos para o Ponto Echo, onde está a 'Cenoura'."
41080-8 = "Aqui Acampamento RABBIT, confirmando sinais de GPS de todas."
41080-9 = "Verifiquei os turnos da empresa de segurança, nenhuma alteração significativa."
41080-10 = "Bem, no Ponto Echo não deve ter problema."
41080-11 = "[s] \"Posso dizer uma coisa?\""
41080-12 = "……O que foi, Professor?"
41080-13 = "Se veio só para dar bronca, pode voltar."
41080-14 = "Palavras desnecessárias atrapalham a operação."
41080-15 = "[s] \"Estou preocupado…\""
41080-16 = "……O senhor acha que vamos roubar?"
41080-17 = "Nós somos a SRT. Não roubamos propriedade alheia."
41080-18 = "Os tambores aqui estão programados para descarte. Ou seja, não causaremos prejuízo financeiro a ninguém."
41080-19 = "Na verdade, as empresas até economizariam nos custos de descarte."
41080-20 = "[s] \"Então, por que não pedir educadamente?\""
41080-21 = "Isso é…"
41080-22 = "É uma questão de orgulho."
41080-23 = "Não podemos depender da piedade alheia!"
41080-24 = "[s] \"Hmm, entendo…\""
41080-25 = "B-Bem, aqueles bentôs do outro dia…"
41080-26 = "Aquilo foi uma 'apreensão' nossa."
41080-27 = "Pode deixar!"
41080-28 = "Pelo nosso orgulho, jamais…!"
41080-29 = "RABBIT2, se acalme. Estamos em operação."
41080-30 = "Está quase na hora. Por favor, faça o reconhecimento antes da invasão."
41080-31 = "Aliás, Miyako, por que você está dando ordens?"
41080-32 = "……RABBIT2, use o codinome em operação."
41080-33 = "Tsc, isso é verdade…"
41080-34 = "Mas o que eu quero saber é por que você está no comando."
41080-35 = "Porque eu sou a comandante…"
41080-36 = "Só porque os superiores mandaram, né?"
41080-37 = "Os mesmos superiores do Conselho que fecharam a SRT."
41080-38 = "……"
41080-39 = "Mas agora, nessa situação, qualquer um pode comandar."
41080-43 = "…O que vocês acham?"
41080-45 = "Para mim, tanto faz. No fundo, não muda nada."
41080-46 = "Eu… ahm…"
41080-48 = "……Entendido."
41080-49 = "Então, o comando desta operação fica com você."
41080-50 = "Por favor, assuma, RABBIT2."
41080-51 = "Hmph. Afinal, o inimigo é só segurança comum… fichinha."
41080-52 = "Treinamos esse tipo de situação exaustivamente. Até de olhos fechados."
41080-54 = "Ahm, Saki-chan…"
41080-55 = "Quer dizer, RABBIT2. Onde devo ficar?"
41080-56 = "Hã? Ahm…"
41080-57 = "E-espera. Posição do atirador em combate urbano… estava no caderno…"
41080-64 = "Ugh, bebi demais… banheiro…"
41080-66 = "…Alguém se aproximando!"
41080-67 = "Hã?! Não era para virem por essa rota!"
41080-68 = "Ah, não… por quê? Não sei! Imprevisto!"
41080-69 = "S-Saki-chan! O que fazemos?!"
41080-70 = "F-Fugir, pode?!"
41080-71 = "Isso… ahm…"
41080-72 = "Lugar alto! Vá para um lugar alto!"
41080-73 = "O básico do tiro é 'campo de visão'. Subindo, provavelmente…"
41080-75 = "Espere, Saki. Mesmo que o guindaste seja bom para atirar, na fuga…"
41080-76 = "Eu sei disso!"
41080-77 = "Hã? O que foi esse barulho…?"
41080-85 = "O quê, intrusos?!"
41080-86 = "Vieram roubar, seus ladrões de merda!"
41080-87 = "Quem é ladrão?!"
41080-91 = "Ah, que inferno, combate iniciado! Dê tudo de si e sigam para o Ponto Echo!"