[translation]
41130-1 = "Episódio 13;Inarizushi"
41130-2 = "（Decidi passar na Vila dos Coelhinhos pra procurar algo pra comer antes de ir checar o parque.）"
41130-4 = "Arredores do Parque dos Coelhinhos - Vila dos Coelhinhos"
41130-6 = "（……Mas, estranhamente, todas as lojas e barracas estavam com as portas fechadas.）"
41130-9 = "Deliciosos, quentinhos e docinhos! Alguém quer provar um Inarizushi~?"
41130-10 = "Ah, você aí! O moço com cara de quem tá precisando de um agrado! Se ainda não comeu, que tal provar um dos meus?"
41130-11 = "Eu garanto que o recheio de hoje tá no ponto perfeito, molhadinho e suculento!"
41130-12 = "E acabei de tirar do fogo! Eles tão pelando de quentes, é a melhor hora pra colocar na boca~!"
41130-13 = "[s] \"Já que você insiste tanto…… vou querer um.\""
41130-15 = "Muito obrigada, moço bonito!"
41130-16 = "Aiai, eu tava quase perdendo as esperanças hoje…… Ninguém passou por aqui. Cheguei a pensar que eu ia ter que comer tudo sozinha de noite, me deu até um frio na barriga."
41130-17 = "E seria um desperdício enorme jogar tanta coisa gostosa fora, não acha?"
41130-18 = "[s] \"Mas também como é que pode? as ruas tão desertas. As outras lojas tão todas de portas fechadas……\""
41130-19 = "Ah, isso? É que a reurbanização violenta dessa área tá prestes a começar. O pessoal tá com medo de ficar no meio do fogo cruzado."
41130-23 = "Ué, pela sua cara, parece que o senhor não sabia dessa novidade quentinha……?"
41130-24 = "Os boatos dizem que os engravatados vão construir uma nova linha de metrô bem aqui debaixo de nós."
41130-25 = "Vão demolir o centro comercial, rasgar o chão pra passar os trilhos e construir um shopping chique em cima dos escombros."
41130-26 = "Como era o nome da empresa mesmo……? Tinha um polvo ou algo assim no logotipo……"
41130-27 = "[s] \"……Kaiser Group?\""
41130-28 = "Isso, isso! Kaiser Construction, acho que era esse o braço deles!"
41130-29 = "Parece que eles tão apostando a alma da empresa nesse projeto massivo."
41130-30 = "Por causa disso, os comerciantes foram \"convidados\" a fechar as portas, e os moradores tão sendo expulsos das próprias casas no calar da noite……"
41130-31 = "Mas, bom, pra uma aluna que vive de bicos que nem eu, essas brigas de cachorro grande tão muito longe da minha realidade. Fufu~……"
41130-35 = "[ns] (Compro mais um Inarizushi pra dar uma moral pra ela.)"
41130-36 = "Ara, o sabor te agradou tanto assim pra querer repetir?"
41130-37 = "Fico lisonjeada. Modéstia à parte, eu tenho muita confiança na habilidade dos meus dedos pra montar esses Inarizushis."
41130-38 = "Minhas cole-- quer dizer, minhas amigas e calouras sempre ficavam babando por eles."
41130-42 = "……Nossa, como eu falo demais, acabei desviando do assunto principal, né?"
41130-43 = "Deixa eu ver……"
41130-44 = "Já que o senhor comprou tantos, vou te dar um bônus especial. Um segredinho bem suculento."
41130-45 = "Sabe a tal da reurbanização da \"Kaiser Construction\" que eu comentei……?"
41130-46 = "Tem um boato correndo por aí de que ela pode ir pro buraco e ser cancelada."
41130-47 = "[s] \"E por que uma empresa gigante recuaria assim?\""
41130-48 = "Lembra que eu falei sobre uns moradores sendo expulsos? Tem um grupo de mendigos rebeldes entocados aqui."
41130-49 = "E eles tão com um arsenal que faria muita escola passar vergonha. Toda vez que a Kaiser tenta avançar as obras, rola tiroteio. A agenda deles tá indo pro ralo."
41130-50 = "Pra piorar o clima, parece que um grupo de garotas armadas e perigosas invadiu e tomou o parque aqui do lado. A Valkyrie tá de mãos atadas porque elas são muito duras na queda."
41130-51 = "Com esse fogo cruzado de todos os lados, a Kaiser tá encurralada…… Entende o tamanho do buraco?"
41130-52 = "[s] \"Essas garotas no parque……\""
41130-53 = "Ara~ O jeito que você arregalou os olhos…… por acaso vocês já tiveram algum…… \"contato íntimo\"?"
41130-54 = "Você já deve ter percebido, eu adoro uma boa fofoca. Especialmente as mais picantes."
41130-61 = "Eu te dou mais um Inarizushi de graça se você abrir o bico e me contar tudo o que sabe sobre os corpos…… digo, sobre elas."
41130-62 = "[s1] \"Não tenho nada de interessante pra te contar……\"\n[s2] \"Desculpa, mas a gente não tem esse nível de intimidade.\""
41130-63 = "……Entendo. Que desperdício de um bom homem."
41130-64 = "……Entendo. Que desperdício de um bom homem."
41130-65 = "Mas, olha…… tem mais um boato……"
41130-66 = "Dizem que essas garotas do parque não são amadoras, mas sim a nata de uma academia de elite."
41130-67 = "Se for verdade, não é surpresa a Valkyrie abaixar a cabeça pra elas. Elas devem ter um arsenal que destrói quarteirões."
41130-68 = "O que não entra na minha cabeça é o motivo de garotas tão finas e de elite estarem chafurdando na lama de um parque público abandonado……"
41130-69 = "Na minha humilde opinião, ou elas tão acobertando alguma sujeira muito grande…… ou cometeram um erro tão fatal que não podem mais voltar a dormir numa cama quente."
41130-70 = "Ou talvez…… elas ainda acreditem em contos de fadas."
41130-71 = "Aquele tipo de sonho doce, fofo e inatingível que só flores cultivadas em estufas, que não conhecem a crueldade do mundo, conseguem sonhar."
41130-72 = "Lidar com o fardo de meninas mimadas imersas nesses delírios febris deve ser um verdadeiro inferno pro coitado que cuida delas, não acha?"
41130-73 = "[s] \"Acho que você tá olhando pelo ângulo errado.\""
41130-74 = "……Ah, é?"
41130-75 = "E qual seria o \"ângulo certo\", moço sábio?"
41130-76 = "[s] \"Sonhar não é pecado. E proteger os sonhos dos meus alunos é o mínimo que eu posso fazer como professor.\""
41130-80 = "……Você é um cara bem esquisito."
41130-81 = "Mas, suponho que homens românticos também tenham o seu charme."
41130-85 = "Bom, acho que vou abaixar as portas por hoje. Obrigada por comprar tudo, bonitão!"
41130-89 = "[ns] \"……O que é isso?\""
41130-90 = "A xepa."
41130-91 = "Eu não aguento comer tudo isso sozinha…… Pensa nisso como um brinde pelo papo gostoso."
41130-92 = "Se você quiser……"
41130-93 = "Pode dar pras suas garotinhas famintas lamberem os beiços."
41130-94 = "Foi um prazer bater papo com você hoje."
41130-95 = "Quem sabe a gente não tromba de novo no escuro por aí…… Sensei~"
41130-100 = "Parque dos Coelhinhos"
41130-103 = "P-Parado aí!! Não se mexe senão eu atiro bem nos seus joelhos……!"
41130-107 = "……Miyu, quantas vezes eu já falei pra abrir o olho e checar a mira antes de ameaçar as pernas de alguém?"
41130-108 = "Baixa a arma, é só o tarado do Sensei."
41130-109 = "A-Ah…… D-Desculpe……!"
41130-111 = "Saco, é só você."
41130-112 = "Eu vi esse vulto andando todo esquisito no mato, achei que fosse um cachorro tarado."
41130-113 = "[s] \"Como é que é……?\""
41130-114 = "E o que você quer aqui hoje? Veio espiar a gente tirando a lama do corpo?"
41130-115 = "Hã? Pera…… que cheirinho é esse……"
41130-119 = "[ns] (Estendo a sacola com os Inarizushis.)"
41130-120 = "Caramba, Inarizushi?! Isso parece bom pra caramba!!"
41130-121 = "Faz séculos que eu não sinto o cheiro disso…… Bateu até nostalgia da SRT……"
41130-122 = "P-Pera aí…… você comprou isso…… pra nós?"
41130-123 = "[s3] \"Sim, podem devorar tudo.\"\n[s4] \"Err…… quer dizer…… eu \"taticamente encontrei\" isso no caminho pra cá……\""
41130-124 = "Hummm……"
41130-125 = "Saki, você é a cobaia. Morde primeiro. Pode ter algum afrodisíaco ou sonífero no meio."
41130-126 = "[s5] \"T-Tá limpo! Eu juro, já comi um no caminho e não desmaiei!\""
41130-127 = "E-Eu devia imaginar…… Pensei que o senhor tivesse realmente tentado comprar o nosso afeto, mas o senhor só achou no chão mesmo……"
41130-128 = "O cheiro tá bom, mas será que não tá podre?"
41130-132 = "Se o meu faro não falha, tá fresquinho……"
41130-135 = "Peraí, esse tempero……"
41130-136 = "Esse gosto doce…… Tinha umas veteranas na SRT que eram loucas por Inarizushi com esse exato mesmo sabor."
41130-137 = "Onde será que as nossas veteranas da elite devem estar se escondendo agora……?"
41130-141 = "……Bom, cavalo dado não se olha os dentes. Vamos meter pra dentro."
41130-143 = "（Enquanto elas devoravam os Inarizushis como se não houvesse amanhã, aproveitei para atualizar o Esquadrão sobre os últimos acont ecimentos.）"
41130-147 = "……Resumindo. A gente foi abandonada pelo Conselho Estudantil Geral e a Kaiser Construction logo vai mandar o rolo compressor em cima do nosso parque."
41130-148 = "Eu já não esperava que os engravatados fossem mover um dedo por nós, mas o cerco tá se fechando rápido demais."
41130-149 = "Ainda mais com o nosso equipamento no osso depois daquele dilúvio……"
41130-151 = "Pff, moleza. A gente engole perrengue no café da manhã."
41130-152 = "Se acabar a bala, eu mordo a jugular desses operários da Kaiser!"
41130-153 = "A Saki tá maluca…… é o nosso fim……"
41130-154 = "A gente não tem arma, não tem abrigo, não tem apoio…… e os inimigos só aumentam……"
41130-155 = "No fim dessa história…… a gente vai ser encurralada……"
41130-156 = "Vamos ser vendidas pro Mercado Negro e forçadas a usar fantasias vergonhosas pra agradar ricaços esquisitos num porão escuro…… Que terror……!!"
41130-157 = "Miyu, acho que sua imaginação suja foi longe demais. Nós ainda temos o…… Sensei, né."
41130-158 = "Mas parando de delírios, a nossa falta de poder de fogo é letal. Se batermos de frente com a Segurança Pública hoje, nós vamos virar peneira."
41130-159 = "Se a gente pelo menos tivesse peças pra consertar as metralhadoras e as torretas automáticas do perímetro…… Mas não temos nada."
41130-161 = "Kuhihi…… Esquadrão, cês tão esquecendo de alguém?"
41130-169 = "Se o problema é arma pesada e peça de reposição…… podem deixar comigo! Eu faço chover chumbo!"
41130-171 = "Próximo Episódio;Escambo Bélico"