[translation]
41140-1 = "第14話;物々交換"
41140-2 = "モエ、何か良い方法でもあるのですか？"
41140-3 = "で、でも今の私たちには、お金も口座も……。"
41140-4 = "……っていうか一番最初に、派手に弾薬を消費したのはお前だけどな。"
41140-6 = "いやいやいや、だからあれはあれで必要なタイミングだったんだって！"
41140-7 = "とにかく、別にお金が無いからって補充ができないわけじゃない。"
41140-8 = "[s] \"まさか銀行を……。\""
41140-9 = "はぁ？何を言ってるんだ？"
41140-10 = "市民の安全を守るべきSRTが、銀行強盗なんてするわけがありません。"
41140-11 = "そんな頭おかしい発想しないって、"
41140-12 = "私が言いたいのは……。"
41140-14 = "ズバリ、物々交換！"
41140-15 = "ま、ある意味原点というか、古典的な取引方法だけど。"
41140-16 = "私たちが持っている貴重な物を渡して、その対価として武器やら弾薬やらを貰うってわけ！"
41140-18 = "「私たちが持っている貴重な物」と言えば……。"
41140-19 = "……焼肉弁当？賞味期限、切れてるけど……。"
41140-20 = "そんなの誰も買わないでしょ。強いて言えばあの「所確幸」くらいで。"
41140-21 = "そうじゃなくて、あの大量のミサイルやら爆弾やらだよ。"
41140-22 = "水に浸かってダメになったとはいえ、それだけで価値がゼロになったわけじゃない。"
41140-23 = "断腸の思いではあるけど、もっと良い持ち主のところに行った方が良いだろうし。"
41140-24 = "[s] \"なるほど……？\""
41140-26 = "ですが、買い取ってくれるのでしょうか？元は高価なものとはいえ、ほとんど故障状態か、さびてしまった状態で……。"
41140-27 = "ま、その辺については任せてよ。伝手があるからさ。"
41140-28 = "例えば、そうだなあ……。"
41140-29 = "ブラックマーケットで武器を扱う「カイザーインダストリー」。あそこには傭兵たちからの、中古の武器に関する需要が絶えない。"
41140-30 = "あそこならこういう錆びたミサイルでも、何かしらの使い道を見出してくれる人がいるでしょ。"
41140-31 = "その分の代わりとして、カイザーグループのそこそこ良い品質の武器を貰えば良いってわけ！"
41140-32 = "へえ、モエにしてはまともな発想じゃん。"
41140-33 = "体調はいつも通りか？もしかして昨日のナポリタン弁当で、食あたりとか？"
41140-34 = "うるさいなぁ！？"
41140-35 = ""
41140-37 = ""
41140-38 = "まあとにかく、営業所に電話してみよう。"
41140-39 = ""
41140-41 = ""
41140-44 = ""
41140-45 = "はい、こちら最高品質の武器をご提供する「カイザーインダストリー」でございます。どういったご用件でしょうか？"
41140-46 = "やあやあ、久しぶり！"
41140-47 = "私だよ、私。前にも色々買わせてもらった、SRT特殊学園の補給担当。"
41140-48 = "あ、あの時のVVIPの……！？"
41140-49 = "ご無沙汰しております！"
41140-50 = "今回も新しいミサイルがご入用でしょうか？"
41140-51 = "それとも以前ご購入されたクラスター爆弾にも、何か問題でも……？"
41140-52 = "……モエ、いつそんな買い物をしたのですか？"
41140-53 = "や、その、別に学園のお金じゃないし？"
41140-54 = "あくまで私用の爆弾！自費だから問題無し！"
41140-55 = "[s] \"「私用の爆弾」って何……？\""
41140-56 = "と、とにかく……"
41140-57 = "今日は買う方じゃなくて、売る方で連絡したの。"
41140-58 = "売る方……ですか？当店では基本、買い取りの方は……。"
41140-59 = "とはいえ、何も聞かずに断るわけにもいきませんね。まずはお話をお伺いしてもよろしいでしょうか？"
41140-60 = "それがねー、実はコンビニでは手に入らないような高級装備が色々手元にあってさ。"
41140-61 = "誘導式対空ミサイルに、威力が調節可能なクラスターグレネードに、遠隔操作が可能なタイプの対戦車ロケット……。"
41140-62 = "な、何と……それらを売ってくださるのですか？"
41140-63 = "うん、まあ若干錆びてたりするんだけど……多分大丈夫でしょ。"
41140-64 = "[s] \"……若干？\""
41140-65 = "（先生、シャラップ！！）"
41140-66 = "そういった特殊なものでしたら、需要は幾らでもあると思いますし……。"
41140-67 = "はい、喜んでお受けいたしましょう。"
41140-68 = "ちなみに代金については、以前と同じ口座振り込みでよろしいでしょうか？"
41140-69 = "あー、実はちょっとその口座使えなくなってて……。"
41140-70 = "代金の代わりに、現物でっていうのはどう？"
41140-71 = "現物……と言いますと？"
41140-72 = "ちょっと安めのやつで良いからさ、威力の高い武器が欲しいんだよね。"
41140-73 = "気化爆弾とか、白リン弾とか……はあ、はあ……！"
41140-74 = ""
41140-76 = ""
41140-77 = "じ、実は大変申し訳ないのですが……只今、武器の在庫が切れておりまして……。"
41140-78 = "……え、いつもあんだけあるのに？全部？"
41140-79 = "はい……実は先日、匿名のお客様が全てお買い上げされまして。"
41140-80 = "なっ……キヴォトスで戦争でもするつもり？"
41140-81 = "誰がそんな大量に……。"
41140-82 = "それは、流石にお答えできないのですが……。"
41140-83 = "すみません、これは顧客の方々の秘密事項となりますので……。"
41140-84 = "ま、まあそれはそうか……。"
41140-85 = "それでは残念ですが、今回のお取引は無かったことに……。"
41140-86 = "また何かありましたら、いつでもご連絡ください！"
41140-87 = ""
41140-89 = ""
41140-90 = ""
41140-91 = "な、何だその意味分からない状況……っていうか、当てが外れた……。"
41140-93 = "ところでモエ、お前いつの間にカイザーインダストリーのVVIPになったんだ。"
41140-94 = "そういえば色々と細かい計算が合わないことがありましたが、まさか……。"
41140-95 = "モエちゃん……横領罪で逮捕……？"
41140-97 = "そ、それは今話すことじゃなくない！？"
41140-98 = "とりあえず今は補給の方が大事で……！"
41140-99 = "ま、まあ「カイザーインダストリー」だけが伝手じゃないから！中古オークションとかだって、幾らでも買い手はいるはず！"
41140-100 = "こういうのをわざわざオークションで買う奴なんかいるのか？"
41140-101 = "舐めるな！最近のオークションでは武器や弾薬はもちろん、ハッキング機器からちょっとした野菜まで何だって手に入る場所なんだぞ！"
41140-102 = "きっと今すぐにでも、爆弾を買わせてくださいってメッセージが――"
41140-103 = ""
41140-106 = ""
41140-107 = ""
41140-108 = "……うわ、ほんとに来た。"
41140-110 = "次回;ささやかで確実な敗北"
