[translation]
41160-1 = "Episódio 16; Reembolso"
41160-5 = "Você é..."
41160-6 = "A 'Cão Louco' da Academia de Polícia Valkyrie..."
41160-8 = "...Sou a Kanna. Pelo menos me chame de Chefe do Departamento de Segurança Pública."
41160-9 = "Não que eu desgoste do apelido, mas não temos intimidade para nos tratarmos assim, não é?"
41160-10 = "Chefe, o que a traz aqui?"
41160-11 = "Você está fazendo essa pergunta mesmo sabendo o que vocês fizeram?"
41160-12 = "Ocupação ilegal de um parque destinado aos cidadãos, causando inquietação na comunidade local... Ouvi sobre isso e vim fazer a fiscalização."
41160-13 = "Mas quem disse que podíamos ficar aqui foi o Chefe do Gabinete de Defesa, sabe? Bem, via Schale, mas ainda assim."
41160-14 = "A Chefe do Departamento de Segurança Pública da Valkyrie pode simplesmente desobedecer ordens de um superior?"
41160-15 = "Parece que você está entendendo errado."
41160-16 = "O Chefe do Gabinete de Defesa nunca disse que vocês 'podem ficar neste parque'."
41160-17 = "Ele apenas disse que 'suspenderia a punição de vocês'."
41160-23 = "...Além disso, a administração do parque não é de competência do Gabinete de Defesa."
41160-24 = "Então, quer dizer que exigir que a gente saia é legítimo... é isso?"
41160-25 = "...Sabendo muito bem que não temos para onde ir."
41160-26 = "Que personalidade adorável você tem, Chefe."
41160-27 = "M-mas, o Departamento de Segurança Pública vir pessoalmente...?"
41160-28 = "Se for sobre ordem pública, não seria competência do Departamento de Guarda...?"
41160-33 = "Ah, basicamente sim."
41160-34 = "...Em uma situação normal, claro."
41160-36 = "Não entendi nada, você veio aqui para nos expulsar à força?"
41160-37 = "Tudo bem, mas esqueceu que da última vez o resultado foi um desastre?"
41160-38 = "Kazekura, escolha bem as suas palavras."
41160-39 = "Ouvi dizer que, com a chuva forte de outro dia, quase todo o equipamento do Esquadrão RABBIT ficou encharcado, não foi?"
41160-40 = "..."
41160-41 = "Soube que venderam itens usados para conseguir equipamentos novos. Mas isso não é pouco para cobrir o parque inteiro?"
41160-42 = "Desta vez, o Departamento de Segurança Pública garantiu uma grande quantidade de armas de fogo com a ajuda de patrocinadores."
41160-43 = "Sei que vocês são de elite, mas outra coisa é saber se conseguem superar a vantagem numérica."
41160-50 = "Vamos, decida logo."
41160-51 = "Saiam deste parque pacificamente, ou tentem a sorte lutando com essas armas de má qualidade."
41160-53 = "Hah, parece que vocês estão falando sério mesmo."
41160-54 = "Mesmo sem armas suficientes, ainda podemos dar um susto em vocês, sabia?"
41160-55 = "M-mas, será que a gente ganha mesmo...?"
41160-56 = "O-o que a gente faz, Miyako-chan..."
41160-62 = "Nós..."
41160-63 = "[s] \"Pode esperar um pouco?\""
41160-67 = "...Sensei do Schale? Por que você está aqui..."
41160-68 = "...Ouvi do Chefe do Gabinete de Defesa que o tratamento do Esquadrão RABBIT ficaria a cargo do Schale."
41160-69 = "No entanto, este é um caso à parte. Mesmo que seja uma instrução do Sensei, não posso reverter a decisão."
41160-70 = "A reurbanização da Cidade dos Coelhinhos já é uma decisão tomada."
41160-71 = "[s1] \"Mas é um pouco complicado pedir para saírem de repente.\"\n[s2] \"Poderia dar um tempo para elas pensarem, nem que seja um pouco?\""
41160-72 = "Acho que já tiveram tempo suficiente até agora..."
41160-73 = "Acho que já tiveram tempo suficiente até agora..."
41160-77 = "...Tudo bem."
41160-78 = "Tenho uma dívida com o Sensei... então vou me retirar por hoje."
41160-79 = "Mas não podemos deixar isso de lado para sempre."
41160-80 = "Calculando por cima, acho que até o final deste mês. Se ainda estiverem neste parque quando esse prazo chegar, não teremos escolha a não ser usar a força."
41160-81 = "...Nós também temos uma 'linha que precisamos proteger'."
41160-85 = "...Recuar!"
41160-95 = "Mesmo dependendo do Schale da última vez, agem como se fossem superiores."
41160-96 = "Mas é um fato que o armamento deles foi reforçado."
41160-97 = "Moe, tem certeza de que aquelas são armas da Kaiser Industry?"
41160-99 = "Tenho sim."
41160-100 = "Ainda assim, não entendo como aquela Valkyrie pão-dura conseguiu comprar equipamentos da Kaiser. Não faz sentido."
41160-101 = "Falando nisso, agora pouco você mencionou um \"patrocinador\"..."
41160-102 = "[s] \"...Talvez seja um suborno.\""
41160-103 = "...\"Suborno\"?"
41160-104 = "Você quer dizer um \"reembolso\"? Aquele tipo de coisa onde uma parte do que foi pago retorna?"
41160-105 = "Mesmo que seja isso, que vantagem a Kaiser Industry teria em fazer algo assim para a Valkyrie...?"
41160-107 = "(Contei para o pessoal do Esquadrão RABBIT o que eu estava pensando.)"
41160-110 = "...Entendo."
41160-111 = "A Kaiser Construction, que está cuidando do desenvolvimento da Cidade dos Coelhinhos, é do mesmo grupo da Kaiser Industry, que lida com armas."
41160-112 = "A transferência de fundos é relativamente simples. Se a Kaiser Industry estivesse repassando o lucro que a Kaiser Construction teria com o desenvolvimento da Cidade dos Coelhinhos para o Departamento de Segurança Pública na forma de armas..."
41160-114 = "Então, o Departamento de Segurança Pública só precisaria expulsar os nômades como pagamento por essas armas."
41160-115 = "...Isso não é ilegal?"
41160-116 = "Sim, é claro que é ilegal."
41160-117 = "Afinal, uma escola de polícia que deveria servir aos cidadãos está trabalhando para uma empresa privada."
41160-118 = "Polícia e empresas conspirando para atacar cidadãos..."
41160-119 = "Não dá nem para acreditar."
41160-120 = "N-nós também não estamos em posição de falar muito, mas..."
41160-121 = "[s] \"Claro, ainda estamos apenas no campo das suposições...\""
41160-122 = "É verdade."
41160-123 = "Não sabemos se o Departamento de Segurança Pública realmente fez um acordo com a Kaiser Industry."
41160-125 = "Sendo registros da Valkyrie, provavelmente estão em um servidor local. Hackear de fora parece impossível."
41160-126 = "Droga, se ao menos tivéssemos alguma prova definitiva..."
41160-127 = "Algum jeito, qualquer método..."
41160-133 = "...Se nos infiltrarmos na Valkyrie, talvez encontremos os registros da transação."
41160-138 = "Miyako, você está falando sério?"
41160-139 = "Estamos falando do prédio principal da Valkyrie, né? Aquela fortaleza, você tem ideia de quantas centenas de pessoas tem lá dentro?"
41160-140 = "Mesmo com apoio adequado, não seria difícil...?"
41160-141 = "Com a nossa força atual, provavelmente..."
41160-142 = "Não seria mais fácil simplesmente denunciar?"
41160-143 = "[s] \"Denunciar um problema da polícia para a própria polícia?\""
41160-144 = "...É verdade. Ambos são da Valkyrie."
41160-145 = "Quando há problemas na Valkyrie, o órgão superior que deveria investigar isso é..."
41160-151 = "Deveria ser a SRT."
41160-153 = "É, pensando bem, é verdade."
41160-154 = "Então só resta a nós fazer isso... se não, ninguém mais vai resolver."
41160-155 = "Mas, será que está tudo bem...?"
41160-156 = "Nós nem temos mais uma escola..."
41160-157 = "[s] \"...Se vocês acreditam nisso.\""
41160-159 = "...Sensei?"
41160-165 = "[ns3] \"Vão em frente, eu assumo a responsabilidade se algo acontecer.\"\n[ns4] \"Tentem não se machucar, por favor.\""
41160-170 = "...Que pessoa estranha."
41160-171 = "Sensei, você realmente sabe o significado da palavra \"responsabilidade\"?"
41160-172 = "Hah, ele é um bobo mesmo."
41160-173 = "Fufu..."
41160-178 = "Mas, graças a isso, nossa determinação se fortaleceu."
41160-179 = "...Nós somos a SRT. A força especial enviada primeiro para lidar com crimes complexos em Kivotos."
41160-184 = "Para manter a ordem, neutralizar os criminosos rapidamente e..."
41160-185 = "Descarregar todo o poder de fogo possível em um instante e..."
41160-186 = "...deixar o local antes que percebam."
41160-188 = "A Valkyrie está conspirando com empresas privadas para realizar atos ilegais... mesmo que a probabilidade seja alta, não conseguiremos descobrir isso através dos procedimentos regulares."
41160-189 = "Esta é, sem dúvida, uma missão na qual a SRT deve intervir."
41160-193 = "Pessoal, preparem-se para a operação."
41160-194 = "A partir de agora, para garantir as provas relacionadas aos subornos ilegais do Departamento de Segurança Pública da Valkyrie..."
41160-196 = "A 'Operação Trevo' está iniciada!"
41160-198 = "Próximo episódio: Operação Trevo (1)"
