[translation]
41170-1 = "第17話;クローバー作戦（１）"
41170-4 = "ヴァルキューレ警察学校・廊下"
41170-7 = ""
41170-8 = ""
41170-9 = ""
41170-10 = "こちらRABBIT1、現在の時刻は2330。只今ポイン[ruby=エコー]トEに[/ruby]到着しました。"
41170-11 = "哨兵の姿は無し、向かい側の廊下に監視カメラらしき多数の機器を確認。"
41170-12 = "こちらキャンプRABBIT。その監視カメラについてはもうハッキング済みだから、気にしないでOK～。"
41170-13 = "画面で見た感じ、近くに警備員は無し。安心してポイン[ruby=シエラ]トSま[/ruby]で行っちゃって。"
41170-14 = "モエちゃん、相変わらず早い……。"
41170-15 = "くひひ、この程度のセキュリティごとき朝飯前よ。"
41170-16 = "……って調子に乗ったところ悪いんだけど、ハッキングは30分しか持たなそう。30分で乱数コードが生成されるっぽくて、この回路はちょいとキツイかな。だからミッションは30分以内によろしく。"
41170-17 = "内容的にまーたあのヴェリタスの副部長かなー……まったく鬱陶しい。"
41170-18 = "仮にもヴァルキューレの本館なのに、警備がいないってのはどうなんだ？"
41170-19 = "大丈夫だっての、信じてよ！"
41170-20 = "モエに言ったんじゃない、ヴァルキューレの方に対してだ。"
41170-21 = "……今は敵ながら呆れたもんだ。これだからヴァルキューレには行きたくないんだっての。"
41170-22 = "まあとにかく、公安局の取引帳簿――「クローバー」が保管されてるポイン[ruby=シエラ]トSは[/ruby]地下3階。一応通行量が少ない西側の階段を使って。"
41170-23 = "……繰り返しになるけど、時間制限30分だから。それまでによろしく。"
41170-24 = ""
41170-26 = ""
41170-28 = "RABBIT1、了解です。"
41170-29 = "と、ところで、先生は……？"
41170-30 = "前回とは違って侵入経路が厳しいので先生には無理です。話し合いの結果、無理やり置いてきました。"
41170-31 = "それに、万が一バレた場合は銃撃戦になるかもしれませんから。"
41170-32 = "[s1] \"役に立たなくてごめん……。\"\n[s2] \"裏側で応援してるね……。\""
41170-33 = "まあ、ある意味いつも通りのメンバーだ。"
41170-34 = "まあ、ある意味いつも通りのメンバーだ。"
41170-35 = "そ、それはそうだね……。"
41170-36 = "はい。私たち、だけで……。"
41170-37 = "ミヤコ、何だその表情は。問題でもあるのか？"
41170-38 = "い、いえ。作戦のことを考えていただけです。"
41170-39 = ""
41170-41 = ""
41170-42 = "では、警戒しながらポイン[ruby=シエラ]トSま[/ruby]で移動！"
41170-46 = ""
41170-47 = "この部屋に、ヴァルキューレの文書が全部……。"
41170-48 = "頑丈な扉ですね。犯罪に関わる証拠なども全てあるでしょうし、当然ではありますが。"
41170-50 = "その割にはやっぱり、警備とか全然いないけどな。"
41170-51 = "ま、楽なのは良いことだけど。"
41170-52 = "……っていうかこれ、何を待ってるんだ？さっさと中に入らないのか？"
41170-53 = "この扉、電子式なんです。"
41170-54 = "今モエちゃんが、一生懸命解除してるみたいで……。"
41170-55 = "……おい、まさかその時間って「30分」にカウントされるわけじゃないよな？"
41170-56 = ""
41170-58 = ""
41170-60 = "急かさないでっての！私だって今急いでるんだから！"
41170-61 = "ちっ、普通に扉をぶち抜くんじゃダメか？"
41170-62 = "その分厚さで行けると思うの？やれるもんならやってみれば？"
41170-63 = "それで警報とか鳴っても責任取れないけど。"
41170-64 = ""
41170-66 = ""
41170-67 = "あー、分かった。これデコードしたら……"
41170-68 = ""
41170-70 = ""
41170-71 = ""
41170-73 = "……クリア！"
41170-74 = ""
41170-79 = "……3分か、結構かかったな。"
41170-80 = "これでも相当速いんだけど！？"
41170-81 = "この難しさ、分かってて言ってる！？"
41170-83 = "今は喧嘩をしてる場合ではありません。"
41170-84 = "もうあまり時間も無いので、急ぎましょう。"
41170-85 = "例のリベートに関する証拠を探してください。"
41170-86 = "じゃあ、"
41170-87 = "私は右の本棚から。"
41170-88 = ""
41170-90 = ""
41170-93 = "うぅ、暗い……。"
41170-94 = ""
41170-96 = ""
41170-100 = "えーっと、"
41170-101 = "公安局、公安局……。"
41170-102 = ""
41170-104 = ""
41170-105 = ""
41170-106 = "「カイザーインダストリー」、記録は1週間前……"
41170-107 = ""
41170-109 = ""
41170-110 = "これだ！"
41170-111 = ""
41170-113 = ""
41170-114 = ""
41170-115 = "ナイスです、サキ。見せてもらえますか？"
41170-120 = "……なるほど。"
41170-121 = ""
41170-123 = ""
41170-124 = "「クローバー」……「カイザーインダストリー」と公安局との間における、違法なリベートの証拠を確保しました。"
41170-125 = "先生が言っていた通りですね、やはり「子ウサギタウンの再開発」の件が間に挟まっていたようです。"
41170-126 = "[s3] \"そっか、やっぱり……。\"\n[s4] \"とりあえず、みんなお疲れ様。\""
41170-127 = "この資料さえあれば、彼女たちの動きを止められそうです。"
41170-128 = "この資料さえあれば、彼女たちの動きを止められそうです。"
41170-129 = "公安局のやつらに一泡吹かせられるな。"
41170-130 = ""
41170-133 = ""
41170-134 = ""
41170-136 = ""
41170-137 = "ん？何してるんだ、ミユ？"
41170-138 = "と、扉、閉めちゃって……。"
41170-139 = "……閉めたなら開ければ良いだろ。"
41170-140 = "で、でもこの扉……"
41170-141 = "ドアノブとか、無いタイプで……開けられない、かも。"
41170-142 = ""
41170-144 = ""
41170-146 = "……はぁっ！？"
41170-148 = "次回;クローバー作戦（２）"
