[translation]
42140-1 = "Episódio 14; O Dilema do Prisioneiro"
42140-2 = "（Depois de arrumar as coisas e voltar do Parque dos Coelhinhos, já estava bem tarde...）"
42140-7 = "Loja de Conveniência Angel 24"
42140-10 = "（Ao olhar para a prateleira de marmitas...）"
42140-14 = "[ns] \"Ué? Não tem nenhuma marmita...?\""
42140-15 = "D-desculpe... É que hoje tudo esgotou."
42140-16 = "[s1] \"Eu estava planejando jantar uma marmita da loja...\"\n[s2] \"Sendo assim, também não sobrou nada para descarte...?\""
42140-19 = "Sim... Até aquela marmita de broto de feijão que sempre sobrava para descarte..."
42140-20 = "E, por algum motivo, desde ontem, o pedido de marmitas foi proibido apenas na nossa unidade..."
42140-21 = "Mesmo perguntando o motivo, só me disseram que era uma nova ordem administrativa...#nAté as marmitas que eu já tinha pedido foram canceladas..."
42140-22 = "Agora, só restou água mineral..."
42140-23 = "[s] \"Será que pães e chás também...?\""
42140-24 = "Sim. Nem pães, nem bebidas de nenhum tipo eu consigo pedir..."
42140-25 = "Hoje a loja praticamente não abriu. #nSinto muito pelo transtorno..."
42140-26 = "[s3] \"Não é culpa sua, Sora.\"\n[s4] （Será que isso... é uma indireta para mim...?）"
42140-33 = "P-Professor... Diga, você sabe de algo sobre o que tem acontecido em D.U. ultimamente?"
42140-34 = "Talvez por causa da confusão na cidade anteontem, não tem quase ninguém... #ne o clima na sede também está estranho..."
42140-35 = "Recebemos um manual grosso dizendo que são as novas regras para o setor de serviços... #ne pessoas assustadoras da Kaiser Security vieram à loja dizendo que iam verificar se estávamos cumprindo as ordens administrativas..."
42140-36 = "Até rolam boatos de que a \"Angel 24\" vai fechar e ser substituída pela \"Kaiser 26\"... O que eu devo fazer?"
42140-37 = "Dizem que na \"Kaiser 26\", o ambiente de trabalho é tão cruel que 26 horas de turno por dia não são suficientes... Se eu trabalhar num lugar desses, vou morrer de exaustão..."
42140-38 = "[ns5] \"Então era esse o significado de 26...\"\n[ns6] \"Trabalhar 26 horas por dia não é impossível...?\""
42140-43 = "[ns] \"Sora, você já jantou?\""
42140-44 = "Sim. Eu trouxe uma marmita, então estou bem."
42140-45 = "Ontem, acabei fazendo carne com batatas demais, então—"
42140-50 = "Ah, bem..."
42140-51 = "Se... se você quiser..."
42140-52 = "[ns] \"N-não precisa! Não se preocupe!\""
42140-57 = "（Como não podia aceitar a marmita da Sora, voltei apressado para o escritório do Schale）"
42140-59 = "Escritório do Schale"
42140-63 = "[ns] \"Estou com tanta fome...\""
42140-69 = "「\"FOX EATS\" aqui!」"
42140-70 = "「[USERNAME], você pediu uma marmita, certo?」"
42140-74 = "[ns] \"Bem, eu não pedi nada...\""
42140-75 = "「Que estranho... Recebemos um pedido para entregar uma porção de inari aqui.」"
42140-76 = "「Vou confirmar, poderia abrir a porta um instante?」"
42140-80 = "[ns7] Abrir a porta.\n[ns8] Não abrir a porta."
42140-85 = "「...Obrigada.」"
42140-91 = "[ns9] \"Vocês são aquelas de antes...?\""
42140-92 = "Boa noite, Professor. Fico feliz em vê-lo novamente."
42140-93 = "Ei! Como você tem passado?"
42140-94 = "Ah... pensar que nos encontraríamos de novo..."
42140-98 = "Professor, você já jantou?"
42140-99 = "...Não tem jeito. #nNão dá para voltar atrás agora..."
42140-104 = "...Instalação concluída, preparando detonação."
42140-105 = "[s10] \"...O que vocês estão fazendo?\""
42140-110 = "3... 2... 1..."
42140-114 = "[ns11] \"Espere, eu vou abrir agora—\""
42140-125 = "Opa, foi mais chamativo do que eu pensava."
42140-126 = "Otogi! Quanto explosivo você usou para essa invasão? #nA porta voou junto com a moldura!"
42140-127 = "Foi mal, foi mal. Não estou acostumada com CQB."
42140-128 = "Ahaha... desculpe, Sensei. Vou consertar a porta agora mesmo..."
42140-129 = "[s12] \"Vocês são aquelas de antes...?\""
42140-133 = "Boa noite... embora seja um pouco presunçoso dizer isso dada a situação... mas estou feliz em vê-lo novamente, Sensei."
42140-134 = "Sensei, você já jantou?"
42140-137 = "[ns] \"Ainda não.\""
42140-138 = "……Eu imaginei."
42140-139 = "Parece que a ordem administrativa atual acabou afetando a logística das lojas de conveniência..."
42140-141 = "Afetando ou não, eles só estão sendo mesquinhos porque você não faz o que eles querem."
42140-142 = "Não somos mais crianças... fazer algo assim é realmente ridículo."
42140-143 = "Bem, mas cortar o suprimento de comida de um inimigo acampado é uma estratégia válida."
42140-144 = "Não importa o quão forte seja a sua vontade, você não consegue lutar se estiver com fome, não é?"
42140-146 = "Eu não acho que o Sensei esteja acampando no Schale, na verdade..."
42140-150 = "Bem, de qualquer forma. Nós, da FOX EATS... não, o Esquadrão FOX, preparamos uma refeição simples para você."
42140-151 = "[ns] \"Isso é... Inari Sushi?\""
42140-152 = "Sim. Você já comeu o Inari que eu fiz antes, não é?"
42140-153 = "Você parecia gostar tanto... então fiz seguindo a mesma receita daquela vez."
42140-154 = "Tem bastante, então pode comer o quanto quiser."
42140-156 = "Bem, imagino que você deva estar receoso de comer algo que nós trouxemos, mas..."
42140-160 = "[ns] Aceitar o Inari."
42140-167 = "……Você está comendo normalmente?"
42140-168 = "Eh...? Sério...? Que perigo... Você não tem nenhum senso de cautela...?"
42140-170 = "Hum, você está bem...?"
42140-171 = "[s13] \"Estou bem, está delicioso.\"\n[s14] \"O sabor está no ponto e o arroz está com uma textura perfeita, é maravilhoso!\""
42140-174 = "Não, não é isso que eu quis dizer..."
42140-179 = "Talvez não seja o nosso lugar para dizer isso, mas... você não deveria suspeitar que poderia haver veneno ou algo assim?"
42140-180 = "[s] \"...Eh? Esse Inari tem veneno?\""
42140-181 = "Não, não tem..."
42140-185 = "Olha, parece que você entendeu errado... nós somos inimigas agora."
42140-186 = "Como Sensei do Schale, você já deve saber, certo? Nós, do Esquadrão FOX, estamos trabalhando com a Presidente Interina do Conselho Estudantil, Kaya, pela restauração da SRT."
42140-187 = "Você recusou a proposta da Presidente Interina Kaya, então você realmente achou que nós, como colaboradoras dela, traríamos comida sem segundas intenções?"
42140-188 = "Mesmo sendo uma pessoa de bom coração, tudo tem um limite..."
42140-189 = "Dizem que é um gesto nobre ajudar um inimigo em necessidade, mas... normalmente, é prudente não tocar no que o inimigo oferece."
42140-190 = "No campo de batalha, às vezes deixamos munição defeituosa de propósito, caso o inimigo a capture..."
42140-191 = "Na SRT, somos ensinadas repetidamente: 'Em território inimigo, não beba nem coma nada que não tenha trazido consigo'..."
42140-192 = "[ns] \"Eu não sou seu inimigo, afinal.\""
42140-196 = "[ns] \"...Sou apenas um professor.\""
42140-200 = "Hmm..."
42140-201 = "……Você é exatamente como diziam."
42140-203 = "Mesmo que não sejamos inimigas, confiar nas pessoas tão facilmente fará você se machucar no futuro."
42140-204 = "Confiar tão rápido passa a impressão de que você é imaturo para o seu oponente... e isso te coloca em desvantagem nas negociações."
42140-205 = "Na sociedade, você deve suspeitar dos outros desde o início... se não ficar atento, acabará saindo perdendo..."
42140-206 = "……Você também é um adulto, então sabe disso, não sabe?"
42140-207 = "[s] \"Porque ganho muito mais confiando do que perdendo por suspeitar.\""
42140-209 = "……Hmm."
42140-210 = "Você não conhece o 'Dilema do Prisioneiro'?"
42140-211 = "Se ambos escolherem o que é vantajoso para o outro, ninguém sofre danos, mas se o outro te trair, você acaba arcando com as consequências... é uma teoria sobre qual escolha é a mais 'racional'."
42140-212 = "Ou seja, independentemente da escolha do outro, trair é sempre mais vantajoso, então você sempre escolhe a traição."
42140-213 = "Na verdade, já enfrentamos muitos 'prisioneiros' até hoje, mas... nunca vi ninguém escolher deliberadamente o que seria vantajoso para o outro."
42140-214 = "……A 'confiança' que os adultos tanto falam é, essencialmente, a mesma coisa."
42140-215 = "[s15] \"É um assunto complexo... mas interessante.\"\n[s16] \"...Como esperado da elite da SRT!\""
42140-218 = "Humpf, mesmo não sendo uma elite, é natural saber pelo menos isso――"
42140-222 = "Não, não é isso……!"
42140-223 = "Tão fácil……"
42140-224 = "[s] \"Mas, na realidade, não seria diferente?\""
42140-225 = "Claro, se formos transpor isso para a realidade, precisamos levar em conta várias variáveis."
42140-226 = "Como o impacto que essa escolha trará para o futuro……"
42140-227 = "……Mas, Sensei. Esta conversa pode terminar em uma única rodada."
42140-228 = "Em uma sociedade selvagem onde o perdedor nunca mais retorna, o mais eficaz é#n\"sempre trair o oponente para causar medo\"――Estratégia All-Defect."
42140-230 = "……Quando isso acabar, talvez nunca mais possamos voltar."
42140-231 = "Mas nós somos armas. #nNão nos lembraremos da escolha do Sensei."
42140-232 = "Essa escolha também não afetará outras alunas."
42140-233 = "Mesmo assim, você confia em nós…… nas alunas?"
42140-234 = "[s] \"Sim, eu confio.\""
42140-236 = "Falar é fácil――"
42140-237 = "……Acalme-se, Kurumi."
42140-239 = "Embora ninguém possa garantir nem o dia de hoje, #no Sensei aposta nas possibilidades de amanhã."
42140-240 = "[ns] \"Com certeza.\""
42140-245 = "[ns17] \"Porque eu sou o Sensei.\"\n[ns18] \"Meu papel é guiar as crianças que se tornarão os adultos de amanhã.\""
42140-253 = "……Que pessoa estranha."
42140-254 = "……Realmente, como diziam os rumores."
42140-255 = "[s] \"Além disso, vocês mesmas provam a força da 'confiança'.\""
42140-257 = "[ns19] \"Ouvi dizer que o Esquadrão FOX é uma equipe com uma confiança profunda na líder do esquadrão.\"\n[ns20] \"Acredito que a força do Esquadrão FOX reside na relação de confiança entre as integrantes.\""
42140-260 = "Yukino-chan, é……?"
42140-261 = "……Bem, tecnicamente sim."
42140-262 = "……Afinal, ela é a líder do esquadrão."
42140-266 = "[ns] \"……Aconteceu alguma coisa?\""
42140-272 = "Não, nada……"
42140-273 = "Os laços do Esquadrão FOX são mais fortes do que qualquer coisa."
42140-275 = "Pelo menos, não é algo que seria abalado por uma palavra de um Sensei que parece um guaxinim."
42140-276 = "……De qualquer forma, somos melhores amigas desde antes de ela se tornar líder."
42140-278 = "Muito obrigada. Parece que consegui confirmar os sentimentos do Sensei……"
42140-283 = "Já entregamos o almoço, então acho que devemos ir embora."
42140-284 = "Desculpe incomodar a esta hora da noite. #nPeço perdão por ter bombardeado você com perguntas de repente……"
42140-285 = "Talvez não compense o pedido de desculpas, mas #nhá algo que você queira nos perguntar?"
42140-286 = "[s21] \"Ouvi dizer que o Esquadrão RABBIT se juntou a vocês……\"\n[s22] \"Como estão as meninas do Esquadrão RABBIT?\""
42140-289 = "O Esquadrão RABBIT agora está……"
42140-290 = "A localização do esquadrão é tecnicamente confidencial, então é um pouco difícil dizer……"
42140-299 = "……Pegue o ônibus número 10 em direção a Shin-Kiroo no ponto em frente ao Schale, desça no ponto final e caminhe cerca de 1 km para o leste ao longo do vale seco; lá existe uma instalação que não consta nos mapas."
42140-300 = "Pode parecer um acampamento abandonado, mas é uma instalação militar construída antes do desaparecimento da Presidente do Conselho Estudantil para o treinamento e operações das alunas da SRT."
42140-301 = "……O Esquadrão RABBIT está lá."
42140-302 = "Por favor, [USERNAME] Sensei, verifique a segurança delas com seus próprios olhos."
42140-304 = "Ei, Niko! Por que você contou?"
42140-305 = "A localização do acampamento onde elas estão é um segredo de nível 2, sabia?"
42140-306 = "Tudo bem, perguntar sobre a segurança delas não é um problema."
42140-307 = "Mas, se descobrirem, provavelmente vamos levar uma bronca, então…… mantenha segredo da Yukino-chan."
42140-308 = "Sério, você……!"
42140-309 = "Haa…… não diga que não avisei se algo acontecer."
42140-311 = "É uma ordem da sublíder do esquadrão, então não temos escolha a não ser obedecer."
42140-312 = "Fufu, obrigada."
42140-313 = "Além disso, se o [USERNAME] Sensei puder mudar aquelas crianças, talvez um dia nós também……"
42140-318 = "Então, até mais..."
42140-319 = "Não, fique bem — Sensei."
42140-326 = "（Depois que a integrante do Esquadrão FOX foi embora, enquanto comia o inari que sobrou, pensei sobre o que viria a seguir）"
42140-330 = "（...Senti que o inari que a Niko trouxe estava com um sabor um pouco mais forte do que antes）"
42140-332 = "Próximo episódio: A justiça da SRT"
