[translation]#[Texto revisado.] Em aguardo de revisão de formatação de texto. - Filipe 11/06.
42160-1 = "Episódio 16: As Razões do Sensei"
42160-3 = "[log]Registro de Interrogatório Tático: 001-S-1[/log]"
42160-5 = "[log]Oficial Interrogadora: Tsukiyuki Miyako, Cadete do Primeiro Ano, Academia SRT[/log]"
42160-7 = "[log]Suspeito Detido: Sensei da Schale[/log]"
42160-10 = "Centro de Treinamento Subterrâneo - Sala de Interrogatório"
42160-12 = "……Eu não consigo entender."
42160-13 = "Como e por que o senhor atravessou uma floresta militar fechada para chegar aqui?"
42160-14 = "[s1] \"O lance do 'farejar o vento' era uma piadinha, obviamente...\"\n[s2] \"Mas eu atravessei a floresta pura e simplesmente para ver você, Miyako.\""
42160-17 = "……Essa é a pior mentira que eu já ouvi."
42160-18 = "O senhor está numa Base de Operações Negras a quilômetros de distância dos limites civis."
42160-19 = "O senhor precisou furar o perímetro eletrônico, e sabendo perfeitamente o quão letal é pisar no covil da FOX sem autorização... O senhor escolheu invadir."
42160-20 = "E, para desviar dos sensores externos e vir até o meu posto no escuro... o senhor precisou de um motivo tático muito específico."
42160-21 = "……Vou perguntar mais uma vez, Sensei."
42160-22 = "――O que o senhor veio caçar aqui dentro?"
42160-23 = "[s3] \"Eu juro pela minha vida, a resposta é a mesma.\"\n[s4] \"Eu vim verificar os seus olhos, Miyako.\""
42160-26 = "……O senhor veio me convencer a desertar, não é?"
42160-27 = "Eu deixei claro na carta, Sensei... Meu coração está trancado."
42160-28 = "Desde o momento em que a Kaya, a única pessoa com o poder da ressurreição da nossa academia nas mãos, roubou a cadeira da presidência...#na nossa greve nas ruas perdeu o sentido."
42160-29 = "Para as minhas ex-lideradas da RABBIT... o frio do parque era inaceitável. Aqui elas têm teto de ferro, calor, caloria e pólvora.#nEles cederam o paraíso tático em troca da nossa submissão."
42160-30 = "……Foi o cálculo militar mais lógico e benevolente para a tropa que eu pude engolir."
42160-31 = "Não, pior... Como um fuzil empunhado por um soldado maior, eu perdi o direito de calcular. Nós só atiramos sob comando agora."
42160-32 = "Por isso... não importa o quão belo seja o seu discurso, Sensei... Eu não posso reverter o processo de assimilação."
42160-33 = "[ns] \"Eu nunca vim pedir pra você desertar, Miyako.\""
42160-35 = "[ns5] \"Eu só preciso de uma única resposta limpa.\"\n[ns6] \"Você está se divertindo e sendo feliz, Miyako?\""
42160-38 = "……Que tipo de pergunta infantil é essa num cenário letal como esse?"
42160-39 = "Eu sou uma operadora da SRT... Meu DNA foi forjado para esmagar os inimigos e defender a linha tênue da justiça."
42160-40 = "Para soldados carregando fardos de sangue... ter o privilégio egoísta de se sentir 'feliz' é uma fraqueza que custa vidas."
42160-41 = "[s7] \"Se o brilho nos seus olhos dissesse que você estava confortável e em paz, eu virava as costas e ia embora sem dar um pio, mas...\"\n[s8] \"Você distorceu o significado da palavra 'Responsabilidade', Miyako.\""
42160-44 = "Distorci... o quê?"
42160-45 = "A responsabilidade de um soldado não se resume ao sacrifício absoluto em prol da missão maior?"
42160-46 = "[ns9] \"A 'Responsabilidade Real' não é vestir uma coroa de espinhos e sangrar sem reclamar.\"\n[ns10] \"Também não é ser passiva, não é fechar os olhos e fingir que é cega...\"\n[ns11] \"...e não é se submeter à tortura psicológica porque você acha que merece ser punida.\""
42160-52 = "[ns12] \"Quando você abraça a Responsabilidade de algo, é pra garantir que você jamais vá derramar lágrimas de arrependimento sobre o seu próprio reflexo no espelho amanhã.\"\n[ns13] \"É agir pra arrancar as correntes do peito. Tem que ser algo que faça você sorrir por ter feito a coisa certa no final.\""
42160-59 = "[ns] \"Vou repetir... Submeter a sua alma a elas... Isso tá te fazendo sorrir, Miyako?\""
42160-64 = "……É exatamente por essa teimosia infernal que eu não queria escutar a sua voz."
42160-67 = "……Desde que eu caí no asfalto com as outras, achei que a verdadeira iniciação na vida 'adulta' era o sacrifício cínico."
42160-68 = "Eu acreditei que engolir o veneno, aceitar as lâminas nas costas e fuzilar minhas próprias crenças era o rito de passagem."
42160-69 = "Que, para parar de ser uma criança, eu teria que rasgar e cuspir em cima dos ideais puros que me forjaram..."
42160-72 = "As veteranas da FOX me contaram como a realidade devorou as ilusões delas. Elas me mostraram um amanhã onde a fé é morta."
42160-73 = "Como eu sou uma cadete ignorante e assustada... as palavras geladas delas afundaram na minha cabeça e me afogaram em dúvida."
42160-74 = "……Eu fechei os olhos, abaixei o cano da arma e fingi que o cinismo delas era o meu conforto."
42160-75 = "Mas aí o senhor surge do inferno só pra bagunçar tudo o que eu tentei aceitar!"
42160-76 = "Por que o senhor está jogando o peso da escolha e o peso do mundo nas costas de uma criança medrosa que só queria obedecer?!"
42160-77 = "[ns] \"Porque, pra minha glória e pra minha desgraça... eu sou só mais um Adulto Problemático que adora dar sermão.\""
42160-81 = "……Você é louco. Problemático."
42160-85 = "――O cálculo foi feito."
42160-89 = "Fique atrás de mim, Sensei. Siga o meu rastro e não faça barulho."
42160-102 = "Esta é a eclusa de saída oeste."
42160-103 = "Eu paralisei temporariamente os fios a laser deste quadrante."
42160-104 = "Se o senhor cruzar esta porta e correr reto por 500 metros, a rota vai vomitar o senhor a alguns quilômetros do ponto de ônibus da rodovia externa antes das sirenes apitarem."
42160-105 = "[s14] \"Você não vai voltar comigo pra floresta?\"\n[s15] \"Como você vai cobrir a invasão sem a Yukino desconfiar?\""
42160-108 = "Sim. O registro e a vida dessa patrulha estão nas minhas mãos esta noite."
42160-109 = "……Se a Capitã descobrir que a muralha do Site Black foi violada por você, ela botará a base inteira em frenesi de caça."
42160-110 = "O dever primário da SRT é cortar as pontas do caos civil antes que elas incendeiem a rua. Eu não vou deixar que a sua morte em solo proibido suje o nome da minha escola."
42160-111 = "[s] \"E o que você pretende arrancar de lá de dentro a partir de agora?\""
42160-112 = "Eu... Vou assumir o fardo da Responsabilidade, como você ensinou."
42160-113 = "É a primeira vez que tento quebrar a correnteza dessa forma... O sangue talvez derrame, e o tiro saia pela culatra... Mas..."
42160-114 = "[ns16] \"Mostre as garras pra elas, Miyako.\"\n[ns17] \"E se as lâminas cortarem fundo demais... o Sensei salta no precipício com você. Boa caçada.\""
42160-119 = "……Eu aceito o comando!"
42160-124 = "……A patrulha demorou. O seu passo estava letárgico."
42160-125 = "Esbarrou em algum urso perigoso no perímetro?"
42160-126 = "Negativo. O breu da floresta não revelou inimigos."
42160-127 = "……Compreendido."
42160-134 = "O Alto Comando despachou as ordens operacionais finais da semana. A sua unidade satélite RABBIT engajará nas linhas de frente do nosso assalto."
42160-135 = "……Essa planta tática em papel..."
42160-136 = "Você reconhece o terreno. É a anatomia do subsolo da Estação dos Coelhinhos."
42160-139 = "Às 09:00 de amanhã, o comboio blindado da Kaiser rasgará a via e descarregará a Ogiva Termobárica Balística <A.N.T.I.O.C.H.> na Plataforma 2 da estação."
42160-140 = "A fim de encobrir o processo, as vias ficarão podadas e lacradas até o relógio bater 12:00――#nPorém, nós antecipamos que a insurreição civil pode se espalhar para os portões e ameaçar a segurança do pátio.#nPortanto, a sua RABBIT deverá ser as escopetas auxiliares da Kaiser nos anéis externos, suprimindo civis no asfalto."
42160-142 = "Ogiva Termobárica <A.N.T.I.O.C.H.>...? Mas esse é o demônio de metal que vocês castraram durante o resgate na Kaiser, meses atrás!"
42160-143 = "Positivo."
42160-144 = "Se é um artefato de destruição em massa apocalíptico... por que o Conselho Estudantil daria ordem para arrancá-lo de um cofre distante e injetá-lo nas entranhas do centro civil de Kivotos?!"
42160-145 = "O que o Alto Comando... Não, o que você vai fazer com isso, Capitã?!"
42160-146 = "Assim que a ogiva tocar os trilhos, o núcleo será engatilhado no fundo do poço da estação―― e explodido sem aviso.#nTodos os operários têm janela curta para evacuar antes da incineração total."
42160-147 = "……A Capitã ordenou a detonação da Termobárica debaixo das avenidas centrais...?"
42160-148 = "Esse tipo de carga enclausurada em dutos herméticos subterrâneos... a onda hiperbárica vai sugar oxigênio, vomitar chamas e transformar os arredores inteiros numa cratera estilhaçada!"
42160-149 = "――Cesse as teorias físicas, Cadete.#nA potência destrutiva daquela bomba de <A.N.T.I.O.C.H.> é muito mais íntima a mim do que qualquer dado teórico que o seu cérebro de novata calcule."
42160-150 = "……Por que aceitou uma ordem de genocídio civil?!"
42160-151 = "――Porque as ordens não são moldadas de sugestões, são decretos absolutos.#nO Conselho absorve todo o sangue derramado e a culpa moral da carnificina. A minha equipe só aperta o gatilho cego."
42160-152 = "Nós não estamos prestando serviço militar... nós vamos queimar inocentes e cometer terrorismo sujo sem sequer ser iluminadas sobre a causa tática da explosão?!"
42160-153 = "O sacrifício das cinzas pavimentará o caminho――"
42160-155 = "――O caminho para a ressurreição da Academia SRT."
42160-159 = "……O milagre da ressurreição, regado com terrorismo e sangue?!"
42160-160 = "Você acha que cimentar uma escola em cima da carne mutilada e do pânico dos cidadãos que juramos proteger vai criar a gloriosa SRT?!"
42160-161 = "Uma instituição doente que vende a alma, ajoelha para mafiosos em troca de pão e incinera o próprio povo... nunca teve o direito divino de usar as letras SRT!!"
42160-163 = "A legitimidade do trono não é divina. Ela é arrancada na bala e no suor."
42160-164 = "Sobreviva primeiro, purifique a anarquia e limpe os rastros de sangue.#nSe a sobrevivência estiver cimentada... as desculpas heroicas e morais podem ser reescritas nos jornais amanhã de manhã."
42160-169 = "……As suas palavras quando eu a admirava não saem da minha cabeça."
42160-170 = "Você dizia: 'A Justiça da SRT é um pilar de aço. Ela não flerta com a sujeira e não curva as costas'."
42160-171 = "――Eu prefiro morrer lutando pela Justiça pura que o seu nome representava no passado do que manchar a farda servindo a uma lenda viva doente e suja como você."
42160-176 = "……Eu disse que as ordens são absolutas."
42160-177 = "A Cadete ousa declarar rebelião aberta contra o comando tático do Esquadrão FOX na minha sala?!"
42160-179 = "――Falso."
42160-180 = "Quem está afundada em rebelião aberta, subversão e alta traição contra a verdadeira alma de Kivotos... é você, Shichido Yukino."
42160-184 = "As únicas cordas vocais divinas capazes de abaixar as nossas armas ou ordenar que o Esquadrão puxe o gatilho sem pensar―― pertenciam inquestionavelmente à Presidente Desaparecida."
42160-196 = "M-Miyako-chan..."
42160-197 = "Haaah..."
42160-198 = "É... Parece que o pacifismo acabou e as balas vão voar, né?"
42160-200 = "……Peço permissão para fuzilá-la, Capitã."
42160-208 = "\nPróximo Episódio: Caminhada Noturna em Sedas de Gala"