[translation]
42190-1 = "第19話;アビス"
42190-5 = "先生、こちらへ。"
42190-6 = "キリノさんが教えてくださった階段はこちらの通路につながっています。"
42190-7 = "傾斜が急なので、転ばないよう足元に気をつけてください。"
42190-8 = ""
42190-15 = "……たしかに、怪しい場所ですね。"
42190-16 = "突貫工事だったのか、手すりや仕上げ材の処理が雑なのに……#n電力供給と通信用の配線は接続されている……"
42190-17 = ""
42190-19 = ""
42190-20 = ""
42190-21 = ""
42190-22 = "これは……使い終わったケミカルライトが床に捨てられています。"
42190-23 = "おそらく、先輩方もこの通路を使って地下施設に入ったのかと。"
42190-24 = "[s] \"ケミカルライト？\""
42190-25 = "はい。暗所での作戦時、特殊部隊員が進入可否と敵味方識別のために使用する標識の一種で……"
42190-26 = "つまり……この先で、FOX小隊が待ち伏せしている可能性が高いという事です。"
42190-27 = "安全な進入経路確保のため、ドアブリーチングを開始します。"
42190-28 = "榴弾に当たって怪我をしないよう、先生は離れてください。"
42190-29 = ""
42190-33 = ""
42190-34 = "では……いきます！"
42190-35 = ""
42190-40 = ""
42190-44 = "[ns] \"この施設は、一体……。\""
42190-45 = "……軍用格納庫ですね。"
42190-46 = ""
42190-48 = ""
42190-49 = "軍用装備と運搬用のレール……奥にはエレベーターが見えます。"
42190-50 = "これほどの格納庫なら……少なくとも1個大隊の武装くらいは賄えそうです。"
42190-51 = "[s] \"駅の下にどうしてこんな軍事施設が……？\""
42190-52 = "確信はありませんが……"
42190-53 = "一般的に、軍事施設は市民に敬遠されるため、郊外に建てられる事が多いです。そのため、運送や運用のコストが嵩んでしまうのですが――"
42190-54 = "こうして市内に大型の格納庫を建設できれば……理論上、必要なコストを大幅に削減できます。その分を装備に充てることもできますし――"
42190-55 = "特に、この施設は駅直下にありますから、#n「有事」の際には鉄道を使ってD.U.各地に兵を送れるので……"
42190-58 = ""
42190-60 = "……カイザーグループが子ウサギタウンの再開発に執着していた理由が、少し分かったような気がします。"
42190-61 = "[s] \"爆破されてしまったら、すべて水の泡になるけどね。\""
42190-62 = "……はい。"
42190-63 = "それこそ、サーモバリック榴弾を使えば、ここは跡形もなく消えてしまいます。"
42190-64 = "ここは――社会の闇を彷徨っていた者でさえ知ることがなかった、秘密の場所。"
42190-65 = "だからこそ、権力者たちは醜悪な本音を曝け出せるのでしょう。"
42190-66 = "ここは、そういった彼らにとって、欲望と自尊心を満たせる唯一の場だったのかもしれません。"
42190-67 = "そして――これほどの施設を手放してまで与えたい恐怖とは、どれほど[ruby=おぞ]悍[/ruby]ましいものなのか……。"
42190-68 = "[s] \"……もしかして、緊張してる？\""
42190-69 = "……いえ。"
42190-70 = "誰にも認められる事のない、口に出す事のない正義に力がないように。"
42190-71 = "誰にも見えない恐怖は――賞味期限切れの廃棄弁当よりも価値のないものです。"
42190-72 = "……私も、こうなって初めて気がつきました。"
42190-73 = "他人から受け継いだ[ruby=SRT]権威の名[/ruby]が――いかに無価値であるかを。"
42190-74 = "現在の時刻は1130。#n弾頭の起爆まであとわずか。"
42190-75 = "私たちのすべき事は――"
42190-76 = ""
42190-81 = ""
42190-82 = "少々お待ちください、先生。"
42190-83 = "ここは先輩方が先に入った地域ですので、無策で近づくのは危険です。"
42190-84 = "先にドローンを飛ばして偵察します。"
42190-85 = ""
42190-87 = ""
42190-88 = "ドローン、起動。"
42190-89 = ""
42190-102 = "……やはり、狙撃されましたね。"
42190-103 = "弾痕の深さとあの弾速……#n狙撃手が使用しているのは12.7mm対物狙撃用弾丸……オトギ先輩ですね。"
42190-104 = "普通の敵なら押し切って突撃するところですが……#nオトギ先輩なら、次の一発で急所を狙うでしょう。"
42190-105 = "いくら私でも、急所に狙撃されたら耐えられません。"
42190-106 = "防弾装備で武装したポイントマンがいれば……"
42190-108 = "……ようやく私たちのことを思い出してくれたみたいだな。"
42190-109 = ""
42190-111 = ""
42190-112 = "この声……"
42190-113 = ""
42190-115 = ""
42190-117 = ""
42190-121 = ""
42190-122 = "……隊員を置いて行く隊長がどこにいる？"
42190-123 = "ひどいよ、ミヤコちゃん……"
42190-124 = "つれないなぁ。#nせめて、一声かけるくらいはしてよね？"
42190-126 = "あの、それが……"
42190-127 = "……ご、ごめんなさい。#n皆さんには無茶なお願いになると思って……"
42190-128 = "どこが無茶なお願いなんだ？"
42190-129 = "その……皆さんに犠牲を強いることになってしまいますから。"
42190-130 = "私の行く道には――厳格な規律も、強力な装備も、暖かい部屋もありません。"
42190-131 = "ただ、私の信じる正義だけが満たされる……険しく苦しい人生が続くだけで……"
42190-132 = "そんな私の正義のために、皆さんが望む人生を諦めろだなんて……言えません。"
42190-133 = ""
42190-135 = ""
42190-136 = ""
42190-139 = "……いたっ。"
42190-140 = "ほんっと話が通じない……。"
42190-142 = "何が私の思う正義よ。#nそれはSRT全員のものでしょ？"
42190-143 = "……せ、先輩たちの姿に憧れてSRTに入ったのは、私たちも同じ……"
42190-145 = "過酷な状況にも決して折れない――厳しい規律。"
42190-146 = "どんな悪人も一撃で制圧できる――圧倒的な強さ！"
42190-147 = "お、[ruby=おぞ]悍[/ruby]ましい敵の前でも揺るがない――大胆な勇気……"
42190-148 = "未知の敵と戦うのは、ちょっと怖いけど……みんなと一緒なら怖くない。"
42190-150 = "余裕で勝てる状況だと、ぶっ放す弾の破滅の味が薄いんだよね。"
42190-151 = "世の中には、教範に書かれていない真理だってあるからな……"
42190-152 = ""
42190-154 = ""
42190-155 = ""
42190-156 = ""
42190-157 = ""
42190-158 = "私たちは、ミヤコの正義を――信じる。"
42190-159 = ""
42190-161 = ""
42190-163 = ""
42190-164 = "……。"
42190-165 = "……分かりました。"
42190-166 = "それでは皆さん、突入の前に装備の点検をお願いします。#n準備が終わり次第、作戦を開始します。"
42190-168 = "FOX小隊との実戦……ちょっと緊張するかも。"
42190-169 = "だな。まるで、洞窟で不可視の怪物と戦う気分だ。"
42190-170 = "そういや、前に話してたトリニティの古い小説にそんな場面なかったっけ？"
42190-171 = "うん。野生のウサギと騎士団が戦う小説に、たしかそんな描写があった。"
42190-172 = "あの洞窟に書かれていたメッセージは、たしか――"
42190-174 = "「勇敢で純粋な心の持ち主のみ――カルバノグの洞窟で道を見つけられるだろう」"
42190-175 = ""
42190-177 = ""
42190-178 = ""
42190-180 = ""
42190-181 = "……そのお話、私も好きです。"
42190-182 = "[s] \"作戦名はもう決めた？\""
42190-183 = "そういえば、作戦名を決めていませんでしたね……"
42190-184 = "せっかくなので、今回の作戦名は例の本のタイトルにしましょうか。"
42190-185 = "ああ、そうするか。"
42190-186 = "賛成～"
42190-188 = "はい、それでは……"
42190-189 = ""
42190-194 = "「カルバノグの兎」作戦――開始です！"
