[translation]
42210-1 = "Episódio 21; Caverna de Carbanog (2)"
42210-2 = "Sala de Operações"
42210-5 = "A-aqui é FOX3... Desculpe, fui derrotada. #nO \"Coelho\" já passou pelo Ponto Lima."
42210-6 = "Aqui é FOX4, o mesmo aqui. #nNosso ponto de emboscada foi descoberto facilmente... Suporte de sniper indisponível no momento."
42210-8 = "Aqui é FOX2, o \"Coelho\" está tentando fazer rapel em direção ao Ponto Oscar."
42210-9 = "As contramedidas que preparamos foram neutralizadas... Precisamos reorganizar a situação de combate."
42210-15 = "...Entendido."
42210-16 = "De agora em diante, a linha de defesa será mantida e operada apenas pela FOX1."
42210-17 = "FOX2, siga o plano, leve os membros da equipe e garanta uma rota de fuga fora da área de operação."
42210-21 = "...FOX2, está me ouvindo?"
42210-25 = "Comunicação cortada, hein..."
42210-26 = "Com aquela explosão enorme... não é de se estranhar que a conexão esteja instável."
42210-27 = "...Na verdade, talvez seja melhor assim, para que eu não precise dizer coisas desnecessárias aos membros da equipe."
42210-31 = "Bem, vamos iniciar a ofensiva \"final\"."
42210-38 = "RABBIT1, rapel concluído."
42210-39 = "Sensei, você está bem?"
42210-40 = "[s1] \"Desci amarrado como se fosse carga, mas...\"\n[s2] \"Estou bem, sem problemas.\""
42210-43 = "Felizmente, parece que você não se feriu."
42210-49 = "RABBIT2, rapel concluído."
42210-50 = "...O ponto de destino, a Sala de Operações, é logo à frente?"
42210-53 = "...O ponto de destino, a Sala de Operações, é logo à frente?"
42210-54 = "Sim, se seguirmos direto por este corredor, chegaremos à parte mais profunda do silo — a Sala de Operações."
42210-56 = "Embora tenhamos neutralizado todo o esquadrão inimigo, as instalações de defesa ainda podem estar ativas — não baixem a guarda até o fim."
42210-57 = "Após verificar o equipamento novamente —"
42210-68 = "...Foi uma habilidade impressionante, Capitã do Esquadrão Tsukiyuki."
42210-70 = "...Yukino-senpai."
42210-71 = "Você sabe o resultado da batalha que ocorreu no andar de cima, não sabe?"
42210-72 = "A deusa da vitória está sorrindo para nós. #nPare com essa resistência inútil e renda-se pacificamente."
42210-73 = "Não, é o contrário."
42210-74 = "No momento em que entramos neste silo primeiro, a \"guerra\" já foi vencida por nós."
42210-76 = "O que isso significa..."
42210-80 = "Estou segurando o botão de autodestruição da ogiva <A.N.T.I.O.C.H.> agora mesmo."
42210-81 = "Se vocês derem um passo sequer dentro da Sala de Operações... apertarei este botão imediatamente."
42210-86 = "Se a ogiva explodir em um espaço confinado como este... todos aqui perderão a vida, mas — a \"operação\" será um sucesso."
42210-87 = "Acho que o mesmo vale para você, senpai."
42210-88 = "Minha vida não é um problema importante."
42210-89 = "Se for pela operação — fazer o que for preciso é o que define a SRT."
42210-92 = "..."
42210-93 = "...Se valorizam suas vidas, vão embora. #nEste é meu último conselho como senpai."
42210-99 = "...Sensei."
42210-100 = "[s] \"...Você não quer desistir aqui, quer?\""
42210-101 = "...Sim."
42210-102 = "Porque nós também somos capazes de fazer qualquer coisa pela operação!"
42210-104 = "[ns] \"...Então, vamos nessa.\""
42210-105 = "Você achou mesmo que fugiríamos com o rabo entre as pernas por causa de um blefe desses?"
42210-106 = "Que botão interessante, tentar apertá-lo antes de mim é trapaça! Eu não vou deixar você apertar... hehe..."
42210-107 = "Pelo futuro da SRT... não podemos recuar agora!"
42210-109 = "Todos, fiquem atentos ao redor!"
42210-113 = "RABBIT Squad, invadindo a Sala de Operações!"
