[translation]
51150-1 = "Episódio 15; O Encontro"
51150-3 = "[ns] \"Quem é você...?\""
51150-4 = "Aha! Esse seu rosto."
51150-5 = "O rosto de quem não faz a menor ideia do que está acontecendo."
51150-6 = "Exatamente a expressão que eu vinha imaginando desde que ouvi falar sobre você."
51150-7 = "Realmente... é adorável. #n Gostei muito, mui~to mesmo."
51150-8 = "Foi ótimo poder conhecê-lo, você, que ouço nos 'boatos'. "
51150-9 = "[s] (Boatos...?)"
51150-10 = "Hm~? Será, será, que você está desconfiando de mim?"
51150-11 = "Tanto a sua aparência, é exatamente como nos boatos."
51150-12 = "E até nesse sentido... é o Sensei? mesmo."
51150-13 = "――Embora isso já não faça mais sentido. Aha!"
51150-14 = "Ah... é mesmo, é mesmo, quase me esqueci. #n Você já leu a cartinha?"
51150-15 = "[s] \"Cartinha, você quer dizer...\""
51150-19 = "<Avisamos a vocês>"
51150-20 = "<Nossa elegância não terminou, a essência deve ser apreciada por muitos>"
51150-21 = "<Quando a diversão começar e vocês olharem para a flor que desabrochará no céu――>"
51150-22 = "<Mais uma vez―― nós visitaremos vocês>"
51150-23 = "[s] \"Essa é... a carta que o Clube das Flores, Pássaros, Vento e Lua enviou, se me lembro bem...\""
51150-24 = "E aguardem ansiosamente."
51150-25 = "Quando nós aparecermos diante de vocês――"
51150-29 = "[log=???][ff4444]<Nós queimaremos a Hyakkiyako até as cinzas>[-][/log]"
51150-32 = "[ns] \"............!?\""
51150-35 = "Ora, ora, ora? Como imaginei... então não lhe disseram?"
51150-36 = "Eram palavras que eu queria que chegassem a você..."
51150-37 = "Ah, então aquela pessoa achou que não era necessário lhe contar?"
51150-38 = "――Que pessoa tola."
51150-39 = "[s] \"......Você é quem enviou a carta do Clube das Flores, Pássaros, Vento e Lua?\""
51150-40 = "Sim, sim. Isso mesmo."
51150-41 = "Se a sua dúvida foi esclarecida, fico muito, mui~to feliz."
51150-42 = "Bem... isso não seria possível. Ahaha!"
51150-43 = "A sua cara de quem não está entendendo nada. #n Uhum, a sua falta de compreensão é hilária."
51150-44 = "Com isso, agora entende o significado da minha pergunta... Sensei?"
51150-45 = "Mesmo sabendo a resposta, você não entende nada da essência. #n É uma pergunta de uma estupidez extrema."
51150-46 = "Então, então, agora é a minha vez."
51150-47 = "Como 'Sensei'... você deve responder às perguntas de uma 'aluna', certo?"
51150-52 = "Você... Sensei da Schale, é――"
51150-53 = "――Gosta de gatos?"
51150-54 = "[s] \"Ehm... O que diabos...\""
51150-55 = "Ahaha! Não diga algo tão triste."
51150-56 = "Mas, bem, é natural, não é. #n Pois esta conversa não tem sentido desde o início."
51150-57 = "――O único motivo de eu ter vindo te visitar. "
51150-59 = "O que será tecido a partir de agora é..."
51150-60 = "Uma 'História de Fantasmas' em prol da elegância."
51150-62 = "[ruby=Hoje]Neste dia[/ruby], após 20 anos, finalmente, finalmente os atores estão todos reunidos. "
51150-63 = "Por isso―― me faça companhia até o final, ouviu?"
51150-64 = "Até o momento em que a história chegar ao seu fim."
51150-70 = "[ns] \"E, espere...!\""
51150-74 = "[ns1] \"......História de fantasmas, o que será isso?\"\n[ns2] \"Essa voz, sinto que a conheço de algum lugar...\""
51150-81 = "Ah, Sensei!? Tudo bem? "
51150-82 = "Você não atendia o telefone... #n Eu estava preocupada que algo tivesse acontecido com você!"
51150-83 = "[s3] \"Ah, estou bem... só vi uma coisa meio estranha.\"\n[s4] \"O que será, acho que o calor do festival me subiu à cabeça...\""
51150-86 = "Eh...? "
51150-87 = "Ah, é mesmo! #n Eu encontrei a Yukari-san!"
51150-88 = "[s] \"Sério!?\""
51150-89 = "Mas tem um probleminha..."
51150-90 = "Na verdade, talvez não seja um problema... hmm."
51150-91 = "Ehm... eu queria te explicar isso pessoalmente!"
51150-92 = "Onde você está agora, Sensei?"
51150-94 = "(Enquanto esperava no ponto de encontro combinado com a Shizuko...)"
51150-99 = "Ah, Sensei!!"
51150-100 = "Finalmente, te encontrei...!"
51150-101 = "Tem tanta gente que foi difícil até chegar aqui. Uuh..."
51150-102 = "[s5] \"Bom trabalho. E então, o que você queria me falar pessoalmente?\"\n[s6] \"Ué, cadê a Yukari...?\""
51150-105 = "Ehm, é verdade que eu encontrei a Yukari-san. #n Mas, as coisas complicaram um pouco..."
51150-106 = "Deixe-me ver... por onde eu começo a explicar..."
51150-107 = "A história é meio longa, mas..."
51150-109 = "Hã, você vai participar como a Miko...!?"
51150-115 = "Sim."
51150-116 = "N-N-Não, espera aí! #n Isso não é o tipo de coisa que se decide por impulso!"
51150-117 = "Se você está se importando com o que eu disse... #n Aquilo foi só eu falando as coisas da minha cabeça, antes de saber sobre a Hyakkaryouran e sobre você, Yukari-san..."
51150-118 = "Que precisávamos de uma Miko..."
51150-119 = "B-Bem, é verdade que eu disse isso...! É verdade que no festival de 20 anos atrás a 'Miko da Família Kadenokouji' era a figura central, então... também acho que a presença da Miko-sama é importante desta vez...!"
51150-120 = "M-Mas, não dessa forma...!"
51150-121 = "Quanto a isso, não se preocupe. #n Eu também não decidi isso por impulso."
51150-125 = "......Eu pensei muito sobre isso."
51150-126 = "Se não posso voltar àquela época... e se ninguém deseja isso."
51150-127 = "Aquilo, desde o começo, não passava de uma ilusão."
51150-128 = "......Sendo assim, farei 'o que devo fazer'."
51150-129 = "Pois esse é―― 'O dever da família Kadenokouji'."
51150-131 = "M-Mas...!"
51150-132 = "Shizuko-san. Poderia, por favor, pedir desculpas ao Sensei em meu nome?"
51150-133 = "Como a Kikyou-senpai disse... eu menti para o Sensei."
51150-134 = "Fui totalmente egoísta... apenas encenei ser alguém que se esforçava pela Hyakkaryouran."
51150-135 = "Como resultado, eu acabei enganando o Sensei."
51150-136 = "......O Sensei com certeza não a culparia. Ele é esse tipo de pessoa."
51150-137 = "Sim. O Sensei com certeza..."
51150-138 = "Mas, esta é a minha decisão. #n Sei que fui muito egoísta em pedir ajuda para a Batalha de Sucessão e depois..."
51150-139 = "'Vou deixar os meus caprichos de lado e voltar para o meu lugar de origem'."
51150-144 = "E também que... 'Está tudo bem agora', por favor, passe esse recado por mim."
51150-150 = "A Yukari-san estava pedindo desculpas a você até o final, Sensei. Dizendo que não tinha cara para te encarar."
51150-151 = "[s] \"E por isso ela foi direto para o local do festival...\""
51150-152 = "Sensei..."
51150-153 = "Será que isso é culpa minha?"
51150-154 = "Será que a Yukari-san desistiu porque eu visitei a Hyakkaryouran?"
51150-155 = "Não, desde o começo..."
51150-156 = "Foi porque eu tentei recriar o festival, não foi."
51150-157 = "[s] \"Não, a culpa não é sua, Shizuko.\""
51150-159 = "[ns7] \"Mesmo que o festival tenha sido o estopim...\"\n[ns8] \"Você não fez nada com má intenção, Shizuko.\""
51150-162 = "[ns9] \"Na verdade, eu agradeço por você ter vindo até mim...\"\n[ns10] \"E ter me contado isso.\""
51150-167 = "N-Não...! Como Presidente do Comitê de Operações do Festival, eu só senti que era minha responsabilidade...!"
51150-168 = "[s] \"......Certo, então vou deixar a Yukari sob os seus cuidados por enquanto, Shizuko.\""
51150-169 = "Eh, e você, Sensei...?"
51150-170 = "Vai escutar mais um pouco sobre a Hyakkaryouran...?"
51150-171 = "[s] \"Atuar como testemunha na Batalha de Sucessão nunca foi o meu objetivo desde o começo.\""
51150-174 = "[ns11] \"Se as garotas da Hyakkaryouran estão passando por problemas...\"\n[ns12] \"Eu quero ouvir o que elas têm a dizer.\""
51150-177 = "[ns] \"Além disso, você mesma disse, não é, Shizuko.\""
51150-179 = "――Que faria com que todos sorrissem."
51150-180 = "Quero que seja esse tipo de festival... sim."
51150-181 = "[s] \"Isso. E por isso, eu também vou me esforçar.\""
51150-182 = "Sensei..."
51150-183 = "[ns] \"E também tem uma coisa que está me incomodando.\""
51150-189 = "[ns13] \"De qualquer forma, a Kikyou, a Renge e a Yukari...\"\n[ns14] \"Deve haver um motivo para o caminho dessas três ter se desencontrado.\""
51150-193 = "Nagusa-san... não é?"
51150-194 = "Aquela que escolheu não continuar na Hyakkaryouran como vice-presidente, #n e optou por devolver a prova de que era a presidente."
51150-195 = "[s] \"Sim, por isso, antes de mais nada, preciso me encontrar com a Nagusa.\""
51150-196 = "Umm... entendi."
51150-197 = "Se você diz, Sensei, deixe o assunto da Yukari-san comigo."
51150-198 = "Afinal, se tem algo a ser feito, Kawawa Shizuko faz com perfeição!"
51150-199 = "Eu vou transformar a Yukari-san na Miko perfeita!"
51150-200 = "Pode aguardar a dança dela, Sensei!"
51150-201 = "[s] \"Conto com você, Shizuko.\""
51150-205 = "[ns] \"O problema é como eu vou encontrar a Nagusa...\""
51150-210 = "[ns] \"Ah... falando nisso.\""
51150-220 = "Nós procurando pela Nagusa...?"
51150-221 = "[s] \"Achei que poderia contar com as três que já a encontraram antes.\""
51150-222 = "Com certeza, não tem ninguém melhor para encontrá-la no meio dessa multidão do que o Clube de Pesquisa de Ninjutsu! ...É o que eu acho também."
51150-224 = "Sim! N, nós já... e-encontramos com a Nagusa-san, então..."
51150-225 = "Somos a escolha certa! Não é mesmo? Presidente, Senhorita Tsukuyo!"
51150-227 = "A propósito... por que você a está procurando?"
51150-228 = "[s15] \"Tem uma garota que eu quero ajudar...\"\n[s16] \"Mas sozinho, não sou o suficiente.\""
51150-231 = "[ns17] \"Gostaria da ajuda do Clube de Pesquisa de Ninjutsu...\"\n[ns18] \"Será que podem?\""
51150-234 = "Para ajudar uma aluna... um motivo bem a cara do Sensei!"
51150-235 = "Sendo assim, não temos motivo para recusar, não é?"
51150-236 = "Tsukuyo, Izuna!"
51150-239 = "Sim!!"
51150-241 = "Nós, o Clube de Pesquisa de Ninjutsu! #n Recebemos com firmeza os sentimentos do Sensei!!"
51150-242 = "Então, todos do Clube de Pesquisa de Ninjutsu!"
51150-243 = "P-Para a batalha...!"
51150-244 = "Iniciando a missão! Nin-nin!"
51150-246 = "Próximo Episódio; Goryou Nagusa"
