[translation]
51170-1 = "第17話;街を歩く怪談（１）"
51170-2 = "燈籠祭の会場・広場"
51170-4 = "こちらの準備は終わりました！"
51170-12 = "巫女様のご登場デース！"
51170-20 = "ああ！素晴らしい！#nよくお似合いですよ、お嬢様！"
51170-22 = "苦しくないですか？#n何か飲み物とか……"
51170-24 = "いえ、お構いなく。#n慣れておりますので。"
51170-25 = "ふふっ……ええ！ええ！勘解由小路のご令嬢ですもの。#nずっとこの時を心待ちにしておりました。"
51170-26 = "お嬢様が百花繚乱から戻ってきてくださって、本当に良かった……！"
51170-27 = "これでもう心配はいりませんね、すべて[ruby=つつがな]が恙無く[/ruby]運ぶことでしょう。"
51170-32 = "こほん、ユカリさん。"
51170-33 = "知っての通り、巫女の舞は祭りの締めとして「勘解由小路の巫女様」に[ruby=おこな]行って[/ruby]いただきます――"
51170-34 = "その様子は、テレビやネットを介して中継する予定です。"
51170-35 = "舞が意味するの[ruby=そうこげいしん]は送故迎新―[/ruby]―古きを送り新しきを迎える……"
51170-37 = "より良い明日、未来を描くという意味を持つ舞です！"
51170-38 = "20年前の舞が最後だったと聞いたのデスが、こうしてまた見られるナンテ！"
51170-39 = "フィーナ、すっごく楽しみデス！"
51170-44 = "ここに儀式の手順をまとめたから――"
51170-45 = "それならご心配には及びません。#nお嬢様は小さい頃から、儀式の手順を叩き込まれておりますので。"
51170-46 = "……そうでしたか。"
51170-48 = "ええ――身共の義務ですから。 "
51170-49 = "完璧にやり遂げますので、ご安心ください。"
51170-50 = "それなら、いいですが……"
51170-51 = "本当に……大丈夫なんですよね……？"
51170-52 = "はい。"
51170-53 = "身共は……"
51170-54 = "身共は……大丈夫です。"
51170-55 = "分かりました。"
51170-56 = "それじゃ、行きましょう！"
51170-61 = "はい……これでいいのです。"
51170-66 = "全部。"
51170-72 = "――ということがあったよ。"
51170-73 = "マジでやったのかよ……ユカリと継承戦って……。 "
51170-74 = "いやぁ、継承戦をしたっていうのもビックリしたけどさぁ。"
51170-75 = "……何でそれをわざわざアタシに？"
51170-76 = "…………。"
51170-77 = "あの子、調停室に来る前にあんたと会ったでしょ。"
51170-78 = "だから一応、知らせとこうと思って。"
51170-79 = "あいつ……あんだけ言ったのに……まだ諦めてなかったのかよ……。 "
51170-80 = "……チッ、知るかよ。アタシは言ったかんな。#n戻ったって無意味だって。"
51170-81 = "だからもういいよ、キキョウ。"
51170-82 = "…………いい、って？"
51170-83 = "こんな風に、連絡してこなくていい。"
51170-84 = "気遣いとかいらないから。#nアタシはもう……自分の青春を探すって決めたんだ。"
51170-85 = "もう、百花繚乱になんか興味ないからさ。"
51170-91 = "……………………そう。"
51170-92 = "そうだよね、アンタはそれを求めてここを出て行った。 "
51170-93 = "……うん。私もそう思ってたから、いいよ。これでこの話は終わり。#nアンタは好きにしたらいい、レンゲ。"
51170-94 = "これでも一応、友達だし……あんたの幸せを願っとくよ。"
51170-95 = "……そうだね、幸せ太りで10キロくらい体重が増えますようにってね。"
51170-96 = "はぁ！？ちょっと何を――"
51170-100 = "あいつ……！言いたい放題いいやがって……！！"
51170-101 = "くっそ……！"
51170-102 = "そっちこそお・し・あ・わ・せ・に！！"
51170-103 = "はぁぁーっ……もう……"
51170-104 = "全部終わったことなのに……#n何で今も……"
51170-106 = "わっ！？"
51170-107 = "どうしたのレンゲ先輩！？"
51170-108 = "レンゲちゃん？"
51170-109 = "ふぁあ……？"
51170-114 = "いや……何でもない。"
51170-115 = "こっちの話というか、終わったことっていうか。"
51170-116 = "百花繚乱……のことですね？"
51170-117 = "まあ、そうだけど…… "
51170-118 = "いや、もう大丈夫。百花繚乱なんか、どうでもいい！"
51170-119 = "せっかくのお祭りなんだ、修行部の一員として楽しまないと……他のことを気にする暇なんてないわけだし。"
51170-120 = "えーと、なんだ……お祭りを楽しむのも修行の一環！#n青春は待っちゃくれない。少女は夜を駆けるべき！"
51170-121 = "なっ！ツバキ部長、ミモリ副部長、カエデ！"
51170-127 = "レンゲちゃんは嘘が苦手なんですね。"
51170-129 = "ん……？"
51170-132 = "「百花繚乱なんか」なんて……本当は思っていないのに。"
51170-133 = "そうそう！レンゲ先輩、ここに来てからずーっと百花繚乱のことばっか話してるじゃんね！"
51170-135 = "い、いや、そこまでは……！？"
51170-136 = "本当に気にしてないなら……電話が終わってから怒ったりしない、と思う。"
51170-141 = "ツバキちゃんの言う通りです。レンゲちゃん、このまま終わらせたくないんですよね？"
51170-142 = "ふっふっふ～！ミモリ先輩はなんと！百鬼夜行最強の読心術師だからね！"
51170-143 = "このお方の前で嘘は通用しな～い！！"
51170-144 = "あっ、カエデちゃんってば……違いますからね！"
51170-150 = "……何でみんなして、そんなこと言うんだよ。"
51170-151 = "もう全部……終わった話だろ。"
51170-152 = "いくら声を上げたって、ナグサ先輩もみんなも帰ってこなかった。"
51170-153 = "それならもう、終わらせた方がいいんだって。"
51170-154 = "すべて投げ出して、青春を探そうって思ったのに……どうして。"
51170-155 = "でも、レンゲ……ユカリに優しかったよね。"
51170-156 = "アタシが？ユカリに……？そんなわけないだろ。"
51170-157 = "あの時アタシはユカリを傷つけるようなことばっか言って……"
51170-158 = "レンゲは、待つ人が苦しむだけなら、無くなればいい、と言ってた。"
51170-159 = "あの時のレンゲの言葉は、ユカリのための言葉……#n後輩が傷つかないための嘘だってみんな気づいてると思うよ。"
51170-160 = "レンゲちゃんはキキョウちゃんと幼馴染だと言っていましたね。"
51170-161 = "…………。"
51170-162 = "本心と違う言葉を口にしちゃうときもありますよ。心配なら、なおさら。"
51170-163 = "心配する気持ちの方が勝って……思ってもない言葉が出てしまう時だって。"
51170-164 = "私にもありますから、よく分かります。"
51170-166 = "えっ、ミモリ先輩も！？"
51170-167 = "ふふっ……ええ、そうですよカエデちゃん。"
51170-168 = "ツバキちゃんと私は幼馴染ですから……#nこれまでに色んなことがあったんですよ？"
51170-169 = "ね、ツバキちゃん。"
51170-171 = "……本気で怒った時のミモリは怖いよ。"
51170-173 = "それは私も分かるかも～！"
51170-174 = "え、ええっ？"
51170-175 = "二人とも……"
51170-179 = "ですからレンゲちゃん。"
51170-184 = "アタシはもう……"
51170-185 = "百花繚乱をやめて、修行部に体験入部してるのに……今更……"
51170-186 = "でもレンゲちゃんは、まだあるんですよね？#n大切な人たちに伝えたい言葉が。"
51170-187 = "……まだ、いいのかな……図々しいとか、思われないかな。"
51170-188 = "大事なのは「気持ち」だと思いますよ、レンゲちゃん。"
51170-189 = "ミモリ副部長……。"
51170-195 = "……レンゲの体験入部はここで終わり。これは部長命令。"
51170-197 = "へっ！？"
51170-199 = "やりたい事、やっておいで。"
51170-200 = "私たちもお手伝いしますので。"
51170-201 = "元修行部のよしみで、ね！でしょ？"
51170-203 = "ツバキ、ミモリ、カエデ……。"
51170-209 = "……うん。分かった。"
51170-211 = "キキョウから聞いたんだ。"
51170-212 = "ユカリにつらい思いをさせたかもしれないって。"
51170-213 = "心配だから見に行ってくれないか、って。"
51170-215 = "……自分でやればいいのを人にやらせるあたり、アイツらしいけど。"
51170-216 = "アタシ、ユカリと話してみるよ。"
51170-219 = "ええ。それでは今から会いに行きましょう。"
51170-220 = "よし！みんなでしゅっぱーつ！"
51170-222 = "みんな、ありがとな。"
51170-230 = "あ、花火！"
51170-231 = "お祭りが始まったみたいですね。"
51170-232 = "私たちも遅れる前に――"
51170-237 = "うわああっ！に、逃げろ！！"
51170-242 = "どうしたんだろう。"
51170-253 = "……えっ、えっ？ツバキ先輩、ミモリ先輩！あ、あれ何……！？"
51170-254 = "！！"
51170-256 = "う～ん、分かんないけど……#nお友達になれそうな感じじゃないねぇ～"
51170-266 = "っ……！#nみんな気をつけろ！"
51170-267 = "来るぞ！！"
51170-278 = "なな、なにこれーっっ！！？"
51170-284 = "うにゃぁああっ！？"
51170-297 = "部長！大丈夫ですか！？"
51170-298 = "部長……！！"
51170-300 = "あっ、う、うん！"
51170-301 = "私は大丈夫……でも、お祭り会場が……！"
51170-302 = "この怪物……どこから来たのっ！？"
51170-304 = "部長、これ……前に空が赤く染まった時と同じに……"
51170-305 = "え、ええっ！？#nあ、あの時と……同じ、ですか！？"
51170-306 = "部長……イズナちゃん！#nど、どうしましょう！？"
51170-308 = "どどどうしよう！？"
51170-309 = "うわっ！あっちにもいる……！"
51170-314 = "（ここは逃げるべき！？）"
51170-315 = "（でも、まだ会場に人が残ってるのに……）"
51170-316 = "（でもでも、イズナとツクヨまで危険にさらすわけには……）"
51170-324 = "うわわっ！？"
51170-325 = "部長！！"
51170-332 = "ご心配には及びません！部長、ツクヨ殿！"
51170-335 = "い、イズナ？"
51170-336 = "イズナちゃん……？"
51170-338 = "今、[ruby=ここ]百鬼夜行[/ruby]には主殿がいますから！"
51170-339 = "主殿は私たち忍術研究部を頼ってくれたのです！"
51170-345 = "イズナはそれに応えるために全力を尽くします！"
51170-346 = "……そうだね！イズナの言う通りだ。#nよーし、じゃあまずは、ここのみんなを助けよう！ "
51170-347 = "絶対、先生殿がなんとかしてくれる！"
51170-352 = "それまで我々、忍術研究部――特殊エージェント一同で、みんなを守りぬくよ！"
51170-354 = "は、はいっ、分かりました！"
51170-355 = "はい！それでは作戦開始です！ニンニン！"
51170-365 = "カホ副部長！お祭り会場の周囲に正体不明の何かが出現……騒ぎが起きているようです！"
51170-366 = "西地区では負傷者が続出しているとのことです！"
51170-367 = "カホ副部長！商店街に正体不明の怪物が現れたという通報が……！"
51170-369 = "カホ副部長！一体どうすれば……！！"
51170-371 = "皆さん、落ち着いてください……！"
51170-372 = "これは……一体……。"
51170-373 = "お祭り会場に正体不明の怪物……一体どうすれば……。"
51170-374 = "お祭りの開始と同時に動き出した未知の襲撃者……これを予見する手掛かりは……ただ一つ。"
51170-379 = "お祭りの開始と同時に動き出した未知の襲撃者……これを予見する手掛かりは……"
51170-380 = "ただ一つ。"
51170-382 = "……花鳥風月部。"
51170-387 = "あの手紙は単なる脅し……いつものボヤ騒ぎ程度だと判断した。"
51170-392 = "その程度の些事にシャーレを巻き込んで、借りを作るのは避けたい……そう思ったのに。"
51170-393 = "……最初から、判断ミスだった？"
51170-395 = "そもそも花鳥風月部は、記録上にしかない、言い伝えの存在。"
51170-396 = "実体を想定すべきだった――というのか。"
51170-397 = "どこで何を見落とした……？#n私の思い至らなかった要素……何か別の手掛かりが……？"
51170-399 = "ニヤ様。"
51170-401 = "……タイミング的に、やはりクズノハと関係が……？#nいや、それとも……"
51170-402 = "ニヤ様……。"
51170-403 = "百花繚乱の方に……？#n行方を[ruby=くら]晦[/ruby]ませた委員長…‥何か我々の知らない情報が……？"
51170-404 = "脅威に備えるためには、そちらを探るべきだった……？ "
51170-405 = "ニヤ様……！"
51170-406 = "私の知らない……得られなかった情報を集めなければ……#n一体どこで何を見落としたのかを把握しないと――"
51170-411 = "ニヤ――"
51170-422 = "ニヤ部長、めっ。#nデコピンだよ～"
51170-430 = "あうっ……！？#nち、チセ……！？"
51170-431 = "チセちゃん！？"
51170-436 = "………………。"
51170-437 = "！！"
51170-438 = "恐るるな"
51170-439 = "目をそらさずに"
51170-440 = "向き合ってこ～"
51170-441 = "部長。じっとしてちゃだめ。"
51170-442 = "ほら、みんな怖がってる。"
51170-447 = "チセちゃん……。"
51170-448 = "……あ。"
51170-449 = "ああ……"
51170-450 = "…………。"
51170-455 = "にゃははっ、そうだね。チセの言う通りだ。"
51170-456 = "[ruby=おんみょう]陰陽部[/ruby]の部長だもの、こんな状態ではお手本にならない。"
51170-457 = "カホ、お祭り運営委員会に連絡をお願いできる？#n現状の共有を。"
51170-459 = "は、はい！"
51170-466 = "あれ……繋がらない……#n何かに通信を邪魔されている、ような……？"
51170-467 = "ふむ……まぁ、そういう事をしていてもおかしくないねぇ。"
51170-468 = "そうねぇ……うん、じゃあそっちは私が行ってくるから……"
51170-469 = "カホは、お祭りに協力してくれた百鬼夜行の商会に、聞き込みをしてくれる～？"
51170-470 = "今は状況を整理して基盤を作るのが先決。#n時間別、種類別に情報の取りまとめを頼めるかな～？"
51170-471 = "責任の追及は後からでもできるからね、よろしく。"
51170-473 = "……はい、承知しました。#nお任せください！"
51170-474 = "ではみなさん、これより私たち陰陽部は、ニヤ様の指示の下動きます！"
51170-476 = "ここからは時間勝負です！全力で参りますよ！#nよろしくお願いいたします！"
51170-477 = "はい！！"
51170-479 = "次回;街を歩く怪談（２）"
