[translation]
51210-1 = "第21話;それでもあなたに"
51210-3 = "ハァッ！"
51210-15 = "雑魚はなんとか倒せたけど、やっぱり……"
51210-23 = "[ns] \"クロカゲには攻撃が通らないね。\""
51210-24 = "立て直しを図っているのか、向こうも大人しくなりましたが……"
51210-25 = "またいつ仕掛けてくるか分からないね～"
51210-26 = "これじゃあ、さっきのヤツ倒しに行けないじゃん！"
51210-27 = "うわぁあん！どうしよう～～！？"
51210-29 = "このままじゃユカリが……"
51210-30 = "そんなのダメだ、なんとか方法を探さないと……！"
51210-31 = "なあ、キキョウ！？"
51210-32 = "…………。"
51210-38 = "[ns] \"ナグサ。\""
51210-42 = "[ns1] \"シュロがユカリを狙っている事、そして――\"\n[ns2] \"この状況が、すべて策略によるものだったというのも理解した。\""
51210-45 = "[ns] \"「百物語」を作るって、どういう意味なのか教えてくれないかな？\""
51210-47 = "[ns] \"シュロは……ユカリで何をする気なの？\""
51210-48 = "それは……"
51210-49 = "ぐだぐだ言ってないで……"
51210-50 = "今はユカリを助ける方が先じゃないのか！？"
51210-52 = "ナグサ先輩は「アヤメの時みたいに」って言ってたよね。"
51210-56 = "キキョウ……？"
51210-61 = "レンゲ、情報は大事だよ。#n悔しいけど、あいつの言う通り私たちは何も知らない。"
51210-62 = "何が正しいのか、どう対処しなきゃいけないのか……何も。"
51210-63 = "情報がないと判断できない。"
51210-64 = "先生はそれを聞いてるんでしょ？#n今ここで情報持ってるのは、ナグサ先輩だけなんだから。"
51210-66 = "私、だけ……。"
51210-67 = "だから教えて。#nあいつの狙いと……私たちはどうすればいいのか。"
51210-68 = "それが分かるのは、ナグサ先輩――あんたしかいないの。"
51210-72 = "………………。"
51210-73 = "……そっか。"
51210-74 = "こんな状況でも、私たちには――"
51210-75 = "花鳥風月部は……"
51210-80 = "ナグサ先輩……？"
51210-86 = "その昔……百鬼夜行が連合になるよりも前、猛威を振るっていたという……魑魅魍魎の集団。"
51210-87 = "彼女らのことを指すの――"
51210-88 = "[ns3] \"「百鬼夜行の連合の今の形態を認めない、極悪非道の部活」\"\n[ns4] \"｢怪書を操り、人々を惑わす魑魅魍魎」……だっけ。\""
51210-91 = "……そう。"
51210-92 = "理由も狙いも、何も分からない……でも手段は確実に存在する。"
51210-93 = "怪書「稲生物怪録」と呼ばれる本を利用して、自分たちの喜悦……#n風流のために……「百物語」という怪談を生み出そうとしている。"
51210-94 = "実際に、私が行った大雪原で花鳥風月部の部長であるコクリコは……アヤメを……"
51210-95 = "……「百物語」にして、「黄昏」の向こうへと連れていったの。"
51210-101 = "私はそれを見ていることしかできなくて……ただただ、無力で……。"
51210-103 = "アヤメ委員長はそれで……"
51210-104 = "……。"
51210-106 = "シュロの言葉が本当なら、今回はユカリを狙っているんだと思う。"
51210-107 = "このままじゃ、ユカリもアヤメみたいに……。"
51210-108 = "どうして……アタシたちに何も言ってくれなかったんだ？"
51210-109 = "怖かったの……本当のことを、言うのが。"
51210-116 = "……ナグサ先輩。"
51210-124 = "なっ、誰だ！？"
51210-126 = "あ、あ――手前さん方ぁ、見えますかぁ？"
51210-130 = "あっ、先生！あっちに……！"
51210-138 = "アハハッ！お祭り、楽しんでますかぁ～？"
51210-139 = "楽しんでくださってますよねぇ……？"
51210-140 = "手前どもが全力を尽くして、手前さん方を楽しませるために用意したのですからぁ。"
51210-144 = "あれは、陰陽部の放送用飛行船……"
51210-145 = "ネットでも中継されてしまっています……！"
51210-146 = "なっ、ど、どうやって！？#nそんなことまでできんのかよ！"
51210-147 = "[s] \"シズコがお祭りのために準備してたやつだ……。\""
51210-148 = "でも、どうして放送なんか……。"
51210-150 = "アハハッ、手前が用意したのはそれだけじゃないんですよぉ。"
51210-151 = "手前さん方に、ご紹介したいお客さまがおりましてぇ？"
51210-155 = "ご存じの方もいるでしょうけどぉ――20年の時を経て再現されたこのお祭りで、手前さん方から期待を集めている”あの”お方！"
51210-164 = "[ns] \"ユカリ……！\""
51210-165 = "アハハッ！よ～く見えてますかぁ？"
51210-166 = "ま、このために準備したんですし？#nよく見えて当然ですけどぉ。"
51210-167 = "この物語の主人公を、ご紹介しますぅ。"
51210-169 = "…………。"
51210-171 = "今は眠り姫のように静寂を貫いていますが、手前には分かっているのですよぉ。"
51210-172 = "この巫女は……誰よりも何よりも大きな傷を胸に秘めているって、ねぇ？"
51210-175 = "憧れの人には振り向いてもらえず――"
51210-178 = "――元に戻りたいと訴えても、無意味だと一蹴され。"
51210-180 = "帰りたいと声を上げても、別の帰る場所があると否定され――"
51210-182 = "巫女様はとうとう自分の場所へと帰りました……そう、ここに！"
51210-184 = "しかし、しかし、可哀相なことに……#n唯一の帰る場所だと思っていたそこで、巫女様に求められたのは――"
51210-185 = "20年前の汚名を返上してほしい――ただそれだけ。"
51210-186 = "…………。"
51210-187 = "そうなんです。誰一人、巫女様の気持ちになんて興味がないのです。"
51210-188 = "ああ！ああ！お可哀想に……#n皆が笑顔になるはずのお祭りで、ひとり悲しみに暮れているなんて。"
51210-189 = "……悔しく、ないですかぁ？"
51210-190 = "その感情をひとりで抱えて苦しむくらいなら……#nいっそのこと、みんなで抱えた方が、よくありませんかぁ？"
51210-194 = "ですから、手前さんの代わりに手前が声を上げましょ。#n手前さんの代わりに、その感情を手前さん方に返して差し上げます！"
51210-195 = "さあさ、これより始まるのは、手前ども花鳥風月部の風流――"
51210-196 = "美しく、艶やかに煌びやかに、百鬼夜行を燃やし尽くして差し上げましょ！"
51210-197 = "手前さん方、どうぞご期待くださいなぁ！アハハハッ！ "
51210-204 = "[ns] \"ユカリ……！\""
51210-206 = "百鬼夜行を燃やす、って言ってたね。"
51210-207 = "早く止めないと……今以上に大変な事態になってしまいます。"
51210-208 = "は、早く行かないと……！"
51210-213 = "[ns] \"クロカゲが、動き出した……！\""
51210-214 = "くそっ……！"
51210-215 = "攻撃が通らないヤツなんて、一体どうしたらいいんだよ！"
51210-216 = "というか、そもそもコイツをどうにかしたところで……#n銃が効かないあいつをどうやって倒すんだ！？"
51210-217 = "……方法なら、ある。"
51210-221 = "キキョウ、本当か……！？"
51210-225 = "[ns] \"これは……百花繚乱の委員長用の……？\""
51210-230 = "そう。ナグサ先輩……あなたが私に残していった「百蓮」。"
51210-231 = "シュロの言葉が本当なら……"
51210-232 = "シュロを倒せるのはただ一人……証を持つ者だけ。#nつまり――"
51210-238 = "ユカリを助けられるのは……ナグサ先輩、あなたしかいない。"
51210-239 = "だからお願い、先輩。#nユカリを助けてあげてほしい。"
51210-240 = "そ、そうだな……たしかに委員長の資格を持つナグサ先輩なら……"
51210-244 = "わたし、は…… "
51210-249 = "でき、ない。"
51210-251 = "はっ！？な、何でだ！？"
51210-253 = "シュロが言っていた、「委員長としての資格を備えている者」……#nそれは、アヤメのことであって、私じゃない。"
51210-254 = "私には……できない。"
51210-255 = "シュロの言う通り……最初から全部、言い訳だったの。"
51210-256 = "自分の本当の姿を知られるのが怖くて、私は逃げようとした。"
51210-257 = "本音を話せずに、アヤメの隣に立つことが精一杯で……#nなんとか隣に立てるよう、「ナグサ」という女の子を演じていた。"
51210-258 = "みんなを、騙していたんだよ。"
51210-259 = "私そのものが……「コスプレ」だったんだ。"
51210-260 = "[s] \"ナグサ……。\""
51210-263 = "ただアヤメの隣にいたくて……アヤメに[ruby=ふさわ]相応[/ruby]しい存在になりたくて。"
51210-264 = "優等生を演じただけの――ニセモノ。"
51210-265 = "……言えなかったの。アヤメを目の前で失って、ここに戻った私が……一人で戻った、なんてみんなに言ったら……"
51210-270 = "絶対に――後ろ指を差された。"
51210-272 = "こんな私に、資格なんてない。"
51210-273 = "こんな私が……ユカリを助けられるわけ――"
51210-279 = "御稜、ナグサ……！！"
51210-284 = "あ……。"
51210-289 = "[ns] \"キキョウ、落ち着いて……！\""
51210-304 = "キキョウ……？"
51210-305 = "私、ユカリに酷いこと言った。"
51210-306 = "あんたには帰る場所があるからって。#n百花繚乱ごっこは要らないでしょって。"
51210-307 = "そんなの思ったことなかったのに……ユカリのためって、自分を騙して……一方的に突き放したの。"
51210-309 = "それが……あの子をあんな風にしてしまった。"
51210-310 = "キ、キョウ……。"
51210-315 = "……。"
51210-316 = "あなたが……私たちを見捨てて出てったことは、今でも許せない。"
51210-317 = "今までずっとあなたを待ってたのに、帰ってこなかったことも……。"
51210-322 = "……でも。"
51210-323 = "でもね。"
51210-325 = "私のせいで……"
51210-326 = "私の、身勝手な発言で傷つけてしまったあの子を……"
51210-327 = "ユカリを助けられるのは、あなたしかいないの。"
51210-328 = "私でもレンゲでもない、そしてアヤメ委員長でもない……#n[ruby=・   ・   ・]あなた[/ruby]しかいない。"
51210-330 = "だから、お願い。"
51210-331 = "自分勝手なお願いだって、分かってる。#n今さらムシが良すぎるって。"
51210-332 = "それでも、お願い……！"
51210-333 = "あの子に、謝りたいの……！"
51210-334 = "お願い……ナグサ先輩。"
51210-336 = "どうか……"
51210-339 = "ナグサ先輩！"
51210-343 = "あ……"
51210-344 = "アタシも……アタシもそうなんだ！"
51210-345 = "アタシだって、こんなことを言う資格はないって分かってるけど！"
51210-346 = "キキョウと一緒なんだ！"
51210-347 = "アタシも、ユカリを傷つけてしまったから……謝りたい。"
51210-348 = "もう一度、会ってちゃんと話したい。"
51210-349 = "我が儘を言っているのは承知だ。こんな事態になって今さら謝罪したいなんて、自己満足にもほどがあるけど……"
51210-350 = "……でも。"
51210-355 = "ユカリが言うように、あの時に戻れるのなら……アタシも……！"
51210-356 = "だから頼む、ナグサ先輩。"
51210-362 = "…………私は、みんなを騙して……"
51210-363 = "嘘を、ついて……"
51210-369 = "[ns] \"ナグサ、私からもお願い。\""
51210-382 = "……分かった。 "
51210-392 = "やってみるよ。"
51210-404 = "[ns] \"やっぱり簡単には通してくれなさそうだね。\""
51210-405 = "先生たちは先に行って……！#nここはアタシらに任せてくれ！"
51210-406 = "そうだね。やる事が決まったからもう大丈夫～#n最大限、足止めすればいいんだよね？"
51210-407 = "分かりました。足止めならお任せください！"
51210-408 = "任せてよ、先生！"
51210-410 = "ナグサ先輩、先生……ユカリを、どうかお願い。 "
51210-412 = "[ns] \"うん、行こう！ナグサ！\""
51210-419 = "……！"
51210-421 = "次回;炎に包まれた街"
