[translation]
52030-1 = "Episódio 3; Um Novo Festival"
52030-5 = "Ei, não derrubem isso!"
52030-6 = "Cuidado com o passo, vão devagar."
52030-12 = "Epa...! Essa placa não é maior do que o que tínhamos combinado?"
52030-13 = "Será que foi um erro de pedido do Comitê de Operações do Festival...?"
52030-14 = "Não, essa é uma encomenda especial do Clube Yin-Yang. #n Dizem que ela é desse tamanho mesmo."
52030-15 = "Parece que eles querem exibir um haiku escrito à mão pela Chise-sama. #n E querem que fique visível de qualquer lugar do local do festival."
52030-29 = "Uau...!?"
52030-30 = "Não corram aqui! É perigoso, não é?"
52030-35 = "Ei, vocês estão bem?"
52030-40 = "Tsc, falhamos..."
52030-44 = "Hmm...?"
52030-50 = "Líder! #n A 'operação para destruir e substituir a placa da Chise-sama' falhou!"
52030-55 = "Hm... nós tínhamos planejado essa operação?"
52030-56 = "Ah, então como esperado da trupe Chimi, #n a 'operação de troca rápida durante o tiroteio' é melhor!?"
52030-58 = "Trupe Chimi...? #n Já ouvi esse nome em algum lugar――"
52030-62 = "Ah! Lembrei! #n Aquele grupo de delinquentes que aparece quando o festival se aproxima! #n Então são vocês que exigem propina e roubam os cupons!"
52030-64 = "Hunf. #n Não me importo com outros festivais, #n mas não tenho interesse nenhum nos cupons do 'Festival Waraku'!"
52030-65 = "Isso mesmo! Isso mesmo! #n Não importa o quão incrível seja a Princesa Waraku, #n ela não chega aos pés do carisma da nossa Líder!"
52030-66 = "E-Eu fico feliz que pensem assim, mas..."
52030-67 = "Acho que não é o momento para falar disso..."
52030-69 = "Hã? Então por que estão atrapalhando?"
52030-70 = "Não me diga que vocês realmente guardam rancor da Chise-sama..."
52030-72 = "A Princesa Waraku não tem nada a ver com isso!"
52030-73 = "Essa placa é da competição de haiku da semana passada, não é!?"
52030-75 = "Ah, aquela organizada pelo Clube Yin-Yang? A Chise-sama foi a vencedora, né."
52030-77 = "Exatamente! #n A Líder também participou com muita determinação, mas..."
52030-78 = "Uuu... por causa de uma sabotagem vil, nem conseguimos passar das eliminatórias..."
52030-83 = "Vocês saíram nas eliminatórias, sim!?"
52030-85 = "Todo mundo só elogia a Princesa Waraku, mas os haikus da Líder são muito melhores!"
52030-86 = "Isso mesmo! Minha alma tremeu com os sentimentos contidos nas palavras!"
52030-87 = "Se todos vissem o haiku da Líder, perceberiam o quão maravilhoso ele é!"
52030-89 = "Hehe... estou ficando com vergonha."
52030-93 = "......Então, foi por isso que tentaram substituir a placa!?"
52030-95 = "Porque, Líder, #n você ficou deprimida desde depois da competição, não ficou?"
52030-96 = "Por isso, pensamos que se colocássemos o haiku da Líder bem no meio do local do festival, #n poderíamos espalhar sua genialidade!"
52030-97 = "Já que chegou a esse ponto... #n Vamos fazer com que todos ouçam o haiku da Líder aqui!"
52030-99 = "E-Espere! Isso é――"
52030-106 = "A#n #nco#nmi#nda#n do#n #n fes#n ti#n val"
52030-108 = "Sem#n #n o#n #n cu#n pom#n de#n #n des#n con#n to"
52030-110 = "Não#n #n dá#n #n pa#n ra#n a#n pro#n ve#n it#n ar"
52030-121 = "Viu, Líder! Todos parecem tão emocionados que nem conseguem falar!"
52030-123 = "......Para começar, isso é um haiku?"
52030-124 = "Bem... festival é um termo que remete ao verão, pelo menos."
52030-126 = "Cale a boca, se a Líder disse que é um haiku, então é um haiku!"
52030-127 = "Não tente encaixar a arte em padrões!"
52030-132 = "Acho mesmo que isso não é um haiku..."
52030-134 = "U... uuu...!"
52030-138 = "D-Desse jeito, eu vou destruir esse festival logo de uma vez!"
52030-146 = "Quando pensei que seria barulhento..."
52030-152 = "Q-Quem é você?"
52030-161 = "Entendo o desejo de apresentar seu haiku, mas não permitirei que atrapalhem o festival."
52030-162 = "Não acho nada admirável causar confusão por ressentimento pessoal."
52030-164 = "Pretendem arruinar a juventude de todos?"
52030-165 = "Nós não permitiremos mais nenhum ato de violência!"
52030-171 = "Hi, Hyakkaryouran...!"
52030-172 = "L-Líder, o que fazemos!? #n Parece que tem mais gente do que antes!"
52030-174 = "Para a Hyakkaryouran... eu tenho um plano!"
52030-178 = "É batalha! Hoje vou lavar minha honra...!"
