[translation]
52080-1 = "第8話;悪夢"
52080-7 = "……記憶の中のアヤメは、#n朝の日差しのように明るくてあたたかい子だった。"
52080-8 = "どんなお願いにも嫌な顔一つしない、百花繚乱の委員長。"
52080-9 = "その笑顔に、みんなが安心させられた。"
52080-13 = "お祭りの屋台の人手が足りない？任せて！#n一人暮らしが長いし、料理なら慣れてるの。"
52080-17 = "神木展望台の前で魑魅一座が暴れてるって？#n困った子たちだなぁ。ちょっと行ってくる！"
52080-22 = "お姉ちゃんとはぐれちゃったの？#n……よしよし、私が探してきてあげるからね！#nいい子だから、ここで待ってて。"
52080-28 = "みんな、何かあればアヤメを探して、アヤメに頼った。"
52080-29 = "他の人なら顔をしかめる頼みでも、アヤメはいつも笑ってて――"
52080-33 = "アヤメ委員長！本日のお稽古も、よろしくお願いします！"
52080-39 = "アヤメ先輩。今度のお祭りのスローガンなんですが、ネタ切れで……。"
52080-40 = "悪いんだけどアヤメちゃん、週末に店番をお願いできないかな……？#n来るはずの子が体調崩しちゃってねぇ……。"
52080-46 = "うん！まかせて！"
52080-49 = "それなのに、私ときたら……アヤメに追いつくだけで精一杯だった。"
52080-50 = "少しでも壁にぶつかると、勝手に涙がこぼれる。#n勝負では一度もアヤメに勝てなかった。"
52080-51 = "みんなに頼られるアヤメの姿を目にする度に……#n心の中で、口には出せない言葉が反響する。"
52080-56 = "アヤメがいなければ、何もできない。できるはずがない。"
52080-57 = "私は、アヤメじゃないから。"
52080-58 = "百花繚乱の委員長としての資格があるのは、アヤメだけだから。"
52080-61 = "でも、アヤメはそんな私の気持ちを察して、#nいつも明るい笑顔で手を差し伸べてくれた。"
52080-70 = "大丈夫だよ、ナグサ。"
52080-71 = "だって私は――"
52080-79 = "私は……あんたを友達だと思ったことなんて、ない。"
52080-83 = "……っ！"
52080-88 = "はぁ、はぁ……また、夢……。"
52080-89 = "なんで、ずっとこんな悪夢が……。"
52080-94 = "……もう起きちゃったんですかぁ？"
52080-95 = "枕が変わると寝つきが悪いたちだったんですねぇ、ナグサちゃん。"
52080-103 = "……[ruby=やぶき]箭吹[/ruby]シュロ。"
52080-104 = "はいはぁい。手前ですよぉ？"
52080-105 = "こんなところでまた会えるだなんて、不思議な縁ですねぇ？"
52080-106 = "……いえ、ナグサちゃんの方から首を突っ込んできたんでしたっけ？"
52080-111 = "なんでわざわざ、こんな魑魅魍魎のうろつく土地に来たんですかぁ？"
52080-112 = "幼なじみにまた会えるかも……なぁんて、#nおバカな望みを持ってるとかぁ？"
52080-113 = "……それは、こっちの台詞だよ。"
52080-114 = "ここで何をしているの？#nこの周辺で見つかっている百物語は、あなたの仕業？"
52080-115 = "どうでしょうねぇ[ruby=ものがたり]？怪談は[/ruby]ネタバレ厳禁ですからぁ。"
52080-116 = "再会の挨拶に、覚めない悪夢をお贈りしたかったですけど……#n起きちゃったならしょうがないですねぇ。"
52080-117 = "悪夢を現実にしてあげますよぉ？"
52080-139 = "アハハッ！#nやっぱりあの時「百蓮」が使えたのは、まぐれじゃないんだぁ！"
52080-140 = "まさかまさかぁ……#n自分がアヤメの代わりに百花繚乱のリーダーになれる……#nまだそんなこと思ってるんですかぁ？"
52080-141 = "なれるかなれないか、じゃない。"
52080-142 = "みんなを守るために、私はやるの。#n……委員長のフリだけでも、やってみせる。"
52080-146 = "へぇ～、いいお話ですねぇ。"
52080-147 = "でも……いくら強くなったところで、二人分の働きはできないでしょう？"
52080-148 = "ず～っと襲いかかってくる恐怖に、どれだけ耐えられるんでしょうねぇ。"
52080-159 = "さあ、新しい物語の幕開けといきましょうかぁ？イヒヒッ！"
