[translation]
52080-1 = "Episódio 8; Pesadelo"
52080-7 = "......A Ayame em minhas memórias, #n era uma menina brilhante e calorosa como o sol da manhã."
52080-8 = "A presidente da Hyakkaryouran, que nunca franzia a testa para nenhum pedido."
52080-9 = "Todos se sentiam seguros com aquele sorriso."
52080-13 = "Faltam pessoas nas barracas do festival? Pode deixar comigo! #n Moro sozinha há muito tempo, estou acostumada a cozinhar."
52080-17 = "Disseram que a Trupe Chimi está causando confusão em frente ao Observatório Shinboku? #n Que crianças problemáticas... Vou dar uma passada lá!"
52080-22 = "Você se perdeu da sua irmã mais velha? #n ......Tudo bem, tudo bem, eu vou procurar por ela para você! #n Seja uma boa menina e espere aqui."
52080-28 = "Todos procuravam a Ayame e dependiam dela para tudo."
52080-29 = "Mesmo quando os pedidos eram de gente que franzia a testa, a Ayame estava sempre sorrindo――"
52080-33 = "Presidente Ayame! Por favor, continue nos treinando hoje também!"
52080-39 = "Ayame-senpai. Sobre o slogan do próximo festival, estamos sem ideias..."
52080-40 = "Desculpe incomodar, Ayame-chan, você poderia cuidar da loja no fim de semana...? #n A menina que deveria vir acabou ficando doente..."
52080-46 = "Sim! Pode deixar comigo!"
52080-49 = "E ainda assim, quando se tratava de mim...... eu mal conseguia acompanhar a Ayame."
52080-50 = "Sempre que encontrava qualquer obstáculo, as lágrimas caíam sem eu querer. #n Nunca venci a Ayame em nenhuma disputa."
52080-51 = "Toda vez que via o quanto todos dependiam da Ayame... #n palavras que não consigo dizer em voz alta ecoam no meu coração."
52080-56 = "Sem a Ayame, não consigo fazer nada. Não tem como eu conseguir."
52080-57 = "Porque eu não sou a Ayame."
52080-58 = "Porque a única que tem qualificação para ser a presidente da Hyakkaryouran é a Ayame."
52080-61 = "Mas a Ayame percebia meus sentimentos e #n sempre me estendia a mão com um sorriso brilhante."
52080-70 = "Está tudo bem, Nagusa."
52080-71 = "Porque eu――"
52080-79 = "Eu... nunca te considerei minha amiga, desde o início."
52080-83 = "......!!"
52080-88 = "Haa, haa... de novo, esse sonho..."
52080-89 = "Por que esse pesadelo continua..."
52080-94 = "......Já acordou?"
52080-95 = "Então você é do tipo que tem dificuldade para dormir em lugares diferentes, Nagusa-chan."
52080-103 = "......Shuro Yabuki."
52080-104 = "Sim, sim. Sou eu, viu?"
52080-105 = "Que coincidência estranha nos encontrarmos aqui de novo, não é?"
52080-106 = "......Não, pera, foi você mesma que se meteu nisso, não foi?"
52080-111 = "Por que você veio de propósito para uma terra onde assombrações vagam por aí?"
52080-112 = "Com o desejo idiota de... talvez encontrar a sua amiga de infância de novo?"
52080-113 = "......Essa frase deveria ser minha."
52080-114 = "O que você está fazendo aqui? #n As 'Hyakumonogatari' encontradas por aqui são obra sua?"
52080-115 = "Quem sabe? Histórias de fantasmas não devem ter spoilers."
52080-116 = "Eu queria te presentear com um pesadelo sem fim como saudação de reencontro... #n mas se você já acordou, não tem jeito."
52080-117 = "Vou transformar seu pesadelo em realidade, então!"
52080-139 = "Ahaha! #n Como eu pensei, não foi por sorte que você conseguiu usar a 'Hyakuren' naquela hora!"
52080-140 = "Não acredito, não acredito... #n Você ainda pensa que pode se tornar a líder da Hyakkaryouran no lugar da Ayame...?"
52080-141 = "Não é sobre ser capaz ou não."
52080-142 = "Para proteger a todos, eu farei isso. #n ......Mesmo que seja apenas fingindo ser a presidente."
52080-146 = "Heh, que história bonita."
52080-147 = "Mas... mesmo que você tenha ficado forte, não consegue fazer o trabalho por duas, certo?"
52080-148 = "Por quanto tempo você acha que vai aguentar o medo que continua vindo atacar?"
52080-159 = "Vamos, que comecem as cortinas de uma nova história, certo? Ihihi!"

