[translation]
52170-1 = "Episódio 17; O Retorno da Presidente"
52170-4 = "......Orçamento adicional para a montagem do local."
52170-5 = "......Termo de nomeação do gerente de segurança do festival."
52170-6 = "Relatório de auditoria de subsídios do Clube Yin-Yang......"
52170-10 = "Uuu...... uuuu......!"
52170-11 = "Por que será que estou lutando contra esses papéis um dia antes do 'Festival Waraku'......?"
52170-12 = "Meu plano de jogar toda a papelada para a Kaho e ir passear na cidade... não, de ir fazer uma inspeção――"
52170-15 = "Bem, estamos indo para o ensaio. #n Por favor, cuide do processamento das solicitações que se acumularam enquanto estivermos fora."
52170-16 = "Estamos indo~"
52170-17 = "Ei!? Eu também vou junto......!"
52170-18 = "Claro, você pode vir se quiser."
52170-19 = "Desde que termine toda a papelada do Festival Waraku com prazo vencido, as solicitações e o restante do trabalho administrativo, é claro."
52170-20 = "Auuu......!"
52170-21 = "Tenho fechado os olhos para suas inúmeras negligências no trabalho, mas......"
52170-22 = "Se a negligência da Niya-sama acabar afetando o Festival Waraku......"
52170-23 = "Desta vez―― não deixarei barato, entende?"
52170-24 = "A expressão da Kaho é assustadora~"
52170-25 = "T, tudo bem......"
52170-28 = "A Kaho parece estar mais perspicaz do que antes......"
52170-29 = "Ah, eu também queria ter visto o ensaio da Chise-nyan......"
52170-30 = "Será que não tem alguma desculpa por aí para adiar esse trabalho de escritório......"
52170-31 = "Por exemplo, uma visita inesperada, ou algo assim......"
52170-37 = "Niya-sama, desculpe interrompê-la em um momento ocupado."
52170-38 = "Há um visitante. Parece ser um assunto urgente......"
52170-39 = "Ah, uma desculpa surgiu......!"
52170-40 = "Uma desculpa?"
52170-41 = "N, não, não é nada."
52170-42 = "Mas, quem viria nos visitar nesta época...... quem é?"
52170-43 = "Seria uma academia querendo visitar o 'Festival Waraku'?"
52170-44 = "Não, sobre isso......"
52170-45 = "A presidente do Comitê de Mediação de Conflitos Hyakkaryouran, Ayame Nanakado, está aqui."
52170-46 = "A presidente Ayame......?"
52170-51 = "Faz tempo, Niya-sama."
52170-52 = "Você tem passado bem?"
52170-53 = "Nyaha...... estou bem, mas nem tudo está correndo conforme o planejado."
52170-54 = "Várias coisas aconteceram em Hyakkiyako enquanto você estava ausente."
52170-55 = "Peço perdão por ter abandonado meus deveres como presidente e me ausentado por tanto tempo. #n Causei muitos transtornos."
52170-56 = "Não, não, conseguimos seguir em frente de alguma forma. Fufu."
52170-60 = "Então...... você está sabendo que o pessoal da Hyakkaryouran foi para a Filial Ebisu procurando pela 'Presidente Ayame'?"
52170-61 = "Sim. Encontrei a Nagusa e as outras lá."
52170-62 = "Então, por que você voltou sozinha......?"
52170-63 = "E...... onde está o Sensei da Schale, que deveria estar acompanhando vocês?"
52170-64 = "É exatamente sobre isso que é meu assunto urgente......"
52170-65 = "Enquanto procurávamos a base do Clube das Flores, Pássaros, Vento e Lua no Grande Campo de Neve, fomos atingidas por uma avalanche repentina."
52170-66 = "Tive sorte de sair ilesa, mas todas as outras ainda estão sob a neve. #n Gostaria que despachassem uma equipe de resgate o quanto antes――"
52170-67 = "......Hum. É uma situação que requer urgência."
52170-68 = "Você ouviu, né?"
52170-72 = "Chamou, Niya-sama?"
52170-73 = "Despache imediatamente alunos com alta mobilidade para o Grande Campo de Neve do Distrito Norte. #n Informaram que o pessoal da Hyakkaryouran e o Sensei [USERNAME] sofreram um acidente."
52170-74 = "S, sim senhor!"
52170-81 = "......Agradeço pela resposta rápida. Como esperado da Niya-sama."
52170-82 = "Não há de quê~ é meu dever como chefe do Clube Yin-Yang."
52170-83 = "Bem, vou voltar para a minha sala――"
52170-91 = "Com licença."
52170-92 = "Desculpe incomodá-la enquanto está cansada, mas posso fazer uma pergunta?"
52170-95 = "Sim, claro."
52170-98 = "As pessoas que sofreram o acidente são...... todas as integrantes da Hyakkaryouran e o Sensei, correto?"
52170-99 = "......? #n O que você quer dizer com isso?"
52170-100 = "Ah, se está falando da Nagusa e da Kikyou――"
52170-101 = "Não, estou falando da presidente da Hyakkaryouran, Ayame Nanakado."
52170-102 = "Você está fingindo ser ela―― você é apenas uma 'sombra', não é?"
52170-103 = "O que está......"
52170-104 = "Você achou mesmo que conseguiria esconder? #n ――espalhando tanto mal por aí?"
52170-105 = "Além disso...... 'Ayame Nanakado abandonando seus amigos no meio de uma crise'―― #n isso nem serve de piada."
52170-110 = "Então, onde está a Ayame? #n ......Hyakumonogatari."
52170-111 = "......Como esperado da presidente Niya. #n Que percebeu tão rápido."
52170-116 = "......!"
52170-117 = "Mas...... que problemático."
52170-123 = "Eu, na verdade, não sou muito ligada a amigos."
52170-125 = "Próximo Episódio; Sonhos de Camas Diferentes"

