[translation]
52190-1 = "Episódio 19; Memórias do Outro Lado"
52190-5 = "Tem certeza de que o 'Templo do Crepúsculo' fica por aqui?"
52190-6 = "......Sim, está correto."
52190-7 = "Mesmo neste campo de neve, existem sinais pelo caminho."
52190-8 = "Árvores cobertas de neve, um rio congelado―― aquele morro também."
52190-9 = "É...... igual à paisagem daquela época."
52190-10 = "Nagusa-chan, sua atenção aos detalhes estranhos é útil nessas horas, né?"
52190-11 = "Bem, então vamos."
52190-18 = "......Ela comeu algo estranho ou o quê?"
52190-19 = "De repente nos soltou...... não sei o que ela está planejando."
52190-20 = "Quem sabe. Mas não dá para confiar no Clube das Flores, Pássaros, Vento e Lua."
52190-21 = "Com certeza tem algo por trás disso."
52190-22 = "Eu também acho...... afinal, eles são os responsáveis por trazer o caos para Hyakkiyako. Não dá para confiar."
52190-23 = "Só que...... tenho a impressão de que ela está agindo por conta própria."
52190-24 = "Talvez possamos escapar dos olhos vigilantes do Clube das Flores, Pássaros, Vento e Lua."
52190-25 = "Ora, ora? Você não está pensando em fugir, está?"
52190-26 = "Não pense em nada ridículo, tá? #n Não importa o quão rápido você corra, não vai conseguir escapar de mim!"
52190-27 = "Além disso...... pode ser que, sem querer, o cano da minha arma acabe apontando para a cabeça do Sensei―― #n não acha?"
52190-28 = "......Hunf."
52190-30 = "[ns] \"Ah, eu sou o refém?\""
52190-31 = "Hã?"
52190-32 = "Você manipula as alunas com palavras, #n mas não aguenta nem um único tiro, né? #n É óbvio que todos vão mirar em você primeiro."
52190-33 = "E ainda por cima, se atira na frente sem nem cuidar da própria vida. Sério......"
52190-46 = "......Realmente, uma idiota."
52190-47 = "[s] \"Não precisa ser forte para proteger alguém.\""
52190-48 = "Haa, de novo com isso......"
52190-49 = "Uma pessoa fraca que nem consegue se proteger querendo cobrir outra...... isso realmente tem algum sentido? #n Você não vai apenas acabar caindo antes de quem você tenta proteger e terminar tudo?"
52190-50 = "Com que lógica você faz isso? #n Eu não entendo nada!"
52190-51 = "[s1] \"Como eu disse antes, meu corpo simplesmente se move quando vejo alguém em perigo......\"\n[s2] \"Independente de ser racional ou normal.\"\n[s3] \"É o que se espera de um ser humano.\""
52190-55 = "E, esperado......?"
52190-56 = "Isso não é......"
52190-57 = "Não tem nada de esperado nisso!"
52190-61 = "Haa, haa......"
52190-62 = "Tão, tão ridículo......"
52190-63 = "Vamos logo para o Templo do Crepúsculo...... #n Não pense em fugir, entendeu?"

