[translation]
61060-1 = "Episódio 6; A Cadeira do Outro Lado"
61060-6 = "……O sol vai se pôr em breve."
61060-7 = "É verdade. Vamos nos apressar um pouco."
61060-11 = "……."
61060-12 = "Hiyori? Aconteceu alguma coisa?"
61060-13 = "É que…… re-realmente vamos voltar para Arius… a ficha caiu, ehehe……."
61060-14 = "Não adianta pensar muito nisso. Só temos que fazer o que precisa ser feito."
61060-15 = "Eu parei de tentar encontrar significado em cada acontecimento."
61060-16 = "Boa mentalidade. Você amadureceu."
61060-21 = "Líder, cala a boca. Você sempre some por conta própria."
61060-22 = "Guuh……."
61060-23 = "Mas, não fica um pouco feliz que a Sa-chan assumiu a liderança de novo?"
61060-24 = "É apenas temporário, claro."
61060-25 = "Is-isso é……!"
61060-26 = "……Esquece. #nDe qualquer forma, não importa o que eu diga, a decisão da Princesa não vai mudar."
61060-27 = "Você não é nada sincera."
61060-28 = "Eu já disse que não é isso!"
61060-30 = "[ns]\"É maravilhoso ver como vocês se dão bem.\""
61060-31 = "Até você, Sensei…… Se continuar dizendo essas coisas, vamos te deixar para trás."
61060-32 = "Fufu. Fiquei surpresa no começo, mas…… fico feliz que o Sensei tenha vindo conosco."
61060-34 = "A-a escolta, pode deixar…… comigo. Ehehe……."
61060-36 = "Sensei, tenho um pedido."
61060-37 = "Poderia dar aulas para o pessoal de Arius?"
61060-38 = "Claro, a prioridade deve ser a segurança do Sensei."
61060-39 = "Seja por aulas remotas ou de forma indireta. #nNão pouparei esforços para realizar o que você deseja."
61060-40 = "Pode ser que isso acabe ignorando a vontade do pessoal de Arius, mas……."
61060-41 = "……Sim? #nDar aulas no local……!?"
61060-43 = "……."
61060-44 = "Eu achei que a missão fosse ajudar com os preparativos para as aulas remotas."
61060-45 = "Que nós iríamos até Arius para convencer os alunos que ficaram lá."
61060-46 = "Quem diria que acabaria virando uma missão de escolta……."
61060-47 = "[ns]\"Desculpe, acabei aumentando o seu trabalho.\""
61060-48 = "N-não…… não é algo com que o Sensei deva se preocupar."
61060-49 = "Na verdade…… #ncomo alguém que já esteve em Arius, fico pensando se não estou causando problemas para o Sensei……."
61060-50 = "Sinto muito por fazer o Sensei se preocupar."
61060-51 = "Aproveitando, só para confirmar."
61060-52 = "Por que você decidiu ir a um lugar tão perigoso?"
61060-56 = "[ns1]\"Não é um motivo muito importante.\"\n[ns2]\"Porque…… tem alunos lá, eu acho.\""
61060-60 = "[ns]\"……O que acha? Não foi um pouco legal da minha parte?\""
61060-61 = "Ah, hã? É……?"
61060-62 = "……Entendi uma coisa muito bem."
61060-63 = "Sensei…… às vezes, você é muito bobo……."
61060-65 = "[ns]\"Não diga isso…….\""
61060-66 = "Hmm……."
61060-67 = "Mas acho que isso é a cara do Sensei."
61060-68 = "Às vezes, a gentileza pode acabar machucando o coração, não é?"
61060-69 = "Sim, eu disse isso de propósito, sabendo disso."
61060-75 = "A-Atsuko……!?"
61060-76 = "Se-Sensei…… eu entendo…… às vezes o peito aperta tanto que a gente acaba se encolhendo, não é……."
61060-77 = "Tá, tá, chega de teatro, levante-se. Ainda temos um longo caminho pela frente."
61060-79 = "Então, pessoal, peço uma salva de palmas."
61060-80 = "――Para celebrar o retorno de uma amiga querida."
61060-86 = "Ah, ahaha... Bem, eu estou toda esfarrapada, mas..."
61060-87 = "Ainda assim, seu halo está intacto, não está?"
61060-88 = "Você protegeu algo que não pode ser substituído. #nO resto, a gente dá um jeito depois."
61060-93 = "Nós ainda temos... tempo."
61060-94 = "...Maia. Obrigado por estar a salvo. #nE... bem-vinda de volta."
61060-95 = "E-estou de volta... é...! Senpai!"
61060-96 = "Sinto muito por não poder fazer nada grandioso para comemorar seu retorno."
61060-97 = "N-não diga isso! #nNa verdade, eu estava com saudades desse tipo de ambiente..."
61060-98 = "Falando nisso, como foi o \"lado de fora\"? #nEu adoraria ouvir da própria Maia."
61060-99 = "O lado de fora... é? #nBem, vejamos..."
61060-100 = "...Foi fascinante."
61060-101 = "E também, lindo..."
61060-106 = "..."
61060-108 = "Eu vi muitas coisas. #nPrédios altíssimos cobertos de vidro."
61060-109 = "Um rio enorme, com pontes atravessando-o."
61060-112 = "Quando anoitecia, as luzes dos prédios e da cidade se refletiam no rio..."
61060-113 = "Balançando na água, parecia que eu estava dentro de um sonho."
61060-115 = "Havia também prédios construídos para apresentações musicais."
61060-116 = "Aqui, eu só conseguia tocar escondida, esperando a \"Madame\" não estar por perto."
61060-119 = "E parece que as apresentações acontecem mais à noite do que de dia."
61060-120 = "Por isso, foram projetados desde o início para parecerem bonitos no escuro."
61060-121 = "No mundo... não é apenas para sobreviver ou por lucro..."
61060-122 = "Existem pessoas que criam coisas ou dedicam seu tempo... #napenas porque é \"bonito\"..."
61060-124 = "Os mercados com barracas de comida tinham pratos que eu nunca tinha visto."
61060-125 = "Só de olhar e sentir o aroma... #nme senti feliz, de alguma forma."
61060-126 = "...Embora eu não pudesse fazer nada além disso."
61060-128 = "Havia lugares onde água potável, limpa o suficiente para beber, era usada apenas para diversão."
61060-130 = "E os ambientes internos e externos pareciam mundos diferentes, como se fosse outro planeta..."
61060-131 = "E então, além disso――"
61060-145 = "..."
61060-146 = "..."
61060-147 = "Mas, em nenhum lugar... eu senti que havia um lugar onde eu pudesse ficar."
61060-148 = "Sim... eu entendo bem esse sentimento."
61060-149 = "Tudo era tão brilhante... e todos pareciam tão felizes."
61060-150 = "Mas, parecia que \"nós éramos diferentes\"..."
61060-151 = "Por isso..."
61060-156 = "Mesmo que eu caísse em um canto daquela cidade e perdesse a consciência..."
61060-157 = "Eu pensei que... provavelmente ninguém notaria."
61060-161 = "Em algum lugar deste mundo, alguém está sentindo felicidade."
61060-162 = "Em algum lugar deste mundo, outra pessoa――está vivendo uma vida plena."
61060-163 = "Mas, por outro lado――"
61060-167 = "Em algum lugar deste mundo, existe alguém que não está assim."
61060-168 = "A frase \"você pode fazer qualquer coisa\"――"
61060-169 = "Talvez significasse que eu não sabia o que fazer."
61060-170 = "Porque ninguém nunca me ensinou... como viver."
61060-171 = "Não existe resposta certa na vida. Por isso, viva como bem entender."
61060-172 = "Soa bem, mas que encorajamento irresponsável e conveniente, não é?"
61060-178 = "...Você se esforçou muito. #nObrigada por ter voltado."
61060-179 = "Senpai……."
61060-180 = "Eu entendo…… eu entendo muito bem esse sentimento."
61060-181 = "Pois aqui…… há muitas garotas que saíram uma vez e acabaram voltando."
61060-182 = "……Embora, entre elas, houvesse algumas que foram para Trinity e perderam o contato."
61060-183 = "……."
61060-184 = "Trinity……."
61060-185 = "O que houve? Maia, você também gostaria de ir lá?"
61060-192 = "N-não, não, não!? De jeito nenhum, eu não quero!"
61060-193 = "Está tudo bem. Eu não vou te impedir. #nMas eu…… provavelmente não consigo."
61060-194 = "Ainda não consigo perdoar…… Trinity."
61060-195 = "C-claro, você tem razão! Não tem como perdoar tão facilmente, tem?!"
61060-196 = "Eu também…… sinto o mesmo que você, Senpai……!"
61060-197 = "Obrigada. #n……Isso é muito reconfortante."
61060-204 = "É isso mesmo. Não há como perdoar."
61060-205 = "O esquadrão que, mesmo estando em uma posição de guiar a todos, simplesmente escolheu "desaparecer"——"
61060-209 = "Especialmente Saori Joumae—— ela."
61060-211 = "Próximo episódio; Gaita"
