[translation]
61070-1 = "第7話;ハーモニカ"
61070-2 = "ねぇ、先生。"
61070-3 = "先生の計画は、アリウスの生徒に試験を受けてもらうことだよね？"
61070-4 = "この「トリニティ総合試験」を。"
61070-10 = "[ns]\"うん。できれば「アリウス総合試験」って名前でね。\""
61070-11 = "名前は大事だよね。"
61070-12 = "ナギサさんも、そう言ってた。"
61070-14 = "アリウスの皆さんが、「トリニティ総合試験」という名前を受け入れられるかを考えると……。"
61070-15 = "やはり、難しいでしょうね。"
61070-16 = "ですが、もし何かの偶然で……。"
61070-17 = "「トリニティ総合試験」の予備印刷分が、「アリウス分校」に流れ着くことがあったとしたら？"
61070-18 = "それも、「アリウススクワッド」という運び手を通じて。"
61070-19 = "もちろんこの件に関して、トリニティは一切の見解を示しません。"
61070-20 = "印刷ミスや配送ミスというのは、往々にして起こりうることです。#nうーん……学園の運営費を少しでも節約するためとはいえ、仁志川センター経由にしたのは失敗でしたね。"
61070-21 = "まったく……学園の運営とは大変なものです。"
61070-23 = "配送ミス、か……。#n今回の仕事は配達員兼ボディーガードということだな。"
61070-24 = "……で、報酬は？聞き忘れてたけど。"
61070-25 = "[s]\"心配しないで。それなりの額を用意するよ。\""
61070-26 = "……。"
61070-27 = "先生がそれでいいなら。"
61070-28 = "[s]\"でも、実はそれ以外の作戦も考えてるんだよね。\""
61070-29 = "べ、別の作戦……ですか！？"
61070-30 = "どうせ、またろくでもないことなんでしょ。#n気にするだけ無駄だよ。"
61070-32 = "私はちょっと楽しみだけどな。#n期待してもいいんだよね、先生？"
61070-34 = "……とはいえ、問題は他にも山積みです。"
61070-35 = "一つ。試験を受けるにあたって、十分な勉強が前提となります。"
61070-36 = "アリウスの皆さんは、果たして一般的な教育を受けていたのか……。"
61070-37 = "やはりそこは……無理があるでしょうね。#nだからこそ、先生に授業をお願いしたのですから……。"
61070-38 = "改めて、先生には感謝しています。#nそして……申し訳ありません。アリウススクワッドの皆さん。"
61070-42 = "……このお願いは、そもそも成り立っていないのかもしれません。"
61070-43 = "これはアリウス分校の運営に、トリニティが口を出すということ。"
61070-44 = "別の学園の方針に干渉するなど、本来あってはならないことですから。"
61070-45 = "「別の学園」ね……。"
61070-46 = "アツコさんはどうお考えですか？"
61070-47 = "……ありがとう、ナギサさん。"
61070-51 = "今はその判断に、素直に感謝しているよ。"
61070-52 = "だってトリニティは、いつでもアリウス分校の所有権を主張できたはずなんだから。"
61070-53 = "あの事件の時……一時的とはいえ、アリウスはトリニティの支配下にあった。"
61070-55 = "[ruby=・   ・   ・   ・   ・]主張できた[/ruby]だけですよ。#n実際に行うのも、それが実現するのも、全く別の話です。"
61070-56 = "だからこそ、先生……いえ、シャーレに[ruby=きりふじ]桐藤[/ruby]ナギサという「個人」が「お願い」せざるを得なかったんです。"
61070-58 = "すごく面倒くさいやり方するよね。単純な話なのに。"
61070-59 = "これが……政治ってやつなんですか……。こ、怖いです……怖すぎます……。"
61070-61 = "これもまた、世の中の一面ということだろう。#n細かいことは置いておくとしても、桐藤ナギサの立ち回りには、正直感心させられた。"
61070-62 = "いい勉強になったな。"
61070-63 = "何それ。もしかして、ティーパーティーの肩を持つつもり？"
61070-64 = "そ、それは……。"
61070-66 = "でも、学べるところがあるなら、誰からだって学ぶべきだと思うよ。"
61070-67 = "……私たちは、知らないことばかりなんだから。"
61070-68 = "はぁ……。"
61070-70 = "先輩、先輩！ハーモニカ吹いてくださいよ！"
61070-71 = "あっ！私も聞きたいです！先輩の演奏、大好きなんです！"
61070-72 = "えっ！？そ、それは……。"
61070-73 = "えー、いいじゃないですか！#n聞かせてくださいよ～！"
61070-74 = "い、いえ。その……ですね……。"
61070-75 = "最近、ふと思ったんですが……。"
61070-76 = "廃墟で、ひとり感傷にひたりながらハーモニカを吹くなんて……。"
61070-77 = "それって、ちょっと……カッコつけすぎのような……。"
61070-78 = "わあっ！先輩が照れてる！"
61070-79 = "珍しいよね！照れた顔……ふふっ、今日はラッキーかも！"
61070-80 = "あの、私も……先輩の演奏……聴きたいです。#n久しぶり、ですし……。"
61070-81 = "ぐっ……！それはちょっと卑怯じゃないですか……！？"
61070-83 = "ダメ……ですか？"
61070-84 = "そっ……れは、ほんとにずるいですよ！"
61070-85 = "……絶対にダメというわけじゃ……ないですけど。"
61070-86 = "やったー！！！"
61070-91 = "まったく……こういうときだけ、みんな意地悪なんですから……。"
61070-92 = "しょうがないですね……それでは……。"
61070-101 = "変な音が入っても、あんまり笑わないでくださいね……？"
61070-102 = "え〜、またそうやって〜"
61070-103 = "先輩が変な音を鳴らしたことなんて、一度もないじゃないですか～！"
61070-105 = "前はマダムが禁止してたから、あんまり聴けなかったけど……。"
61070-106 = "でも、マダムがいない時に、こっそり演奏してくれましたよね？"
61070-107 = "下手とか変だなって思ったことなんて、一度もないです。"
61070-108 = "私、あまり詳しくはないですが……才能があると思いますよ？"
61070-112 = "そんなに褒めても、何も出ませんからね！？"
61070-113 = "……。"
61070-114 = "はぁ……。"
61070-115 = "では、演奏します……ね。"
61070-127 = "わあああ……。"
61070-128 = "ふふ……やっぱりこの音が好きだなぁ。"
61070-130 = "（……なんだろう）"
61070-131 = "（やっと、帰ってきた実感が湧いた気がする……）"
61070-148 = "……帰って来たね。"
61070-149 = "……ああ。"
61070-150 = "すぅ……ふぅ……。"
61070-151 = "……どうしたんだ？"
61070-152 = "いや……なんとなく、ね。"
61070-153 = "……。"
61070-154 = "……そうか。そうだな。"
61070-156 = "……うん。"
61070-157 = "うぅ……私たちがアリウスに戻って……#n本当に大丈夫なんでしょうか……？"
61070-158 = "この話、前にもした……気はするんですけど……。"
61070-159 = "やっぱり戻ってきてみると、なんだか……#nモヤモヤするというか……。"
61070-160 = "[ns]\"私も、同じような気持ちだよ。\""
61070-161 = "あ……先生も、ここは初めてじゃないですもんね……。"
61070-162 = "でも、まぁ、私たちがアリウスに戻るとなれば……。"
61070-163 = "十中八九……歓迎されないよね。"
61070-165 = "そうだな。残っている連中にとって、私たちは裏切り者も同然だろう。"
61070-166 = "きっと、そうだと思う。"
61070-167 = "……もしかしたら、盛大なお出迎えをしてくれるかもね。"
61070-168 = "たしか今のまとめ役は、スバルだったな。"
61070-169 = "うん……。"
61070-171 = "以前から、何度か内密に使者を送り……#n話し合いの機会を持とうと試みてきました。"
61070-172 = "結果は？"
61070-173 = "……救護騎士団が、救護活動に専念する他なかった。#nとだけ申し上げます。"
61070-174 = "唯一掴めたのは、あちらに残っている方々をまとめている生徒の名前だけ。#nその生徒は――"
61070-175 = "―[ruby=かけはし]―梯ス[/ruby]バル。"
61070-176 = "……！"
61070-178 = "[ns]\"スバルって、どんな子だったの？\""
61070-179 = "それはたぶん、サッちゃんが一番詳しいんじゃないかな。"
61070-180 = "……。"
61070-181 = "人柄を一言で語るのは簡単なことではないが、私の記憶では……。"
61070-182 = "話が通じるようで、どこかズレるタイプだったな。"
61070-184 = "そうだっけ？"
61070-188 = "でも、よく考えたら……間違ってはないか。"
61070-189 = "[ns]\"話ができないわけじゃないってことだね？\""
61070-190 = "そういう見方もできるが……。"
61070-191 = "いや、先生のことだ。#nどんな相手でも、まずは会話を試みるのだろうな。"
61070-192 = "――止まってくれ。#n……これより作戦体制に移行する。準備は良いな？"
61070-196 = "アリウススクワッド、任務開始だ。"
61070-200 = "この感じ……懐かしいね。"
61070-205 = "その……先生。"
61070-206 = "ゆっくり話ができるのは、これが最後になるかもしれない。#nだから、聞いておきたいことがあるんだ。"
61070-207 = "どうして……いつも、そんな風に自分を後回しにして……損な役回りばかり引き受けようとするんだ？"
61070-208 = "あっ、いや。別に、それを責めるつもりじゃない。ただ……。"
61070-212 = "……。"
61070-213 = "私は、先生が傷ついたり、苦しんだりするのを……もう見たくない。"
61070-214 = "それが心の傷でも、身体の傷でも……同じことだ。"
61070-215 = "[s]\"その気持ちだけで、なんだか元気が出てくるよ。そのためかな。\""
61070-216 = "そ、そうか？#nそれなら、今後も私が先生の心配をし続ければ――"
61070-217 = "……いや、ないな。#nそんなに都合よくいくわけがないことはよく知っている。"
61070-218 = "ん？どうして急にこんなことを……か。"
61070-219 = "……。"
61070-220 = "この場所に来ると、いろいろと思い出してしまうんだ。"
61070-221 = "いろいろなことがあったからな……。"
61070-222 = "……。"
61070-223 = "その、先生？"
61070-224 = "……。"
61070-225 = "私はやはり、先生にちゃんと謝ってな――"
61070-229 = "[ns]\"あっ、そうだ！トリニティに編入した子の話だけどさ！\""
61070-230 = "えっ、あっ、あぁ。 "
61070-231 = "[s]\"あの子たち、みんなに感謝してたよ。\""
61070-232 = "え……？"
61070-233 = "……どうして？"
61070-235 = "[ruby=スクワッド]私たち[/ruby]があの作戦を実行したから、なんて。そんなの、結果論でしょ。"
61070-236 = "それでも、あの子たちがアリウスの外で学園生活を送れるきっかけにはなったのか……。"
61070-238 = "でも……それって……#n私たちがやったことですけど、でも……。"
61070-239 = "すっごく、悪いこと……だったんじゃないでしょうか……？"
61070-240 = "うん。テロだよ。絶対にやっちゃいけないことだった。"
61070-241 = "うわぁぁぁぁぁぁああん！やっぱりそうなんですねぇ～！"
61070-243 = "[ns3]\"でもね。\"\n[ns4]\"編入した子たちから、感謝の言葉を預かった。\"\n[ns5]\"これだって、れっきとした事実だよ。\""
61070-247 = "……。"
61070-248 = "先生……？事実って、なに？"
61070-249 = "……歴史ってなんなのかな。"
61070-250 = "[s6]\"直接的な答えじゃなくて申し訳ないけど。\"\n[s7]\"それを知るために、私たちは勉強するんじゃないかな。\""
61070-253 = "ふふっ、一本取られちゃった。"
61070-254 = "今のは先生らしくて、ちょっとカッコよかったよ。"
61070-255 = "えっ？先生らしさついでに、もうひとつ聞きたいことがあるって？"
61070-256 = "[s]\"みんなは普段、ちゃんと勉強してる？\""
61070-257 = "それなら心配いらないよ。勉強するの、私は結構好きなんだ。"
61070-258 = "えへへ……。先生がこっそり、教育用のBDとかを送ってくれてましたし……。"
61070-259 = "……まあ、やって損するものでもないし。#n時間ができたときに少しずつね。"
61070-260 = "ああ。私も同じだ。世の中の仕組みを知っておいて損はない。"
61070-261 = "……今思えば、これも先生の言った通りだったな。"
61070-263 = "[ns8]\"よかった。これでまた一歩、完成に近づいたよ。\"\n[ns9]\"私の壮大な計画がね……！\""
61070-266 = "先生がそういうテンションのときって、一番不安になるんだけど……。"
61070-267 = "ま、待ってください……！"
61070-268 = "どうした？"
61070-269 = "……ああ、なるほど。そういうことか。"
61070-270 = "はい……。"
61070-272 = "ついに……。"
61070-273 = "帰ってきたんですね……。"
61070-275 = "はぁ……最高でした、先輩。"
61070-276 = "アンコール！アンコール！"
61070-277 = "……お断りします。"
61070-278 = "照れないでくださいよ！カッコよかったのに！"
61070-279 = "いや、それがですね……。"
61070-280 = "実はもう、これ以上吹ける曲がないんです……。"
61070-281 = "あっ……楽譜って、あんまり手に入らないですもんね……。"
61070-282 = "じゃあ、しょうがないですね……。"
61070-287 = "せ、先輩！た、大変です！"
61070-288 = "落ち着いてください。#n順を追ってゆっくりお願いします。"
61070-289 = "は、はいっ！"
61070-290 = "……スクワッドが、アリウスに入りました。#nシャーレの先生と一緒です。"
61070-294 = "スクワッドが……！？"
61070-295 = "あいつら、どの面下げて……！"
61070-296 = "私はまだ、スクワッドのこと……。"
61070-298 = "……。"
61070-299 = "無理だよ……顔も見たくない……。"
61070-300 = "そう、会いたくない。"
61070-301 = "トリニティが来たかと思えば、次はスクワッド……？#n一体何しにきたんだ……！"
61070-303 = "ちょっと待ってください。"
61070-304 = "……シャーレの先生も一緒だと言いましたよね？"
61070-305 = "そ、そうです！"
61070-306 = "……。"
61070-307 = "なるほど……そういうことですか。"
61070-308 = "スクワッドは巻き込まれた可能性も……？"
61070-309 = "ど、どういうことですか、先輩？"
61070-310 = "皆さん。"
61070-311 = "スクワッドだけであれば、大した問題にはならなかったでしょう。"
61070-312 = "ですが、問題は「シャーレの先生」と呼ばれる、あの大人です。"
61070-313 = "その大人がアリウスに現れた以上、今までのやり方では通じません。"
61070-318 = "な、なんでですか……？"
61070-319 = "なんでって……考えてみなよ。#nあの大人のせいで、結局……。"
61070-320 = "マダムが……いなくなったんでしょ……？"
61070-321 = "そ、それは、でも……あっ！"
61070-322 = "そう。"
61070-323 = "あの大人は何をするかわかんない。どんな力を持ってるかも。"
61070-324 = "どんな結果をもたらすかも……予測がつかない。#n大人って、そういうものでしょ？"
61070-325 = "……たしかに。"
61070-326 = "いつだって、私たちじゃ想像もできないことをやるんだから。"
61070-328 = "せ、先輩……これからどうすれば……？"
61070-329 = "ひとまず、落ち着きましょう。それから……。"
61070-330 = "……。"
61070-331 = "「お出迎え」に、出てみましょうか。"
61070-332 = "そっ、それって……大丈夫なんですか……！？"
61070-333 = "正直なところ、大丈夫かどうかは私にもまだ判断がついていません。"
61070-334 = "ですが……やってみなければ分からないでしょう？そうではありませんか？"
61070-335 = "差し当たって、各自の銃のセーフティは、外さないでおいてください。"
61070-336 = "……今は、まだ。"
61070-337 = "分かりました、先輩！"
61070-340 = "次回;アリウス流"
