[translation]
61090-1 = "Episódio 9; Hora da aula"
61090-2 = "Ufa..."
61090-3 = "Ugh, uugh...!"
61090-8 = "Foi uma diferença mínima, mas..."
61090-9 = "Com isso, a disputa está decidida."
61090-10 = "Esquadrão... vocês ficaram um pouco enferrujadas?"
61090-11 = "Talvez sim."
61090-12 = "Mas não tanto quanto vocês.#nNo geral, seus movimentos estão sem vigor."
61090-13 = "...!"
61090-14 = "E então, o que vão fazer?"
61090-15 = "Acho que conseguimos provar o nosso 'valor'."
61090-19 = "Bem, eu acho que não tem jeito..."
61090-20 = "Elas estão se achando...!"
61090-21 = "De qualquer forma, vocês devem ter tido várias experiências lá 'fora'.#nO resultado já era óbvio desde o começo."
61090-22 = "Abandonaram Arius, e agora vêm dar pitaco...!"
61090-23 = "Haa..."
61090-24 = "Acalme-se, Misaki."
61090-25 = "Isso é algo que precisamos aceitar."
61090-26 = "O mesmo vale para aquele adulto, o Sensei.#nÉ egoísta, insistente..."
61090-27 = "Fica dizendo que é 'pelo bem de Arius', mas com certeza tem outras intenções por trás..."
61090-35 = "Uwa!?"
61090-36 = "E-Espera aí!? Você tá bem!?"
61090-37 = "Desmaiou..."
61090-38 = "Double tap no peito e depois um headshot, sem nem fazer movimento preparatório..."
61090-39 = "A Subaru-senpai disse que ela enferrujou, mas... não parece nem um pouco..."
61090-41 = "Atsuko!?"
61090-42 = "Hiiiii!?"
61090-43 = "Não me importo com o que digam sobre nós.#nMas podem parar de falar mal do Sensei também?"
61090-44 = "Espero que vocês tenham pelo menos esse nível de bom senso."
61090-45 = "Eu também ainda sou membro de Arius, sabiam?"
61090-46 = "S-Sim!"
61090-47 = "..."
61090-49 = "(Todas estão encolhidas com expressões meio assustadas)"
61090-50 = "(Para conversarmos num clima um pouco mais animado...)"
61090-51 = "[ns]\"Certo, pessoal! Vamos estudar!\""
61090-52 = "Estudar...? O que exatamente quer que a gente faça!?#nNós não temos nada aqui!"
61090-53 = "Não temos conhecimento, as salas de aula estão em pedaços.#nFaltam materiais, e até alguém para nos ensinar..."
61090-54 = "...Dizer isso em voz alta dá uma tristeza."
61090-55 = "[s1]\"Não se preocupe.\"\n[s2]\"Contanto que tenhamos cadeiras, mesas e um quadro-negro, daremos um jeito.\""
61090-60 = "[ns]\"E além disso, nós temos sim quem ensine.\""
61090-64 = "...Você vai mesmo fazer isso aqui?"
61090-65 = "[s3]\"Tem mesas e é só erguer as cadeiras caídas.\"\n[s4]\"Temos até a mesa dos Senseies e o quadro-negro! Não é a sala de aula perfeita?\""
61090-68 = "A definição da palavra 'perfeita' deve ter mudado drasticamente sem eu saber..."
61090-69 = "E mesmo que eu quisesse procurar o significado, quase não sobrou nenhum dicionário em Arius..."
61090-70 = "De qualquer forma, já está tarde.#nLogo vai anoitecer..."
61090-71 = "[s5]\"A primeira aula vai ser curtinha, então tudo bem.\"\n[s6]\"Só vamos fazer a chamada, dar uma orientação básica e terminar.\""
61090-74 = "Tem certeza de que vai ficar tudo bem...?"
61090-75 = "[s]\"Tudo bem. Eu confio na Saori!\""
61090-76 = "!?"
61090-77 = "!?"
61090-78 = "Por que o meu nome foi parar nessa conversa...?"
61090-79 = "[s7]\"Isso é porque... os Senseies em treinamento escolhidos a dedo!\"\n[s8]\"Serão os responsáveis por dar a primeira aula!\""
61090-82 = "Quando foi que essa seleção aconteceu?"
61090-83 = "Agora...? ...Ah, saquei."
61090-84 = "Por acaso, o 'plano grandioso' que o Sensei falou era isso!?"
61090-85 = "Aquelas perguntas de 'estão estudando direitinho?' eram só pra verificar isso..."
61090-86 = "Você podia ter combinado isso com a gente antes... Haa..."
61090-87 = "Então, eu... eu vou...?"
61090-88 = "[s]\"Por favor, nos ensine, Saori-sensei!\""
61090-89 = "Sim, por favor nos ensine. Saori-sensei."
61090-90 = "Até a Atsuko...!?"
61090-92 = "(Saori subiu no palanque, mesmo com uma expressão desajeitada)"
61090-94 = "(O que e como eu devo ensinar...?)"
61090-95 = "(Hm? Isso é... um livro de Ciências Sociais. ...Cultura Social, Teoria do Contrato Social?)"
61090-99 = "(Eu consigo... Se for isso!)"
61090-100 = "Iniciando a aula! Sentem-se!"
61090-101 = "Eh, precisamos mesmo sentar?"
61090-102 = "Ah, eu... já tô sentada..."
61090-103 = "Abram seus cadernos. Se não tiverem, pode ser a caderneta escolar!#nPelo menos isso cada uma de vocês deve ter."
61090-104 = "Se nem isso tiverem, copiem de quem está do lado depois."
61090-105 = "A quantidade de conhecimento que fica retida é totalmente diferente entre apenas ouvir e anotar à mão."
61090-106 = "S-Sim!"
61090-107 = "É exatamente a Saori-senpai da época em que ela era instrutora..."
61090-108 = "Antes de começar a aula, tenho uma coisa a dizer."
61090-112 = "Contratos! São extremamente importantes!!"
61090-113 = "Contratos...?"
61090-114 = "O que é isso... Uma cultura de fora...?"
61090-115 = "Um contrato é um documento trocado com a outra parte para que as promessas não sejam esquecidas."
61090-116 = "Sem isso! Não importa o quanto você trabalhe! Você não receberá a sua recompensa!"
61090-117 = "É muito comum você se esforçar à toa e voltar de mãos abanando!!"
61090-118 = "É um grito que vem do fundo da alma..."
61090-119 = "Será que... é experiência própria...?"
61090-120 = "Força, Satchan...!"
61090-121 = "Irmã Saori...!"
61090-123 = "...A sociedade é algo intangível.#nA ideia central da 'Teoria do Contrato Social' é que a sociedade é um mecanismo artificial, mantido pelos contratos entre seus membros."
61090-124 = "Em outras palavras, a sociedade não existe desde o princípio, e todas as pessoas possuem direitos inerentes desde o nascimento."
61090-125 = "C-Com licença... Posso fazer uma pergunta?"
61090-126 = "Pode falar."
61090-127 = "Você disse que não existe desde o princípio, mas então... os direitos de nascença também não existem...?"
61090-128 = "Boa pergunta. Pode realmente parecer contraditório à primeira vista."
61090-129 = "Mas pensem que existe a seguinte premissa."
61090-130 = "'Assumir' que os seres humanos nascem com direitos inerentes――"
61090-131 = "Aumenta as chances de criar uma sociedade melhor."
61090-132 = "Mesmo que na realidade seja diferente, 'acreditar nisso' acaba gerando um resultado melhor...?"
61090-133 = "Eu nunca tinha pensado por esse lado...!"
61090-137 = "O tempo acabou. A aula de hoje fica por aqui."
61090-138 = "Se tiverem dúvidas, perguntem na próxima aula."
61090-139 = "Se preparar antes da aula... pode ser difícil ainda, mas certifiquem-se de revisar a matéria."
61090-140 = "Pois a revisão traz mais resultados no aprendizado do que a preparação prévia."
61090-144 = "Então... Como eu me saí...?"
61090-145 = "[s9]\"Foi incrível, Saori-sensei...\"\n[s10]\"Estou emocionado, Saori-sensei...\""
61090-148 = "Eu ainda não mereço ser chamada de 'Sensei'..."
61090-149 = "De qualquer forma, se eu fui bem, que bom."
61090-151 = "[ns]\"Muito bem, a próxima é a Senseia de física, Misaki-sensei!\""
61090-152 = "...Eu? E ainda física... cê tá brincando?"
61090-153 = "Hã? Balística é parecida com a mecânica clássica...?"
61090-154 = "..."
61090-155 = "Até que não é totalmente sem relação..."
61090-156 = "Haa... É só eu fazer, né."
61090-159 = "Primeiro, memorizem as fórmulas. Vocês não devem estar com a mente ligada nisso mesmo, né?"
61090-160 = "Não vou exigir que entendam o conteúdo! Vocês não estão nesse nível."
61090-161 = "Tanto em matemática quanto em física, tudo começa memorizando as coisas!"
61090-162 = "Bem... se conseguirem entender desde o início, eu recomendo seguirem esse caminho."
61090-163 = "Mas esse tipo de pessoa costuma tentar avaliar as outras através de números e estatísticas――"
61090-164 = "Acabam não entendendo os sentimentos dos outros e causando problemas desnecessários..."
61090-166 = "Olá. Eu sou [ruby=Hakari]Hakari[/ruby] Atsuko e serei a responsável pela aula de biologia."
61090-167 = "Vamos começar a aula.#nBiologia é divertida e é uma área muito importante."
61090-168 = "Por exemplo, o que é uma 'célula'?"
61090-169 = "Por qual processo uma contusão passa até sarar――Vamos ver um exemplo prático."
61090-170 = "[s]\"Atsuko! Para! Para!\""
61090-171 = "Por que me parou? Isso é algo superimportante, sabe?"
61090-172 = "Hehe, tudo bem. Eu sei como pegar leve."
61090-173 = "Então, que tal começarmos por 'Glóbulos brancos e glóbulos vermelhos'?"
61090-175 = "Com isso, acho que consegui dar uma explicação geral sobre os componentes das células e suas funções."
61090-176 = "As células podem ser consideradas a unidade mais fundamental dos seres vivos, então certifiquem-se de lembrar bem disso."
61090-178 = "..."
61090-179 = "H-Hã... Pessoal. Ehehe... Quanto tempo, né..."
61090-180 = "Então, hã..."
61090-184 = "S-Sensei!? O q-que eu devo fazer...?"
61090-185 = "Eu só costumo ler revistas no meu tempo livre... Não tenho nenhum conhecimento especializado..."
61090-186 = "[ns]\"...!\""
61090-188 = "[ns](Ouvir a palavra revistas me deu uma ideia)"
61090-189 = "Hã? Falar sobre como é viver no mundo lá fora...?"
61090-190 = "As roupas que vi nas revistas... as comidas...?"
61090-191 = "..."
61090-192 = "Sim! Se for isso... acho que consigo falar...!"
61090-194 = "A-Ahm, novamente... olá..."
61090-195 = "Isso pode ser meio repentino e surpreendente, mas... hã..."
61090-196 = "O que vocês acham de 'moda'?"
61090-200 = "Ehehe... S-Sim, é claro. É um assunto meio inusitado, né..."
61090-201 = "Mas a moda... não é apenas sobre usar roupas...#nAcho que é sobre... você mesmo decidir como quer ser visto pelos outros..."
61090-202 = "Isso pode ser... surpreendentemente importante..."
61090-203 = "E, e também... o jeito como as pessoas de 'fora' vivem...#nSobre o 'estilo de vida' delas...!"
61090-205 = "(A aula de Hiyori foi a mais popular entre as quatro)"
61090-209 = "(Talvez por causa do empenho de todas do Esquadrão atuando como Senseias)"
61090-210 = "(Eu pude sentir a cautela das alunas de Arius em relação às 'aulas' diminuindo)"
61090-211 = "(Eu estava esperando exatamente por esse momento!)"
61090-213 = "[ns11]\"――Portanto, podemos chegar a esta conclusão.\"\n[ns12]\"Sendo algo autoevidente, isso significa que――\""
61090-219 = "(Um bom número de estudantes conseguiu acompanhar a aula direitinho)"
61090-225 = "(...Claro que também teve alunas que foram o exato oposto)"
61090-226 = "(Mas eu acho que ambos os casos fazem parte da 'vida escolar')"
61090-228 = "[ns]\"A aula de hoje termina aqui! Bom trabalho, pessoal!\""
61090-229 = "Bom trabalho..."
61090-230 = "Ugh... Que dor de cabeça..."
61090-231 = "Mas, surpreendentemente, até que pode ter valido a pena, não é?"
61090-232 = "Me deixa dar uma olhada no seu caderno."
61090-233 = "O que você tava fazendo agora há pouco?"
61090-234 = "Ah, eu acabei dando uma viajada..."
61090-238 = "..."
61090-240 = "Por enquanto... fique à vontade para usar este lugar, Sensei."
61090-241 = "...Desculpe. Isso é tudo que podemos lhe oferecer."
61090-242 = "[s13]\"Não tem problema, eu trouxe um saco de dormir.\"\n[s14]\"Viu só. Hmm, nada mau.\""
61090-248 = "[ns]\"...Saori?\""
61090-249 = "...Sensei."
61090-250 = "Só um pouquinho."
61090-251 = "Há algo que eu gostaria de discutir com você, incluindo o que aconteceu hoje... Se importa?"
61090-253 = "Próximo episódio; Feridas e Vestígios"