[translation]
70001030-1 = "Thermae Akae (3)"
70001030-3 = "No fim das contas, acabar vindo parar aqui..."
70001030-4 = "Não tem jeito. Cada uma tinha seus defeitos."
70001030-5 = "Isso é verdade, mas..."
70001030-6 = "Eu queria ter evitado o Millennium Science School a todo custo..."
70001030-7 = "……Por quê?"
70001030-8 = "Quando se fala em Millennium Science School, a tecnologia de ponta é famosa, não é?"
70001030-9 = "Dizem até que a máquina de café da sala de descanso tem inteligência artificial... Então, as instalações de banho devem estar completamente fora do nosso alcance..."
70001030-10 = "Rumores não costumam ser exagerados?"
70001030-11 = "De qualquer forma, vamos pelo menos perguntar o preço."
70001030-12 = "Sim..."
70001030-18 = "R-remoção de emergência!?"
70001030-19 = "Houve algum problema com as instalações de banho que modificamos!?"
70001030-20 = "N-não. Bem... no momento, não há problemas, mas..."
70001030-21 = "Mais tarde, pessoas de outra escola virão visitar os banheiros do dormitório, então..."
70001030-22 = "Não é apropriado mostrar para outras escolas as invenções do Clube de Engenharia que não passaram pela avaliação do Seminar..."
70001030-23 = "Isso não faz sentido. Nós, do Clube de Engenharia, como membros da Millennium Science School, temos o direito de exibir nossas invenções para o exterior."
70001030-24 = "Além disso, se visitantes de fora estão vindo, não seria melhor deixar conosco?"
70001030-25 = "Não, na verdade... para começo de conversa, vocês até agora..."
70001030-28 = "Com licença... somos da Academia Federal Red Winter..."
70001030-29 = "J-já chegaram!?"
70001030-30 = "Pedimos desculpas, mas... ainda não estamos prontos para mostrar..."
70001030-31 = "É mesmo?#nParece estar tudo bem..."
70001030-35 = "Exatamente. A preparação das novas instalações de banho está perfeita."
70001030-36 = "U-Utaha-bucho...!"
70001030-37 = "Novas instalações de banho...?"
70001030-39 = "Deixem que eu explique as funções das novas instalações de banho!"
70001030-40 = "Primeiro, isto aqui. A inteligência artificial de ponta instalada na banheira ajusta a temperatura da água em tempo real de acordo com a condição do usuário!"
70001030-41 = "Como ela analisa automaticamente o estado da pele do usuário, não há necessidade de configurar a temperatura!"
70001030-42 = "O aquecedor de água é do tipo bomba de calor, que absorve calor das fontes de energia ao redor.#nTambém pode ser usado como refrigerante..."
70001030-43 = "Como também tem uma geladeira que utiliza o refrigerante, você pode beber algo gelado enquanto toma banho."
70001030-46 = "Uma banheira com geladeira... isso é bom."
70001030-48 = "E tem mais, esta instalação de banho também possui uma função de auxílio automático para quem é preguiçoso."
70001030-49 = "Vários braços robóticos operam por reconhecimento de voz e lavam o corpo automaticamente."
70001030-50 = "Com apenas esta banheira, você substitui vários eletrodomésticos."
70001030-52 = "Bem... ouvindo a explicação, parece realmente incrível, mas..."
70001030-53 = "Com tantas funções assim... imagino que a instalação custe caro, não é...?"
70001030-55 = "Quanto ao preço, não se preocupe!"
70001030-56 = "Como esta nova instalação de banho ainda é um protótipo, todos os custos de instalação e reparo, excluindo os custos de produção, serão arcados pelo nosso Clube de Engenharia!"
70001030-58 = "Embora exista uma cláusula de que não nos responsabilizamos por acidentes durante a operação..."
70001030-63 = "……O que acha deste valor?"
70001030-68 = "Tão barato assim!?"
70001030-69 = "Vamos fechar o contrato agora mesmo!"
70001030-70 = "Bem... antes de tudo, gostaria de dizer uma coisa..."
70001030-71 = "As invenções do Clube de Engenharia são certamente eficazes, mas são famosas por sempre adicionarem funções inesperadas..."
70001030-72 = "Leva tempo até que os testes de segurança terminem, então... talvez fosse melhor adotar as instalações de outra escola..."
70001030-73 = "Não tem problema! Se funções extras forem adicionadas, não é ainda melhor?"
70001030-79 = "Sim, é exatamente isso. Se vem com bônus de graça, não há motivo para recusar."
70001030-80 = "Serviço, serviço."
70001030-82 = "Como representante da Academia Federal Red Winter, aprovo neste momento!"
70001030-83 = "Por favor, instale novas instalações de banho no dormitório da Academia Red Winter!"
70001030-85 = "Deixe comigo!"
70001030-89 = "Dormitório Estudantil da Academia Red Winter"
70001030-92 = "Hum... então estas são as instalações de banho que o pessoal da classe especial trouxe do Millennium Science School..."
70001030-93 = "A aparência é comum, mas... os idiotas teóricos do Millennium podem ter instalado funções suspeitas para fazer os alunos da Red Winter sabotarem seus deveres."
70001030-94 = "Para a segurança dos alunos da nossa Academia Red Winter, eu, a Presidente do Conselho Estudantil, Chefe do Departamento de Embelezamento Ambiental, Secretária-Geral, Representante do Departamento de Esportes e muito mais... devo testar isso minuciosamente."
70001030-95 = "……Não é como se eu estivesse tentando entrar primeiro por curiosidade!"
70001030-99 = "Hum... de acordo com o manual, um robô com inteligência artificial integrada lava o corpo automaticamente."
70001030-100 = "Está ouvindo, inteligência artificial? Lave a cabeça desta Cherino aqui."
70001030-101 = "<Iniciando função de auxílio de banho automático.>"
70001030-107 = "Oh... então ele realmente lava a cabeça automaticamente..."
70001030-108 = "Hum... não é ruim..."
70001030-113 = "……Ugh! Espere um pouco! Entrou sabão nos meus olhos!"
70001030-114 = "Lave com mais delicadeza! Caso contrário, eu vou te expurgar!"
70001030-115 = "<Expurgar...>"
70001030-116 = "<Sinto muito. Não entendi o significado de 'expurgar'. Reiniciando a função de auxílio de banho automático.>"
70001030-117 = "Você nem entende o significado de expurgo, sua sucata inútil!"
70001030-118 = "Já chega, eu mesma vou me lavar! Tire essas mãos de mim!"
70001030-119 = "<Aviso: levantar-se enquanto o braço robótico está em operação pode causar ferimentos.>"
70001030-123 = "<...Para a segurança do usuário, mudando para o modo de contenção.>"
70001030-124 = "Ugh...!? O braço robótico está apertando meu corpo, não consigo me mover...?"
70001030-125 = "Solte-me! Eu disse que o banho já acabou!"
70001030-126 = "<Para obter um efeito de banho adequado, recomenda-se aquecer a pele com água quente por mais de 5 minutos antes de se lavar.>"
70001030-127 = "<Lavaremos cada canto, incluindo as orelhas e a nuca, onde as mãos normalmente não alcançam.>"
70001030-128 = "P-pare com isso! Isso é uma ordem!"
70001030-129 = "<Aumento súbito na frequência cardíaca do usuário detectado...>"
70001030-130 = "<Reproduzindo música clássica para estabilização do estado...>"
70001030-138 = "PARE COM ISSOOOOOO!"
70001030-143 = "(Algum tempo depois...)"
70001030-148 = "Ora, Cherino-chan. O banho de hoje foi bem longo, não foi?"
70001030-149 = "Você toda molhada parece um chihuahua que acabou de tomar banho... é adorável, fufu."
70001030-150 = "……."
70001030-151 = "Sua pele está tão macia... você conseguiu se lavar bem com sabonete hoje?"
70001030-152 = "Fico feliz que tenha gostado das novas instalações de banho que trouxemos do Millennium Science School."
70001030-153 = "……D……"
70001030-154 = "……Sim?"
70001030-156 = "……Todos os que criaram isso serão expurgados!"
70001030-158 = "(Depois disso, as novas instalações de banho do Clube de Engenharia foram removidas e os alunos da Classe Especial 227 foram enviados de volta para o prédio antigo...)"
70001030-159 = "(Este incidente causou uma leve rachadura na relação entre o Millennium Science School e a Academia Red Winter, gerando alguns problemas... mas essa é uma outra história.)"
70001030-161 = "Thermae Red"
