[translation]
70000020-1 = "Encontro suspeito (2)"
70000020-2 = "（――E assim, começou o encontro entre o Secretariado de Red Winter e o Pandemonium）"
70000020-6 = "Kikiki! Viu só, Presidente?#nDesta vez, a taxa de votação de confiança realizada novamente contra o nosso Pandemonium bateu o recorde de baixa!"
70000020-15 = "（Makoto-senpai... você está desesperada para recuperar o prestígio que perdeu, não é?）"
70000020-16 = "Está com uma cara de quem não entendeu nada?#nVou te ensinar, como um favor especial."
70000020-17 = "De qualquer forma, a maioria das alunas não entende nada de política!#nEm outras palavras, é mais fácil governar se elas não tiverem interesse, em vez de ficarem pensando nisso ou naquilo!"
70000020-18 = "Essa taxa de votação de 3,8% é a prova de que nosso poder é inabalável!"
70000020-20 = "Que coisa realmente patética, Presidente do Conselho.#nCom uma estratégia tão míope, você vai acabar tropeçando nos próprios pés, sabia?"
70000020-21 = "Tomoe, diga a taxa de votação da última eleição geral de Red Winter."
70000020-22 = "300%, Presidente."
70000020-24 = "O-o quê!?"
70000020-25 = "Entendeu agora, Presidente do Conselho?#nQuanto maior o número, melhor!"
70000020-26 = "Se pretende rivalizar com a nossa Academia Federal de Red Winter, trate de conseguir esse nível de apoio!"
70000020-27 = "M-mas que absurdo!#nComo pude perder até na taxa de aprovação..."
70000020-28 = "………………"
70000020-33 = "Droga, estou sendo menosprezada...!?#nEu, Makoto, a Presidente do Pandemonium...!!"
70000020-34 = "……Parece que o plano falhou, e não há motivo para ficarmos aqui, certo?#nVamos, vamos voltar, senpai."
70000020-35 = "A-ainda não!#nVoltar depois de ser humilhada por Red Winter... tal humilhação jamais..."
70000020-36 = "……Hm?"
70000020-43 = "O-o que é isso..."
70000020-45 = "Hum. Percebeu, Presidente do Conselho?"
70000020-50 = "Se-Secretária-Geral...?"
70000020-57 = "Esse é o retrato que simboliza a minha autoridade."
70000020-58 = "Ficou hipnotizada por uma figura tão magnífica, não foi?#nAo olhar, dá até vontade de prestar respeito, não dá?"
70000020-59 = "Não, nem um pouco..."
70000020-63 = "（Mas será que dá para insistir que isso é ela mesma?）"
70000020-64 = "（Para começar, o gênero é diferente...）"
70000020-67 = "Parece que você não tem olho para a arte."
70000020-68 = "Pinturas não são o básico da propaganda?#nE pensar que essa é a Presidente do Pandemonium..."
70000020-69 = "Hahaha, o futuro de Gehenna é sombrio!"
70000020-70 = "O que disse?"
70000020-71 = "Senpai... se começar uma confusão aqui, tudo irá por água abaixo."
70000020-72 = "Por favor, acalme-se primeiro.#nSua mesquinhez vai acabar sendo revelada."
70000020-74 = "Hum. Não se preocupe com uma pequena brincadeira, Presidente do Conselho."
70000020-75 = "Além disso, mesmo que você seja mesquinha, uma Presidente grandiosa como eu não se importa!"
70000020-76 = "Já que estamos aqui, vamos criar uma lembrança para celebrar a amizade entre Gehenna e Red Winter."
70000020-77 = "Que tal... poderia me dizer suas crenças ou seu lema de vida?"
70000020-83 = "Crenças... lema de vida...?"
70000020-84 = "Makoto-senpai, você não disse isso antes?"
70000020-85 = "Quando comeu o pudim da geladeira sem permissão..."
70000020-88 = "Ah? Pudim?"
70000020-89 = "Kikikiki.#nAh, fui eu quem comeu, sim."
70000020-90 = "E o que tem isso?#nAchou que eu fosse pedir desculpas?"
70000020-91 = "Não é que eu quisesse que pedisse desculpas..."
70000020-92 = "Sendo a Makoto-senpai, não espero nada mesmo que ela tente se justificar."
70000020-93 = "Kikikiki. Ouça bem, Iroha. No dicionário da Makoto, não existe arrependimento nem remorso."
70000020-94 = "Sendo a Presidente do Pandemonium, é natural não ter essas coisas, não é?"
70000020-95 = "Eu, Hanuma Makoto――"
70000020-96 = "Não tenho um pingo de arrependimento na minha vida!"
70000020-97 = "Ah, sim..."
70000020-99 = "……Hum, como esperado da presidente do Pandemonium."
70000020-100 = "Comer o pudim dos outros sem permissão...#nQue audácia. Magnífico, presidente Makoto."
70000020-101 = "Muito bem, eu gostei!"
70000020-102 = "Tomoe, chame o melhor artesão de Red Winter!"
70000020-103 = "Sim, Secretária-Geral."
70000020-104 = "Vou conceder a ela um presente digno dessa figura corajosa!"
70000020-106 = "(Como as coisas chegaram a esse ponto...)"
70000020-108 = "(Alguns dias depois, em frente ao portão da Gehenna)"
70000020-114 = "……Ako, o que é isso?"
70000020-115 = "Parece ser uma estátua enviada de Red Winter para o Pandemonium……."
70000020-116 = "Isso é... a presidente Makoto, não é?"
70000020-121 = "………………."
70000020-128 = "(A estátua com o punho erguido para o céu desapareceu sem deixar vestígios assim que o som do disparo do Destroyer ecoou)"
70000020-129 = "Registro de Patrulha do Pandemonium em Red Winter"
70000020-141 = "Tcharam! É a Ibuki!"
70000020-142 = "Bom dia!#nFufun, pudim, pudiiim♪"
70000020-143 = "……Ah!"
70000020-144 = "I-Ibuki... é que..."
70000020-145 = "E-espere, Ibuki...!"
70000020-147 = "Ué...?#nO pudim da Ibuki... cadê...?"
70000020-148 = "Ibuki... não pode comer o pudim? É porque a Ibuki foi uma menina má?"
70000020-149 = "Não é nada disso.#nA culpa de tudo é..."
70000020-150 = "I-Ibuki! Eu estava erradaaaa!#nEu não sabia que era o pudim da Ibuki, eu... euuuuu!!!"
70000020-151 = "Me desculpa, Ibuki!!! Eu te imploro, me perdoeeeee!!!"
70000020-152 = "Haa..."
