[translation]
70014040-1 = "The Apothecary's Wanderings (4)"
70014040-2 = "Protection money...? You don't do anything around here anyway."
70014040-3 = "Patrolling is about making sure nothing happens. #nDon't come crying to me if you get robbed!"
70014040-4 = "Then do as you please. #nWhether it's taken by robbers or taken by you, there's no difference."
70014040-5 = "Geez, you're impossible to talk to. #nWhat is it? Are you acting tough because you've got that kid named Kai staying with you?"
70014040-6 = "That child has nothing to do with this!"
70014040-7 = "Since it's a good opportunity, I'll enlighten you. That Shintani Kai is—"
70014040-8 = "An uncontrollable troublemaker, a villain so notorious she's called one of the Seven Prisoners!"
70014040-9 = "Word is she turned the Shanhaijing academy upside down, didn't she?"
70014040-10 = "And she apparently hired a whole bunch of Black Market residents, too?"
70014040-11 = "She's way more dangerous than you think!"
70014040-12 = "……!"
70014040-13 = "Oh, right."
70014040-14 = "If she really wanted to, she could even cure your illness, old woman!"
70014040-15 = "……."
70014040-16 = "Hoh... you're quite well-informed."
70014040-17 = "It seems her skills are the real deal, at least."
70014040-18 = "Then why would she leave an old woman like you to fend for yourself?"
70014040-19 = "It's because... she wants to take over your house!"
70014040-20 = "You can't keep secrets here."
70014040-21 = "The Black Market is a place where everything eventually comes to light!"
70014040-22 = "Besides... I owe Kai a debt."
70014040-27 = "Sorry, but you'll have to be the one to pay up, old woman!"
70014040-31 = "……!!!"
70014040-33 = "[ns] \"I have to stop them!\""
70014040-34 = "……."
70014040-35 = "[s] \"Kai...?\""
70014040-40 = "……Hmph, you young fools."
70014040-41 = "I've known that for a long time."
70014040-45 = "W-what!?"
70014040-46 = "……?"
70014040-47 = "……I haven't lived here this long for nothing."
70014040-48 = "You wouldn't understand how many people I've seen who deceive and are deceived."
70014040-49 = "I knew from the very beginning, even without you telling me."
70014040-50 = "Th-then, why...?"
70014040-51 = "Why try to hand over the house?"
70014040-52 = "That's already enough for me."
70014040-53 = "Whatever kind of child Kai is, or whatever she does outside, it has nothing to do with me."
70014040-54 = "That child was truly here. She lived in my house, even if only for a short while. #nThat is enough. What more could I ask for?"
70014040-55 = "Two is better than one. And... one is better than none. #nI'm sure the house feels the same way."
70014040-56 = "So—don't get in the way of my cleaning!"
70014040-57 = "I must have her inherit this house!"
70014040-61 = "Th-that doesn't matter! We don't care about your personal circumstances!"
70014040-62 = "Enough with the preaching!"
70014040-63 = "You're the one who stirred up this trouble, old woman!"
70014040-65 = "You lot! Come out!"
70014040-75 = "……How irritating."
70014040-76 = "[s] \"Kai...?\""
70014040-77 = "I don't like this. Ah, I really don't like this."
70014040-78 = "……."
70014040-79 = "The old woman talking about inheriting houses."
70014040-80 = "The idiots making a scene. Everything."
70014040-81 = "Sensei, don't get in my way. This is a warning."
70014040-85 = "……Don't worry, I won't kill them."
70014040-86 = "I won't kill them."
70014040-92 = "Y-you!? #nIt's Kai! Shintani Kai is—!!"
70014040-93 = "I-I can't breathe—! #nIt's... suffocating...!"
70014040-94 = "Hah, hah!? M-my whole body, it's itching—! Aaaaaaaah—!!!"
70014040-99 = "S-stop... I can't... take any more—!!"
70014040-100 = "Hallucinations...? #nS-stay back! Don't come any closer—!!!"
70014040-105 = "It's rain...! Ah! It's rain...!"
70014040-106 = "It feels like... my body is melting! My legs...! My arms...! My hair...!!!"
70014040-107 = "Gaaaaaaaaaaaaaaaaaaaaah!!!!!"
70014040-111 = "[ns] \"Kai. What was that just now...?\""
70014040-112 = "As you can see."
70014040-113 = "……."
70014040-114 = "They're all safe, aren't they? #n...On the outside, at least."
70014040-115 = "[s] \"That may be true, but...!\""
70014040-116 = "Don't worry."
70014040-117 = "I don't do things that can't be undone. #n...Unless something truly extreme happens."
70014040-118 = "Kai...?"
70014040-119 = "……!"
70014040-120 = "……."
70014040-121 = "Let's go home. The sun has already set."
70014040-125 = "……Yeah."
70014040-131 = "Are you hurt?"
70014040-132 = "……I think that's my line."
70014040-133 = "Ho ho ho... I'm fine, perfectly fine. I am a resident of this place, after all."
70014040-135 = "(The conversation between Kai and the old woman continued naturally, without interruption.)"
70014040-136 = "(I listened to the two of them in silence.)"
70014040-138 = "Is it already this late...?"
70014040-139 = "I think I'll go get some rest."
70014040-140 = "You two shouldn't stay up too late either."
70014040-141 = "……We will."
70014040-145 = "(The old woman returned to her room, dragging her feet, though she seemed a bit lighter than before.)"
70014040-146 = "(...Before long, the sound of steady breathing could be heard.)"
70014040-147 = "……."
70014040-148 = "[s] \"She's a strong person.\""
70014040-149 = "……Well, I suppose so."
70014040-150 = "[s] \"Are you okay?\""
70014040-151 = "……That's a strange thing to ask."
70014040-152 = "Shouldn't you be asking that of those thugs from earlier?"
70014040-153 = "[s] \"But you have a complicated look on your face.\""
70014040-154 = "……!"
70014040-155 = "……."
70014040-159 = "How should I put this..."
70014040-160 = "……I'm not used to this."
70014040-161 = "[s] \"Helping the old woman?\""
70014040-162 = "……!"
70014040-163 = "……It's useless to try and deceive Sensei with something like this."
70014040-164 = "But I didn't act based on some moral compass of 'doing good'."
70014040-165 = "I simply acted as my heart desired, and this was the result."
70014040-166 = "……Just as I did throughout the day today."
70014040-167 = "[s] \"That's fine, too.\""
70014040-168 = "What...?"
70014040-169 = "[s] \"You don't have to be a good person to do good things.\""
70014040-170 = "I find that hard to understand."
70014040-171 = "[s1] \"Sometimes, just going with the flow is important too.\"\n[s2] \"All's well that ends well, right?\""
70014040-174 = "Is it really? With that kind of thinking?"
70014040-175 = "[s] \"At least for now, yes.\""
70014040-176 = "……!"