[translation]
70013010-1 = "Uma erva daninha não floresce sozinha (1)"
70013010-2 = "Salão do restaurante fino do hotel"
70013010-6 = "..."
70013010-7 = "... Finalmente."
70013010-8 = "Chegamos!"
70013010-9 = "Restaurante de hotel de altíssimo padrão...!"
70013010-14 = "C-comer num lugar desses com a Aru-sama... agora posso morrer sem arrependimentos!"
70013010-15 = "Aru-chan, tem certeza? Aqui parece ser caro pra dedéu, hein?"
70013010-17 = "Podem ficar tranquilas, hoje eu pago. Além disso, ultimamente minha renda tem se estabilizado."
70013010-18 = "... Dito isso, acho melhor não abusar."
70013010-19 = "I-isso daqui é tranquilo!"
70013010-20 = "Ultimamente tenho até conseguido guardar dinheiro."
70013010-21 = "Como presidente, tenho que fazer isso de vez em quando."
70013010-22 = "Então, aproveitem o dia de hoje."
70013010-24 = "Kufufu, já que você diz assim, a gente vai ter que se divertir né~"
70013010-25 = "Só para saber, fez a reserva direitinho?"
70013010-27 = "Ah, claro!"
70013010-28 = "Hmm, com licença."
70013010-29 = "Bem-vindos."
70013010-30 = "É do Rikuhatsuma..."
70013010-34 = "Estávamos aguardando. Por aqui, por favor."
70013010-46 = "Por favor, sentem-se à mesa perto da janela."
70013010-56 = "Então, vou explicar rapidamente o menu de hoje."
70013010-57 = "O prato principal é um filé de vitela cozido ao estilo Wild Hunt, especialidade do chef."
70013010-58 = "É cozido em um molho deglaceado com vinho de acidez suave e o suco da carne."
70013010-59 = "Para que se perceba um sabor rico e profundo..."
70013010-66 = "O garçom continuou a explicação, mas –"
70013010-73 = "Infusão, al dente, brunoise... palavras que Aru e as outras não estavam acostumadas a ouvir."
70013010-74 = "A-ah, sim! Tudo parece delicioso!"
70013010-75 = "Então, vou trazer a amuse-bouche."
70013010-81 = "Aru-chan, você tá entendendo alguma coisa?"
70013010-82 = "Quer dizer que é comida de primeira linha, né?"
70013010-83 = "Não precisa se preocupar com detalhes. É caro, então tudo deve ser gostoso."
70013010-88 = "Aliás, até a água... é diferente, né."
70013010-89 = "... É água mineral."
70013010-90 = "Q-que tipo de pessoa costuma comer num lugar desses?"
70013010-100 = "Uau! Gente, todo mundo parece super rico~"
70013010-101 = "Nós também estamos aqui como clientes, não precisamos nos comparar com os outros."
70013010-102 = "E o código de vestimenta também está perfeito –"
70013010-103 = "Não exageraram um pouco?"
70013010-104 = "N-nada disso...!"
70013010-105 = "Não está perfeito para uma refeição elegante?"
70013010-106 = "Kufufu. Então a Aru-chan também sabe todas as etiquetas, né?"
70013010-107 = "Então, uma pergunta. Você sabe a ordem de usar a faca e o garfo?"
70013010-108 = "E-eu também queria saber. Por que tem tantos tipos?"
70013010-109 = "O quê... i-isso é..."
70013010-111 = "Cada prato usa um talher diferente."
70013010-112 = "... Mas não sei qual usar primeiro."
70013010-113 = "Q-qualquer um serve, né? O importante é comer."
70013010-120 = "Que barulheira é essa?"
70013010-121 = "Parece que tem uns peixes fora d'água por aqui..."
70013010-123 = "Hmm? Tá falando da gente?"
70013010-124 = "Foi... foi você que insultou a Aru-sama agora?"
70013010-126 = "Aru?"
70013010-130 = "..."
70013010-131 = "V-vocês são...!"
70013010-132 = "Empresa de Conveniência 68!!"
70013010-137 = "Hmm... quem é você?"
70013010-142 = "Vocês... me esqueceram!?"
70013010-143 = "Vilão é tudo igual, né~?"
70013010-144 = "Não vou lembrar de todos."
70013010-145 = "Sou da Família Rigatoni! Bruno Rigatoni!"
70013010-146 = "Não me diga que esqueceram esse nome!"
70013010-151 = "Família... Rigatoni...?"
70013010-152 = "... Não acredito."
70013010-153 = "Agora que você falou..."
70013010-155 = "F-fufu..."
70013010-156 = "Fuhahahaha...!"
70013010-157 = "Parece que finalmente se lembraram!"
70013010-158 = "Hora da vingança! Vamos nessa, pessoal!!"
70013010-167 = "Lutar num lugar desses? Tá doido?"
70013010-168 = "Eu paguei uma nota aqui, viu! Vão fechar os olhos para o que eu fizer!"
70013010-169 = "A essa altura, é briga de morte –"
70013010-170 = "Vou cobrar a conta daquela vez!"
70013010-171 = "Acabem com eles!"
70013010-183 = "Kyaha! Que recepção animada."
70013010-184 = "Presidente, o que fazemos?"
70013010-185 = "Se quebrarmos as coisas daqui, a senhora vai pagar?"
70013010-186 = "U-uh... mas –"
70013010-187 = "– Se a gente fugisse agora, não seria hard-boiled!"
70013010-188 = "Pessoal, comecem o contra-ataque!"
70013010-189 = "Essa é a Aru-chan! Assim que se faz!"
70013010-190 = "D-deixem comigo, Aru-sama. Vou acabar com todos eles..."
70013010-203 = "De repente, começou um tiroteio no restaurante."
70013010-204 = "O que terá acontecido entre a Empresa de Conveniência 68 e a Família Rigatoni?"