[translation]
80000037-1 = "心のこもったご褒美を"
80000037-2 = "（便利屋68に舞い込んだ依頼を一緒に解決した後の、アルとの帰り道……）"
80000037-3 = "今日もお疲れ様、先生。"
80000037-4 = "[s] \"うん、アルの方こそ。\""
80000037-5 = "最初はどうなるかと思ったけれど、やっぱり先生と私は最高のパートナーね。"
80000037-6 = "私たちが颯爽と現場に着地した瞬間の、あいつらの顔……"
80000037-7 = "ふふっ、ゾクゾクしちゃうわね♪"
80000037-8 = "今日の依頼も完璧に解決したことだし、便利屋68の名前はますます広がるに違いないわ！"
80000037-9 = "このまま行けばゲヘナの全校生徒が、いえ、最終的にはキヴォトスのありとあらゆる生徒たちが、「便利屋68」と聞いただけで震えあがる……そんな日もそう遠くないわね？"
80000037-10 = "[s] \"確かに、そうかもね。\""
80000037-11 = "ふふっ、やっぱりそうよね！"
80000037-12 = "ああ、でもあんまり急に名前が広がると、それはそれで困っちゃうかもしれないわね……。"
80000037-13 = "「便利屋68」がすごすぎる存在になって、誰も近づけなくなったら困るじゃない？"
80000037-14 = "お金さえあれば何でも受けてくれる、危なそうでかつ大事な時に頼りがいがあるのが便利屋……それをモットーにしていきたいのだけど、"
80000037-15 = "「誰も近づけさせないほどの威厳」を備えたら本末転倒。"
80000037-16 = "難しいわね……アウトローの流儀というのは、やはり孤独な道なのかしら……。"
80000037-17 = "まあ、それもそれで悪くないわね！えぇ！"
80000037-18 = "ふふっ……。"
80000037-19 = "……。"
80000037-21 = "（い、今もしかして良い雰囲気かしら！？カッコよい感じなんじゃないかしら！？）"
80000037-22 = "じゃあ、自画自賛はこれくらいにして……。"
80000037-23 = "[s] \"自画自賛って言っちゃった……。\""
80000037-24 = "そ、それは良いの！せっかくの良い雰囲気を壊さないで！"
80000037-25 = "と、とにかく我々便利屋68のパートナーである先生のために、その、特別に用意したものがあって……。"
80000037-30 = "[ns1] \"チョコレート……！\"\n[ns2] \"これ、バレンタインデーのプレゼントだと思っても良い？\""
80000037-31 = "ご、誤解しないで！これはその、えっと……。"
80000037-32 = "ご、誤解しないで！これはその、えっと……。"
80000037-33 = "そ、そう！あくまで報酬の一環よ！"
80000037-34 = "日頃から頑張ってもらってる先生のために用意した、「超」が5個は付くような「最高級チョコレート」よ。"
80000037-35 = "ふふっ、ブラックマーケットでも滅多に手に入らないものなんだから。じっくり味わいなさいね？"
80000037-36 = "[s] \"うん、ありがとう！\""
80000037-37 = "え、えぇ、そうよね。まあ先生なら、そうやって分かりやすく喜んでくれると思っていたけれど……。"
80000037-38 = "（こ、ここまでダイレクトに伝えられると、何だか……！）"
80000037-39 = "[s] \"……あれ？\""
80000037-40 = "どうしたの、先生？"
80000037-42 = "さぁさぁご注目！本日はバレンタインデー、ということであの「最高級チョコレート」を特別に安売りしちゃいますよー！"
80000037-44 = "どこからどう見ても上品で高級なこちらの商品！本来なら10万円で売られていてもおかしくない品ですが……"
80000037-45 = "何てことでしょう、会社で発注ミスが！こうなっては仕方ないと今回の大セールに至りました！ネットでは相変わらず定価で売っているみたいですし、逆に考えると今のうち！"
80000037-46 = "あまりにも仕入れすぎちゃったので、もう色んな事を諦めて何と「95%OFF」で販売！"
80000037-47 = "もう倉庫代が浮けば良いです、"
80000037-48 = "さぁ今こそこの「高級チョコレート」を手軽に買えるチャンス！"
80000037-49 = "早い者勝ちですよー！"
80000037-51 = "[ns] \"わぁ……。\""
80000037-52 = "ちょっ、ちょっとちょっと！どういうことよ！？"
80000037-53 = "インターネットで質問したら、「高いけどめちゃめちゃ良い」ってみんなが言ってたから……"
80000037-54 = "先生へのプレゼントならこれしか無いって思って……"
80000037-55 = "すっごく悩んだ末に、頑張って買ったのにぃ！？"
80000037-56 = "[s] \"そっか……。\""
80000037-57 = "こ、これはもしかして詐欺……！！"
80000037-58 = "[s3] \"アル、一旦落ち着いて……。\"\n[s4] \"あのチョコと一緒じゃないよ。これはアルがプレゼントしてくれたんだから。\""
80000037-59 = "そ、そうね……結局物の価値というのは、あくまで相対的なもの……。"
80000037-60 = "そ、そうね……結局物の価値というのは、あくまで相対的なもの……。"
80000037-61 = "何より大事なのはあげる側ともらう側の気持ち。"
80000037-62 = "ふふっ。私としたことが、大事なことを見失うところだったわ。"
80000037-63 = "まあ、ショックはまだ癒えないけれど……"
80000037-64 = "先生もそう言ってくれたことだし。"
80000037-65 = "悔しいけれど、"
80000037-66 = "もう買ってしまったのだから……。"
80000037-67 = "仕方、な……。"
80000037-68 = "……仕方ないわけないでしょう！？"
80000037-69 = "それはそれ、これはこれ！私は納得できない！"
80000037-73 = "ふふっ……私がいつまでもやられっぱなしだと思ったら大間違いよ。"
80000037-74 = "信頼には信頼で、仕打ちには仕打ちで！やられた分はきっちりやり返すのが、便利屋68のモットーだもの！"
80000037-75 = "[s] \"次々と増えていくモットー……。\""
80000037-76 = "まずはWebサイトを検索して本社の位置を特定、そこを襲撃するために……。"
80000037-77 = "[s] \"あの、アルさん……？\""
80000037-78 = "よし、決めたわ！さあ行くわよ先生。次の活動は決まったわ。"
80000037-79 = "それにそもそも便利屋68では、オフィスに帰る前までが依頼！"
80000037-80 = "だから、このまま付き合ってくれるわよね？先生？"
80000037-81 = "[s] \"うん、アルの頼みなら。\""
80000037-82 = "ふふっ、やっぱり先生はそうじゃないと！"
80000037-83 = "さあ見ておきなさい、先生。私のアウトローな大活躍を！"
80000037-85 = "（その後アルと一緒にハードボイルドな展開を共にすることになるのだけれど、それはまた別のお話）"
