[translation]
80000119-1 = "Espírito de Competição Ardente"
80000119-2 = "（Enquanto trabalhava até tarde da noite...）"
80000119-9 = "[ns] \"……？\""
80000119-12 = "[ns1] \"……Quem está aí?\"\n[ns2] Organizo o ambiente ao redor."
80000119-15 = "Você não se assustou."
80000119-16 = "Por acaso... você já está acostumado?"
80000119-19 = "[ns3] \"……Shiroko?\"\n[ns4] \"O que houve?\""
80000119-22 = "Hum... surpresa fracassada."
80000119-23 = "Hm?"
80000119-24 = "O motivo de eu ter vindo a esta hora?"
80000119-25 = "……Fufu."
80000119-26 = "Você se preocupa mais com o motivo do que com o fato de eu ter vindo."
80000119-27 = "Ah, mas... o Sensei sempre foi assim."
80000119-28 = "Nesse aspecto, você é realmente desligado."
80000119-33 = "[ns5] \"Ah, isso é...\"\n[ns6] \"……Desta vez tem mais, né?\""
80000119-36 = "Hum... achei que você lembraria."
80000119-37 = "Desta vez, preparei uma quantidade maior."
80000119-38 = "Está tudo bem. Agora eu consigo fazer várias coisas."
80000119-39 = "……？"
80000119-40 = "A mesma coisa... daquela Shiroko também...?"
80000119-41 = "Hee, é mesmo...?"
80000119-45 = "[ns7] \"Por acaso...\"\n[ns8] \"Vocês estão competindo...?\""
80000119-48 = "……Competindo?#nDe jeito nenhum."
80000119-49 = "Eu só sei exatamente o que aquela Shiroko faria."
80000119-50 = "Além disso, nossas posições são diferentes, então não tem como competir."
80000119-51 = "――Mesmo com chocolates, eu sou mais forte."
80000119-52 = "[s9] \"……Você está definitivamente levando isso a sério!\"\n[s10] \"Não entrem nessa disputa estranha!\""
80000119-55 = "……Fufu."
80000119-56 = "Obrigada por continuar sendo o Sensei de sempre."
80000119-57 = "……Já terminei o que tinha que fazer, então vou indo."
80000119-58 = "[s11] \"Você acabou de chegar, não foi?\"\n[s12] \"Poderia ficar um pouco mais...\""
80000119-61 = "Hum, se precisar de algo, entre em contato."
80000119-62 = "Serei sempre bem-vinda."
80000119-63 = "Mas――"
80000119-64 = "Hoje... achei que seria mais reconfortante se eu viesse te ver."
80000119-65 = "……Hum."
80000119-66 = "O Sensei é esse tipo de pessoa."
80000119-67 = "Eu estou bem, então não se preocupe."
80000119-68 = "……Sou uma boa aluna, não sou?"
80000119-69 = "[s13] \"Você pensou nisso tudo...\"\n[s14] \"Shiroko, você é uma boa menina.\""
80000119-72 = "……Fufu."
80000119-73 = "É difícil vir todo dia, mas..."
80000119-74 = "Eu virei ao Schale novamente."
80000119-75 = "Sensei... até mais."
80000119-77 = "（Shiroko abriu um sorriso radiante e foi embora sem nem me dar tempo de me despedir）"
80000119-78 = "（……A grande quantidade de chocolates que recebi dela serviu de companhia para o meu trabalho de restauração do escritório）"
