[translation]
80000067-1 = "Se você se importar, você perde."
80000067-2 = "（Recebi uma mensagem da Neru e vim até o campus da Millennium）"
80000067-3 = "Ei, Sensei!"
80000067-4 = "[s1] \"...Neru?\"\n[s2] Viro-me na direção de onde veio o som."
80000067-8 = "Você foi rápido. Na verdade, desculpe por ter te feito esperar."
80000067-9 = "Ah, assunto? Ah, bem, sobre isso... não, entrar nesse assunto de repente é..."
80000067-10 = "Bem, não é nada demais. Não crie tantas expectativas."
80000067-11 = "É que, eu só..."
80000067-15 = "Não, bem, eu acho que o Sensei vai gostar. Eu escolhi um incrível."
80000067-16 = "...Toma, pega logo!"
80000067-21 = "[ns3] \"I-isso é...?\"\n[ns4] \"Que formato incrível...!?\""
80000067-22 = "E aí, ficou surpreso!?"
80000067-23 = "E aí, ficou surpreso!?"
80000067-24 = "É legal, né? Digo, não é bom? Cara, deu um trabalhão achar isso. Em todo lugar que eu ia, só tinha coisa sem graça."
80000067-25 = "...Ah? O que é isso, você pergunta?"
80000067-26 = "Você não sabe, Sensei? Hoje é Dia dos Namorados, não é?"
80000067-27 = "Você está tão ocupado a ponto de esquecer disso? Como sempre, sua vida é difícil, hein. Bem, eu me lembrei por você."
80000067-28 = "...Eh, não é esse o sentido? ...O design?"
80000067-29 = "Ah... será que faltou impacto? Bem, olhando de novo, talvez pudesse ser um pouco maior mesmo."
80000067-30 = "Ou então, talvez uma escultura..."
80000067-31 = "...Ah?"
80000067-32 = "O significado do Dia dos Namorados?"
80000067-33 = "É o dia de dar chocolate, não é? Tem algum outro significado?"
80000067-34 = "[s5] \"...Não, não se preocupe. Obrigado.\"\n[s6] \"De qualquer forma, é legal e bonito.\""
80000067-35 = "Haha, isso mesmo. Não se preocupe com detalhes, é só aproveitar."
80000067-36 = "Haha, isso mesmo. Não se preocupe com detalhes, é só aproveitar."
80000067-37 = "Ah, mas enfim, vamos abrir logo."
80000067-38 = "Eu estava curiosa para saber qual é o gosto."
80000067-39 = "[s7] \"Isso é ótimo, mas...\"\n[s8] \"...Tem certeza?\""
80000067-40 = "...Ah, o que houve?"
80000067-41 = "...Ah, o que houve?"
80000067-42 = "Você não vai dizer que não quer, né? Fui eu que comprei, então está tudo bem, não está?"
80000067-46 = "Anda, senta logo! Vamos comer!"
80000067-47 = "[s] \"...\""
80000067-49 = "（Depois disso, dividi o chocolate com a Neru enquanto sentíamos os olhares das pessoas ao redor）"
80000067-50 = "（Embora o sabor fosse bom, acabei me preocupando mais com o design e outras coisas）"
