[translation]
80000099-1 = "Ovo termal?"
80000099-2 = "（O local onde Meg me chamou era um beco longe da área comercial）"
80000099-3 = "Hehe. Estava te esperando, Sensei!"
80000099-4 = "[s1] \"Meg?\"\n[s2] \"O que está fazendo em um lugar como este?\""
80000099-9 = "Hehe~! Não se surpreenda com o que vou dizer!"
80000099-10 = "Hoje é um dia muito, muito especial!"
80000099-11 = "Bem, acho que o Sensei já deve saber! Diferente de mim, você é inteligente!"
80000099-12 = "De qualquer forma, como você sempre me ajuda, eu queria retribuir de alguma forma!"
80000099-13 = "Mas, a única coisa que sei fazer é criar fontes termais, então..."
80000099-14 = "Quebrar, cavar, esculpir... são só essas coisas que eu faço..."
80000099-15 = "Ah, claro que também sei construir, mas deixa isso de lado!"
80000099-16 = "Fiquei pensando nisso, e decidi fazer algo dentro do que eu consigo!"
80000099-17 = "Sendo assim! Aqui! Pegue!"
80000099-21 = "Nnn~!!"
80000099-26 = "[ns3] \"Isso é um ovo termal...?\"\n[ns4] \"Será que é um ovo defumado...?\""
80000099-29 = "E então, o que será?"
80000099-30 = "É uma surpresa até você descascar!"
80000099-31 = "Bem, dito isso, a única coisa que eu conseguiria fazer é um ovo termal."
80000099-32 = "Mas este aqui é um pouquinho diferente! Deve ser mais doce que um ovo comum!"
80000099-33 = "Então, Sensei! Descasque logo! #nEu também quero confirmar se ficou bom!"
80000099-34 = "Uuu~, eu também estou ficando empolgada!"
80000099-35 = "[ns] Tento descascar o ovo que recebi."
80000099-38 = "[ns5] \"Tem chocolate dentro...!\"\n[ns6] \"Não era um ovo!?\""
80000099-41 = "Tcharam!!!"
80000099-42 = "Não era um ovo termal, era um chocolate termal!!!"
80000099-43 = "Eba! Palmas, palmas!!"
80000099-44 = "Sensei, Sensei! Coma, coma!"
80000099-45 = "Rápido, rápido~!"
80000099-50 = "[ns7] \"Oh, é chocolate mesmo.\"\n[ns8] \"Isso é muito gostoso.\""
80000099-53 = "……!"
80000099-54 = "……！！！！"
80000099-55 = "Ooooooh!! Grande sucesso~!!!"
80000099-56 = "Hehe... Para ser sincera, eu estava preocupada com o que faria se não estivesse gostoso #n... Fico feliz que tenha dado certo."
80000099-57 = "……Hm? Se eu não experimentei antes?"
80000099-58 = "Sim, porque eu só fiz esse."
80000099-59 = "……Ah."
80000099-60 = "……! É verdade! Eu deveria ter feito um protótipo!"
80000099-61 = "O Sensei é realmente inteligente!! ……Hehe."
80000099-65 = "Bem, então..."
80000099-66 = "……Vou fazer outro, e dessa vez eu também vou comer!"
80000099-68 = "（Depois disso, fiz uma enorme quantidade de \"ovos termais de chocolate\" com a Meg）"
80000099-69 = "（……A ponto da geladeira do Schale ficar completamente lotada com os chocolates da Meg）"
