[translation]
80000013-1 = "Mar de chocolate"
80000013-2 = "（Enquanto patrulhava a cidade com Hoshino, descobrimos um pequeno museu oceanográfico）"
80000013-3 = "（Como os olhos de Hoshino brilhavam silenciosamente, entramos no museu, demos uma volta e saímos depois de um tempo）"
80000013-5 = "D.U. - Em frente ao Museu Oceanográfico"
80000013-6 = "Quem diria que tinha um museu oceanográfico por aqui, hein."
80000013-7 = "Não é muito grande, mas foi divertido ver tantos peixes diferentes depois de tanto tempo."
80000013-8 = "E como quase não tinha ninguém, deu para ver os peixes com calma. Uhehe."
80000013-9 = "[s] \"Fico feliz que tenha se divertido.\""
80000013-10 = "Sim. Ah... aquilo ali é a lojinha?"
80000013-14 = "Sensei, olha! É um conjunto de chocolates com motivos de peixes que estão em exposição neste museu!"
80000013-18 = "Esta aqui é uma estrela-do-mar, e esta é um baiacu..."
80000013-23 = "Será que esta é uma baleia? Oh, que fofa!"
80000013-24 = "...Ué? Mas se bem me lembro, não tinha baleias neste aquário, né?"
80000013-25 = "Por que será que tem chocolates em formato de baleia..."
80000013-26 = "[s1] \"Seja como for, talvez seja porque baleias são fofas?\"\n[s2] \"Talvez por questões comerciais...?\""
80000013-27 = "Bom, é verdade... como você disse, Sensei, baleias são criaturas fofas."
80000013-28 = "Se é para fazer chocolates fofos assim, elas são indispensáveis, né. Uhe."
80000013-29 = "Uhe, entendi..."
80000013-30 = "Essa tia aqui não entende muito dessas coisas..."
80000013-31 = "Bem, de qualquer forma, acho que não tem problema comprar um desses como lembrança."
80000013-36 = "Pronto, Sensei. Pode pegar."
80000013-37 = "Vou te dar um de lembrança também."
80000013-38 = "[s] \"O de baleia... tem certeza que posso pegar?\""
80000013-39 = "Sim, pode pegar, sem problemas."
80000013-40 = "O triste é que o gosto é todo igual, então depois que vai para a barriga, não faz diferença. Uhehe."
80000013-41 = "É claro que é verdade que o souvenir em formato de baleia é o que eu mais gosto..."
80000013-42 = "É justamente por isso que eu quero que você fique com ele, Sensei."
