[translation]
80000011-1 = "ロッカーのラブソング"
80000011-2 = "商店街・レコード屋"
80000011-9 = "あれ。「ブラック・デス・ポイズン」の限定シングル出てたんだ。"
80000011-10 = "今シーズンはほとんど新曲を出してなかったのに、急に限定シングルだなんてどうしたんだろ。見てみよう……。"
80000011-14 = "バレンタインデーを狙ったラブソング？"
80000011-15 = "今までガチガチのヘビメタ路線だった「ブラック・デス・ポイズン」が、どうしてこんなジャンルの音楽にチャレンジを……？"
80000011-16 = "うーん、まあでも好きだし……試しに買ってみるか。"
80000011-17 = "あの、このアルバムを……"
80000011-18 = "（あ、「ブラック・デス・ポイズン」の限定版アルバム『恋は心臓を撃ち抜いて手に入れるもんなんだよ』ですね。）"
80000011-19 = "（こちらのはバレンタインデーを記念した限定シングルですので、ご購入された皆様に特別なプレゼントをお渡ししています。）"
80000011-20 = "特別なプレゼント？"
80000011-21 = "（はい、購入された方には……）"
80000011-26 = "（この牛の骸骨型のチョコレートを、おまけで差し上げます！）"
80000011-27 = "……。"
80000011-28 = "（あ、あれ？どうかされましたか？）"
80000011-29 = "……いや、大きすぎて戸惑っただけ。"
80000011-30 = "（そうでしたか。では、「ブラック・デス・ポイズン」の新曲と共に、良いバレンタインデーを。）"
80000011-35 = "つい貰っちゃったけど……このチョコレート、どう処理しようか……？"
80000011-36 = "食べるには量が多いし、ここから便利屋のオフィスまで持っていくのもちょっと……。"
80000011-37 = "[s] \"やあ、カヨコ。\""
80000011-38 = "あっ、先生。"
80000011-39 = "偶然だね、先生もレコードを買いに？"
80000011-40 = "[s] \"まあそんなところ。\""
80000011-42 = "[s] \"ところで、すごい大きさのチョコレートだね。\""
80000011-43 = "ああ……好きなグループのアルバムを買ったんだけど、おまけでもらっちゃって。"
80000011-44 = "持ち運ぶにはかさばるけど、好きなバンドのおまけを捨てるのも気が進まないし、持て余してたとこで……。"
80000011-48 = "良かったら先生、これ貰ってくれない？"
80000011-49 = "[s] \"カヨコが良ければ、ありがたく。\""
80000011-50 = "良かった。むしろ先生がこのチョコレートをもらってくれなかったら、どうしようかと思った。"
80000011-52 = "あーその……今日がバレンタインデーなのは知ってるけど、特別な意味とかは無いから……。"
80000011-53 = "これは、そういうのじゃないから。分かった？"
80000011-55 = "（その後カヨコがくれた巨大な骸骨のようなチョコレートを持って、シャーレに戻った。）"
80000011-56 = "（精巧に彫刻されたチョコレートは、なんだか食べるのがもったいなくて壁に飾っておいた。）"
