[translation]
80000100-1 = "試食の心"
80000100-2 = "玄武商会"
80000100-3 = "（ルミに試食を頼まれ、玄武商会に向かった）"
80000100-4 = "あ、先生。いらっしゃい。"
80000100-5 = "さあ、こっちに。……って、もっと近くに座ってよ。"
80000100-6 = "[s] \"ごめん、ごめん。ところで、今日は何を作ってくれたの？\""
80000100-7 = "そうだね……まずはお茶でもどう？いい茶葉が手に入ったから。"
80000100-8 = "今日は腕によりをかけて色々準備しておいたからね。"
80000100-9 = "（ルミが淹れてくれた緑茶で喉を潤した）"
80000100-10 = "さて、察しのいい先生なら、お茶を用意した時点でなんとなく気づいたと思うけど……"
80000100-11 = "[s1] \"うーん……何だろう。\"\n[s2] \"何となく分かったような。\""
80000100-12 = "あはは、流石にヒントが少なかったね。たしかに、お茶だけで相手の考えが分かるなら、会話する必要なんて無くなっちゃうし。"
80000100-13 = "はい、これあげる。"
80000100-14 = "ほんと？じゃあ、先生の答えを聞かせてもらおうかな。"
80000100-15 = "……何か甘いものを用意したんじゃないかって？#nさすがだね、先生。言葉にしなくても通じ合えるなんて。"
80000100-20 = "これ？月餅だよ。"
80000100-21 = "普通の月餅とちょっと違って、チョコレートが入ってるんだ。"
80000100-22 = "[s] \"三種類とも、違うような気がする。\""
80000100-23 = "いい観察力だね。先生の言う通り、この月餅はそれぞれ違うんだ。"
80000100-24 = "1つ目は、餡を包むところまでは一緒なんだけど、表面をチョコレートでコーティングしたもの。"
80000100-25 = "2つ目は、チョコレートを包んだもの。"
80000100-26 = "最後、3つ目はちょっと他とは毛色を変えてみたんだ。"
80000100-27 = "皮を薄めにして、クリーム状のチョコレートを包んで凍らせたもの。#n名付けて、アイスチョコ月餅！"
80000100-28 = "この3つのどれが一番「チョコレート月餅」の名に[ruby=ふさわ]相応[/ruby]しいかな？"
80000100-29 = "さあ、ゆっくり味わってみて。甘すぎたら、緑茶で口直ししてね。"
80000100-31 = "（ルミに言われた通り、順番に味わってみたところ……）"
80000100-32 = "（どれも非常に美味しく、甲乙つけ難かった）"
80000100-34 = "それじゃあ、先生の答えを聞かせてもらおうかな。"
80000100-35 = "どれが「チョコレート月餅」に相応しいと思った？"
80000100-36 = "[s3] \"月餅らしさを残して表面をコーティングした一番目かな。\"\n[s4] \"ここはチョコの美味しさをたっぷり味わえる二番目かな。\"\n[s5] \"料理は挑戦って言うし、変わり種の三番目かな。\""
80000100-40 = "そっか……よし！参考になったよ。ありがとう、先生。"
80000100-41 = "[s] \"でも、試食だけじゃなくてちょっと期待もしてたんだけど……\""
80000100-42 = "……その、さ。なんというか、今日はバレンタインデーでしょ？"
80000100-43 = "だから、試食は口実だったというか……"
80000100-44 = "[s] \"え……？\""
80000100-45 = "……。"
80000100-46 = "……なんか、自分でもこういう気持ちになるとは思っていなかったんだけど。"
80000100-47 = "いざ口にすると……恥ずかしいもんだね。"
80000100-48 = "昨日、練習したときは大丈夫だったのになぁ、どうしてなんだろ……"
80000100-49 = "って、こんなこと言ったら、もっと恥ずかしくなってきた……どうしよう。"
80000100-50 = "[s6] \"……私が言うのもあれだけど。\"\n[s7] \"もう少し、遠回しに伝えるとか……？\""
80000100-53 = "それは……何か嫌で。"
80000100-54 = "その……先生には……隠し事をしたくなかったから。"
80000100-55 = "だから、全部素直に話そうって……"
80000100-56 = "まさか、こんな恥ずかしくなるなんてね……"
80000100-57 = "[s] \"……せっかくだから、一緒に食べよっか。\""
80000100-58 = "え？でもそれは、先生のために用意したんだよ？"
80000100-59 = "量が多すぎて食べ切れなさそう……？"
80000100-60 = "……。"
80000100-61 = "うん、分かった。ちょっと待ってて、お茶を用意してくるから。"
80000100-63 = "（二人で静かにチョコレート月餅を味わいながら、時々会話をした）"
