[translation]
80000127-1 = "Garotas e Snacks"
80000127-4 = "Cheguei no Schale."
80000127-5 = "[s] \"Ué. Hikari, hoje é o seu dia de turno?\""
80000127-6 = "Nanan."
80000127-7 = "Hoje é o dia de dar doces para a pessoa que eu mais gosto."
80000127-8 = "Por isso eu vim te ver."
80000127-9 = "[s] \"Não consigo nem enxergar de tanta emoção...\""
80000127-14 = "Toma, aqui está."
80000127-15 = "A mais nova, Framing Composition Tipo C, bolinha de chocolate."
80000127-16 = "Incrível, né?#nEu achei aquela que eu estava querendo, que sorte."
80000127-17 = "Com isso, a Hikari de hoje está no modo invencível."
80000127-18 = "De qualquer forma, experimenta, vai."
80000127-22 = "[ns1] \"Que legal... Obrigado, Hikari!\"\n[ns2] (Recebi a bolinha de chocolate)"
80000127-31 = "[ns] \"......\""
80000127-33 = "[ns3] \"É um desperdício comer isso sozinho...\"\n[ns4] \"Queria que alguém comesse comigo.\""
80000127-37 = "[ns] \"Hikari, você me ajuda?\""
80000127-38 = "Hã...!?"
80000127-43 = "Sim!"
80000127-45 = "(Comi o chocolate novo junto com a Hikari)"
80000127-46 = "(Ao fazer uma careta por causa da acidez, a Hikari me viu e deu uma risada muito alegre)"
