[translation]
80000019-1 = "Item de evento"
80000019-2 = "Departamento de Desenvolvimento de Jogos - Sala do Clube"
80000019-3 = "（Na sala do Departamento de Desenvolvimento de Jogos, eu estava jogando um RPG online com a Yuzu.）"
80000019-10 = "Ah, Sensei. O chefe está indo para o seu lado."
80000019-11 = "Nós dois já estamos em frangalhos, mas se conseguirmos aguentar esse ataque, devemos vencer..."
80000019-12 = "Vou preparar uma habilidade de ataque, então... por favor, cuide da linha de frente por um momento!"
80000019-20 = "Bom trabalho, Sensei!"
80000019-21 = "Graças ao Sensei, conseguimos terminar o raide de dificuldade máxima em segurança."
80000019-22 = "Eu não teria conseguido sozinha... muito obrigada por me ajudar!"
80000019-23 = "[s] \"Foi graças ao seu esforço, Yuzu.\""
80000019-24 = "N-não é verdade. Eu só consegui derrotar o chefe porque o Sensei ficou me dando buffs o tempo todo."
80000019-25 = "Além disso, o sistema desse raide de chefe não permite que uma pessoa participe sozinha..."
80000019-26 = "Primeiro, vamos dividir os espólios do raide."
80000019-28 = "Eu já tenho essa espada, e essa armadura tem um nível menor que a minha..."
80000019-29 = "Acho que não tem problema se eu te der todos os espólios de hoje, Sensei."
80000019-30 = "[s] \"Tem certeza mesmo?\""
80000019-31 = "Sim, porque o que eu queria já é outra coisa."
80000019-35 = "E-então, hum..."
80000019-36 = "S-Sensei, você poderia aceitar este item também?"
80000019-38 = "[s] \"...O que é isso?\""
80000019-39 = "É um item de chocolate especial que só pode ser obtido durante o período do evento de Dia dos Namorados."
80000019-40 = "É apenas um item de recuperação de energia, mas... eu queria te dar um chocolate assim, Sensei..."
80000019-41 = "C-claro, teria sido melhor se eu pudesse te dar um chocolate de verdade, mas... eu não tive coragem de ir comprar no meio daquela multidão lá fora..."
80000019-42 = "É só um chocolate dentro do jogo que não dá para comer de verdade, mas..."
80000019-43 = "Eu ficaria muito feliz se você cuidasse bem dele."
80000019-45 = "（Guardei com carinho o item de chocolate que recebi da Yuzu no inventário do jogo.）"
