[translation]
80000002-1 = "Erro no pedido"
80000002-2 = "Schale - \"Angel 24\""
80000002-5 = "B-bem-vindo, Sensei...!"
80000002-8 = "……Ei."
80000002-9 = "Sensei, você não gostaria de comprar um chocolate...?"
80000002-10 = "Agora, na Angel 24, se você comprar um chocolate, ganha outro de graça!"
80000002-11 = "É a chance de ficar com as duas mãos cheias (de doces)!"
80000002-12 = "[s] \"B-bem, agora não...\""
80000002-13 = "Entendo..."
80000002-14 = "Uuu... o que eu vou fazer com tudo isso..."
80000002-15 = "[s] Parece que há algum problema, então vou perguntar."
80000002-16 = "Na verdade, é que, por causa do Dia dos Namorados, eu me empolguei e fiz um pedido de chocolates, mas acabei errando a quantidade..."
80000002-17 = "Eu pensei que 20 unidades seriam o suficiente, mas acabei pedindo 20 caixas..."
80000002-18 = "Então, não tive escolha a não ser fazer essa promoção de \"leve um, ganhe outro\", mas como quase nenhum cliente vem aqui... uuu..."
80000002-19 = "Se a matriz descobrir isso, eu estou perdida..."
80000002-20 = "Se continuar assim, não só vou ficar sem mesada, como vou acabar com uma dívida astronômica para pagar o prejuízo...!?"
80000002-21 = "[s] \"Então, por que não sai e tenta vender lá fora?\""
80000002-22 = "Ah, isso é..."
80000002-23 = "C-claro, talvez venda mais do que ficando aqui esperando, mas..."
80000002-24 = "Será que vou conseguir vender tudo isso...?"
80000002-25 = "[s1] \"Tenho certeza que vai dar certo.\"\n[s2] \"Eu vou te ajudar.\""
80000002-26 = "(Uuu, será que é seguro ficar devendo um favor para o \"Sensei\", sobre quem circulam tantos boatos estranhos...)"
80000002-27 = "(Uuu, será que é seguro ficar devendo um favor para o \"Sensei\", sobre quem circulam tantos boatos estranhos...)"
80000002-28 = "(Mas não tenho outra opção, e ele não parece ser uma pessoa tão ruim assim... talvez...)"
80000002-29 = "E-então... sim, conto com você!"
80000002-31 = "(Saí com Sora e nos esforçamos para vender os chocolates.)"
80000002-38 = "(Graças ao interesse inesperado das alunas que passavam, tudo foi vendido rapidamente.)"
80000002-40 = "I-incrível, Sensei...! Mesmo com aquela quantidade toda, esgotou tão rápido!"
80000002-41 = "Além disso, acho que até algumas alunas famosas de Trinity e Gehenna apareceram..."
80000002-42 = "Quem será esse Sensei, afinal de contas...?"
80000002-43 = "[s] \"……?\""
80000002-44 = "N-nada! Não é nada!"
80000002-48 = "Independente de quem ele seja, é alguém em quem posso confiar...?"
80000002-52 = "Ei, Sensei. Na verdade, sobrou um chocolate..."
80000002-53 = "Se não se importar, você poderia aceitar?"
80000002-58 = "Ah, não! Não é nada que eu peguei da loja sem permissão ou por descuido!"
80000002-59 = "Este aqui eu comprei com meu próprio dinheiro, é um chocolate meu para você..."
80000002-60 = "Feliz Dia dos Namorados."
