[translation]
83300100500-6 = "Tenho algo que gostaria de perguntar..."
83300100500-7 = "Ah, sim!"
83300100500-8 = "Presidente, bom trabalho! Pode dizer o que precisar!"
83300100500-9 = "Não é uma ordem, então não precisa ficar tão tensa."
83300100500-10 = "Tenho a impressão de que as coisas estão mais barulhentas do que antes de eu sair."
83300100500-11 = "P-p-peço perdão! Vou resolver isso imediatamente!"
83300100500-12 = "Não, eu ainda não disse uma palavra sobre querer que você resolva..."
83300100500-13 = "Mesmo tendo acabado de terminar o treinamento de resistência ao frio, eles estão animados só porque ouviram que haverá uma festa em Gehenna..."
83300100500-14 = "Faltou consciência como membros do Comitê Disciplinar! Peço perdão!"
83300100500-15 = "Festa em Gehenna...?"
83300100500-16 = "Presidente...!"
83300100500-17 = "Ako, você descobriu alguma coisa?"
83300100500-18 = "Perguntei aos alunos e parece que, enquanto estávamos fora..."
83300100500-19 = "O Pandemonium anunciou que realizará uma festa no Dia dos Namorados!"
83300100500-20 = "Eu imaginei. Acabei de ouvir isso dela também."
83300100500-21 = "Pensando bem, eles também fizeram uma festa na mesma época do ano passado."
83300100500-22 = "Mas, sinto que este ano está tudo muito agitado... Preciso de mais informações."
83300100500-23 = "Ah... parece que o Clube de Merenda está envolvido em algo nessa 'festa de Gehenna'!"
83300100500-24 = "O Clube de Merenda...?"
83300100500-25 = "Entendido, vou seguir para o Clube de Merenda agora."
83300100500-26 = "Ako, continue reunindo mais informações por aqui."
83300100500-27 = "Sim! Pode deixar comigo!"
