[translation]
83302200500-6 = "Waaaaah! Obrigada por me salvar, Hina-san!"
83302200500-12 = "Nós derrotamos o 'monstro' por enquanto, mas..."
83302200500-13 = "O que exatamente aconteceu?"
83302200500-14 = "Bem... é que..."
83302200500-15 = "É que..."
83302200500-16 = "A Fuuka-senpai foi levada embora...!"
83302200500-17 = "Ela me disse para esperar até que ela voltasse, mas..."
83302200500-18 = "Não tínhamos muito tempo até o dia da entrega das refeições para o Pandemonium..."
83302200500-19 = "Pensei que, se não cumpríssemos o prazo, eles usariam isso como desculpa para cortar o orçamento do Clube de Merenda novamente...!"
83302200500-20 = "Juri, acalme-se. Pode me deixar organizar as coisas?"
83302200500-27 = "Resumindo o que a Juri disse..."
83302200500-28 = "Logo agora, bem perto do dia da entrega das refeições..."
83302200500-29 = "Snif... sim."
83302200500-30 = "A Fuuka foi sequestrada pelo Clube de Pesquisa Gourmet, é isso?"
83302200500-31 = "...Haa, já perdi a conta de quantas vezes isso aconteceu."
83302200500-32 = "Snif. Sim, é isso mesmo..."
83302200500-33 = "Mas você tentou fazer tudo sozinha para conseguir cumprir o prazo, não foi?"
83302200500-34 = "Então, ouvi da chefe do Departamento de Desenvolvimento de Fontes Termais que a água subterrânea do Clube de Merenda tinha efeitos incríveis..."
83302200500-35 = "E quando eu usei para fazer ovos cozidos na fonte termal..."
83302200500-36 = "Aquele 'monstro' nasceu. É essa a sequência dos fatos?"
83302200500-38 = "Uuu... snif... sim, é isso...! É tudo culpa minha...!"
83302200500-39 = "(Então a causa da Makoto ter ficado daquele jeito foi por ter comido a comida que a Juri fez...)"
83302200500-40 = "Waaaaah! Me desculpe! Hina-san! Fuuka-senpai!"
83302200500-41 = "Não, a Juri não precisa se desculpar."
83302200500-42 = "Houve alguns problemas, mas você tentou fazer o seu melhor, não foi?"
83302200500-43 = "Hina-san...!"
83302200500-44 = "...Mas, é verdade. Eu também não posso deixar a Fuuka sequestrada."
83302200500-45 = "Obrigada por me contar. Não se preocupe, vou resgatar a Fuuka agora mesmo."
83302200500-46 = "Sim! Muito obrigada! Por favor, Hina-san!"
