[translation]
84303301000-5 = "Muito obrigada...! O jogo que me esforcei tanto para criar quase acabou ferindo alguém..."
84303301000-6 = "Por que isso aconteceu...? Até ontem, todos estavam se divertindo tanto jogando!"
84303301000-7 = "O jogo não deveria ter mudado nada... A Yuzu-chan também disse que não havia problemas no código..."
84303301000-9 = "Provavelmente, é influência de uma força das trevas! Mas o ladrão nos salvou!"
84303301000-10 = "Se é um ladrão especialista em coletar informações, talvez ele saiba a resposta!"
84303301000-15 = "Sério...!?"
84303301000-16 = "Você... está bem?"
84303301000-17 = "Aliás... Aris-chan? Quem é esta pessoa...?"
84303301000-19 = "Peço desculpas pela demora na apresentação."
84303301000-20 = "Sou Seia Yurizono, do Chá das Cinco da Academia Trinity."
84303301000-21 = "Desta vez, também estou na posição de responsável pelos alunos de Trinity."
84303301000-22 = "Portanto, resolver este caso também era minha função. Por isso, não se preocupem tanto."
84303301000-27 = "...Responsável? ...O que é Chá das Cinco?"
84303301000-28 = "Hmm..."
84303301000-30 = "É o que chamam de conselho estudantil. Seria o equivalente ao Seminar aqui em Millennium."
84303301000-35 = "Então é alguém como a Yuuka!"
84303301000-36 = "Sinto que ela tem um cargo um pouco mais elevado..."
84303301000-38 = "(O motivo de eu não ter sido afetada pelo jogo deve ser porque as informações foram compartilhadas comigo de antemão.)"
84303301000-39 = "(Se eu não estivesse em alerta, teria acabado como os outros alunos.)"
84303301000-46 = "Então não é um ladrão, é o Rei dos Ladrões!"
84303301000-51 = "Aris-chan...!?"
84303301000-52 = "Provavelmente não estou em uma posição tão grandiosa quanto esperam..."
84303301000-53 = "Estou apenas fazendo o que deve ser feito. Não sou alguém de status elevado."
84303301000-54 = "Entendo...!"
84303301000-55 = "Então, no grupo do Rei dos Ladrões, existe um sábio?"
84303301000-56 = "Um sábio que vê tudo enviou o Rei dos Ladrões para nos ajudar...!"
84303301000-58 = "...Hã!?"
84303301000-59 = "É verdade...!?"
84303301000-61 = "Bem, quem sabe."
84303301000-62 = "De qualquer forma... eu testemunharei que vocês são inocentes."
84303301000-63 = "Para isso, precisamos de uma análise. Poderiam me entregar esse jogo?"
84303301000-68 = "Hã? O, o nosso jogo...?"
84303301000-69 = "Não me importo, mas... você consegue ler o código?"
84303301000-71 = "Não, eu não consigo ler. Mas conheço alguém que consegue."
84303301000-75 = "...O tal \"sábio\" a quem vocês se referem."

