[translation]
90000045-4 = "Eu trouxe os dados do Binah."
90000045-5 = "Sim, confirmei. São de fato os dados do terceiro profeta de Decagrammaton, 'Binah'."
90000045-6 = "Começarei a análise agora. Bom trabalho."
90000045-7 = "[s] \"Obrigado, conto com você.\""
90000045-8 = "Foi tranquilo graças ao seu algoritmo, Chefe."
90000045-9 = "Naturalmente. Ah, a análise foi concluída. Vou exibir no monitor."
90000045-16 = "……É só isso?"
90000045-17 = "Com os dados que obtivemos desta vez, só foi possível descobrir isso."
90000045-18 = "Ainda estamos longe de ver o quadro completo, mas pelo menos demos o primeiro passo."
90000045-19 = "Uma jornada de mil milhas começa com um único passo, não é?"
90000045-20 = "Sim. Vamos continuar coletando o máximo de informações possível."
90000045-21 = "Vamos descansar um pouco antes da próxima."
90000045-28 = "O próximo destino é... as 'ruínas' nos arredores de Millennium."
90000045-30 = "Próximo episódio: 'Coleta de Dados (5) Ruínas'"
