[translation]
90000080-1 = "第9話;捜索作戦"
90000080-3 = "部長、「ケテル」の移動を捉えたよ。#n――こっちに向かってる。"
90000080-4 = "このままだと、約3分後に遭遇するよ。"
90000080-5 = "このルートもまた、手詰まりですか……。"
90000080-6 = "うん。どのルートもケテルとぶつかる。"
90000080-7 = "そもそも、こいつを引き離すなんて不可能なのかも……。"
90000080-8 = "「廃墟水没地区」の捜索……予想以上に時間がかかってしまいそうですね……。"
90000080-9 = "「かくれんぼ」にはそれなりに自信がありましたが……仕方ありません。"
90000080-10 = "先生、一旦エイミと退却してください。私は次の手を考えます。"
90000080-11 = "[s] \"わかった。\""
