#[!][Build: "1"]
#[!][Data: "20/09"]
[translation]
901010400430-6 = ""
901010400430-7 = "Resumindo o que apurei sobre a pesca e o preço dos caranguejos..."
901010400430-8 = "O preço na ponta final para o consumidor nos mercados quase não mudou, mas no cais a pesca aumentou tanto que o preço de atacado caiu vertiginosamente."
901010400430-9 = "Muitos pescadores disseram até que pretendem reduzir as saídas pro mar."
901010400430-10 = "Como assim? Não faz sentido nenhum..."
901010400430-11 = "Se o preço unitário caiu, eles não deviam vender o máximo que puderem pra compensar e lucrar no volume?"
901010400430-12 = "Ai, FOX3, você é tão ingênua pra negócios..."
901010400430-13 = ""
901010400430-15 = ""
901010400430-16 = "Fruto do mar estraga num piscar de olhos! E a demanda do público não sobe da noite pro dia. #nSe pescar demais sem comprador, o prejuízo é certo."
901010400430-17 = "Ficar queimando preço à toa só destrói o valor da mercadoria."
901010400430-18 = "Ah, tá bom, dona sabichona dos mares."
901010400430-20 = "Em suma, a flutuação de preços colocou os pescadores numa sinuca de bico."
901010400430-21 = "E com o rumor do \"Caranguejo de Tambor de Óleo\", a aversão popular ao caranguejo só vai piorar."
901010400430-22 = "Mas quem ganha com isso afinal? #nQue ligação isso tem com o preço do pescado?"
901010400430-23 = ""
901010400430-25 = ""
901010400430-26 = ""
901010400430-29 = ""
901010400430-30 = "Mas quem ganha com isso afinal? Que ligação isso tem com o preço do pescado?\n[as1] Quem lucraria se o preço despencasse de vez.\n[as2] Quem lucraria se o preço disparasse lá no alto.\n[as3] Provavelmente alguém sem relação nenhuma com o preço."
901010400430-31 = "A gente já não falou sobre isso antes? #nSeria algum comerciante querendo comprar a preço de banana."
901010400430-32 = "Claro que um custo de aquisição menor aumenta a margem, mas..."
901010400430-33 = "Um boato monstruoso desses destrói a própria demanda de consumo! #nA longo prazo seria um tiro no pé."
901010400430-34 = "Além disso, se os barcos pararem de pescar, a oferta diminui e o preço não vai cair mais."
901010400430-35 = "Hum... será?"
901010400430-36 = "Sensei, você realmente acha que essa teoria faz sentido?"
901010400430-37 = ""
901010400430-39 = ""
901010400430-40 = ""
901010400430-43 = "Como assim? Se a tendência com esse boato é o preço despencar ainda mais, de onde você tirou essa ideia?"
901010400430-44 = "Sensei... por acaso você tava dormindo de olho aberto enquanto a gente explicava?"
901010400430-45 = "Pensa com mais carinho, por favor."
901010400430-46 = ""
901010400430-48 = ""
901010400430-49 = ""
901010400430-52 = ""
901010400430-54 = ""
901010400430-55 = "Alguém sem relação nenhuma com o preço...? Por que diz isso?"
901010400430-56 = "...Eu concordo plenamente com o Sensei."
901010400430-57 = "Espalhar uma história difamatória dessas sabendo que vai abalar o consumo, justo quando o atacado já está no chão..."
901010400430-58 = "Indica que o autor dos boatos não tem interesses financeiros no comércio de pescados. É quase certo ser um terceiro alheio ao setor."
901010400430-59 = "Cada vez mais bizarro... Se não dá lucro nenhum, por que cargas d'água inventar calúnias sobre caranguejos?"
901010400430-60 = "...Será que o criador do boato tem alergia mortal a caranguejo?"
901010400430-61 = "Tipo, passou mal comendo um ensopado no passado e jurou vingança eterna contra toda a indústria pesqueira!"
901010400430-62 = "Qual é, Otogi, que teoria mais sem pé nem cabeça!"
