[translation]
901010400330-8 = "Olá, é o \"FOX EATS\"!"
901010400330-9 = "Não está procurando um lugar para comer?"
901010400330-15 = "Hã, é... o quê? Já tenho delivery, valeu."
901010400330-17 = "O foco do \"FOX EATS\" é delivery, mas... também fazemos divulgação de restaurantes."
901010400330-18 = "Quer saber, posso te indicar uns lugares que estão aceitando pedidos agora mesmo no Porto Kanezaki, que tal?"
901010400330-23 = "Hmm, então tá, vou aceitar."
901010400330-24 = "Quero ver qual é a recomendação do entregador."
901010400330-26 = "Bom... agora mesmo, o \"Aida Suisan\" é o mais recomendado!"
901010400330-27 = "Eles recebem caranguejo fresco todo dia e dá pra comer vários pratos diferentes."
901010400330-32 = "Esse lugar... não é o que a gente estava olhando agora?"
901010400330-33 = "Desculpa, mas esse restaurante... não vai rolar. Não sou muito fã de caranguejo."
901010400330-35 = "É alergia a crustáceo?"
901010400330-36 = "Não... é que caranguejo dá um trabalho danado pra comer, né?"
901010400330-37 = "E além disso, ultimamente tem história de caranguejo atacando as pessoas..."
901010400330-38 = "Meio que... ver a pinça do caranguejo me dá agonia."
901010400330-40 = "Pois é. Por que caranguejo é tão chato de comer, hein?"
901010400330-42 = "Talvez porque ele seja gostoso demais? Tipo, pra se proteger."
901010400330-43 = "E então, que tal um prato com carne de caranguejo já desfiada?"
901010400330-48 = "Carne de caranguejo desfiada?"
901010400330-49 = "Isso. Afinal, ficar quebrando a casca toda hora demora muito."
901010400330-50 = "Que tal um Tenshinhan (omelete de arroz) com caranguejo de verdade? E o croquete de creme de caranguejo com bastante manteiga também é muito recomendado!"
901010400330-51 = "Aí sim! Isso aí eu como tranquilo!"
901010400330-52 = "E justo hoje eu estava a fim de uma comidão mais gordurosa."
901010400330-53 = "Vamos almoçar nesse restaurante então!"
901010400330-62 = "B-bem-vindos! Quantas pessoas?"
901010400330-64 = "Duas pessoas~"
901010400330-71 = "Tem uma mesa pra quatro aqui?"
901010400330-72 = "Desculpa, três porções de chahan de caranguejo, pra viagem, por favor!"
901010400330-76 = "S-sim! Um momento, por favor!"
901010400330-77 = "Mas o que está acontecendo? Até agora não tinha vindo ninguém, e de repente..."
901010400330-78 = "Aqui é o restaurante especializado em caranguejo recomendado pelo \"FOX EATS\", o \"Aida Suisan\", correto?"
901010400330-79 = "Todo mundo recomenda esse lugar pra comer pratos deliciosos de caranguejo..."
901010400330-80 = "Sim, aqui é o Aida Suisan, mas... \"FOX EATS\"?"
901010400330-84 = "... Não pode ser, aquela moça que entregou os panfletos mais cedo?"