#[!][Build: "1"]
#[!][Data: "20/09"]
[translation]
901010600130-7 = ""
901010600130-8 = "Com licença!"
901010600130-9 = "Desculpe atrapalhar a faina. Que tal um energético bem geladinho para dar um gás?"
901010600130-10 = ""
901010600130-12 = ""
901010600130-13 = "Opa, não é a garota das entregas do outro dia?"
901010600130-14 = "Salvou meu dia de novo, garota! Muito obrigado, vou beber já!"
901010600130-15 = "Hihi, não esquece de deixar cinco estrelas pro FOX EATS, hein!"
901010600130-16 = "A propósito... acabei ouvindo uma conversa com o marinheiro mais velho ali do lado..."
901010600130-17 = "Ele comentou que o Miya... o rapaz novato da tripulação sumiu..."
901010600130-18 = "Ai, ai... O velho rabugento voltou com aquela mesma ladainha de novo..."
901010600130-19 = "Esquenta com isso não, moça. Na vida de marinheiro, gente largando o barco é mato."
901010600130-20 = "Acontece com tanta frequência assim?"
901010600130-21 = "Pois é... Tem gente que corre porque o balanço do mar embrulha o estômago, mas..."
901010600130-22 = "O Miyaguchi não era frouxo que nem o velho fala, não. Ele reclamava de boca cheia, mas na hora do trampo pegava pesado de verdade."
901010600130-23 = "Pra ser bem sincero com você... Eu acho que ele se mandou foi por causa de dívida braba de jogo."
901010600130-24 = ""
901010600130-26 = ""
901010600130-27 = "Dívida de jogo?"
901010600130-28 = "É. Tem muita gente que entra na pesca pesada justamente pra quitar empréstimo atrasado."
901010600130-29 = "O trabalho é uma desgraça de cansativo, mas a diária compensa se souber economizar."
901010600130-30 = "Só que o Miyaguchi se meteu com apostas clandestinas. Em vez de abater a conta, a dívida foi virando uma bola de neve..."
901010600130-31 = "E no desespero, o tanso foi pedir arrego pros agiotas da \"Família Carpaccio\"..."
901010600130-33 = "Família Carpaccio?"
901010600130-34 = "É. Já deve ter visto aqueles brutamontes de terno preto vigiando a guarita do portão principal, né? São eles."
901010600130-35 = ""
901010600130-39 = "É uma máfia antiga e bem temida por esses lados. Oficialmente eles fazem a segurança privada do porto."
901010600130-40 = "Mas por baixo dos panos emprestam dinheiro a juros extorsivos pra quem tá no bico do corvo."
901010600130-41 = "Como é que um viciado em aposta que nem o Miyaguchi ia pagar uma taxa daquelas? #nCom certeza deu no pé antes que viessem cobrar o coro dele."
901010600130-42 = "Então era essa a história toda por trás..."
901010600130-43 = "É isso aí. Vê se não vai inventar de mexer com jogo de azar, ouviu bem?"
901010600130-44 = "E agiota nem pensar, é pedir pra desgraçar a vida."
901010600130-45 = "Pode deixar, vou guardar o conselho com carinho!"
