[translation]
901010800230-11 = "Isso é..."
901010800230-15 = "Fufu, parece que acertamos na sorte."
901010800230-19 = "Aqui FOX2, encontrei alguns dados interessantes na área de descarga da saída."
901010800230-20 = "Um deles é a lista de membros que trabalham neste depósito, e o outro é o detalhamento das vendas, registrando o fluxo de caixa da filial."
901010800230-24 = "– Para entender os objetivos da organização, o jeito mais rápido é olhar o livro de vendas."
901010800230-25 = "Bom trabalho, FOX2. Copie os dados e envie para cá."
901010800230-26 = "Sim, rapidinho."
901010800230-27 = "FOX2. No detalhamento das vendas, há algum registro chamativo? Tipo transações suspeitas."
901010800230-28 = "Hmm, nada muito chamativo, mas..."
901010800230-29 = "O que me chama a atenção é que parece que eles estão reduzindo os gastos ultimamente."
901010800230-30 = "Trocaram os doces dos membros por bolachas mais baratas, e não compraram as munições periódicas."
901010800230-31 = "De repente ficaram sem grana?"
901010800230-32 = "Não, a quantia total aumentou em relação aos anos anteriores."
901010800230-33 = "Talvez estejam planejando gastar uma grana alta."
901010800230-34 = "E mesmo assim compram caranguejos que não vão comer... que coisa suspeita."
901010800230-40 = "Aqui FOX3."
901010800230-41 = "FOX2. Os dois membros com quem você conversou há pouco no portão dos fundos, Tango 3 e Tango 4, se movimentaram da posição designada."
901010800230-42 = "Podem estar indo para a administração. Saia daí rápido."
901010800230-43 = "Mas ainda não terminei de copiar os dados –"
901010800230-47 = "FOX2, alguém está indo na sua direção. Cuidado."
901010800230-48 = "...!"
901010800230-57 = "Ei, a porta está aberta?"
901010800230-63 = "Quem está aí!"
901010800230-71 = "Olá! É o FOX EATS!"
901010800230-72 = "... FOX EATS?"
901010800230-73 = "Ah, capo, é aquele que o senhor falou outro dia. O serviço de delivery que estão comentando por aqui."
901010800230-74 = "Deve ser o entregador."
901010800230-75 = "Não pedimos nada disso! O que uma pessoa de fora está fazendo no nosso escritório?"
901010800230-76 = "Ei, você aí! É espião de outra família?"
901010800230-78 = "Ah, bem..."
901010800230-82 = "Desculpem-meee, vim fazer uma entrega, mas não tinha ninguém na entrada."
901010800230-83 = "Achei que se deixasse lá fora ia estragar, então entrei para procurar alguém."
901010800230-84 = "É mesmo? A segurança do portão principal deixou você entrar?"
901010800230-85 = "Hmm... não tinha ninguém no portão principal?"
901010800230-86 = "Xiii, os caras estão matando serviço de novo."
901010800230-87 = "E então, quem pediu o quê?"
901010800230-88 = "Vejamos... duas porções de inarizushi!"
901010800230-89 = "Acho que pediram para um lanche noturno. Inarizushi não pesa no estômago, é ideal."
901010800230-90 = "Alguém aí pediu inarizushi?"
901010800230-92 = "Vamos ver..."
901010800230-94 = "Tá bem. Deixa o inarizushi aí."
901010800230-95 = "Na próxima vez que entrar sem permissão, não vai ter moleza!"
901010800230-96 = "Sim! Obrigado pela preferência!"